### ISSUE TITLE
[华农兄弟] 华农兄弟兄弟家的枇杷熟了他也不摘我们去摘一点来吃 - https://youtu.be/CQaKJafd_ts

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1003]
https://youtu.be/CQaKJafd_ts
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 4, 2020 at 06:30PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/CQaKJafd_ts

#华农兄弟：兄弟家的枇杷熟了，他也不摘，我们去摘一点来吃
#Huanong Brothers: My buddy's loquats is now ripe. But he leave them on the tree. Let's pick some for ourselves.

0:00:00.000,0:00:01.940
# 大家好  今天去摘點這個
Hi everyone! Today we're gonna pick some, you know,

0:00:02.440,0:00:04.100
# 這個枇杷哦  這是兄弟家的
some loquats. They are at my buddy's place.

0:00:04.100,0:00:05.980
# 你看  我們都跑到廣東這邊來的
Look! We've come to Guangdong.

0:00:07.380,0:00:09.040
# 你看  這棟房子就是兄弟家的
Look! This is my buddy's flat.

0:00:09.160,0:00:10.840
# 以前我們跟他都是鄰居來的
We used to be neighbours.

0:00:11.140,0:00:12.840
# 他現在都搬到廣東這邊來啦
But now he has moved here to Guangdong.

0:00:13.580,0:00:14.860
# 你看  他家的枇杷果
Look! These are his loquats.

0:00:15.440,0:00:16.600
# 那麼多他都不摘
There are so many, but he's not picking them.

0:00:17.020,0:00:18.900
# 剛好今天他不在喲  我幫它摘
It just so happens that he's not around today. I can help him.

0:00:20.020,0:00:20.820
# 一樹都是
They're all over the tree.

0:00:31.060,0:00:32.260
# 哇  這個樹好上
Wa! What an easy climb!

0:00:33.040,0:00:34.780
# 直接踩上來都就可以了啦
Step on it, and I'm in right away.

0:00:38.960,0:00:40.640
# 摘多一點回去
Pick more, won't you?

0:00:41.320,0:00:41.820
# 接著
Catch it!

0:00:43.820,0:00:45.200
# 啊  沒有接到
Ah! I couldn't.

0:00:46.620,0:00:47.520
# 沒接到哇
You couldn't catch?

0:00:47.560,0:00:49.600
# 嗯  我還沒過來呢
Um! I'm still coming , you know.

0:00:50.520,0:00:51.500
# 看  看到沒有
Can, can you see it now?

0:00:51.900,0:00:52.620
# 你看到啦
Now I can.

0:00:53.480,0:00:54.640
# 拿到啦
It's in my hands now.

0:01:32.300,0:01:33.260
# 好啦  好啦  夠啦
Alright, alright! It's enough.

0:01:33.880,0:01:35.380
# 吃到你們牙酸都有啦
There are enough to make your teeth fatigue.

0:01:45.060,0:01:46.120
# 你看  就摘了這幾個
Look! I've just picked a few here.

0:01:54.160,0:01:55.360
# 嗯  這枇杷好啦
Um! This loquat is really tasty.

0:01:59.080,0:02:00.920
# 很好肉  你看  肉是白色的
It's so rich. Look! The pulp is white.

0:02:02.580,0:02:03.760
# 啊 熟過頭啦
Ah! It's too ripe.

0:02:12.520,0:02:13.300
# 好不好看 
Does it look good?

0:02:13.860,0:02:14.780
# 帶回去哦
I'll bring them back.

0:02:15.340,0:02:16.900
# 把樹技割斷了一點
I've chopped some of the branches.

0:02:18.160,0:02:18.920
# 沒辦法
Well, anyway,

0:02:19.640,0:02:20.560
# 我太重啦
I'm too heavy,

0:02:23.420,0:02:24.660
# 我它樹枝壓斷啦
and these branches couldn't stand my weight.

0:02:26.360,0:02:27.100
# 收工  收工
Let's go, let's go!

0:02:31.080,0:02:32.980
# 這邊還有  全部撒到地上啦
Some more here. They were all splashed onto the ground.

0:02:44.540,0:02:45.140
# 走啦
Let's go!
