### ISSUE TITLE
【美食作家王刚】砂锅焗鱼 - https://youtu.be/Qkh6tZhdh-I

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1005]
**视频链接**：https://youtu.be/Qkh6tZhdh-I

视频时长3:26，预计发布时间为北京时间5月6日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“姜葱焗鲈鱼”“砂锅焗鱼”的做法，不用加一滴水，成菜入味鲜嫩

简介
同学们好，今天和大家分享一道“姜葱焗鲈鱼”，也可以用相同鱼改刀的方法和不加水焗的方法来根据自己的口味来做砂锅鱼，垫底的姜葱不变，其他的调味料和酱汁都可以根据自己的喜好来改变。这样做出来的鱼像烤鱼一样非常入味，但又能一定程度的保存了鱼的嫩，不会像烤鱼一样太干，非常推荐大家有机会可以尝试。

本期菜品：【姜葱焗鲈鱼】
【主料】
鲈鱼一条（约750克）
【辅料】
洋葱（约200克）
生姜2块（约40克）
大蒜几颗（约30克）
葱花（少许）
【调味料】
食用盐（约4克）
胡椒粉（少许）
香辣豆豉（90克）
蚝油（20克）
排骨酱（30克）
海鲜酱（30克）

字幕
0:00:00.280,0:00:01.480
哈喽大家好 我是王刚

0:00:01.500,0:00:03.400
本期视频我跟大家分享一道家常菜

0:00:03.720,0:00:05.020
姜葱焗鲈鱼

0:00:05.980,0:00:07.880
首先我们准备鲈鱼1条（约750克）

0:00:08.085,0:00:11.311
将鱼敲晕之后刮去鱼鳞去除内脏清洗干净备用

0:00:24.182,0:00:25.334
下一步开始改刀

0:00:26.031,0:00:27.571
首先我们从鱼肚下刀

0:00:28.993,0:00:30.997
将两边的鱼肉切开露出脊骨

0:00:32.965,0:00:34.708
然后切掉尾部多余的脊骨

0:00:36.610,0:00:39.480
切掉尾骨之后在鲈鱼的两边各切上一字花刀

0:00:39.653,0:00:42.195
这一步的目的是方便成菜入味和成熟

0:00:50.642,0:00:51.918
下一步开始准备酱料

0:00:52.355,0:00:53.804
碗中加入蚝油20克

0:00:55.781,0:00:57.813
加入排骨酱和海鲜酱各30克

0:01:08.519,0:01:09.658
加入食用盐1勺（约2克）

0:01:10.560,0:01:11.681
加入少许胡椒粉

0:01:12.810,0:01:15.243
最后加入香辣豆豉90克搅拌均匀备用

0:01:21.202,0:01:24.838
然后将调好的酱料均匀地涂抹在鲈鱼两边腌制30分钟

0:01:25.084,0:01:27.599
同学们香辣豆豉可以参考往期的教学

0:01:42.405,0:01:43.790
下一步开始准备料头

0:01:44.118,0:01:46.815
准备洋葱1个对半切开之后切成小片备用（约200克）

0:01:51.826,0:01:53.813
准备生姜2块切成姜片备用（约40克）

0:01:56.810,0:01:58.633
准备大蒜几颗切成小粒备用（约30克）

0:02:02.217,0:02:04.714
然后在砂锅中加入食用盐1勺搅拌均匀

0:02:04.984,0:02:07.808
加盐搅拌的目的是让料头出水防止烧糊

0:02:13.020,0:02:16.227
最后再把腌制好的鲈鱼放入砂锅中下一步开始制作

0:02:23.526,0:02:25.959
首先我们把砂锅放在灶上开大火烧开

0:02:41.649,0:02:44.810
大火烧开之后继续盖上盖子转小火烧10分钟即可

0:02:50.651,0:02:52.537
10分钟之后用筷子插入鱼身

0:02:53.120,0:02:55.380
如果很容易插透即说明鲈鱼已熟

0:02:58.086,0:02:59.617
最后撒上葱花即可上菜

0:03:02.724,0:03:05.348
一道非常美味的姜葱焗鲈鱼就制作完成

0:03:06.700,0:03:25.280
下面开始技术总结
第一，原材料最好选择少刺或者无刺的鱼
第二，垫底的料头姜葱可以适当的多加一些
第三，不能吃辣的同学可以根据个人口味调制酱料
第四，制作的前部分必须开大火烧开然后再转小火烧
姜葱焗鲈鱼的技术总结完毕


```

**Comment by Yingzhang1122** [comment]
#标题（翻译主要意思即可，不要超过 100 个字符）
#厨师长教你：“姜葱焗鲈鱼”“砂锅焗鱼”的做法，不用加一滴水，成菜入味鲜嫩
#Chef Wang teaches you: "Jiang Cong Ju Lu Yu" (Baked Bass with Ginger and Onion). No need for water, but more than yummy!

#简介
#同学们好，今天和大家分享一道“姜葱焗鲈鱼”，也可以用相同鱼改刀的方法和不加水焗的方法来根据自己的口味来做砂锅鱼，垫底的姜葱不变，其他的调味料和酱汁都可以根据自己的喜好来改变。这样做出来的鱼像烤鱼一样非常入味，但又能一定程度的保存了鱼的嫩，不会像烤鱼一样太干，非常推荐大家有机会可以尝试。
Hi everyone, today I'd like to share with you how to cook "Jiang Cong Ju Lu Yu" (Baked Bass with Ginger and Onion). You can also use a similar way of cutting and 'baking' to cook your own dish according to your habit. Based on ginger and onion, you may use other ingredients and sauces that you like. With the flavors well penetrated inside, the fish cooked in this way will taste like grilled fish, but more tender and juicy. I'd highly recommend that you try it yourself!

#本期菜品：【姜葱焗鲈鱼】
Dish: "Jiang Cong Ju Lu Yu" (Baked Bass with Ginger and Onion)
#【主料】
#鲈鱼一条（约750克）
Major ingredient:
A bass fish (~750 grams)
#【辅料】
#洋葱（约200克）
#生姜2块（约40克）
#大蒜几颗（约30克）
#葱花（少许）
Other ingredients:
Onion (~200 grams)
2 pieces of ginger (~40 grams)
Several cloves of garlic (~30 grams)
Cut spring onion (A little)
#【调味料】
#食用盐（约4克）
#胡椒粉（少许）
#香辣豆豉（90克）
#蚝油（20克）
#排骨酱（30克）
#海鲜酱（30克）
Seasonings:
Salt (~4 grams)
Pepper powder (A little)
Spicy "Douchi" (fermented soybeans) (90 grams)
Oyster sauce (20 grams)
Spare rib sauce (30 grams)
Seafood sauce (30 grams)

#字幕
0:00:00.280,0:00:01.480
#哈喽大家好 我是王刚
Hi everyone, I'm Wang Gang

0:00:01.500,0:00:03.400
#本期视频我跟大家分享一道家常菜
In this video, I'm going to share with you a homestyle dish

0:00:03.720,0:00:05.020
#姜葱焗鲈鱼
"Jiang Cong Ju Lu Yu" (Baked Bass with Ginger and Onion)

0:00:05.980,0:00:07.880
#首先我们准备鲈鱼1条（约750克）
First, prepare a bass fish (~750 grams)

0:00:08.085,0:00:11.311
#将鱼敲晕之后刮去鱼鳞去除内脏清洗干净备用
Knock it out, remove the fish scales and internal organs, and wash it clean

0:00:24.182,0:00:25.334
#下一步开始改刀
Next, cut the fish

0:00:26.031,0:00:27.571
#首先我们从鱼肚下刀
Cut from the belly first

0:00:28.993,0:00:30.997
#将两边的鱼肉切开露出脊骨
Cut the fish open to expose the spine

0:00:32.965,0:00:34.708
#然后切掉尾部多余的脊骨
Then cut out the spine near its tail

0:00:36.610,0:00:39.480
#切掉尾骨之后在鲈鱼的两边各切上一字花刀
After removing the tail, cut both sides of the fish in a parallel manner 

0:00:39.653,0:00:42.195
#这一步的目的是方便成菜入味和成熟
This step is for better flavor penetration and faster cooking

0:00:50.642,0:00:51.918
#下一步开始准备酱料
Next, prepare the sauce

0:00:52.355,0:00:53.804
#碗中加入蚝油20克
Add 20 grams of oyster sauce

0:00:55.781,0:00:57.813
#加入排骨酱和海鲜酱各30克
Add 30 grams of spare rib sauce and 30 grams of seafood sauce

0:01:08.519,0:01:09.658
#加入食用盐1勺（约2克）
Add a spoon of salt (~2 grams)

0:01:10.560,0:01:11.681
#加入少许胡椒粉
Add some pepper powder

0:01:12.810,0:01:15.243
#最后加入香辣豆豉90克搅拌均匀备用
Finally, add 90 grams of spicy "Douchi" (fermented soybeans) and stir it well

0:01:21.202,0:01:24.838
#然后将调好的酱料均匀地涂抹在鲈鱼两边腌制30分钟
Smear the sauce uniformly on both sides of the fish and marinate for 30 minutes

0:01:25.084,0:01:27.599
#同学们香辣豆豉可以参考往期的教学
Please refer to previous videos to find how to make spicy "Douchi" (fermented soybeans)

0:01:42.405,0:01:43.790
#下一步开始准备料头
Next, prepare the other ingredients

0:01:44.118,0:01:46.815
#准备洋葱1个对半切开之后切成小片备用（约200克）
Cut an onion into halves, and cut it into small pieces (~200 grams)

0:01:51.826,0:01:53.813
#准备生姜2块切成姜片备用（约40克）
Cut 2 pieces of ginger into slices (~40 grams)

0:01:56.810,0:01:58.633
#准备大蒜几颗切成小粒备用（约30克）
Cut some garlic into small pieces (~30 grams)

0:02:02.217,0:02:04.714
#然后在砂锅中加入食用盐1勺搅拌均匀
Add one spoon of salt into the casserole and mix well

0:02:04.984,0:02:07.808
#加盐搅拌的目的是让料头出水防止烧糊
The purpose of this step is to drive the liquid out of the ingredients by osmosis and prevent the food from being burnt during cooking #请检查这里

0:02:13.020,0:02:16.227
#最后再把腌制好的鲈鱼放入砂锅中下一步开始制作
Finally, put the marinated fish into the casserole and start cooking

0:02:23.526,0:02:25.959
#首先我们把砂锅放在灶上开大火烧开
First, burn the casserole with high heat till boiling

0:02:41.649,0:02:44.810
#大火烧开之后继续盖上盖子转小火烧10分钟即可
After boiling, close the lid and burn with low heat for 10 minutes

0:02:50.651,0:02:52.537
#10分钟之后用筷子插入鱼身
10 minutes later, poke a chopstick into the fish

0:02:53.120,0:02:55.380
#如果很容易插透即说明鲈鱼已熟
If it's very easy to poke it through, the fish is well cooked

0:02:58.086,0:02:59.617
#最后撒上葱花即可上菜
At last, sprinkle some minced spring onion, and the dish is done!

0:03:02.724,0:03:05.348
#一道非常美味的姜葱焗鲈鱼就制作完成
A very delicious "Jiang Cong Ju Lu Yu" (Baked Bass with Ginger and Onion) is ready to serve!

0:03:06.700,0:03:25.280
#下面开始技术总结
#第一，原材料最好选择少刺或者无刺的鱼
#第二，垫底的料头姜葱可以适当的多加一些
#第三，不能吃辣的同学可以根据个人口味调制酱料
#第四，制作的前部分必须开大火烧开然后再转小火烧
#姜葱焗鲈鱼的技术总结完毕
Next, technical summary
First, it's better to choose fish with few or no bones
Second, it's OK to use more ginger and onion as the base
Third, if you don't like spicy food, you can make your own sauce that you like
Fourth, you should use high heat first till boiling and turn to low heat later
That's the end of the technical summary
