### ISSUE TITLE
【美食作家王刚】竹鼠烧竹笋 - https://youtu.be/ZUgKPqO9kOU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#101]
【美食作家王刚】竹鼠烧竹笋 - https://youtu.be/ZUgKPqO9kOU 
这是刚哥最新的视频私享链接，方便大家提前添加字幕，做菜过程文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。然后就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间8月29日晚6点

首先我们准备躁动不安的竹鼠1只大约1500克左右
温馨提示：以下镜头比较血腥，未成年人请在成年人陪同下观看
首先我们来处理竹鼠
在锅中加入宽水开大火烧开
同学们可以尽量的多准备一些开水这样才能更好的操作
水开之后再倒入桶里面将竹鼠浸泡40秒
建议不忍心的同学交给摊主处理
大家注意竹鼠不能烫太久否则毛拔不下来
40秒之后将其捞出将毛发清理干净
然后用喷枪把表皮烧至焦黄
这一步的目的是去除无法处理的绒毛和皮腥味
温馨提示：爱鼠人士请立即离开，后方有较血腥镜头
表皮烧至焦黄之后再清洗干净
竹鼠皮和猪皮类似毛囊里面都有腥味
所以必须经过此法加工才能去除
清洗干净之后再切开去除内脏清洗干净
随着竹鼠近些年来养殖面的扩大
也普遍的出现在人们的餐桌或者河边
但很多地方价格略高毕竟物以稀为贵
清洗干净之后去掉竹鼠的头和指甲
然后再剁成大小均匀的块备用
同学们可以适量的剁大块一些这样更有嚼头
下一步开始准备辅料
准备新鲜的竹笋一根将其拨开再切成块备用
没有鲜竹笋的同学可以用发胀的笋干代替
准备红薯宽粉几根折断加清水浸泡备用
准备干香菇1小把浸泡发胀备用（大概需要60分钟左右）
准备八角桂皮少许
最后再准备生姜1小块拍散备用
香菇发胀之后清洗干净挤干水份备用
下一步开始制作
首先我们在锅中加入适量的清水
然后将剁好的竹鼠冷水下锅焯水
这一步的目的是去除血水
竹鼠属于啮齿类哺乳动物
其皮下的肉质跟老鸭肉类似
必须经过焯水才能更好的去除异味
竹鼠焯水之后倒出备用
然后锅中再次加入适量的清水
锅在加入一勺食用盐
再将切好的竹笋下锅焯水
鲜竹笋必须加盐焯水才能减少苦涩味
否则成菜之后发苦
同学们注意焯水的中途需要加入少许食用油
竹笋焯水之后倒出备用
下一步开始制作
首先我们把锅烧热
锅烧热之后加入适量的油滑锅
滑好锅之后将热油倒出
然后加入少许的底油烧热
油温6成热之后将竹鼠下锅翻炒1分钟
中途加入准备好的香料和生姜
这一步的目的是将竹鼠的皮肉收紧
翻炒1分钟之后再加入适量的料酒去腥
同学们料酒必须在大火翻炒中挥发才能有作用
料酒挥发之后加入8克花生酱翻炒均匀
竹鼠肉虽好但却难在去腥和增香
加入花生酱翻炒之后才是这道菜的香味灵魂所在
然后锅中加入蚝油10克
加入老抽2克调底色
再加入生抽酱油15克从锅边淋入炒出香味
中途加入处理好的竹笋下锅翻炒均匀
翻炒均匀之后再加入适量的清水
同学们清水的量只要没过原料即可
再加入发胀的干香菇下锅
然后开大火烧开
中途撇去浮沫
撇去浮沫之后转小火盖上锅盖焖40分钟
如果竹鼠比较大只的话则需要增加焖煮的时长
在第30分钟的时候揭开锅盖
然后加入泡好的宽粉下锅
剩下的十分钟转中火收汁
然后在起锅之前少许食用盐白糖和胡椒粉调味
最后调好味之后即可出锅装盘
一道软糯适口香味十足的烧竹笋就制作完成
下面开始技术总结
第一，宰杀竹鼠比较血腥建议同学们购买成品肉鼠，或者让摊主加工
第二，此菜做法是以本人长时间研制开发而成
          希望大家多多鼓励其他美食原创作者也分享更多经验
第三，竹鼠不能烫太久否则毛拔不下来
第四，此菜中以鲜竹笋和干香菇味主辅料不需要再加鸡精味精
第五，嫌制作时间长的同学可以直接用高压锅上汽压8分钟即可
烧竹鼠的技术总结完毕

**Comment by immoonancient** [comment]
Published \o/
