### ISSUE TITLE
[华农兄弟] 华农兄弟晚上田里好多黄鳝夹点来油炸味道很不错哦 - https://youtu.be/DfarqWPhP_U

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1038]
https://youtu.be/DfarqWPhP_U
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 12, 2020 at 11:36AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/DfarqWPhP_U

#华农兄弟：晚上田里好多黄鳝，夹点来油炸，味道很不错哦
#Huanong Brothers: There are a lot of swamp eels in the field at night. We catch some and fry them. It tastes not bad.

0:00:00.000,0:00:03.480
# 大家好 今天的月亮很園哦  我去抓點黃鱔來
Hi everyone! The moon is so round tonight. Let me catch some swamp eels.

0:00:03.860,0:00:06.580
# 現在 黃鱔都出來活動了  大晚上的
The eels are going out now, at night.

0:00:07.100,0:00:09.220
# 在這個附近田裡面
They should be nearby, in the field.

0:00:09.220,0:00:11.420
# 在那個附近田裡面就  應該就有黃鱔啦
There should be, should be some eels in the fields nearby.

0:00:12.380,0:00:15.740
# 就有沒有  好像就是鑽在這個田裡面
Any here? It seems that they squeezed into the field here.

0:00:16.080,0:00:17.340
# 在這找一  找一下
Let me search, search for while here,

0:00:19.860,0:00:21.120
# 看能不能找到一條
and see if I can get one.

0:00:22.480,0:00:24.080
# 不知道這裡下面有沒有
Would there be any here underneath?

0:00:25.100,0:00:26.140
# 哦喲  有一條
Oyo! Here's one!

0:00:27.920,0:00:28.920
# 看見沒有 看見沒有
Can you see it? Can you?

0:00:31.640,0:00:34.140
# 還想走  用  用那個燈照著它眼睛
You wanna run away? I, I'm flashing its eyes with my torch.

0:00:34.940,0:00:36.020
# 它就  走不掉
Then it, it can't run away.

0:00:36.300,0:00:37.360
# 誒呀  看見沒有
Eya! Can you see it?

0:00:38.860,0:00:39.740
# 就抓到一條
So one is caught.

0:00:41.880,0:00:42.480
# 還有沒有
Any more?

0:00:44.160,0:00:44.740
# 沒有
Nope

0:00:45.780,0:00:46.780
# 這邊也看一下
Have a look on this side too.

0:00:48.560,0:00:49.900
# 你看  這裡也有一條哦
Look! Here's another one!

0:00:51.040,0:00:51.900
# 這條  好大的
This one, is really small.

0:00:53.880,0:00:54.680
# 小的也要
But I don't mind.

0:00:56.340,0:00:56.840
# 好活潑
It's so energetic.

0:00:57.640,0:00:58.320
# 還想跑
It wants to run away.

0:01:00.440,0:01:01.780
# 你看  它這裡應該有
Look! There should be some here.

0:01:05.640,0:01:06.800
# 這裡有一條  這裡
Here's one, here.

0:01:07.000,0:01:07.740
# 這裡看到了
I can see it here.

0:01:08.580,0:01:09.900
# 看到  只看到半截身體
I see, I can only see half of its body.

0:01:13.840,0:01:14.860
# 好活潑啊  這個
It's so energetic.

0:01:20.560,0:01:23.580
# 這裡有一條  像蛇一樣的哦  一條那麼長
Here's one! It looks like a snake, you know. It's so long.

0:01:26.520,0:01:27.600
# 這樣逮到它了
So then, I've caught it.

0:01:32.780,0:01:33.640
# 沒看到了
I can't see any.

0:01:34.640,0:01:35.380
# 往下走
Let's go down there.

0:01:41.580,0:01:42.620
# 你看  這裡有一條
Look! Here's one!

0:01:43.580,0:01:44.580
# 那麼看不清楚的
It's so hard to see.

0:01:44.720,0:01:46.200
# 就看到一條尾巴 好像在這裡
I can only see a tail. It seems that it's here.

0:01:50.620,0:01:51.380
# 動都動不了
It can't even move.

0:01:53.000,0:01:53.520
# 那麼猛
It' so fierce.

0:01:54.840,0:01:55.860
# 看一下還有沒有  在這
Let me take a look and see if there are any more, here.

0:02:08.300,0:02:09.580
# 看到有一條有這裡的
I saw one here.

0:02:10.560,0:02:11.120
# 跑了
But it ran away.

0:02:16.540,0:02:17.500
# 不知道跑哪裡去了
It ran to God-knows-where-it-is,

0:02:18.320,0:02:18.840
# 鑽走了
and squeezed away.

0:02:19.460,0:02:19.960
# 這甚麼
What is it?

0:02:21.080,0:02:23.480
# 鯽魚是不是  還是  還是那個鬥魚
Is it "ji yu" (local carps)? Or, is it, I mean, fighting fish?

0:02:25.820,0:02:26.400
# 拿網來
Give me the net!

0:02:30.440,0:02:31.200
# 誒呀  撈到啦
Eya! Got it!

0:02:32.420,0:02:33.420
# 你看  這兩條
Look! These two are,

0:02:34.120,0:02:34.820
# 小鯽魚
small  "ji yu".

0:02:35.420,0:02:36.460
# 那麼小的鯽魚
The "ji yu" are so small.

0:02:37.260,0:02:39.140
# 肯定是從我家池塘裡逃出來的
They must be fugitives from the pond at my site.

0:02:40.740,0:02:42.080
# 拿桶裝  裝起來
Let me put, put them into the bucket.

0:02:43.000,0:02:44.320
# 你看  這裡有一條鯽魚哦
Look! Here's a "ji yu"

0:02:44.940,0:02:45.940
# 那麼大的鯽魚
What a huge "ji yu"!

0:02:49.200,0:02:50.100
# 誒呀  想跑
Eya! You wanna run away?

0:02:55.920,0:02:56.420
# 你看
Look!

0:02:56.880,0:02:58.140
# 這個鯽魚可以哦
This "ji yu" is not bad.

0:03:01.100,0:03:02.160
# 夠大吧  這個鯽魚
Big, isn't it? This "ji yu"

0:03:02.900,0:03:03.780
# 多裝點水來
Let me get more water.

0:03:08.300,0:03:10.360
# 你看  又一條  黃鱔
Look! Here's one more, one more eel.

0:03:14.320,0:03:14.820
# 誒呦
Eyo!

0:03:15.700,0:03:16.200
# 跑了
It ran away?

0:03:16.620,0:03:17.180
# 沒夾穩
It didn't hold it tight.

0:03:20.480,0:03:21.400
# 又看到泥鰍啦
I see a loach again.

0:03:22.060,0:03:22.960
# 這裡有條泥鰍
Here's a loach.

0:03:40.100,0:03:40.800
# 有條蚯蚓
An earthworm

0:03:41.720,0:03:43.100
# 蚯蚓也夾回去  給魚吃
Earthworm or not, I'm taking it back, for the fish.

0:03:45.820,0:03:47.160
# 跑了  跑了一條
Run away, one has run away.

0:03:48.680,0:03:49.760
# 我去看下其他地方有沒有
Let me see if there are any more at other places.

0:03:54.960,0:03:55.960
# 你看  這裡有一條
Look! Here's one.

0:03:56.040,0:03:56.540
# 你看
Look!

0:03:57.220,0:03:57.720
# 黃鱔
It's eel.

0:03:58.180,0:03:58.800
# 那麼小
It's so small.

0:03:59.880,0:04:00.940
# 還想跑
You still wanna run away?

0:04:04.000,0:04:04.800
# 你看  這裡有一個
Look! Here's a,

0:04:05.100,0:04:05.820
# 雷頭光  (註︰沒有原字幕)
"lightening head" (local amphibian).

0:04:06.720,0:04:09.100
# 誒呦  跑得那麼快  上樹了
Eyo? It runs so fast. It's on the tree now.

0:04:10.180,0:04:11.100
# 鑽到樹上去了
It has climbed onto the tree.

0:04:11.960,0:04:13.580
# 哇 這裡一條大泥鰍哦
Wa! Here's a huge loach!

0:04:14.480,0:04:14.980
# 看到沒有
Can you see it?

0:04:15.840,0:04:16.580
# 那麼大的
It's so huge.

0:04:17.160,0:04:18.660
# 這夾子應該不好夾
I don't think the tongs can work well.

0:04:25.960,0:04:27.160
# 誒呦  抓到啦
Eyo! Got it!

0:04:29.060,0:04:30.000
# 你看  在這裡
Look! It's here.

0:04:32.360,0:04:33.460
# 這個泥鰍夠大啦
This loach is huge, isn't it?

0:04:34.160,0:04:34.880
# 又大又肥
A big fat loach

0:04:38.380,0:04:38.880
# 別跑
Don't run away!

0:04:39.620,0:04:40.660
# 把它放進桶裡面去
Let me put it into the bucket.

0:04:43.500,0:04:44.940
# 你看  就抓了那麼一點點
Look! So we've caught just a tiny little bit here.

0:04:46.320,0:04:47.240
# 兩條大鯽魚
Two big "ji yu"

0:04:48.560,0:04:49.280
# 好大呀
They're huge!

0:04:49.440,0:04:50.240
# 這些養著
I'll keep them.

0:04:51.260,0:04:52.020
# 這條泥鰍
This loach,

0:04:52.580,0:04:54.340
# 這條泥鰍好大啊  這條泥鰍
this loach is really big, this loach.

0:04:58.920,0:05:00.100
# 我們明天  明天
Tomorrow, tomorrow we'll,

0:05:01.020,0:05:02.440
# 明天再一起來把它煮掉
we'll cook them all together tomorrow.

0:05:03.880,0:05:05.240
# 做盤龍黃鱔
I'll make "Dragon Eels"!

0:05:07.480,0:05:09.040
# 好啦 現在要回去啦
Alright! We need to go back now.

0:05:09.340,0:05:10.500
# 因為都在都快十二點啦
Cuz it's nearly midnight now.

0:05:10.960,0:05:12.640
# 我們明天再搞  處理它
We'll take care of them, deal with them tomorrow.

0:05:14.040,0:05:14.880
# 我家在那裡
My home is over there.

0:05:36.020,0:05:37.100
# 把火點著來
Let me set the fire.

0:06:17.360,0:06:19.740
# 你看  這就是我們昨天抓的黃鱔
Look! These are the swamp eels that we caught yesterday night.

0:06:20.420,0:06:21.240
# 我們挑一些
Let's choose some,

0:06:22.200,0:06:24.440
# 挑一些來做那個盤龍黃鱔
choose some for your "Dragon Eels"

0:06:25.340,0:06:26.880
# 誒呀  你最小咯
Aya! You're the smallest,

0:06:27.620,0:06:28.540
# 剛好合適
and so you're perfect.

0:06:32.820,0:06:34.180
# 這種小的是剛剛好的
These small ones are perfect for our dish.

0:06:43.520,0:06:44.700
# 有好多泥鰍
There are a lot of loaches.

0:06:57.120,0:06:57.660
# 夠了
Enough,

0:06:58.340,0:06:59.020
# 就搞這些  (註︰想不到怎麼又自然又近似的說法，所以選擇自然地表達到當時的意思就算了)
enough for a dish.

0:07:12.460,0:07:13.260
# 等下我就先
You'll be the first one,

0:07:14.900,0:07:15.840
# 抓你來烤
the first one to be grilled.

0:07:15.840,0:07:16.640
# 那麼緊張幹嘛
Why are you so nervous?

0:07:24.100,0:07:24.700
# 先蓋著它
Cover it first.

0:07:25.320,0:07:26.160
# 油還沒燒熱
The oil has not yet been heated.

0:07:27.120,0:07:27.680
# 不要急
I'll take my time.

0:07:29.220,0:07:30.680
# 把這個油  倒下去
I pour the oil, into the wok.

0:07:33.740,0:07:35.100
# 這個油一定要多
It needs a lot of oil

0:07:40.260,0:07:40.760
# 好啦
Alright!

0:07:41.980,0:07:43.200
# 等一下  油燒熱啦
I'll come again, in a minute,

0:07:43.640,0:07:44.140
# 再來
when the oil is heated.

0:07:54.580,0:07:55.560
# 拿一條試一下
Let me get one and have a try.

0:08:12.880,0:08:14.440
# 可以啦  這樣就可以啦
Alright! It's alright now!

0:08:15.300,0:08:16.840
# 等下全部一起倒下去就好
I'll then pour all the rest into the wok and that's it.

0:08:17.380,0:08:17.880
# 一起卷
Let them curl up together,

0:08:18.240,0:08:19.320
# 油溫就沒那麼高啦
Then the oil won't be that hot.

0:08:20.040,0:08:20.800
# 把這個黃鱔
I'll pour the swamp eels,

0:08:21.780,0:08:23.060
# 把它倒下去然後蓋起來
pour them all into the wok and then cover it.

0:08:23.740,0:08:24.400
# 太殘忍了
It's too cruel.

0:08:35.120,0:08:36.620
# 飆的這地上上一地都是
It spills to everywhere onto the ground.

0:08:56.000,0:08:57.560
# 你看  都不卷的這個
Look! They aren't really curling up at all.

0:08:57.920,0:09:00.700
# 這個黃鱔太凄犬 太堅強啦
The eels are too stubborn, too tough.

0:09:05.960,0:09:07.700
# 我搞點料子來  把它
I'll fetch some ingredients,

0:09:08.140,0:09:10.180
# 拌一拌  這樣才好吃
and then, make a dressing. It tastes much better.

0:09:10.920,0:09:11.420
# 你看
Look!

0:09:12.440,0:09:13.380
# 全部盤在一起
They're all curling up together.

0:09:23.200,0:09:24.440
# 搞點這個配料來
Let me fetch some ingredients,

0:09:25.140,0:09:25.940
# 搞點辣椒
some chilli.

0:09:34.300,0:09:34.800
# 好啦
Alright!

0:09:37.520,0:09:39.640
# 先把這些裝起來  剛好把它們給裝起來
Let me put it into the bowl first. Put them into the bowl.

0:09:44.200,0:09:45.120
# 先放點鹽
Put some salt

0:09:45.540,0:09:46.840
# 這鹽稍微放多一點
It needs a bit more salt.

0:09:48.020,0:09:49.760
# 放點鹽  放點裝油
Put some salt, some soy sauce

0:09:50.440,0:09:51.520
# 醬油要搞多一點
I need a bit more soy sauce.

0:09:56.520,0:09:57.320
# 搞點料酒
Some cooking wine

0:10:00.380,0:10:01.840
# 嗯  我先炸一下這個  (註︰不想用"fry"，好像不太合適)
Um! Let me put it into the hot oil first.

0:10:02.340,0:10:03.540
# 炸一下之後就可以
Put it into the oil, then I can,

0:10:05.160,0:10:07.360
# 放在那上面  淋在這上面就可以吃了
put it on top, pour it on top, then it's done.

0:10:12.860,0:10:13.360
# 哇
Wa!

0:10:14.000,0:10:14.700
# 好香啊
It smells so good!

0:10:23.220,0:10:25.080
# 搞點這個香油  潑到這上面來
I pour the flavoured oil, onto the eels.

0:10:32.620,0:10:33.240
# 把這個
I pour the,

0:10:34.780,0:10:37.300
# 香油  淋在每一條黃鱔上
the flavoured oil, onto each eel.

0:10:46.580,0:10:48.100
# 你看  這個黃鱔
Look! This eel,

0:10:48.580,0:10:49.600
# 盤在這裡哦
it has curled up.

0:10:51.820,0:10:52.380
# 嗯
Um!

0:10:54.660,0:10:55.560
# 味道很不錯誒
It tastes really not bad.

0:10:58.140,0:10:59.160
# 很鮮嫩哦
It's so fresh and tender.

0:11:01.220,0:11:02.280
# 剛好有點辣辣的
It's also a bit spicy.

0:11:03.360,0:11:04.200
# 辣椒放少啦
I put too few chilli.

0:11:05.480,0:11:06.660
# 再多點辣椒就好啦
It would be much better with more chilli.

0:11:14.880,0:11:15.840
# 你看  它的肉可以
Look! Its meat can be,

0:11:16.740,0:11:17.720
# 你看  可以撕的哦
can be torn off.

0:11:19.940,0:11:20.700
# 一片一片的
It's in pieces,

0:11:22.260,0:11:23.260
# 可以把它撕下來
and can be torn off.

0:11:24.140,0:11:25.140
# 頭  給小狗吃
Head. Leave it for the doggies.

0:11:33.880,0:11:35.240
# 把它的內臟撕下來
Let me tear off its guts.

0:11:37.920,0:11:38.900
# 你看  這就是
Look! This is,

0:11:40.260,0:11:41.060
# 黃鱔的內臟
the guts of swamp eels.

0:11:50.860,0:11:51.360
# 來
Come here!

0:11:52.300,0:11:52.920
# 誰要吃的
Who wants it?

0:11:54.360,0:11:54.860
# 搶
Grab it!

0:11:56.260,0:11:57.280
# 被那小狗搶走了
It's grabbed by the puppy.

0:11:58.080,0:11:58.740
# 再搞一條來
Let me get one more.

0:12:03.000,0:12:04.060
# 外焦裡嫩的
It crispy outside and tender inside.

0:12:06.520,0:12:07.060
# 你看
Look!

0:12:07.800,0:12:08.740
# 直接撕開來吃
I can tear it and eat right away.

0:12:16.060,0:12:17.460
# 這條是內臟 看
This is gut, look!

0:12:17.940,0:12:19.220
# 一下子就把它撕出來了
It can be taken out by a single pull.

0:12:22.300,0:12:22.840
# 你看  這個
Look! This is,

0:12:23.280,0:12:23.920
# 給狗吃
for the dogs.

0:12:31.860,0:12:32.360
# 小黑
Blacky!

0:12:53.380,0:12:55.900
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:12:56.800,0:12:57.500
# 這個做的
It's ah,

0:12:57.960,0:12:58.780
# 還是比較好吃的
it's really quite tasty.

0:12:59.200,0:13:00.140
# 雖然不怎麼卷
Although they don't really curl up,

0:13:00.560,0:13:01.300
# 不怎麼盤
and don't really look like a dragon,

0:13:03.100,0:13:04.000
# 但是味道好
But it tastes,

0:13:05.100,0:13:05.980
# 還是  還可以的
still, still not bad.

0:13:08.480,0:13:10.120
# 嗯 大肥狗  給一個給你吃
Um! Chubby dog, I give you a piece.

0:13:11.060,0:13:11.800
# 在你頭上
It's on your head.

0:13:14.280,0:13:15.040
# 再吃一條
I have one more.
