### ISSUE TITLE
【雪鱼探店】福建牛排-https://www.youtube.com/watch?v=WPcUQqMEGss

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#106]
https://www.youtube.com/watch?v=WPcUQqMEGss

视频已经于北京时间8月27日 21:30发布
**中文字幕如下**
福建 泉州市（地名）
这就是牛排
这里还有酸菜 萝卜
它这边也有套餐
咸饭 牛排
你好 我要这个牛排
两碗米饭
再要一个牛肉羹
要一个大碗还是小碗
小碗就可以
牛排就一小份 牛肉羹也是一小碗
那拿两个牛排吧
牛排两个 那汤只要一碗
汤只要一碗
咸菜 青菜需要吗
不需要 谢谢
46块钱
扫码（手机付款）后拿着单子去前面取菜
我的钱付过去了
（牛肉羹）
（咸饭）
（牛排）
我看很多评论都会说
为什么不给摄影师吃呢
这次就给摄影师傅吃
加了一块肉 加了一碗咸饭
他们这边的米饭是11点半之后
才有这种白米饭
11点半之前都是这种咸饭
一看就是加了胡萝卜
有味道的咸饭
这次咱们主要是来吃牛排
这个牛排是这种炖的牛排
15块钱一块儿
还有一碗 这个是10块钱的牛肉羹
再加了一个3块钱的咸饭
刚才点餐的时候
点餐的小哥哥说
这个牛排很小 确实是很小
只有这么一小碟的肉
牛排是带骨头的牛肋排
和咱们平常说的西式的牛排是不一样的
它这个是炖出来的
它一看就是炖的特别烂
（肉烂脱骨）
（直接撕着吃）
牛排其实颜色比较深
下面汤汁里的油还是有很多的
用它来配米饭 应该还不错
吃起来有这种咖喱的味道
还有这种黑胡椒粉 辛辣的味道
牛肉其实瘦肉比较多
但是有了汤汁之后
就会觉得牛排没有那么柴
这是我喜欢的味道
很滑啊 朝哪走啊
对比这几天吃的饭你会发现
这个牛排还属于比较重口的
其他的饮食都是比较清淡的
我们主打的就是牛排 牛肉羹
其实也没有其他很多的小菜
主要就是牛肉 牛排
（我们专业就是做这个）
（四代人）
（四代人都是做这个）
刚才那个收银员是您儿子
他第四代 我第三代
我看咱这边的牛排 其实
和其他地方的牛排都不太一样
做法不一样
是
而且牛排是这种比较小的
我们基本上都是传统的做法
嗯 对 牛肉羹都是手工的
这边牛排是这种咖喱味的是吧
放一点咖喱
放一点那个
（姜 葱）
大叔 这个店一般是几点开始营业
我们早上基本上
正常营业是早上十点
到晚上八点
早卖完就早收
没有超过8点的
（原来是固定量的）
一天卖多少 固定
（习惯性用倒装句）
早卖完就卖完了 就收摊了
没有了 就这样子
（牛排200斤左右）
（牛肉羹差不都80多斤）
有时候六点钟 七点钟就关门了 没有了
基本上没有超过8点（关门）的
一天卖两餐的 基本上晚上就没有了
（就不卖了？）
（是没有了 不说不卖）
钱给我们赚 我们都是（卖东西的）
我们这个店是家庭式的
主要我们这个是家庭式
只雇佣了2个工人
只雇佣了2个工人？
加上我们一家六个人
自己做 这个手艺是家庭式的
做这个牛肉就是用心去做
就做的好
我跟我儿子讲 要用心去做 做得好
不要失传 一代传一代

**Comment by immoonancient** [comment]
最后还是我上传了...
