### ISSUE TITLE
[华农兄弟] 华农兄弟：嫩粽叶长出来了，摘点来包粽子，很香很好吃哦   #https://youtu.be/RXame-S6ZiI

### ISSUE THREAD

**Issue by vincenthychow** [immoonancient/YTSubtitles#1077]
https://www.ixigua.com/i6827841813139685899/?logTag=93S7_h9X6-Pw3gc1jWf0Y

未上YT
過兩天才上

**Comment by vincenthychow** [comment]
bot, please upload
Look! This hairy fig,
# 你看  這個五指毛桃


is growing really well, isn’t it.
# 長的夠茂盛啦


Let me clear the weep for it.
# 幫它除除草


This is edible, you know.
# 這個是可以吃的哦


It will be edible when it becomes ripe.
# 等它熟了時候就可以吃


But there are a lot of seeds.
# 不過很多籽的呦


It’s a bit sweet.
# 有點甜甜的


A soup with the hairy fig,
# 這個五指毛桃煲湯


Its root, can be used to make a soup.
# 它的根啊  用來煲湯


The smells so good. We made one before.
# 很香的哦  上次我們也煲過


It was savory sweet.
# 特別甜


The fruits are still green. We can come and pic some when they become ripe.
# 現在果子還沒熟  熟了之後我們可以過來摘一點


There’s so,
# 這裡那麼


so much grass. It’s a no man land.
# 這麼多草啊  沒人來的  這個地方


Aya! Really a lot!
# 哎呀 真的好多啊


Hi everyone!
# 大家好


Today I’m gonna pick some dumpling leaves,
# 今天摘點這個糉葉哦


get some dumpling leaves.
# 搞點糉子來吃


The dumpling leaves have,
# 這個糉葉剛剛


have just come out. They are, really young, you know.
# 剛剛開始出來了  很嫩的哦  這個


This one can be picked right away.
# 像這個可以直接摘


Here are so many, everywhere.
# 好多啊這裡  一大片都是


There are more up there.
# 上面更多


Let’s have a look up there.
# 我們在上面看一下


We come here every year
# 每年我都會來這裡摘


and pick a lot of leaves.
# 摘很多


There are even more a tiny little bit in front of us.
# 再前面一點點更多


Look! This leave is really beautiful and large.
# 你看  這樣糉葉就很靚啦  很大


Look! Especially this one
# 你看  特別是這個


Cuz they’re for wrapping the rice dumplings,
# 因為裹著糉子


wrap, larger leaves mean bigger dumplings.
# 裹 糉葉大  裹的糉子才大


Let’s pick some.
# 摘點回去


This is really young, this one.
# 這一個就很嫩了  這個


Those bought from the markets are all dry, dried.
# 城市里面買的這個糉葉都是乾的  都曬乾啦


Eh, the fresh ones can’t be put onto transports.
# 額  這個新鮮的沒辦法運輸


In the villages, we can have the fresh ones,
# 我們在農村裡面就可以吃的到這個新鮮的


pick the fresh leaves.
# 摘的到新鮮的糉葉


We can have a whole bunch of them without much effort.
# 隨便一摘就一大把


When we’re picking the leaves we need, this one, the second leaf.
# 摘糉葉的時候要摘這個  第二片哦


This first leaf is, a bit smaller.
# 這個第一片長出來的  小一點


The second leaf,
# 第二片


is the,
# 才是


most tasty.
# 最美味的


But the first one is still aright, if there are too few, or no second leaf.
# 如果沒有  糉葉很少的話  第一片也可以摘


Some more in the front.
# 前面還有


Even more in the front.
# 前面更多


Wa! The water, the water current is so strong here.
# 哇  這個水  水很急哦


I’m bring a trap here next time. There must be fish.
# 下次要摘個地籠來  肯定有魚


Look! The leaves are everywhere here.
# 你看  這裡一大片都是哦


The leaves are all the way up there.
# 一路走上去  全是這個糉葉


There’s no way to pick them all.
# 摘都摘不完


Hiu! Here’s a little spider.
# 噓  有個蜘蛛在這裡


C’mon, c’mon, c’mon! Go ‘way, go ‘way!
# 來來來來來  讓開讓開


Let me come in.
# 讓我來


Small spider
# 小蜘蛛


Single child. It’s so big, though it’s the single child.
# 獨苗啊  這個獨苗一片都那麼大


This is a bit small.
# 這個就小一點


This is smaller.
# 這個比較小


This one is, young.
# 這一片都是  嫩的


Look! I’ve so many here. It’s enough.
# 你看  摘了那麼多  夠啦


Let’s leave some of other people in the village.
# 留一點給村裡面的其他人摘


We shouldn’t take everyone.
# 別全部摘完啦


Alright! Let’s go back,
# 好  現在回去啦


and make the rice dumplings now.
# 回去做糉子


Look! These are the dumpling leaves that we picked. Let me wash them.
# 你看  這個糉葉我們摘回去啦  我洗一下


Let me wash them here with some water.
# 放點水裡面洗一下


There are almost six hundred leaves.
# 這裡差不多六百片啦


They fill up the pot.
# 這個都滿啦


Later,
# 等一下


when we have all the dumplings ready, all ready, we bring them to the county seat,
# 等我們全部把糉子包好來  包好來  帶到縣城去


and let them, let the children have a try.
# 給他(她)們  小孩嘗一下


I soak them here with water first. And then, wash them, that’s it.
# 先用水這樣先泡一下  然後再把它  洗一下就可以啦


There’s too little sticky rice.
# 這個糯米太少啦


I need to fetch more later.
# 等一下  我再去搞一點來


I just soak it here, so that,
# 就這樣泡一下  把它


so that,
# 泡的


it gets saturated with water.
# 泡飽和來就可以啦


Look! It’s beautiful, isn’t it?
# 你看  很靚的哦  這個


Now we’re gonna get some plant ash.
# 現在要把它燒點草木灰出來


Without plant ash,
# 不燒草木灰的話


it's no good.
# 就不好


It’s the traditional way,
# 以前古老的辦法


without using soda.
# 沒有那個小蘇打


Simply putting the soda is also an option.
# 直接放小蘇打也可以的


But plant ash is a better option.
# 燒點草木灰更好


Look! The fire starts to grow now.
# 你看  現在火慢慢地著啦


In the past, our grandpa and gradma,
# 以前我們的爺爺奶奶


they chopped down these plants,
# 他(她)們摘這個草木灰的時候就是


when they were making the plant ash. These are living plants, you know.
# 把這個植物砍下來  就這種生的哦  (註︰不明白甚麼是「生的」)


We burn, burn them right away.
# 就直接  直接這樣燒


Alright! The fire is not strong, but, slowly…
# 可以  燒的不是很著  但是慢慢地


I have no ideas why they use only this plant.
# 我也不知道為甚麼他(她)只要  指定了這種植物


It doesn’t smell anything. But, it smells good when they’re being burnt.
# 沒甚麼味道  但是  燒起來確實很香


Um! I can sense the smell.
# 嗯  是有點香味


It takes longer, the but is still not here.
# 現在還沒那麼快  火還沒著呢


The fire sounds “pili pala”.
# 燒的噼裡啪啦響


It’s the scent of childhood.
# 小時候的味道


It takes longer.
# 這沒那麼快


We only need a tiny little bit of plant ash, as we don’t need so much.
# 因為我們要的不多  我們只要一點點這個草木灰就可以啦


Burn the bunch over there, that’s it!
# 把這一捆燒掉就好啦


The fire is a bit stronger now.
# 那火有點大


It’s getting stronger.
# 現在火越來越旺盛啦


Some boiled water, to put off the, you know
# 要開水哦  要把這個  滅一下


The residue needs to be filtered.
# 把這個渣過濾掉


Leave it here.
# 撐一下它


It needs to be filtered.
# 把這個過濾一下


This is al, alkaline water.
# 這就是碱  碱水


Alright! I’ll throw it away.
# 好啦  這個就不要啦


Look! This is saphora flower.
# 你看 這是槐花哦


Leave it here,
# 讓它放在這裡


and it will, gradually sink to the bottom.
# 讓它慢慢  它慢慢會沉澱下去


Aiya! This is brown.
# 哎呀  這個是黃的


No worries. Just let it sink.
# 沒事  讓它沉澱


I’m gonna pick some palm leaves,
# 我去摘點那個棕樹葉來


as strings.
# 綁糉子


It’s so high, but we don’t even have a ladder.
# 那麼高 梯子都沒帶


Eh! I can climb onto the tree here.
# 誒  可以爬到這邊樹上去


The posture is not good.
# 姿勢沒擺好


I need a good posture before I can climb.
# 要擺好姿勢才好爬


I can also help it, help it trim the branches here.
# 我再幫它  幫它修一下這個樹枝


Alright!
# 可以


Four here, should be enough.
# 有四個  應該足夠了


Wa! Here’s a longhorn beetle.
# 哇  這裡有一個天牛哦


Come here.
# 來


Come here.
# 來


It yelps, you know.
# 它會叫的哦


Come here.
# 來


Look! It can’t move anymore when I’m holding it’s horn. Look!
# 你看  拎著它的鬚它就動不了了  你看


It’s horn is really long. Look! Have alook!
# 這個鬚很長的哦  你看  你看一下


Eyo! It bites!
# 誒呦  它咬人的


How dare it is to bite me.
# 它竟然想咬哦


Have a look at its, mou, mouth.
# 你看它的  嘴  嘴巴


It’s like a pair of huge pincers, look!
# 像個兩個大鉗子一樣  你看


Alright! 
# 可以啦


I let you go.
# 放你走啦


We loved playing with them when we were small.
# 小時候經常抓來玩


But now,
# 這個時候


we don’t find it fun anymore when we grow up. C’mon! Go!
# 長大了就不喜歡玩了 快點快點  走


Let me put it,
# 把它放到


onto the tree.
# 樹上去


It would be stepped if it’s left on the path.
# 放到路邊等下被人家踩死啦


Put it here.
# 放在這裡啊


It yelps. Look! Why don’t you say thanks to me?
# 它還會叫的  你看  還不謝謝我


Fly!
# 飛


Hurry up!
# 快點


It can fly. Why doesn’t it fly?
# 它會飛的哦  它又不飛


Eh? It flies, it flies, it flies, it flies.
# 誒  飛啦  飛啦  飛啦  飛啦


This one, in the middle, this part,
# 把這個 中間  這一塊


remove it, that’s it. Take away those on this sides.
# 搞下來就可以啦  這邊上這個不要


And then,
# 要把這個


tear is up into pieces, slowly.
# 慢慢地   一片一片撕下來


Look! It’s so beautiful!
# 你看  這樣就很靚了


Today we went to the town and bought some pick. We’ve bought some pick.
# 今天去鎮上賣[SIC]豬肉  買了一點點豬肉


But it doesn’t seem enough. Let’s get a duck to make it enough.
# 不是很夠哦  拿那個鴨肉來湊


There are some ducks, up there.
# 上面有 有幾個鴨子


Let’s catch one.
# 抓一個來


This is the meaty one, this one.
# 這個肉才多  這個


The other ducks, have hardly any meat.
# 其它都是  沒甚麼肉


Fear not, fear not. It’s not scary.
# 別怕別怕  我都不怕


Look! This duck, can still swim.
# 你看  這個鴨子  還會游泳


Alright! It’s fat and white.
# 好啦  白白胖胖的


Let me chop it up,
# 我把它剁碎來


chop it up and marinate it.
# 剁碎把腌一下


I only need to make the meat out,
# 把它的肉取到來就可以了


and throw the bones away.
# 骨頭不要


Take some meat, from this duck.
# 把這個鴨子  取點那個肉出來


I wanna try the chicken breast.
# 吃一下它的雞胸肉  (註︰不指鴨為雞，同樣不澄清)


A piece of meat of this size in each rice dumpling is enough.
# 一個糉子包一塊這樣的肉就可以啦


Look! I cut the meat out, piece by piece,
# 你看  把這個肉這樣  一塊一塊的切下來


to fill the dumplings with soul,
# 這樣才有靈魂


and taste.
# 才好吃


The duck was really fat.
# 這鴨子很肥的


But who knows why it gets skinny after staying just a few days here.
# 在我家養了幾天  竟然一下子就瘦了


This duck, is so meaty.
# 好多肉啊  這鴨子


Enough! Look! I don’t need that much.
# 夠了  看  不要那麼多


Let me put the duck meat here first,
# 這個鴨肉先放在這裡


and fetch some pork.
# 再搞點豬肉


This is duck meat, and this is pock.
# 這個是鴨肉  這個豬肉


Let me just mix them up,
# 混在一起算啦


the pock and the duck.
# 豬跟鴨在一起


And the fetch some, you know,
# 再搞點  這個


ginger.
# 生薑


After ginger, some salt
# 生薑放了再放點鹽


I wanna make it more salty.
# 這鹽稍微要多一點


So I need a bit more salt.
# 稍微放咸一點


Mr. Cameraman prefers stronger taste.
# 攝影小哥口味比較重


I can put a bit more salt.
# 可以放多點鹽


Then some cooking wine
# 加點料酒


The texture becomes smooth with the cooking wine.
# 加完料酒就是會滑一點


And then some,
# 再加一點


soy sauce.
# 醬油


Um! Soy sauce
# 嗯  加了點醬油


After soy sauce, then some,
# 加完醬油再加點


oil,
# 油


Wa! It’s so smooth, their,
# 哇  好滑呀 它們的


muscles.
# 肌肉


And also put some,
# 再加點這個


this is, this is our Indian shoots powder here.
# 這個是  我們這邊的蕉芋粉


It makes the meat,
# 加點這個


even smoother.
# 更滑


More, not enough
# 不夠 要多加一點


Marinate it for a while.
# 讓它腌一下


Marinate it for,
# 腌個


for about half an hour.
# 半個小時左右


Then we can wrap the rice dumplings right away.
# 就可以直接煲糉子啦  (註︰我懷疑這裡字幕應該是「包」，不是「煲」)


Um! It smells so good!
# 嗯  香啊


There are too huge buckets, more than five, around seven or eight kilograms here.
# 這裡兩大桶 十幾  十五斤左右啊  這裡


The rice has already, cost me a lot.
# 米都買了  買了不少錢


Let’s have a look at the, you know
# 去看一下  那個


I pour in the water.
# 把這個水倒進去


It’s green.
# 綠色的


Alright! This water is for cooking the dumplings.
# 好啦  這個水是用來煮糉子的


Wrapping rice dumplings,
# 裹糉子這個


take a long time to learn. There’s, there’s no short cut.
# 這個要慢慢去學的一下子    一下子學不會


I couldn’t do it when I was small. But I’m now learning the skills gradually.
# 以前我還小的時候也不會  慢慢地慢慢地就會了


Take a piece of,
# 搞一塊


duck meat.
# 鴨肉


Cover it, with some rice.
# 蓋  這一點米


And that’s it.
# 這樣就可以啦


Wrap it here,
# 包成這樣


hold it on the other side.
# 一捏過來


Look! And then,
# 你看  直接就


a rice dumpling is in front of me right away.
# 一個糉子  就出來了


It needs to be tied tighter.
# 紥的時候要把它紥緊一點


Mine, mine is a bit ugly.
# 我做的  我做的有點醜


Anyway
# 沒辦法


My hands are a bit clumsy.
# 手太笨啦


Look!
# 你看


Not bad, it’s squarish.
# 可以  四個角


Look! So we have a whole pot here. Let me cook them first.
# 你看  包了那麼一鍋  我先把它燉了先


Otherwise, we can’t have our first bite even when it gets dark.
# 不然等  到晚上都吃不了了


It’s plain green.
# 一片綠色的


Pretty!
# 很漂亮哦


Let me start the fire first.
# 先燒一下火


The cover can hardly fit.
# 蓋都蓋不上


Wa!
# 哇


It smells so good!
# 好香哦


Those at the bottom, flip them to the top.
# 下面的  往上撈


Flip those at the bottom to the top.
# 把下面的撈上來


Ah! It takes a few more moments.
# 啊  再煮一下


Wa!
# 哇


It’s getting ready now.
# 現在開始熟了哦


Let me have a try.
# 先嘗一下


It’s, very hot!
# 好燙啊  這個


Look!
# 你看


It’s so pretty, this dumpling.
# 很漂亮哦  這個糉子


Squarish
# 四個角


Look!
# 你看


It’s just right.
# 剛剛好


It’s ready,
# 都已經


mushy. The rice is like,
# 煲爛啦  這個米都變成了那個


a bit mushy.
# 稀稀的


Look!
# 你看


Duck meat
# 鴨子肉


Um! It smells so good. It’s the scent of rice dumplings.
# 嗯  很香  很香糉子的味道


The duck meat,
# 那個鴨肉


the duck meat tastes really good.
# 這鴨肉好吃


And it’s chewy.
# 很有嚼勁


Doggies! You want some?
# 小狗  想不想吃


C’mon! I give you some.
# 來  給點你們吃


This is sticky rice. You don’t like it.
# 這糯米  不好吃的


Look! Everybody, be a good dog!
# 你們  一個一個給我聽話啊


Especially you,
# 特別是你


and Big Chubby.
# 還有大胖狗


You wanna bite other people’s chickens again.
# 又想去咬人家雞


You got stopped by me, fortunately.
# 幸好我欄住了


Lick it, lick it.
# 舔一舔  舔一舔


Alright! The video ends here.
# 好啦  今天的視頻就到這裡啦


There’s one more pot. Let me cook it, two pots.
# 還有一鍋  把它燉了  燉兩鍋


Ah! It’s a bit hot.
# 啊  有點燙


Let’s pick these out, and put these into the pot.
# 我們把這些撈起來  把這裡的放下去燉


I bring some,
# 帶點出去


for Mr. Cameraman,
# 給攝影小哥


so that he can enjoy.
# 給攝影小哥吃

**Comment by immoonancient** [comment]
西瓜视频可以先下载下来，然后找个字幕软件打时间轴的
或者甚至可以自行上传 YouTube（设置成只能自己看）然后用 YouTube 打轴

**Comment by vincenthychow** [comment]
這個不是百分百準確的。我有印像西瓜和YT的時長不知何事有時會有些少差別。更甚的，有時某些空鏡頭會不完全一樣。任何地方只要有百分之一秒的差別，做好的時間軸差不多已沒用了。所以還是以他最後上載的為準吧。

**Comment by vincenthychow** [comment]
已發佈
