### ISSUE TITLE
【美食作家王刚】炸蜂蛹 - https://youtu.be/BPExmlZapmU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#109]
【美食作家王刚】炸蜂蛹 - https://youtu.be/BPExmlZapmU
这是刚哥最新的视频私享链接，方便大家提前添加字幕，就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间8月31日晚6点

**Comment by tiffychou** [comment]
這有人做了嗎？沒有的話我可以做。有小伙伴可以幫忙打中文字幕嗎？這樣會快一些

**Comment by immoonancient** [comment]
还没，上吧

**Comment by immoonancient** [comment]
已上传，等发布
