### ISSUE TITLE
[手工耿] 腦瓜崩兒神器 - https://youtu.be/UsBSCeyOM-s

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1099]
https://youtu.be/UsBSCeyOM-s
<p>&#35270;&#39057;&#21457;&#24067;&#20110; May 29, 2020 at 09:00PM</p>
<p>&#26631;&#39064;<br>
&#12304;&#25163;&#24037;&#32831;&bull;Useless Edison&#12305;&#33258;&#35069;&#24382;&#33126;&#29916;&#23849;&#20818;&#31070;&#22120;&#65281;Forehead Flick weapon.</p>
<p>&#31616;&#20171;<br>
&#25163;&#24037;&#32831;&#20170;&#26085;&#33258;&#35069;&#30446;&#37636;&#65306; &#33126;&#29916;&#23849; &#26262;&#22778;&#39770;&#32568; &#26262;&#27683;&#26885; &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #UselessEdison #&#32831;&#24101; #ChineseEdison #shougonggeng #handicraft #diy #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #inventions #&#20013;&#22283;&#30332;&#26126; #&#20013;&#22283;&#24859;&#36842;&#29983; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by Kevinzheng5** [comment]
标题
【手工耿•Useless Edison】自制弹脑瓜崩儿神器/Forehead Flicker

简介
手工耿今日自制自录：脑瓜崩儿，暖壶鱼缸，暖气椅—别人笑我太疯癫，笑完疯癫笑我闲。大家好，我是手工耿，如果你喜欢我的视频，欢迎点击订阅。
Useless Edison makes: Forehead Flicker, Thermos Bottle Fish Tank and Heater Bench. Others tease at my madness, and so much leisure time I have. Hi guys, I’m useless Edison. If you like my video, please click subscribe! 

字幕
0:00:00.000,0:00:02.620
（脑瓜崩）
(Forehead Flicker)

0:00:02.820,0:00:05.105
朋友之间，有的时候为了增进友谊
To improve our friendships between buddies

0:00:05.105,0:00:08.135
经常会开一些善意的小玩笑
We mess up with each other all the time

0:00:08.135,0:00:09.995
躲在门后，吓对方一跳啊
Like hiding behind the door and scare them

0:00:09.995,0:00:11.675
做一些小恶作剧啊
Some pranks

0:00:11.675,0:00:13.525
弹个脑瓜崩之类的
Like flick them on the forehead

0:00:13.525,0:00:16.985
但是有的朋友，因为说身体素质的原因
But some guys have limitations on physical strength

0:00:17.640,0:00:20.305
中指没有力量，没有办法弹出一个响亮
They have weak fingers and cannot flick hard enough 

0:00:20.305,0:00:22.880
清脆悦耳的脑瓜崩儿
To flick with a crisp and sweet noise

0:00:22.880,0:00:26.300
所以说，我做了一个脑瓜崩辅助器
Thus, I made a flicking assistant device

0:00:26.460,0:00:29.520
可以看一下，有弹簧
Have a look, there’s a spring inside

0:00:29.705,0:00:32.305
带起来也非常方便
It’s easy to wear too

0:00:32.305,0:00:35.255
把中指插进去就可以，后面有根手镯
Put your middle finger in. There’s a bracelet too

0:00:36.295,0:00:37.415
安装上
Just assembly

0:00:37.955,0:00:39.045
就可以了
That’s it

0:00:41.245,0:00:44.615
看一下，力量如何
Let’s see how strong it is

0:00:46.120,0:00:48.560
先拿鸡蛋做个实验
Let’s test it with an egg first

0:00:55.400,0:00:57.360
（暖壶鱼缸）
(Thermos Bottle Fish Tank)

0:01:15.060,0:01:17.060
（暖气椅）
(Heater Bench)

0:01:17.340,0:01:20.180
天气越来越冷，每天我工作完
It’s getting colder and colder. Every day I got off work,

0:01:20.180,0:01:23.040
都喜欢靠在这个暖气片旁边暖和一下
I’d like to lean on this heating radiator

0:01:23.040,0:01:26.320
但是蹲时间久了发现腿比较麻
But my legs went numb after a while

0:01:26.420,0:01:29.780
所以说我准备做一个暖气春秋椅
So I planned to make a heater bench

0:03:00.795,0:03:03.705
差不多已经制作完成了
Almost done

0:03:03.705,0:03:06.845
本想油完漆再安装，但是说我已经迫不及待了
I was going to paint it and then assembly. But I can no longer wait

0:03:06.845,0:03:08.365
先坐上再说吧
Let’s have a try first

0:03:21.065,0:03:22.465
看它的温度
Let’s measure the temperature

0:03:29.585,0:03:31.125
坐一下试试效果
Let’s sit on it and see

0:03:33.505,0:03:34.505
哇
Whoa

0:03:34.635,0:03:37.565
暖和！这温度是四周围
So warm! The heat surrounds you

0:03:37.565,0:03:40.135
把你包起来的，全部后背
It embraces you 

0:03:40.135,0:03:42.535
都能感受到，而且
All your back can feel it

0:03:42.895,0:03:44.565
而且这种椅子不仅
And the chair is not only

0:03:44.565,0:03:46.545
冬天坐着比较暖和
Warm during the winter

0:03:46.545,0:03:48.985
夏天坐着也比较凉爽
It’s also cool during the summer

0:03:48.985,0:03:51.675
一年四季都能用，谢谢
Good all year round. Thanks
