### ISSUE TITLE
[雪鱼] 西安卤面 - https://youtu.be/AhGjPmKGMUw

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1105]
**视频链接**：https://youtu.be/AhGjPmKGMUw

视频时长：8min
发布日期：北京时间6月1日 20:00

# 请翻译以下全部内容

```

字幕
1
00:00:01,920 --> 00:00:06,840
陕西·西安

2
00:00:12,480 --> 00:00:15,520
我们现在在一个小区里

3
00:00:15,520 --> 00:00:18,560
准备吃中午饭

4
00:00:19,240 --> 00:00:22,280
路两边有很多小吃摊

5
00:00:22,600 --> 00:00:25,280
看看今天中午吃什么吧

6
00:00:25,280 --> 00:00:26,880
早上起来还没有吃饱饭

7
00:00:26,880 --> 00:00:29,080
现在出来的时间是比较早吧

8
00:00:29,080 --> 00:00:32,040
看了几家小店 都还没有打算开张

9
00:00:32,040 --> 00:00:34,320
走了半天 直到看到这锅肉

10
00:00:34,320 --> 00:00:37,120
我这两条腿真的是走不动路了

11
00:00:45,680 --> 00:00:50,120
来的太早了 没想到这边的面条还没有做好

12
00:00:50,120 --> 00:00:52,880
不过门口的大锅已经支棱起来了

13
00:00:52,880 --> 00:00:56,880
看里面的肉 真的是特别香

14
00:01:06,600 --> 00:01:09,720
一天这一锅肉够吗

15
00:01:09,720 --> 00:01:12,400
要不够下午再烧吧

16
00:01:28,560 --> 00:01:31,280
一会儿这个肉直接浇在面上吃的是吧

17
00:01:31,280 --> 00:01:36,120
这个肉 一会儿烧好以后 每一碗都有 都含着有

18
00:01:51,960 --> 00:01:55,000
在西安的面馆里 总少不了两种食材

19
00:01:55,000 --> 00:01:56,760
一种呢 是大蒜

20
00:01:56,760 --> 00:01:58,920
另外一种是醋

21
00:02:01,120 --> 00:02:03,880
怎么把它给忘了 还有辣子

22
00:02:06,520 --> 00:02:10,840
我们今天吃的是卤面 面条是上锅蒸出来的

23
00:02:10,840 --> 00:02:14,280
面条出锅 然后在上面放上卤子

24
00:02:14,280 --> 00:02:17,440
大碗的是13块钱 小碗的是11块钱

25
00:02:17,440 --> 00:02:20,600
每碗当中 都含有肉啊 菜啊

26
00:02:33,240 --> 00:02:35,600
干的时间好长了

27
00:02:35,600 --> 00:02:38,560
一个生意坚持这么久 太不容易了

28
00:02:38,560 --> 00:02:41,120
那你没办法 你要生活的嘛

29
00:02:41,120 --> 00:02:46,080
人要生活就是这样子

30
00:02:46,960 --> 00:02:48,520
反正跟上班一样

31
00:02:48,520 --> 00:02:51,960
你上班 工作 有时候干也要干一辈子嘛 是吧

32
00:02:53,720 --> 00:02:57,000
你人 你活着你不干 你咋么办

33
00:02:57,000 --> 00:02:59,400
是不 你不干这个就得干那个

34
00:03:03,640 --> 00:03:06,200
都是些老顾客过来的是吧 附近上班的

35
00:03:06,200 --> 00:03:09,080
老顾客多 干的时间长了 老顾客也多

36
00:03:09,080 --> 00:03:11,040
但是新顾客也有

37
00:03:11,040 --> 00:03:14,360
反正可多顾客都说 （味道）还行

38
00:03:14,360 --> 00:03:16,240
喜欢吃了他就爱吃

39
00:03:16,240 --> 00:03:19,040
你有的人他不喜欢吃这种面 那咱能怎么办

40
00:03:19,040 --> 00:03:20,200
就是一碗面

41
00:03:20,200 --> 00:03:24,360
没有可香啊 像人家那种大口香得很

42
00:03:24,360 --> 00:03:26,920
这没有 就很家常的味嘛

43
00:03:26,920 --> 00:03:28,800
就家常味

44
00:04:06,520 --> 00:04:09,040
我要一个大碗的 再加个蛋

45
00:04:09,040 --> 00:04:11,800
大碗的 加个蛋

46
00:04:26,560 --> 00:04:29,600
还是很多料的呀

47
00:04:40,000 --> 00:04:40,920
辣子呢

48
00:04:40,920 --> 00:04:42,520
要

49
00:04:42,520 --> 00:04:43,600
再来一勺？

50
00:04:43,600 --> 00:04:45,840
可以 可以

51
00:04:47,680 --> 00:04:49,920
还有煎蛋

52
00:04:52,560 --> 00:04:53,360
好 谢谢

53
00:04:53,360 --> 00:04:55,160
不客气

54
00:04:59,840 --> 00:05:02,120
看我们的大碗卤面上来了

55
00:05:02,120 --> 00:05:06,320
不过我发现 后面的大哥在吃面之前会先剥蒜

56
00:05:06,320 --> 00:05:09,800
13块钱的卤面 阿姨说够两个人吃的

57
00:05:09,840 --> 00:05:11,480
确实不少

58
00:05:11,480 --> 00:05:16,720
红的 黄的 绿的 各种各样的颜色应有尽有

59
00:05:16,720 --> 00:05:20,920
卤面里面除了有肉 菜花 豆角

60
00:05:20,920 --> 00:05:22,480
此外呢 我们还加了一个蛋

61
00:05:22,480 --> 00:05:24,080
这个是什么

62
00:05:24,080 --> 00:05:26,400
土豆

63
00:05:31,480 --> 00:05:34,560
阿姨刚才说 面条没有多好吃

64
00:05:34,560 --> 00:05:38,440
但是食材丰富 让人感觉食欲大开

65
00:05:52,560 --> 00:05:56,440
面条是干的 没有任何的汤汁 加了辣子

66
00:05:58,080 --> 00:06:02,600
这个焖面加上辣子 辣子是香而不辣的

67
00:06:02,600 --> 00:06:05,880
但是很下面条

68
00:06:10,400 --> 00:06:12,920
觉得不够 这边还有

69
00:06:19,360 --> 00:06:22,400
这哪是用碗装 这是用盆装

70
00:06:25,880 --> 00:06:28,400
有能吃不饱的吗

71
00:06:33,960 --> 00:06:35,200
谢谢

72
00:06:40,360 --> 00:06:44,680
面条稍微有些油 有些酱油的咸味

73
00:06:44,680 --> 00:06:49,000
面和菜就是这么浑然一体

74
00:06:54,160 --> 00:06:56,720
吃到现在 菜已经吃光了

75
00:06:56,720 --> 00:07:00,080
然后我们说 把辣子放进去

76
00:07:00,080 --> 00:07:03,760
辣子都能当一道菜 配面条来吃

77
00:07:16,800 --> 00:07:20,800
面馆里的面条是用这种蒸屉蒸出来的

78
00:07:20,800 --> 00:07:24,160
每卖一屉才会再去蒸一屉

79
00:07:24,160 --> 00:07:27,520
不知不觉的工夫已经卖了三四屉了

80
00:08:03,880 --> 00:08:06,320
叔 走了 拜拜

81
00:08:08,840 --> 00:08:12,200
拍的差不多了 我们要走了

82
00:08:16,400 --> 00:08:20,880
关 注
雪 鱼 探 店


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
字幕
1
00:00:01,920 --> 00:00:06,840
陕西·西安
Xian, Shanxi
2
00:00:12,480 --> 00:00:15,520
我们现在在一个小区里
We are in a community now
3
00:00:15,520 --> 00:00:18,560
准备吃中午饭
Ready to eat lunch
4
00:00:19,240 --> 00:00:22,280
路两边有很多小吃摊
There are many food stalls on both sides of the street
5
00:00:22,600 --> 00:00:25,280
看看今天中午吃什么吧
Let’s see what to eat at this afternoon
6
00:00:25,280 --> 00:00:26,880
早上起来还没有吃饱饭
Not get full from breakfast
7
00:00:26,880 --> 00:00:29,080
现在出来的时间是比较早吧
It’s still too early for lunch
8
00:00:29,080 --> 00:00:32,040
看了几家小店 都还没有打算开张
Some restaurants still not open yet
9
00:00:32,040 --> 00:00:34,320
走了半天 直到看到这锅肉
Walk a long time until we saw the pot of meat
10
00:00:34,320 --> 00:00:37,120
我这两条腿真的是走不动路了
I’m really tired of walk
11
00:00:45,680 --> 00:00:50,120
来的太早了 没想到这边的面条还没有做好
I came too early that their noodle not done yet
12
00:00:50,120 --> 00:00:52,880
不过门口的大锅已经支棱起来了
But their huge pot is ready
13
00:00:52,880 --> 00:00:56,880
看里面的肉 真的是特别香
The meat is very fragment
14
00:01:06,600 --> 00:01:09,720
一天这一锅肉够吗
Is one pot of meat enough for the whole day?
15
00:01:09,720 --> 00:01:12,400
要不够下午再烧吧
We will make more if it needed
16
00:01:28,560 --> 00:01:31,280
一会儿这个肉直接浇在面上吃的是吧
We pour the meat on the noodles later, right?
17
00:01:31,280 --> 00:01:36,120
这个肉 一会儿烧好以后 每一碗都有 都含着有
We will pour the meat in every bowl, 
18
00:01:51,960 --> 00:01:55,000
在西安的面馆里 总少不了两种食材
There’s always two ingredients in noodle restaurant of Xian
19
00:01:55,000 --> 00:01:56,760
一种呢 是大蒜
One is garlic
20
00:01:56,760 --> 00:01:58,920
另外一种是醋
Another one is vinegar 
21
00:02:01,120 --> 00:02:03,880
怎么把它给忘了 还有辣子
How could i forget the last one, spicy pepper as well
22
00:02:06,520 --> 00:02:10,840
我们今天吃的是卤面 面条是上锅蒸出来的
We gonna have Lumian today, the noodle is steamed in a pot
23
00:02:10,840 --> 00:02:14,280
面条出锅 然后在上面放上卤子
After pour the meat on top, the noodle is ready to serve
24
00:02:14,280 --> 00:02:17,440
大碗的是13块钱 小碗的是11块钱
13 yuan for large bowl, 11 yuan for small bowl
25
00:02:17,440 --> 00:02:20,600
每碗当中 都含有肉啊 菜啊
Meat and vegetable in every bowl
26
00:02:33,240 --> 00:02:35,600
干的时间好长了
We’ve work here a long time
27
00:02:35,600 --> 00:02:38,560
一个生意坚持这么久 太不容易了
It’s not easy to hold a business for that long time
28
00:02:38,560 --> 00:02:41,120
那你没办法 你要生活的嘛
You have no choice
29
00:02:41,120 --> 00:02:46,080
人要生活就是这样子
This is how life looks like
30
00:02:46,960 --> 00:02:48,520
反正跟上班一样
Like works
31
00:02:48,520 --> 00:02:51,960
你上班 工作 有时候干也要干一辈子嘛 是吧
You work for life sometimes right?
32
00:02:53,720 --> 00:02:57,000
你人 你活着你不干 你咋么办
What else can you do?
33
00:02:57,000 --> 00:02:59,400
是不 你不干这个就得干那个
Correct? You need make a choice
34
00:03:03,640 --> 00:03:06,200
都是些老顾客过来的是吧 附近上班的
They all are old customers, works nearby
35
00:03:06,200 --> 00:03:09,080
老顾客多 干的时间长了 老顾客也多
You will have more customers after you work such that long time
36
00:03:09,080 --> 00:03:11,040
但是新顾客也有
We also have new customers as well
37
00:03:11,040 --> 00:03:14,360
反正可多顾客都说 （味道）还行
They said Lumian not bad
38
00:03:14,360 --> 00:03:16,240
喜欢吃了他就爱吃
He like to eat if he love it
39
00:03:16,240 --> 00:03:19,040
你有的人他不喜欢吃这种面 那咱能怎么办
What else you can do if he doesn’t like it
40
00:03:19,040 --> 00:03:20,200
就是一碗面
Just a bowl of noodle
41
00:03:20,200 --> 00:03:24,360
没有可香啊 像人家那种大口香得很
Not that fragment as others restaurant 
42
00:03:24,360 --> 00:03:26,920
这没有 就很家常的味嘛
Just family restaurant
43
00:03:26,920 --> 00:03:28,800
就家常味
Family flavor
44
00:04:06,520 --> 00:04:09,040
我要一个大碗的 再加个蛋
I want a large bowl of Lumian and an egg
45
00:04:09,040 --> 00:04:11,800
大碗的 加个蛋
Large bowl of Lumian with an egg
46
00:04:26,560 --> 00:04:29,600
还是很多料的呀
Plenty of sides
47
00:04:40,000 --> 00:04:40,920
辣子呢
How about spicy pepper
48
00:04:40,920 --> 00:04:42,520
要
yeah
49
00:04:42,520 --> 00:04:43,600
再来一勺？
One more spoon of spicy pepper?
50
00:04:43,600 --> 00:04:45,840
可以 可以
sure
51
00:04:47,680 --> 00:04:49,920
还有煎蛋
And fried egg?
52
00:04:52,560 --> 00:04:53,360
好 谢谢
Yeah, thank you
53
00:04:53,360 --> 00:04:55,160
不客气
You’re welcome
54
00:04:59,840 --> 00:05:02,120
看我们的大碗卤面上来了
Our large bowl of Lumian is ready
55
00:05:02,120 --> 00:05:06,320
不过我发现 后面的大哥在吃面之前会先剥蒜
I also find out the big brother who behind us will peel the garlic before eat his noodle
56
00:05:06,320 --> 00:05:09,800
13块钱的卤面 阿姨说够两个人吃的
Aunt said 13 yuan of Lumian is enough for two people to eat 
57
00:05:09,840 --> 00:05:11,480
确实不少
Sure did
58
00:05:11,480 --> 00:05:16,720
红的 黄的 绿的 各种各样的颜色应有尽有
Red, yellow and green, colorful
59
00:05:16,720 --> 00:05:20,920
卤面里面除了有肉 菜花 豆角
There is meat, cauliflower, and beans in Lumian
60
00:05:20,920 --> 00:05:22,480
此外呢 我们还加了一个蛋
We also add an egg
61
00:05:22,480 --> 00:05:24,080
这个是什么
What’s this?
62
00:05:24,080 --> 00:05:26,400
土豆
potato
63
00:05:31,480 --> 00:05:34,560
阿姨刚才说 面条没有多好吃
Aunt said the noodle not as good as i thought it would be
64
00:05:34,560 --> 00:05:38,440
但是食材丰富 让人感觉食欲大开
But it have plenty of ingredients, make me feel appetite wide open 
65
00:05:52,560 --> 00:05:56,440
面条是干的 没有任何的汤汁 加了辣子
Noodle is dry and without soup but add spicy pepper
66
00:05:58,080 --> 00:06:02,600
这个焖面加上辣子 辣子是香而不辣的
This noodle with spicy pepper, and it is fragment but not spicy
67
00:06:02,600 --> 00:06:05,880
但是很下面条
Feel so good with noodle
68
00:06:10,400 --> 00:06:12,920
觉得不够 这边还有
There’s more if you want more
69
00:06:19,360 --> 00:06:22,400
这哪是用碗装 这是用盆装
This is not a bowl, even larger as pot
70
00:06:25,880 --> 00:06:28,400
有能吃不饱的吗
Everyone will get full by this
71
00:06:33,960 --> 00:06:35,200
谢谢
Thank you
72
00:06:40,360 --> 00:06:44,680
面条稍微有些油 有些酱油的咸味
Noodle is a little bit oily with salty taste from soy sauce
73
00:06:44,680 --> 00:06:49,000
面和菜就是这么浑然一体
Noodle and sides are such good combo
74
00:06:54,160 --> 00:06:56,720
吃到现在 菜已经吃光了
Now all sides are gone
75
00:06:56,720 --> 00:07:00,080
然后我们说 把辣子放进去
And we said mix spicy pepper with rest of it
76
00:07:00,080 --> 00:07:03,760
辣子都能当一道菜 配面条来吃
Even spicy pepper are a side with noodle
77
00:07:16,800 --> 00:07:20,800
面馆里的面条是用这种蒸屉蒸出来的
Noodles in the restaurant are make by steamer like this
78
00:07:20,800 --> 00:07:24,160
每卖一屉才会再去蒸一屉
They make new after last is gone
79
00:07:24,160 --> 00:07:27,520
不知不觉的工夫已经卖了三四屉了
About 3 or 4 noodles of steamers are gone in such time
80
00:08:03,880 --> 00:08:06,320
叔 走了 拜拜
Uncle, we gonna go, bye
81
00:08:08,840 --> 00:08:12,200
拍的差不多了 我们要走了
Almost done, we should go
82
00:08:16,400 --> 00:08:20,880
关 注
雪 鱼 探 店
