### ISSUE TITLE
【美食作家王刚】西湖牛肉羹 - https://youtu.be/p2yltcu5WQk

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1141]
**视频链接**：https://youtu.be/p2yltcu5WQk

视频时长4:16，预计发布时间为北京时间6月11日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：杭帮菜“西湖牛肉羹”的家常做法，江南传统名菜，味道鲜美口感丰富

简介
同学们好，今天和大家分享一道杭帮菜“西湖牛肉羹”，其用料讲究简单新鲜，此菜成羹必须避免过稠，需要保证清淡爽口开胃。最棒的是这道菜口感层次多变并且营养丰富，特别适合老人孩子，想尝试的朋友一定不要错过这样的一道好菜，学习起来！

字幕
0:00:00.460,0:00:01.580
哈喽大家好我是王刚

0:00:01.580,0:00:03.620
本期视频我跟大家分享一道家常菜

0:00:04.100,0:00:05.300
家常牛肉羹

0:00:05.720,0:00:08.700
首先我们准备新鲜的牛里脊肉150克

0:00:08.775,0:00:11.600
切成小片之后再剁成绿豆大小的颗粒备用

0:00:17.450,0:00:19.975
准备老豆腐1小块切成小颗粒备用（约150克）

0:00:19.975,0:00:23.300
同学们最好选择紧实一些的老豆腐这样更香

0:00:28.325,0:00:30.825
准备新鲜的香菇2个切成小颗粒备用

0:00:30.975,0:00:34.875
切香菇的时候也要将香菇蒂留下这样鲜味更浓

0:00:46.025,0:00:47.950
准备适量的海鲜菇切碎备用

0:00:47.950,0:00:50.125
同学们也可以加入各自喜欢的菇类

0:00:50.750,0:00:54.200
“黑白”菇的加入可以代替味精调节牛肉羹的鲜味

0:00:55.475,0:00:57.300
准备适量的香菜切碎备用

0:00:57.300,0:00:59.750
不喜欢香菜的同学可以用小葱代替

0:01:01.550,0:01:05.300
最后准备鸡蛋2个分别将蛋清和蛋黄搅拌均匀备用

0:01:05.650,0:01:08.475
蛋黄和蛋清分别下锅可以让颜色更有层次

0:01:14.700,0:01:16.100
下一步开始制作

0:01:16.300,0:01:18.425
首先我们在锅中加入适量的清水

0:01:20.975,0:01:22.350
再加入适量的食用盐

0:01:22.550,0:01:26.500
然后将切好的豆腐，菇类，牛肉粒依次下锅焯水

0:01:26.600,0:01:28.550
这一步的目的是去除豆腐的豆腥味

0:01:28.575,0:01:30.825
去除菇类的涩味和牛肉的血沫

0:01:42.300,0:01:44.350
大火烧开之后再撇去浮沫

0:01:50.050,0:01:51.650
然后焯好水之后倒出备用

0:01:51.675,0:01:54.750
同学们切记要用到2个漏勺或者改用密漏

0:01:54.750,0:01:56.650
否则会导致竹篮打水一场空

0:01:57.125,0:01:59.150
然后在锅中加入适量的纯净水

0:01:59.150,0:02:01.150
有条件的同学可以改用清汤

0:02:03.375,0:02:05.700
大火烧开之后将焯好水的原料下锅

0:02:11.775,0:02:13.475
然后再继续撇去浮沫

0:02:16.350,0:02:18.250
烧至1分钟之后开始调味

0:02:19.350,0:02:21.850
锅中加入适量的食用盐和胡椒粉即可

0:02:32.250,0:02:34.325
然后将锅离火加入适量的水淀粉

0:02:34.475,0:02:36.825
把汤汁勾成比米汤略稠的芡即可

0:02:46.875,0:02:49.650
重新烧开之后加入准备好的蛋黄和蛋清

0:02:49.800,0:02:53.775
同学们切记蛋液必须少许慢慢的倒入这样成形更好看

0:02:57.375,0:03:00.875
在倒入蛋清的时候泡沫会影响美观但不影响食用

0:03:00.880,0:03:03.100
比较介意的同学可以撇去不要

0:03:13.060,0:03:15.480
最后在起锅之前加入适量的生抽酱油

0:03:22.200,0:03:24.260
再加入切好的香菜即可出锅

0:03:34.080,0:03:36.940
一道营养美味的家常牛肉羹就制作完成

0:03:45.080,0:04:10.680
下面开始技术总结
第一，牛肉最好选择里脊或者外脊，这样老人和孩子更加容易消化
第二，所有原材料最好事先焯水，这样可以去除大部分的涩味和腥味（豆腥味和牛肉血腥味）
第三，水淀粉不能一次性倒入，新手必须少量多次的添加，否则容易过于浓稠无法补救
第四，此菜适合四季食用，冬天暖胃夏天消暑，特别适合胃口不好的老人和孩子
家常牛肉羹的技术总结完毕


```

**Comment by KristenXChen** [comment]
认领

**Comment by KristenXChen** [comment]
0:00:00.460,0:00:01.580
哈喽大家好我是王刚
Hello, this is Wang Gang

0:00:01.580,0:00:03.620
本期视频我跟大家分享一道家常菜
In this video, I will share the recipe of 

0:00:04.100,0:00:05.300
家常牛肉羹
homemade beef soup

0:00:05.720,0:00:08.700
首先我们准备新鲜的牛里脊肉150克
First, we prepare 150g of fresh beef tenderloin 

0:00:08.775,0:00:11.600
切成小片之后再剁成绿豆大小的颗粒备用
cut the beef into slices before chopping them into half cm size cubes

0:00:17.450,0:00:19.975
准备老豆腐1小块切成小颗粒备用（约150克）
Prepare 150g of firm tofu and cut it into small cubes for later use

0:00:19.975,0:00:23.300
同学们最好选择紧实一些的老豆腐这样更香
Firmer tofu is preferred for a richer flavor

0:00:28.325,0:00:30.825
准备新鲜的香菇2个切成小颗粒备用
Prepare two fresh shiitake mushrooms and dice them into little cubes

0:00:30.975,0:00:34.875
切香菇的时候也要将香菇蒂留下这样鲜味更浓
add the stems of the mushrooms to enrich the flavor

0:00:46.025,0:00:47.950
准备适量的海鲜菇切碎备用
Dice few clamshell mushrooms for later use

0:00:47.950,0:00:50.125
同学们也可以加入各自喜欢的菇类
Other mushrooms can be added based on your preference

0:00:50.750,0:00:54.200
“黑白”菇的加入可以代替味精调节牛肉羹的鲜味
The combination of dark and light colored mushrooms can create a umami flavor, replacing MSG

0:00:55.475,0:00:57.300
准备适量的香菜切碎备用
rough chop some cilantros for later use

0:00:57.300,0:00:59.750
不喜欢香菜的同学可以用小葱代替
for those who dislike cilantros, green onions can be a replacement

0:01:01.550,0:01:05.300
最后准备鸡蛋2个分别将蛋清和蛋黄搅拌均匀备用
lastly, prepare two eggs, whisk the yolks and egg whites separately

0:01:05.650,0:01:08.475
蛋黄和蛋清分别下锅可以让颜色更有层次
Separating yolks and egg whites renders better visual presentation of the dish

0:01:14.700,0:01:16.100
下一步开始制作
now we are ready to cook

0:01:16.300,0:01:18.425
首先我们在锅中加入适量的清水
first, we add the right amount of water in the wok

0:01:20.975,0:01:22.350
再加入适量的食用盐
then add a right amount of salt

0:01:22.550,0:01:26.500
然后将切好的豆腐，菇类，牛肉粒依次下锅焯水
blanch prepared tofu, mushrooms and beef

0:01:26.600,0:01:28.550
这一步的目的是去除豆腐的豆腥味
to remove the beany flavor in tofu

0:01:28.575,0:01:30.825
去除菇类的涩味和牛肉的血沫
astringent flavor in mushroom and blood foams in beef

0:01:42.300,0:01:44.350
大火烧开之后再撇去浮沫
remove the foams after boiling

0:01:50.050,0:01:51.650
然后焯好水之后倒出备用
strain the ingredients for later use

0:01:51.675,0:01:54.750
同学们切记要用到2个漏勺或者改用密漏
use two overlapped strainers or a single strainer with small holes

0:01:54.750,0:01:56.650
否则会导致竹篮打水一场空
to prevent ingredients from falling out

0:01:57.125,0:01:59.150
然后在锅中加入适量的纯净水
add filtered water in the wok

0:01:59.150,0:02:01.150
有条件的同学可以改用清汤
clear stock is also a good option

0:02:03.375,0:02:05.700
大火烧开之后将焯好水的原料下锅
add blanched ingredients after boiling

0:02:11.775,0:02:13.475
然后再继续撇去浮沫
remove the excess foams

0:02:16.350,0:02:18.250
烧至1分钟之后开始调味
cook for 1 minute before seasoning

0:02:19.350,0:02:21.850
锅中加入适量的食用盐和胡椒粉即可
add a right amount of salt and white pepper powder

0:02:32.250,0:02:34.325
然后将锅离火加入适量的水淀粉
remote the wok from the stove and add a right amount of slurry

0:02:34.475,0:02:36.825
把汤汁勾成比米汤略稠的芡即可
till the broth is slightly thicker than congee.

0:02:46.875,0:02:49.650
重新烧开之后加入准备好的蛋黄和蛋清
bring it to boil and add the whisked yolks and egg whites

0:02:49.800,0:02:53.775
同学们切记蛋液必须少许慢慢的倒入这样成形更好看
pour the yolks and egg whites slowly for a better visual presentation of the dish

0:02:57.375,0:03:00.875
在倒入蛋清的时候泡沫会影响美观但不影响食用
foams can form while pouring but doesn’t affect the taste

0:03:00.880,0:03:03.100
比较介意的同学可以撇去不要
remove the foam if a good visual presentation is required

0:03:13.060,0:03:15.480
最后在起锅之前加入适量的生抽酱油
add the right amount of soy sauce 

0:03:22.200,0:03:24.260
再加入切好的香菜即可出锅
add chopped cilantro before pouring the soup out of the wok

0:03:34.080,0:03:36.940
一道营养美味的家常牛肉羹就制作完成
The delicious and nutritious homemade beef soup is done

0:03:45.080,0:04:10.680
下面开始技术总结
第一，牛肉最好选择里脊或者外脊，这样老人和孩子更加容易消化
第二，所有原材料最好事先焯水，这样可以去除大部分的涩味和腥味（豆腥味和牛肉血腥味）
第三，水淀粉不能一次性倒入，新手必须少量多次的添加，否则容易过于浓稠无法补救
第四，此菜适合四季食用，冬天暖胃夏天消暑，特别适合胃口不好的老人和孩子
家常牛肉羹的技术总结完毕
Below is the summary of key points
Firstly, digestive tenderloin is preferred ingredients for this dish
Secondly, blanch the ingredients ahead of time to remove bitterness and beany flavors in tofu and blood foams in beef.
thirdly, pour the slurry slowly to prevent overly thickened broth
Fourthly, this dish is suitable for all seasons. It is stomach warming during the winter and cooling during the summer, best suited for olderlys and children with digestive problems.
