### ISSUE TITLE
[手工耿] 洗衣機器人 - https://youtu.be/fVgjoh4oYBQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1142]
https://youtu.be/fVgjoh4oYBQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 8, 2020 at 07:00PM</p>
<p>&#26631;&#39064;<br>
&#12304;&#25163;&#24037;&#32831;&bull;Useless Edison&#12305;&#33258;&#35069;&#26371;&#27927;&#34915;&#26381;&#30340;&#27231;&#22120;&#20154;&#65292;&#35299;&#25918;&#38617;&#25163;&#36229;&#23526;&#29992;&#65281;</p>
<p>&#31616;&#20171;<br>
&#27927;&#34915;&#27231;&#22750;&#20102;&#24590;&#40636;&#36774;&#65311;&#21448;&#19981;&#24819;&#25163;&#25619;&#34915;&#26381;&#24590;&#40636;&#36774;&#65311; &#37027;&#23601;&#21205;&#25163;&#35069;&#20316;&#19968;&#20491;&#27927;&#34915;&#27231;&#22120;&#20154;&#21543;&#65292;&#20197;&#24460;&#22352;&#26049;&#37002;&#21917;&#33590;&#23601;&#22909;&#21862;&#65281; &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #UselessEdison #&#32831;&#24101; #ChineseEdison #shougonggeng #handicraft #diy #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #inventions #&#20013;&#22283;&#30332;&#26126; #&#20013;&#22283;&#24859;&#36842;&#29983; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by p1ach** [comment]
认领
