### ISSUE TITLE
[雪鱼] 裤带蘸水面4min - https://youtu.be/THuwUxiPLgw

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1179]
**视频链接**：<https://youtu.be/THuwUxiPLgw>

# 请翻译以下全部内容

```

字幕
<1
00:00:01,920 --> 00:00:04,000
陕西·西安

2
00:00:04,000 --> 00:00:05,980
我坐在板凳上看人家吃面条

3
00:00:06,120 --> 00:00:08,600
每个人都是抱着一个不锈钢的盆

4
00:00:08,600 --> 00:00:13,600
眼睁睁地看着他们 吃完了一整盆的面条

5
00:00:13,600 --> 00:00:16,400
这陕西十大怪当中的碗盆难分开

6
00:00:16,400 --> 00:00:18,560
我今天算是见识到了

7
00:00:18,720 --> 00:00:21,080
在陕西 尤其是关中地区

8
00:00:21,080 --> 00:00:23,080
面食的吃法是多种多样

9
00:00:23,080 --> 00:00:25,600
如果你和我一样 来这边走一遭

10
00:00:25,600 --> 00:00:28,120
怕是顿顿也不带重样的

11
00:00:40,480 --> 00:00:44,160
蘸水面

12
00:00:48,920 --> 00:00:50,920
我要了一个裤带蘸水面

13
00:00:50,920 --> 00:00:53,000
阿姨先端来了一个小碗

14
00:00:53,000 --> 00:00:55,960
我说 不应该是面条像裤带吗 怎么碗这么小

15
00:00:55,960 --> 00:00:58,400
放近了一看才发现

16
00:00:58,400 --> 00:01:00,080
这个只是蘸水

17
00:01:00,080 --> 00:01:03,640
真正的面条在这里 用盆装的

18
00:01:03,640 --> 00:01:06,520
面条真的是像裤带一样

19
00:01:06,520 --> 00:01:08,480
又宽 又粗

20
00:01:08,480 --> 00:01:11,200
关键这一盆才12块钱

21
00:01:14,600 --> 00:01:17,120
别的地方加面条都是再加一些

22
00:01:17,120 --> 00:01:21,160
这边面条是按根来加 一根3块钱

23
00:01:22,520 --> 00:01:25,480
端上来的除了面条之外 还有蘸水

24
00:01:25,480 --> 00:01:27,840
能够看到蘸水红油油的

25
00:01:27,840 --> 00:01:32,080
上面就是芝麻 辣子 香葱和蒜末

26
00:01:32,920 --> 00:01:36,440
是西红柿卤子吧

27
00:01:36,440 --> 00:01:40,600
你看 咱们在这边吃面 他们一般都会先剥一瓣蒜

28
00:01:40,600 --> 00:01:42,200
但是我看里面是有蒜汁的

29
00:01:42,200 --> 00:01:43,800
咱们就不剥蒜了

30
00:01:43,800 --> 00:01:48,760
直接是把面条扯进蘸水里

31
00:01:49,600 --> 00:01:53,080
面条真的是又长又宽

32
00:01:55,320 --> 00:02:00,600
我弄了老半天 这一根面条都没有到头

33
00:02:06,680 --> 00:02:08,800
这才是一根面

34
00:02:08,800 --> 00:02:13,280
这一根面就顶普通的一碗面

35
00:02:24,960 --> 00:02:27,320
面条就像大面皮一样

36
00:02:27,320 --> 00:02:29,360
蘸水真的是很有味

37
00:02:29,360 --> 00:02:31,920
里面有西红柿的酸甜感

38
00:02:31,920 --> 00:02:35,280
还有芝麻和辣椒的香味

39
00:02:35,280 --> 00:02:38,840
蒜汁放在里面 一点不会觉得突兀

40
00:02:53,320 --> 00:02:57,080
这一根面进去 盆里就像少了好多面条一样

41
00:02:57,080 --> 00:03:02,280
平常的话 姑娘吃一根就差不多了 两根都有点撑了

42
00:03:02,280 --> 00:03:04,600
男的 可以多加一根

43
00:03:08,400 --> 00:03:13,800
一根面条1两7

44
00:03:21,160 --> 00:03:24,640
1两7x4根

45
00:03:29,040 --> 00:03:34,200
咱们都是按照我们当地人的饭量做的

46
00:03:34,200 --> 00:03:39,200
见过最多的人吃几根  最多的能吃16根

47
00:03:39,560 --> 00:03:41,680
很胖吗

48
00:03:41,680 --> 00:03:44,000
不胖 个子还没他高

49
00:03:44,000 --> 00:03:46,640
特别能吃 一来就是16根

50
00:03:46,640 --> 00:03:50,080
像南方人吃不完这一份

51
00:03:50,080 --> 00:03:53,320
他们也就两根就吃撑了

52
00:03:53,320 --> 00:03:57,360
咱们当地人就是 基本上4根够吃

53
00:03:57,360 --> 00:03:58,720
4根差不多

54
00:03:58,720 --> 00:04:00,040
4根都吃饱了

55
00:04:00,040 --> 00:04:03,000
在咱家吃面就是两怪

56
00:04:03,000 --> 00:04:06,680
一个是 面条宽

57
00:04:06,680 --> 00:04:09,320
另一个大老碗  碗盆分不开

58
00:04:09,320 --> 00:04:12,200
12块钱一盆面

59
00:04:22,800 --> 00:04:26,200
关 注
雪 鱼 探 店

>
```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
字幕
<1
00:00:01,920 --> 00:00:04,000
陕西·西安
Xi’an, Shanxi
2
00:00:04,000 --> 00:00:05,980
我坐在板凳上看人家吃面条
I’m watching them eating noodle while i’m on the wooden bench
3
00:00:06,120 --> 00:00:08,600
每个人都是抱着一个不锈钢的盆
Everyone are holding a stainless steel pot
4
00:00:08,600 --> 00:00:13,600
眼睁睁地看着他们 吃完了一整盆的面条
And they finished a whole pot of noodle
5
00:00:13,600 --> 00:00:16,400
这陕西十大怪当中的碗盆难分开
It’s called “Bowls as big as basins” in Shanxi Ten strange customs
6
00:00:16,400 --> 00:00:18,560
我今天算是见识到了
I saw it today
7
00:00:18,720 --> 00:00:21,080
在陕西 尤其是关中地区
In Shanxi, expecilly in Guanzhong area
8
00:00:21,080 --> 00:00:23,080
面食的吃法是多种多样
There are many ways to eat wheat flour products
9
00:00:23,080 --> 00:00:25,600
如果你和我一样 来这边走一遭
If you come here just like me
10
00:00:25,600 --> 00:00:28,120
怕是顿顿也不带重样的
You will not have same meals every day
11
00:00:40,480 --> 00:00:44,160
蘸水面
Zhanshui noodle
12
00:00:48,920 --> 00:00:50,920
我要了一个裤带蘸水面
I ordered a belt zhanshui noodle
13
00:00:50,920 --> 00:00:53,000
阿姨先端来了一个小碗
The auntie brought a small bowl first
14
00:00:53,000 --> 00:00:55,960
我说 不应该是面条像裤带吗 怎么碗这么小
I say, isn’t the noodle as long as the belt? Why is the bowl so small?
15
00:00:55,960 --> 00:00:58,400
放近了一看才发现
I took a closer look and found out 
00:00:58,400 --> 00:01:00,080
这个只是蘸水
This is a Zhanshui(lit:”dipping soup”)
17
00:01:00,080 --> 00:01:03,640
真正的面条在这里 用盆装的
The noodle actually is in the pot
18
00:01:03,640 --> 00:01:06,520
面条真的是像裤带一样
The noodle looks like a belt
19
00:01:06,520 --> 00:01:08,480
又宽 又粗
Wide and thick
20
00:01:08,480 --> 00:01:11,200
关键这一盆才12块钱
The noodle in the pot only 12 yuan
21
00:01:14,600 --> 00:01:17,120
别的地方加面条都是再加一些
Other place add some noodles when you order
22
00:01:17,120 --> 00:01:21,160
这边面条是按根来加 一根3块钱
This place add every noodle for 3 yuan
23
00:01:22,520 --> 00:01:25,480
端上来的除了面条之外 还有蘸水
They also serve noodles with zhanshui

24
00:01:25,480 --> 00:01:27,840
能够看到蘸水红油油的
We can see zhanshui is red and oily
25
00:01:27,840 --> 00:01:32,080
上面就是芝麻 辣子 香葱和蒜末
With sesame, spicy pepper, green onion, mashed garlic on the top
26
00:01:32,920 --> 00:01:36,440
是西红柿卤子吧
Is that tomato soup?
27
00:01:36,440 --> 00:01:40,600
你看 咱们在这边吃面 他们一般都会先剥一瓣蒜
You can see they will peel a garlic before eat noodle
28
00:01:40,600 --> 00:01:42,200
但是我看里面是有蒜汁的
But I saw there is garlic sauce
29
00:01:42,200 --> 00:01:43,800
咱们就不剥蒜了
So we don’t need to
30
00:01:43,800 --> 00:01:48,760
直接是把面条扯进蘸水里
Just put noodle in the Zhanshui
31
00:01:49,600 --> 00:01:53,080
面条真的是又长又宽
The noodle are very widely and thickly
32
00:01:55,320 --> 00:02:00,600
我弄了老半天 这一根面条都没有到头
I can’t reach to the end of the noodle
33
00:02:06,680 --> 00:02:08,800
这才是一根面
This is a noodle
34
00:02:08,800 --> 00:02:13,280
这一根面就顶普通的一碗面
A noodle like this can compared with regular noodles
35
00:02:24,960 --> 00:02:27,320
面条就像大面皮一样
Like “da mian pi”
36
00:02:27,320 --> 00:02:29,360
蘸水真的是很有味
Zhanshui are very delicious
37
00:02:29,360 --> 00:02:31,920
里面有西红柿的酸甜感
With sourness from tomatoes
38
00:02:31,920 --> 00:02:35,280
还有芝麻和辣椒的香味
And fragment of sesame and spicy pepper as well
39
00:02:35,280 --> 00:02:38,840
蒜汁放在里面 一点不会觉得突兀
Garlic sauce in the Zhanshui will not make you feel weird at all
40
00:02:53,320 --> 00:02:57,080
这一根面进去 盆里就像少了好多面条一样
It feel there are so many noodles are missing when i finish a noodle
41
00:02:57,080 --> 00:03:02,280
平常的话 姑娘吃一根就差不多了 两根都有点撑了
Normally, one noodle is enough for lady, two is full
42
00:03:02,280 --> 00:03:04,600
男的 可以多加一根
Man can have one more noodle
43
00:03:08,400 --> 00:03:13,800
一根面条1两7
The weight of a noodle is about 1.7 liang85 grams
44
00:03:21,160 --> 00:03:24,640
1两7x4根
Multiply by four
45
00:03:29,040 --> 00:03:34,200
咱们都是按照我们当地人的饭量做的
We all cook according to food amount of our local people 
46
00:03:34,200 --> 00:03:39,200
见过最多的人吃几根  最多的能吃16根
How many noodles have you seen people who eat most? 16 
47
00:03:39,560 --> 00:03:41,680
很胖吗
Is he fat?
48
00:03:41,680 --> 00:03:44,000
不胖 个子还没他高
No, not as tall as him
49
00:03:44,000 --> 00:03:46,640
特别能吃 一来就是16根
He eat a lot
50
00:03:46,640 --> 00:03:50,080
像南方人吃不完这一份
People who from south of China can not finish it
51
00:03:50,080 --> 00:03:53,320
他们也就两根就吃撑了
They eat 2 noodles at most
52
00:03:53,320 --> 00:03:57,360
咱们当地人就是 基本上4根够吃
Our local people usually eat four noodles
53
00:03:57,360 --> 00:03:58,720
4根差不多
About four noodles
54
00:03:58,720 --> 00:04:00,040
4根都吃饱了
They will get full with four noodles
55
00:04:00,040 --> 00:04:03,000
在咱家吃面就是两怪
There is two strange things in my restaurant 
56
00:04:03,000 --> 00:04:06,680
一个是 面条宽
First, noodle is widely 
57
00:04:06,680 --> 00:04:09,320
另一个大老碗  碗盆分不开
Second is Bowls as big as basins
58
00:04:09,320 --> 00:04:12,200
12块钱一盆面
12 yuan for a pot of noodle
59
00:04:22,800 --> 00:04:26,200
关 注
雪 鱼 探 店
Subscribe xueyu 
>

**Comment by Kevinzheng5** [comment]
认领
