### ISSUE TITLE
【美食作家王刚】杭州之行 - https://youtu.be/RivS8qxCSj0

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1199]
**视频链接**：https://youtu.be/RivS8qxCSj0

视频时长10:45，预计发布时间为北京时间6月26日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
杭州之行！带父亲逛西湖，再去拜访一下影视飓风的Tim，不虚此行，真的学到了很多！

简介
大家好，拍视频教大家做菜有几年时间了，内容本身自认为有一些经验，但在拍摄后期设备等等方面的确还不够专业，总觉得还能做得更好。为了能给大家呈现出更加好的画质，更专业的内容，我决定去杭州找Tim去取取经，看看专业的科技型视频创作者的工作室，这次杭州之旅不虚此行，学到了很多！

字幕
0:00:00.325,0:00:01.285
哈喽大家好

0:00:01.500,0:00:03.375
今天是父亲节

0:00:03.525,0:00:05.550
带我老爸到杭州去玩一下

0:00:06.075,0:00:07.550
然后把我女儿也带上

0:00:07.550,0:00:10.125
这样才能显示出我也在过节

0:00:11.301,0:00:14.150
现在我们就开车到机场

0:00:14.400,0:00:15.225
走嘛

0:00:20.999,0:00:23.898
沺沺和爸爸一起出去玩开心吗

0:00:23.925,0:00:25.000
开心

0:00:33.675,0:00:36.800
今天杭州西湖这里下很大的雨

0:00:37.575,0:00:43.020
所以我们今天只能说买把伞走一走就算了

0:00:43.020,0:00:44.100
是不是宝贝

0:00:44.675,0:00:47.450
下雨不是特别好

0:00:48.175,0:00:49.625
到处都是水对不对

0:00:49.625,0:00:51.050
而且还起风有点冷

0:00:51.350,0:00:52.925
我们四川要热得多

0:00:52.925,0:00:55.675
所以带孩子和老爸到这里来逛一圈

0:00:56.075,0:00:56.575
走嘛

0:01:04.050,0:01:05.950
这边的柳树很漂亮对吧

0:01:06.350,0:01:07.025
对

0:01:07.700,0:01:09.265
这边还有桃树

0:01:10.775,0:01:14.525
待会带你去吃西湖醋鱼好不好

0:01:15.175,0:01:16.300
喜欢吃吗

0:01:19.875,0:01:21.725
它以为你有东西喂它

0:01:21.725,0:01:22.425
来

0:01:24.575,0:01:25.975
丢 再丢

0:01:27.375,0:01:28.525
它走啦

0:01:28.700,0:01:31.225
不可以踩小草快出来

0:01:35.525,0:01:37.900
你走一会吧好不好 爸爸牵

0:01:38.425,0:01:39.950
虽然今天天气不怎么好

0:01:39.975,0:01:41.725
但是还是来玩一趟嘛

0:01:41.725,0:01:44.600
来都来了一千多公里是吧

0:01:45.925,0:01:48.525
还是来逛一圈下大雨也要来逛一圈

0:02:11.800,0:02:13.126
上二楼在哪里

0:02:13.126,0:02:14.214
二楼这边上

0:02:17.525,0:02:19.200
头发都散了

0:04:24.728,0:04:25.791
哈喽 大家好

0:04:26.170,0:04:31.105
本来是说这两天带我老爸和女儿到西湖玩一下

0:04:31.105,0:04:32.254
结果这两天在下雨

0:04:32.755,0:04:36.273
所以正好到这边去拜访一个朋友 一个老师

0:04:36.603,0:04:39.504
你们猜一下是谁 跟他学习学习

0:04:39.511,0:04:43.152
现在我们在这个工业园区这里 走吧

0:04:48.943,0:04:49.981
哈喽

0:04:49.981,0:04:51.435
哈喽哈喽

0:04:53.720,0:04:54.783
你好你好

0:04:55.491,0:04:57.092
王老师好王老师好

0:04:57.153,0:04:58.644
哈喽哈喽 你们好

0:04:58.717,0:04:59.499
来吧来吧

0:05:00.721,0:05:01.710
全员迎接

0:05:02.077,0:05:03.066
我们公司人比较多

0:05:07.929,0:05:11.044
比我们工作室要大很多倍

0:05:11.044,0:05:11.411
是吗

0:05:11.533,0:05:15.312
对 我们总共才十多台电脑

0:05:15.418,0:05:16.383
这才只是1号

0:05:16.786,0:05:20.806
我们这边直播 直播平时我们在这边播

0:05:21.319,0:05:22.126
来 宝贝

0:05:23.359,0:05:28.161
看一下 你平时只要这边机位开起来以后你只要坐下

0:05:28.381,0:05:30.666
然后你看这边全部就能看到你自己的情况

0:05:30.739,0:05:34.329
然后下面大家刷什么弹幕啊 互动 然后你的销售额什么

0:05:34.357,0:05:36.690
都可以直接第二个屏幕显示

0:05:37.034,0:05:39.199
所以你可以坐下来感受感受

0:05:39.614,0:05:42.881
然后这是麦克风 你说话的话可以感觉一下

0:05:45.278,0:05:46.409
这个太牛了这个

0:05:47.829,0:05:49.895
给你们点赞 这个真的太牛了

0:05:50.105,0:05:51.532
这个声音是不是很带劲

0:05:53.176,0:05:56.873
嗯 这边就是平时切换啊 导播 要做一个渐影

0:05:56.873,0:06:00.373
做什么效果都可以用一个人来控

0:06:00.380,0:06:02.094
然后这边是声音 声控

0:06:05.242,0:06:06.051
全部都自动对焦

0:06:06.704,0:06:10.120
然后这是电影机的画质 其实也不重

0:06:10.120,0:06:11.989
体验一下

0:06:14.403,0:06:14.988
诶 不重

0:06:14.988,0:06:16.306
不重不重 挺轻的

0:06:17.331,0:06:18.215
没有我想象中的重

0:06:18.215,0:06:21.413
你们现在是用什么在拍 还是用索尼的

0:06:22.616,0:06:24.620
A73 就是我们手里的那台A73

0:06:24.848,0:06:25.777
主力机现在

0:06:25.777,0:06:27.882
可以可以 A73够了

0:06:29.194,0:06:30.178
我们这边其实是

0:06:30.333,0:06:31.818
服务器

0:06:31.837,0:06:36.547
对 我们公司其实所有的人都可以进入这个主服务器

0:06:36.684,0:06:39.828
然后服务器的速度非常快 读写都是一个GB一秒

0:06:39.891,0:06:44.101
每个人的电脑可以同时访问同样的素材 可以多个人同时做同一个视频

0:06:44.456,0:06:46.880
看一下 我们这儿奇奇怪怪的屏幕非常多

0:06:46.880,0:06:48.593
特别特别长的 超长的

0:06:48.966,0:06:49.941
5k屏

0:06:50.260,0:06:53.504
动画师 他就是专门负责做我们的动画

0:06:55.335,0:06:58.725
然后我们这边的动画都是他一个人

0:07:02.014,0:07:03.700
你们现在剪片都是用什么在剪

0:07:06.023,0:07:07.700
pr

0:07:08.465,0:07:11.545
其实用达芬奇可能更带劲一点

0:07:12.283,0:07:13.787
这是辣椒面

0:07:13.787,0:07:15.089
从我们老家带过来的

0:07:15.117,0:07:16.620
谢谢 谢谢

0:07:22.561,0:07:25.568
你们的大礼包对吧 多谢多谢

0:07:26.242,0:07:30.461
这个东西也是和这个一样功能的导播台

0:07:30.488,0:07:35.146
但它的优点就是它是同时把3张摄影卡的信号聚到一起推流出去

0:07:35.146,0:07:37.513
这样就不会卡 你在任何地方都可以播

0:07:38.780,0:07:39.572
我看看手感

0:07:41.067,0:07:42.342
挺重的 有一斤

0:07:42.406,0:07:45.857
TS80 然后这你们到时候装在相机或者那个边上

0:07:45.857,0:07:48.092
然后只要把相机信号接上就可以直接播了

0:07:48.438,0:07:50.707
然后这样推出去的信号也是好的

0:07:50.734,0:07:51.837
不会有什么问题

0:07:52.238,0:07:56.547
潘老师又解决我们第一个大难题 直播的问题

0:07:56.547,0:07:57.422
直播老是卡

0:07:57.422,0:08:00.146
那我们还是想看一下潘老师的red

0:08:01.185,0:08:04.593
red拍起来质感就不一样了

0:08:04.620,0:08:05.550
这个画质就真的绝了

0:08:05.805,0:08:07.727
拍出来就不一样 然后

0:08:07.773,0:08:09.103
这个焦没对上

0:08:09.249,0:08:14.142
对 给你拿下来 可以直接拿着用

0:08:16.283,0:08:17.249
这个重量

0:08:17.322,0:08:18.042
其实也还好吧

0:08:18.042,0:08:22.634
比c500重一点点吧 比c500可能重个一两斤

0:08:23.080,0:08:24.566
可以看比如我坐在这里

0:08:26.124,0:08:28.092
然后它这个主要是都是触摸屏的

0:08:28.429,0:08:29.440
还是触摸屏的

0:08:29.440,0:08:31.800
对 所以调起来就特别特别方便

0:08:31.837,0:08:34.552
比如说这边按了以后

0:08:34.743,0:08:36.411
这个应该有六七斤吧

0:08:36.730,0:08:38.269
但这个确实画质看起来很厉害

0:08:38.743,0:08:40.474
这个画质还是感觉又有点不一样

0:08:41.150,0:08:45.058
确实red就有最好的视觉上的感觉和画质

0:08:45.058,0:08:47.837
这个我比较喜欢 这个就是很老式的

0:08:47.891,0:08:50.189
电影放映机

0:08:50.689,0:08:52.556
也是特别老的放胶片的

0:08:54.051,0:08:55.818
小时候那个是吧

0:08:55.818,0:08:57.085
对对 这就是小时候

0:08:57.459,0:08:58.634
这个还可以用的吗

0:08:58.689,0:08:59.636
可以用可以用

0:09:01.413,0:09:02.242
这个就厉害了

0:09:02.279,0:09:02.998
对 这个挺好的

0:09:03.090,0:09:07.873
我记得我们小时候那个要挑啊 挑着去学校放

0:09:07.891,0:09:08.411
对对对

0:09:08.474,0:09:11.272
然后每个人收一块钱还是五毛钱

0:09:11.272,0:09:13.121
这也差不多 以前就是这样

0:09:13.531,0:09:14.907
对这个印象很深很深

0:09:15.008,0:09:17.659
这种全向屏的立体声

0:09:18.215,0:09:20.420
感觉身临其境 站在你身边的感觉

0:09:20.967,0:09:22.361
我给你们试一下

0:09:25.659,0:09:26.780
这个是实时录的

0:09:26.798,0:09:27.208
嗯

0:09:31.263,0:09:32.292
为什么没有风噪

0:09:32.493,0:09:34.115
对 这个就是啊

0:09:34.379,0:09:35.591
一点风噪都没有

0:09:37.823,0:09:39.472
我们现在剪片都是用达芬奇

0:09:39.472,0:09:39.682
嗯

0:09:39.691,0:09:41.705
我其实也推荐你们转向达芬奇

0:09:41.777,0:09:44.921
因为相对来说会更简单 调色调颜色

0:09:45.486,0:09:49.859
处理佳能的东西会更加有优势一点

0:09:50.944,0:09:52.830
佳能相机拍出来的更有优势

0:09:53.431,0:09:55.290
对 佳能拍出来的会更有优势一点

0:09:55.992,0:09:57.632
然后比如说调色的话

0:09:57.850,0:10:02.124
调色的话就是比如说这边可以red的话它最大的优势

0:10:02.206,0:10:05.564
就是它可以后期转成ut 后期转成ut就行

0:10:06.005,0:10:09.750
然后比如说我们可以套一个lut 就是调色的lut

0:10:11.527,0:10:13.222
然后现在可以给你调出这种感觉

0:10:13.695,0:10:16.575
这个质感是完全是无法比拟的

0:10:16.821,0:10:19.390
然后我们就到时候有任何问题问我就行了

0:10:21.869,0:10:23.190
有什么问题尽管问

0:10:23.208,0:10:27.071
我们到时候拉个群 我们可以拉个群到时有问题（就问） 简单 这个好办

0:10:27.071,0:10:29.750
今天太耽误您时间了

0:10:29.750,0:10:30.543
没有没有

0:10:32.611,0:10:33.946
行了今天差不多

0:10:33.951,0:10:35.135
行行行 多谢多谢

0:10:36.010,0:10:37.732
欢迎欢迎 特地跑这么远过来

0:10:38.643,0:10:39.053
行了行了

0:10:39.308,0:10:42.142
好 沺沺 我们准备回去了


```

**Comment by Chuwanggangsiqiu** [comment]
认领

**Comment by Chuwanggangsiqiu** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
杭州之行！带父亲逛西湖，再去拜访一下影视飓风的Tim，不虚此行，真的学到了很多！
We are going to Hangzhou, brought my father to Xihu. And visited Yingshidianfeng’s Tim, it’s a worthwhile trip, learned so much!
简介
大家好，拍视频教大家做菜有几年时间了，内容本身自认为有一些经验，但在拍摄后期设备等等方面的确还不够专业，总觉得还能做得更好。为了能给大家呈现出更加好的画质，更专业的内容，我决定去杭州找Tim去取取经，看看专业的科技型视频创作者的工作室，这次杭州之旅不虚此行，学到了很多！
Hi Everyone, I have been teaching cooking for a few years already, I believe there is some experience throughout the content, but our filming, post-production, equipment are still not professional enough, though we could do better. To present better image quality and more professional content, I decided to go to Hangzhou and learn from Tim, to have a look in a tech-based video producer’s studio, it was a worthwhile trip, learned so much!!!
字幕
0:00:00.325,0:00:01.285
哈喽大家好
Hello, Everyone
0:00:01.500,0:00:03.375
今天是父亲节
Today is Father’s Day
0:00:03.525,0:00:05.550
带我老爸到杭州去玩一下
Bring my dad to have fun in Hangzhou
0:00:06.075,0:00:07.550
然后把我女儿也带上
And my daughter, too
0:00:07.550,0:00:10.125
这样才能显示出我也在过节
In this way, I’m celebrating as well
0:00:11.301,0:00:14.150
现在我们就开车到机场
Now, we are driving to the airport 
0:00:14.400,0:00:15.225
走嘛
Let’s go
0:00:20.999,0:00:23.898
沺沺和爸爸一起出去玩开心吗
Tiantian, are you happy going out with your dad?
0:00:23.925,0:00:25.000
开心
Happy!!!!
0:00:33.675,0:00:36.800
今天杭州西湖这里下很大的雨
It’s raining hard in Xihu Hangzhou today
0:00:37.575,0:00:43.020
所以我们今天只能说买把伞走一走就算了
We can merely have a walk with purchased an umbrella 
0:00:43.020,0:00:44.100
是不是宝贝
Isn’t it, babe?
0:00:44.675,0:00:47.450
下雨不是特别好
Raining is not good
0:00:48.175,0:00:49.625
到处都是水对不对
Waters are everywhere, right?
0:00:49.625,0:00:51.050
而且还起风有点冷
And it also feels a bit cold with wind rises 
0:00:51.350,0:00:52.925
我们四川要热得多
Sichuan is much warmer than here
0:00:52.925,0:00:55.675
所以带孩子和老爸到这里来逛一圈
So, we went to this place 
0:00:56.075,0:00:56.575
走嘛
Let’s go
0:01:04.050,0:01:05.950
这边的柳树很漂亮对吧
These willows are pretty，right?
0:01:06.350,0:01:07.025
对
Yah~
0:01:07.700,0:01:09.265
这边还有桃树
There are peach trees as well
0:01:10.775,0:01:14.525
待会带你去吃西湖醋鱼好不好
I will take you to have West Lake vinegar fish later, Yah?
0:01:15.175,0:01:16.300
喜欢吃吗
Do you like it?
0:01:19.875,0:01:21.725
它以为你有东西喂它
I thought you have something to feed it
0:01:21.725,0:01:22.425
来
Come
0:01:24.575,0:01:25.975
丢 再丢
Throw, a bit more
0:01:27.375,0:01:28.525
它走啦
It’s gone
0:01:28.700,0:01:31.225
不可以踩小草快出来
You can’t step on the lawn
0:01:35.525,0:01:37.900
你走一会吧好不好 爸爸牵
Can you walk a little? Daddy will be holding your hand 
0:01:38.425,0:01:39.950
虽然今天天气不怎么好
Although the weather is not that good 
0:01:39.975,0:01:41.725
但是还是来玩一趟嘛
But we are having a trip 
0:01:41.725,0:01:44.600
来都来了一千多公里是吧
We are already here, traveled more than 1000Km
0:01:45.925,0:01:48.525
还是来逛一圈下大雨也要来逛一圈
Have a walk even it’s raining right now 
0:02:11.800,0:02:13.126
上二楼在哪里
Where is the second floor?
0:02:13.126,0:02:14.214
二楼这边上
It’s over that side
0:02:17.525,0:02:19.200
头发都散了
Your hair is all loose
0:04:24.728,0:04:25.791
哈喽 大家好
Hello Everyone
0:04:26.170,0:04:31.105
本来是说这两天带我老爸和女儿到西湖玩一下
We have planned to take my father and daughter have a trip to Xihu
0:04:31.105,0:04:32.254
结果这两天在下雨
But as a result, is raining all-day
0:04:32.755,0:04:36.273
所以正好到这边去拜访一个朋友 一个老师
So we are going to visit one of my friend, a master~
0:04:36.603,0:04:39.504
你们猜一下是谁 跟他学习学习
Guess who it is, we are going to learn from him
0:04:39.511,0:04:43.152
现在我们在这个工业园区这里 走吧
Now we are in the industrial park, let’s go
0:04:48.943,0:04:49.981
哈喽
Hello
0:04:49.981,0:04:51.435
哈喽哈喽
Hello, Hello
0:04:53.720,0:04:54.783
你好你好
Hi
0:04:55.491,0:04:57.092
王老师好王老师好
Hi, Chief Wang 
0:04:57.153,0:04:58.644
哈喽哈喽 你们好
Hello, everyone 
0:04:58.717,0:04:59.499
来吧来吧
Come on 
0:05:00.721,0:05:01.710
全员迎接
Full team greeting
0:05:02.077,0:05:03.066
我们公司人比较多
We have a lot of people here 
0:05:07.929,0:05:11.044
比我们工作室要大很多倍
The studio is many times larger than ours 
0:05:11.044,0:05:11.411
是吗
Is it?
0:05:11.533,0:05:15.312
对 我们总共才十多台电脑
Yah, we only have over ten computers in total 
0:05:15.418,0:05:16.383
这才只是1号
This is just the first one 
0:05:16.786,0:05:20.806
我们这边直播 直播平时我们在这边播
We normally have live-streaming here, 
0:05:21.319,0:05:22.126
来 宝贝
Come on babe
0:05:23.359,0:05:28.161
看一下 你平时只要这边机位开起来以后你只要坐下
Have a look, you can just sit down when you start filming
0:05:28.381,0:05:30.666
然后你看这边全部就能看到你自己的情况
And you can have a clear sight of yourself at here
0:05:30.739,0:05:34.329
然后下面大家刷什么弹幕啊 互动 然后你的销售额什么
And the real-time comment, interaction, and your sales 
0:05:34.357,0:05:36.690
都可以直接第二个屏幕显示
It can show up on the second screen
0:05:37.034,0:05:39.199
所以你可以坐下来感受感受
You can sit down and have a feel
0:05:39.614,0:05:42.881
然后这是麦克风 你说话的话可以感觉一下
And this is the Microphone, you can have a feel
0:05:45.278,0:05:46.409
这个太牛了这个
This is decent 
0:05:47.829,0:05:49.895
给你们点赞 这个真的太牛了
I will give a thumb up for this, this is insane!
0:05:50.105,0:05:51.532
这个声音是不是很带劲
Sounds energetic, right?
0:05:53.176,0:05:56.873
嗯 这边就是平时切换啊 导播 要做一个渐影
Yeah, if you want to switch the screen, making a long shadow in broadcasting
0:05:56.873,0:06:00.373
做什么效果都可以用一个人来控
Any animations can be controlled by one person 
0:06:00.380,0:06:02.094
然后这边是声音 声控
And here is the volume control 
0:06:05.242,0:06:06.051
全部都自动对焦
It‘s all auto-focused
0:06:06.704,0:06:10.120
然后这是电影机的画质 其实也不重
And this is the filming camera quality, it’s not heavy 
0:06:10.120,0:06:11.989
体验一下
Have a feel
0:06:14.403,0:06:14.988
诶 不重
Yah, it’s not heavy 
0:06:14.988,0:06:16.306
不重不重 挺轻的
Yeah, it’s pretty light
0:06:17.331,0:06:18.215
没有我想象中的重
It’s not as heavy as I thought
0:06:18.215,0:06:21.413
你们现在是用什么在拍 还是用索尼的
What are you guys filming with? Are you still using SONY?
0:06:22.616,0:06:24.620
A73 就是我们手里的那台A73
SONY A7iii it’s what we are having right now 
0:06:24.848,0:06:25.777
主力机现在
It’ our primary one
0:06:25.777,0:06:27.882
可以可以 A73够了
Yah, A7iii is enough 
0:06:29.194,0:06:30.178
我们这边其实是
This is our server room 
0:06:30.333,0:06:31.818
服务器
Server 
0:06:31.837,0:06:36.547
对 我们公司其实所有的人都可以进入这个主服务器
Yah, all the employee will have access to this server 
0:06:36.684,0:06:39.828
然后服务器的速度非常快 读写都是一个GB一秒
And this server’s speed is super-fast, reading speed is one Gigabyte/sec 
0:06:39.891,0:06:44.101
每个人的电脑可以同时访问同样的素材 可以多个人同时做同一个视频
Everyone’s computer can access the same material at the same time and work on the same video. 
0:06:44.456,0:06:46.880
看一下 我们这儿奇奇怪怪的屏幕非常多
Have a look, we have a lot of odd screens
0:06:46.880,0:06:48.593
特别特别长的 超长的
It’s very long 
0:06:48.966,0:06:49.941
5k屏
5K screen
0:06:50.260,0:06:53.504
动画师 他就是专门负责做我们的动画
He is the animator, specialize in our animation production 
0:06:55.335,0:06:58.725
然后我们这边的动画都是他一个人
And he’s the only one who is making animation
0:07:02.014,0:07:03.700
你们现在剪片都是用什么在剪
What are you guys using to do the video clipping? 
0:07:06.023,0:07:07.700
pr
Premiere 
0:07:08.465,0:07:11.545
其实用达芬奇可能更带劲一点
DaVinci Resolve could be more dynamic
0:07:12.283,0:07:13.787
这是辣椒面
This is the chili powder
0:07:13.787,0:07:15.089
从我们老家带过来的
We brought from our hometown 
0:07:15.117,0:07:16.620
谢谢 谢谢
Thank you
0:07:22.561,0:07:25.568
你们的大礼包对吧 多谢多谢
Your gift pack, right?  Thank you
0:07:26.242,0:07:30.461
这个东西也是和这个一样功能的导播台
This broadcast station has the same function as the other one 
0:07:30.488,0:07:35.146
但它的优点就是它是同时把3张摄影卡的信号聚到一起推流出去
But it has the feature of combining signals from three filming cards and push out at the same time 
0:07:35.146,0:07:37.513
这样就不会卡 你在任何地方都可以播
And it will not be lagging, you can broadcast anywhere you want
0:07:38.780,0:07:39.572
我看看手感
Let me try it
0:07:41.067,0:07:42.342
挺重的 有一斤
It’s a bit heavy, about 1 jin (500g)
0:07:42.406,0:07:45.857
TS80 然后这你们到时候装在相机或者那个边上
TS80 and you can put it on the camera or by the side
0:07:45.857,0:07:48.092
然后只要把相机信号接上就可以直接播了
And put on the camera signal, then you can start broadcasting
0:07:48.438,0:07:50.707
然后这样推出去的信号也是好的
The signal is great, too 
0:07:50.734,0:07:51.837
不会有什么问题
There won’t be any issues
0:07:52.238,0:07:56.547
潘老师又解决我们第一个大难题 直播的问题
Master pan have figured out another big problem for us, the live streaming issue
0:07:56.547,0:07:57.422
直播老是卡
Our live streaming always lagging
0:07:57.422,0:08:00.146
那我们还是想看一下潘老师的red
I still want to see master pan’s red
0:08:01.185,0:08:04.593
red拍起来质感就不一样了
The image quality of red is phenomenal
0:08:04.620,0:08:05.550
这个画质就真的绝了
The image quality is decent
0:08:05.805,0:08:07.727
拍出来就不一样 然后
There is a difference when you are filming out
0:08:07.773,0:08:09.103
这个焦没对上
The camera is not focusing
0:08:09.249,0:08:14.142
对 给你拿下来 可以直接拿着用
This can be taken off and used directly
0:08:16.283,0:08:17.249
这个重量
This weight 
0:08:17.322,0:08:18.042
其实也还好吧
It’s actually alright
0:08:18.042,0:08:22.634
比c500重一点点吧 比c500可能重个一两斤
A bit heavier than c500, probably 1-2 jin(0.25kg-0.5kg) heavier 
0:08:23.080,0:08:24.566
可以看比如我坐在这里
Take a look when I’m sitting there
0:08:26.124,0:08:28.092
然后它这个主要是都是触摸屏的
And it’s all touch-screened 
0:08:28.429,0:08:29.440
还是触摸屏的
Touch-screened?
0:08:29.440,0:08:31.800
对 所以调起来就特别特别方便
Yah, so it’s more convenient when you are modulating
0:08:31.837,0:08:34.552
比如说这边按了以后
For example, if you touched here
0:08:34.743,0:08:36.411
这个应该有六七斤吧
This should be about 6-7 jin (3kg-3.5kg)
0:08:36.730,0:08:38.269
但这个确实画质看起来很厉害
But the image quality is fabulous 
0:08:38.743,0:08:40.474
这个画质还是感觉又有点不一样
This image quality feels a bit different
0:08:41.150,0:08:45.058
确实red就有最好的视觉上的感觉和画质
Indeed, red has the best image quality and visual feeling
0:08:45.058,0:08:47.837
这个我比较喜欢 这个就是很老式的
I like this one, this is very old-fashioned 
0:08:47.891,0:08:50.189
电影放映机
Film projector

0:08:50.689,0:08:52.556
也是特别老的放胶片的
And it’s very old and you can put on photographic film 
0:08:54.051,0:08:55.818
小时候那个是吧
The one in childhood, right?
0:08:55.818,0:08:57.085
对对 这就是小时候
Yah, in the childhood
0:08:57.459,0:08:58.634
这个还可以用的吗
Is this still working?
0:08:58.689,0:08:59.636
可以用可以用
Yeah, it’s still functioning 
0:09:01.413,0:09:02.242
这个就厉害了
This is amazing
0:09:02.279,0:09:02.998
对 这个挺好的
Yah, it feels good
0:09:03.090,0:09:07.873
我记得我们小时候那个要挑啊 挑着去学校放
I remember when we're little, we were picking photographic film for it in the school 
0:09:07.891,0:09:08.411
对对对
Yah
0:09:08.474,0:09:11.272
然后每个人收一块钱还是五毛钱
And charging with 0.5-1RMB per person  
0:09:11.272,0:09:13.121
这也差不多 以前就是这样
This is pretty much the same thing, that’s how it looks before
0:09:13.531,0:09:14.907
对这个印象很深很深
This is very impressive to me
0:09:15.008,0:09:17.659
这种全向屏的立体声
This all dimension surrounded sound     
0:09:18.215,0:09:20.420
感觉身临其境 站在你身边的感觉
Feels immersive, like a very close feeling
0:09:20.967,0:09:22.361
我给你们试一下
Let’s try it
0:09:25.659,0:09:26.780
这个是实时录的
This is all real-time 
0:09:26.798,0:09:27.208
嗯
yah
0:09:31.263,0:09:32.292
为什么没有风噪
Why is there no wind noise?
0:09:32.493,0:09:34.115
对 这个就是啊
Yah, that’s how it is 
0:09:34.379,0:09:35.591
一点风噪都没有
No wind noise at all
0:09:37.823,0:09:39.472
我们现在剪片都是用达芬奇
Our video clipping is all made through DaVinci resolve 
0:09:39.472,0:09:39.682
嗯
Yeah
0:09:39.691,0:09:41.705
我其实也推荐你们转向达芬奇
I also recommend you turn into DaVinci 
0:09:41.777,0:09:44.921
因为相对来说会更简单 调色调颜色
Make it a lot easier when you are doing color mixing 
0:09:45.486,0:09:49.859
处理佳能的东西会更加有优势一点
Deal with Cannon will have more advantage 
0:09:50.944,0:09:52.830
佳能相机拍出来的更有优势
Cannon will have the edge 
0:09:53.431,0:09:55.290
对 佳能拍出来的会更有优势一点
Yah, Cannon will have a bit more edge
0:09:55.992,0:09:57.632
然后比如说调色的话
When we talk about color mixing
0:09:57.850,0:10:02.124
调色的话就是比如说这边可以red的话它最大的优势
And that’s the biggest advantage of the red 
0:10:02.206,0:10:05.564
就是它可以后期转成ut 后期转成ut就行
You can convert it into UT during post-production work
0:10:06.005,0:10:09.750
然后比如说我们可以套一个lut 就是调色的lut
For example, we can use the lookup table when we are doing color mixing
0:10:11.527,0:10:13.222
然后现在可以给你调出这种感觉
And now you can have this feeling
0:10:13.695,0:10:16.575
这个质感是完全是无法比拟的
The image quality is extradentary  
0:10:16.821,0:10:19.390
然后我们就到时候有任何问题问我就行了
And you can ask me any question you have later
0:10:21.869,0:10:23.190
有什么问题尽管问
Just ask me if you have any questions 
0:10:23.208,0:10:27.071
我们到时候拉个群 我们可以拉个群到时有问题（就问） 简单 这个好办
We can create a group chat, and let me know any question you have, It’s simple 
0:10:27.071,0:10:29.750
今天太耽误您时间了
I have taken too much time of you today
0:10:29.750,0:10:30.543
没有没有
Nah~
0:10:32.611,0:10:33.946
行了今天差不多
Alright, that’s about it
0:10:33.951,0:10:35.135
行行行 多谢多谢
Okay, thank you so much
0:10:36.010,0:10:37.732
欢迎欢迎 特地跑这么远过来
You are welcome, you came all the way here
0:10:38.643,0:10:39.053
行了行了
kk
0:10:39.308,0:10:42.142
好 沺沺 我们准备回去了
Alright, Tiantian, we are heading back now
