### ISSUE TITLE
[华农兄弟] 华农兄弟去田里逛一下看有什么好吃的摘点来吃 - https://youtu.be/ADbOesLQXSc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1213]
https://youtu.be/ADbOesLQXSc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 27, 2020 at 11:42AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bit, please upload
#https://youtu.be/ADbOesLQXSc

#华农兄弟：去田里逛一下，看有什么好吃的，摘点来吃
#Huanong Brothers: We have a walk around and see if there are any food snacks. Then we pick some.

0:00:27.680,0:00:28.180
# 你看
Look!

0:00:28.820,0:00:29.880
# 很多這個花哦
There are a lot of this kind of flowers.

0:00:30.760,0:00:33.360
# 這個可以吃的  這個  果實可以吃的
These are edible. I mean, the fruits are edible.

0:00:34.940,0:00:36.820
# 現在還沒熟  熟了時候再來
Now they're still green. Let's come again when they're ripe.

0:00:38.160,0:00:40.080
# XXX啊  我們這邊叫  (註︰沒有原字幕)
We call them "o angzi" here.

0:01:04.920,0:01:06.820
# 哇  好多蕉芋花呀
Wa! A lot of Indian shots!

0:01:07.940,0:01:09.540
# 今天又不是情人節
But today is not the Valentine's Day.

0:01:12.340,0:01:13.480
# 這裡  有一個
Here, here's one.

0:01:20.120,0:01:21.180
# 好甜吶
So sweet!

0:01:27.020,0:01:29.040
# 這裡好多這蕉芋花 都沒人吃
Here are many this kind of Indian shots. But nobody wants them,

0:01:30.060,0:01:30.940
# 就我吃
except me.

0:01:33.180,0:01:33.760
# 現在
Now,

0:01:35.640,0:01:37.360
# 年輕人都不在家  (註︰這個「家」是指「老家」，說明清楚會好一點)
the younger people are not in their villages.

0:01:41.740,0:01:42.880
# 嗯  好甜吶
Um! So sweet!

0:01:50.540,0:01:51.920
# 好啦好啦  等下吃飽啦
Enough, enough. Don't get stuffed.

0:01:54.300,0:01:55.400
# 今天又不是甚麼
Today is not any special day.

0:01:55.940,0:01:57.240
# 如果是情人節的話
If it's the Valentine's Day today,

0:01:58.660,0:02:00.800
# 我就拗點去 今天不是
I would bend down some, and bring back home. But it's not.

0:02:01.620,0:02:02.120
# 算啦
Forget it!

0:02:10.380,0:02:11.960
# 你看  這個是西瓜哦
Look! This is a watermelon.

0:02:12.660,0:02:13.420
# 小紅玉來的
It's a "xiaohungyu" (a local watermelon species).

0:02:13.500,0:02:15.540
# 用手指一彈就爆掉了  這個很脆的
A single flick is enough to burst it open. It's really brittle.

0:02:16.040,0:02:18.280
# 而且都是農戶用那個機肥種的
And they're grown by the farmers with organic fertiliser.

0:02:19.520,0:02:21.380
# 到時候我要  拉一車回去
I'm gonna bring one whole cart of them back home,

0:02:22.320,0:02:22.960
# 慢慢吃
and enjoy whenever I like.

0:02:24.540,0:02:25.120
# 很靚的
Beautiful!

0:02:30.200,0:02:33.880
# 你看  這個粘衣服的哦  如果一去的全身衣服都粘滿的
Look! These things stick onto the clothes. They'll be covering all your clothes once you get inside.

0:02:34.580,0:02:36.800
# 想[SIC]人人家種的一樣  長得那麼荿盛
They grow so well that they look as if they're grown by somebody.

0:02:43.940,0:02:47.200
# 你看這個桃子  全部熟了哦  都紅了
Look! These peaches, they're all ripe, and all red now.

0:02:49.300,0:02:51.420
# 你看這個  摘這個來吃一下
Have a look at this one! Let me pick this one and have a try.

0:02:51.820,0:02:52.320
# 誒呦
Eyo!

0:02:53.140,0:02:54.020
# 竟然會掉
Why does it fall?

0:02:59.340,0:02:59.920
# 這個
This one

0:03:00.740,0:03:01.600
# 誒呀  熟啦
Eya! It's ripe now.

0:03:02.180,0:03:03.200
# 裡面的熟啦
It's also ripe inside.

0:03:04.900,0:03:07.360
# 你看  徒手就可以把它剝開
Look! I can simply crack it open by hands.

0:03:11.280,0:03:11.960
# 嗯~
Um~

0:03:12.800,0:03:15.840
# 哇  好香哦  它這個是土桃子來的
Wa! It smells so good! This is our local peach here.

0:03:20.040,0:03:20.620
# 壞了
Rotten

0:03:21.680,0:03:22.440
# 你看下面還有  (註︰這句不明白)
Look! There are more down there.

0:03:23.240,0:03:24.440
# 紅的 就這樣子的
They're all red, just like this one.

0:03:25.200,0:03:26.640
# 有點毛  毛有點多
There's some fur. It's a bit furry.

0:03:36.160,0:03:37.240
# 挑大點的摘
I'm gonna pick the big ones.

0:03:49.080,0:03:49.880
# 你看  這個大
Look! This is big!

0:04:02.500,0:04:03.420
# 還可以哦
Not bad

0:04:06.040,0:04:06.960
# 一樹都是
They're all over the trees.

0:04:09.840,0:04:11.100
# 你看  這個李子樹
Look! This is a plum tree.

0:04:11.900,0:04:15.620
# 好多哦這上面  地上都掉了一地都是  沒人要
There are a lot. They all fell onto the ground. They're everywhere but nobody picks them.

0:04:19.880,0:04:20.380
# 哇
Wa!

0:04:28.300,0:04:30.600
# 掉那麼多  樹都不用上
So many fall down. I don't even need to climb the tree.

0:04:36.020,0:04:36.820
# 紅的
It's red.

0:04:56.580,0:04:57.540
# 摔爆啦
It's crushed.

0:05:02.520,0:05:03.520
# 你看這種李子
Look! This kind of plums,

0:05:04.260,0:05:05.700
# 這種李子很好吃哦  這種李子
this kind of plums is really tasty, this kind of plums.

0:05:07.160,0:05:09.320
# 在農村裡面  吃都沒人吃
The people in the villages don't really like them.

0:05:10.000,0:05:10.860
# 樹上還有好多
There are still a lot in the tree.

0:05:14.160,0:05:15.260
# 你看  這是豬血李哦
Look! This is a "pig blood plum".

0:05:17.060,0:05:17.900
# 都沒人吃
But nobody wants them.

0:05:25.300,0:05:26.300
# 樹上好多
There are a lot in the tree.

0:05:30.080,0:05:31.080
# 袋子又沒帶
But I don't have a bag with me.

0:05:34.180,0:05:34.960
# 留點
Leave some,

0:05:35.940,0:05:37.380
# 留點路過的人吃
leave some to those who pass by.

0:05:39.520,0:05:41.060
# 一個人不要把全部摘掉吧
It's too mean to pick everything for my own self.

0:05:46.880,0:05:47.960
# 這是野生的
They're wild plums,

0:05:49.180,0:05:50.320
# 沒人  沒人要的
and don't, don't belong to anyone.

0:06:08.020,0:06:10.280
# 溜達了一圈  甚麼都沒找到
I've strolled around once, but couldn't find anything special.

0:06:11.420,0:06:14.420
# 不次西瓜熟了時候我們再來  西瓜現在還沒熟
Let's come again when the watermelons become ripe. They're not yet ripe.

0:06:14.840,0:06:16.080
# 熟了之後我們再來
Let's come again when they're ripe.

0:06:16.680,0:06:18.120
# 那邊就一大片都是西瓜
The whole area there are watermelons.

0:06:18.400,0:06:19.420
# 都是兄弟家的
They're all my buddy's.

0:06:20.500,0:06:22.920
# 好啦  今天的視頻就到這裡啦  回去啦
Alright! The video ends here. Let's head back.
