### ISSUE TITLE
【美食作家王刚】厨具配齐 - https://youtu.be/QrDN4EGE7F8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1216]
**视频链接**：https://youtu.be/QrDN4EGE7F8

视频时长5:25，预计发布时间为北京时间6月29日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨具和配件全部到齐，开始撕膜！新后厨工作室基本完工，很快就能投入使用，大家敬请期待！

简介
相信大家已经很期待新的后厨工作室，我也很期待！现在装修水电用具基本全部到位，就剩下一次深度的大扫除和把调料食材等入库，基本上都是我想象中的样子，很快就可以投入使用了。前几天去杭州学习了不少提升拍摄质量的知识，也会趁着这次升级后厨来升级拍摄方面的质量，相信大家会喜欢的！

字幕
0:00:00.441,0:00:04.089
哈喽大家好 我们今天把锅这些东西买过来了

0:00:04.788,0:00:05.844
买了6个锅

0:00:07.156,0:00:09.373
然后还有一些其他的宽油盆啊

0:00:09.531,0:00:11.602
这些也到了 陆陆续续到了

0:00:11.616,0:00:13.984
现在我就把这里面收拾一下

0:00:14.498,0:00:15.923
该弄得弄 然后该摆的摆

0:00:16.405,0:00:20.032
大概过两天就应该可以做饭吃了这里

0:00:36.002,0:00:37.051
这里面全是宽油盆

0:00:38.232,0:00:39.129
先放地上吧

0:00:57.697,0:01:00.796
现在师傅已经帮我们把这些配件都拿过来了

0:01:00.804,0:01:01.556
锅也拿过来了

0:01:01.803,0:01:03.228
现在的话就把这个拆了

0:01:07.341,0:01:09.505
这个拆了 然后把这个胶纸撕掉

0:01:10.006,0:01:14.643
也挺多的 有几个打荷台 有灶呀还有不锈钢的那个东西

0:01:15.722,0:01:17.754
把它撕完了之后再把地上的扫一下

0:01:18.647,0:01:23.271
然后应该再过个几天这里就可以开火了

0:01:25.211,0:01:27.537
我先来撕一个 看看这个好不好撕

0:01:33.298,0:01:35.725
这个很简单 一下子就撕掉了

0:01:38.543,0:01:41.472
撕完了之后这里不锈钢的看起来很干净

0:01:43.733,0:01:45.587
这一个的话是用来装调料的

0:01:46.062,0:01:48.430
里面全部放调料盆

0:01:49.538,0:01:52.229
然后这个我们下了班之后这个可以把它盖起来

0:01:54.419,0:01:57.717
这样子就可以防止蟑螂跑进去 或者老鼠

0:02:01.701,0:02:04.406
然后这个灶台的纸应该比较难撕一点

0:02:06.246,0:02:06.827
慢慢来

0:02:26.866,0:02:28.621
好了 这个就撕好了

0:02:30.343,0:02:32.315
撕完了之后看起来干干净净

0:02:39.040,0:02:41.945
还不错 现在就慢慢的去撕这些

0:02:43.159,0:02:45.013
等一下还有几个同事一起来帮我弄

0:02:45.567,0:02:46.926
我先一个人慢慢做着

0:04:16.510,0:04:18.595
现在我们这个上面还有2个洞

0:04:18.621,0:04:20.422
我准备用这个去给它补一下

0:04:20.936,0:04:25.062
刚才那个叔叔借了我一个锯子 给它锯成了2块

0:04:37.479,0:04:37.953
 行了

0:04:40.104,0:04:41.329
下一个

0:04:46.450,0:04:48.751
这样刚好 因为这个也是旧的 

0:04:48.832,0:04:50.774
我就将就它这个旧的安上去

0:04:53.236,0:04:54.150
现在就可以了

0:04:54.231,0:04:57.826
 就是等一下我们再大扫除把它搞干净一点

0:04:58.485,0:05:00.633
今天我们把这个膜啊这些都撕好了

0:05:00.633,0:05:04.774
这个灶台我们3个人也把它搬好了

0:05:05.213,0:05:08.289
然后打荷台啊这些也弄好了 地上也弄干净了

0:05:08.901,0:05:15.410
现在就等着明天再搞精细一点 搞干净一点这些卫生

0:05:16.150,0:05:20.855
然后估计再过一个星期就可以开火了

0:05:21.722,0:05:23.745
好啦本期视频就到这里了 拜拜


```

**Comment by Kevinzheng5** [comment]
认领

**Comment by Kevinzheng5** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨具和配件全部到齐，开始撕膜！新后厨工作室基本完工，很快就能投入使用，大家敬请期待！
Equipment is here for the new studio! New studio almost ready!

简介
相信大家已经很期待新的后厨工作室，我也很期待！现在装修水电用具基本全部到位，就剩下一次深度的大扫除和把调料食材等入库，基本上都是我想象中的样子，很快就可以投入使用了。前几天去杭州学习了不少提升拍摄质量的知识，也会趁着这次升级后厨来升级拍摄方面的质量，相信大家会喜欢的！
I believe you guys are looking forward to the new kitchen studio and I can’t be more excited myself. Now the appliances are all here and the renovation is almost done. The only two things left are a thorough clean-up and buying the ingredients and seasonings. It is very close to what I’ve expected and it is almost ready. The past few days I’ve been in Hangzhou to learn how to improve my photographing skills and I’ll practice those skills in this episode. Hope you guys like it!

字幕
0:00:00.441,0:00:04.089
哈喽大家好 我们今天把锅这些东西买过来了
Hey guys, we bought these kitchenware today like the woks

0:00:04.788,0:00:05.844
买了6个锅
Six woks

0:00:07.156,0:00:09.373
然后还有一些其他的宽油盆啊
And other stuffs like the pots for Kuanyou

0:00:09.531,0:00:11.602
这些也到了 陆陆续续到了
They are all here gradually

0:00:11.616,0:00:13.984
现在我就把这里面收拾一下
Now I’m going to clean up the place

0:00:14.498,0:00:15.923
该弄得弄 然后该摆的摆
Put everything in the right place

0:00:16.405,0:00:20.032
大概过两天就应该可以做饭吃了这里
Then the place should be ready to cook in about two days

0:00:36.002,0:00:37.051
这里面全是宽油盆
These are the pots for Kuanyou

0:00:38.232,0:00:39.129
先放地上吧
Leave them on the floor for now

0:00:57.697,0:01:00.796
现在师傅已经帮我们把这些配件都拿过来了
Now the delivery guys have got the parts here

0:01:00.804,0:01:01.556
锅也拿过来了
Along with the woks

0:01:01.803,0:01:03.228
现在的话就把这个拆了
Now let’s break the cases

0:01:07.341,0:01:09.505
这个拆了 然后把这个胶纸撕掉
And peel off the films

0:01:10.006,0:01:14.643
也挺多的 有几个打荷台 有灶呀还有不锈钢的那个东西
A lot of stuffs here including the chef tables, stoves and the stainless steel appliances

0:01:15.722,0:01:17.754
把它撕完了之后再把地上的扫一下
Let’s peel the films and sweep the floor

0:01:18.647,0:01:23.271
然后应该再过个几天这里就可以开火了
Then we can cook in here in a few days

0:01:25.211,0:01:27.537
我先来撕一个 看看这个好不好撕
Let me peel one first to see whether it comes off easily

0:01:33.298,0:01:35.725
这个很简单 一下子就撕掉了
There you go, pretty easy

0:01:38.543,0:01:41.472
撕完了之后这里不锈钢的看起来很干净
With the films gone, these stainless steel surfaces seem so clean

0:01:43.733,0:01:45.587
这一个的话是用来装调料的
This cabinet is for the seasoning 

0:01:46.062,0:01:48.430
里面全部放调料盆
We’ll put the seasoning cans in here

0:01:49.538,0:01:52.229
然后这个我们下了班之后这个可以把它盖起来
The cabinet can be closed like this after work

0:01:54.419,0:01:57.717
这样子就可以防止蟑螂跑进去 或者老鼠
Thus it keeps the roaches and rats out

0:02:01.701,0:02:04.406
然后这个灶台的纸应该比较难撕一点
The films on the stoves are hard to come off

0:02:06.246,0:02:06.827
慢慢来
Let’s take it slow

0:02:26.866,0:02:28.621
好了 这个就撕好了
Alright, all the peelings on this done

0:02:30.343,0:02:32.315
撕完了之后看起来干干净净
It seems so clean and tidy after peeling

0:02:39.040,0:02:41.945
还不错 现在就慢慢的去撕这些
Nice, let’s move on the others

0:02:43.159,0:02:45.013
等一下还有几个同事一起来帮我弄
A few colleagues are coming to help me

0:02:45.567,0:02:46.926
我先一个人慢慢做着
Let me start first

0:04:16.510,0:04:18.595
现在我们这个上面还有2个洞
There are two missing slots up there

0:04:18.621,0:04:20.422
我准备用这个去给它补一下
I’m going to fill those with these

0:04:20.936,0:04:25.062
刚才那个叔叔借了我一个锯子 给它锯成了2块
That nice uncle lent me a saw to cut it into two pieces

0:04:37.479,0:04:37.953
 行了
Alright

0:04:40.104,0:04:41.329
下一个
Next one

0:04:46.450,0:04:48.751
这样刚好 因为这个也是旧的 
Nice fit, this fence is used

0:04:48.832,0:04:50.774
我就将就它这个旧的安上去
Let’s give it another place to shine

0:04:53.236,0:04:54.150
现在就可以了
Nice

0:04:54.231,0:04:57.826
 就是等一下我们再大扫除把它搞干净一点
Next we are going to clean up the place

0:04:58.485,0:05:00.633
今天我们把这个膜啊这些都撕好了
Today we peeled all the films on the appliances

0:05:00.633,0:05:04.774
这个灶台我们3个人也把它搬好了
We three also moved the stoves in the right places

0:05:05.213,0:05:08.289
然后打荷台啊这些也弄好了 地上也弄干净了
The chef tables are also in the right places and we swept the floor

0:05:08.901,0:05:15.410
现在就等着明天再搞精细一点 搞干净一点这些卫生
Tomorrow we’ll do stuffs with more details. Clean up everything

0:05:16.150,0:05:20.855
然后估计再过一个星期就可以开火了
And then the place should be ready to cook in a week

0:05:21.722,0:05:23.745
好啦本期视频就到这里了 拜拜
Alright that’s it for this episode. Bye!
