### ISSUE TITLE
【美食作家王刚】家庭版麻婆豆腐 - https://youtu.be/pznZansDXSA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#122]
【美食作家王刚】家庭版麻婆豆腐 - https://youtu.be/pznZansDXSA
这是刚哥最新的视频私享链接，方便大家提前添加字幕，做菜过程文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。然后就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间9月3日晚6点

首先我们准备老豆腐1块
将老豆腐先切成厚片然后再切成小方块备用
同学们老豆腐和嫩豆腐的却别前者更香或者更嫩
然后在盆中加入适量的食用盐（约4克）
再加入适量的开水将豆腐浸泡几分钟
这样可以让豆腐嫩滑定型
下一步开始准备辅料
准备五花肉一块去皮之后剁成肉末备用
猪肉和牛肉的区别主要在于价格和香味
如果仅仅是家常菜完全可以用猪肉
猪肉剁好之后下一步开始准备辅料
准备适量的红泡椒切碎备用
准备生姜1块拍散之后剁碎备用
最后将泡好的豆腐沥干水份备用
下一步开始操作
首先我们把锅烧热
锅烧热之后加入适量的菜籽油
油温6成热之后加入几颗青花椒爆香
青花椒爆香之后将肉末下锅翻炒
这一步必须将肉末下锅炒香煸出猪油
猪肉煸成干香之后加入适量的豆瓣酱炒香炒出红油
豆瓣酱炒香之后加入适量的辣椒面翻炒几下
辣椒面炒至油润之后再加入适量的清水烧开
清水烧开之后开始调味
锅中加入适量的食用盐
然后将豆腐下锅中小火烧5分钟
中途分3个时间段加入淀粉勾3次芡
这样的目的是尽量收紧每一次勾芡后溢出的水份
尽可能的包裹收紧豆腐里外的汁水
此菜如果勾芡3次以下
豆腐成菜上桌后会溢水造成中间无味
而且汤汁过多影响卖相
收够3次芡汁后即可出锅装盘
最后再撒上花椒面和葱花即可上菜
一道非常美味的麻婆豆腐就制作完成

**Comment by WuStevenShengyang** [comment]
我来吧

**Comment by immoonancient** [comment]
发布了未校对的的字幕...现在更正...

**Comment by immoonancient** [comment]
校对后的字幕已上传，等重新发布

**Comment by immoonancient** [comment]
更正的字幕已发布
