### ISSUE TITLE
[手工耿] 硅膠假手自動塗抹裝置 - https://youtu.be/vUhtZcaSu1w

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1228]
https://youtu.be/vUhtZcaSu1w
<p>&#35270;&#39057;&#21457;&#24067;&#20110; June 30, 2020 at 06:00PM</p>
<p>&#26631;&#39064;<br>
&#30789;&#33184;&#20551;&#25163;&#33258;&#21205;&#22615;&#25273;&#35037;&#32622;&#65292;&#20877;&#20063;&#19981;&#29992;&#33258;&#24049;&#25830;&#33225;&#21862;!&#12304;&#25163;&#24037;&#32831;&bull;Useless Edison&#12305;</p>
<p>&#31616;&#20171;<br>
&#25163;&#24037;&#32831;&#33258;&#35069;&#30446;&#37636;&mdash;&mdash; 1/&#33258;&#21205;&#22615;&#25273;&#35037;&#32622;&#12290; 2/&#24392;&#31783;&#33258;&#34892;&#36554;&#12290; 3/&#32011;&#36523;&#34584;&#34523;&#12290; &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #UselessEdison #&#32831;&#24101; #ChineseEdison #shougonggeng #handicraft #diy #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #inventions #&#20013;&#22283;&#30332;&#26126; #&#20013;&#22283;&#24859;&#36842;&#29983; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by max-sun-hongyi** [comment]
0:00:02.820,0:00:06.600
Recently I've invented a tool for ladies to apply facial essence on their face

0:00:07.040,0:00:08.260
Next I'll demonstrate how to use it

0:00:09.020,0:00:11.260
 First load facial essence into the equipment

0:00:16.980,0:00:18.780
next we close the circuit then we are ready to go 

0:00:20.640,0:00:23.060
it automatically puts facial essence on the these fake hands

0:00:24.240,0:00:26.600
my face is larger than the average, so I've put two drops on the hands

0:00:37.400,0:00:40.180
next we spread it evenly on my face

0:00:55.700,0:01:00.340
gently pat it all over the face until it is absorbed

0:01:09.680,0:01:11.600
That's it

0:01:12.220,0:01:16.480
My face feel well moisturized after this process

0:01:22.460,0:01:24.960
The suspention system on this bike isn't very good 

0:01:24.960,0:01:28.780
I'm going to replace these spokes with springs, let's see how it goes
