### ISSUE TITLE
[华农兄弟] 华农兄弟把抓得蛇头鱼和黄鳝宰了做酸菜鱼很美味哦 - https://youtu.be/yENQ2CkzNBI

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1245]
https://youtu.be/yENQ2CkzNBI
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 5, 2020 at 01:44PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/yENQ2CkzNBI

#华农兄弟：把抓得蛇头鱼和黄鳝宰了，做酸菜鱼，很美味哦
#Huanong Brothers: We cook the fish that we caught yesterday, to make a "suan cai yu". Tasty!

0:00:00.000,0:00:01.960
# 這個就是昨天晚上收獲的魚
These are the fish that we caught yesterday night.

0:00:10.440,0:00:11.680
# 多吧  哎喲
A lot, isn' it? Ayo!

0:00:16.040,0:00:18.060
# 等下我就  把你們先煮啦
You guys will be the first to be cooked in a while.

0:00:18.900,0:00:19.720
# 洗一下
Wash you,

0:00:21.240,0:00:22.300
# 把你洗乾淨
cleanse you,

0:00:23.340,0:00:24.260
# 再來處理
for further processing.

0:00:30.360,0:00:31.820
# 我們做一個酸菜魚
We're gonna make a "suan cai yu"
(Suan cai yu. Lit: Boiled fish with pickled cabbage, usually spicy)

0:00:31.820,0:00:32.340
# (沒對白)
(Suan cai yu. Lit: Boiled fish with pickled cabbage, usually spicy)

0:00:32.340,0:00:34.520
# 這個蛇頭魚煮酸菜很好吃的
Snakehead fish is a good ingredient for suan cai yu.
(Suan cai yu. Lit: Boiled fish with pickled cabbage, usually spicy)

0:00:35.400,0:00:36.740
# 先把這個最大條的
Let me start with this largest one.

0:00:37.480,0:00:38.340
# 就你先
You're the first one.

0:00:40.780,0:00:41.960
# 刮一下這個魚鱗
I'm gonna scratch the scales.

0:00:42.300,0:00:44.380
# 它這個魚鱗好大不好刮
Its scales are too big and are rather hard to remove.

0:00:45.500,0:00:47.320
# 用手指來扣才快一點
Fingers might be more efficient.

0:00:59.020,0:01:01.100
# 沒拍死 拍死啦
It's still alive. Let me slap it to death!

0:01:04.100,0:01:05.180
# 你看  這個魚鱗
Look! The scales...

0:01:08.460,0:01:10.220
# 這個不用刮鱗的這個
There's no need to remove the scales of this fish.

0:01:13.720,0:01:15.900
# 這樣就可以啦  砍成一段段就可以啦
That's it. Chop it up into chunks and it's done.

0:01:26.400,0:01:28.460
# 好快的  這個火燒的好快
It's so fast. The fire grows really fast.

0:01:32.720,0:01:34.000
# 讓它慢慢燒
Leave it burning for a while.

0:01:35.260,0:01:36.520
# 放點這個鹹菜
Put some, this kind of pickled cabbage.

0:01:41.940,0:01:43.760
# 切大塊有[SIC]點  好夾一點
Cut it into larger pieces.  It's easier to take with chopsticks.

0:01:44.700,0:01:45.880
# 鹹菜已經搞定啦
The pickled cabbage is now ready.

0:01:45.880,0:01:48.060
# 你看  搞 搞了一點豆芽回來
Look! I've fetched, fetched some sprouts.

0:01:53.780,0:01:55.500
# 這豆芽淋一下水就好啦
The sprouts only need to be rinsed.

0:01:55.760,0:01:56.340
# 這個
The,

0:01:57.100,0:01:59.540
# 生薑大蒜  洗乾淨就好啦
the ginger and the garlic, wash them and that's it.

0:02:01.820,0:02:03.580
# 我們要拍一下這個生薑
We gotta smash the ginger.

0:02:04.780,0:02:06.920
# 這個會怕把它拍爆  這個瓷板
I don't wanna break it. It's a porcelain board.

0:02:12.400,0:02:14.780
# 你看  這個 準備好這些料等一下
Look! Here, we have these ingredients ready. We'll,

0:02:15.080,0:02:16.100
# 我們等一下再來
we'll come back to them in a while.

0:02:16.580,0:02:18.380
# 要先把它  那個醎菜抄[SIC]一下
Now let's fry, fry the pickled cabbage first.

0:02:20.360,0:02:21.240
# 先把這個油
Let me put the oil,

0:02:22.260,0:02:22.940
# 放下去
into the wok first.

0:02:27.940,0:02:29.080
# 先要炒一下
It needs to be fried for a while.

0:02:35.020,0:02:37.340
# 把這個大蒜先放下去炒一下
I put the garlic and fry it for a while.

0:02:37.820,0:02:38.620
# 更香
It smells even better.

0:02:40.040,0:02:41.200
# 這個差不多香啦
The scents starts coming out now.

0:02:43.740,0:02:44.360
# 搞點水
Put some water,

0:02:45.320,0:02:46.180
# 去燜它
and stew it.

0:02:51.620,0:02:53.360
# 哎喲  那麼靚的
Ayo! Why is it so beautiful?

0:02:56.360,0:02:58.080
# 都不夠水再加一點
More water. It's not enough.

0:03:04.980,0:03:06.300
# 用鍋蓋先蓋著它
Cover it with the lid first.

0:03:07.020,0:03:08.800
# 把它煮開然後就放那個魚
I'll put the fish when it boils.

0:03:09.320,0:03:10.560
# 把這個魚放下去
Now I put the fish into the wok.

0:03:10.640,0:03:12.660
# 有黃鱔有泥鰍 有蛇頭魚
There are eels, loaches and snakehead fish.

0:03:19.140,0:03:20.560
# 把這個豆芽也放下去
And the sprouts too

0:03:34.220,0:03:36.060
# 加點水  水有點少
Put some more water. The water here is not quite enough.

0:03:47.420,0:03:48.140
# 加點鹽
Put some salt.

0:03:50.840,0:03:52.200
# 這個鹽要加多一點
We needs a bit more salt,

0:03:53.900,0:03:54.800
# 那麼多魚
as we have so many fish.

0:03:59.620,0:04:00.940
# 好啦 蓋蓋起來
Alright! Cover it with the lid.

0:04:06.860,0:04:07.580
# 用火來
Cook it with fire,

0:04:08.180,0:04:09.560
# 猛火來燒它
with strong fire.

0:04:12.760,0:04:15.020
# 我把火吹一下  看它沒著啊
I try blowing into the fire. It's not glowing.

0:04:26.960,0:04:27.620
# 哎  著啊
Ay! It glows.

0:04:27.620,0:04:30.180
# 你看  這個狗還小的時候很胖的
Look! This dog used to be a fat boy when he was small.

0:04:30.820,0:04:31.660
# 現在都變
But he's now,

0:04:32.340,0:04:33.180
# 瘦狗啦
a skinny dog.

0:04:33.600,0:04:34.340
# 那麼瘦
So skinny

0:04:35.460,0:04:37.700
# 是不是  你那麼瘦  怎麼搞的
Aren't you? You're so skinny. What happened?

0:04:38.740,0:04:41.420
# 不是沒餵你  吃 吃那麼多還那麼瘦
I do feed you well. You, you eat so much but you're still so skinny.

0:04:44.420,0:04:45.080
# 吃多一點
Eat more,

0:04:46.200,0:04:47.500
# 長成 大胖狗
and be a big fat dog!

0:04:48.540,0:04:49.200
# 知不知道
Got it?

0:04:49.420,0:04:50.620
# 哇  看你牙齒
Wa! Have a look at your teeth!

0:04:51.660,0:04:52.260
# 笑一個
Smile!

0:04:53.140,0:04:53.840
# 笑一下
Smile!

0:04:54.940,0:04:55.940
# 笑一下
Hey, smile!

0:04:58.060,0:04:59.100
# 快點  笑一下
C'mon! Smile!

0:05:03.420,0:05:04.300
# 就這樣子的
So this is his smile.

0:05:05.160,0:05:05.740
# 這小狗 (註︰沒有原字幕)
This doggy,

0:05:06.160,0:05:07.260
# 好臭它的身上
his body is so stingy.

0:05:07.860,0:05:08.740
# 沒給它洗澡
I didn't bathe him.

0:05:10.280,0:05:12.580
# 我都沒空洗我自己的澡  還幫你洗
I don't even have the time to bathe myself. How can I bathe you?

0:05:14.680,0:05:16.280
# 你自己去河裡面洗就行啦
You can simply take a bath yourself in the river.

0:05:16.700,0:05:17.580
# 挨著那麼近
It's so close, just outside.

0:05:18.060,0:05:19.500
# 自己洗完自己回來啊
Take bath there and then come back.

0:05:25.200,0:05:28.020
# 你看  這個豬種的西紅杮哦  現在都熟啦
Look! These are the tomatoes planted by the pigs. They're now ripe.

0:05:31.500,0:05:32.720
# 還有一個不是很紅的
And this one is still a bit green.

0:05:36.520,0:05:37.620
# 可以吧  你看
Not bad. Look!

0:05:39.040,0:05:40.540
# 你機番茄
Organic tomatoes

0:05:44.720,0:05:45.780
# 這邊是有點壞的
It's a bit rotten on this side.

0:05:49.100,0:05:49.660
# 嗯
Um!

0:05:50.360,0:05:51.100
# 好好吃啊
Tasty!

0:05:51.140,0:05:53.280
# 你看  這有籽的哦 我也種一棵
Look! Here are seeds. Let me plant one tomato tree as well.

0:05:53.900,0:05:54.660
# 種在這裡
I plant it here.

0:05:59.880,0:06:02.180
# 只有一個  額 多一個我給你吃
I have just one. Eh, I'll give you one if there's another.

0:06:07.100,0:06:08.120
# 全來啦  它們
They're, all here.

0:06:09.020,0:06:09.940
# 全部還沒熟
The rest are all green.

0:06:10.660,0:06:11.740
# 熟了我再過來
I'll come again when they're ripe.

0:06:21.220,0:06:22.020
# 有點辣椒
Here's some chilli.

0:06:22.680,0:06:24.020
# 放點辣椒更好哦
It tastes much better with some chilli.

0:06:37.060,0:06:39.180
# 這個  快  快好啦
It's, nearly, nearly done.

0:06:39.460,0:06:42.140
# 我搞點紅油來 紅紅的顏色更好看
Let me fetch some chilli oil. The red colour makes it look more attractive.

0:06:49.580,0:06:51.780
# 加點豆瓣醬去顏色就來啦
With some bean paste sauce, the colour comes.

0:06:52.940,0:06:54.160
# 乳白色的顏色
The milky white colour,

0:06:55.560,0:06:56.800
# 變成紅油啦
is now changed to the colour of chilli oil.

0:07:00.020,0:07:01.620
# 你看  放點芥藍下去
Look! Put some Chinese kale.

0:07:02.060,0:07:03.320
# 乾脆吃火鍋算啦
Why don't we simply make it a hotpot?

0:07:03.880,0:07:04.520
# 多搞點
Put some more...

0:07:04.900,0:07:07.800
# 看一下  去冰箱裡面找一下有甚麼就放下去啦
Let's see, let's find whatever something in the fridge and put it here.

0:07:09.420,0:07:11.600
# 懶很煮啦  今天晚飯都不用煮
It saves our cooking time, for the dinner tonight.

0:07:11.740,0:07:13.480
# 拿著碗就到這裡吃就行啦
I only need to bring my bowl here for my dinner.

0:07:15.720,0:07:16.780
# 甚麼樣的都有
Here's everything.

0:07:19.440,0:07:22.740
# 應有盡有 哎喲  忘記啦  知道搞隻鴨子下來
It meets all wishes. Aya! I've forgotten. I should have fetched a duck,

0:07:23.080,0:07:24.580
# 放在這裡  一鍋燉了它
then I could put it here, and cook it with everything.

0:07:25.620,0:07:26.720
# 看一下熟了沒有
Let's see if it's done.

0:07:27.560,0:07:28.940
# 哎呀  你看  這個
Aya! Look! This is,

0:07:29.440,0:07:30.920
# 色香味俱全
it's appealing to your eyes, your nose and your taste buds.

0:07:34.300,0:07:36.140
# 哎呀 先嘗一下
Aya! Let me have a try.

0:07:38.720,0:07:39.900
# 搞一條蛇頭魚
Let me get a snakehead fish.

0:07:40.840,0:07:42.200
# 這蛇頭魚喲  這個
This is snakehead fish, this one.

0:07:43.780,0:07:44.920
# 薑 薑不要
Ginger. Pass

0:07:49.100,0:07:50.720
# 怎麼又一顆薑  不要
Why is there another piece of ginger? Pass

0:07:52.020,0:07:53.080
# 你看  這魚可以
Look! The fish, it's not bad.

0:07:54.560,0:07:56.380
# 這個湯才是精華
The essence is in the soup.

0:07:56.860,0:07:58.460
# 精華中的精華
It's the essence of essence.

0:07:59.100,0:08:00.240
# 乳白色的哦
It's milky white, you know.

0:08:07.500,0:08:08.080
# 嗯
Um!

0:08:09.280,0:08:10.440
# 好好吃哦
It's really tasty!

0:08:12.460,0:08:13.340
# 那條泥鰍
The loach...

0:08:14.340,0:08:16.060
# 哎呀  好辣哦
Aya! It's so spicy!

0:08:17.920,0:08:19.620
# 攝影小哥他肯定吃不了啦
Mr. Cameraman surely can't stand it.

0:08:21.040,0:08:23.380
# 這蛇頭魚  很嫩的這個肉哦
The snakehead fish, its meat is really tender.

0:08:23.860,0:08:25.180
# 而且沒有甚麼小骨頭
And there are hardly any small bones.

0:08:34.680,0:08:35.580
# 小狗懷孕啦
The doggy is pregnant.

0:08:36.920,0:08:37.940
# 多吃點魚骨頭
Eat more fish bones!

0:08:38.200,0:08:39.340
# 你看  這鍋裡面啊
Look! Inside this wok...

0:08:40.580,0:08:41.980
# 好香啊 看上去都香
It smells so good. I can tell by my eyes.

0:08:52.660,0:08:54.820
# 你看  這個味道很好的  這個味道
Look! The taste is really good, this taste,

0:08:55.100,0:08:56.260
# 特別是這個湯的味道
especially the taste of the soup.

0:08:57.040,0:08:58.080
# 濃濃的味道
It's so rich,

0:08:59.540,0:09:00.180
# 魚肉味
rich flavour of fish.

0:09:06.360,0:09:07.320
# 這蛇頭魚
This snakehead fish,

0:09:08.540,0:09:10.400
# 這個蛇頭魚  很好吃的這種蛇頭魚
this snakehead fish, this kind of snakehead fish is really tasty.

0:09:10.480,0:09:11.360
# 它肉很緊
Its meat is very firm.

0:09:11.640,0:09:12.420
# 特別好吃
And it's exceptionally tasty.

0:09:13.380,0:09:14.680
# 我很喜歡吃這個蛇頭魚
I like snakehead fish very much.

0:09:19.080,0:09:20.500
# 小黑  口水都流出來啦
Blacky is drooling.

0:09:27.260,0:09:30.380
# 這魚頭給公狗給你吃 燙不燙  哈哈
This fish head, it's for the big boy. It's for you. Is it hot? Ha ha!

0:09:30.700,0:09:31.200
# 很燙
It is!

0:09:37.060,0:09:38.020
# 嗯  這小黑狗
Um! This black doggy,

0:09:41.160,0:09:41.880
# 以前它是
used to be,

0:09:42.480,0:09:44.220
# 爆炸頭  現在都不爆炸啦
very fussy. But he's now no more fussy at all.

0:09:45.020,0:09:45.680
# 太多狗啦
Here are too many dogs.

0:09:47.460,0:09:48.140
# 沒辦法
He just can't,

0:09:48.820,0:09:49.820
# 沒辦法做王
can't be the alpha.

0:09:51.200,0:09:53.020
# 小黑  口水流出來啦
Blacky! She's drooling again.

0:09:56.580,0:09:58.820
# 好啦 今天的視頻就到這裡啦
Alright! The video ends here.

0:10:00.200,0:10:02.940
# 直接當晚飯吃啦  搞點飯就直接這樣吃算啦
It will be my dinner. I'll get some rice and it will be my dinner right away.

0:10:03.300,0:10:04.240
# 就不要煮菜啦
Then I don't need any other dishes.

0:10:05.200,0:10:06.680
# 又可以省一點  省一點煤氣
I can also save some, save some gas.
