### ISSUE TITLE
[老飯骨] 韭菜蝦皮卷煎餅 - https://youtu.be/CVrXrkwYXN8

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1294]
**视频链接**：https://youtu.be/CVrXrkwYXN8

發佈時間北京時間7月17日晚上10點，時長4分44
# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•韭菜蝦皮卷煎餅】讓韭菜蝦皮非同尋常的關鍵！酥脆鮮香，簡單易學，趕緊來一手！ |老飯骨

简介

小友們好，今天老飯骨又要教給大家一道小菜——韭菜蝦皮卷煎餅！
這道菜美味的關鍵在於蝦皮的干焙、熗韭菜蝦皮的油還要提前加蔥和辣椒熗一會兒。照著視頻裡做出來的韭菜蝦皮，卷煎餅、卷生菜都是絕配！讓大爺、二伯讚不絕口，一個不夠再來倆！

字幕
1
00:00:00,000 --> 00:00:03,200
尝尝让我师父一直念念不忘的

2
00:00:03,200 --> 00:00:04,720

3
00:00:04,720 --> 00:00:06,400
吃一个想俩吃俩想仨的

4
00:00:07,320 --> 00:00:08,200
就差肘子

5
00:00:08,200 --> 00:00:09,600
韭菜虾皮卷煎饼

6
00:00:09,600 --> 00:00:13,440

7
00:00:13,440 --> 00:00:15,800
煎饼现成的买就行 山东的煎饼

8
00:00:15,800 --> 00:00:19,640
虾皮咱们一定要挑这种自然颜色

9
00:00:19,640 --> 00:00:22,080
不能挑那种愣白的 愣白的不行

10
00:00:22,080 --> 00:00:25,080
首先得把虾皮的咸味给它去一去

11
00:00:25,080 --> 00:00:26,360
得洗一洗

12
00:00:26,360 --> 00:00:28,320
它再干净 它底下也有沙子

13
00:00:28,320 --> 00:00:30,960
捞 一定拿手捞出来 底下一层沙子

14
00:00:30,960 --> 00:00:32,240
你不信你看底儿

15
00:00:32,240 --> 00:00:35,520
看见没有网友们 你看看 再来一遍

16
00:00:35,520 --> 00:00:38,160
这个洗到什么时候为止

17
00:00:38,160 --> 00:00:41,160
一会您尝尝 它没有太多咸味了

18
00:00:41,160 --> 00:00:44,840
虾皮洗的要快 不能泡

19
00:00:44,840 --> 00:00:48,200
把那鲜味咸味泡干净了也不行 动作要快

20
00:00:48,200 --> 00:00:51,480
这行了 没问题

21
00:00:51,480 --> 00:00:54,360
您看虾皮洗完了 咱们切点葱

22
00:00:54,360 --> 00:00:55,800

23
00:00:55,800 --> 00:00:57,440
搁在一边备料

24
00:00:57,440 --> 00:00:59,160
切好了以后点火

25
00:00:59,160 --> 00:01:01,960
把这虾皮攥攥 把这水攥出去

26
00:01:01,960 --> 00:01:05,560
咱们把这虾皮 这叫焙 干焙

27
00:01:06,960 --> 00:01:10,720
不放油 焙干 焙干香气就出来了

28
00:01:10,720 --> 00:01:15,000
把这水气给它焙出去 让它酥脆

29
00:01:15,000 --> 00:01:17,080
咱这虾皮这样焙干也行

30
00:01:17,080 --> 00:01:20,160
搁在托盘里搁烤箱里烤也可以

31
00:01:20,160 --> 00:01:23,800
已经支棱了 开始松散了 一粒是一粒

32
00:01:23,800 --> 00:01:25,760
一定小火给它焙干了

33
00:01:25,760 --> 00:01:28,320
师父您看香味出来了吧

34
00:01:28,320 --> 00:01:30,280
现在闻的全是虾米皮味

35
00:01:31,080 --> 00:01:31,960
海鲜味

36
00:01:31,960 --> 00:01:34,520
差不多了 好关火

37
00:01:34,520 --> 00:01:35,960
出锅

38
00:01:35,960 --> 00:01:38,560
咱们先耗点葱油

39
00:01:38,560 --> 00:01:42,080
耗葱油是增加它的香味

40
00:01:42,080 --> 00:01:44,000
一般做韭菜是这样

41
00:01:44,000 --> 00:01:47,920
做韭菜的东西不能搁生葱

42
00:01:47,920 --> 00:01:49,640
炸点葱油特别好

43
00:01:49,640 --> 00:01:52,280
因为 搁这生葱和韭菜一串味

44
00:01:54,600 --> 00:01:56,920
两个都是比较冲的味道

45
00:01:56,920 --> 00:01:58,200
耗着葱油

46
00:01:58,200 --> 00:02:00,680
咱们这儿切两刀韭菜

47
00:02:00,680 --> 00:02:02,400
韭菜的头儿咱们不要

48
00:02:02,400 --> 00:02:06,280
尽量多使点叶子的部分

49
00:02:06,280 --> 00:02:07,960

50
00:02:07,960 --> 00:02:09,800
这就够了

51
00:02:09,800 --> 00:02:12,120
在这跟我们网友说一下

52
00:02:12,120 --> 00:02:14,960
入伏的韭菜就不要吃了 韭菜发臭

53
00:02:14,960 --> 00:02:16,920
香气出来了

54
00:02:16,920 --> 00:02:19,640
小点火 咱把这个葱别糟蹋

55
00:02:19,640 --> 00:02:23,040
都捞出来 留着待会炒菜使

56
00:02:23,040 --> 00:02:25,520
关键步骤 火停着呢（最小火）

57
00:02:25,520 --> 00:02:27,280
这个油是热的

58
00:02:27,280 --> 00:02:30,200
把这个辣椒炝一下

59
00:02:30,200 --> 00:02:34,440
然后把辣椒捞出去 炸点辣椒油

60
00:02:34,440 --> 00:02:37,240
要呲 一呲这香气就出来了

61
00:02:37,240 --> 00:02:40,400
用热油呲韭菜和虾皮

62
00:02:40,400 --> 00:02:43,120

63
00:02:43,120 --> 00:02:47,040
这是一个倒呲油的方法 叫炝

64
00:02:47,040 --> 00:02:49,600
这个虾皮刚才咱们已经焙干了

65
00:02:49,600 --> 00:02:50,720
这一呲油

66
00:02:50,720 --> 00:02:54,360
韭菜的香味和油的香味儿

67
00:02:54,360 --> 00:02:56,040
全都能吃到虾米皮里边

68
00:02:56,040 --> 00:02:58,680
吃油了以后 也透明了 也酥脆了

69
00:02:58,680 --> 00:03:00,720
韭菜也不会有烂韭菜的味

70
00:03:00,720 --> 00:03:03,760
盐呢 要不要 刚才洗的有点咸味

71
00:03:03,760 --> 00:03:05,840
所以其它的调料就不用加了

72
00:03:05,840 --> 00:03:08,560
你看我给大家准备了一个食盒

73
00:03:08,560 --> 00:03:10,840
有虾皮 有煎饼

74
00:03:10,840 --> 00:03:14,120
然后有彩椒 还有尖椒

75
00:03:14,120 --> 00:03:17,040
还有小葱 还有生菜

76
00:03:17,040 --> 00:03:19,800
尝尝让我师父一直念念不忘的

77
00:03:19,800 --> 00:03:21,840
韭菜煎饼卷虾皮

78
00:03:21,840 --> 00:03:24,600
真得先跟你大爷 直接给他搁嘴里边

79
00:03:24,600 --> 00:03:26,120

80
00:03:26,120 --> 00:03:28,080
看看大爷什么表情

81
00:03:28,080 --> 00:03:30,000
谢谢朝辉 谢谢二伯

82
00:03:30,000 --> 00:03:32,640
大爷吃 大爷怎么样啊

83
00:03:33,320 --> 00:03:33,960
好吃

84
00:03:33,960 --> 00:03:36,960
这咸味刚刚好 正好

85
00:03:36,960 --> 00:03:39,040
最有特点的 搁了点辣椒

86
00:03:39,040 --> 00:03:40,800
我吃别的就没搁辣椒

87
00:03:40,800 --> 00:03:42,560
师父尝尝

88
00:03:42,560 --> 00:03:45,240

89
00:03:45,240 --> 00:03:47,400
一口就下去了 酥香

90
00:03:47,400 --> 00:03:48,840
没有虾米皮的腥味

91
00:03:48,840 --> 00:03:52,040
它这个调料的运用 非常恰当

92
00:03:52,040 --> 00:03:54,600
我说最突出的就这点辣椒用的好

93
00:03:54,600 --> 00:03:57,880
它每种过味道提出来的恰到好处

94
00:03:57,880 --> 00:03:59,960
吃一个想俩吃俩想仨的

95
00:03:59,960 --> 00:04:01,400
再来一个

96
00:04:01,400 --> 00:04:04,080
第二个就是生菜卷虾皮

97
00:04:04,600 --> 00:04:06,280
看师父这个嘴

98
00:04:06,280 --> 00:04:09,400

99
00:04:09,400 --> 00:04:11,520
有荤有素 营养搭配

100
00:04:11,520 --> 00:04:13,360
就差肘子了

101
00:04:14,360 --> 00:04:17,080
咱们今天是为了吃的素一点

102
00:04:17,080 --> 00:04:19,400
真的 大爷说的对

103
00:04:19,400 --> 00:04:22,160
吃完这个 我真是从心里边说什么

104
00:04:22,160 --> 00:04:23,320
还想吃 不是

105
00:04:23,320 --> 00:04:24,480
有没有肉啊

106
00:04:24,480 --> 00:04:26,120
再卷片儿肉吃更香了

107
00:04:26,120 --> 00:00:02,000

**Comment by BOWEN0305772** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【國宴大師•韭菜蝦皮卷煎餅】讓韭菜蝦皮非同尋常的關鍵！酥脆鮮香，簡單易學，趕緊來一手！ |老飯骨
Attention! The secret recipe lets the shrimp and Chinese chive be fantastic!
简介

小友們好，今天老飯骨又要教給大家一道小菜——韭菜蝦皮卷煎餅！
這道菜美味的關鍵在於蝦皮的干焙、熗韭菜蝦皮的油還要提前加蔥和辣椒熗一會兒。照著視頻裡做出來的韭菜蝦皮，卷煎餅、卷生菜都是絕配！讓大爺、二伯讚不絕口，一個不夠再來倆！
Hello, everyone, today Lao Fangu is going to teach us a kind of appetizer: shrimp and Chinese chive wrap! 
The key points of is cuisine is the torrefaction of shrimp. The oil which be cooked with shrimp and Chinese chive could be fried with onions and peppers first. The fired shrimp and chive we made followed by video would be amazing! You can eat with jianbing (it is like pita, but crispier), lettuces. Da Ye and Er Bai could not stop eating! They need one more! 
字幕
1
00:00:00,000 --> 00:00:03,200
尝尝让我师父一直念念不忘的
Let me taste this delicacy that my master could not forget
2
00:00:03,200 --> 00:00:04,720

3
00:00:04,720 --> 00:00:06,400
吃一个想俩吃俩想仨的
He wants to eat as many as he can 
4
00:00:07,320 --> 00:00:08,200
就差肘子
It could be better if we have the Jokbal
5
00:00:08,200 --> 00:00:09,600
韭菜虾皮卷煎饼
shrimp and Chinese chive wrap
6
00:00:09,600 --> 00:00:13,440

7
00:00:13,440 --> 00:00:15,800
煎饼现成的买就行 山东的煎饼
You can find the Jianbing at food store, Shandong(a Chinese province)’s Jianbing
8
00:00:15,800 --> 00:00:19,640
虾皮咱们一定要挑这种自然颜色
For small shrimp, we must pick this kind of shrimp with the natural color 
9
00:00:19,640 --> 00:00:22,080
不能挑那种愣白的 愣白的不行
Not with the immature white
10
00:00:22,080 --> 00:00:25,080
首先得把虾皮的咸味给它去一去
At first, we need to get rid of the saline taste of the shrimp
11
00:00:25,080 --> 00:00:26,360
得洗一洗
We need to wash
12
00:00:26,360 --> 00:00:28,320
它再干净 它底下也有沙子
Even it looks like clean, but the bottom still leaves sands. 
13
00:00:28,320 --> 00:00:30,960
捞 一定拿手捞出来 底下一层沙子
Catch them with your hand, you can see there is a layer of sands on the bottom. 
14
00:00:30,960 --> 00:00:32,240
你不信你看底儿
See the bottom
15
00:00:32,240 --> 00:00:35,520
看见没有网友们 你看看 再来一遍
See it my friend, see it twice, dude. 
16
00:00:35,520 --> 00:00:38,160
这个洗到什么时候为止
When can we finish washing? 
17
00:00:38,160 --> 00:00:41,160
一会您尝尝 它没有太多咸味了
You could taste later; it is not salty that much. 
18
00:00:41,160 --> 00:00:44,840
虾皮洗的要快 不能泡
We must wash the shrimp fast, not soak in the water.
19
00:00:44,840 --> 00:00:48,200
把那鲜味咸味泡干净了也不行 动作要快
It could not be good if we get rid of all the salty and umami flavor. We need to be fast.
20
00:00:48,200 --> 00:00:51,480
这行了 没问题
Ok, now is good. 
21
00:00:51,480 --> 00:00:54,360
您看虾皮洗完了 咱们切点葱
After washing shrimp, let’s cut up some green onions.
22
00:00:54,360 --> 00:00:55,800

23
00:00:55,800 --> 00:00:57,440
搁在一边备料
Put aside as prepare
24
00:00:57,440 --> 00:00:59,160
切好了以后点火
Now we turn on the cooktop
25
00:00:59,160 --> 00:01:01,960
把这虾皮攥攥 把这水攥出去
Clench the shrimp, let the water out of shrimp
26
00:01:01,960 --> 00:01:05,560
咱们把这虾皮 这叫焙 干焙
Now we need to dry the shrimp, it calls torrefying 
27
00:01:06,960 --> 00:01:10,720
不放油 焙干 焙干香气就出来了
No oil, just torrefy them, the aroma would come out
28
00:01:10,720 --> 00:01:15,000
把这水气给它焙出去 让它酥脆
We need to dry them too, which makes them be more crispy
29
00:01:15,000 --> 00:01:17,080
咱这虾皮这样焙干也行
We can torrefy the shrimp in this way
30
00:01:17,080 --> 00:01:20,160
搁在托盘里搁烤箱里烤也可以
As well as we can put them on the comal and dry them in the oven
31
00:01:20,160 --> 00:01:23,800
已经支棱了 开始松散了 一粒是一粒
the shrimps have been stood up. Now they are separated, one by one. 
32
00:01:23,800 --> 00:01:25,760
一定小火给它焙干了
It must be low flame.
33
00:01:25,760 --> 00:01:28,320
师父您看香味出来了吧
Master, the aroma has come out
34
00:01:28,320 --> 00:01:30,280
现在闻的全是虾米皮味
All I smell is the aroma of shrimp. 
35
00:01:31,080 --> 00:01:31,960
海鲜味
Seafood flavor 
36
00:01:31,960 --> 00:01:34,520
差不多了 好关火
Almost down, turn it off 
37
00:01:34,520 --> 00:01:35,960
出锅
Get out from pan
38
00:01:35,960 --> 00:01:38,560
咱们先耗点葱油
Let’s make some green onion oil
39
00:01:38,560 --> 00:01:42,080
耗葱油是增加它的香味
The green onion oil can add its aroma
40
00:01:42,080 --> 00:01:44,000
一般做韭菜是这样
We usually do that when we cook chives. 
41
00:01:44,000 --> 00:01:47,920
做韭菜的东西不能搁生葱
When cooking chives, we cannot add any fresh green onions
42
00:01:47,920 --> 00:01:49,640
炸点葱油特别好
It could be better to make some green onion oil. 
43
00:01:49,640 --> 00:01:52,280
因为 搁这生葱和韭菜一串味
The flavor would be tainted if we put the chives and the fresh green onion together. 
44
00:01:54,600 --> 00:01:56,920
两个都是比较冲的味道
Both of them have the pungent smell. 
45
00:01:56,920 --> 00:01:58,200
耗着葱油
While making the onion oil, 
46
00:01:58,200 --> 00:02:00,680
咱们这儿切两刀韭菜
Now we are going to cut chives. 
47
00:02:00,680 --> 00:02:02,400
韭菜的头儿咱们不要
We do not need the head
48
00:02:02,400 --> 00:02:06,280
尽量多使点叶子的部分
Leave the part of leaves as many as possible
49
00:02:06,280 --> 00:02:07,960

50
00:02:07,960 --> 00:02:09,800
这就够了
That’s all
51
00:02:09,800 --> 00:02:12,120
在这跟我们网友说一下
Now we need to remind that 
52
00:02:12,120 --> 00:02:14,960
入伏的韭菜就不要吃了 韭菜发臭
It is better not to eat the chives at the hottest summer. They are stinky.
53
00:02:14,960 --> 00:02:16,920
香气出来了
Now the aroma comes out
54
00:02:16,920 --> 00:02:19,640
小点火 咱把这个葱别糟蹋
Turn it down. We could not waste the green onion. 
55
00:02:19,640 --> 00:02:23,040
都捞出来 留着待会炒菜使
Get all onions out, we need them to be used later. 
56
00:02:23,040 --> 00:02:25,520
关键步骤 火停着呢（最小火）
Attention! We turn it off (or keep the flame at lowest level)
57
00:02:25,520 --> 00:02:27,280
这个油是热的
The oil is hot
58
00:02:27,280 --> 00:02:30,200
把这个辣椒炝一下
Now put the pepper into the oil. 
59
00:02:30,200 --> 00:02:34,440
然后把辣椒捞出去 炸点辣椒油
Then get out the pepper. We make some pepper oil. 
60
00:02:34,440 --> 00:02:37,240
要呲 一呲这香气就出来了
Must hear the sound, “chi”，chi is the start of aroma. 
61
00:02:37,240 --> 00:02:40,400
用热油呲韭菜和虾皮
Now we put the hot oil on the shrimp and chives. 
62
00:02:40,400 --> 00:02:43,120

63
00:02:43,120 --> 00:02:47,040
这是一个倒呲油的方法 叫炝
This way is called Qiang (transient fried)
64
00:02:47,040 --> 00:02:49,600
这个虾皮刚才咱们已经焙干了
The shrimp now is dry.
65
00:02:49,600 --> 00:02:50,720
这一呲油
By the way Qiang
66
00:02:50,720 --> 00:02:54,360
韭菜的香味和油的香味儿
The favor of chives and aroma of oil
67
00:02:54,360 --> 00:02:56,040
全都能吃到虾米皮里边
All in the shrimp
68
00:02:56,040 --> 00:02:58,680
吃油了以后 也透明了 也酥脆了
Shrimp with oil would be more transparent and more crispy 
69
00:02:58,680 --> 00:03:00,720
韭菜也不会有烂韭菜的味
The chives would not be tasted like be decayed 
70
00:03:00,720 --> 00:03:03,760
盐呢 要不要 刚才洗的有点咸味
How about salt? Do we need to add some salts? We left some salt when we washed the shrimp
71
00:03:03,760 --> 00:03:05,840
所以其它的调料就不用加了
Thus, we do not need to add extra seasonings
72
00:03:05,840 --> 00:03:08,560
你看我给大家准备了一个食盒
Look, I prepare a bento box for us. 
73
00:03:08,560 --> 00:03:10,840
有虾皮 有煎饼
Shrimp and Jianbing
74
00:03:10,840 --> 00:03:14,120
然后有彩椒 还有尖椒
And color pepper, and chili pepper
75
00:03:14,120 --> 00:03:17,040
还有小葱 还有生菜
And green onion, and lettuce 
76
00:03:17,040 --> 00:03:19,800
尝尝让我师父一直念念不忘的
Let me taste this delicacy that my master could not forget

77
00:03:19,800 --> 00:03:21,840
韭菜煎饼卷虾皮
Chives and shrimp wrap
78
00:03:21,840 --> 00:03:24,600
真得先跟你大爷 直接给他搁嘴里边
Give your Da Ye first, put into his mouth directly
79
00:03:24,600 --> 00:03:26,120

80
00:03:26,120 --> 00:03:28,080
看看大爷什么表情
See Da Ye’s face
81
00:03:28,080 --> 00:03:30,000
谢谢朝辉 谢谢二伯
Thanks Chaohui, thanks Er Bo
82
00:03:30,000 --> 00:03:32,640
大爷吃 大爷怎么样啊
Da Ye, how do you feel
83
00:03:33,320 --> 00:03:33,960
好吃
good
84
00:03:33,960 --> 00:03:36,960
这咸味刚刚好 正好
The salty flavor is exactly fine. 
85
00:03:36,960 --> 00:03:39,040
最有特点的 搁了点辣椒
The most special part is adding the pepper.
86
00:03:39,040 --> 00:03:40,800
我吃别的就没搁辣椒
I have never added pepper when I eat other food. 
87
00:03:40,800 --> 00:03:42,560
师父尝尝
Have a taste, master
88
00:03:42,560 --> 00:03:45,240

89
00:03:45,240 --> 00:03:47,400
一口就下去了 酥香
I can wolf down it; it is so crispy.
90
00:03:47,400 --> 00:03:48,840
没有虾米皮的腥味
No the stinky smell of shrimp
91
00:03:48,840 --> 00:03:52,040
它这个调料的运用 非常恰当
Every seasoning is used properly
92
00:03:52,040 --> 00:03:54,600
我说最突出的就这点辣椒用的好
The best is the use of pepper
93
00:03:54,600 --> 00:03:57,880
它每种过味道提出来的恰到好处
Every kind of flavor is accurate to be embodied. 
94
00:03:57,880 --> 00:03:59,960
吃一个想俩吃俩想仨的
The one is not enough
95
00:03:59,960 --> 00:04:01,400
再来一个
I want one more
96
00:04:01,400 --> 00:04:04,080
第二个就是生菜卷虾皮
Second one is lettuce and shrimp wrap
97
00:04:04,600 --> 00:04:06,280
看师父这个嘴
Look master’s mouth
98
00:04:06,280 --> 00:04:09,400

99
00:04:09,400 --> 00:04:11,520
有荤有素 营养搭配
There are meat as well as vegetables, keeping the balance of nutrition
100
00:04:11,520 --> 00:04:13,360
就差肘子了
It could be better if we have the Jokbal
101
00:04:14,360 --> 00:04:17,080
咱们今天是为了吃的素一点
Today we prefer to being more vegetarian
102
00:04:17,080 --> 00:04:19,400
真的 大爷说的对
Yes, you are truly correct. 
103
00:04:19,400 --> 00:04:22,160
吃完这个 我真是从心里边说什么
After eating this, I really want to say something from my heart.
104
00:04:22,160 --> 00:04:23,320
还想吃 不是
Don’t you want more?
105
00:04:23,320 --> 00:04:24,480
有没有肉啊
No meat?!
106
00:04:24,480 --> 00:04:26,120
再卷片儿肉吃更香了
Wrap one piece of meat would be more delicious
