### ISSUE TITLE
【美食作家王刚】接伯爷伯娘去看新工作室 - https://youtu.be/-xHoV0Z0bXI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#1295]
**视频链接**：https://youtu.be/-xHoV0Z0bXI

视频时长5:53，预计发布时间为北京时间7月20日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
王刚接伯爷伯娘去看看自己的新工作室，顺便摘点葡萄给亲戚朋友

简介
大家好，第一次带伯爷伯娘来看看新工作室，他们很满意，😂到时候要办寿宴就提前预定了！

字幕
0:00:00.364,0:00:01.017
哈喽 大家好

0:00:01.164,0:00:04.185
今天难得抽时间出来带我伯爷伯娘

0:00:04.185,0:00:05.824
去看一下我的新工作室

0:00:06.284,0:00:08.102
然后顺便再摘点葡萄吃一下

0:00:08.300,0:00:11.120
那个工作室已经弄了有差不多一个月了

0:00:11.120,0:00:12.211
这次是第一次去

0:00:13.805,0:00:14.554
诶呀 好热

0:00:15.128,0:00:15.601
好热啊

0:00:15.601,0:00:16.497
这里面好热和哦

0:00:16.720,0:00:17.670
马上就开空调

0:00:21.554,0:00:22.176
到了 四伯爷

0:00:25.181,0:00:27.163
哦哟 还是多远一趟哦

0:00:27.849,0:00:29.310
慢点慢点

0:00:33.173,0:00:33.847
看一下嘛

0:00:34.360,0:00:35.680
走嘛进去看一下

0:00:38.499,0:00:39.350
就是这里面

0:00:39.533,0:00:41.389
不过这里面夏天有点热

0:00:41.500,0:00:42.828
冬天可能就要好点

0:00:42.828,0:00:43.807
冬天就安逸

0:00:44.380,0:00:46.533
这个花花草草喊师父来都修剪好了

0:00:46.741,0:00:48.936
不是这里面的草笼笼深得很

0:00:49.764,0:00:52.094
这里场景还可以嘛

0:00:53.840,0:00:54.445
宽敞

0:00:54.736,0:00:58.544
这里反正是玻璃的光线比较好

0:00:58.544,0:00:59.544
嗯

0:01:00.300,0:01:01.644
你看有回声

0:01:01.644,0:01:03.465
这里是喂鱼的吗

0:01:03.717,0:01:04.344
嗯

0:01:04.668,0:01:05.564
还没放水

0:01:06.315,0:01:07.067
可以啊

0:01:08.555,0:01:10.839
这些桌子都可以转的

0:01:11.377,0:01:14.001
可以可以可以

0:01:14.567,0:01:17.831
这里面都没有吊的灯都是安的路灯

0:01:19.171,0:01:21.052
就跟外面的路灯一样的

0:01:21.679,0:01:23.202
这个是塑料的吗

0:01:23.650,0:01:25.218
是铁的

0:01:27.540,0:01:28.220
走嘛

0:01:38.073,0:01:40.000
这就是厨房我把灯打开

0:01:42.094,0:01:44.467
哦哟 好宽哦

0:01:45.023,0:01:45.746
可以

0:01:48.822,0:01:49.898
6个灶

0:01:51.566,0:01:55.069
以后你满70岁的时候好生给你整哈

0:01:55.180,0:01:55.792
要的啊

0:01:56.237,0:01:58.109
可以啊

0:01:58.257,0:02:01.000
伯娘满60岁都可以给你炒几桌

0:02:01.000,0:02:01.668
要的啊

0:02:02.520,0:02:04.900
这里是7米的灶

0:02:05.968,0:02:07.408
加这个灶7米

0:02:07.469,0:02:10.935
这个灶是2米1个3个灶加1个这个灶

0:02:11.770,0:02:13.960
这里可以同时6个人炒菜

0:02:14.460,0:02:15.140
可以

0:02:15.140,0:02:15.460
可以

0:02:15.500,0:02:16.260
可以啊

0:02:16.626,0:02:18.660
如果是炒菜这边可以蒸东西

0:02:19.273,0:02:21.223
然后这边有2个冰箱

0:02:21.223,0:02:25.079
就是你满十的话整2头猪都放得进去

0:02:25.727,0:02:28.322
3头猪都放得进去

0:02:29.100,0:02:29.577
可以

0:02:29.577,0:02:32.196
前段时间没有整归一都不好带你们来看得

0:02:32.196,0:02:34.140
这里乱糟糟的

0:02:34.260,0:02:36.315
哪里嘛 这下整好了就可以了

0:02:36.430,0:02:38.985
要得 走带你们摘点葡萄回去吃

0:02:39.696,0:02:42.738
四伯爷种了那么多年的庄稼没看见过这样的嘛

0:02:42.738,0:02:44.341
没看见过

0:02:44.381,0:02:45.659
结起一片片的

0:02:49.797,0:02:51.589
摘一两个尝一下就可以了

0:02:55.705,0:02:56.925
这个要用剪刀剪

0:02:57.561,0:02:59.002
不过直接掐也可以

0:03:00.473,0:03:02.577
别人剪刀剪了才好看啊

0:03:04.150,0:03:05.521
味道还多安逸

0:03:05.548,0:03:06.989
肯定了人家几十种

0:03:07.923,0:03:11.570
我跟老板说了叫他拿剪刀来剪

0:03:12.293,0:03:14.531
给你剪几斤回去吃

0:03:16.353,0:03:18.133
上面吊的全是票子

0:03:19.133,0:03:22.693
这一条路算下去四伯爷你猜有多重

0:03:22.709,0:03:23.832
几百斤是有的

0:03:24.129,0:03:25.773
300-400斤是有的

0:03:26.036,0:03:27.210
一条400斤嘛

0:03:27.210,0:03:30.003
这里害怕有几百条哦

0:03:30.908,0:03:33.331
诶呀 这些葡萄好安逸哦

0:03:33.514,0:03:34.447
多得很

0:03:39.990,0:03:41.269
嘿 这一串还多安逸

0:03:41.269,0:03:42.158
这串不得行

0:03:42.455,0:03:43.112
不得行啊

0:03:43.938,0:03:45.406
你看上面还有红的都嘛

0:03:45.406,0:03:47.016
哦 都还有红的要黑了才好吃噶

0:03:47.016,0:03:48.684
噢 全部都要黑的

0:03:50.400,0:03:52.119
哦 它挂在绳子上了

0:03:53.366,0:03:54.214
尝两颗看

0:03:54.235,0:03:55.591
尝一下看嘛

0:03:56.523,0:03:57.398
没得事的

0:04:03.048,0:04:04.065
嗯

0:04:04.701,0:04:06.508
这个葡萄安逸呀

0:04:06.692,0:04:07.349
好甜哦

0:04:08.373,0:04:08.693
哎呀

0:04:08.693,0:04:10.173
叔叔这一串黑完了

0:04:10.485,0:04:12.013
哦 就是要这种

0:04:13.408,0:04:14.433
这串黑完了

0:04:15.594,0:04:16.394
我拿着你剪嘛

0:04:16.497,0:04:17.527
就是这种就安逸

0:04:18.945,0:04:19.871
伯爷来尝哈这个

0:04:19.935,0:04:21.067
黢黑的这个

0:04:22.541,0:04:23.131
这个

0:04:23.689,0:04:24.537
又大又黑

0:04:24.873,0:04:27.222
伯娘尝下这个黢黑的肯定更甜

0:04:33.677,0:04:34.073
是吧

0:04:34.311,0:04:34.652
嗯

0:04:37.867,0:04:39.933
我估计要吃6-7斤哦

0:04:42.081,0:04:42.343
你呀

0:04:42.937,0:04:43.222
是啊

0:04:43.222,0:04:43.700
你好能干

0:04:44.339,0:04:46.010
我一会儿都要吃好多哦

0:04:46.010,0:04:46.929
你吃得到6-7斤嘛的

0:04:47.190,0:04:48.073
只能干饱

0:04:51.186,0:04:52.150
我看电视一晚

0:04:52.283,0:04:54.734
一次吃个半斤到1斤最多了

0:04:54.734,0:04:57.355
看电视的时候2-3斤我轻轻就吃了

0:04:58.308,0:04:59.537
你问你伯娘嘛

0:05:00.239,0:05:00.753
噢哦

0:05:00.904,0:05:02.006
一会儿吃一颗一会儿吃一颗

0:05:02.006,0:05:03.236
他吃甜的凶得很的

0:05:03.775,0:05:05.794
我吃肉都只能吃饱

0:05:05.819,0:05:06.772
我都吃不闷

0:05:06.885,0:05:07.211
要得了

0:05:07.753,0:05:09.894
你看叔叔给我们摘了这么多

0:05:10.513,0:05:13.793
这里有十三四斤吧

0:05:14.120,0:05:15.298
这哈提回去慢慢吃

0:05:15.311,0:05:16.101
要得呀

0:05:16.415,0:05:17.882
那走嘛 我们回去了

0:05:18.973,0:05:21.025
快来哟 提起走哦

0:05:25.719,0:05:27.255
好要的 慢走

0:05:31.098,0:05:32.089
总共是好多斤呢

0:05:33.380,0:05:36.415
今天是20多斤哦

0:05:38.273,0:05:40.073
这里20多斤

0:05:40.073,0:05:43.353
这里20多斤给亲戚一人分一包差不多了啊

0:05:46.672,0:05:47.953
现在就打道回府了

0:05:48.427,0:05:50.298
本期视频就到这里 拜拜


```

**Comment by archerdominique** [comment]
bot, please upload
标题（翻译主要意思即可，不要超过 100 个字符）
王刚接伯爷伯娘去看看自己的新工作室，顺便摘点葡萄给亲戚朋友
Chef Wang Gang Shows Uncle and Aunt around His New Studio. Pick some Grapes for Family Relatives

简介
大家好，第一次带伯爷伯娘来看看新工作室，他们很满意，😂到时候要办寿宴就提前预定了！
Hello guys. This is my first time taking uncle and aunt to my new studio, and they are quite satistifed 😂. They made a reservation at mine for their birthday banquet

字幕
0:00:00.364,0:00:01.017
哈喽 大家好
Hello guys

0:00:01.164,0:00:04.185
今天难得抽时间出来带我伯爷伯娘
This is a rare chance today, to have spare time to take my uncle and aunt

0:00:04.185,0:00:05.824
去看一下我的新工作室
to see my new studio

0:00:06.284,0:00:08.102
然后顺便再摘点葡萄吃一下
On the way also pick some grapes to eat

0:00:08.300,0:00:11.120
那个工作室已经弄了有差不多一个月了
That studio has been prepared for almost a month

0:00:11.120,0:00:12.211
这次是第一次去
This is their first time there

0:00:13.805,0:00:14.554
诶呀 好热
Aiya, this is so hot

0:00:15.128,0:00:15.601
好热啊
So hot?

0:00:15.601,0:00:16.497
这里面好热和哦
It's so warm inside here

0:00:16.720,0:00:17.670
马上就开空调
I will turn on the air conditioner at once

0:00:21.554,0:00:22.176
到了 四伯爷
We've arrived, uncle

0:00:25.181,0:00:27.163
哦哟 还是多远一趟哦
Oh, it's such a long way

0:00:27.849,0:00:29.310
慢点慢点
Easy, easy

0:00:33.173,0:00:33.847
看一下嘛
Take a look

0:00:34.360,0:00:35.680
走嘛进去看一下
Come on, let's get in and have a look

0:00:38.499,0:00:39.350
就是这里面
It's in here

0:00:39.533,0:00:41.389
不过这里面夏天有点热
But in summer it's a bit hot

0:00:41.500,0:00:42.828
冬天可能就要好点
Would probably be better when it comes to winter

0:00:42.828,0:00:43.807
冬天就安逸
Winter is comfy

0:00:44.380,0:00:46.533
这个花花草草喊师父来都修剪好了
I have asked some workers to trim the plants well

0:00:46.741,0:00:48.936
不是这里面的草笼笼深得很
Or else the grass and leaves are very thick

0:00:49.764,0:00:52.094
这里场景还可以嘛
This place looks not bad

0:00:53.840,0:00:54.445
宽敞
Wide 

0:00:54.736,0:00:58.544
这里反正是玻璃的光线比较好
It's made of glass, and we have good light

0:00:58.544,0:00:59.544
嗯
Um

0:01:00.300,0:01:01.644
你看有回声
You hear, it's echoing

0:01:01.644,0:01:03.465
这里是喂鱼的吗
Is this for feeding fish?

0:01:03.717,0:01:04.344
嗯
Yeah

0:01:04.668,0:01:05.564
还没放水
Water's not in yet

0:01:06.315,0:01:07.067
可以啊
Good

0:01:08.555,0:01:10.839
这些桌子都可以转的
We've got spinning plate on these tables

0:01:11.377,0:01:14.001
可以可以可以
Nice nice 

0:01:14.567,0:01:17.831
这里面都没有吊的灯都是安的路灯
The lamps are not hanging above, they are installed on the ground 

0:01:19.171,0:01:21.052
就跟外面的路灯一样的
Like street lamps outside

0:01:21.679,0:01:23.202
这个是塑料的吗
Is this made from plastics?

0:01:23.650,0:01:25.218
是铁的
Steel

0:01:27.540,0:01:28.220
走嘛
Let's go

0:01:38.073,0:01:40.000
这就是厨房我把灯打开
This is the kitchen, and I'll turn on the light

0:01:42.094,0:01:44.467
哦哟 好宽哦
Oh yo, it's so spacious

0:01:45.023,0:01:45.746
可以
Good

0:01:48.822,0:01:49.898
6个灶
Six stoves

0:01:51.566,0:01:55.069
以后你满70岁的时候好生给你整哈
Later when you are 70 I'll cook you a good banquet

0:01:55.180,0:01:55.792
要的啊
Of course

0:01:56.237,0:01:58.109
可以啊
Ok

0:01:58.257,0:02:01.000
伯娘满60岁都可以给你炒几桌
When aunt gets 60 I can also prepare a banquet for you 

0:02:01.000,0:02:01.668
要的啊
Definitely

0:02:02.520,0:02:04.900
这里是7米的灶
The stoves take 7 metre's length

0:02:05.968,0:02:07.408
加这个灶7米
With this one, 7 metre

0:02:07.469,0:02:10.935
这个灶是2米1个3个灶加1个这个灶
This one is 2 metre long, we've got three of the kind, as well as this one

0:02:11.770,0:02:13.960
这里可以同时6个人炒菜
It allows 6 persons to cook at the same time

0:02:14.460,0:02:15.140
可以
Good

0:02:15.140,0:02:15.460
可以
Nice

0:02:15.500,0:02:16.260
可以啊
So good

0:02:16.626,0:02:18.660
如果是炒菜这边可以蒸东西
You can steam-cook stuff here when one is stir-frying there

0:02:19.273,0:02:21.223
然后这边有2个冰箱
And then there are 2 fridges

0:02:21.223,0:02:25.079
就是你满十的话整2头猪都放得进去
Even if you need 2 whole pigs for your birthday banquet you can store the pork here 

0:02:25.727,0:02:28.322
3头猪都放得进去
It can store even three

0:02:29.100,0:02:29.577
可以
Nice

0:02:29.577,0:02:32.196
前段时间没有整归一都不好带你们来看得
Previously it was not well furnished, and I could not show you around

0:02:32.196,0:02:34.140
这里乱糟糟的
It was quite messy

0:02:34.260,0:02:36.315
哪里嘛 这下整好了就可以了
No worries, now that it's all finished

0:02:36.430,0:02:38.985
要得 走带你们摘点葡萄回去吃
Of course. Come, I take you to pick some grapes

0:02:39.696,0:02:42.738
四伯爷种了那么多年的庄稼没看见过这样的嘛
Uncle, you've been farming many years have you seen anything like this?

0:02:42.738,0:02:44.341
没看见过
Not really

0:02:44.381,0:02:45.659
结起一片片的
Growing to quite a few patches

0:02:49.797,0:02:51.589
摘一两个尝一下就可以了
Pick one or two and have a taste

0:02:55.705,0:02:56.925
这个要用剪刀剪
It's better to cut it using scissors

0:02:57.561,0:02:59.002
不过直接掐也可以
But it's alright to pick directly by your hands

0:03:00.473,0:03:02.577
别人剪刀剪了才好看啊
They cut with scissors to make them look better

0:03:04.150,0:03:05.521
味道还多安逸
The taste is so nice

0:03:05.548,0:03:06.989
肯定了人家几十种
Of course they've got so many types of grapes here

0:03:07.923,0:03:11.570
我跟老板说了叫他拿剪刀来剪
I've asked the manager to take scissors to cut the vine

0:03:12.293,0:03:14.531
给你剪几斤回去吃
A few jins of grapes for you to bring back home 

0:03:16.353,0:03:18.133
上面吊的全是票子
There are all cashes hanging above

0:03:19.133,0:03:22.693
这一条路算下去四伯爷你猜有多重
Take a count, uncle, guess how does they weigh, all the grapes along this path

0:03:22.709,0:03:23.832
几百斤是有的
Must be hundreds of jins

0:03:24.129,0:03:25.773
300-400斤是有的
Definitely has 300 to 400 jins

0:03:26.036,0:03:27.210
一条400斤嘛
400 jins per path

0:03:27.210,0:03:30.003
这里害怕有几百条哦
I'm afraid there are hundreds of paths here

0:03:30.908,0:03:33.331
诶呀 这些葡萄好安逸哦
Aiya, these grapes are so nice

0:03:33.514,0:03:34.447
多得很
There are plenties here

0:03:39.990,0:03:41.269
嘿 这一串还多安逸
Hey, this string looks quite nice

0:03:41.269,0:03:42.158
这串不得行
Not really

0:03:42.455,0:03:43.112
不得行啊
Is it?

0:03:43.938,0:03:45.406
你看上面还有红的都嘛
You see, there are some red bits in the string

0:03:45.406,0:03:47.016
哦 都还有红的要黑了才好吃噶
Oh, there are still some red bits. Not tasty until they turn black

0:03:47.016,0:03:48.684
噢 全部都要黑的
Oh, we need it all black 

0:03:50.400,0:03:52.119
哦 它挂在绳子上了
Oh, it hangs on a rope

0:03:53.366,0:03:54.214
尝两颗看
Try one or two

0:03:54.235,0:03:55.591
尝一下看嘛
Have a taste

0:03:56.523,0:03:57.398
没得事的
It's alright

0:04:03.048,0:04:04.065
嗯
Um

0:04:04.701,0:04:06.508
这个葡萄安逸呀
These grapes are nice

0:04:06.692,0:04:07.349
好甜哦
So sweet

0:04:08.373,0:04:08.693
哎呀
Aiya

0:04:08.693,0:04:10.173
叔叔这一串黑完了
Uncle, this string is all black

0:04:10.485,0:04:12.013
哦 就是要这种
Ohh, this is what you need

0:04:13.408,0:04:14.433
这串黑完了
This string is all black

0:04:15.594,0:04:16.394
我拿着你剪嘛
I hold it for you to cut

0:04:16.497,0:04:17.527
就是这种就安逸
We need just this kind. It's so nice

0:04:18.945,0:04:19.871
伯爷来尝哈这个
Come on, uncle. Have a taste of this

0:04:19.935,0:04:21.067
黢黑的这个
Pitch black

0:04:22.541,0:04:23.131
这个
This

0:04:23.689,0:04:24.537
又大又黑
Black and large

0:04:24.873,0:04:27.222
伯娘尝下这个黢黑的肯定更甜
Aunt, try this black one. It must taste sweeter

0:04:33.677,0:04:34.073
是吧
Isn't it?

0:04:34.311,0:04:34.652
嗯
Emm

0:04:37.867,0:04:39.933
我估计要吃6-7斤哦
I could eat 6 to 7 jins

0:04:42.081,0:04:42.343
你呀
You?

0:04:42.937,0:04:43.222
是啊
Of course

0:04:43.222,0:04:43.700
你好能干
You're quite good at it!

0:04:44.339,0:04:46.010
我一会儿都要吃好多哦
I can eat a lot in a while

0:04:46.010,0:04:46.929
你吃得到6-7斤嘛的
Can you really eat 6 to 7 jins?

0:04:47.190,0:04:48.073
只能干饱
(什么是干饱……？

0:04:51.186,0:04:52.150
我看电视一晚
I watch the TV for an evening

0:04:52.283,0:04:54.734
一次吃个半斤到1斤最多了
I would eat at most half to one jin a time

0:04:54.734,0:04:57.355
看电视的时候2-3斤我轻轻就吃了
Watching TV I eat 2 to 3 jins easily

0:04:58.308,0:04:59.537
你问你伯娘嘛
You ask your aunt

0:05:00.239,0:05:00.753
噢哦
Ohh

0:05:00.904,0:05:02.006
一会儿吃一颗一会儿吃一颗
One grape after another

0:05:02.006,0:05:03.236
他吃甜的凶得很的
He's very fierce at eating sweets

0:05:03.775,0:05:05.794
我吃肉都只能吃饱
Meat can only fill my stomach

0:05:05.819,0:05:06.772
我都吃不闷
?

0:05:06.885,0:05:07.211
要得了
Good

0:05:07.753,0:05:09.894
你看叔叔给我们摘了这么多
You see, the uncle have picked so many for us

0:05:10.513,0:05:13.793
这里有十三四斤吧
We've got probably 13 or 14 jins here

0:05:14.120,0:05:15.298
这哈提回去慢慢吃
Let's bring them back and eat them at ease

0:05:15.311,0:05:16.101
要得呀
Of course

0:05:16.415,0:05:17.882
那走嘛 我们回去了
Let's go then, we're going back

0:05:18.973,0:05:21.025
快来哟 提起走哦
Come on quick, take them up

0:05:25.719,0:05:27.255
好要的 慢走
Ok, good, take your pace

0:05:31.098,0:05:32.089
总共是好多斤呢
How many jins are there?

0:05:33.380,0:05:36.415
今天是20多斤哦
Today is over 20 jins

0:05:38.273,0:05:40.073
这里20多斤
We've got more than 20 jins here

0:05:40.073,0:05:43.353
这里20多斤给亲戚一人分一包差不多了啊
20 jins, should be enough if we give every relative a bag of grapes

0:05:46.672,0:05:47.953
现在就打道回府了
Now we're returning home

0:05:48.427,0:05:50.298
本期视频就到这里 拜拜
That's all for today's video, bye!

**Comment by SilvesterDong** [comment]
bot, please upload

**Comment by immoonancient** [comment]
不好意思昨天漏了上传这期...
