### ISSUE TITLE
[华农兄弟]再借公鼠 - https://www.youtube.com/watch?v=6oBeqQFSJZs

### ISSUE THREAD

**Issue by vincenthychow** [immoonancient/YTSubtitles#131]
[华农兄弟]再借公鼠 - https://www.youtube.com/watch?v=6oBeqQFSJZs

**Comment by immoonancient** [comment]
视频那里出了点问题，lock 了一个空字幕。现在成品字幕无法上传
等待清哥调整中...

**Comment by immoonancient** [comment]
沟通过了，我们的字幕上传到英文（英国）然后自行发布
