### ISSUE TITLE
[华农兄弟] 华农兄弟拔点摄影小哥家的花生顺便游个泳再摘点兄弟家的西瓜 - https://youtu.be/xNrY7m4R7no

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1315]
https://youtu.be/xNrY7m4R7no
<p>&#35270;&#39057;&#21457;&#24067;&#20110; July 25, 2020 at 11:36AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/xNrY7m4R7no

#华农兄弟：拔点摄影小哥家的花生，顺便游个泳，再摘点兄弟家的西瓜
#Huanong Brothers: We pick some Mr. Cameraman's peanuts and also have a swim. And them pick some watermelons from my buddy's place.

0:00:00.000,0:00:00.700
# 大家好
Hi everyone!

0:00:01.480,0:00:03.520
# 現在這個花生熟啦  這玉米也熟啦
Now the peanuts here are ripe, and so are the corns.

0:00:04.720,0:00:07.120
# 我撴一下那太陽傘  大熱這啦天氣
I'm trying to stand an umbrella here. It's too hot now.

0:00:07.780,0:00:09.840
# 我順便拔一點回去  回去煮
I'll then pick some back home, and then cook them.

0:00:10.660,0:00:13.440
# 這攝影小哥家的  我家今年  今年沒種
These are Mr. Cameraman's peanuts. I haven't, haven't grown any this year.

0:00:14.580,0:00:17.360
# 我不用種  左隣右舍都種了很多
I don't need to. Everybody next to me is already growing a lot.

0:00:19.280,0:00:22.000
# 到前面去 它怎麼斜在這
Let me go to the front. Why isn't it standing upright?

0:00:22.000,0:00:23.580
# 誒呦   小朋友
Aya! Kid!

0:00:37.540,0:00:39.100
# 你看  這太陽傘立好啦
Look! This umbrella is alright now.

0:00:40.000,0:00:42.120
# 這樣就可以躲一下太陽  就沒有那麼熱
Then we can have a shelter, and it's not so hot now.

0:00:43.080,0:00:44.000
# 誒  桶呢
Eh? Where's my bucket?

0:00:48.000,0:00:50.200
# 搞點花生  用來煮著吃
Pick some peanuts, then we can cook them.

0:00:50.900,0:00:51.780
# 很好吃的哦
It's really tasty, you know.

0:00:54.740,0:00:55.600
# 哎呀
Aya!

0:00:56.160,0:00:56.840
# 你看
Look!

0:00:58.240,0:00:59.940
# 粒粒飽滿  好多啊
Round and full. A lot!

0:01:04.160,0:01:07.260
# 這花生就是拔好拔  但摘的時候不好摘
The peanuts, pulling them out is easy. But picking them off is a headache.

0:01:10.120,0:01:11.460
# 要一個一個摘
They need to be picked one by one.

0:01:21.340,0:01:22.120
# 好多哦
A lot!

0:01:26.600,0:01:28.360
# 要下了雨來拔應該很好拔
It should be much easier after rain.

0:01:29.900,0:01:31.260
# 趕緊來幫忙
Come and help us! C'mon! 

0:01:40.120,0:01:41.440
# 這是我的
This is mine.

0:01:41.440,0:01:43.520
# 你看我多麼粗暴的拔
See how rudely I'm picking them?

0:01:47.200,0:01:49.100
# 我都在拔呢
I'm also picking.

0:01:49.600,0:01:51.160
# 你在拔是不是  嗯
You're picking, aren't you?
Um!

0:01:51.420,0:01:53.280
# 好啊  等下你多吃兩個啊
Good! Eat more in a while, alright?

0:01:59.000,0:02:00.440
# 這個草來的
This is weed.

0:02:01.880,0:02:04.280
# 啊  太熱啦  你看  全身都是汗
Ah! It's too hot! Look! I'm soaked with sweat.

0:02:05.380,0:02:07.600
# 我下去河  河裡面泡一下  受不了啦
Let me go, go into the river. I can't stand anymore.

0:02:09.740,0:02:12.080
# 啊  你看這個水潭
Ah! Have a look at this pond!

0:02:13.140,0:02:14.500
# 這個水潭舒服的哦
This pond is really nice, you know.

0:02:24.260,0:02:25.640
# 啊  舒服
Ah! Cool!

0:02:29.160,0:02:30.220
# 誒  這個淺噠
Eh? Why is it so shallow?

0:02:30.880,0:02:33.820
# 這裡就深一點  這裡你看  全部  下面全部是沙子
It's a bit deeper here. Here, look, it's all, all sand at the bottom.

0:02:37.720,0:02:39.640
# 在水裡泡一下舒服多啦
Soaking in the water, makes me feel so much better.

0:02:40.800,0:02:42.980
# 現在最少三十六度以上哦
I think it's now at least thirty six degrees.

0:02:44.300,0:02:45.220
# 要不要下來哦
You wanna come down?

0:02:47.120,0:02:48.220
# 不要拍啦  下來
Come down! Don't film anymore!

0:02:55.120,0:02:58.840
# 嗯~太淺啦這裡  找個深一點的地方
Um~ The water is too shallow here. Let me find a deeper spot.

0:02:59.780,0:03:01.600
# 誒  剛好從  可以從這裡過
Eh? I can pass, pass right from here.

0:03:24.880,0:03:27.660
# 哇  這  全身泡在水裡很舒服的哦
Wa! It's, you know, soaking the whole body in the water is really great.

0:03:29.220,0:03:32.100
# 全身都涼爽一下  你看 我兒子也來了
It cools every inch of my skin. Look! My son is also coming.

0:03:52.620,0:03:53.680
# 我厲害吧
Am I marvellous?

0:03:55.180,0:03:56.400
# 爸爸再遊回去  你看
Daddy is gonna swim back there, look!

0:04:06.740,0:04:10.000
# 剛遊完泳是吧 全身清爽是吧  搞幾個西瓜來吃
After swimming, the whole body is cool. Let's fetch some watermelons.

0:04:10.380,0:04:12.900
# 去兄弟家  他家西瓜熟啦  剛才叫我去
Let's go to my buddy's place. His watermelons are ripe now and he just asked me to go.

0:04:13.080,0:04:14.660
# 走  帶你們去摘西瓜
Let's go! Come with me to pick watermelons!

0:04:15.000,0:04:17.340
# 帶你們去  摘西瓜  走
Come with me, to pick watermelons. Let's go!

0:04:48.440,0:04:52.960
# 你看  掏出來啦  兄弟幫我把它搞  搞出來的
Look! We've taken it out! My buddy helps he bring it, bring it out.

0:04:53.880,0:04:55.180
# 那裡條路  過不去
There's roadwork. We can't pass.

0:04:55.860,0:04:58.300
# 這裡一袋  那輛車還有一袋  這還有兩個
Here's a bag. There's another bag in another car. Two more are coming.

0:04:59.860,0:05:00.600
# 這還有兩個
Here are two more.

0:05:04.820,0:05:07.100
# 你看  就摘了那麼一丟丟  太熱啦
Look! We've just picked a tiny little bit here. It's too hot.

0:05:07.860,0:05:09.500
# 等下雨的時候我再去拔
I'll go again when it rains.

0:05:14.780,0:05:16.280
# 差不多啦  夠啦
Alright! It's enough.

0:05:18.060,0:05:21.000
# 經常煮這一個來吃  要洗乾淨來
We'll make it very often. Let's wash them first.

0:05:27.700,0:05:30.360
# 你看  搓兩下就幹淨啦  這花生
Look! Squeeze them a couple of time and its cleansed, the peanuts.

0:05:31.420,0:05:33.680
# 這水  把這個水
The water, pour out,

0:05:35.180,0:05:35.860
# 倒掉
the water.

0:05:37.760,0:05:40.020
# 這個花生都是種下去就沒人管了
After planting, nobody has ever taken care of the peanuts.

0:05:41.720,0:05:44.980
# 我去看了一下  還沒死
Then I took a look and they were still alive.

0:05:47.380,0:05:49.140
# 現在就長了那麼多
And now so many have grown.

0:05:56.900,0:05:58.400
# 來  加點鹽下去就好啦
Alright! Put some salt and that's it.

0:06:01.140,0:06:02.060
# 夠了  夠了
Enough, enough

0:06:03.900,0:06:04.400
# 可以
Alright!

0:06:07.120,0:06:08.460
# 好啦  開始煮啦
Alright! Let's start cooking.

0:06:09.680,0:06:12.960
# 要煮差不多一個多小時就可以吃啦
Cook it for around an hour and something, then we can our feast.

0:06:13.860,0:06:15.580
# 好  我們就等一等
Alright! Let's wait.

0:06:15.920,0:06:19.380
# 你看  這兩條繩子拴着它  就可以放養啦
Look! With these two strings, I can let them walk around now.

0:06:19.880,0:06:21.440
# 如果不拴著它  它全跑的哦
They would run away, if they're not tethered, you know.

0:06:21.620,0:06:23.820
# 要拴一個月左右才放  要不然不放
I'm gonna tether them for a month, before I can let them run around freely.

0:06:24.440,0:06:25.660
# 跑了就太可惜了
It would be too bad if they run away.

0:06:27.080,0:06:29.840
# 上次找這兩隻  找  找那隻黑色那隻羊
Last time I looked for the two, looked, looked for the, for the black goat.

0:06:30.480,0:06:31.660
# 找的太辛苦啦
It was killing me.

0:06:42.180,0:06:43.160
# 嘿呦
Heyo!

0:06:45.480,0:06:46.480
# 一看到我就跑
They run away once they see me.

0:06:49.600,0:06:51.040
# 管它嘞  讓它們吃飽來
Leave them alone, and let them eat as much as they like.

0:06:51.320,0:06:52.920
# 讓它清理一下這些草也好
It's nice to let them clear some of the weed here.

0:06:55.080,0:06:56.340
# 晚上再把它牽回去
I'm gonna take them back to the shed at night.

0:07:01.260,0:07:02.880
# 這個熟了哦這個
It's done now, the peanuts.

0:07:04.480,0:07:05.280
# 把它抬出來
Let me take it out there.

0:07:06.220,0:07:06.720
# 好燙
Hot!

0:07:07.160,0:07:08.880
# 你看這個花生熟了
Look! The peanuts are done now.

0:07:09.340,0:07:10.200
# 很香的哦
It smells really good, you know.

0:07:16.400,0:07:17.100
# 有點燙
It's a bit hot.

0:07:18.040,0:07:18.820
# 剛起鍋的
It's just taken away from the heat.

0:07:23.220,0:07:24.400
# 好像差了點鹽
It seems that the salt is not quite enough.

0:07:35.120,0:07:37.280
# 哇  好香啊
Wa! It smells wonderful!

0:07:37.280,0:07:39.080
# 好香啊  太燙了哦
It's good. Too hot, isn't it?

0:07:40.500,0:07:41.040
# 好不好吃
Does it taste good?

0:07:42.620,0:07:43.220
# 不要怕燙
Never mind the heat

0:07:43.480,0:07:45.540
# 沒事啊  不燙了不燙了  不燙吼
It's fine. It's not hot, it's not not, it's not hot anymore.

0:07:46.040,0:07:47.580
# 嗯  好糯啊
Um! It's soft and mushy.

0:07:50.960,0:07:52.260
# 好不好吃刘星辰
Does it taste good? Liu Xingchen.

0:07:52.260,0:07:52.800
# 好吃
Yup!

0:07:53.080,0:07:53.580
# 好吃
Indeed

0:07:56.940,0:07:58.280
# 家裡好玩還是縣城好玩
Where do you like more? In the village or in the county seat?

0:07:58.540,0:07:59.140
# 家裡
In the village

0:07:59.540,0:08:01.860
# 家裡好玩哦  又可以去游泳 是不是
Yea, in the village. And you can go swimming too, right?

0:08:01.860,0:08:02.400
# 嗯
Um!

0:08:04.000,0:08:05.800
# 縣城  只能關在家裡
In the county seat, I can only stay at home.

0:08:06.140,0:08:07.260
# 只能關在家裡是不是
You can only stay at home, right?

0:08:09.660,0:08:11.900
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:08:13.940,0:08:14.840
# 帶小孩
I gotta take care of the kids.
