### ISSUE TITLE
[华农兄弟] 华农兄弟狗子又生了一窝小奶狗拿手上软绵绵胖乎乎的 - https://youtu.be/Nx3LPY26bh4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1350]
https://youtu.be/Nx3LPY26bh4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 5, 2020 at 01:04PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/Nx3LPY26bh4

#华农兄弟：狗子又生了一窝小奶狗，拿手上软绵绵，胖乎乎的
#Huanong Brothers: Dog gave birth to another litter of puppies. All are soft and chubby.

0:00:00.000,0:00:03.680
# 前幾天那個小  那個母狗哦 母狗它又生啦  你看
Hi everyone! The pup...The mother dog, the mother, gave birth again a few days ago. Look!

0:00:03.680,0:00:04.860
# 生了好多隻
She has born a lot of puppies.

0:00:05.300,0:00:06.220
# 我去看一下
Let's go and have a look.

0:00:07.380,0:00:08.380
# 這是它的飯飯
This is their meal.

0:00:09.560,0:00:11.360
# 哇  東一條西一條
Wa! One is here and one is there.

0:00:12.440,0:00:14.320
# 你看  一地都是狗崽
Look! The puppies are everywhere.

0:00:14.720,0:00:17.300
# 我想摸這個白  我想摸這個棕的
I wanna touch this white, I wanna touch this brown one.

0:00:17.780,0:00:21.240
# 天氣熱 它們都是  睡的亂七八糟的
It's hot. So they're all sleeping everywhere, here and there.

0:00:21.940,0:00:24.760
# 你看  那麼多堆  這兩隻黑的是小黑的
They're so scattered. These two black ones are Blacky's puppies.

0:00:25.540,0:00:27.240
# 剩下都是那母狗生的
And the rest are all the mother's.

0:00:28.120,0:00:31.140
# 因為小黑不會帶崽  所以拿到這裡給它帶
Blacky doesn't take care of the puppies at all. So I bring them to her mom.

0:00:31.160,0:00:32.360
# 它們兩個星兩姊妹嗎
Are these two puppies sisters?

0:00:32.360,0:00:32.920
# 對呀
Yea!

0:00:33.540,0:00:38.140
# 哪個是  哪個是女的哪個是男的  這兩個黑的
Which one, which one is a girl and which one is a boy? I mean these two black ones.

0:00:38.140,0:00:40.260
# 這個你要問它哦  我又不知道哦
You really gotta ask them. I have no way to tell.

0:00:41.260,0:00:42.980
# 你看這個是不是  這種產色的
Have a look at this one. Isn't it, what kind of colour is it?

0:00:44.780,0:00:47.460
# 它  它眼睛都不張開的呀
Why, why don't they open their eyes?

0:00:47.460,0:00:49.500
# 沒那麼快  要到二十天左右才張開
Not so soon. It takes around twenty days before they can open their eyes.

0:00:50.940,0:00:53.320
# 你看  這個就是  灰的  是不是
Look! This is, this is grey, isn't it?

0:00:54.020,0:00:55.020
# 我想摸
I wanna touch it.

0:00:57.740,0:01:00.400
# 它們都吃的好飽哦  八條狗崽都吃的好飽
They've all eaten a lot. All eight puppies have eaten a lot.

0:01:00.440,0:01:03.540
# 這個好漂亮哦 它想爬走
This is really pretty. It wants to run away.

0:01:05.420,0:01:07.220
# 哇  這個也好漂亮
Wa! This is also very pretty!

0:01:08.420,0:01:10.380
# 為甚麼這些老是動啊
Why are they always moving?

0:01:11.240,0:01:12.580
# 不知道  它害怕
No ideas. Perhaps they're scared.

0:01:16.500,0:01:17.340
# 你看這小狗
Have a look at this puppy!

0:01:17.660,0:01:19.320
# 你看  咕嚕咕嚕咕嚕咕嚕
Look! Gulu gulu gulu gulu

0:01:20.400,0:01:22.240
# 好可愛  這個哦
It's really cute, this one, oh.

0:01:23.120,0:01:24.160
# 像這樣抱著它
You can hold it here.

0:01:26.320,0:01:27.820
# 這也好可愛
This is also very cute.

0:01:33.040,0:01:34.260
# 它眼這樣閉著的
So its eyes are just closed.

0:01:36.300,0:01:37.940
# 這也好可愛  嗯
And this one is cute as well.
Um!

0:01:40.960,0:01:42.640
# 打哈欠  想睡覺
It's yawning. It wants to sleep.

0:01:43.600,0:01:46.420
# 睡在我手上多舒服啊  是不是  你看
Sleeping on my hands is so comfortable. Isn't it? Look!

0:01:53.220,0:01:54.620
# 要不要給一個給你玩
Do you wanna play with one of them?

0:01:56.020,0:01:56.700
# 要不要
Do you?

0:01:58.680,0:02:00.100
# 嘿嘿  妹妹也不敢
Hehe
Little girl doesn't dare.

0:02:00.100,0:02:00.840
# 不要是不是
You don't want, do you?

0:02:01.620,0:02:02.600
# 你敢是不是
But you dare, don't you?

0:02:02.600,0:02:03.140
# 嗯
Um...

0:02:03.680,0:02:06.400
# 你看 好可愛  要不要親它
Look! It's so cute. You wanna kiss it?

0:02:07.380,0:02:08.400
# 嘿嘿嘿嘿
Hehe hehe

0:02:11.620,0:02:13.500
# 你想往哪裡跑
Where exactly do you want to go?

0:02:15.640,0:02:17.580
# 好啦好啦好啦好啦 走了走了  刘星辰
Alright, aright, alright, alright! Let's go, let's go! Liu Xingchen!

0:02:17.920,0:02:19.280
# 你別提人家尾巴
Don't grab its tail!

0:02:21.880,0:02:23.020
# 好啦 小
Alright! Kids,

0:02:23.200,0:02:25.780
# 全部都調皮搗蛋  是不是  老是動人家
they're all little monsters, aren't they? They're always disturbing the puppies.

0:02:25.780,0:02:26.780
# 好啦
Alright!

0:02:27.660,0:02:32.260
# 讓它們 睡在這裡  等下晚上母狗它會回來
Let them, sleep here. The mother is gonna come back, later in the evening.

0:02:32.960,0:02:33.680
# 餵奶的
She'll feed them.

0:02:34.780,0:02:36.560
# 我去搞點好吃的給那個母狗吃
Let me go and fetch some good food for the mother.

0:02:39.160,0:02:40.460
# 個個都很健康哦
They're all in very good health.
