### ISSUE TITLE
[华农兄弟] 华农兄弟抓只猪回来处理剩饭剩菜顺便抓只鸡来炖很香哦 - https://youtu.be/xxUh8Ifjrnk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1359]
https://youtu.be/xxUh8Ifjrnk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 7, 2020 at 11:40AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/xxUh8Ifjrnk

#华农兄弟：抓只猪回来处理剩饭剩菜，顺便抓只鸡来炖，很香哦
#Huanong Brothers: We catch a pig to deal with the leftover, and also a chicken. We cook the chicken. It smells so good.


0:00:00.000,0:00:03.100
# 大家好  家裡的剩飯剩菜太多啦  那小狗都吃不完
Hi everyone! We have far too much leftover at home. Those doggies just can't finish it.

0:00:03.660,0:00:05.020
# 去兄弟家搞條豬來
I'm gonna fetch a pig from my buddy's place.

0:00:05.420,0:00:08.780
# 用豬來吃  合理利用  那就不會沒  沒有那個浪
I use a pig. It's called reasonable utilisation. Then it won't be, not so, there won't be so, I mean...

0:00:09.080,0:00:12.100
# 不會浪費啦 就沒有那麼多那個剩飯剩菜扔出去
We won't be wasting so much food. We won't need to throw away so much, you know, so much leftover.

0:00:12.920,0:00:14.800
# 小豬幾乎甚麼都可以吃的掉
Piggies eat almost everything.

0:00:15.680,0:00:17.820
# 你看  香蕉  好多哇
Look! Bananas. A lot!

0:00:18.440,0:00:19.520
# 下面還有池塘哦
There's also a pond down there.

0:00:20.480,0:00:22.020
# 兄弟家豬場在上面一點
My buddy's pig farm is just a bit up there.

0:00:23.000,0:00:25.800
# 那條鵝我抓一下看抓不抓很到  好大啊
That goose, let me see if I can catch it. It's huge!

0:00:29.580,0:00:30.900
# 全啄人的這個雞
It pecks, this chicken.

0:00:31.880,0:00:32.680
# 大公雞
A big rooster

0:00:34.940,0:00:37.900
# 你看  我們養的那鵝就前面那個小的一樣那麼大
Look! Our geese are only as big as the small one in the front,

0:00:37.900,0:00:39.000
# 那麼大一點點哦
or a tiny little bit larger.

0:00:39.000,0:00:41.580
# 你看  這個鵝好大啊  大了一兩倍
Look! This goose is really big. It's double or even triple in size.

0:00:46.980,0:00:47.480
# 你看
Look!

0:00:48.360,0:00:49.040
# 那麼大
It's so big!

0:00:51.940,0:00:54.200
# 豬就在這裡面  我們進去看一下
The pigs are here inside. Let's get in and have a look.

0:00:58.880,0:00:59.460
# 你看
Look!

0:01:00.220,0:01:02.060
# 一堆喲  小豬崽
A bunch of them, piglets

0:01:02.280,0:01:03.460
# 比較小的這些
These are a bit smaller.

0:01:14.620,0:01:16.420
# 你看  這就是兄弟養的
Look! These are my buddy's,

0:01:16.820,0:01:17.440
# 香豬
Huanjian pigs.

0:01:18.320,0:01:20.400
# 嘴巴好像尖  尖了一些
Their mouths seem to be a bit, a bit pointed.

0:01:27.120,0:01:28.820
# 你看  這小豬好可愛喲
Look! These piglets are really cute.

0:01:32.440,0:01:33.100
# 它一
In one,

0:01:33.580,0:01:35.340
# 它一窩就生了十來條
there's a dozen of piglets in a single litter.

0:01:35.380,0:01:36.760
# 這兩條都是母的
Both of them are sow.

0:01:51.340,0:01:54.860
# 你看  這個豬欄都是就地取材  全部是用那個小木頭
Look! This pigsty is built with local and natural resources. These are all small logs.

0:01:56.020,0:01:57.340
# 一根一根釘起來的
They were nailed one by one.

0:01:57.720,0:01:58.740
# 把紥實的哦
It's really firm, you know.

0:02:46.120,0:02:48.940
# 好啦  終於把它抓  抓回來啦
Alright! Finally we've, we've got it.

0:02:50.900,0:02:52.200
# 我它拉回我們家去
We're gonna take it back to our site.

0:02:58.360,0:02:59.840
# 呃  順便帶一隻雞回去
Eh, why don't we take a chicken with us?

0:02:59.840,0:03:01.880
# 你看  這些都是放養雞來的  很好吃的哦
Look! These are all free range chickens. They taste really good, you know.

0:03:03.080,0:03:04.740
# 拿抄網來抄  抄一個來
Let me get a catching net, and catch one.

0:03:11.320,0:03:12.120
# 有沒抓到
Got it?

0:03:29.900,0:03:32.340
# 你看  這是老閹雞來的哦
Look! This is an old capon.

0:03:32.880,0:03:34.100
# 這個雞閹過了的
It has been castrated.

0:03:34.940,0:03:36.040
# 肉質很好吃的
The texture of the meat is really good.

0:03:41.040,0:03:41.740
# 沒蛋
No balls

0:03:44.580,0:03:46.060
# 可以  好啦 我們先回去
Okay, alright! Let's go back first.

0:03:53.420,0:03:55.280
# 一百三十
A hundred and thirty...

0:03:57.420,0:03:58.200
# 三十二
thirty two

0:03:58.540,0:03:59.620
# 一百三十
A hundred and thirty

0:04:15.120,0:04:16.360
# 胡韦汝
Hu Weiru!

0:04:32.800,0:04:33.620
# 你看  這頭豬
Have a look at this pig!

0:04:34.220,0:04:36.660
# 太胖啦  身上的肥膘都出來啦
It's too fat. Its whole body is covered with fat.

0:04:37.320,0:04:40.840
# 我先放到這個  這個豬欄裡面餓它三天三夜
I'll first put it in the, in the pigsty and starve it for three whole days and nights.

0:04:41.400,0:04:44.060
# 然後再來餵 餵朲西給它吃  它就會吃啦
And then I'll feed it, feed it something. It will be eating then.

0:04:45.620,0:04:47.760
# 你看  生無可戀一樣
Look! It seems that it has lost all its meanings of life.

0:04:48.880,0:04:50.900
# 可以 我又不會對你怎麼啦
Fine! I'm not doing any harm to you.

0:04:51.600,0:04:52.840
# 剛好把它移過這裡來
Right now we can move it to this side.

0:05:08.180,0:05:09.840
# 出去出去 你自由啦
Get out, get out! You're free now!

0:05:10.380,0:05:11.120
# 這裡
Here,

0:05:11.920,0:05:13.840
# 這很好玩的哦  你不出來
there's so much fun here, you now. Why aren't you coming out?

0:05:16.800,0:05:19.460
# 拍不屁股  拍你屁股  不出來
Spank you, I spank you. You're not coming out.

0:05:33.740,0:05:35.480
# 這個豬受驚嚇啦
This pig, is traumatised.

0:05:38.980,0:05:39.800
# 很怕人
It's very scared of people.

0:05:40.760,0:05:43.840
# 一直  以為  以為馬上就要吃它啦
It keeps thinking, thinking that we might eat it immediately.

0:05:48.660,0:05:49.500
# 不理我
No response

0:05:52.280,0:05:54.200
# 你看  它現在一動不動的
Look! It's now like a statue.

0:05:54.740,0:05:57.340
# 先餓它三天三夜  去一下它身上的油脂
Let's first starve it for three whole days and nights, to get rid some of the oil and fat on its body.

0:05:58.080,0:06:00.040
# 然後再想辦法  看一下怎麼
And then let's see, how we can,

0:06:00.640,0:06:01.540
# 怎麼煮它
how we can cook it.

0:06:02.860,0:06:05.080
# 紅燒還是清蒸 還是烤
Would it be stew, or steam, or grill?

0:06:08.840,0:06:09.940
# 理都不理人
It ignores me completely.

0:06:10.360,0:06:12.280
# 肯定害怕受了驚嚇  沒事
It must be scared. It's traumatised. No worries.

0:06:12.780,0:06:13.680
# 明天就好啦
It will be alright tomorrow.

0:06:16.120,0:06:17.540
# 你看  這還有個南瓜哦
Look! Here are also some pumpkins.

0:06:17.920,0:06:19.980
# 以前是  以前那  那批豬種的
They were there, they were planted by our pre, previous batch of pigs.

0:06:20.720,0:06:21.740
# 這裡還有一個
Here's one more.

0:06:22.960,0:06:24.780
# 來  拿點南瓜給你吃
C'mon! Here are some pumpkins for you!

0:06:24.780,0:06:25.700
# 這個南瓜
These are pumpkins.

0:06:26.940,0:06:28.300
# 看它吃不吃  哎呀
Let's see if it's eating. Aya!

0:06:36.980,0:06:37.880
# 一動不動
It's like a statue.

0:06:39.140,0:06:40.440
# 它又想吃又害怕
It wants to eat but it's scared.

0:06:41.160,0:06:41.840
# 沒事
No worries!

0:06:43.380,0:06:44.400
# 過段時間就好啦
It will be alright after some time.

0:06:46.200,0:06:47.040
# 不管它啦
Leave it alone.

0:06:47.560,0:06:48.640
# 過兩天再來看它
I'll come again in a couple of days.

0:06:49.080,0:06:50.440
# 餓不死它  它那麼胖
It can survive. It's so fat.

0:06:52.020,0:06:53.100
# 豬已經安頓好啦
So now the pig is settled down.

0:06:53.540,0:06:54.740
# 就安排這隻鴨
It's time for the duck.

0:06:54.960,0:06:56.300
# 這隻不是鴨  這是雞
It's not a duck. It's a chicken.

0:06:57.580,0:06:58.700
# 把刀磿鋒利一點
Let me sharpen the knife. Make it a bit sharper.

0:07:02.000,0:07:03.640
# 你看  這隻雞已經殺好啦
Look! This chicken is now ready.

0:07:04.260,0:07:05.980
# 又大又肥 你看
It's big and fat. Look!

0:07:07.780,0:07:09.700
# 它肉很結實哦  好重啊  這隻雞
Its meat is really firm. It's so heavy, this chicken.

0:07:10.320,0:07:11.400
# 我先把它砍碎先
Let me  chop it up first.

0:07:14.060,0:07:15.260
# 我把這雞
I'm gonna chop,

0:07:18.900,0:07:20.420
# 翅肪  先抇它砍下來
chop the chicken wings first.

0:07:21.300,0:07:22.280
# 要搞大塊一點
I'll chop it up in larger pieces.

0:07:26.560,0:07:27.340
# 隨便吃
Feel free to take it.

0:07:41.620,0:07:42.660
# 我都還沒吃
Don't try to eat before me!

0:07:46.300,0:07:47.300
# 雞屁股你們吃
The chicken butt is yours.

0:07:54.820,0:07:59.500
# 你看這個肉  它還會動的  一跳一跳  夠新鮮
Have a look at the meat! It's still moving, trembling. That means it's fresh.

0:08:01.320,0:08:02.660
# 拍點生薑下去
I smash some ginger.

0:08:05.180,0:08:08.780
# 放點生薑下去  再搞點香菇  這香菇要洗一下
Put some ginger, and also some shiitake mushrooms. The mushrooms need to be washed first.

0:08:20.420,0:08:23.260
# 這香菇洗好啦  直接倒進去
So the mushroom have been washed. I just pour them in right away.

0:08:25.640,0:08:27.240
# 再加點山泉水
Then put some spring water.

0:08:35.180,0:08:36.560
# 這個 多加點水
Well, a bit more water

0:08:37.580,0:08:38.560
# 湯就多一點
Then we can have more soup.

0:08:42.020,0:08:42.520
# 好啦
Alright!

0:08:59.140,0:09:00.540
# 哇  這個
Wa! This,

0:09:01.040,0:09:02.280
# 這個火夠猛
this fire is really strong.

0:09:05.740,0:09:07.160
# 這狗還戴了個眼鏡
This dog is wearing eyeglasses.

0:09:10.460,0:09:14.120
# 我去看一下那兩頭羊 剛剛下來啦  看到我它又跑
Let me go and have a look at the two goats. They have just come down. But they ran away once they saw me.

0:09:14.760,0:09:18.300
# 我搞又個樹叉  樹叉給它  給它吃
I'm taking a branch, a branch for them, to feed them.

0:09:23.440,0:09:24.420
# 跑哪裡去啦
Where are they?

0:09:32.760,0:09:33.800
# 你看這些羊
Have a look at these goats!

0:09:34.780,0:09:38.620
# 給它吃那樹上的嫩葉子哦  草它都不怎麼喜歡吃
I'm giving them the young leaves on the tree. They don't really like grass.

0:09:38.900,0:09:41.700
# 好多象草都  沒有利用起來
I have a lot of elephant grass here, but no use.

0:09:42.720,0:09:43.720
# 搞頭牛來
I'm gonna fetch a cow.

0:09:45.240,0:09:46.100
# 四大家禽
Four types of major livestock

0:09:46.520,0:09:50.040
# 四大家禽都齊啦  豬  雞鴨鵝牛羊
We'll then have all four types of major livestock, pigs, chickens, ducks, geese, cattle and goats.

0:09:51.820,0:09:52.740
# 還有兔子也有
And we have bunnies too.

0:09:54.100,0:09:55.440
# 好膽小現在這個羊
This goat is now a coward.

0:09:55.920,0:09:58.840
# 我把鏈子全部解掉啦  它們自由自在在這生活著
I've taken away all the leashes. So they can enjoy the free and worrieless life here.

0:10:00.340,0:10:01.460
# 很幸福哦它們
That's exactly what life should be.

0:10:06.240,0:10:07.580
# 每天都吃的飽飽的
They have more than enough to eat every day.

0:10:10.000,0:10:13.600
# 很多粉絲說這個羊  這毎羊像瓜子一樣
A lot of fans say that this goat, this goat looks like a pumpkin seed.

0:10:15.260,0:10:16.760
# 它頭羊頭是有點像哦
Yes, its head looks a bit like a pumpkin seed.

0:10:18.080,0:10:19.880
# 一白一黑的  瓜子臉
Black and white, pumpkin seed face.

0:10:21.040,0:10:22.460
# 瓜子臉就這樣子的
That's what pumpkin seed face means.

0:10:27.060,0:10:29.620
# 對我們愛理不理  它們吃它們的
They are completely indifferent to us. They eat their own food.

0:10:30.320,0:10:31.040
# 我們
And we,

0:10:32.300,0:10:33.480
# 我們拍我們的
we film our own video.

0:10:37.360,0:10:38.880
# 不知道甚麼時候能下小羊
I wonder when they are gonna give birth to babies.

0:10:41.860,0:10:43.720
# 你看  我一  我一站起來它們就走
Look! Once I, once I stand up, they run away immediately.

0:10:45.780,0:10:48.420
# 這就是你們的遊樂場  想去哪裡就去哪裡
This is your playground. You can go wherever you like.

0:10:57.200,0:10:58.760
# 來來來  這個好吃的
Come here, come here! This is tasty.

0:10:59.680,0:11:02.140
# 這個才好吃  我去看一下那個豬
This one tastes much better. I'm gonna have a look at the pig.

0:11:10.160,0:11:10.980
# 你看這隻豬
Have a look at the pig!

0:11:12.100,0:11:14.640
# 一動不動  吃也不吃喝也不喝的
It's like a statue. It's not eating, nor drinking.

0:11:19.500,0:11:22.120
# 它不來  不來拉倒
It's not coming. Forget it then.

0:11:23.420,0:11:27.240
# 它在那裡睡大覺吧  多睡幾天
Let it have a good sleep there, sleep for a few more days.

0:11:27.660,0:11:29.360
# 這個豬的鼻子
The nose of this pig,

0:11:30.060,0:11:31.700
# 好像小一點  又尖
seems to be a bit smaller, and pointed.

0:11:32.140,0:11:33.780
# 以前我那個是又圓
The noses of our previous pigs were, round and,

0:11:34.260,0:11:37.220
# 圓圓的 而且比較大
they were round, and, and were larger.

0:11:38.020,0:11:40.180
# 像那個山上的野豬一樣
It's like a wild boar in the mountain.

0:11:43.480,0:11:45.420
# 理一下我誒  理都不理我
Give me some response. Why aren't you giving me any response at all?

0:11:46.140,0:11:48.860
# 站起來  站起來給我看一下你的身材
Stand up! Stand up and show me your physique!

0:11:49.240,0:11:51.020
# 看你身材好不好  快點
Let me see if you have a good body.

0:11:52.280,0:11:54.240
# 這石頭  扔給你吃的
These are rocks. You can eat them.

0:11:54.540,0:11:56.980
# 我是叫你站起來  肚子那麼大
I ask you to stand up! You have such a big belly.

0:11:57.980,0:11:59.760
# 哎呀  石頭它也吃啊
Aya! It's really eating rocks.

0:12:01.140,0:12:02.720
# 很厲害哦  它那牙齒哦
They're so powerful, its teeth.

0:12:04.000,0:12:06.020
# 肚子那麼大  是不是懷孕了
You have such a big belly. Are you pregnant?

0:12:08.220,0:12:10.980
# 你是一頭公豬  而且還被閹了的
You're a boar. What's more, you're castrated.

0:12:13.920,0:12:17.340
# 可能閹  閹過之後那個肉比較好吃  所以就
Perhaps the texture of the pork from a cas, castrated pig is better. So I,

0:12:18.600,0:12:20.360
# 叫兄弟提前就把它閹了
I asked my buddy to have it castrated beforehand.

0:12:29.420,0:12:30.740
# 不理人的這隻豬
It's not giving any response, this pig.

0:12:31.600,0:12:32.980
# 可能比較陌生
Perhaps it's not familiar to this place.

0:12:33.860,0:12:34.620
# 過段時間來
A bit more time,

0:12:35.680,0:12:37.480
# 過段時間來它就不陌生了
it will more familiar to this place after a bit more time.

0:12:38.960,0:12:41.720
# 還有兩隻鴨一個鵝
There are still two ducks and one goose.

0:12:42.080,0:12:43.120
# 等著它們下蛋
I'm waiting for their eggs.

0:12:44.520,0:12:45.660
# 再不下蛋的話
And if they're still not laying eggs,

0:12:46.380,0:12:47.260
# 就把它宰了
I'll kill them.

0:12:49.920,0:12:52.180
# 天天在偷看我 那隻瓜子臉
It's peeping me every day, that pumpkin seed face.

0:12:52.880,0:12:54.280
# 一看到我來了就跑
It runs away once it sees me.

0:12:57.740,0:13:00.100
# 哎呀  好香啊  你看
Aya! It smells so good! Look!

0:13:01.140,0:13:04.660
# 湯都滿起來啦  現在要 小火 小火慢燉
It's now full of soup. Now low heat, cook it on low heat.

0:13:05.000,0:13:07.080
# 燉到吃飯的時候就可以直接吃了
Then we can eat it right away at meal time.

0:13:08.060,0:13:09.600
# 我先把其他菜先煮了先
Let me cook other dishes first.

0:13:12.160,0:13:13.080
# 留一點火給它
I leave a little bit fire here.

0:13:23.440,0:13:25.360
# 開吃開吃  我先吃一下
Meal time, meal time! Let me be the first one.

0:13:28.240,0:13:28.960
# 香
Nice!

0:13:32.080,0:13:33.080
# 你看這香菇
Have a look at the mushrooms here!

0:13:33.920,0:13:35.640
# 婀娜多姿的身材
It looks so flirtatious.

0:13:38.840,0:13:40.540
# 讓我找個雞朖來嘗一下
Let me find a chicken leg and have a try.

0:13:42.420,0:13:44.000
# 哇  這個雞眼夠大啦
Wa! This chicken leg is really big!

0:13:45.340,0:13:46.340
# 這個雞腿
This chicken leg,

0:13:47.360,0:13:48.720
# 看上去都有食慾
it looks so appetising.

0:13:51.840,0:13:54.760
# 要拿著吃  雞腿要食著吃才好吃
I gotta hold it by hands. That's the only correct way to enjoy a chicken leg.

0:13:55.580,0:13:56.340
# 有點
It's a bit,

0:13:57.340,0:13:58.100
# 有點燙
a bit hot.

0:14:04.920,0:14:06.320
# 看上去是不是很有食慾
Does it look appetising?

0:14:10.760,0:14:12.460
# 兄弟家的雞就是不一樣
Buddy's chicken always makes a difference.

0:14:15.860,0:14:18.720
# 養了差不多快一年啦  這隻雞
He has been raising it for almost a year, this chicken.

0:14:20.440,0:14:21.340
# 被我抓回來
And now I've caught it.

0:14:23.020,0:14:25.620
# 它這隻雞不是公的  也不是母的哦
This chicken is neither a rooster, nor a hen, you know,

0:14:25.700,0:14:26.500
# 是閹的
but a capon.

0:14:30.440,0:14:31.140
# 好燙
It's hot!

0:14:36.700,0:14:37.800
# 雞腿也那麼大
It's just a chicken leg and it's so big.

0:14:42.880,0:14:43.680
# 沒那麼快
Not so soon

0:14:47.260,0:14:49.820
# 去媽媽那裡去 去  不要拿出來
Go to your mother, go! Don't take it out!

0:14:50.420,0:14:50.920
# 去
Go!

0:14:52.120,0:14:53.340
# 你看  這香菇
Look! This mushroom...

0:14:58.820,0:15:00.480
# 好啦  今天的視頻到這裡啦
Alright! The video ends here.

0:15:01.060,0:15:03.900
# 等下叫他們一起過來吃  那麼大鍋
I'll ask them to come here and enjoy it together. It's such a big wok.
