### ISSUE TITLE
[手工耿] 鋼拖鞋 - https://youtu.be/MuxwDXgn5ko

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1418]
https://youtu.be/MuxwDXgn5ko
<p>&#35270;&#39057;&#21457;&#24067;&#20110; August 23, 2020 at 06:00PM</p>
<p>&#26631;&#39064;<br>
Steel Slippers! &#29399;&#29399;&#32317;&#26159;&#21676;&#22750;&#25302;&#38795;&#24590;&#40636;&#36774;? &#27833;&#32114;&#32361;&#20570;&#25104;&#30340; [&#37628;&#25302;&#38795;]&#65292;&#35731;&#20182;&#20497;&#29609;&#30340;&#30433;&#33288;!&#12304;&#25163;&#24037;&#32831;Handy Geng&#12305;</p>
<p>&#31616;&#20171;<br>
My dog likes to play with slippers, but the slippers will always be bitten, making the dog unhappy. So I specially created this special [steel slippers] for my dog, which is not only entertaining but also very practical. &#23478;&#35041;&#30340;&#29399;&#29399;&#24456;&#21916;&#27489;&#21644;&#25302;&#38795;&#29609;&#32781;&#65292;&#20294;&#26159;&#25302;&#38795;&#32317;&#26371;&#34987;&#21676;&#22750;&#65292;&#20351;&#24471;&#29399;&#29399;&#19981;&#30433;&#33288;&#12290; &#25152;&#20197;&#25105;&#29305;&#24847;&#28858;&#29399;&#29399;&#25171;&#36896;&#20102;&#36889;&#27454;&#29544;&#19968;&#28961;&#20108;&#30340;&#12304;&#37628;&#25302;&#38795;&#12305;&#65292;&#19981;&#20677;&#21487;&#20197;&#23067;&#27138;&#65292;&#36996;&#24456;&#23526;&#29992;&#12290; Thank you for your liking and subscribing! &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #&#37628;&#25302;&#38795; #SteelSlipper #&#33258;&#35069;&#25302;&#38795; #&#27231;&#22120;&#20154; #UselessEdison #&#32831;&#24101; #ChineseEdison #handicraft #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #&#20013;&#22283;&#30332;&#26126; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by BOWEN0305772** [comment]
认领

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

标题
Steel Slippers! 狗狗總是咬壞拖鞋怎麼辦? 油絲繩做成的 [鋼拖鞋]，讓他們玩的盡興!【手工耿Handy Geng】

家裡的狗狗很喜歡和拖鞋玩耍，但是拖鞋總會被咬壞，使得狗狗不盡興。
所以我特意為狗狗打造了這款獨一無二的【鋼拖鞋】，不僅可以娛樂，還很實用。
My dog likes to play with slippers, but the slippers will always be bitten, making the dog unhappy.
So I specially created this special [steel slippers] for my dog, which is not only entertaining but also very practical.

0:00:03.240,0:00:08.520
家里的狗狗很喜欢和我的拖鞋一起玩耍
my dog always likes to play with my slippers
0:00:16.180,0:00:18.420
但是普通的拖鞋质量有点差
but the quality of plastic slippers is not good enough
0:00:18.880,0:00:20.740
呐，玩着玩着就玩坏了，
well, the slippers are broken easily
0:00:21.600,0:00:22.860
不能够让它尽兴
the plastic slippers are not enough for my dog
0:00:22.860,0:00:26.000
所以我准备用油丝绳
so I want to prepare the wire ropes to make a pair of steel slippers
0:00:26.140,0:00:28.140
做一双“钢拖”
Let him play enough at one time
0:00:33.380,0:03:23.240
让他一次玩个够
(music)
0:03:23.580,0:03:25.580
音乐声
well, the pair of steel have been finished
0:03:26.100,0:03:28.100
呐，这双钢拖就算是完成啦
not only the pretty look but also the practical purpose
0:03:28.920,0:03:30.200
无论是从美观度还是从使用方面
which are so good
0:03:30.540,0:03:32.760
啊，我感觉都不错
now it is time to give them to my dog come here my doggy
0:03:34.100,0:03:35.700
接下来就看我们家狗狗喜不喜欢啦
come on
0:03:35.700,0:03:37.700
狗狗，狗狗狗，
look at the slipper for you
0:03:37.900,0:03:40.600
看给你做的拖鞋，不是喜欢咬拖鞋吗,来吃
dont you like to bite the slippers? Come to bite
0:03:40.940,0:03:42.940
特别好吃，吃啊
very good, bite them!
0:03:43.500,0:03:45.500
吃啊吃啊吃啊
come on
0:03:47.880,0:03:49.880
辜负了我一番好意
He betrayed my kindness
0:03:50.200,0:03:52.200
不喜欢吃
My doggy does not like it.
