### ISSUE TITLE
[雪鱼] 南昌豪气拌粉 - https://youtu.be/5wWVTjTaWac

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1430]
**视频链接**：https://youtu.be/5wWVTjTaWac

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
南昌豪气早餐拌粉，一桌摆20盆料任选，13元一碗重辣够味，顾客能排到门口

简介
在南昌，一碗重辣的拌粉，真的能够满足一天最初的期待。前几天我吃过3元的素拌粉，但是一次也吃不够呀，这次选择了牛肉拌粉，一碗13元，桌子上摆了那么多的料，有辣椒、花生、酸萝卜、雪里红、牛肉片、猪耳朵、猪肚等等，我早上7点到店，顾客们就已经开始排长队了。很多人选择打包带着去上班，年纪稍微大一点的顾客就会选择在店里慢慢享用。牛肉拌粉的颜色诱人，金黄的酱油色勾人食欲，牛肉很大片，青辣椒红辣椒白蒜末一样不少，挑一筷子送入口中，一吸溜就能感受到米粉的爽滑。不过需要提醒的是，米粉的辣味真的够足。
字幕
1
00:00:03,725 --> 00:00:05,400
在柳州吃过螺蛳粉

2
00:00:05,700 --> 00:00:07,150
在桂林吃过米粉

3
00:00:07,400 --> 00:00:10,900
今天我们来尝一尝南昌的米粉是什么样子

4
00:00:17,551 --> 00:00:18,526
江西 南昌

5
00:00:20,075 --> 00:00:22,575
哎呀 这队伍都堵到门口了

6
00:00:23,975 --> 00:00:25,225
站在队伍的最后

7
00:00:25,300 --> 00:00:26,800
正是考验视力的时候

8
00:00:27,125 --> 00:00:29,825
让我看看这的拌粉都有什么样子的

9
00:00:34,925 --> 00:00:38,025
这米粉可以和很多种肉拌一起

10
00:00:38,225 --> 00:00:42,425
像牛肉啊 猪肚 猪肝都是可以的

11
00:00:43,575 --> 00:00:46,250
也可以把几种肉混合一起拌

12
00:00:46,250 --> 00:00:47,575
价格会更高

13
00:00:52,350 --> 00:00:56,525
我要一个牛肉拌粉 就这些

14
00:01:07,275 --> 00:01:10,175
她们是5个人拿着五个盆拌粉 好壮观啊

15
00:01:12,950 --> 00:01:14,250
凉拌粉

16
00:01:14,250 --> 00:01:15,150
要香菜吗？

17
00:01:15,350 --> 00:01:16,600
要 所有的料都要

18
00:02:07,525 --> 00:02:11,625
南昌人都喜欢吃粉 早餐就是拌粉

19
00:02:11,625 --> 00:02:15,750
拌粉就是米粉加各种菜、调料

20
00:02:16,039 --> 00:02:19,364
我今天点的是13元的牛肉拌粉

21
00:02:20,075 --> 00:02:26,575
加了花生 萝卜这些配菜 上面铺满了牛肉

22
00:02:26,900 --> 00:02:29,325
看起来真的很不错

23
00:02:31,325 --> 00:02:33,875
这碗粉几乎是一半粉一半料

24
00:02:33,975 --> 00:02:35,475
看起来好好吃啊

25
00:02:36,225 --> 00:02:39,425
我发现除了牛肉 香菜比较多之外

26
00:02:39,425 --> 00:02:40,975
还有更多的辣椒

27
00:02:41,050 --> 00:02:42,175
江西人喜欢吃辣

28
00:02:42,300 --> 00:02:45,700
连早上最快捷的一餐也不会放过辣椒

29
00:02:45,900 --> 00:02:49,200
这么一闻都能闻着辣味

30
00:02:49,625 --> 00:02:54,600
这里有红辣椒 绿辣椒 还有蒜末

31
00:02:55,700 --> 00:02:58,075
这个米粉感觉很厚实

32
00:02:58,075 --> 00:03:00,975
用筷子一夹 感觉沉甸甸的

33
00:03:05,475 --> 00:03:08,025
看这大片的牛肉 我都等不及要吃了

34
00:03:20,200 --> 00:03:26,714
第一口是牛肉 蒜末 有点辣味 咸味略淡

35
00:03:26,925 --> 00:03:31,000
这个米粉一夹还感觉特别爽滑

36
00:03:34,900 --> 00:03:38,375
和大片牛肉一起吃 绝配啊

37
00:03:44,225 --> 00:03:46,575
吃起来好爽滑

38
00:03:48,375 --> 00:03:50,992
里面是不是加了香油啊 感觉好香啊

39
00:03:58,450 --> 00:04:04,272
这个牛肉是沾满了辣椒和蒜的 吃起来特别开胃

40
00:04:09,050 --> 00:04:16,025
辣椒是新鲜辣椒 辣度是直击灵魂的辣

41
00:04:21,675 --> 00:04:24,100
吃到最后 还有这么多的料啊

42
00:04:25,750 --> 00:04:28,850
感觉有把火往胃里烧（好辣）

43
00:04:29,100 --> 00:04:31,700
真想对着空调吹吹嘴

44
00:04:32,000 --> 00:04:34,800
我去年11月份时候来过南昌一次

45
00:04:35,125 --> 00:04:40,600
在这边吃了三顿饭 感觉承受不了这样的辣度

46
00:04:40,900 --> 00:04:42,725
结果呢就是视频也没有发

47
00:04:42,850 --> 00:04:46,925
今年呢再来一次南昌挑战一下日常吃饭的辣度

48
00:05:11,525 --> 00:05:14,250
这是打包带走的

49
00:05:19,650 --> 00:05:23,125
这个是自己带保温饭盒来的

50
00:05:33,950 --> 00:05:35,900
辣椒香菜要吗

51
00:05:36,800 --> 00:05:39,075
一碗要一碗不要

52
00:06:31,950 --> 00:06:34,250
看很多本地人来吃拌粉的时候

53
00:06:34,350 --> 00:06:35,800
都会要一碗猪肝鸡蛋汤

54
00:06:35,975 --> 00:06:38,250
像我的饭量 吃一碗米粉就饱了

55
00:06:40,975 --> 00:06:42,325
吃完感觉好辣啊

56
00:06:42,500 --> 00:06:45,200
唯一不好的地方是里面加了蒜

57
00:06:46,350 --> 00:06:48,325
这大早上的啊


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
南昌豪气早餐拌粉，一桌摆20盆料任选，13元一碗重辣够味，顾客能排到门口

简介
在南昌，一碗重辣的拌粉，真的能够满足一天最初的期待。前几天我吃过3元的素拌粉，但是一次也吃不够呀，这次选择了牛肉拌粉，一碗13元，桌子上摆了那么多的料，有辣椒、花生、酸萝卜、雪里红、牛肉片、猪耳朵、猪肚等等，我早上7点到店，顾客们就已经开始排长队了。很多人选择打包带着去上班，年纪稍微大一点的顾客就会选择在店里慢慢享用。牛肉拌粉的颜色诱人，金黄的酱油色勾人食欲，牛肉很大片，青辣椒红辣椒白蒜末一样不少，挑一筷子送入口中，一吸溜就能感受到米粉的爽滑。不过需要提醒的是，米粉的辣味真的够足。
字幕
1
00:00:03,725 --> 00:00:05,400
在柳州吃过螺蛳粉
I have eaten snail noodle in Liuzhou
2
00:00:05,700 --> 00:00:07,150
在桂林吃过米粉
And rice noodle in Guilin
3
00:00:07,400 --> 00:00:10,900
今天我们来尝一尝南昌的米粉是什么样子
Let’s try rice noodle in Nanchang
4
00:00:17,551 --> 00:00:18,526
江西 南昌
Nanchang, Jiangxi
5
00:00:20,075 --> 00:00:22,575
哎呀 这队伍都堵到门口了
Aiya, customers are lining up to the door 
6
00:00:23,975 --> 00:00:25,225
站在队伍的最后
Sit on the end of the line
7
00:00:25,300 --> 00:00:26,800
正是考验视力的时候
It's time to test eyesight
8
00:00:27,125 --> 00:00:29,825
让我看看这的拌粉都有什么样子的
let me take a look at the Banfen
9
00:00:34,925 --> 00:00:38,025
这米粉可以和很多种肉拌一起
Rice noodle can be mixed with a lot of types of meat
10
00:00:38,225 --> 00:00:42,425
像牛肉啊 猪肚 猪肝都是可以的
Like beef or pork belly, and pork liver
11
00:00:43,575 --> 00:00:46,250
也可以把几种肉混合一起拌
Or mixed them together 
12
00:00:46,250 --> 00:00:47,575
价格会更高
It will be more expensive 
13
00:00:52,350 --> 00:00:56,525
我要一个牛肉拌粉 就这些
I want a beef Banfen, that’s all
14
00:01:07,275 --> 00:01:10,175
她们是5个人拿着五个盆拌粉 好壮观啊
Five people are mixing five pots at same time
15
00:01:12,950 --> 00:01:14,250
凉拌粉
Cold mixed rice noodle
16
00:01:14,250 --> 00:01:15,150
要香菜吗？
Add cilantro?
17
00:01:15,350 --> 00:01:16,600
要 所有的料都要
Yeah, all of the ingredients 
18
00:02:07,525 --> 00:02:11,625
南昌人都喜欢吃粉 早餐就是拌粉
Nanchang people love to eat rice noodle so much even eat it as breakfast
19
00:02:11,625 --> 00:02:15,750
拌粉就是米粉加各种菜、调料
Mixed rice noodle is mix rice noodle with different dishes and seasonings
20
00:02:16,039 --> 00:02:19,364
我今天点的是13元的牛肉拌粉
I ordered 13 yuan beef mixed rice noodle
21
00:02:20,075 --> 00:02:26,575
加了花生 萝卜这些配菜 上面铺满了牛肉
With toppings like pickled peanut and radish, and beef on it
22
00:02:26,900 --> 00:02:29,325
看起来真的很不错
Looks pretty good
23
00:02:31,325 --> 00:02:33,875
这碗粉几乎是一半粉一半料
Almost half of ingredients and half of rice noodle in a bowl
24
00:02:33,975 --> 00:02:35,475
看起来好好吃啊
Looks so delicious 
25
00:02:36,225 --> 00:02:39,425
我发现除了牛肉 香菜比较多之外
I found out that 
26
00:02:39,425 --> 00:02:40,975
还有更多的辣椒
And more red pepper
27
00:02:41,050 --> 00:02:42,175
江西人喜欢吃辣
Jiangxi people like spicy food
28
00:02:42,300 --> 00:02:45,700
连早上最快捷的一餐也不会放过辣椒
Even eat it in the fastest meal in a day, which is breakfast
29
00:02:45,900 --> 00:02:49,200
这么一闻都能闻着辣味
I can smell spicy now
30
00:02:49,625 --> 00:02:54,600
这里有红辣椒 绿辣椒 还有蒜末
There is red pepper, green pepper and minced garlic
31
00:02:55,700 --> 00:02:58,075
这个米粉感觉很厚实
This rice noodle looks pretty thick
32
00:02:58,075 --> 00:03:00,975
用筷子一夹 感觉沉甸甸的
It feels heavy to use chopstick to narrow it
33
00:03:05,475 --> 00:03:08,025
看这大片的牛肉 我都等不及要吃了
I can’t wait to eat in front of huge slices of beef
34
00:03:20,200 --> 00:03:26,714
第一口是牛肉 蒜末 有点辣味 咸味略淡
The first bite with beef, minced garlic, a little bit spicy and light salty
35
00:03:26,925 --> 00:03:31,000
这个米粉一夹还感觉特别爽滑
This rice noodle feels very tender and smoothy 
36
00:03:34,900 --> 00:03:38,375
和大片牛肉一起吃 绝配啊
It’s a great combo to eat with beef
37
00:03:44,225 --> 00:03:46,575
吃起来好爽滑
Very tender and smoothy 
38
00:03:48,375 --> 00:03:50,992
里面是不是加了香油啊 感觉好香啊
Does it add sesame oil? Smells so fragment
39
00:03:58,450 --> 00:04:04,272
这个牛肉是沾满了辣椒和蒜的 吃起来特别开胃
This beef is soaked in chili and minced garlic. It tastes very appetizing.
40
00:04:09,050 --> 00:04:16,025
辣椒是新鲜辣椒 辣度是直击灵魂的辣
Fresh red pepper is pretty spicy
41
00:04:21,675 --> 00:04:24,100
吃到最后 还有这么多的料啊
The are a lot of ingredients left at the end
42
00:04:25,750 --> 00:04:28,850
感觉有把火往胃里烧（好辣）
My stomach are burning(so spicy)
43
00:04:29,100 --> 00:04:31,700
真想对着空调吹吹嘴
I want use air conditioning to blow my mouth
44
00:04:32,000 --> 00:04:34,800
我去年11月份时候来过南昌一次
I visited Nanchang once in November last year 
45
00:04:35,125 --> 00:04:40,600
在这边吃了三顿饭 感觉承受不了这样的辣度
And ate 3 meals, all too spicy for me 
46
00:04:40,900 --> 00:04:42,725
结果呢就是视频也没有发
And i didn’t post any videos about it
47
00:04:42,850 --> 00:04:46,925
今年呢再来一次南昌挑战一下日常吃饭的辣度
I want to challenge it again this year
48
00:05:11,525 --> 00:05:14,250
这是打包带走的
This is for take out
49
00:05:19,650 --> 00:05:23,125
这个是自己带保温饭盒来的
This is bring his own Thermal lunch box
50
00:05:33,950 --> 00:05:35,900
辣椒香菜要吗
Add red pepper and 
51
00:05:36,800 --> 00:05:39,075
一碗要一碗不要
Red pepper and cilantro for one bowl
52
00:06:31,950 --> 00:06:34,250
看很多本地人来吃拌粉的时候
Local people come to eat mixed rice noodle
53
00:06:34,350 --> 00:06:35,800
都会要一碗猪肝鸡蛋汤
With pork liver and egg soup
54
00:06:35,975 --> 00:06:38,250
像我的饭量 吃一碗米粉就饱了
I will get full with one bowl of rice noodle
55
00:06:40,975 --> 00:06:42,325
吃完感觉好辣啊
So spicy
56
00:06:42,500 --> 00:06:45,200
唯一不好的地方是里面加了蒜
The only bad part is that it adds garlic
57
00:06:46,350 --> 00:06:48,325
这大早上的啊
What a morning!
