### ISSUE TITLE
【美食作家王刚】开胃青椒 - https://youtu.be/EPYYnC0OLlE

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#148]
【美食作家王刚】开胃青椒 - https://youtu.be/EPYYnC0OLlE
这是刚哥最新的视频私享链接，方便大家提前添加字幕，做菜过程文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。然后就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间9月7日晚6点

首先我们准备适量的二荆条去掉辣椒蒂之后备用（约1000克）
二荆条在四川是比较常见的一种辣椒
且辣度微辣比较香
湖南椒和四川二荆条外形酷似但只辣不香
然后准备适量的小米辣去蒂备用
小米辣的味道比较冲不能吃辣的同学请慎重
原料准备好之后盆中加入适量的清水清洗干净
因为是直接浸泡食用所以同学们最好多清洗几遍
辣椒清洗干净之后捞出沥干水份备用
此菜从这里开始全程都不能再沾生水否则容易拉肚子
然后将辣椒斜刀切成小段备用
同学们也可以带上手套用手撕成小条腌制
再将小米辣对半切开备用
吃不了辣的同学可以换成大红椒或者甜椒
准备适量的大蒜切成蒜片备用
加入大蒜之后会有一股特殊的香味
不喜欢大蒜的同学可以将其换成仔姜
刀工不好的同学也可以对半切开
大蒜切好之后放入盆中
下一步开始制作
首先我们在盆中加入适量的食用盐
同学们盐的量可以稍微多一些这样才够味
再加入适量的白糖
白糖和盐的比例是1.5比1
然后将辣椒抓拌均匀腌制60分钟备用
这60分钟辣椒和盐糖会发生一些反应
腌制辣椒出的水会有一些粘稠
属于正常现象同学们不必担心
辣椒腌制60分钟之后放入坛中
只要是可以密封的容器也可以
同学们也可以放入盆中直接用保鲜膜封口
最后把剩下的辣椒水一起倒入
下一步开始制作料汁
首先我们在锅中加入清水300克
加入适量的鲜花椒
没有鲜花椒的同学也可以用青花椒代替
加入白醋200克
加入生抽酱油300克
然后开大火烧开
这一步的目的是样料汁融合煮出花椒的香味
大火烧开之后再关火冷却备用
料汁冷却之后再倒入容器里面
最后盖上盖子将辣椒腌制3天左右
中途需要将辣椒翻一翻方便入味
一道开胃青椒就制作完成
下面开始技术总结
第一，辣椒的辣度需要根据个人口味来，
第二，糖的比例要比盐多一些，这样是为了中和辣味而非增加甜味
第三，料汁的比例为清水1.5，酱油1.5，白醋1.0再加上适量的花椒
第四，青椒做好之后的第二天和第三天都需要翻动一下方便入味
开胃青椒的技术总结完毕

**Comment by kdliu86** [comment]
偶素素

**Comment by kdliu86** [comment]
#151
