### ISSUE TITLE
【美食作家王刚】糖醋排骨的创新做法 - https://youtu.be/6RzyOsnzQ3o

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#149]
【美食作家王刚】糖醋排骨的创新做法 - https://youtu.be/6RzyOsnzQ3o
这是刚哥最新的视频私享链接，方便大家提前添加字幕，做菜过程文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。然后就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间9月8日晚6点

 首先我们准备一板精瘦型的排骨
将排骨每根分开之后剁成大小均匀的块备用
最好选择肉少的排骨
因为这道菜吃的是味道而不是肉
下一步我们开始准备辅料
准备生姜1小块切成姜片备用
准备柠檬1个横切成片备用
加柠檬的目的是让酸度更纯
然后我们把柠檬中的籽去掉
同学们柠檬籽会让菜品发苦所以必须去掉
准备适量的干山楂备用
加山楂的目的是增加香甜解除排骨的腻味
准备大葱2根切成段备用
最后准备适量的冰糖敲散备用
敲散的冰糖是用于糖色的炒制
下一步我们开始制作
首先我们在锅中加入适量的清水
然后将准备好的排骨下锅焯水10分钟
中途加入适量的料酒去腥
水开之后撇去浮沫
焯水10分钟的目的是让排骨肉质松散脱骨
喜欢有嚼劲的同学只需焯水6分钟即可
10分钟之后将排骨倒出备用
然后我们再次把锅烧热
锅烧热之后加入宽油
油温烧至6成热之后将排骨下锅炸香炸至略黄
这一步的目的是将排骨表面的肉收紧炸香
排骨炸好之后倒出控油备用
下一步开始炒糖色
将准备好的冰糖下锅
然后加入少许的清水将冰糖炒化
冰糖变糖色的过程就是糖化，焦变
后续会跟大家分享糖色的全过程
当糖浆接近咖啡色的时候锅离火
继续用铁锅的余温将其炒至想要的颜色
再加入顺便好的开水下锅把糖色于水融合
然后将炸好的排骨下锅
加入切好的姜片
加入切好的柠檬和山楂
翻炒之后再加入适量的清水将排骨烧20分钟
中途加入适量的冰糖
冰糖的量可以根据个人口味调节
锅中加入5克保宁醋增加酸味
同学们醋可以少加一些
因为柠檬的酸味也在其中
不能让醋和柠檬抢味
烧至10分钟的时候加入少许的食用盐调味
同学们糖醋味的菜肴加盐并不能调咸味
而是通过食用盐让糖醋的味道更加醇厚
再加入切好的大葱段下锅
当烧至20分钟后将大葱和柠檬捡出不用
然后继续小火收汁3分钟把汤汁收浓
汤汁浓稠之后翻炒几下即可出锅装盘
一道酸甜可口的糖醋排骨就制作完成
下面开始技术总结
第一，原料可以选择猪排羊排或者牛排骨
第二，此菜加入柠檬和山楂后味道更加醇厚
第三，牙口不好的同学可以增加焯水的时间
第四，收汁的时候必须小火否则汤汁容易烧焦变黑
糖醋排骨的技术总结完毕

**Comment by kdliu86** [comment]
贼好的, 拿来偶看看
