### ISSUE TITLE
[手工耿] 螺母加特林 - https://youtu.be/Wwid7aVB_cs

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1497]
https://youtu.be/Wwid7aVB_cs
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 19, 2020 at 08:30PM</p>
<p>&#26631;&#39064;<br>
Gatling Gun &#29992;&#19978;&#21315;&#20491;&#34746;&#27597;&#35069;&#20316;&#21152;&#29305;&#26519;&#27231;&#27085;&#65292;&#23041;&#21147;&#36229;&#24375;!&#12304;&#25163;&#24037;&#32831;Handy Geng&#12305;</p>
<p>&#31616;&#20171;<br>
&#20170;&#22825;&#38289;&#20358;&#28961;&#20107;&#29992;&#25105;&#30340;&#33836;&#33021;&#34746;&#27597;&#35069;&#20316;&#20102;&#21152;&#29305;&#26519;&#27231;&#27085;&#65292; &#26377;&#25163;&#25345;/&#22352;&#24335;/&#36650;&#24335;&#30340;&#65292;&#20320;&#26356;&#21916;&#27489;&#21738;&#19968;&#27454;&#65311; Thank you for your liking and subscribing! &mdash;&mdash; &#21029;&#20154;&#31505;&#25105;&#22826;&#30219;&#30322;&#65292;&#31505;&#23436;&#30219;&#30322;&#31505;&#25105;&#38289;&#12290; &#22823;&#23478;&#22909;&#65292;&#25105;&#26159;&#25163;&#24037;&#32831;&#65292;&#22914;&#26524;&#20320;&#21916;&#27489;&#25105;&#30340;&#35222;&#38971;&#65292;&#27489;&#36814;&#40670;&#25802;&#35330;&#38321;&#12290; #&#25163;&#24037;&#32831; #&#21152;&#29305;&#26519; #&#26426;&#26538; #&#33258;&#21046;&#21152;&#29305;&#26519; #&#27231;&#22120;&#20154; #UselessEdison #&#32831;&#24101; #ChineseEdison #handicraft #&#25163;&#24037; #&#30828;&#26680; #&#33258;&#35069;&#27231;&#22120;&#20154; #&#20013;&#22283;&#30332;&#26126; #&#24290;&#26612;&#24859;&#36842;&#29983; #&#25630;&#31505;&#30332;&#26126;</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/113772413d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by sophiascf** [comment]
认领

**Comment by sophiascf** [comment]
# 标题
# Gatling Gun 用上千個螺母製作加特林機槍，威力超強!【手工耿Handy Geng】
# Thousands nuts to make a powerful Gatling Gun [Handy Geng]

# 简介
# Introduction

# 今天閑來無事用我的萬能螺母製作了加特林機槍，
# Today, I used my all-purpose nuts to make a Gatling Gun.
# 有手持/坐式/輪式的，你更喜歡哪一款？
# It has hand held/sitting/wheeled three types, which one is your favourite?

# Thank you for your liking and subscribing!
# —— 別人笑我太瘋癲，笑完瘋癲笑我閑。
# 大家好，我是手工耿，如果你喜歡我的視頻，歡迎點擊訂閱。

+
0:00.0
 
0:03.0
Gatling Gun
0:13.1
 
0:14.8
After welding, bend while it's hot.
3:42.4
 
3:43.8
Do you feel the wheels are too big?
3:44.2
 
3:45.2
Actually they are from Second Battalion Commander.
3:45.5
 
3:46.4
They are only temporary cameos.
3:48.4
 
3:50.0
Welcome to subscribe this channel, I will keep updating.
5:07.6
 
5:10.1
Thank you for watching, welcome to subscribe my channel.     - Handy Geng

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

# 标题
# Gatling Gun 用上千個螺母製作加特林機槍，威力超強!【手工耿Handy Geng】
# Thousands nuts to make a powerful Gatling Gun [Handy Geng]

# 简介

# 今天閑來無事用我的萬能螺母製作了加特林機槍，
# Today, I used my all-purpose nuts to make a Gatling Gun.
# 有手持/坐式/輪式的，你更喜歡哪一款？
# It has hand held/sitting/wheeled three types, which one is your favourite?

# import intro

0:0:00.000,0:0:03.000
加特林
Gatling Gun

0:0:13.100,0:0:14.800
焊接完后趁热掰弯
After welding, bend while it's hot.

0:3:42.400,0:3:43.800
觉不觉得轱辘有点大？
Do you feel the wheels are too big?

0:3:44.200,0:3:45.200
其实这是二营长的货
Actually they are from Second Battalion Commander.

0:3:45.500,0:3:46.400
老王只是临时客串
They are only temporary cameos.

0:3:48.400,0:3:50.000
喜欢关注一下以后会持续更新
Welcome to subscribe this channel, I will keep updating.

0:5:07.600,0:5:10.100
感谢收看 欢迎订阅 —— 手工耿
Thank you for watching, welcome to subscribe my channel.
- Handy Geng
