### ISSUE TITLE
[雪鱼] 青岛海鲜 - https://youtu.be/l5zdPDgmO1Q

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#1504]
**视频链接**：https://youtu.be/l5zdPDgmO1Q

# 请翻译以下全部内容

```


字幕
1
00:00:02,300 --> 00:00:03,740
山东 青岛

2
00:00:11,780 --> 00:00:13,860
哈哈 到码头了

3
00:00:21,355 --> 00:00:22,505
快点啊

4
00:00:25,660 --> 00:00:28,320
沙子口码头

5
00:00:28,320 --> 00:00:28,820
 

6
00:00:29,695 --> 00:00:30,695
 

7
00:00:36,500 --> 00:00:37,500
 

8
00:00:47,940 --> 00:00:50,920
一箱箱的鱼都是从船舱里搬上来的

9
00:00:50,920 --> 00:00:51,960
还带着冰块

10
00:00:55,000 --> 00:00:58,120
这艘船上米鱼、带鱼、鲳鱼比较多

11
00:00:59,620 --> 00:01:03,060
都不是零卖的 要买需要买一筐是吗 对的

12
00:01:07,940 --> 00:01:10,720
你分辨鱼是否新鲜就看鱼的眼睛

13
00:01:13,400 --> 00:01:16,120
鱼的眼睛发黄了 就不好了

14
00:01:16,300 --> 00:01:17,440
35斤 一共122元

15
00:01:19,180 --> 00:01:20,180
没有8块钱给你找

16
00:01:20,535 --> 00:01:21,535
120元算了

17
00:01:22,585 --> 00:01:23,585
好的 谢谢您

18
00:01:23,955 --> 00:01:24,975
 

19
00:01:31,225 --> 00:01:32,225
完了

20
00:01:34,480 --> 00:01:38,540
完了 想天真了  他们这边都是一筐筐的卖

21
00:01:38,600 --> 00:01:39,600
不零卖的

22
00:01:40,180 --> 00:01:42,420
我刚才还得到一个消息

23
00:01:42,540 --> 00:01:44,660
这艘船上来的都是鱼

24
00:01:44,760 --> 00:01:47,260
如果想吃梭子蟹 就得需要去别的码头了

25
00:01:48,040 --> 00:01:49,040
小港码头

26
00:01:52,840 --> 00:01:53,980
 

27
00:02:02,100 --> 00:02:03,120
看了一会 也没发现合适的

28
00:02:04,020 --> 00:02:06,880
看来还得去农贸市场买

29
00:02:12,460 --> 00:02:13,720
这个蟹 多少钱一斤

30
00:02:14,120 --> 00:02:15,120
这个35元一斤

31
00:02:17,340 --> 00:02:20,660
这个大的90元一斤 是本地蟹

32
00:02:21,920 --> 00:02:23,920
本地蟹壳发绿

33
00:02:25,860 --> 00:02:28,420
南方蟹发黑发黄

34
00:02:30,020 --> 00:02:32,700
您帮我挑一个比较好的吧

35
00:02:34,720 --> 00:02:38,000
最大的能有1斤是吧

36
00:02:39,720 --> 00:02:41,060
怎么看蟹肥不肥啊

37
00:02:44,760 --> 00:02:48,680
你看这个位置 延伸到顶端了 比较丰满

38
00:02:51,040 --> 00:02:52,540
 

39
00:02:55,880 --> 00:02:58,660
不肥的蟹 这个位置比较空

40
00:03:06,580 --> 00:03:08,280
就拿这个比较肥的

41
00:03:20,820 --> 00:03:22,640
一共60元   一共7两重

42
00:03:31,020 --> 00:03:32,020
 

43
00:03:36,060 --> 00:03:38,960
这个虾是体格不同 价格不同吗

44
00:03:40,360 --> 00:03:41,360
这种小的40元一斤

45
00:03:41,800 --> 00:03:43,300
 

46
00:03:43,400 --> 00:03:45,000
这种大的150元一斤

47
00:03:45,120 --> 00:03:46,520
那这个太贵了

48
00:03:48,500 --> 00:03:51,380
 

49
00:03:51,380 --> 00:03:52,620
 

50
00:03:53,040 --> 00:03:55,220
这一份90元2斤

51
00:03:56,000 --> 00:03:57,300
 

52
00:03:58,980 --> 00:04:00,300
您给我拿4个吧

53
00:04:01,280 --> 00:04:03,100
 

54
00:04:05,295 --> 00:04:06,395
 

55
00:04:08,920 --> 00:04:10,920
海捕虾45元一斤 4个虾16元

56
00:04:14,900 --> 00:04:16,900
生蚝5元一斤 20个13元

57
00:04:17,100 --> 00:04:18,100
 

58
00:04:18,320 --> 00:04:19,800
扇贝5元一斤 10几个5元

59
00:04:24,760 --> 00:04:27,720
这个农贸市场是我见过最干净的了

60
00:04:30,680 --> 00:04:35,920
地上几乎看不到菜叶 水渍

61
00:04:36,460 --> 00:04:39,500
除了干净以外 这边还有很多监控

62
00:04:39,500 --> 00:04:42,340
 

63
00:04:42,340 --> 00:04:44,595
 

64
00:04:44,600 --> 00:04:47,360
有海鲜交易纠纷 就可以查看录像

65
00:04:47,880 --> 00:04:51,060
去前面走一下 看看有没有加工海鲜的地方

66
00:04:51,080 --> 00:04:53,520
 

67
00:04:54,635 --> 00:04:57,655
 

68
00:04:58,220 --> 00:04:59,280
 

69
00:05:01,580 --> 00:05:06,700
不管几个螃蟹都是一锅一蒸  一锅15元

70
00:05:06,700 --> 00:05:08,540
这一大袋15元

71
00:05:15,160 --> 00:05:20,600
现在海鲜已经入锅了 等15分钟就可以吃了

72
00:05:27,040 --> 00:05:31,280
像扇贝 生蚝 它的肉直接从壳里掉出来了

73
00:05:33,740 --> 00:05:34,860
先尝一个

74
00:05:35,960 --> 00:05:38,680
真的很鲜甜的感觉

75
00:05:40,940 --> 00:05:42,960
不蘸姜醋汁也挺好吃的

76
00:05:47,980 --> 00:05:49,880
 

77
00:05:54,780 --> 00:05:56,080
这个汁水多

78
00:06:01,420 --> 00:06:06,160
在青岛有种豪气叫做把海鲜当饭吃

79
00:06:10,020 --> 00:06:14,460
这么一盘 原材料才18元

80
00:06:24,060 --> 00:06:27,760
现在螃蟹也上桌了  这个蟹是60块钱

81
00:06:27,760 --> 00:06:29,720
足足有7两重

82
00:06:31,360 --> 00:06:35,220
蒸熟的螃蟹红彤彤的 颜值很高

83
00:06:36,140 --> 00:06:39,180
这蟹腿挺粗的

84
00:06:40,220 --> 00:06:42,900
先吃这个腿吧

85
00:06:49,240 --> 00:06:52,900
吃一口就是鲜甜的味道

86
00:06:53,820 --> 00:06:54,820
再来一个

87
00:06:55,120 --> 00:06:57,660
 

88
00:06:58,720 --> 00:06:59,720
 

89
00:07:03,080 --> 00:07:04,560
蟹肉很厚实

90
00:07:05,220 --> 00:07:06,220
 

91
00:07:08,365 --> 00:07:09,365
 

92
00:07:13,595 --> 00:07:15,045
 

93
00:07:17,245 --> 00:07:18,245
 

94
00:07:19,855 --> 00:07:21,075
 

95
00:07:26,955 --> 00:07:27,955
 

96
00:07:28,885 --> 00:07:29,985
 

97
00:07:33,375 --> 00:07:34,375
 


```

**Comment by shuaisoserious** [comment]
认领

**Comment by shuaisoserious** [comment]
字幕
1
00:00:02,300 --> 00:00:03,740
山东 青岛
Qingdao, Shandong
2
00:00:11,780 --> 00:00:13,860
哈哈 到码头了
Haha, we arrived at the pier
3
00:00:21,355 --> 00:00:22,505
快点啊
Hurry up
4
00:00:25,660 --> 00:00:28,320
沙子口码头
Shazikou pier
5
00:00:28,320 --> 00:00:28,820
 

6
00:00:29,695 --> 00:00:30,695
 

7
00:00:36,500 --> 00:00:37,500
 

8
00:00:47,940 --> 00:00:50,920
一箱箱的鱼都是从船舱里搬上来的
Boxes of fish are brought up from the cabin
9
00:00:50,920 --> 00:00:51,960
还带着冰块
With covered ice cubes
10
00:00:55,000 --> 00:00:58,120
这艘船上米鱼、带鱼、鲳鱼比较多
Brown coaker, beltfish, and pomfret mostly on this boat
11
00:00:59,620 --> 00:01:03,060
都不是零卖的 要买需要买一筐是吗 对的
It’s not sold individually. And You need to buy a whole basket at least right? yeah
12
00:01:07,940 --> 00:01:10,720
你分辨鱼是否新鲜就看鱼的眼睛
You can tell if the fish is fresh by looking at the eyes of fish
13
00:01:13,400 --> 00:01:16,120
鱼的眼睛发黄了 就不好了
It means not fresh if the eyes of fish are yellow
14
00:01:16,300 --> 00:01:17,440
35斤 一共122元
35 jin(17.5 kg), 122 yuan total
15
00:01:19,180 --> 00:01:20,180
没有8块钱给你找
I don’t have change for u
16
00:01:20,535 --> 00:01:21,535
120元算了
How about 120 yuan?
17
00:01:22,585 --> 00:01:23,585
好的 谢谢您
Fine, thank you
18
00:01:23,955 --> 00:01:24,975
 

19
00:01:31,225 --> 00:01:32,225
完了
Oh no
20
00:01:34,480 --> 00:01:38,540
完了 想天真了  他们这边都是一筐筐的卖
I don’t know that they  sell in basket only
21
00:01:38,600 --> 00:01:39,600
不零卖的
Not for sale individually 
22
00:01:40,180 --> 00:01:42,420
我刚才还得到一个消息
I just got a message
23
00:01:42,540 --> 00:01:44,660
这艘船上来的都是鱼
This boat is full of fish
24
00:01:44,760 --> 00:01:47,260
如果想吃梭子蟹 就得需要去别的码头了
If you want to eat portunus, you have to go to another pier
25
00:01:48,040 --> 00:01:49,040
小港码头
Small port pier
26
00:01:52,840 --> 00:01:53,980
 

27
00:02:02,100 --> 00:02:03,120
看了一会 也没发现合适的
After looking for a while, I didn’t find any good portunus
28
00:02:04,020 --> 00:02:06,880
看来还得去农贸市场买
We should buy it at agricultural market
29
00:02:12,460 --> 00:02:13,720
这个蟹 多少钱一斤
How much is this crab per jin(0.5kg)?
30
00:02:14,120 --> 00:02:15,120
这个35元一斤
35 yuan per jin(70yuan per kg)
31
00:02:17,340 --> 00:02:20,660
这个大的90元一斤 是本地蟹
The big one is 90 per jin( about 180 yuan per kg) which is local crab
32
00:02:21,920 --> 00:02:23,920
本地蟹壳发绿
Local crab shells is green
33
00:02:25,860 --> 00:02:28,420
南方蟹发黑发黄
Southern crab shells is black and yellow
34
00:02:30,020 --> 00:02:32,700
您帮我挑一个比较好的吧
Can you help me choose a better crab?
35
00:02:34,720 --> 00:02:38,000
最大的能有1斤是吧
The biggest crab is about 1 jin(kg), right?
36
00:02:39,720 --> 00:02:41,060
怎么看蟹肥不肥啊
How to know if the crab is fatty or not?
37
00:02:44,760 --> 00:02:48,680
你看这个位置 延伸到顶端了 比较丰满
Check this out, it extend to the top, More plump
38
00:02:51,040 --> 00:02:52,540
 

39
00:02:55,880 --> 00:02:58,660
不肥的蟹 这个位置比较空
There is empty if that's not a fatty crab
40
00:03:06,580 --> 00:03:08,280
就拿这个比较肥的
I want the fatty crab
41
00:03:20,820 --> 00:03:22,640
一共60元   一共7两重
60 yuan total, about 7 liang (350g)
42
00:03:31,020 --> 00:03:32,020
 

43
00:03:36,060 --> 00:03:38,960
这个虾是体格不同 价格不同吗
Do those shrimp have different prices depending on it’s own size?
44
00:03:40,360 --> 00:03:41,360
这种小的40元一斤
This type of small shrimp is about 40 yuan per jin(80 yuan per kg) 
45
00:03:41,800 --> 00:03:43,300
 

46
00:03:43,400 --> 00:03:45,000
这种大的150元一斤
This type of big shrimp is about 150 yuan per jin(300 yuan per kg)
47
00:03:45,120 --> 00:03:46,520
那这个太贵了
That’s too expensive
48
00:03:48,500 --> 00:03:51,380
 

49
00:03:51,380 --> 00:03:52,620
 

50
00:03:53,040 --> 00:03:55,220
这一份90元2斤
This one is 90 yuan/2 jin( about 90 yuan per kg) 
51
00:03:56,000 --> 00:03:57,300
 

52
00:03:58,980 --> 00:04:00,300
您给我拿4个吧
May you pls get me 4 shrimps?
53
00:04:01,280 --> 00:04:03,100
 

54
00:04:05,295 --> 00:04:06,395
 

55
00:04:08,920 --> 00:04:10,920
海捕虾45元一斤 4个虾16元
Sea-caught shrimp 45 yuan per jin(90 yuan per kg), and 4 shrimps is 16 yuan
56
00:04:14,900 --> 00:04:16,900
生蚝5元一斤 20个13元
Oyster 5 yuan per jin(10 yuan per kg), or 20 oysters for 13 yuan
57
00:04:17,100 --> 00:04:18,100
 

58
00:04:18,320 --> 00:04:19,800
扇贝5元一斤 10几个5元
Scallop is 5 yuan per jin(10 yuan per kg)or about ten scallops for 5 yuan
59
00:04:24,760 --> 00:04:27,720
这个农贸市场是我见过最干净的了
This agricultural market is the cleanest i’ve even seen 
60
00:04:30,680 --> 00:04:35,920
地上几乎看不到菜叶 水渍
There just very few vegetable leaves or water stain on the ground
61
00:04:36,460 --> 00:04:39,500
除了干净以外 这边还有很多监控
There also are a lot of monitoring
62
00:04:39,500 --> 00:04:42,340
 

63
00:04:42,340 --> 00:04:44,595
 

64
00:04:44,600 --> 00:04:47,360
有海鲜交易纠纷 就可以查看录像
You can check out the video tape if there is a seafood transaction dispute
65
00:04:47,880 --> 00:04:51,060
去前面走一下 看看有没有加工海鲜的地方
Go ahead and see if there is any place to processed seafood
66
00:04:51,080 --> 00:04:53,520
 

67
00:04:54,635 --> 00:04:57,655
 

68
00:04:58,220 --> 00:04:59,280
 

69
00:05:01,580 --> 00:05:06,700
不管几个螃蟹都是一锅一蒸  一锅15元
Steamed a pot no matter how many crabs charge 15 yuan per pot
70
00:05:06,700 --> 00:05:08,540
这一大袋15元
15 for the big bag of seafood
71
00:05:15,160 --> 00:05:20,600
现在海鲜已经入锅了 等15分钟就可以吃了
Now the seafood is in the pot and steaming it, you can eat it after 15 minutes
72
00:05:27,040 --> 00:05:31,280
像扇贝 生蚝 它的肉直接从壳里掉出来了
Seafood like scallops, and oysters, its meat just fell out of the shell
73
00:05:33,740 --> 00:05:34,860
先尝一个
Let’s try it
74
00:05:35,960 --> 00:05:38,680
真的很鲜甜的感觉
It taste fresh and sweet
75
00:05:40,940 --> 00:05:42,960
不蘸姜醋汁也挺好吃的
And still delicious without dipping of ginger and vinegar sauce
76
00:05:47,980 --> 00:05:49,880
 

77
00:05:54,780 --> 00:05:56,080
这个汁水多
Very juicy
78
00:06:01,420 --> 00:06:06,160
在青岛有种豪气叫做把海鲜当饭吃
In qingdao people eat seafood as common as rice
79
00:06:10,020 --> 00:06:14,460
这么一盘 原材料才18元
A whole plate of raw seafood like this are 18 yuan only
80
00:06:24,060 --> 00:06:27,760
现在螃蟹也上桌了  这个蟹是60块钱
Now the crab is also on the table, it’s 60 yuan
81
00:06:27,760 --> 00:06:29,720
足足有7两重
About 7 liang(350g)
82
00:06:31,360 --> 00:06:35,220
蒸熟的螃蟹红彤彤的 颜值很高
The steamed crabs are red and beautiful
83
00:06:36,140 --> 00:06:39,180
这蟹腿挺粗的
The legs of crabs pretty thick
84
00:06:40,220 --> 00:06:42,900
先吃这个腿吧
Let's start from the crab leg
85
00:06:49,240 --> 00:06:52,900
吃一口就是鲜甜的味道
Fresh and sweet taste
86
00:06:53,820 --> 00:06:54,820
再来一个
One more
87
00:06:55,120 --> 00:06:57,660
 

88
00:06:58,720 --> 00:06:59,720
 

89
00:07:03,080 --> 00:07:04,560
蟹肉很厚实
The crab meat is very thick
90
00:07:05,220 --> 00:07:06,220
 

91
00:07:08,365 --> 00:07:09,365
 

92
00:07:13,595 --> 00:07:15,045
 

93
00:07:17,245 --> 00:07:18,245
 

94
00:07:19,855 --> 00:07:21,075
 

95
00:07:26,955 --> 00:07:27,955
 

96
00:07:28,885 --> 00:07:29,985
 

97
00:07:33,375 --> 00:07:34,375
