### ISSUE TITLE
[华农兄弟] 华农兄弟把小白猪安顿好后看一下兄弟家的脐橙顺路挖点红薯 - https://youtu.be/6cUcbwLicOk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#1526]
https://youtu.be/6cUcbwLicOk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 29, 2020 at 12:02PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/6cUcbwLicOk

#华农兄弟：把小白猪安顿好后，看一下兄弟家的脐橙，顺路挖点红薯
#Huanonb Brothers: We settle down the white piggies, look at our buddy's navel oranges, and dig some sweet potatoes.

0:00:00.000,0:00:03.260
# 大家好  去年兄弟抓了我兩隻香豬哦
Hi everyone! My buddy caught two pigs from my place last year.

0:00:03.260,0:00:04.980
# 他現在  到現在也不給錢
But now…. I mean he has never paid me, not even now.

0:00:04.980,0:00:07.460
# 今天我去他那裡抓了兩條白豬回來
So I caught two white pigs from his place today.

0:00:07.860,0:00:11.920
# 他說用那個香豬哏白豬配在一起生出來的哦
He said that it was bred from a Huanjiang pig and a white pig, you know.

0:00:13.060,0:00:14.160
# 看上去就很漂亮
They look really pretty.

0:00:18.760,0:00:19.920
# 兩條小白豬
Two white piggies

0:00:21.400,0:00:23.680
# 抬上去和那個黑豬一起餵
Let's carry it up there and keep it with that black pig,

0:00:24.180,0:00:25.320
# 看一下怎麼樣
and see what will happen.

0:00:29.660,0:00:31.020
# 誒 你們自由啦
Ey! You’re free now.

0:01:04.800,0:01:07.200
# 這個是  這公的
This one is, this is male.

0:01:11.760,0:01:13.340
# 你看  這小豬自己跑出來啦
Look! This piggy is coming out itself.

0:01:14.520,0:01:15.540
# 自己會跑出來哦
It comes out itself.

0:01:23.100,0:01:25.360
# 你看 兩條大白豬
Look! Two fat white pigs.

0:01:28.000,0:01:29.440
# 屁股上都黑色的
Their butts are black,

0:01:31.220,0:01:32.840
# 長了有胎記
with birthmarks.

0:01:37.420,0:01:38.600
# 它們在交流
They’re communicating.

0:01:47.020,0:01:48.480
# 你看  那小豬還想喝奶
Look! That piggy wants milk.

0:01:49.320,0:01:50.820
# 它那麼小就被我抓回來啦
I’ve caught them back here, though they’re still so small.

0:01:51.600,0:01:54.000
# 這沒事啊  看它都斷奶啦
No worries. They’ve already weaned, I bet

0:02:09.960,0:02:14.240
# 這個豬最  最大的話能長六七百斤的哦
These pigs can reach up to, up to three hundred and fifty kilograms, you know.

0:02:14.240,0:02:17.160
# 它養個一兩年的話可以長到很大的
They can be super huge in a year or two.

0:02:18.140,0:02:19.480
# 過年的时候應該有兩百斤
I think they could reach around a hundred kilograms by the Chinese New Year.

0:02:21.560,0:02:22.500
# 一人一百斤
Let’s have fifty kilograms each.

0:02:24.380,0:02:25.340
# 要不要一人一條
Or you want one each?

0:02:28.760,0:02:32.300
# 你看  耆們慢慢就會  慢慢就會熟悉的
Look! They’ll be gradually, gradually familiar with this place.

0:02:32.580,0:02:33.520
# 它們自己
They’ll have,

0:02:34.860,0:02:35.740
# 自己玩自己的
they'll have their own fun.

0:02:36.380,0:02:37.880
# 它們自己會自己吃啦
They’ll find their own food.

0:02:38.140,0:02:38.960
# 不用我們管啦
We don’t really need to take care of them.

0:02:40.680,0:02:43.100
# 不管它們  讓它們自己在  在這裡玩
Leave them alone and let them have, have fun here.

0:02:44.040,0:02:45.480
# 啊  你們在這裡玩就好了啊
Ah! Stay here and have fun! Everything will be fine.

0:02:45.880,0:02:49.120
# 不是抓你們  不要那麼怕
Don’t be so scared. I’m not catching you.

0:02:50.360,0:02:52.980
# 小豬已經安頓好啦  我去看一下兄弟家的臍橙
The piggies have already been settled down. Let’s have a look at my buddy’s navel oranges.

0:02:53.240,0:02:55.320
# 今年的臍橙聽說產量很高
I’ve heard that the yield is really high this year.

0:02:55.820,0:02:57.440
# 就在那裡村口  就我們村的
It’s right at the entrance of the village, our village.

0:02:58.920,0:03:00.240
# 有點黃出來啦  看見沒有
Look! It’s turning yellow, see?

0:03:01.640,0:03:02.920
# 慢慢地黃起來啦
It’s turning yellow gradually.

0:03:04.000,0:03:05.920
# 你看  三胞胎
Look! Triplet

0:03:07.280,0:03:09.140
# 一樹都是  你看這棵
They’re all over the tree. Have a look at this tree!

0:03:11.240,0:03:14.780
# 好多啊今年  碩果累纍纍
There are a lot this year. So fruitful!

0:03:15.420,0:03:16.880
# 今年產量好高哦
The yield this year is really high,

0:03:18.100,0:03:19.420
# 比去年高很多誒
much higher than last year.

0:03:20.480,0:03:23.060
# 你看  這些都是種了差多快五年的樹啦
Look! These are about five-year old trees.

0:03:24.780,0:03:27.440
# 五年才那麼大一點  那麼大一點的幹子
Five years, but it's still not really big, the branches are still not really that big.

0:03:31.200,0:03:33.400
# 你看這個樹都斷啦  太多啦
Look! This branch is about to break. There are just too many oranges.

0:03:33.960,0:03:35.280
# 直接掰下來啦
Let me just pick one right away.

0:03:35.760,0:03:37.560
# 看一下有沒有掉在地上的
See if any has dropped onto the ground.

0:03:37.560,0:03:39.240
# 哎呀 真的有個掉在地上的
Aya! Here's really one on the ground.

0:03:40.380,0:03:42.980
# 你看是不是  泥巴都有啦
This one, isn’t it? I can even see mud on it.

0:03:44.560,0:03:46.360
# 嘗一下  看下怎麼樣 味道
Let me have a try, and see how it is, how it tastes.

0:03:46.720,0:03:47.980
# 現在應該可以好吃啦
It might be tasty, by this time.

0:03:53.440,0:03:54.740
# 嗯  還有點酸
Um! It’s still a little bit sour.

0:03:57.620,0:03:59.920
# 黃一些就好吃啦  現在還不是很黃
It will taste much better when it turns yellow. But it’s still a bit green.

0:04:01.720,0:04:03.940
# 現在還不是很甜  太酸啦
It’s not really that sweet, too sour.

0:04:04.460,0:04:08.000
# 臍橙都還沒熟  看下路過  路過兄弟家這個紅薯
The navel oranges are not yet ripe. We now pass by my, my buddy’s sweet potatoes.

0:04:08.000,0:04:08.880
# 搞點回去
Let’s get some back home.

0:04:09.940,0:04:11.840
# 這個紅薯  不知道有沒有
These are sweet potatoes. But I don’t know if there are really any,

0:04:12.620,0:04:13.660
# 挖了才知道
at least not before I start digging.

0:04:15.580,0:04:17.080
# 哎呀  你看
Aya! Look!

0:04:18.660,0:04:20.820
# 你看  這裡有一個了吧  是不是
Look! Here’s one, right?

0:04:21.160,0:04:23.180
# 那麼小  那麼小也可以吃的啦
It’s so small. It’s small but it’s also edible.

0:04:23.560,0:04:24.220
# 是不是
Right?

0:04:26.440,0:04:30.040
# 這樣紅薯很漂亮的哦  看下  不大又不小
This kind of sweet potatoes are really pretty. Look! They're not too big, not too small.

0:04:31.000,0:04:31.760
# 剛剛好
Perfect size.

0:04:34.860,0:04:36.120
# 這還有幾個啊
Here are a few more.

0:04:44.080,0:04:46.140
# 這個小太了  這個拿回去給小豬吃
This one is too small. I’ll take it back for the piggies.

0:04:51.400,0:04:52.600
# 誒呀  這麼大啊
Eya! So big.

0:04:53.540,0:04:54.760
# 這個才大  這個
This is huge, this one.

0:05:02.460,0:05:03.660
# 夠啦夠啦  不要啦
Enough, enough! No more

0:05:04.840,0:05:07.940
# 看一下  看一下子就挖到那麼多
Look! I have, I have so many here in just a few minutes.

0:05:10.380,0:05:11.900
# 剛好  這裡有一個袋子
It just so happens that, here is a bag.

0:05:13.500,0:05:14.920
# 肯定兄弟給我準備的
It must be prepared by my buddy, specially for me.

0:05:16.200,0:05:20.020
# 好啦  把這紅薯藤帶回去給豬吃
Alright! Let me take these leaves for the pigs.

0:05:22.720,0:05:25.340
# 把這紅薯  把它洗一下
The sweet potatoes… Let me wash them.

0:05:29.660,0:05:30.180
# 你看
Look!

0:05:31.560,0:05:32.800
# 這小紅薯
These small sweet potatoes.

0:05:35.100,0:05:37.960
# 挖番薯的同時順手帶了幾個玉米回來 (註︰不知怎樣表達這個「順手」，我想意思就是在附近，「來都來了」)
I’ve taken a couple of corns back as well, cuz they were close to the sweet potatoes.

0:05:41.080,0:05:43.260
# 這樣剝乾淨點用那個
Peel them well, and then, you know,

0:05:44.560,0:05:48.680
# 鍚紙裹起來就直接這樣  烤熟它就可以啦
wrap them up with aluminium foil, and then we can, just grill them right away.

0:05:51.040,0:05:51.980
# 這樣就漂亮啦
It’s really pretty now.

0:06:11.280,0:06:14.660
# 嗯  可以啦  準備  上炭
Um! Alright! Everything’s ready! Get the charcoal!

0:06:24.560,0:06:26.180
# 先把這裡兩放到這裡先
Let me first put these two here.

0:06:36.960,0:06:39.320
# 你看  這樣就熟的  熟的快啦
Look! Then, it’s gonna take, take less time.

0:06:41.000,0:06:42.820
# 再過鄰個小時候可以開吃啦
We can start after half an hour.

0:06:44.200,0:06:45.200
# 這個玉米
The corns,

0:06:46.100,0:06:46.760
# 熟了哦
are done now.

0:06:48.080,0:06:50.160
# 應該熟了 按道理來說的話
They should be done now, theoretically.

0:06:50.980,0:06:52.220
# 哎呀  好燙啊
Aya! It’s really hot!

0:06:57.300,0:06:58.580
# 金黃的身體
Golden yellow body.

0:07:06.720,0:07:08.100
# 泡點水  好燙啊
It’s too hot. Let me rinse it.

0:07:18.300,0:07:19.680
# 好啦 嘗一下
Alright! Let me try,

0:07:19.680,0:07:20.900
# 嘗一下味道怎樣
and see how it tastes.

0:07:22.940,0:07:23.800
# 嗯
Um!

0:07:25.420,0:07:26.220
# 好香
It smells so good,

0:07:27.940,0:07:29.580
# 真的好香啊  好好吃啊
really, really good! It’s so tasty!

0:07:31.340,0:07:32.420
# 看下這紅薯
Have a look at the sweet potatoes.

0:07:34.380,0:07:35.380
# 這才是紅色
This colour is called red.

0:07:36.260,0:07:40.020
# 你看  這個好啊 這個小  小紅薯
Look! It's really tasty, this small, small sweet potatoes.

0:07:48.140,0:07:52.560
# 都熟透了 它只是這個水分被蒸乾了一樣
It’s done now, in fact. It’s just dried out.

0:07:54.800,0:07:56.600
# 嗯  好吃啊  搞一個
Um! Tasty! Have one!

0:08:03.440,0:08:04.800
# 剛好又紅又紛的
It’s red and mushy, prefect!

0:08:05.900,0:08:09.080
# 今天視頻到這裡啦  準備吃晚飯啦
The video ends here. We need to get ready for dinner.
