### ISSUE TITLE
[老饭骨] 烂肉面 - https://youtu.be/MILPPXQ_JCk

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1546]
**视频链接**：https://youtu.be/MILPPXQ_JCk

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•烂肉面】家常面条豪横吃法烂肉面，一碗管饱，还原老舍《茶馆》中的经典美味！ |老饭骨
简介
小友们好！咱们又见面了！今天二伯为大家带来一道老舍《茶馆》中的经典美味——烂肉面！
这烂肉面做法简单家常，打卤料足，有猪棒骨、腔骨、猪骨头、干香菇、干口蘑、木耳等，一碗就能管饱！
今天片尾除了介绍芹菜的各种吃法，还有超多大爷二伯的彩蛋，大家千万不要错过哦！
字幕
1
00:00:00,000 --> 00:00:02,440
有骨头 有剔下来的肉头子

2
00:00:02,440 --> 00:00:05,320
边角料 腔骨还有棒骨 什么都有

3
00:00:05,320 --> 00:00:07,080
就是做菜剩下的东西

4
00:00:07,080 --> 00:00:10,040
黄花 干口蘑 木耳 香菇

5
00:00:10,040 --> 00:00:10,800
这打卤面啊师父

6
00:00:11,160 --> 00:00:12,640
什么打卤面啊

7
00:00:12,640 --> 00:00:14,120
不是打卤面是什么面

8
00:00:14,120 --> 00:00:15,240
烂肉面

9
00:00:15,240 --> 00:00:18,480

10
00:00:19,160 --> 00:00:21,520
我第一次知道烂肉面

11
00:00:21,520 --> 00:00:24,600
是从电影《茶馆》里头

12
00:00:24,600 --> 00:00:27,160
香菇水留着 底下不能要

13
00:00:27,160 --> 00:00:29,320

14
00:00:29,320 --> 00:00:31,600
口蘑水 也是

15
00:00:31,600 --> 00:00:32,800
光要上边的 底下都不要

16
00:00:32,800 --> 00:00:34,080
底下有沙子

17
00:00:34,080 --> 00:00:36,160
这个菜是流传好多年的

18
00:00:36,160 --> 00:00:39,480
支个棚 摆两张桌子就卖烂肉面

19
00:00:39,480 --> 00:00:41,480
咱把这改一下刀 小魏

20
00:00:41,480 --> 00:00:43,080
今天咱这是提升版了师父

21
00:00:43,080 --> 00:00:44,160
原来没这么好的料

22
00:00:44,160 --> 00:00:46,320
就是筋头巴脑 边边沿沿

23
00:00:46,320 --> 00:00:48,480
这个菜是必须得有口蘑的是吧

24
00:00:48,480 --> 00:00:49,920
必须得有口蘑

25
00:00:49,920 --> 00:00:53,200
过去打卤 好多都离不开口蘑

26
00:00:54,600 --> 00:00:56,560
葱姜 大料 桂皮

27
00:00:56,560 --> 00:00:59,440
这个肉让小亮连冲带泡都白了

28
00:00:59,440 --> 00:01:02,520
里边的沫子就少多了 一会就不用焯了

29
00:01:02,520 --> 00:01:04,120
黄酒 齐活

30
00:01:04,120 --> 00:01:06,640
高压锅压吧 因为时间的问题

31
00:01:06,640 --> 00:01:09,520
这是能让人吃饱又解馋的

32
00:01:09,520 --> 00:01:11,280
其实烂肉面白煮也行

33
00:01:11,280 --> 00:01:13,360
咱这里边再加点酱油也行

34
00:01:13,360 --> 00:01:18,040

35
00:01:18,040 --> 00:01:20,520
来 40分钟到50分钟都可以

36
00:01:20,520 --> 00:01:21,600
越烂乎越好

37
00:01:21,600 --> 00:01:23,400
花椒对这个菜影响很大的

38
00:01:23,400 --> 00:01:25,480
花椒油

39
00:01:25,480 --> 00:01:28,120
我就要这花椒油的香味

40
00:01:28,120 --> 00:01:31,960
打卤面 这面那面 它离不开这个

41
00:01:31,960 --> 00:01:34,280
这香味是慢慢让它释放出来

42
00:01:34,280 --> 00:01:38,080
花椒的香只有这样出的才好

43
00:01:38,080 --> 00:01:39,600
小火你看见没有

44
00:01:39,600 --> 00:01:42,560
这花椒基本都黑了 就行了

45
00:01:44,160 --> 00:01:46,440
这香气多好

46
00:01:46,440 --> 00:01:49,000
歇会吧 就等着拆骨肉了

47
00:01:49,000 --> 00:01:51,240
不能太薄了 太薄了没口感了面

48
00:01:51,240 --> 00:01:52,440

49
00:01:54,160 --> 00:01:56,680
三仔儿 齐活

50
00:01:56,680 --> 00:01:59,160
熟了 这可烂乎啊师父

51
00:01:59,160 --> 00:02:03,360
杠杠的这肉 没毛病 香啊师父

52
00:02:03,360 --> 00:02:05,720
你看一抖落就下来了 特别烂乎

53
00:02:06,880 --> 00:02:08,960
这边晾着咱打卤

54
00:02:08,960 --> 00:02:11,400
花椒油 先煸葱花呗师父

55
00:02:11,400 --> 00:02:14,040
葱花炝锅

56
00:02:14,040 --> 00:02:17,240
炝出香味煸口蘑 煸香菇

57
00:02:17,240 --> 00:02:18,720
黄花

58
00:02:21,120 --> 00:02:22,600
木耳

59
00:02:22,600 --> 00:02:25,640

60
00:02:25,640 --> 00:02:26,640
酱油

61
00:02:26,640 --> 00:02:30,160

62
00:02:30,160 --> 00:02:31,200
黄酒

63
00:02:31,200 --> 00:02:32,440

64
00:02:32,440 --> 00:02:34,800
香菇水口蘑水

65
00:02:34,800 --> 00:02:37,480
根儿不能要 有沙子

66
00:02:37,480 --> 00:02:41,160
来两勺烂肉汤 好了

67
00:02:41,160 --> 00:02:43,960
老抽让它调调色 行了

68
00:02:43,960 --> 00:02:48,000
师父调汤 我把面煮上 两不耽误

69
00:02:48,000 --> 00:02:49,840
这还有点白胡椒粉

70
00:02:49,840 --> 00:02:51,800
今儿这汤 鲜味十足

71
00:02:51,800 --> 00:02:53,440
把拆骨肉搁进去

72
00:02:53,440 --> 00:02:55,720
这能不好吃么 这够横的

73
00:02:55,720 --> 00:02:59,120
好  面也差不多了

74
00:02:59,120 --> 00:03:00,440
烂肉面

75
00:03:00,440 --> 00:03:02,800
是不是咕嘟时间越长越好吃

76
00:03:02,800 --> 00:03:04,040
差不多就得了

77
00:03:04,040 --> 00:03:07,800
面也好了 豪华版烂肉面

78
00:03:07,800 --> 00:03:09,440
出锅

79
00:03:09,440 --> 00:03:11,640

80
00:03:11,640 --> 00:03:14,640
真是烂肉 一碗烂肉面出锅了

81
00:03:14,640 --> 00:03:15,560

82
00:03:15,560 --> 00:03:16,360
你得忒儿喽

83
00:03:16,360 --> 00:03:18,200

84
00:03:18,200 --> 00:03:22,320
终于吃到《茶馆》里边的烂肉面了

85
00:03:22,320 --> 00:03:27,080
拆骨肉你看 这个面这个卤

86
00:03:27,080 --> 00:03:29,000
我觉得跟咱们吃

87
00:03:29,000 --> 00:03:30,840
正常打卤是不一样的

88
00:03:30,840 --> 00:03:33,360
一般的花椒油都是后呲的

89
00:03:33,360 --> 00:03:35,880
你看我拿花椒油打底子

90
00:03:35,880 --> 00:03:40,320
我用温火慢慢的让花椒释放

91
00:03:40,320 --> 00:03:42,720
最后炸到花椒有点糊了

92
00:03:42,720 --> 00:03:46,200
花椒那种淡淡的那种香气味

93
00:03:46,200 --> 00:03:50,200
然后用这个再煸葱花煸菌类

94
00:03:50,200 --> 00:03:52,680
然后淡化花椒油的味 似有似无

95
00:03:52,680 --> 00:03:55,200
这跟后呲截然不同

96
00:03:55,200 --> 00:03:56,720
后边呲全是花椒油的味

97
00:03:56,720 --> 00:03:59,600
又学一招师父 感谢

98
00:03:59,600 --> 00:04:00,680
师弟 走

99
00:04:00,680 --> 00:04:03,840
你们吃吧 最后一口

100
00:04:05,560 --> 00:04:06,400
吃的满头大汗

```

**Comment by WillZhang975** [comment]
认领

**Comment by WillZhang975** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•烂肉面】家常面条豪横吃法烂肉面，一碗管饱，还原老舍《茶馆》中的经典美味！ |老饭骨
简介
小友们好！咱们又见面了！今天二伯为大家带来一道老舍《茶馆》中的经典美味——烂肉面！
这烂肉面做法简单家常，打卤料足，有猪棒骨、腔骨、猪骨头、干香菇、干口蘑、木耳等，一碗就能管饱！
今天片尾除了介绍芹菜的各种吃法，还有超多大爷二伯的彩蛋，大家千万不要错过哦！
【The State Banquet Master Chef - Rotten Pork Noodles】 Home-made noodles with rotten pork, full with one bowl, restore the classic taste of Lao She's "Teahouse"! |The old rice bones.
INTRODUCTION
Hello, friends! Here we are again! Today Er Bai brings you a classic dish from Lao She's "Teahouse" - rotten pork noodles!
This rotten pork noodle is simple, with plenty of marinade ingredients, including pork rod bones, pork bones, dried shiitake, dried mushrooms, wood fungus and more, you will be full with one bowl!
In addition to the various ways to eat celery at the end of today's film, there's also a superb number of bonuses for Da Ye and Er Bai, so don't miss it!

字幕
1
00:00:00,000 --> 00:00:02,440
有骨头 有剔下来的肉头子
There are bones, there are heads of meat.
2
00:00:02,440 --> 00:00:05,320
边角料 腔骨还有棒骨 什么都有
Trimmings, bones, rods, everything.
3
00:00:05,320 --> 00:00:07,080
就是做菜剩下的东西
They are what's left over from cooking.
4
00:00:07,080 --> 00:00:10,040
黄花 干口蘑 木耳 香菇
Daylily Dried mushrooms, dried fungus, shiitake
5
00:00:10,040 --> 00:00:10,800
这打卤面啊师父
It's marinade noodles, Master
6
00:00:11,160 --> 00:00:12,640
什么打卤面啊
Wrong
7
00:00:12,640 --> 00:00:14,120
不是打卤面是什么面
What kind of noodles?
8
00:00:14,120 --> 00:00:15,240
烂肉面
Rotten meat noodles
9
00:00:15,240 --> 00:00:18,480

10
00:00:19,160 --> 00:00:21,520
我第一次知道烂肉面
First time I knew rotten meat noodles
11
00:00:21,520 --> 00:00:24,600
是从电影《茶馆》里头
was in the movie “Teahouse”
12
00:00:24,600 --> 00:00:27,160
香菇水留着 底下不能要
Keep the shiitake water except the bottom part.
13
00:00:27,160 --> 00:00:29,320

14
00:00:29,320 --> 00:00:31,600
口蘑水 也是
So is mushroom water
15
00:00:31,600 --> 00:00:32,800
光要上边的 底下都不要
Just the top, not the bottom.
16
00:00:32,800 --> 00:00:34,080
底下有沙子
There's sand at the bottom
17
00:00:34,080 --> 00:00:36,160
这个菜是流传好多年的
It's a dish that's been around for years
18
00:00:36,160 --> 00:00:39,480
支个棚 摆两张桌子就卖烂肉面
Put up a shed, set up two tables and that’s enough to sell noodles.
19
00:00:39,480 --> 00:00:41,480
咱把这改一下刀 小魏
Let’s cut it here, Wei
20
00:00:41,480 --> 00:00:43,080
今天咱这是提升版了师父
Today we have an upgrade, Master.
21
00:00:43,080 --> 00:00:44,160
原来没这么好的料
It didn’t have the nice ingredients before.
22
00:00:44,160 --> 00:00:46,320
就是筋头巴脑 边边沿沿
Just trimmings
23
00:00:46,320 --> 00:00:48,480
这个菜是必须得有口蘑的是吧
The mushroom is essential in this dish, right?
24
00:00:48,480 --> 00:00:49,920
必须得有口蘑
Of course
25
00:00:49,920 --> 00:00:53,200
过去打卤 好多都离不开口蘑
Mushroom is part of marinated noodles. 
26
00:00:54,600 --> 00:00:56,560
葱姜 大料 桂皮
green onions, ginger, star anise, cinnamon
27
00:00:56,560 --> 00:00:59,440
这个肉让小亮连冲带泡都白了
The pork is nearly white after washing
28
00:00:59,440 --> 00:01:02,520
里边的沫子就少多了 一会就不用焯了
There's less froth inside. We don’t have to blanch it later
29
00:01:02,520 --> 00:01:04,120
黄酒 齐活
Huangjiu rice wine. That’s all!
30
00:01:04,120 --> 00:01:06,640
高压锅压吧 因为时间的问题
Considering time, let’s use pressure pot.
31
00:01:06,640 --> 00:01:09,520
这是能让人吃饱又解馋的
It's the one that will fill you up and satisfy your cravings
32
00:01:09,520 --> 00:01:11,280
其实烂肉面白煮也行
Actually, the rotten meat noodles can be cooked in plain water.
33
00:01:11,280 --> 00:01:13,360
咱这里边再加点酱油也行
We can add a little soy sauce here.
34
00:01:13,360 --> 00:01:18,040

35
00:01:18,040 --> 00:01:20,520
来 40分钟到50分钟都可以
about 40-50 mins
36
00:01:20,520 --> 00:01:21,600
越烂乎越好
It’s better to stew it longer.
37
00:01:21,600 --> 00:01:23,400
花椒对这个菜影响很大的
Szechuan peppers are a big influence on this dish.
38
00:01:23,400 --> 00:01:25,480
花椒油
Szechuan pepper oil
39
00:01:25,480 --> 00:01:28,120
我就要这花椒油的香味
I want the aroma of pepper oil
40
00:01:28,120 --> 00:01:31,960
打卤面 这面那面 它离不开这个
The noodles can’t separate from it.
41
00:01:31,960 --> 00:01:34,280
这香味是慢慢让它释放出来
The scent is being released slowly
42
00:01:34,280 --> 00:01:38,080
花椒的香只有这样出的才好
This is the only way to get the aroma of pepper.
43
00:01:38,080 --> 00:01:39,600
小火你看见没有
Do you see that? Simmer it.
44
00:01:39,600 --> 00:01:42,560
这花椒基本都黑了 就行了
Until the peppers are mostly black
45
00:01:44,160 --> 00:01:46,440
这香气多好
That's a nice aroma
46
00:01:46,440 --> 00:01:49,000
歇会吧 就等着拆骨肉了
Let's take a break. We're just waiting for the bone and meat.
47
00:01:49,000 --> 00:01:51,240
不能太薄了 太薄了没口感了面
You can't make it too thin. It's too thin. It'll lose its texture.
48
00:01:51,240 --> 00:01:52,440

49
00:01:54,160 --> 00:01:56,680
三仔儿 齐活
Finish!
50
00:01:56,680 --> 00:01:59,160
熟了 这可烂乎啊师父
It's done. It's rotten, Master
51
00:01:59,160 --> 00:02:03,360
杠杠的这肉 没毛病 香啊师父
This meat is really good. It's delicious, Master.
52
00:02:03,360 --> 00:02:05,720
你看一抖落就下来了 特别烂乎
Look at the way it came off. It's so rotten.
53
00:02:06,880 --> 00:02:08,960
这边晾着咱打卤
Leave it here. 
54
00:02:08,960 --> 00:02:11,400
花椒油 先煸葱花呗师父
Sichuan peppercorn oil. Stir in the onion first
55
00:02:11,400 --> 00:02:14,040
葱花炝锅
Stir-fry green onion
56
00:02:14,040 --> 00:02:17,240
炝出香味煸口蘑 煸香菇
when aroma comes out we stir-fry mushroom and shiitake
57
00:02:17,240 --> 00:02:18,720
黄花
Daylily
58
00:02:21,120 --> 00:02:22,600
木耳
black fugus
59
00:02:22,600 --> 00:02:25,640

60
00:02:25,640 --> 00:02:26,640
酱油
soy sauce
61
00:02:26,640 --> 00:02:30,160

62
00:02:30,160 --> 00:02:31,200
黄酒
huangjiu rice wine
63
00:02:31,200 --> 00:02:32,440

64
00:02:32,440 --> 00:02:34,800
香菇水口蘑水
the mushroom and shiitake water
65
00:02:34,800 --> 00:02:37,480
根儿不能要 有沙子
There are sands at the bottom. We don’t use it.
66
00:02:37,480 --> 00:02:41,160
来两勺烂肉汤 好了
And two spoons broth. That’s it.
67
00:02:41,160 --> 00:02:43,960
老抽让它调调色 行了
Use dark soy sauce to add some color
68
00:02:43,960 --> 00:02:48,000
师父调汤 我把面煮上 两不耽误
Master makes the marinade and I boil the noddles.
69
00:02:48,000 --> 00:02:49,840
这还有点白胡椒粉
Add some white pepper.
70
00:02:49,840 --> 00:02:51,800
今儿这汤 鲜味十足
Today’s soup has much umami taste
71
00:02:51,800 --> 00:02:53,440
把拆骨肉搁进去
then add the separated meat in it.
72
00:02:53,440 --> 00:02:55,720
这能不好吃么 这够横的
Isn't this delicious? It's so good
73
00:02:55,720 --> 00:02:59,120
好  面也差不多了
Okay, noodles are almost ready
74
00:02:59,120 --> 00:03:00,440
烂肉面
Rotten meat noodles
75
00:03:00,440 --> 00:03:02,800
是不是咕嘟时间越长越好吃
Is it true that the longer cooking process, the better it tastes?

76
00:03:02,800 --> 00:03:04,040
差不多就得了
You need to balance.
77
00:03:04,040 --> 00:03:07,800
面也好了 豪华版烂肉面
The noodles are ready. The superb rotten meat noodles.
78
00:03:07,800 --> 00:03:09,440
出锅
Time to enjoy it!
79
00:03:09,440 --> 00:03:11,640

80
00:03:11,640 --> 00:03:14,640
真是烂肉 一碗烂肉面出锅了
How rotten it is!
81
00:03:14,640 --> 00:03:15,560

82
00:03:15,560 --> 00:03:16,360
你得忒儿喽
The rotten meat noodles is ready! So good!
83
00:03:16,360 --> 00:03:18,200

84
00:03:18,200 --> 00:03:22,320
终于吃到《茶馆》里边的烂肉面了
Finally, the rotten pork noodles from "Teahouse is in my mouth.
85
00:03:22,320 --> 00:03:27,080
拆骨肉你看 这个面这个卤
Look at the marinade.
86
00:03:27,080 --> 00:03:29,000
我觉得跟咱们吃
I think it’s different from 
87
00:03:29,000 --> 00:03:30,840
正常打卤是不一样的
the common marinaded noodles.
88
00:03:30,840 --> 00:03:33,360
一般的花椒油都是后呲的
Usually, the Sichuan pepper oil is used at the end
89
00:03:33,360 --> 00:03:35,880
你看我拿花椒油打底子
but I used it at the beginning 
90
00:03:35,880 --> 00:03:40,320
我用温火慢慢的让花椒释放
simmer it to release the aroma
91
00:03:40,320 --> 00:03:42,720
最后炸到花椒有点糊了
until they are black
92
00:03:42,720 --> 00:03:46,200
花椒那种淡淡的那种香气味
the gentle aroma from Sichuan peppercorn
93
00:03:46,200 --> 00:03:50,200
然后用这个再煸葱花煸菌类
mixed with fried green onion and mushrooms
94
00:03:50,200 --> 00:03:52,680
然后淡化花椒油的味 似有似无
so the aroma of Sichuan pepper is ambiguous
95
00:03:52,680 --> 00:03:55,200
这跟后呲截然不同
the results are totally different
96
00:03:55,200 --> 00:03:56,720
后边呲全是花椒油的味
You will get strong pepper taste if it is used in the last
97
00:03:56,720 --> 00:03:59,600
又学一招师父 感谢
I learnt a new trick Master, Thanks
98
00:03:59,600 --> 00:04:00,680
师弟 走
Come on brother
99
00:04:00,680 --> 00:04:03,840
你们吃吧 最后一口
You guys eat it.
100
00:04:05,560 --> 00:04:06,400
吃的满头大汗
You are sweating out on your head.
