### ISSUE TITLE
[老饭骨] 大烩菜 - https://youtu.be/qDKmbwiCmNE

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1552]
**视频链接**：https://youtu.be/qDKmbwiCmNE

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•大烩菜】简单粗暴家常大烩菜，冬天来一锅，暖暖的很幸福！ |老饭骨

简介
小友们好，最近天气逐渐转凉，老饭骨带给大家一道做法十分简单粗暴的大烩菜。
北方的小友一定不陌生，各种材料炖一锅，有肉有菜，满满一大锅，冬天来一碗，暖暖的，吃了就热乎，幸福感爆棚！
这大炖菜虽说做法简单，下菜的顺序也有讲究，怎么才能把食材炖得鲜美，激发出食材的香味，小魏师傅在视频里会一步一步教给大家。
最后想问问大家，小魏师傅的“丈母娘”炸丸子小友们吃过吗？

字幕
1
00:00:00,000 --> 00:00:02,400
豆腐白菜丸子 这菜有食欲

2
00:00:02,400 --> 00:00:04,320
四季平安 大烩菜

3
00:00:08,760 --> 00:00:11,920
这全乎 还有肉片呢

4
00:00:11,920 --> 00:00:13,320
有什么原料就搁什么原料

5
00:00:13,320 --> 00:00:14,760
煸一下肉片

6
00:00:15,680 --> 00:00:18,440
肉片要厚点 五花肉片

7
00:00:18,440 --> 00:00:20,960
这个一般就是大锅炖

8
00:00:20,960 --> 00:00:23,280
冬天来这么一锅

9
00:00:23,280 --> 00:00:26,400
大料瓣  葱丁下上

10
00:00:26,400 --> 00:00:28,600
炸成金黄色

11
00:00:28,600 --> 00:00:30,320
这菜有点意思

12
00:00:30,320 --> 00:00:31,440
蒜跟姜搁进去

13
00:00:31,440 --> 00:00:34,360
四季平安菜 白菜豆腐保平安

14
00:00:34,360 --> 00:00:35,880
看着那肉就有食欲

15
00:00:35,880 --> 00:00:40,000
这块儿这厚度适合我 不能太薄

16
00:00:40,000 --> 00:00:41,920
把这黄花搁进去一块煸一下

17
00:00:41,920 --> 00:00:43,360
提鲜又提香

18
00:00:43,360 --> 00:00:46,120
忘忧草啊 吃着高兴啊

19
00:00:46,120 --> 00:00:48,720
木耳 把水一定挤干了

20
00:00:48,720 --> 00:00:51,360
西红柿借点味 借点鲜味

21
00:00:51,360 --> 00:00:55,040
香味出来了 你看他煸菜的流程对

22
00:00:55,040 --> 00:00:58,880
这时候咱们就顺着锅边烹酱油

23
00:01:00,040 --> 00:01:03,240
你看到没有 这不贴着锅边

24
00:01:03,240 --> 00:01:07,120
香味出不来 锅气出不来

25
00:01:07,120 --> 00:01:10,400
顺序有讲究 先煸肉片煸出香味来

26
00:01:10,400 --> 00:01:13,720
然后再煸大料 让料香味出来

27
00:01:13,720 --> 00:01:17,720
然后跟着葱姜蒜 黄花木耳西红柿

28
00:01:17,720 --> 00:01:19,560
加水 开水

29
00:01:20,760 --> 00:01:24,120
红薯粉条来一大锅 这好吃

30
00:01:24,120 --> 00:01:27,320
还不够吃这个

31
00:01:27,320 --> 00:01:32,800
再来点水 这点就差不多了

32
00:01:32,800 --> 00:01:35,240
这边炖上 炸点丸子

33
00:01:35,240 --> 00:01:36,240
开大火

34
00:01:40,280 --> 00:01:41,520
这丸子馅里头有

35
00:01:41,520 --> 00:01:43,680
肉馅姜末小葱末

36
00:01:43,680 --> 00:01:46,800
糯米蒸熟的 鸡蛋黄一个鸡蛋黄

37
00:01:46,800 --> 00:01:47,960
蛋清也可以

38
00:01:47,960 --> 00:01:50,440
盐 胡椒粉 酱油

39
00:01:50,440 --> 00:01:52,560
这丸子有时候我们家也自己做

40
00:01:53,600 --> 00:01:56,440
香油是吧 香油这儿呢

41
00:01:56,440 --> 00:01:58,000
老岳母是安徽的

42
00:01:58,000 --> 00:02:00,280
她每年春节老太太（自己做）

43
00:02:01,240 --> 00:02:04,120
你这是南北大菜南北结合

44
00:02:05,520 --> 00:02:07,160
你知道这菜叫什么菜

45
00:02:08,760 --> 00:02:11,920
丈母娘菜

46
00:02:11,920 --> 00:02:14,200
再给它抓一下 有糯米有小葱

47
00:02:14,200 --> 00:02:15,600
你这姑爷行

48
00:02:15,600 --> 00:02:19,760
把老丈母娘做的手艺给学着了

49
00:02:19,760 --> 00:02:23,640
农村的土菜讲究 糯米它起黏啊

50
00:02:23,640 --> 00:02:26,840
不用搁别的你看这黏度上来了

51
00:02:26,840 --> 00:02:28,440
而且没有这么腻

52
00:02:28,440 --> 00:02:29,480
春节的时候做

53
00:02:29,480 --> 00:02:32,880
下班的时候 搁俩丸子搁点白菜

54
00:02:32,880 --> 00:02:36,040
豆腐一炖 过去穷啊没办法啊

55
00:02:36,040 --> 00:02:38,480
少来点淀粉

56
00:02:38,480 --> 00:02:41,840
开始炸了 四五成（油温）

57
00:02:43,200 --> 00:02:45,400
这个烩菜有点意思了

58
00:02:45,400 --> 00:02:48,880
我觉得这烩菜 还是得白菜给它炖的

59
00:02:48,880 --> 00:02:51,640
让它烂乎点 不能脆

60
00:02:51,640 --> 00:02:53,680
平常就来这么一个菜 

61
00:02:53,680 --> 00:02:55,080
一家子全解决了

62
00:02:55,080 --> 00:02:56,560
你这丸子豆腐一炸好了

63
00:02:56,560 --> 00:02:57,920
这菜就算成功了

64
00:02:57,920 --> 00:03:02,600
不用切 手一撕就行了 手撕白菜

65
00:03:02,600 --> 00:03:05,520
这边先炖着 丸子也行了

66
00:03:05,520 --> 00:03:08,680
这丸子白嘴都能吃都好吃 这大烩菜

67
00:03:08,680 --> 00:03:10,680
炸豆腐

68
00:03:10,680 --> 00:03:12,760
这豆腐炸的时候不用攉拢

69
00:03:12,760 --> 00:03:14,240
叫它定住型就行了

70
00:03:14,240 --> 00:03:15,680
这时候咱给调点口

71
00:03:15,680 --> 00:03:18,440
加点盐 两勺

72
00:03:18,440 --> 00:03:20,560
这个菜就得有点口儿

73
00:03:20,560 --> 00:03:23,880
胡椒粉 吃出后味胡椒的辣来

74
00:03:23,880 --> 00:03:26,040
丸子这时候加进去

75
00:03:27,280 --> 00:03:30,600
团团圆圆 四季平安大烩菜

76
00:03:30,600 --> 00:03:33,160
多炖会 炖个十来分钟

77
00:03:33,160 --> 00:03:35,400
咕咕嘟嘟 味儿就出来了

78
00:03:35,400 --> 00:03:37,160
这越炖越香

79
00:03:37,160 --> 00:03:40,880
豆腐也行了 豆腐白菜丸子 粉条

80
00:03:40,880 --> 00:03:43,120
大锅炖啊 这菜有食欲

81
00:03:43,120 --> 00:03:45,960
这菜得用砂锅出 砂锅就保温

82
00:03:45,960 --> 00:03:48,400
冬天热乎 齐活

83
00:03:48,400 --> 00:03:50,960
砂锅炖个十来分钟就行

84
00:03:50,960 --> 00:03:56,840
熟啦 这菜有意思 看着就漂亮

85
00:03:56,840 --> 00:03:59,080
小香油来点

86
00:03:59,080 --> 00:04:00,920
来块肉 来块丸子

87
00:04:02,400 --> 00:04:03,920
烫啊师父 您注意点

88
00:04:03,920 --> 00:04:06,760
吃的就是这个热乎劲

89
00:04:06,760 --> 00:04:08,720
这汤还真鲜

90
00:04:08,720 --> 00:04:11,600
菌类跟豆腐的鲜味

91
00:04:11,600 --> 00:04:12,920
这丸子好吃

92
00:04:12,920 --> 00:04:16,040
搁完糯米之后真是糯 而且不腻

93
00:04:16,040 --> 00:04:18,920
这冬天来一锅

94
00:04:18,920 --> 00:04:21,040
对这个菜 就这肉香

95
00:04:24,760 --> 00:04:27,400
这个菜来一大碗米饭一吃 热乎乎的

96
00:04:27,400 --> 00:04:29,520
我说找不着熬白菜的味

97
00:04:29,520 --> 00:04:32,480
这回找着了 这黄花搭的巧

98
00:04:32,480 --> 00:04:34,480
四季平安大烩菜

99
00:04:35,760 --> 00:04:39,080
这太接地气了 老百姓太喜欢这菜了


```

**Comment by max-sun-hongyi** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•大烩菜】简单粗暴家常大烩菜，冬天来一锅，暖暖的很幸福！ |老饭骨
[State Banquet Master•Stewed Dishes] Simple and straightforward homemade stewed dishes, a pot in winter, warm and happy! |Lao Fan Gu
简介
小友们好，最近天气逐渐转凉，老饭骨带给大家一道做法十分简单粗暴的大烩菜。
北方的小友一定不陌生，各种材料炖一锅，有肉有菜，满满一大锅，冬天来一碗，暖暖的，吃了就热乎，幸福感爆棚！
这大炖菜虽说做法简单，下菜的顺序也有讲究，怎么才能把食材炖得鲜美，激发出食材的香味，小魏师傅在视频里会一步一步教给大家。
最后想问问大家，小魏师傅的“丈母娘”炸丸子小友们吃过吗？
Hello, friends, the weather has gradually turned cold recently, and Lao Fan Gu brought you a very simple and straightforward stew.
Friends from the north must be familiar with this dish. All kinds of ingredients are stewed in a pot, there are meat and vegetables, and there is a big pot full of them. Have a bowl in winter warms you up and fill you with joy and comfort.
Although the preparation of this big stew is simple, the order of cooking ingredients is also important. How to stew the ingredients deliciously and inspire the aroma of the ingredients, Master Wei will teach you step by step in the video.
Finally, I would like to ask everyone, have you all eaten Master Wei's meat balls made in his "mother-in-law" style?

字幕
1
00:00:00,000 --> 00:00:02,400
豆腐白菜丸子 这菜有食欲
Tofu and cabbage balls, this dish looks appetizing
2
00:00:02,400 --> 00:00:04,320
四季平安 大烩菜
Four Seasons Stew
 
3
00:00:08,760 --> 00:00:11,920
这全乎 还有肉片呢
This has all, look there is meat

4
00:00:11,920 --> 00:00:13,320
有什么原料就搁什么原料
Put whatever ingredients you have
5
00:00:13,320 --> 00:00:14,760
煸一下肉片
Stir the meat slices
6
00:00:15,680 --> 00:00:18,440
肉片要厚点 五花肉片
We need thicker meat, pork belly
 
7
00:00:18,440 --> 00:00:20,960
这个一般就是大锅炖
Usually we would use a big pot to stew
8
00:00:20,960 --> 00:00:23,280
冬天来这么一锅
Imaging having such a big stew in winter time
9
00:00:23,280 --> 00:00:26,400
大料瓣  葱丁下上
Aniseed   spring onion in
10
00:00:26,400 --> 00:00:28,600
炸成金黄色
Fried into golden brown
11
00:00:28,600 --> 00:00:30,320
这菜有点意思
This dish is interesting
12
00:00:30,320 --> 00:00:31,440
蒜跟姜搁进去
Put garlic and ginger in
 
13
00:00:31,440 --> 00:00:34,360
四季平安菜 白菜豆腐保平安
Four Seasons Ping An Vegetables, Chinese Cabbage and Tofu keeps you safe
14
00:00:34,360 --> 00:00:35,880
看着那肉就有食欲
Look at the meat it’s so alluring
15
00:00:35,880 --> 00:00:40,000
这块儿这厚度适合我 不能太薄
This piece is suitable for me, not too thin
16
00:00:40,000 --> 00:00:41,920
把这黄花搁进去一块煸一下
Put this yellow flower in and stir it together
17
00:00:41,920 --> 00:00:43,360
提鲜又提香
Fresh and fragrant
18
00:00:43,360 --> 00:00:46,120
忘忧草啊 吃着高兴啊
Worry-less grass, eat and feel the joy
19
00:00:46,120 --> 00:00:48,720
木耳 把水一定挤干了
To cook the fungus you must squeeze the water throughly
20
00:00:48,720 --> 00:00:51,360
西红柿借点味 借点鲜味
Borrow some umami flavor from tomatoes
21
00:00:51,360 --> 00:00:55,040
香味出来了 你看他煸菜的流程对
The smell comes out. Look at his cooking process, right
22
00:00:55,040 --> 00:00:58,880
这时候咱们就顺着锅边烹酱油
At this time, let's cook soy sauce along the side of the pot
23
00:01:00,040 --> 00:01:03,240
你看到没有 这不贴着锅边
Did you see it? If you don’t pour soy sauce along the side of the pot
24
00:01:03,240 --> 00:01:07,120
香味出不来 锅气出不来
The aroma won’t come out, wok-hei won't come out
25
00:01:07,120 --> 00:01:10,400
顺序有讲究 先煸肉片煸出香味来
The order is exquisite, first stir the meat slices to get the aroma
26
00:01:10,400 --> 00:01:13,720
然后再煸大料 让料香味出来
Then stir the aniseed to let the flavor come out
27
00:01:13,720 --> 00:01:17,720
然后跟着葱姜蒜 黄花木耳西红柿
Then followed with green onion, ginger, garlic, yellow flower fungus, tomatoes
28
00:01:17,720 --> 00:01:19,560
加水 开水
Add water boiling water
29
00:01:20,760 --> 00:01:24,120
红薯粉条来一大锅 这好吃
Sweet potato vermicelli comes in a big pot, it's delicious
30
00:01:24,120 --> 00:01:27,320
还不够吃这个
Not enough to eat
31
00:01:27,320 --> 00:01:32,800
再来点水 这点就差不多了
Some more water, that's about it
32
00:01:32,800 --> 00:01:35,240
这边炖上 炸点丸子
Simmer here, fry some meatballs
33
00:01:35,240 --> 00:01:36,240
开大火
Turn on the heat
34
00:01:40,280 --> 00:01:41,520
这丸子馅里头有
This meatball has
35
00:01:41,520 --> 00:01:43,680
肉馅姜末小葱末
Minced ginger and shallot
36
00:01:43,680 --> 00:01:46,800
糯米蒸熟的 鸡蛋黄一个鸡蛋黄
Steamed glutinous rice with egg yolk and one egg yolk
37
00:01:46,800 --> 00:01:47,960
蛋清也可以
Egg white is fine too
38
00:01:47,960 --> 00:01:50,440
盐 胡椒粉 酱油
Salt pepper soy sauce
39
00:01:50,440 --> 00:01:52,560
这丸子有时候我们家也自己做
Sometimes our family makes this meatball by ourselves
40
00:01:53,600 --> 00:01:56,440
香油是吧 香油这儿呢
Sesame oil, right? sesame oil here
41
00:01:56,440 --> 00:01:58,000
老岳母是安徽的
My mother-in-law is from Anhui
42
00:01:58,000 --> 00:02:00,280
她每年春节老太太（自己做）
Every Spring Festival she (makes it herself)
43
00:02:01,240 --> 00:02:04,120
你这是南北大菜南北结合
You are a combination of north and south dishes
44
00:02:05,520 --> 00:02:07,160
你知道这菜叫什么菜
Do you know what this dish is called?
45
00:02:08,760 --> 00:02:11,920
丈母娘菜
Mother-in-law dish
46
00:02:11,920 --> 00:02:14,200
再给它抓一下 有糯米有小葱
Grab it again. There are glutinous rice and spring onions
47
00:02:14,200 --> 00:02:15,600
你这姑爷行
You are such a good son-in-law
48
00:02:15,600 --> 00:02:19,760
把老丈母娘做的手艺给学着了
I learned the craftsmanship of the old mother-in-law
49
00:02:19,760 --> 00:02:23,640
农村的土菜讲究 糯米它起黏啊
The countryside dish is very particular about it’s ingredients, stick rice is very sticky.
50
00:02:23,640 --> 00:02:26,840
不用搁别的你看这黏度上来了
No need to leave anything else, you see the viscosity is up
51
00:02:26,840 --> 00:02:28,440
而且没有这么腻
And not so tired
52
00:02:28,440 --> 00:02:29,480
春节的时候做
Cook this during the Spring Festival
53
00:02:29,480 --> 00:02:32,880
下班的时候 搁俩丸子搁点白菜
After work, put two meat balls and some cabbage
54
00:02:32,880 --> 00:02:36,040
豆腐一炖 过去穷啊没办法啊
Stew tofu. We used to be poor and had no other choice.
55
00:02:36,040 --> 00:02:38,480
少来点淀粉
Add less starch
56
00:02:38,480 --> 00:02:41,840
开始炸了 四五成（油温）
Let’s start to fry 120-150 degrees Celsius (oil temperature)
57
00:02:43,200 --> 00:02:45,400
这个烩菜有点意思了
This stew is a bit interesting
58
00:02:45,400 --> 00:02:48,880
我觉得这烩菜 还是得白菜给它炖的
I think this braised vegetable should be stewed with cabbage
59
00:02:48,880 --> 00:02:51,640
让它烂乎点 不能脆
Make it softer, not too crunchy
60
00:02:51,640 --> 00:02:53,680
平常就来这么一个菜 
I usually have this dish
61
00:02:53,680 --> 00:02:55,080
一家子全解决了
The whole family is done
62
00:02:55,080 --> 00:02:56,560
你这丸子豆腐一炸好了
Once your tofu balls are fried
63
00:02:56,560 --> 00:02:57,920
这菜就算成功了
This dish is successfully cooked
64
00:02:57,920 --> 00:03:02,600
不用切 手一撕就行了 手撕白菜
No need to cut, just tear it by hand, tear the cabbage by hand
65
00:03:02,600 --> 00:03:05,520
这边先炖着 丸子也行了
Stew here first, meat balls will be done soon
66
00:03:05,520 --> 00:03:08,680
这丸子白嘴都能吃都好吃 这大烩菜
This meatball is delicious by itself, this stew dish
67
00:03:08,680 --> 00:03:10,680
炸豆腐
fried tofu
68
00:03:10,680 --> 00:03:12,760
这豆腐炸的时候不用攉拢
You don’t need to move this tofu when it’s fried
69
00:03:12,760 --> 00:03:14,240
叫它定住型就行了
Just let it form its shape
70
00:03:14,240 --> 00:03:15,680
这时候咱给调点口
Let's make some adjustments on taste at this time
71
00:03:15,680 --> 00:03:18,440
加点盐 两勺
Add some salt spoons
72
00:03:18,440 --> 00:03:20,560
这个菜就得有点口儿
This dish has to be a bit salty
73
00:03:20,560 --> 00:03:23,880
胡椒粉 吃出后味胡椒的辣来
The ground pepper, you can taste the spicy aftertaste of pepper
74
00:03:23,880 --> 00:03:26,040
丸子这时候加进去
Add the balls at this time
75
00:03:27,280 --> 00:03:30,600
团团圆圆 四季平安大烩菜
Reunion and Live well Four Seasons Stew
76
00:03:30,600 --> 00:03:33,160
多炖会 炖个十来分钟
Simmer more, simmer for ten more minutes
77
00:03:33,160 --> 00:03:35,400
咕咕嘟嘟 味儿就出来了
Let it simmer and the taste will come out 
78
00:03:35,400 --> 00:03:37,160
这越炖越香
The more stewed the better
79
00:03:37,160 --> 00:03:40,880
豆腐也行了 豆腐白菜丸子 粉条
Tofu is fine too, tofu and cabbage noodles
80
00:03:40,880 --> 00:03:43,120
大锅炖啊 这菜有食欲
Big pot stew, this dish looks so appetising
81
00:03:43,120 --> 00:03:45,960
这菜得用砂锅出 砂锅就保温
This dish has to be made in a clay pot, it keeps 
82
00:03:45,960 --> 00:03:48,400
冬天热乎 齐活
Winter makes you warm, this is all set 
83
00:03:48,400 --> 00:03:50,960
砂锅炖个十来分钟就行
Simmer in a clay pot for about ten minutes
84
00:03:50,960 --> 00:03:56,840
熟啦 这菜有意思 看着就漂亮
It's cooked, this dish is interesting and beautiful
85
00:03:56,840 --> 00:03:59,080
小香油来点
Some sesame oil
86
00:03:59,080 --> 00:04:00,920
来块肉 来块丸子
Have a piece of meat and a meat ball
87
00:04:02,400 --> 00:04:03,920
烫啊师父 您注意点
Careful it’s hot, Master, pay attention

88
00:04:03,920 --> 00:04:06,760
吃的就是这个热乎劲
I enjoy eating this hot
89
00:04:06,760 --> 00:04:08,720
这汤还真鲜
This soup taste really good
90
00:04:08,720 --> 00:04:11,600
菌类跟豆腐的鲜味
The umami taste of fungus and tofu
91
00:04:11,600 --> 00:04:12,920
这丸子好吃
This meatball is delicious
92
00:04:12,920 --> 00:04:16,040
搁完糯米之后真是糯 而且不腻
After putting the glutinous rice, it's really sticky and not greasy
93
00:04:16,040 --> 00:04:18,920
这冬天来一锅
Have a pot of this in the winter
94
00:04:18,920 --> 00:04:21,040
对这个菜 就这肉香
For this dish, it's meaty
95
00:04:24,760 --> 00:04:27,400
这个菜来一大碗米饭一吃 热乎乎的
This dish comes with a big bowl of rice and it's warm
96
00:04:27,400 --> 00:04:29,520
我说找不着熬白菜的味
I said I can't find the taste of boiled cabbage
97 
00:04:29,520 --> 00:04:32,480
这回找着了 这黄花搭的巧
This time I found this yellow flower.
98
00:04:32,480 --> 00:04:34,480
四季平安大烩菜
Four Seasons Ping An Stew
99
00:04:35,760 --> 00:04:39,080
这太接地气了 老百姓太喜欢这菜了
This is so home style. People like this dish so much.
