### ISSUE TITLE
[老饭骨] 烧椒皮蛋 - https://youtu.be/dAtfRRDv5K0

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1585]
**视频链接**：https://youtu.be/dAtfRRDv5K0

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•烧椒皮蛋】四川经典凉菜烧椒皮蛋，吃一次就上瘾！调汁儿是关键！ |老饭骨

简介
小友们好，今天大爷的徒弟杨兵师傅给大家带来最正宗地道的四川经典凉菜——烧椒皮蛋！
这个烧椒皮蛋，做法非常简单，家常又下饭，学会了调汁儿的手法，用来调制其他凉菜也很美味！
烧椒的味儿，皮蛋的味儿和特制酱汁的味道，小小的凉菜也能吃出浓浓家乡的感觉。
小友们还在等什么？快点击视频一起来学习如何做这道经典开胃小菜吧！

字幕
1
00:00:00,000 --> 00:00:02,240
今天做啥子菜

2
00:00:02,240 --> 00:00:04,640
你看么 皮蛋

3
00:00:04,640 --> 00:00:05,880
做一个烧椒皮蛋

4
00:00:05,880 --> 00:00:08,560
其实这个烧就是这么玩的 非常简单

5
00:00:08,560 --> 00:00:10,480
好吃好看

6
00:00:10,480 --> 00:00:16,000

7
00:00:16,000 --> 00:00:18,160
我第一步先要烫一点红油

8
00:00:18,800 --> 00:00:21,080
四川啥子的地方的菜

9
00:00:21,080 --> 00:00:23,320
在成都做的这个菜比较多一点

10
00:00:23,320 --> 00:00:25,080
重庆也在做 内江也在做

11
00:00:25,080 --> 00:00:26,160
这个东西都一样

12
00:00:26,160 --> 00:00:27,920
只是他们采用的这个东西

13
00:00:27,920 --> 00:00:29,840
各有千秋不一样

14
00:00:29,840 --> 00:00:32,080
咱们这个用的是线椒

15
00:00:32,080 --> 00:00:35,480
线椒肉比较厚 它会有脆脆的口感

16
00:00:35,480 --> 00:00:38,240
这个是用的二荆条的（辣椒面）

17
00:00:38,240 --> 00:00:41,160
差不多油温合适就呲一下

18
00:00:41,160 --> 00:00:44,640
然后还是一样 加一点凉油

19
00:00:44,640 --> 00:00:46,600
简单一些

20
00:00:46,600 --> 00:00:48,280
我这又放了点凉油

21
00:00:48,280 --> 00:00:51,840
免的辣椒面等会糊了

22
00:00:51,840 --> 00:00:55,480
油温烧起来大概差不多六成左右

23
00:00:55,480 --> 00:00:57,360
先少倒一点进去

24
00:00:58,520 --> 00:01:01,400
差不多合适 就把它倒进去

25
00:01:01,400 --> 00:01:05,400
然后放一点醋把味道激发出来

26
00:01:05,400 --> 00:01:08,600
看一下 呲辣椒油搁点醋

27
00:01:08,600 --> 00:01:10,120
一个是香

28
00:01:10,120 --> 00:01:13,120
让味道释放的更加充分些

29
00:01:13,120 --> 00:01:14,640
还有一个一会儿这个辣椒

30
00:01:14,640 --> 00:01:16,160
它能扒到菜上

31
00:01:16,160 --> 00:01:17,720
放那儿

32
00:01:17,720 --> 00:01:19,360
现在我来烧椒

33
00:01:19,360 --> 00:01:22,200
辣椒稍微串一下

34
00:01:22,200 --> 00:01:23,720
其实这个烧就是这么玩的

35
00:01:23,720 --> 00:01:27,320
在农村里面把辣椒直接放在

36
00:01:27,320 --> 00:01:30,400
烧完膛火的炉灰 柴火灰

37
00:01:30,400 --> 00:01:32,640
直接把辣椒扔进去就好了

38
00:01:32,640 --> 00:01:35,080
让它这样烧 烧出虎皮

39
00:01:35,080 --> 00:01:36,800
它里面同时也熟了

40
00:01:37,600 --> 00:01:41,520
起虎皮了 待会把虎皮去掉 把皮撕掉

41
00:01:42,760 --> 00:01:44,200
其实还有一种方法

42
00:01:44,200 --> 00:01:46,040
也可以在锅里面去焙

43
00:01:46,040 --> 00:01:48,760
锅里面什么都不放就干的 干焙

44
00:01:48,760 --> 00:01:50,600
但是它没有这种燎的香

45
00:01:50,600 --> 00:01:52,400
燎的时候它起了虎皮之后

46
00:01:52,400 --> 00:01:56,200
还是要有点余温 让它稍微熟一点

47
00:01:56,200 --> 00:01:59,040
别到时候辣椒会有点生

48
00:01:59,040 --> 00:02:01,240
好了 巴适的很

49
00:02:01,240 --> 00:02:04,200
你看现在拿刀稍微把它刮掉

50
00:02:04,200 --> 00:02:06,240
不用刮的太干净 刮的时候

51
00:02:06,240 --> 00:02:09,040

52
00:02:09,040 --> 00:02:11,240
直接这样我切长一点

53
00:02:11,240 --> 00:02:13,120
其实手撕也行

54
00:02:13,120 --> 00:02:17,600
你看线椒这个香啊 清香嘞

55
00:02:17,600 --> 00:02:20,440
这就是比锅里焙的香啊

56
00:02:20,440 --> 00:02:22,400
对 就是燎的它比较香一点

57
00:02:22,400 --> 00:02:25,080
准备好了 然后现在就是调汁

58
00:02:25,080 --> 00:02:27,560
这个菜调汁是关键 非常简单

59
00:02:27,560 --> 00:02:29,760
姜末 大概有个二十克左右

60
00:02:29,760 --> 00:02:32,960
蒜末也差不多

61
00:02:32,960 --> 00:02:35,400
香油 来一点点的香油

62
00:02:35,400 --> 00:02:37,440
这个不要太多

63
00:02:37,440 --> 00:02:38,800
然后再来点花椒油

64
00:02:38,800 --> 00:02:40,640
稍微比香油要多一点

65
00:02:40,640 --> 00:02:44,800
米醋 一勺 一勺半

66
00:02:44,800 --> 00:02:47,440
酱油 也是一勺半差不多吧

67
00:02:47,440 --> 00:02:48,840
一看就是三合油

68
00:02:48,840 --> 00:02:51,640
然后来点味精

69
00:02:51,640 --> 00:02:53,840
来点盐 盐适量

70
00:02:53,840 --> 00:02:57,280
然后放一个刚才烫的最关键的东西哦

71
00:02:57,280 --> 00:02:59,200
辣椒油要带底子

72
00:02:59,200 --> 00:03:02,720
带点辣椒面

73
00:03:02,720 --> 00:03:04,800
我觉得酱油还要来一点

74
00:03:04,800 --> 00:03:10,400
不够 这个汁儿很关键

75
00:03:10,400 --> 00:03:11,400
好差不多了

76
00:03:11,400 --> 00:03:12,320
家庭里面做菜

77
00:03:12,320 --> 00:03:15,200
咱们要漂漂亮亮的 要漂亮

78
00:03:15,200 --> 00:03:19,240
齐活 多棒 这菜快 还好吃呢

79
00:03:19,240 --> 00:03:22,080
把这个烧椒堆在中间

80
00:03:22,080 --> 00:03:26,120
这个汁 从中间浇 为了好看

81
00:03:26,120 --> 00:03:27,000

82
00:03:27,000 --> 00:03:29,200
都搁里面差不多了

83
00:03:29,200 --> 00:03:31,960
最后那点汁还要淋一圈

84
00:03:31,960 --> 00:03:35,320
要转圈 这样它才有味道

85
00:03:35,320 --> 00:03:37,960
好吃好看

86
00:03:38,960 --> 00:03:41,880
放点葱花在上面

87
00:03:41,880 --> 00:03:43,280
这个菜安逸了

88
00:03:43,280 --> 00:03:46,240
这回不管大爷了我先尝尝 您必须嘞

89
00:03:47,080 --> 00:03:48,520
不会难吃的

90
00:03:49,560 --> 00:03:52,640
一定是好吃的很

91
00:03:53,600 --> 00:03:56,160
他做那汁太香了

92
00:03:56,160 --> 00:04:00,800
小菜 但是做出了浓浓的家乡的味道

93
00:04:00,800 --> 00:04:03,560
烧椒的味 皮蛋的味 汁水的味

94
00:04:03,560 --> 00:04:06,240
融在一起 我跟你说

95
00:04:06,240 --> 00:04:07,480

96
00:04:07,480 --> 00:04:12,480
味道浓你看 料汁辣椒 太香了这个

97
00:04:12,480 --> 00:04:15,760
杨兵下次再搞几个小菜过来

98
00:04:15,760 --> 00:04:20,760
老菜 家乡菜 带过来几个

99
00:04:20,760 --> 00:04:22,200
我爱吃

100
00:04:23,960 --> 00:04:25,640
不是你爱吃 是都爱吃

101
00:04:25,640 --> 00:04:27,640
师父爱吃 这个作业就交得好

102
00:04:27,640 --> 00:04:29,520
这好吃 这真好吃
```

**Comment by 3yearsyoung** [comment]
【国宴大师•烧椒皮蛋】四川经典凉菜烧椒皮蛋，吃一次就上瘾！调汁儿是关键！ |老饭骨
State Banquet Master Chef - Classic Sichuan Cold Dish: Century Eggs with Charred Chillies

简介
小友们好，今天大爷的徒弟杨兵师傅给大家带来最正宗地道的四川经典凉菜——烧椒皮蛋！
Hello everyone! Today, Da Ye’s disciple - Chef Yang Bing is bringing us one of the most authentic classic Sichuan local cold dishes: century eggs with charred chillies!
这个烧椒皮蛋，做法非常简单，家常又下饭，学会了调汁儿的手法，用来调制其他凉菜也很美味！
This dish is extremely easy to cook, and best served with rice at home. The sauce used in this dish also goes very well with other cold dishes as long as you master the techniques of making it! 
烧椒的味儿，皮蛋的味儿和特制酱汁的味道，小小的凉菜也能吃出浓浓家乡的感觉。
The flavours of charred chillies, century eggs and the special sauce from this small plate bring out such a rich and strong taste of Sichuan
小友们还在等什么？快点击视频一起来学习如何做这道经典开胃小菜吧！
So, what are you waiting for? Watch the video and let’s learn how to make this classic starter!

字幕
1
00:00:00,000 --> 00:00:02,240
今天做啥子菜
What are you cooking today?

2
00:00:02,240 --> 00:00:04,640
你看么 皮蛋
As you can see, century eggs

3
00:00:04,640 --> 00:00:05,880
做一个烧椒皮蛋
I’m going to make century eggs with charred chillies

4
00:00:05,880 --> 00:00:08,560
其实这个烧就是这么玩的 非常简单
That’s how you char the chillies, very easy

5
00:00:08,560 --> 00:00:10,480
好吃好看
It looks gorgeous and tastes great

6
00:00:10,480 --> 00:00:16,000

7
00:00:16,000 --> 00:00:18,160
我第一步先要烫一点红油
Firstly, I need to make some red chilli oil

8
00:00:18,800 --> 00:00:21,080
四川啥子的地方的菜
Where does this dish come from in Sichuan?

9
00:00:21,080 --> 00:00:23,320
在成都做的这个菜比较多一点
It’s most commonly seen in Chengdu

10
00:00:23,320 --> 00:00:25,080
重庆也在做 内江也在做
You can also find it in Chongqing and Neijiang

11
00:00:25,080 --> 00:00:26,160
这个东西都一样
The method is all the same

12
00:00:26,160 --> 00:00:27,920
只是他们采用的这个东西
But the ingredients used in this recipe

13
00:00:27,920 --> 00:00:29,840
各有千秋不一样
Can be varied in different regions

14
00:00:29,840 --> 00:00:32,080
咱们这个用的是线椒
Here, we opt for these long chillies

15
00:00:32,080 --> 00:00:35,480
线椒肉比较厚 它会有脆脆的口感
The flesh is comparatively thicker, which will give us the crunchy texture

16
00:00:35,480 --> 00:00:38,240
这个是用的二荆条的（辣椒面）
These crushed chillies are made from Erjingtiao chilli peppers

17
00:00:38,240 --> 00:00:41,160
差不多油温合适就呲一下
We will sizzle them when the oil temperate is right

18
00:00:41,160 --> 00:00:44,640
然后还是一样 加一点凉油
As usual, add some cold oil first

19
00:00:44,640 --> 00:00:46,600
简单一些
It makes things simpler

20
00:00:46,600 --> 00:00:48,280
我这又放了点凉油
I have added some more cold oil

21
00:00:48,280 --> 00:00:51,840
免的辣椒面等会糊了
To prevent the chillies from getting burnt

22
00:00:51,840 --> 00:00:55,480
油温烧起来大概差不多六成左右
The oil is about 60 percent hot (180 degree centigrade)

23
00:00:55,480 --> 00:00:57,360
先少倒一点进去
Add a little bit in first

24
00:00:58,520 --> 00:01:01,400
差不多合适 就把它倒进去
Pour the rest of the oil into the bowl when you feel comfortable

25
00:01:01,400 --> 00:01:05,400
然后放一点醋把味道激发出来
Then add some vinegar to bring out the flavour

26
00:01:05,400 --> 00:01:08,600
看一下 呲辣椒油搁点醋
Look, sizzling chilli oil with vinegar

27
00:01:08,600 --> 00:01:10,120
一个是香
It’s so fragrant

28
00:01:10,120 --> 00:01:13,120
让味道释放的更加充分些
And the flavour is being fully released

29
00:01:13,120 --> 00:01:14,640
还有一个一会儿这个辣椒
In the meantime, the chilli oil will be able

30
00:01:14,640 --> 00:01:16,160
它能扒到菜上
To be captured by other ingredients when plating the dish

31
00:01:16,160 --> 00:01:17,720
放那儿
Put it there

32
00:01:17,720 --> 00:01:19,360
现在我来烧椒
Now, let’s char the chillies

33
00:01:19,360 --> 00:01:22,200
辣椒稍微串一下
Skewer these chillies first

34
00:01:22,200 --> 00:01:23,720
其实这个烧就是这么玩的
That’s how you char the chillies

35
00:01:23,720 --> 00:01:27,320
在农村里面把辣椒直接放在
In the countryside, we normally just put the chillies

36
00:01:27,320 --> 00:01:30,400
烧完膛火的炉灰 柴火灰
Directly on the embers from the wood fire oven

37
00:01:30,400 --> 00:01:32,640
直接把辣椒扔进去就好了
Just throw them in there until done

38
00:01:32,640 --> 00:01:35,080
让它这样烧 烧出虎皮
Char them like this to get the slightly burnt skins

39
00:01:35,080 --> 00:01:36,800
它里面同时也熟了
It also cooks the flesh inside at the same time

40
00:01:37,600 --> 00:01:41,520
起虎皮了 待会把虎皮去掉 把皮撕掉
The skins are slightly burnt now, which will be removed later

41
00:01:42,760 --> 00:01:44,200
其实还有一种方法
There is actually another method

42
00:01:44,200 --> 00:01:46,040
也可以在锅里面去焙
That you can toast the chillies in the pan

43
00:01:46,040 --> 00:01:48,760
锅里面什么都不放就干的 干焙
Just dry toast them without adding anything else

44
00:01:48,760 --> 00:01:50,600
但是它没有这种燎的香
But the chillies wouldn’t be as fragrant as what we are getting here

45
00:01:50,600 --> 00:01:52,400
燎的时候它起了虎皮之后
After the skins are slight burnt

46
00:01:52,400 --> 00:01:56,200
还是要有点余温 让它稍微熟一点
Keep them warm so they can be properly cooked

47
00:01:56,200 --> 00:01:59,040
别到时候辣椒会有点生
In case the flesh is still raw

48
00:01:59,040 --> 00:02:01,240
好了 巴适的很
Done! Fantastic!

49
00:02:01,240 --> 00:02:04,200
你看现在拿刀稍微把它刮掉
Now roughly remove the skins with a knife

50
00:02:04,200 --> 00:02:06,240
不用刮的太干净 刮的时候
You don’t need to remove them completely

51
00:02:06,240 --> 00:02:09,040

52
00:02:09,040 --> 00:02:11,240
直接这样我切长一点
Julienne the chillies like this

53
00:02:11,240 --> 00:02:13,120
其实手撕也行
You can also rip them apart by hand

54
00:02:13,120 --> 00:02:17,600
你看线椒这个香啊 清香嘞
The fragrance of these long chillies is extraordinary. So fresh!

55
00:02:17,600 --> 00:02:20,440
这就是比锅里焙的香啊
They are much more fragrant than those toasted in the pan

56
00:02:20,440 --> 00:02:22,400
对 就是燎的它比较香一点
Indeed. The charred ones smell so much better

57
00:02:22,400 --> 00:02:25,080
准备好了 然后现在就是调汁
They are ready now. Let’s move on to making the sauce

58
00:02:25,080 --> 00:02:27,560
这个菜调汁是关键 非常简单
The sauce is key for this dish. It’s very easy to make

59
00:02:27,560 --> 00:02:29,760
姜末 大概有个二十克左右
About 20g of crushed ginger

60
00:02:29,760 --> 00:02:32,960
蒜末也差不多
Same amount of crushed garlic

61
00:02:32,960 --> 00:02:35,400
香油 来一点点的香油
A touch of sesame oil

62
00:02:35,400 --> 00:02:37,440
这个不要太多
Don’t add too much of this

63
00:02:37,440 --> 00:02:38,800
然后再来点花椒油
Then some Sichuan pepper oil

64
00:02:38,800 --> 00:02:40,640
稍微比香油要多一点
Slightly more than the sesame oil

65
00:02:40,640 --> 00:02:44,800
米醋 一勺 一勺半
One and half spoons of rice vinegar

66
00:02:44,800 --> 00:02:47,440
酱油 也是一勺半差不多吧
Soy sauce, one and half spoons as well

67
00:02:47,440 --> 00:02:48,840
一看就是三合油
The typical Sanheyou (a sauce made from sesame oil, soy sauce and vinegar)

68
00:02:48,840 --> 00:02:51,640
然后来点味精
Then, a bit MSG

69
00:02:51,640 --> 00:02:53,840
来点盐 盐适量
Some salt, to taste

70
00:02:53,840 --> 00:02:57,280
然后放一个刚才烫的最关键的东西哦
And of course, the most essential ingredient we made earlier

71
00:02:57,280 --> 00:02:59,200
辣椒油要带底子
The red chilli oil including the chillies in it

72
00:02:59,200 --> 00:03:02,720
带点辣椒面
The crushed chillies

73
00:03:02,720 --> 00:03:04,800
我觉得酱油还要来一点
I think we need some extra soy sauce

74
00:03:04,800 --> 00:03:10,400
不够 这个汁儿很关键
It’s not enough. The sauce is so important

75
00:03:10,400 --> 00:03:11,400
好差不多了
Alright, that’s it

76
00:03:11,400 --> 00:03:12,320
家庭里面做菜
When you cook at home

77
00:03:12,320 --> 00:03:15,200
咱们要漂漂亮亮的 要漂亮
The dish shall be beautifully presented. They must look nice

78
00:03:15,200 --> 00:03:19,240
齐活 多棒 这菜快 还好吃呢
All assembled. How good! This is a quick and easy recipe, and it’s delicious

79
00:03:19,240 --> 00:03:22,080
把这个烧椒堆在中间
Pile up the charred chillies in the middle

80
00:03:22,080 --> 00:03:26,120
这个汁 从中间浇 为了好看
Pour the sauce also from the middle for better presentation

81
00:03:26,120 --> 00:03:27,000

82
00:03:27,000 --> 00:03:29,200
都搁里面差不多了
Put most of the sauce there

83
00:03:29,200 --> 00:03:31,960
最后那点汁还要淋一圈
Save the last bit to drizzle around the plate

84
00:03:31,960 --> 00:03:35,320
要转圈 这样它才有味道
Circle like this, so the sauce is fully incorporated into the dish

85
00:03:35,320 --> 00:03:37,960
好吃好看
It looks gorgeous and tastes great

86
00:03:38,960 --> 00:03:41,880
放点葱花在上面
Sprinkle some spring onions on the top

87
00:03:41,880 --> 00:03:43,280
这个菜安逸了
This dish is now served

88
00:03:43,280 --> 00:03:46,240
这回不管大爷了我先尝尝 您必须嘞
I’ll tuck in first before Da Ye this time. Of course, help yourself

89
00:03:47,080 --> 00:03:48,520
不会难吃的
It won’t taste bad

90
00:03:49,560 --> 00:03:52,640
一定是好吃的很
It must taste amazing

91
00:03:53,600 --> 00:03:56,160
他做那汁太香了
The sauce he made is so aromatic

92
00:03:56,160 --> 00:04:00,800
小菜 但是做出了浓浓的家乡的味道
It’s a small dish, but it brings out a rich and strong Sichuan flavour

93
00:04:00,800 --> 00:04:03,560
烧椒的味 皮蛋的味 汁水的味
The flavours of charred chillies, century eggs and the sauce

94
00:04:03,560 --> 00:04:06,240
融在一起 我跟你说
When you combine them together, let me tell you

95
00:04:06,240 --> 00:04:07,480

96
00:04:07,480 --> 00:04:12,480
味道浓你看 料汁辣椒 太香了这个
Yes, the flavour is so rich. Look at the sauce and chillies. It’s absolutely brilliant!

97
00:04:12,480 --> 00:04:15,760
杨兵下次再搞几个小菜过来
Bring us some more small dishes next time, Yang Bing

98
00:04:15,760 --> 00:04:20,760
老菜 家乡菜 带过来几个
Traditional Sichuan local dishes. Just bring them here

99
00:04:20,760 --> 00:04:22,200
我爱吃
I simply love them

100
00:04:23,960 --> 00:04:25,640
不是你爱吃 是都爱吃
It’s not just you, but we all love them

101
00:04:25,640 --> 00:04:27,640
师父爱吃 这个作业就交得好
As long as the master loves it, I consider my job well done

102
00:04:27,640 --> 00:04:29,520
这好吃 这真好吃
This is tasty, this is SO tasty!
