### ISSUE TITLE
[雪鱼探店] 福建特色芋圆 - https://www.youtube.com/watch?v=jCFgtZlEuN8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#160]
https://www.youtube.com/watch?v=jCFgtZlEuN8

发布日期 2019 年 9 月 6 日

**Comment by okiamnewhere** [comment]
添加字幕文件，
感谢您的辛苦翻译，辛苦啦。
1 
00:00:01,920 --> 00:00:04,920
福建·晋江

2 
00:00:14,880 --> 00:00:17,040
登场

3 
00:00:34,760 --> 00:00:37,120
是不是应该到那边排队

4 
00:00:37,120 --> 00:00:39,000
不用排队 在这边拿就行

5 
00:00:41,400 --> 00:00:45,200
第一屉芋圆出来的时候 我们都没有等到

6 
00:00:45,200 --> 00:00:47,600
现在是第二屉

7 
00:00:47,800 --> 00:00:49,520
每一屉芋圆有84个

8 
00:00:49,520 --> 00:00:51,680
这个芋圆的个头 可不算很大

9 
00:00:51,680 --> 00:00:54,960
所以每个人来买 可不是一两个的事

10 
00:00:57,160 --> 00:00:58,120
虽然说 来的时候

11 
00:00:58,120 --> 00:01:00,200
我们没有看到很多人在排队

12 
00:01:00,200 --> 00:01:02,280
但是这个屋里是坐满人的

13 
00:01:02,600 --> 00:01:04,960
很多长辈都是在这儿说着 笑着

14 
00:01:04,960 --> 00:01:07,120
等着第一屉出来

15 
00:01:21,080 --> 00:01:24,560
很多都是打包带走吃的

16 
00:01:35,520 --> 00:01:37,560
离我的芋圆又近了一步

17 
00:01:46,840 --> 00:01:49,760
你好 我要4个芋圆 再加一个肉汤

18 
00:01:50,920 --> 00:01:52,120
对

19 
00:01:53,320 --> 00:01:55,160
对 在这边吃

20 
00:02:25,760 --> 00:02:28,800
收款成功22元

21 
00:02:33,520 --> 00:02:36,880
这个芋圆不是像我们以前吃的甜品

22 
00:02:36,880 --> 00:02:39,480
那种芋头加木薯粉的芋圆

23 
00:02:39,480 --> 00:02:41,440
而是肉的芋圆

24 
00:02:41,440 --> 00:02:42,720
3块钱一粒

25 
00:02:42,720 --> 00:02:43,720
这里面是4个

26 
00:02:43,720 --> 00:02:45,600
上面 刚才那个那个小姐姐说

27 
00:02:45,600 --> 00:02:48,000
上面加的是花生碎 所以说

28 
00:02:48,000 --> 00:02:49,720
可能 还会有甜的口感

29 
00:02:52,400 --> 00:02:54,840
芋圆看上去很晶莹 看到没

30 
00:02:55,320 --> 00:02:56,280
哇

31 
00:02:56,560 --> 00:02:59,320
一夹就把肉馅给夹出来了

32 
00:03:00,080 --> 00:03:04,160
这个闻着感觉很香 有这种肉香味

33 
00:03:04,160 --> 00:03:08,240
芋圆

34 
00:03:14,200 --> 00:03:15,880
它这个里面不是肉馅

35 
00:03:15,880 --> 00:03:18,680
是这种肉团 肉块的状态

36 
00:03:23,360 --> 00:03:26,680
它这个外面有点黏牙 有点弹口

37 
00:03:26,680 --> 00:03:30,000
但是里面的肉是真香

38 
00:03:31,320 --> 00:03:33,600
外面撒的是糖粉和花生碎

39 
00:03:33,920 --> 00:03:37,480
所以说 它是一种咸 甜的结合

40 
00:03:42,440 --> 00:03:44,400
我还是第一次吃这种口感

41 
00:03:45,600 --> 00:03:47,280
很奇妙

42 
00:03:47,280 --> 00:03:47,880
很 奇妙

43 
00:03:47,880 --> 00:03:50,680
很 奇妙

44 
00:04:04,000 --> 00:04:07,560
芋圆是干吃的 所以咱们配了一碗汤

45 
00:04:07,560 --> 00:04:09,800
这个汤里都是瘦肉

46 
00:04:12,680 --> 00:04:15,640
里面差不多有4块肉

47 
00:04:21,520 --> 00:04:23,560
这个就是吃肉 喝汤

48 
00:04:23,560 --> 00:04:26,360
它这个肉都是这种大块的

49 
00:04:26,600 --> 00:04:29,520
让人看着就想把它撕咬掉

50 
00:04:33,680 --> 00:04:35,880
阿姨 这个店开多久了

51 
00:04:35,880 --> 00:04:38,560
很久了

52 
00:04:38,560 --> 00:04:39,600
上百年了

53 
00:04:39,600 --> 00:04:43,000
我看很多都是买着回家吃 带走吃

54 
00:04:43,000 --> 00:04:46,040
有的买回家吃 有的在这里吃

55 
00:04:48,760 --> 00:04:50,200
很多人过来拍过吧

56 
00:04:50,200 --> 00:04:51,640
很多人拍过 到时候要评论

57 
00:04:51,640 --> 00:04:53,320
我给你讲 如果有人在评论里说

58 
00:04:53,320 --> 00:04:55,000
态度不好 态度不好 态度不好

59 
00:04:55,000 --> 00:04:56,960
你们要说 这是历史 以前的事情

60 
00:04:56,960 --> 00:04:59,280
现在哪里会 你们来 态度哪里不好

61 
00:04:59,280 --> 00:05:04,680
早几年确实 因为是老人家在做

62 
00:05:04,680 --> 00:05:06,960
老人在卖的

63 
00:05:08,800 --> 00:05:11,160
现在还没到点 到点忙的时候

64 
00:05:11,160 --> 00:05:12,760
人密密麻麻的

65 
00:05:12,760 --> 00:05:15,280
你没大声 讲不了

66 
00:05:15,280 --> 00:05:16,560
尤其像你们是第一次来

67 
00:05:16,560 --> 00:05:18,320
你们也不知道怎么点吧

68 
00:05:18,320 --> 00:05:18,560
对

69 
00:05:18,560 --> 00:05:20,000
对不对 不懂怎么点

70 
00:05:20,000 --> 00:05:22,200
我要问你说 你们要吃什么

71 
00:05:22,200 --> 00:05:24,640
你们就在那儿傻傻的 不知道点什么

72 
00:05:24,640 --> 00:05:26,280
那好了 我们就先卖别人

73 
00:05:26,280 --> 00:05:29,120
哇 我都先来 你没给我 你卖给别人

74 
00:05:29,120 --> 00:05:31,760
其实那时候 密密麻麻的人 没办法

75 
00:05:31,760 --> 00:05:34,880
如果在一个人身上耗费时间太多

76 
00:05:34,880 --> 00:05:37,840
耗费一两分钟 那其他人全部堵死掉了

77 
00:05:37,840 --> 00:05:40,800
现在很多人说 没有以前的好吃

78 
00:05:40,800 --> 00:05:42,800
是啊 现在食材

79 
00:05:42,800 --> 00:05:44,880
现在猪肉有以前的猪肉好吃吗

80 
00:05:44,880 --> 00:05:46,000
对不对

81 
00:05:47,320 --> 00:05:49,440
就怪食材这些

82 
00:05:49,440 --> 00:05:52,360
做 这个如果没有用心继续做

83 
00:05:52,360 --> 00:05:54,760
不可能开那么久呢 开五六十年呢

84 
00:05:54,760 --> 00:05:55,880
对不对

85 
00:05:55,880 --> 00:05:57,560
只是说 态度是一样的

86 
00:05:57,560 --> 00:06:00,720
但是 现在是食材的问题

87 
00:06:04,040 --> 00:06:06,000
和大哥聊天的时候你会发现

88 
00:06:06,000 --> 00:06:08,680
他的求生欲 还是很强的

89 
00:06:08,840 --> 00:06:10,600
最后呢 就是要补充一点

90 
00:06:10,600 --> 00:06:12,080
芋圆有两种吃法

91 
00:06:12,080 --> 00:06:14,520
可以像我这样 加花生碎来吃

92 
00:06:16,120 --> 00:06:18,880
还有一种就是和瘦肉汤 和骨头汤搭配

93 
00:06:19,040 --> 00:06:21,800
这个味道我不知道 我是后来才听说的

94 
00:06:21,800 --> 00:06:24,560
但是不同的吃法 不同的享受吧

95 
00:06:25,280 --> 00:06:27,040
好了 今天的视频就到这儿

96 
00:06:27,040 --> 00:06:28,800
 ( ^_^ )/~~拜拜

97 
00:06:37,480 --> 00:06:40,480
关 注
雪 鱼 探 店
