### ISSUE TITLE
[老饭骨] 摔萝卜炖羊排- https://youtu.be/N4aolRJ-LxA

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#1674]
**视频链接**：https://youtu.be/N4aolRJ-LxA

<备注内容，如视频时长、发布日期等等（如果无需备注，请删除此行）>

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•摔萝卜炖羊排】汤清肉鲜!简单必学的一道摔萝卜炖羊排，20分钟出锅!|老饭骨

简介
小友们好，大家在评论区一直要老饭骨做的炖羊排来了！
这次由二伯掌勺，教小友们快速做出一锅汤清肉鲜、营养丰富的摔萝卜炖羊排。
快速鸡汤的做法大家伙可以参考之前的【国宴鸡豆花】视频https://youtu.be/IKCLukES7-s
摔出来的萝卜里面的纤维更开，比直接切出来的萝卜更加入味。最后加入焯过的虫草花和枸杞，喝汤吃肉，冬季养生就看这锅汤了！

字幕
1
00:00:00,000 --> 00:00:02,000

2
00:00:02,000 --> 00:00:04,160
摔萝卜炖羊排 好了

3
00:00:04,160 --> 00:00:10,120

4
00:00:10,120 --> 00:00:12,720
羊排冷水下锅 煮它一煮

5
00:00:12,720 --> 00:00:14,080
热水一下闷死了

6
00:00:14,080 --> 00:00:16,360
那些浮沫子 那些脏东西

7
00:00:16,360 --> 00:00:17,680
慢慢就出来了

8
00:00:17,680 --> 00:00:19,320
我们把沫子打掉了就干净了

9
00:00:19,320 --> 00:00:21,360
搁酒 搁点葱姜

10
00:00:21,360 --> 00:00:22,920
我这个比较奇特

11
00:00:22,920 --> 00:00:26,160
摔萝卜羊排 我把这萝卜给摔了

12
00:00:26,160 --> 00:00:27,280
看您怎么摔

13
00:00:27,280 --> 00:00:28,440
你看大爷啊

14
00:00:28,440 --> 00:00:30,280

15
00:00:30,280 --> 00:00:30,920
酥了么

16
00:00:30,920 --> 00:00:32,040
完全酥了您看

17
00:00:32,040 --> 00:00:34,120
这纤维全开了

18
00:00:34,120 --> 00:00:36,480
比直接切更加入味了 对

19
00:00:36,480 --> 00:00:39,560
你看一磕就掉 劈柴块

20
00:00:39,560 --> 00:00:40,840

21
00:00:40,840 --> 00:00:42,520
（萝卜）飞水 搁块冰糖

22
00:00:42,520 --> 00:00:44,240
冰糖 你不管多臭的萝卜

23
00:00:44,240 --> 00:00:45,280
只要搁上冰糖

24
00:00:45,280 --> 00:00:47,000
萝卜（臭）味就没了

25
00:00:47,000 --> 00:00:47,920
摔萝卜羊排

26
00:00:47,920 --> 00:00:50,720
这个季节正好吃羊肉跟萝卜

27
00:00:50,720 --> 00:00:53,680
就说这羊肉做完的汤我就不要了

28
00:00:53,680 --> 00:00:55,280
换上清鸡汤

29
00:00:55,280 --> 00:00:58,680
鸡汤喝着倍儿鲜 肉吃着倍儿香

30
00:00:58,680 --> 00:01:00,800
好了 捞高压锅里头吧

31
00:01:00,800 --> 00:01:01,960

32
00:01:02,640 --> 00:01:04,080
小料洗一下

33
00:01:04,080 --> 00:01:07,320
小茴香 白胡椒粒 花椒 当归

34
00:01:07,320 --> 00:01:09,840
把这沙子稍微冲一冲就行了

35
00:01:09,840 --> 00:01:11,360

36
00:01:11,360 --> 00:01:12,920
然后再搁点姜葱

37
00:01:12,920 --> 00:01:15,880

38
00:01:15,880 --> 00:01:18,600
压上 让它熟的更快 二十五分钟

39
00:01:18,600 --> 00:01:22,680

40
00:01:22,680 --> 00:01:23,840
萝卜出锅

41
00:01:23,840 --> 00:01:26,240
摔的跟切的感觉不一样

42
00:01:26,240 --> 00:01:27,800
它特别面乎

43
00:01:27,800 --> 00:01:29,040
那边压着东西

44
00:01:29,040 --> 00:01:31,480
我把汤清出来就齐了

45
00:01:31,520 --> 00:01:36,080
黄酒 鸡腻子 来点清汤

46
00:01:36,080 --> 00:01:37,280
一般的来不及吊汤的

47
00:01:37,280 --> 00:01:39,480
就这种应急的

48
00:01:39,480 --> 00:01:41,720
省去了吊汤的这功夫

49
00:01:41,720 --> 00:01:43,920
而且效果是一样的 快速鸡汤

50
00:01:43,920 --> 00:01:47,480
撒点白胡椒粉 葱姜盐

51
00:01:47,480 --> 00:01:48,960
虫草花焯水

52
00:01:48,960 --> 00:01:53,240
羊排一熟 这鸡汤一得就完活

53
00:01:53,240 --> 00:01:58,240
水开了 鸡蓉下锅

54
00:01:58,240 --> 00:02:00,560
攒起来 你看攒个窝儿转

55
00:02:00,560 --> 00:02:02,080

56
00:02:02,080 --> 00:02:04,840
你看 这儿一个漩涡

57
00:02:05,920 --> 00:02:09,760
旋旋旋 东西都旋在一块去了

58
00:02:09,760 --> 00:02:12,000

59
00:02:12,240 --> 00:02:13,280
开始慢慢的出沫子了

60
00:02:13,280 --> 00:02:14,520
渗透出沫子了

61
00:02:14,520 --> 00:02:16,920
小魏在渗透沫子的同时呢

62
00:02:16,920 --> 00:02:18,880
比如要开锅

63
00:02:18,880 --> 00:02:21,280
要大开的时候你就拧小火

64
00:02:21,280 --> 00:02:23,520
不能大开 一大开就完了

65
00:02:23,520 --> 00:02:26,680
小火 拧小点 火不能大

66
00:02:26,680 --> 00:02:28,240
似开非开的时候

67
00:02:28,240 --> 00:02:31,320
这样这沫子它就不浑了

68
00:02:31,320 --> 00:02:33,240

69
00:02:33,240 --> 00:02:35,640
这样可以下第二次了

70
00:02:35,640 --> 00:02:40,160

71
00:02:40,160 --> 00:02:42,200
大火再顶一下

72
00:02:42,200 --> 00:02:43,640
让它开着 似开非开

73
00:02:43,640 --> 00:02:46,560
你要不顶它那沫子出不来

74
00:02:46,560 --> 00:02:48,800
这沫子不出去这汤清不了

75
00:02:48,800 --> 00:02:52,600
再稍微小一点 还得让它开

76
00:02:52,600 --> 00:02:56,520

77
00:02:56,520 --> 00:02:59,320
行了 第三遍

78
00:02:59,320 --> 00:03:02,080

79
00:03:02,080 --> 00:03:02,920
不能有沫子

80
00:03:02,920 --> 00:03:06,280
大爷讲话 叫清澈见底

81
00:03:06,280 --> 00:03:09,960
关火 你看这汤

82
00:03:09,960 --> 00:03:11,560
沉下去了

83
00:03:11,560 --> 00:03:13,520
经过三遍扫之后

84
00:03:13,520 --> 00:03:15,160
汤非常香

85
00:03:15,160 --> 00:03:18,640
羊排也好了 出锅吧

86
00:03:18,640 --> 00:03:20,440
二十五分钟又闷了十分钟

87
00:03:20,440 --> 00:03:22,840

88
00:03:22,840 --> 00:03:23,920
没味儿 咱调个味儿吧

89
00:03:23,920 --> 00:03:27,920
给点盐 白胡椒粉 黄酒

90
00:03:27,920 --> 00:03:29,840

91
00:03:32,280 --> 00:03:33,800
我得把肉捞出来

92
00:03:33,800 --> 00:03:35,280
大爷 这萝卜摔完了

93
00:03:35,280 --> 00:03:36,880
刚才我尝了一块

94
00:03:36,880 --> 00:03:39,880
把纤维组织全给摔烂了

95
00:03:39,880 --> 00:03:42,920
吃起来绵软了 而且特别嫩

96
00:03:42,920 --> 00:03:46,280
好了 把清好的鸡汤

97
00:03:46,280 --> 00:03:47,760
倒进去了

98
00:03:47,760 --> 00:03:50,600
鲜啊 再来点

99
00:03:50,600 --> 00:03:52,720

100
00:03:52,720 --> 00:03:54,040
开锅就得

101
00:03:54,040 --> 00:03:56,520
虫草花 然后枸杞子

102
00:03:56,520 --> 00:03:58,080
一道大菜行了

103
00:03:58,080 --> 00:04:01,520
为什么是拆解 把这个菜拆解做

104
00:04:01,520 --> 00:04:04,680
你看肉先压

105
00:04:04,680 --> 00:04:06,720
压完之后你看 淡淡的香料

106
00:04:06,720 --> 00:04:08,280
又吃不出香料味 肉很香

107
00:04:08,280 --> 00:04:09,600
然后再调味

108
00:04:09,600 --> 00:04:10,840
调味之后 清好的鸡汤

109
00:04:10,840 --> 00:04:12,040
我们再合在一起

110
00:04:12,040 --> 00:04:14,720
然后喝着汤吃着肉

111
00:04:14,720 --> 00:04:15,920
如果肉要不够味

112
00:04:15,920 --> 00:04:17,200
我们还可以自己

113
00:04:17,200 --> 00:04:19,600
自行喜欢 调个汁

114
00:04:19,600 --> 00:04:21,040
香菜末 小米辣

115
00:04:21,040 --> 00:04:22,040
然后我们再搁点豉油

116
00:04:22,040 --> 00:04:24,000
拿小油一呲 搁点小葱花 

117
00:04:24,000 --> 00:04:27,200
蘸点汁 别有一番风味

118
00:04:27,200 --> 00:04:29,600
摔萝卜炖羊排 好了

119
00:04:29,600 --> 00:04:31,400

120
00:04:31,400 --> 00:04:32,160
大爷您看

121
00:04:32,160 --> 00:04:34,360
还在咕嘟咕嘟冒着泡儿呢

122
00:04:34,360 --> 00:04:37,240
汤清味美

123
00:04:37,680 --> 00:04:39,360

124
00:04:39,360 --> 00:04:40,360
看看萝卜

125
00:04:40,360 --> 00:04:43,600

126
00:04:43,600 --> 00:04:44,640
摔的酥烂

127
00:04:44,640 --> 00:04:59,280

128
00:04:59,280 --> 00:04:59,840
是吧大爷

129
00:04:59,840 --> 00:05:00,720
这汤鲜吧

130
00:05:00,720 --> 00:05:02,280
这个萝卜摔完了

131
00:05:02,280 --> 00:05:03,680
效果就跟切的不一样

```

**Comment by glasscatfish** [comment]
认领

**Comment by glasscatfish** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•摔萝卜炖羊排】汤清肉鲜!简单必学的一道摔萝卜炖羊排，20分钟出锅!|老饭骨
【State Banquet Master Chef• Smashed radish and lamb rib stew】one must learn, only take 20 minutes!

简介
小友们好，大家在评论区一直要老饭骨做的炖羊排来了！
这次由二伯掌勺，教小友们快速做出一锅汤清肉鲜、营养丰富的摔萝卜炖羊排。
快速鸡汤的做法大家伙可以参考之前的【国宴鸡豆花】视频https://youtu.be/IKCLukES7-s
摔出来的萝卜里面的纤维更开，比直接切出来的萝卜更加入味。最后加入焯过的虫草花和枸杞，喝汤吃肉，冬季养生就看这锅汤了！
Hello! We are making stewed lamb ribs that you requested in the comment area!
Today, Er Bai is taking over to teach you a tasty and nutritious dish: Smashed radish and lamb rib stew.
For more details on making “instant” chicken broth, you could refer to 【State Banquet Ji Douhua (Chicken tofu pudding)】 Link: https://youtu.be/IKCLukES7-s
Smashing the radish breaks its fiber, so it absorbs more flavour than just cutting it. Add blanched cordyceps flower and goji berry at the end to make it nutritious, it’s a great stew to have in winter!


字幕
1
00:00:00,000 --> 00:00:02,000

2
00:00:02,000 --> 00:00:04,160
摔萝卜炖羊排 好了
Smashed radish and lamb rib stew. done!

3
00:00:04,160 --> 00:00:10,120

4
00:00:10,120 --> 00:00:12,720
羊排冷水下锅 煮它一煮
Put lamb ribs in cold water and blanch it

5
00:00:12,720 --> 00:00:14,080
热水一下闷死了
Hot water prevent the impurities from coming out

6
00:00:14,080 --> 00:00:16,360
那些浮沫子 那些脏东西
Impurities in the meat comes out 

7
00:00:16,360 --> 00:00:17,680
慢慢就出来了
slowly

8
00:00:17,680 --> 00:00:19,320
我们把沫子打掉了就干净了
Let’s skim it to make it clean

9
00:00:19,320 --> 00:00:21,360
搁酒 搁点葱姜
Add some huangjiu rice wine, green onion and ginger

10
00:00:21,360 --> 00:00:22,920
我这个比较奇特
This is unique

11
00:00:22,920 --> 00:00:26,160
摔萝卜羊排 我把这萝卜给摔了
I smash the radish 

12
00:00:26,160 --> 00:00:27,280
看您怎么摔
I’ll watch how you do it

13
00:00:27,280 --> 00:00:28,440
你看大爷啊
Look at Da Ye

14
00:00:28,440 --> 00:00:30,280

15
00:00:30,280 --> 00:00:30,920
酥了么
Is it broken yet?

16
00:00:30,920 --> 00:00:32,040
完全酥了您看
Absolutely! Have a look!

17
00:00:32,040 --> 00:00:34,120
这纤维全开了
All the fibers are broken

18
00:00:34,120 --> 00:00:36,480
比直接切更加入味了 对
Smashing it lets it absorbs more flavours than cutting it

19
00:00:36,480 --> 00:00:39,560
你看一磕就掉 劈柴块
Look! It breaks if you split it like this. Split cut.

20
00:00:39,560 --> 00:00:40,840

21
00:00:40,840 --> 00:00:42,520
（萝卜）飞水 搁块冰糖
Blanch the radish with some rock sugar

22
00:00:42,520 --> 00:00:44,240
冰糖 你不管多臭的萝卜
Nomatter how stinky the radish is

23
00:00:44,240 --> 00:00:45,280
只要搁上冰糖
As long as you add rock sugar

24
00:00:45,280 --> 00:00:47,000
萝卜（臭）味就没了
The stinkiness of the radish will be removed

25
00:00:47,000 --> 00:00:47,920
摔萝卜羊排
Smashed radish and lamb ribs

26
00:00:47,920 --> 00:00:50,720
这个季节正好吃羊肉跟萝卜
This is a great season the have lamb and radish

27
00:00:50,720 --> 00:00:53,680
就说这羊肉做完的汤我就不要了
Discard the liquid from blanching the lamb

28
00:00:53,680 --> 00:00:55,280
换上清鸡汤
Add in chicken broth

29
00:00:55,280 --> 00:00:58,680
鸡汤喝着倍儿鲜 肉吃着倍儿香
Chicken broth gives it more flavour, the meat tastes better too

30
00:00:58,680 --> 00:01:00,800
好了 捞高压锅里头吧
Ready! Let’s put them in the pressure cooker.

31
00:01:00,800 --> 00:01:01,960

32
00:01:02,640 --> 00:01:04,080
小料洗一下
Rinse the spices

33
00:01:04,080 --> 00:01:07,320
小茴香 白胡椒粒 花椒 当归
Fennel seed, white peppercorn, sichuan peppercorn, angelica sinensis

34
00:01:07,320 --> 00:01:09,840
把这沙子稍微冲一冲就行了
Rins off the sand

35
00:01:09,840 --> 00:01:11,360

36
00:01:11,360 --> 00:01:12,920
然后再搁点姜葱
Add some ginger and green onion

37
00:01:12,920 --> 00:01:15,880

38
00:01:15,880 --> 00:01:18,600
压上 让它熟的更快 二十五分钟
Cook it with the pressure cooker so it cooks faster, 25 minutes. 

39
00:01:18,600 --> 00:01:22,680

40
00:01:22,680 --> 00:01:23,840
萝卜出锅
Remove the radish from the pot

41
00:01:23,840 --> 00:01:26,240
摔的跟切的感觉不一样
Smashed radish are different from cut ones

42
00:01:26,240 --> 00:01:27,800
它特别面乎
It’s softer

43
00:01:27,800 --> 00:01:29,040
那边压着东西
While the lamb is cooking

44
00:01:29,040 --> 00:01:31,480
我把汤清出来就齐了
I’ll make the broth

45
00:01:31,520 --> 00:01:36,080
黄酒 鸡腻子 来点清汤
huangjiu rice wine, ground chicken breast, clear broth

46
00:01:36,080 --> 00:01:37,280
一般的来不及吊汤的
If you don’t have enough time to make broth

47
00:01:37,280 --> 00:01:39,480
就这种应急的
Use this ‘instant’ chicken broth

48
00:01:39,480 --> 00:01:41,720
省去了吊汤的这功夫
It saves the time for make real broth

49
00:01:41,720 --> 00:01:43,920
而且效果是一样的 快速鸡汤
It serves the same purpose

50
00:01:43,920 --> 00:01:47,480
撒点白胡椒粉 葱姜盐
Sprinkle some white pepper, ginger, green onion, and salt

51
00:01:47,480 --> 00:01:48,960
虫草花焯水
Blanch the cordyceps flower

52
00:01:48,960 --> 00:01:53,240
羊排一熟 这鸡汤一得就完活
Once the lamb rib is cooked, the broth is made, it’s almost done. 

53
00:01:53,240 --> 00:01:58,240
水开了 鸡蓉下锅
Water is boiling, add ground chicken mixture

54
00:01:58,240 --> 00:02:00,560
攒起来 你看攒个窝儿转
Stir it so it drifts

55
00:02:00,560 --> 00:02:02,080

56
00:02:02,080 --> 00:02:04,840
你看 这儿一个漩涡
Looke, there is a whirlpool

57
00:02:05,920 --> 00:02:09,760
旋旋旋 东西都旋在一块去了
Let it drift, everything will get together

58
00:02:09,760 --> 00:02:12,000

59
00:02:12,240 --> 00:02:13,280
开始慢慢的出沫子了
And slowly 

60
00:02:13,280 --> 00:02:14,520
渗透出沫子了
There’s foam coming out

61
00:02:14,520 --> 00:02:16,920
小魏在渗透沫子的同时呢
Xiao Wei, as the foam forms 

62
00:02:16,920 --> 00:02:18,880
比如要开锅
If it’s about to boil, 

63
00:02:18,880 --> 00:02:21,280
要大开的时候你就拧小火
to come to rolling boil, turn the heat down

64
00:02:21,280 --> 00:02:23,520
不能大开 一大开就完了
Don’t let come to rolling boil 

65
00:02:23,520 --> 00:02:26,680
小火 拧小点 火不能大
Low heat

66
00:02:26,680 --> 00:02:28,240
似开非开的时候
Let it come to almost boil

67
00:02:28,240 --> 00:02:31,320
这样这沫子它就不浑了
So the the foam doesn’t make the broth cloudy

68
00:02:31,320 --> 00:02:33,240

69
00:02:33,240 --> 00:02:35,640
这样可以下第二次了
Now, we can add more ground chicken mixture

70
00:02:35,640 --> 00:02:40,160

71
00:02:40,160 --> 00:02:42,200
大火再顶一下
Turn the heat up to bring up the temperature

72
00:02:42,200 --> 00:02:43,640
让它开着 似开非开
Let it come to almost boil

73
00:02:43,640 --> 00:02:46,560
你要不顶它那沫子出不来
If you don’t let it come to almost boil, the impurities don’t come out


74
00:02:46,560 --> 00:02:48,800
这沫子不出去这汤清不了
If the impurities are not out, the broth is not cloudy

75
00:02:48,800 --> 00:02:52,600
再稍微小一点 还得让它开
Turn the heat a little lower but make make sure it’s still almost boiling

76
00:02:52,600 --> 00:02:56,520

77
00:02:56,520 --> 00:02:59,320
行了 第三遍
Now, the third time

78
00:02:59,320 --> 00:03:02,080

79
00:03:02,080 --> 00:03:02,920
不能有沫子
Can’t let it have impurities

80
00:03:02,920 --> 00:03:06,280
大爷讲话 叫清澈见底
In Da Ye’s word: so clear that you can see the bottom

81
00:03:06,280 --> 00:03:09,960
关火 你看这汤
Turn the heat off. Look at the broth

82
00:03:09,960 --> 00:03:11,560
沉下去了
The chicken sinks

83
00:03:11,560 --> 00:03:13,520
经过三遍扫之后
After three times of clearing it

84
00:03:13,520 --> 00:03:15,160
汤非常香
It’s very flavourful

85
00:03:15,160 --> 00:03:18,640
羊排也好了 出锅吧
Lamb ribs are ready, remove them from the pot.

86
00:03:18,640 --> 00:03:20,440
二十五分钟又闷了十分钟
25 minutes and 10 more minutes

87
00:03:20,440 --> 00:03:22,840

88
00:03:22,840 --> 00:03:23,920
没味儿 咱调个味儿吧
Not flavourful enough, let’s season it.

89
00:03:23,920 --> 00:03:27,920
给点盐 白胡椒粉 黄酒
Add some salt, white pepper, huangjiu rice wine

90
00:03:27,920 --> 00:03:29,840

91
00:03:32,280 --> 00:03:33,800
我得把肉捞出来
I need to remove the meat 

92
00:03:33,800 --> 00:03:35,280
大爷 这萝卜摔完了
Da Ye, the radish is smashed

93
00:03:35,280 --> 00:03:36,880
刚才我尝了一块
I tasted one

94
00:03:36,880 --> 00:03:39,880
把纤维组织全给摔烂了
All the fibers are broken

95
00:03:39,880 --> 00:03:42,920
吃起来绵软了 而且特别嫩
It’s soft and tender

96
00:03:42,920 --> 00:03:46,280
好了 把清好的鸡汤
Now, put the cleared broth

97
00:03:46,280 --> 00:03:47,760
倒进去了
In the pot

98
00:03:47,760 --> 00:03:50,600
鲜啊 再来点
Very flavourful! Add more.

99
00:03:50,600 --> 00:03:52,720

100
00:03:52,720 --> 00:03:54,040
开锅就得
Once it boils

101
00:03:54,040 --> 00:03:56,520
虫草花 然后枸杞子
Add cordyceps flower and goji berry

102
00:03:56,520 --> 00:03:58,080
一道大菜行了
A main course

103
00:03:58,080 --> 00:04:01,520
为什么是拆解 把这个菜拆解做
Why do we make the components separately

104
00:04:01,520 --> 00:04:04,680
你看肉先压
Cook the meat first

105
00:04:04,680 --> 00:04:06,720
压完之后你看 淡淡的香料
So it has a touch of flavour from the spices

106
00:04:06,720 --> 00:04:08,280
又吃不出香料味 肉很香
But you don’t really taste the spices, they make the meat more flavourful

107
00:04:08,280 --> 00:04:09,600
然后再调味
Then we season it 

108
00:04:09,600 --> 00:04:10,840
调味之后 清好的鸡汤
And we put it together with the clear broth

109
00:04:10,840 --> 00:04:12,040
我们再合在一起
We add the together

110
00:04:12,040 --> 00:04:14,720
然后喝着汤吃着肉
Have the broth and meat

111
00:04:14,720 --> 00:04:15,920
如果肉要不够味
If you think the meat is not seasoned enough

112
00:04:15,920 --> 00:04:17,200
我们还可以自己
You can make

113
00:04:17,200 --> 00:04:19,600
自行喜欢 调个汁
a sauce for it

114
00:04:19,600 --> 00:04:21,040
香菜末 小米辣
Cilantro, "Xiaomila" chili pepper

115
00:04:21,040 --> 00:04:22,040
然后我们再搁点豉油
And some soy sauce

116
00:04:22,040 --> 00:04:24,000
拿小油一呲 搁点小葱花 
Add some hot oil and scallion

117
00:04:24,000 --> 00:04:27,200
蘸点汁 别有一番风味
It give a different taste to have it with the sauce

118
00:04:27,200 --> 00:04:29,600
摔萝卜炖羊排 好了
Smashed radish and lamb stew is done

119
00:04:29,600 --> 00:04:31,400

120
00:04:31,400 --> 00:04:32,160
大爷您看
Look! Da Ye

121
00:04:32,160 --> 00:04:34,360
还在咕嘟咕嘟冒着泡儿呢
It’s still boiling

122
00:04:34,360 --> 00:04:37,240
汤清味美
Very tasty!

123
00:04:37,680 --> 00:04:39,360

124
00:04:39,360 --> 00:04:40,360
看看萝卜
Look at the radish

125
00:04:40,360 --> 00:04:43,600

126
00:04:43,600 --> 00:04:44,640
摔的酥烂
So soft and tender

127
00:04:44,640 --> 00:04:59,280

128
00:04:59,280 --> 00:04:59,840
是吧大爷
Right? Da Ye

129
00:04:59,840 --> 00:05:00,720
这汤鲜吧
It’s very flavourful, isn’t it?

130
00:05:00,720 --> 00:05:02,280
这个萝卜摔完了
Smashed radish is

131
00:05:02,280 --> 00:05:03,680
效果就跟切的不一样
really different from cut ones
