### ISSUE TITLE
[雪鱼探店] 佛跳墙 - https://youtu.be/fIhDHcuw_Nw

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#176]
https://youtu.be/fIhDHcuw_Nw

视频于 2019 年 9 月 9 日发布

**Comment by immoonancient** [comment]
这个我来吧

**Comment by okiamnewhere** [comment]
感谢大家的辛苦翻译！
**中文字幕稿如下：**
1 
00:00:01,880 --> 00:00:04,920
福建·福州

2 
00:00:11,400 --> 00:00:12,920
你好

3 
00:00:25,720 --> 00:00:29,600
进来了也没有人招待 也不知道朝哪儿走

4 
00:00:31,800 --> 00:00:33,840
应该是朝这边方向走

5 
00:00:34,760 --> 00:00:36,880
看到了 看到了

6 
00:00:36,880 --> 00:00:38,960
现在看到有人在吃饭了

7 
00:00:38,960 --> 00:00:41,040
应该是没错的

8 
00:00:45,760 --> 00:00:47,920
我问一下吧

9 
00:00:47,920 --> 00:00:51,520
小哥 吃饭在哪边

10 
00:00:51,520 --> 00:00:52,400
三楼

11 
00:00:52,400 --> 00:00:53,920
哦 三楼

12 
00:00:55,120 --> 00:00:57,560
哎呀 好累呀

13 
00:01:25,280 --> 00:01:26,400
这边是

14 
00:01:26,400 --> 00:01:29,000
咱先说这个佛跳墙

15 
00:01:29,000 --> 00:01:31,160
最低

16 
00:01:31,160 --> 00:01:32,080
一位

17 
00:01:32,080 --> 00:01:36,480
最高是金尊大坛正宗佛跳墙

18 
00:01:36,480 --> 00:01:39,280
7980元

19 
00:01:39,280 --> 00:01:42,000
一大坛 当然这个是10人份的

20 
00:01:42,000 --> 00:01:44,120
咱不可能定这个预定版的

21 
00:01:44,120 --> 00:01:45,560
咱就要这种现成的

22 
00:01:45,560 --> 00:01:49,480
要不就是398一位的 要不就是598一位的

23 
00:01:49,480 --> 00:01:53,080
398的 是极品正宗佛跳墙

24 
00:01:53,080 --> 00:01:55,840
还有一个是至尊正宗佛跳墙

25 
00:01:55,840 --> 00:01:57,960
那个就是600块钱

26 
00:02:00,600 --> 00:02:03,800
其它的都是需要预定的 就不要了

27 
00:02:03,800 --> 00:02:06,040
价格也太贵了

28 
00:02:11,680 --> 00:02:13,920
那我就要这个吧

29 
00:02:14,360 --> 00:02:16,200
398那个

30 
00:02:16,480 --> 00:02:18,040
极品正宗佛跳墙

31 
00:02:18,040 --> 00:02:19,320
再加一个荔枝肉

32 
00:02:19,320 --> 00:02:20,920
再加一个芋泥吧

33 
00:02:22,400 --> 00:02:23,160
对

34 
00:02:24,840 --> 00:02:26,760
就是你刚才说的88块钱的

35 
00:02:27,640 --> 00:02:28,240
对

36 
00:02:28,240 --> 00:02:29,800
我也不知道它具体叫什么

37 
00:02:29,800 --> 00:02:31,840
它里面是加了马蹄是吧

38 
00:02:32,800 --> 00:02:34,240
吃起来比较脆那种

39 
00:02:34,240 --> 00:02:35,680
再要一个芋泥

40 
00:02:36,000 --> 00:02:37,120
对

41 
00:02:37,360 --> 00:02:38,480
可以了

42 
00:02:39,280 --> 00:02:40,400
够吃

43 
00:02:40,400 --> 00:02:41,280
够吃

44 
00:02:41,280 --> 00:02:42,840
量都比较小吗

45 
00:02:43,080 --> 00:02:45,120
佛跳墙它一份就这样子

46 
00:02:45,120 --> 00:02:46,680
试试吧 不够再加

47 
00:02:49,680 --> 00:02:51,400
不用要酒水

48 
00:02:51,520 --> 00:02:53,760
咱们来的时候 首先是到一楼的大厅

49 
00:02:53,760 --> 00:02:56,760
但是它那个地方是没有卖饭的

50 
00:02:56,760 --> 00:02:57,840
只是有一个卖茶叶的

51 
00:02:57,840 --> 00:02:59,280
还有一个我不知道卖什么的

52 
00:02:59,280 --> 00:03:02,040
然后咱们是上了二楼 二楼有很多人在吃饭

53 
00:03:02,040 --> 00:03:07,400
但是人家是销售和主管在这儿聚餐吃饭

54 
00:03:07,400 --> 00:03:08,800
问了之后才知道

55 
00:03:08,800 --> 00:03:11,600
原来吃饭的地方在三楼

56 
00:03:11,600 --> 00:03:14,160
我们真的是辗转反侧来到这个地方

57 
00:03:21,920 --> 00:03:23,400
它这边是这样的

58 
00:03:23,400 --> 00:03:29,400
极品的佛跳墙是398

59 
00:03:29,400 --> 00:03:30,440
极品的福跳墙是398

60 
00:03:30,440 --> 00:03:33,400
还有这边要收1%的服务费

61 
00:03:40,480 --> 00:03:43,600
10%

62 
00:03:52,320 --> 00:03:54,640
一落座 阿姨就倒来了茶水

63 
00:03:54,640 --> 00:03:57,520
然后呢 给我们倒了一小碟的陈醋

64 
00:03:57,520 --> 00:03:58,920
作为调料品

65 
00:03:58,920 --> 00:04:01,600
还附赠了一小碟的甜品

66 
00:04:01,600 --> 00:04:04,200
这里的服务真的是很到位

67 
00:04:04,560 --> 00:04:07,360
有一种在吃宴席的感觉

68 
00:04:09,240 --> 00:04:11,200
每个人都是这种

69 
00:04:11,480 --> 00:04:14,160
红桌布上面再盖了一层（白）桌布

70 
00:04:14,680 --> 00:04:16,320
有的（人多）是这种大圆桌

71 
00:04:16,320 --> 00:04:19,360
像我们这种人少的 就是小方桌

72 
00:04:35,280 --> 00:04:37,000
好 谢谢

73 
00:04:37,000 --> 00:04:38,720
这个是荔枝肉

74 
00:04:44,800 --> 00:04:46,720
还是回到我们的佛跳墙

75 
00:04:46,720 --> 00:04:48,640
佛跳墙真的是不算大

76 
00:04:48,640 --> 00:04:52,000
这么一盅

77 
00:04:52,000 --> 00:04:55,120
上来佛跳墙 还配了一个银丝卷

78 
00:04:55,120 --> 00:04:57,080
说和它配着来吃

79 
00:04:57,080 --> 00:04:58,680
现在

80 
00:04:58,680 --> 00:05:01,440
历史性的时刻开启

81 
00:05:10,200 --> 00:05:13,720
好像除了一个蛋 都看不到什么东西

82 
00:05:15,000 --> 00:05:17,080
里面的料太贵

83 
00:05:17,080 --> 00:05:20,560
里面有海参 鲍鱼这些 等等吧

84 
00:05:20,560 --> 00:05:22,880
咱们就先喝汤

85 
00:05:22,880 --> 00:05:24,920
避免这一碗吃不饱

86 
00:05:24,920 --> 00:05:27,440
那咋办 不能再要一个吧

87 
00:05:37,880 --> 00:05:39,400
第一口你会觉得

88 
00:05:39,400 --> 00:05:41,920
鲜中还带有点苦味

89 
00:05:41,920 --> 00:05:44,440
很神奇的味道

90 
00:05:48,880 --> 00:05:52,640
吃完这个佛跳墙 明天我就能重返18岁

91 
00:05:54,280 --> 00:05:55,640
大补啊

92 
00:05:59,000 --> 00:06:01,800
这里面能够看到的

93 
00:06:01,800 --> 00:06:05,600
海参 鲍鱼 最大的鸽子蛋

94 
00:06:06,440 --> 00:06:08,440
如果说你把（料）放进碗里

95 
00:06:08,440 --> 00:06:10,600
可能就是那么一小碗

96 
00:06:10,600 --> 00:06:13,120
我在等有没有人帮我介绍一下

97 
00:06:13,120 --> 00:06:15,160
佛跳墙里有什么样的东西

98 
00:06:15,160 --> 00:06:17,200
有几样确实是不认识

99 
00:06:17,680 --> 00:06:20,680
你好 我想问一下 这个是什么东西 这个

100 
00:06:20,680 --> 00:06:22,400
上面那个厚厚的东西吗

101 
00:06:22,400 --> 00:06:23,520
那个是鳖裙

102 
00:06:23,520 --> 00:06:24,680
叫什么

103 
00:06:24,680 --> 00:06:26,000
就是甲鱼的边
壳周围的肉质软边

104 
00:06:28,200 --> 00:06:30,280
它里面还有一个

105 
00:06:30,280 --> 00:06:33,520
好像是有点带蹄筋似的东西

106 
00:06:34,680 --> 00:06:36,160
就是像一个人字形的嘛

107 
00:06:37,480 --> 00:06:39,840
还是一个就是花胶

108 
00:06:39,840 --> 00:06:41,000
花胶

109 
00:06:41,000 --> 00:06:42,800
那类似粉丝的呢

110 
00:06:42,800 --> 00:06:45,080
类似粉丝 这个是粉丝吗

111 
00:06:47,440 --> 00:06:49,000
第一次知道这个

112 
00:06:50,640 --> 00:06:53,320
短一点的一丝一丝的是瑶柱

113 
00:06:53,320 --> 00:06:55,120
瑶柱 就是大的干贝

114 
00:06:55,520 --> 00:06:56,200
谢谢

115 
00:06:56,200 --> 00:06:58,080
不客气 这里面一共9样食材

116 
00:06:58,080 --> 00:06:59,960
哦 9样食材

117 
00:07:01,000 --> 00:07:05,560
佛跳墙的汤颜色像中草药的颜色

118 
00:07:05,560 --> 00:07:07,240
里面有九种食材

119 
00:07:07,240 --> 00:07:10,000
它为了保持食材本来的味道

120 
00:07:10,000 --> 00:07:12,680
分别制成一道菜 然后汇集在一起

121 
00:07:12,680 --> 00:07:14,400
加入高汤和绍兴酒

122 
00:07:14,400 --> 00:07:16,520
再文火煨制十几个小时

123 
00:07:16,520 --> 00:07:19,160
才成了我们眼前的这一盅

124 
00:07:19,160 --> 00:07:22,280
400块钱的

125 
00:07:22,680 --> 00:07:24,040
它虽然说是肉做的

126 
00:07:24,040 --> 00:07:26,960
但是你品尝不出来任何油腻的感觉

127 
00:07:30,880 --> 00:07:33,680
我要告诉你 海参和鲍鱼是什么样的味道吗

128 
00:07:35,520 --> 00:07:38,320
说不出来的味道

129 
00:07:41,640 --> 00:07:44,440
每吃一口 都是钱的味道

130 
00:08:21,280 --> 00:08:24,040
关 注
雪 鱼 探 店

**Comment by kdliu86** [comment]
#189
