### ISSUE TITLE
【美食作家王刚】去华农家，四伯第一次坐飞机 https://youtu.be/1LfLbyITYXQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#178]
【美食作家王刚】去华农家，四伯第一次坐飞机 https://youtu.be/1LfLbyITYXQ
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间9月11日晚6点

四伯爷东西收拾归一（好）没哦
该收拾的都收拾好了
带几套衣服就是了耍两三天就回来
伯娘（伯母）整理好没哦四伯爷
她整理好了
她的衣服收拾好了一起就去了
她怎么能去呢要在家里照顾小畜生（鸡鸭）
小芬去不去嘛
娃儿（沺沺）在读书她要照看娃儿
四伯爷以前坐过飞机没有哦
没有我一直在屋头种庄稼哪有时间出去坐飞机哦
飞机票好贵哦以前
现在很便宜了（有的）比汽车票都还便宜
才五六百（到广州）
那么便宜呀 嗯
我还不晓得
但是坐飞机有时候有气流
气流就是有时候可能会抖几下比汽车要抖一点
安不安全呢
你放心很安全中国的飞机是最安全的
那安全就好
从成都坐过去（广州）2个小时的样子就到了
那么快啊
肯定快嘛飞机是飞的
那安逸两个小时就到了（路上）还不受罪
一会就到了 抽几根烟就到了
飞机上面是不能抽烟的
那在飞机上烟瘾来了还只有憋住哦
憋一会儿一个多小时
那个多小时熬住就是了
没事的
我伯爷60岁多一点了第一次坐飞机他很开心
是不是四伯爷 嗯
坐飞机倒是很开心的
还没剪完那个海椒（辣椒蒂）
还有一点点
我老爸还在这里搬砖
好久这里能做完
今天下午能做完
其实每次带我伯爷出去玩没带父母
其实以前我老爸老妈就是在外面漂泊了大半辈子
他们现在更想留在家里面所谓的享清福
我伯爷再农村老家呆了几十年
有个心愿就是有机会的话就出去走一走
正好的话偶尔我就带伯爷出去散散心
这是我去借的车四伯爷
上车
你行李房后面嘛
要得 好
放这里二排（后排）
系好安全带哦
这个要取下来吗
从那边绕过来
安全带（系好）
我想一下这个车怎么整燃（点火）
空挡放手刹
踩刹车离合踩下去
好现在挂空挡
哦不对挂一档
松离合
车身抖动就开始走
感觉到抖动了开始松刹车
整慢点嘛
开得归一的（我会开车的）

四伯爷
这下子做飞机怕不怕哟
不害怕害怕啥子哟
最安全的就是飞机
嘿嘿嘿
他以前没有坐过
我以前第一次坐飞机都有点害怕
特别是起飞的时候
只有起飞和降落的时候有点感觉
其他没得什么感觉
这个机场还挺大的
是一个国际机场吧
是国际机场
四伯爷到了哟
好好好
到了
现在跟我伯爷去兄弟家玩
我们还有两盒月饼放在安检那个地方
等一下我们再过去拿
给我兄弟带了2盒月饼
我还自带了宽油
宽油是寄过去的
飞机上不让带这个东西
现在我跟伯爷都去到票了
这两张票都是不同的机子取的
这边取不了
重庆方言
脚葩手软
我们四川也有这种叫法
是都嘛
有这个说法吧
嗯有这个说法
那这个呢
二不挂五是什么意思哦
二不挂五就是
说你有能力也说你没有能力就叫二不挂五
我们那边有没有这个说法
有有
正南其北呢
也有这个说法呀
我们那边说的正儿八经
嗯
巴适
这个都不用说得
就是很安逸嘛巴适惨了
这个是瞌睡迷西
我们四川那边（有没有这种说法）
有这个说法
我们那边说的拽磕打睡
嗯
扯蒲汗就是打呼噜嘛
到处都在说
打王逛是什么意思哦
这个我们四川还没有
这下面写的不好好听讲
扯把子只要是四川人都晓得
好嘛走嘛我们去候机了
好嘛
这个是座位号吗
53排
往里面走
这下 上升了
这有什么感觉嘛
没得感觉得
下面的公路跟豇豆一样
 看到就跟一根线一样
嘿嘿 高都嘛越高看起来就越小
第一次做飞机怎么样嘛 
没有什么感觉
你看这个翅膀摇摇晃晃的
有点紧张
有点紧张吗
 平稳起的时候就一点感觉都没有
你看下面那条长江
长江好大哟
你看这个云好白哦
跟棉花糖一样
 跟棉花一样
 好漂亮哟
嗯
远在天边近在眼前
嗯
耶 四伯爷可以哟 还多有文化哟
嘿嘿 
人活在这个社会上好是好
坐飞机看一下外面的世界好安逸哟
 以后我有时间在带你出去耍
好嘛好嘛 那到安逸哦
你看外面好漂亮哦
在飞机上看见下面的白云 好美哦
下面那些白云跟棉花一样 好安逸嘛
真的看斗有点舒服
你看外面的云层嘛
像不像汪洋大海嘛
一望无崖
这个飞机飞得好平稳哦
没有什么起伏
下次我又带你出去耍哈
要得嘛
这次的飞机就是没有坐多久
一两个小时还不久吗
 要去新西兰才安逸
那才舒服
嘿嘿嘿
你还想坐久点呀
哈哈哈 
这辈子还是可以了
现在的现代化飞机也坐了高铁也坐了
算可以了
现在准备吃饭了
好 准备开饭
有一包榨菜
有一个面包
还有点水果
慢慢吃四伯爷
马马虎虎
飞机上没有肉吗
咦 有肉
安逸
下了飞机我们油竹鼠吃哦
那也是肉哦
好好好
这还是有肉
 你先将就吃这个
只说不多 是个意思
嗯
好 我也要开始吃了
本期视频就到这里
拜拜
拜拜

**Comment by immoonancient** [comment]
时间关系在 YT 直接做了字幕，回头再在这里同步
