### ISSUE TITLE
【美食作家王刚】王刚四伯看竹鼠 - https://youtu.be/Pvp7Kjx_PPg

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#183]
【美食作家王刚】王刚四伯看竹鼠 - https://youtu.be/Pvp7Kjx_PPg
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间9月14日晚6点

这是我兄弟找的司机来接我们
现在我们从白云机场这边坐车到我兄弟家
大概4个小时左右
师傅你们知道华农兄弟它们拍视频吗
知道啊
他们在我们那边都是名人哦很出名的
名人 对
你们都属于网红
哎呀 网不网红这个东西怎么说呢
 我觉得没有网不网红
大家都是普通人嘛
经过长途跋涉我们终于到了兄弟家
总不能空手来
我们带了自制的菜籽油 宽油
然后给我兄弟一人带了一盒月饼过来
现在已经到了他们家门口了
兄弟
兄弟来啦
买那么多东西干嘛提那么多东西
来 里面请
这个是自带的宽油
里面坐里面坐
哇 你们的狗好有礼貌啊
这狗不咬人的
拎到这个就不烫
我给你介绍一下
这是我四伯专业的屠夫
嘿嘿嘿
这个是我们班的同学
你好你好 很漂亮哦
你也很漂亮
嘿嘿嘿
说明你漂亮好不好
这个玉米很好吃的
吃了玉米不会中暑吧
不会不会 这都是兄弟家摘的
对了 我四伯说他想看一下你的竹鼠
可以啊
介绍一下你的竹鼠
上次你们家那个伊丽莎白鼠怎么样了
好啊 还在上面那呢越来越胖了
我们边走边聊
好
就在上面
这鸡也不错
全都是母鸡
咦 你们家猪呢
都被我关起来了
关起来啦
它一出来的话就跑到外面去啦
习惯了
我们不在的时候经常跑到外面去
到时候都变野猪啦
或者不见了
那就亏大啦
嘿嘿嘿
好大
现在公鼠和母鼠的比例是1：7
那公鼠不是很累吗
没办法公的都卖光啦就剩下一点点啦
就只有轮着来嘛
这批怀孕就抓走再放别的进去
这公鼠太辛苦了
听说你的伊丽莎白鼠很漂亮哦我看一下
在那边
在哪里 我们看一下嘛
哇 好漂亮啊
真的很漂亮
好漂亮
我怎么感觉它瘦了
这个不是伊丽莎白鼠
哦
这个是没名字的
无名莎白
嘿嘿嘿
但是它是白色的
但是不听话
不听话还是很危险的
你看 跟兔子一样
你看这个我抱它都不动
很乖很乖
公的还是母的
公的
真的很乖
不会咬人
那个就不行
这个很温顺
很温顺的
抱着它都没事
来 跟大家打个招呼
哈喽 一年不见甚是想念
它不会说话
它肯定想说大家好哦
它这个白鼠跟黑鼠吃起来是不是不一样啊
这个我不知道
 嘿嘿嘿
白的不好吃
你居然不中套
这个就是西西
西西
发给它做老婆啦
哦
后面生出来的就是白色的
这小的也会咬人的
小的也会咬人啊
小的好可爱哦
你看它的牙齿还是白的还没变黄
对 还没变黄
慢慢的就变黄了因为它还没断奶还在吃奶
我提一下嘛
拎它尾巴
小心它反过来咬到你
不要丢哈不是要摔到它
不会不会它反不过来的
这个好可爱哦
现在它要咬人了
它现在生气了
我拍一下手他会不会安静下来
哇 好神奇啊
它听到声音了
以为遇到危险了就趴着不动
吓到它们了
等一下它慢慢的就恢复过来了
现在又开始了
一下子就安静了
对一下子就安静了
好神奇啊
这是还没断奶的
它们小时候会打架吗
不会
小时候不打架
长大了都不会只要不在一起
长大了是不是争老婆才会打架
不是 因为只有生过崽子之后就会打架
哦 护崽是吧
对 这是天性
真的放在一起一大推都不会打架的
给它加点水
这个猪长不大很难长大
现在应该才20多斤
这个猪在我们那边要卖1000多
要
 这个小猪都是600到700块钱
长得太慢了
我们就喂了一点菜叶子跟那个象草叶子给它吃
你们家的猪好有灵性啊
对
 这个猪的肉是不是要香一点
肯定香啊
天天都吃草吃菜叶子
哦
那你们准备什么时候弄一只小的来吃一下
这个自己养的舍不得吃
等长大以后在吃
有大的呀那里有一只大的
那个是公的
把公猪杀了
那是小猪它老爸呀 你把它老爸杀了它全体攻击我怎么办
全家都杀了呀
嘿嘿嘿 你好狠呀
我们现在是去哪里弄鱼呀
就在上面山上
哦是你家的是吧
对 我自己家的池塘
那里面有好多鱼哦
现在差不多1年多没放
嗯
我们现在去抓鱼鱼在那边
嗯
那我关机了不录了
好好

**Comment by immoonancient** [comment]
这期我顶上吧...
