### ISSUE TITLE
【雪鱼探店】手工麻糍-https://www.youtube.com/watch?v=syAahnaiwNE

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#193]
视频已经于北京时间9月14日 21:30发布，
中文字幕稿如下，感谢大家～
**字幕**
1 
00:00:01,880 --> 00:00:04,920
福建·泉州

2 
00:00:25,720 --> 00:00:29,120
我们今天要去尝尝这个

3 
00:00:34,400 --> 00:00:35,880
地方不大

4 
00:00:37,000 --> 00:00:39,320
堂食请自取

5 
00:00:41,360 --> 00:00:42,680
额 糟糕

6 
00:00:42,680 --> 00:00:45,440
每当看菜单的时候 我都会变的很纠结

7 
00:00:45,440 --> 00:00:47,680
因为你不知道 应该点哪一种

8 
00:00:47,680 --> 00:00:50,880
还有 一个或一份的量 到底有多大

9 
00:00:58,000 --> 00:00:59,280
让我开心的是

10 
00:00:59,280 --> 00:01:01,880
这次没有

11 
00:01:08,280 --> 00:01:10,640
三个（古早味）手工麻糍 三个花生馅的

12 
00:01:10,640 --> 00:01:13,000
再要一个冷冰

13 
00:01:13,720 --> 00:01:16,080
你稍等一下

14 
00:01:19,160 --> 00:01:21,400
三个这个花生

15 
00:01:21,400 --> 00:01:23,640
三个古早

16 
00:01:24,720 --> 00:01:26,680
现在要不要先吃古早味的

17 
00:01:26,680 --> 00:01:28,240
要的话 我就先包给你们

18 
00:01:28,240 --> 00:01:29,800
然后再帮你做冰

19 
00:01:29,800 --> 00:01:31,800
就是古早味没办法达到那么长时间

20 
00:01:31,800 --> 00:01:33,520
哦 明白 行 可以

21 
00:01:33,520 --> 00:01:35,680
那就先做这个 就先吃它

22 
00:01:35,680 --> 00:01:36,440
可以 可以

23 
00:01:36,440 --> 00:01:39,400
哦 这个是不能够放时间很长的

24 
00:01:40,640 --> 00:01:41,800
为什么

25 
00:01:42,280 --> 00:01:43,960
你吃几口就知道了

26 
00:01:43,960 --> 00:01:45,720
不会脆的

27 
00:01:47,240 --> 00:01:48,560
花生的 没关系

28 
00:01:48,560 --> 00:01:50,360
花生的晚一点没关系

29 
00:01:50,360 --> 00:01:51,080
可以

30 
00:01:51,240 --> 00:01:51,960
来

31 
00:01:51,960 --> 00:01:52,680
谢谢

32 
00:01:53,760 --> 00:01:56,080
然后呢 你们可以上楼坐

33 
00:01:56,080 --> 00:01:58,080
行 我先付钱吧

34 
00:01:58,720 --> 00:02:00,320
可以 可以 好 谢谢

35 
00:02:01,320 --> 00:02:03,360
12+12=24

36 
00:02:03,360 --> 00:02:04,840
我先上去吃这个吧

37 
00:02:04,840 --> 00:02:06,720
好 谢谢 麻烦了

38 
00:02:51,640 --> 00:02:54,600
我手上的就是古早味的手工麻糍

39 
00:02:54,600 --> 00:02:55,920
古早味的手工麻糍

40 
00:02:55,920 --> 00:02:57,800
（这家店做的）是这种梭形的

41 
00:02:57,800 --> 00:03:00,400
从我刚进来 到现在拿到手工麻糍

42 
00:03:00,400 --> 00:03:01,720
围绕在我周围的

43 
00:03:01,720 --> 00:03:05,400
全部都是黄豆粉的这种香味

44 
00:03:05,400 --> 00:03:06,880
它这个是拿麻糍面团

45 
00:03:06,880 --> 00:03:09,600
把它扯成一个稍微圆的饼的形状

46 
00:03:09,600 --> 00:03:11,160
然后包上这个

47 
00:03:11,160 --> 00:03:12,320
有点类似薄脆吧

48 
00:03:12,320 --> 00:03:14,480
炸的薄薄的 脆脆的

49 
00:03:14,480 --> 00:03:16,760
这种小的油炸的东西

50 
00:03:16,760 --> 00:03:19,480
把它包进去 然后丢到黄豆粉里

51 
00:03:19,480 --> 00:03:23,000
团一团 就成了这个手工麻糍

52 
00:03:26,360 --> 00:03:27,440
谢谢

53 
00:03:29,240 --> 00:03:31,080
上面这一粒粒是热的

54 
00:03:31,080 --> 00:03:31,560
热的

55 
00:03:31,560 --> 00:03:34,320
对 你要挖一个和冰一起吃

56 
00:03:34,320 --> 00:03:36,000
对 这个跟冰

57 
00:03:36,000 --> 00:03:38,600
再加一点冰 再挖一点冰 下面是冰 对

58 
00:03:38,600 --> 00:03:39,760
这个是什么

59 
00:03:39,760 --> 00:03:42,240
这是阿达子

60 
00:03:42,240 --> 00:03:45,840
阿达子

61 
00:03:46,600 --> 00:03:48,720
就是它下面还有芋头那些

62 
00:03:48,720 --> 00:03:50,080
芋泥是吧

63 
00:03:50,080 --> 00:03:51,560
不 不 不  我们是芋头

64 
00:03:51,560 --> 00:03:52,320
芋头

65 
00:03:52,320 --> 00:03:53,240
对 对 对

66 
00:03:53,240 --> 00:03:53,920
谢谢

67 
00:03:53,920 --> 00:03:55,600
等一下下楼要慢一点

68 
00:03:55,600 --> 00:03:57,920
感觉好温暖

69 
00:04:02,200 --> 00:04:04,080
哇 阿达子是热的

70 
00:04:04,080 --> 00:04:05,400
但是冰是凉的

71 
00:04:05,400 --> 00:04:07,480
两个就是冰火两重天

72 
00:04:08,200 --> 00:04:10,280
但同时都在嘴里

73 
00:04:17,520 --> 00:04:22,040
这阿达子有点这种QQ糖的口感

74 
00:04:26,640 --> 00:04:29,680
刚才这个小姐姐说 下面是有芋头的

75 
00:04:29,680 --> 00:04:32,800
看我把冰山挖过来

76 
00:04:32,800 --> 00:04:34,720
能不能看到芋头

77 
00:04:36,000 --> 00:04:38,240
我真的是来到泉州之后觉得

78 
00:04:38,240 --> 00:04:40,160
这边有很多做芋头的小吃

79 
00:04:40,160 --> 00:04:41,840
把它做成甜品

80 
00:04:41,840 --> 00:04:45,680
但是 芋头又不会做的特别甜

81 
00:04:45,880 --> 00:04:47,840
这应该是芋头吧

82 
00:05:05,920 --> 00:05:07,640
它这个糯米糍是糯米做的

83 
00:05:07,640 --> 00:05:09,800
外面细腻 软糯

84 
00:05:09,800 --> 00:05:12,960
但是里面包的这种薄脆 油炸的东西

85 
00:05:12,960 --> 00:05:15,720
吃起来又是这种香脆感

86 
00:05:15,720 --> 00:05:18,200
两个是完全不同的口味

87 
00:05:18,200 --> 00:05:20,680
但是同时都会在你的口中

88 
00:05:20,680 --> 00:05:24,280
发生这种物理反应

89 
00:05:37,440 --> 00:05:40,720
最开始怎么会想到做手工麻糍的呢

90 
00:05:40,720 --> 00:05:43,880
这个其实是漳州的小吃

91 
00:05:43,880 --> 00:05:44,800
漳州的

92 
00:05:44,800 --> 00:05:48,200
对 因为我去那边吃到 我好几年前

93 
00:05:50,800 --> 00:05:53,160
第一次吃的感觉 哇 好好吃

94 
00:05:53,160 --> 00:05:55,520
但是没有什么想法 因为那时候我在上班

95 
00:05:55,520 --> 00:05:59,400
后面再去吃 因为跟我女儿在讲的时候

96 
00:05:59,400 --> 00:06:02,040
我们讲到漳州 就会想到它嘛

97 
00:06:03,520 --> 00:06:05,720
后面再去吃的时候 就突然

98 
00:06:05,720 --> 00:06:08,200
想说 泉州没有

99 
00:06:08,200 --> 00:06:09,720
所以就引进过来了

100 
00:06:25,520 --> 00:06:28,360
关 注
雪 鱼 探 店

**Comment by chrisnico** [comment]
Hi 已翻译好 求审阅

**Comment by kdliu86** [comment]
self reminder
