### ISSUE TITLE
【美食作家王刚】烧牛腩 - https://youtu.be/LF1wC6u30MA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#201]
【美食作家王刚】烧牛腩 - https://youtu.be/LF1wC6u30MA
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间9月21日晚6点

首先我们准备新鲜的牛腩2000克
将牛腩改刀切成四大块备用
同学们最好选择未打水的牛腩
关于如何分辨注水牛肉请翻看往期视频
 然后将牛腩放入盆中加入清水清洗干净浸泡60分钟
这一步的目的是去除牛肉中的血水
下一步开始准备辅料
准备生姜1大块切成姜片备用
同学们姜片可以适当的切厚一些
准备大葱2根切成葱段备用
下一步开始准备香料
碗中加入八角3颗
加入2小块桂皮
加入两颗三奈
加入几颗丁香
同学们丁香不能多加
加入一小把小茴香
下一步开始处理牛肉
首先我们将泡好的牛肉放入锅中
然后加入适量的清水开大火烧开将牛肉焯水10分钟
这一步的目的是将牛肉煮制定型
如果采用冰冻牛肉则需要将牛肉煮熟
中途加入适量的料酒和姜片小葱
同学们这一步并非将牛肉煮熟
而是将牛肉煮至定型方便切块
大火烧开之后撇去浮末
10分钟之后将牛肉捞出
用清水将牛肉清洗干净后再捡出姜葱
然后趁热将牛肉切成大小均匀小方块备用
下一步开始烧牛肉
首先我们在锅中加入适量的底油
油温烧至5成热之后将准备好的香料和姜葱下锅
然后将香料转小火炒香
香料炒香之后再加入切好的牛腩下锅
牛腩下锅之后开中小火翻炒5分钟
这一步的目的是将牛腩炒干爆香
翻炒5分钟之后加入适量的糖色翻炒几下上色
没有糖色的同学可以用老抽代替
牛腩上色之后加入料酒30克从锅边淋入翻炒均匀
然后再加入芝麻酱10克炒匀
同学们也可以加入2块腐乳曾香
翻炒均匀之后加入适量的清水烧40分钟
清水的量最好能没过牛腩
烧至第10分钟的时候把姜葱捡出不用
姜葱捡出之后转小火烧30分钟
因为牛腩是加工的半成品所以不能留姜葱在锅中久存
否则姜葱在长时间保存中会发酸
30分钟之后将牛腩倒出备用
一道半成品烧牛腩就制作完成
下面开始技术总结
第一，牛腩在前期加工必须用清水浸泡，否则在锅中必须煮熟透再切
第二，此法制作的基础上在后期加工中可以改成香辣或者麻辣
第三，待牛腩凉透之后即可封膜放冰箱保存
第四，烧好的牛腩作为半成品待用可以在做菜时大大提高出菜率

烧牛腩的技术总结完毕

麻辣牛肉面
30分钟之后将牛腩倒出备用
下一步开始准备面条
首先我们准备碱水面300克
同学们相对来说碱水面口感更好
准备适量的空心菜掐节备用
大家也可以选择自己喜欢的蔬菜
牛腩凉透之后取出放入碗中备用
准备麻辣火锅底料30克切散备用
不喜欢牛油味的同学可以用辣椒面和花椒代替
下一步开始煮面
首先我们在锅中加入适量的清水
大火烧开之后加入碱水面下锅
碱水面下锅水开之后不能煮太久只需要煮几秒钟即可
然后将煮好的面条捞出放入碗中
下一步开始煮牛腩
首先在锅中加入少许的油烧热
油温4成热之后将切好的火锅底料下锅小火炒化
同学们切记此过程中必须开微小火否则容易炒糊
底料炒化之后加入烧好的牛腩翻炒均匀
然后加入清汤350克
没有清汤的同学可以用清水代替
然后开大火烧开
大火烧开之后加入少许酱油调味
然后再加入准备好的空心菜下锅烫熟
蔬菜烫熟之后即可出锅
一道非常美味的麻辣牛肉面就制作完成
下面开始技术总结
第一，不喜欢麻辣味的同学可以直接加清汤和牛腩的原汤煮
第二，除了面条之外还可以用红薯粉或者粉丝
麻辣牛肉面的技术总结完毕

**Comment by WuStevenShengyang** [comment]
我来吧
