### ISSUE TITLE
[雪鱼探店] 烫米浆 - https://youtu.be/zdeodumeJyc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#203]
https://youtu.be/zdeodumeJyc

视频于 2019 年 9 月 17 日已发布

**Comment by okiamnewhere** [comment]
**中文字幕稿如下，感谢大家**
1 
00:00:01,880 --> 00:00:04,920
福建·福州

2 
00:00:08,080 --> 00:00:09,480
现在才是六点钟

3 
00:00:09,480 --> 00:00:11,720
但是马路上的人真的是特别多

4 
00:00:11,720 --> 00:00:14,080
我们今天到怎么繁忙的地方来

5 
00:00:14,080 --> 00:00:17,240
就是为了来吃一碗锅边糊

6 
00:00:17,800 --> 00:00:20,760
如果你和我一样 也是第一次听到这个名字

7 
00:00:20,760 --> 00:00:22,880
真的会有点摸不着头脑

8 
00:00:22,880 --> 00:00:24,040
不过肯定的是

9 
00:00:24,040 --> 00:00:26,800
它的制作和锅边有关

10 
00:00:42,440 --> 00:00:45,920
米浆

11 
00:01:16,400 --> 00:01:18,720
这么潇洒的姿势 再来一遍

12 
00:02:30,560 --> 00:02:32,400
这个是我们要的3块5的锅边

13 
00:02:32,400 --> 00:02:35,920
然后配上了三角糕和油饼来吃

14 
00:02:36,120 --> 00:02:37,600
（来这家店吃饭）就是你没坐下

15 
00:02:37,600 --> 00:02:39,960
大叔就会帮你端上来这碗锅边

16 
00:02:39,960 --> 00:02:43,440
然后自己去拿油饼或者三角糕什么的

17 
00:02:43,800 --> 00:02:47,840
油饼
三角糕
锅边

18 
00:02:47,840 --> 00:02:49,920
锅边糊做的时候 是把

19 
00:02:49,920 --> 00:02:53,320
米浆沿着锅沿倒下去

20 
00:02:53,320 --> 00:02:55,280
等它差不多半熟的时候

21 
00:02:55,280 --> 00:02:56,480
刮进汤里

22 
00:02:56,480 --> 00:02:58,080
这碗锅边糊 你能看到的是

23 
00:02:58,080 --> 00:03:00,880
上面是汤 下面是米浆块

24 
00:03:00,880 --> 00:03:02,720
里面还有鱿鱼 虾米

25 
00:03:02,720 --> 00:03:05,400
撒了一些紫菜 还有一些葱花

26 
00:03:05,400 --> 00:03:07,360
这样就出锅了

27 
00:03:15,600 --> 00:03:19,880
这个汤很像虾米和鱿鱼熬出来的汤

28 
00:03:20,280 --> 00:03:23,360
表面泛着一些零星的油花

29 
00:03:23,360 --> 00:03:26,440
下面米浆块是很多的

30 
00:03:27,920 --> 00:03:29,640
可能是因为它（米浆块）太滑嫩

31 
00:03:29,640 --> 00:03:32,600
以至于想把它夹起来 都有点困难

32 
00:03:37,160 --> 00:03:39,480
算了 还是直接用勺吧

33 
00:03:42,520 --> 00:03:45,360
来这家小店吃饭 并没有很多的选择

34 
00:03:45,360 --> 00:03:47,040
除了人手一碗的锅边糊

35 
00:03:47,040 --> 00:03:49,320
也就是炸米糕 油饼这些了

36 
00:03:49,320 --> 00:03:51,720
有没有发现 大家在早上起来

37 
00:03:51,720 --> 00:03:54,120
对油炸的东西 格外的宽容

38 
00:04:10,720 --> 00:04:13,360
米糕 就是米糕 炸的米糕 五香味

39 
00:04:26,800 --> 00:04:29,120
早上起来和我们共进早餐的

40 
00:04:29,120 --> 00:04:31,440
永远是起得早的老年人

41 
00:04:45,040 --> 00:04:47,960
关 注
雪 鱼 探 店
