### ISSUE TITLE
【美食作家王刚】教刘苏良做狮子头 - https://youtu.be/lJ3VoSMmS18

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#209]
【美食作家王刚】教刘苏良做狮子头 - https://youtu.be/lJ3VoSMmS18
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间9月26日晚6点

哈喽大家好我是王刚
这两位是我的兄弟
哈喽大家好我们是华农兄弟
这是我四伯
我是王刚的四伯
国庆节就快要到了
祖国的生日也快到了
过生日嘛 大家都很开心
我想跟大家分享一道国宴菜
 当中比较有名的一个叫做清炖狮子头
然后今天我做红烧吧 好不好
好
做红烧来招待我这两位兄弟
其实这个猪肉用不完
皮子给它去掉
然后先把肉切碎
切碎了之后再剁一下
 其实做这个菜五花肉是最好的
半肥半瘦
把它剁一下
你过来嘛 兄弟
哇
这个肉啊
猪肉哦
来帮忙剁两刀好不好
放点竹鼠肉下去
啊
搞点竹鼠肉下去
我的天 你是什么时候都不会忘记的的竹鼠哦
烧狮子头的肉稍微粗一点点就行了
来 你来剁一会儿
我来
哇
这刀太锋利了
跟我们家的比起来
我们家那个刀很钝哦
我觉得用你们家里养的那个土猪做出来肯定更好吃
是
每次来都不给我机会
下次来
下次去我那里
现场烤一条给你
 好 我来剁一会儿
辛苦了辛苦了
现在变成肉末了
稍微剁一下就行了
够不够啊 就那么一点点
这还要加其它配料
加香菇 加莲藕 加胡萝卜
哦
可以了 这个剁成这样子就行了
你们那边好像没有做这个菜吧
没有
我们那边过年过节都是吃的那种肉圆
你们切菜也是这样切吗
我们切菜没有那么利索
这香菇也要切碎吗
也要切碎
切碎放进去
这个加香菇就不用放味精了
我在这里看着回去我都可以做了
嘿嘿嘿
切个葱都那么有技术
你也可以啊
放一点盐
这个就是调味调色
调色
这个是老抽
生抽调鲜味
好 差不多了
然后就是这样子 
抓
我们一人抓一会儿好不好
好
这个还可以加一些剩的米饭进去
米饭
对 也是为了增加口感
也是很爽的
好 差不多了
我们现在开始盘了啊
你看
好圆哦
对啊 圆圆的
现在闻不到香味
这个要炸了之后才有香味
好
这个就盘好了
然后我们就准备下锅制作
放宽油哦
你知道这个是什么吗
宽油哦
你都知道是宽油了
这个确实是宽油
放那么多
宽油了当然要宽了
不宽怎么叫宽油呢
做这个菜油都放了半盆了
你会看油温吗
不会
我最开始学的时候就是用手伸下去
真的
手都要熟
现在都可以伸下去
现在油温好没烫呢
嗯 
还没烫
都可以伸下去
好不容易过来这个菜我教你
试油温的时候手一伸
不要挨着油离它远一点
感觉有点热了
好 你再伸出来
再烧一会儿又感觉一下
感觉有点烫手了油温就差不多了
可以下肉了
这个不能从中间放下去要从锅边溜下去
 那么讲究啊
必须的
要从锅边下去
哦
对
从锅边下去
可以轻轻的推一下
哦
轻轻的推
现在都可以闻到香味了
对
就是这样炸它
炸完之后等下又要煎
炸完之后就用这个
香料姜葱下去炒出香味
然后加水
然后加酱油糖色或者老抽
给它上色
然后再调点味道
慢慢的给它微（小火烧）
把味道烧进去
烧大概半个小时然后就收汁
就勾点芡就可以
把它淋在上面再撒点葱花就可以上菜了
哇 看到没有金黄辣
差不多可以捞了
你看
怎么样
可以起锅了
但是这个捞出来了还要烧一会儿
现在已经炸香了
真的很漂亮哦
好香啊
然后我们这个油
现在把它盛起来放着下次炸东西又可以用了
嗯
就不是说浪费
不存在浪费的
然后我们锅里面要留一点油
把这个香料放进去
还有这个姜葱
给它慢慢炒 炒出香味
这个爆香了然后我们就加水
好 大概加这么多

这个是老抽
然后放这个酱油
提鲜
再抖点盐下去
有点多哦
放心吧这个没问题
然后这个我们加一点点白糖进去提一下鲜
这个要盖上锅盖
现在我们把这个盖上
盖上烧一会儿
烧40分钟吧
那么久啊
那就烧半个小时吧
现在我把这个火烧得很旺哦
兄弟要烧一点开水准备蒸螃蟹
粗鲁一点啊
快拦住它不要它跑出来
可以了
兄弟 火稍微停一下
兄弟你尝一个
尝一个
这个火好大啊
没关系 你尝一个蟹看熟了没有
 熟了 里面都熟了
熟了吧 好
熟了那我就熟虾了哦
嗯
把虾煮下去就差不多了
姜也放下去
这个葱也放下去
哇
 你看这个虾好大
这个虾
准备吃饭啦
好开饭了
哇
香吗
好香哦
可以了时间已经到了
揭开锅盖
现在捞起来
你看
现在里面已经很软了
炖了它那么久水都炖干一半了
对
然后我们加点这个水淀粉
把它勾成一个芡
淀粉要一点点的放
不能一次放太多
为什么
因为你放太多掌握不好这个量的话
下去要嘛浓了 要嘛太稀了
哦
再放一点点
好
 淋在这个上面
然后在中间撒一点葱花
爸爸
诶
我也要吃那个
好 你要吃“狮子头”啊
我不要
好我们开饭了
其实这个菜是淮扬菜
嗯
对 以前我们周总理很喜欢吃这道菜
那道菜是国宴菜
然后做得很清淡
但是我们这个的话为了更下饭一点
所以就做成红烧
像以前一样
我们还小的时候
生活很困难
对
逢年过节才有肉吃
不像现在几乎每顿都可以吃肉
我们小时候也是一样的
就是可能
十天半个月才能看见一点点肉
所以在这里我们祝我们伟大的祖国
生日快乐
好了 拜拜
拜拜

**Comment by archerdominique** [comment]
我接
