### ISSUE TITLE
[雪鱼探店] 新疆烤包子 - https://youtu.be/ID5BL9sXqDA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#211]
https://youtu.be/ID5BL9sXqDA

视频发布日期 2019 年 9 月 21 日

**Comment by okiamnewhere** [comment]
**中文字幕稿如下，感谢你们**
1 
00:00:01,800 --> 00:00:04,720
哇 塞

2 
00:00:04,800 --> 00:00:05,800
感觉

3 
00:00:18,360 --> 00:00:20,880
烤包子

4 
00:00:23,800 --> 00:00:26,000
刚才司机师傅带我们来的时候

5 
00:00:26,000 --> 00:00:28,400
在好远就闻着烤包子的味道

6 
00:00:28,400 --> 00:00:30,080
他自己都饿了

7 
00:00:30,680 --> 00:00:32,720
看吧 这排队的阵势

8 
00:00:33,640 --> 00:00:36,240
我也不知道要多久才能够吃得上

9 
00:01:13,000 --> 00:01:18,000
烤包子刚端上来就能够闻到一股

10 
00:01:18,280 --> 00:01:20,720
看看我的烤包子

11 
00:01:21,880 --> 00:01:25,480
真的想
赶紧吃掉它

12 
00:01:56,200 --> 00:01:59,280
之前都是吃的蒸的包子 这次是烤包子

13 
00:01:59,520 --> 00:02:02,760
把包子放在馕坑里烤着来吃

14 
00:02:02,760 --> 00:02:05,360
每一个包子都不算大吧

15 
00:02:05,360 --> 00:02:07,280
我们来尝一口

16 
00:02:10,480 --> 00:02:11,480
包子能够吃出来的

17 
00:02:11,480 --> 00:02:13,000
它的皮是用死面擀出来的

18 
00:02:13,000 --> 00:02:16,080
因为是死面的 它的皮擀的特别薄

19 
00:02:16,080 --> 00:02:18,400
它这个就不能叫肉馅了

20 
00:02:18,400 --> 00:02:20,320
看 都是肉丁

21 
00:02:20,320 --> 00:02:23,800
里面唯一的菜就是洋葱 皮芽子

22 
00:02:27,160 --> 00:02:28,440
（包子皮）好像一个小帐篷

23 
00:02:28,440 --> 00:02:31,120
把肉丁 肉团放进去

24 
00:02:33,360 --> 00:02:35,600
它这里面都是大肉块

25 
00:02:35,600 --> 00:02:37,200
吃起来特别得过瘾

26 
00:02:37,200 --> 00:02:39,840
比吃肉馅过瘾的多

27 
00:02:44,560 --> 00:02:48,440
这个包子还有个特点就是

28 
00:02:48,440 --> 00:02:52,520
吃一口感觉好像吃辣椒一样

29 
00:02:54,880 --> 00:02:57,720
吃烤包子 我还要了一碗酸汤馄饨

30 
00:02:57,720 --> 00:03:01,360
每个小馄饨 都像一个小元宝一样

31 
00:03:01,360 --> 00:03:02,720
沉入酸汤里

32 
00:03:02,720 --> 00:03:05,720
等待着我把它捞起来

33 
00:03:09,560 --> 00:03:12,280
来买烤包子的时候 还是后面的大爷告诉我

34 
00:03:12,280 --> 00:03:15,240
如果说 你要到店里来吃就不需要排队了

35 
00:03:15,240 --> 00:03:18,240
反正也要吃饭嘛 就进来来吃了

36 
00:03:18,240 --> 00:03:19,800
免去了排队的烦恼

37 
00:03:24,600 --> 00:03:27,640
一个多少钱

38 
00:03:28,240 --> 00:03:30,840
3块5一个

39 
00:03:31,880 --> 00:03:34,160
来 给我拿上4个

40 
00:03:34,160 --> 00:03:36,760
14块钱

41 
00:03:42,120 --> 00:03:45,400
这边还有一锅的手抓饭

42 
00:03:45,400 --> 00:03:48,680
上面都是肉 还有胡萝卜

43 
00:03:49,800 --> 00:03:54,520
这边吃的都是羊肉 那边还有在串的肉串

44 
00:03:57,960 --> 00:04:00,880
大哥 我问一下 这个店开多久了

45 
00:04:00,880 --> 00:04:03,520
这个店开多久了

46 
00:04:03,800 --> 00:04:05,720
10几年了

47 
00:04:05,720 --> 00:04:07,640
只是中午卖吗

48 
00:04:07,640 --> 00:04:11,400
早晨9点到下午4点

49 
00:04:13,680 --> 00:04:16,200
这边是刚做出来的

50 
00:04:16,200 --> 00:04:17,880
这一炉能够蒸多少个

51 
00:04:17,880 --> 00:04:19,680
哦 烤多少个

52 
00:04:19,680 --> 00:04:21,200
150个

53 
00:04:22,040 --> 00:04:24,120
看一直在忙

54 
00:04:24,120 --> 00:04:25,800
12个炉

55 
00:04:26,440 --> 00:04:28,960
就这么一直不停地烤

56 
00:04:28,960 --> 00:04:32,600
一炉出来 一炉进去

57 
00:04:36,200 --> 00:04:37,880
刚出炉的

58 
00:04:43,480 --> 00:04:45,160
又来一次

59 
00:04:49,680 --> 00:04:52,200
大哥 我问一下 你买了多少个

60 
00:04:52,200 --> 00:04:53,320
10个

61 
00:04:53,320 --> 00:04:55,960
哦 吃过这个包子

62 
00:04:57,960 --> 00:04:59,840
好多人都跑这边来吃

63 
00:04:59,840 --> 00:05:01,840
你要是再晚 可能就排很多人了

64 
00:05:01,840 --> 00:05:03,280
现在还属于人少的

65 
00:05:03,280 --> 00:05:05,440
现在算人少的 到一点多的时候

66 
00:05:05,440 --> 00:05:07,600
一点多 人多

67 
00:05:08,160 --> 00:05:09,640
现在还属于 人不多的时候

68 
00:05:09,640 --> 00:05:12,160
这边的烤包子就是出一炉 抢一炉

69 
00:05:12,160 --> 00:05:13,680
很快就没有了

70 
00:05:13,680 --> 00:05:16,280
刚才那个大哥说 现在人还不多

71 
00:05:16,280 --> 00:05:18,480
半个小时之后 人会更多

72 
00:05:18,480 --> 00:05:20,680
咱们还属于来的比较早的

73 
00:05:32,400 --> 00:05:35,200
关 注
雪 鱼 探 店
