### ISSUE TITLE
【美食作家王刚】干煸肥肠 - https://youtu.be/34ts0OtA9DQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#219]
【美食作家王刚】干煸肥肠 - https://youtu.be/34ts0OtA9DQ
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间9月30日晚6点

首先我们准备新鲜的肥肠1套
即一头猪的大肠就是1套
然后选择肠头这段比较光滑的一节用剪刀剪断备用
嫌麻烦的同学也可以任意选择
大家一直以来都有个疑问就是大肠到底那一面才是接触粪便
其实就是在大肠光滑的这一面接触猪的粪便
因为摊主的清理肥肠的时候通常会将带粪便这面翻过来清洗干净
摊主为了有好的卖相
所以会将有猪油的一面隐藏在里面
下一步开始处理
我们加入适量的清水先将光滑的一面抓洗几遍
然后用剪刀将肥肠剪开再撕掉里面多余的肥油
喜欢味道浓一些的同学也可以适当的保留一些
下一步继续清洗
盆中加入1小把食用盐
再加入适量的白醋抓洗10分钟
这一步的目的是去除肥肠的异味
10分钟之后加入适量的清水清洗干净
然后将肥肠切成小段挤干水分备用
挤干水分之后加入适量的生抽酱油抓匀
加生抽的目的是提前入味
然后加入1大把干淀粉抓匀
下一步开始准备辅料
准备1小块生姜和几颗大蒜切成粒备用
同学们可要多加一些姜蒜粒增香
准备几根小葱切成小段备用
准备适量的干辣椒剪成小节备用
最后准备适量的油酥花生米和芝麻备用
下一步开始制作
首先我们把锅烧热
锅烧热之后加入宽油
油温烧至6成热之后将准备好的肥肠依次下锅炸至定型
肥肠炸至定型之后捞出
然后将油温重新升至7成热再下肥肠复炸
待肥肠金黄酥脆之后捞出备用
然后将热油到处下一步开始炒制
过中加入少许的热油
加入适量的青花椒爆锅
再讲准备好的姜蒜粒下锅爆香
料头爆香之后加入炸好的肥肠翻炒几下
翻炒几下之后加入准备好的干辣椒下锅
然后在锅边淋入少许的葱油开小火翻炒1分钟
这一步的目的是将干辣椒炒香炒出辣味
1分钟之后加入花生米和芝麻然后开始调味
锅中加入适量的鸡精
加入少许白糖
再加入少许香油翻炒几下
最后加入小葱炒匀即可出锅装盘
一道香辣开胃的干煸肥肠就制作完成
下面开始技术总结
第一，肥肠最好选择肠头的位置，这样成菜更有口感
第二，肥肠需要提前用生抽调味，否则炒制的时候无法入味
第三，此菜更适合开胃下酒，不适合下饭
干煸肥肠的技术总结完毕

**Comment by zh2245** [comment]
领取翻译，谢谢
