### ISSUE TITLE
【美食作家王刚】华农送竹鼠挖土 - https://youtu.be/cUNWHPYENEE

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#220]
【美食作家王刚】华农送竹鼠挖土 - https://youtu.be/cUNWHPYENEE
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间10月2日晚6点

刚哥
诶 兄弟
诶 兄弟
哇 这只好凶啊
竹鼠来了
什么时候到的
刚到
你看它在干嘛
这个好凶
要不我们搞点竹子给它吃
对 我这里有竹子
哪里有竹子
我们家那么多竹子你不知道吗
这根可以啊
这根最好啦
 对对对 就这根
可以啦
你也太客气了吧又带3只竹鼠过来
没事儿自家养的
我把它劈一下吧
它们这几天都饿坏了
 小心啊
好凶啊这个
我给你说它是不会认主人的哦
咦 好凶啊
好霸道啊
这样可是不行的哟 这么霸道
对吧
晚上我们把它那个了
哪个
你这边有没有烧烤架
有啊
可以哟
先把它烤了再说
不然这2个早上起来会受伤的
这里还有一个
小心哦 小心手哦
那么凶
嘿 出来啦
出来一只
出来一只
 拉它尾巴就可以了
 咦呀
好凶啊 好凶啊
好肥呀
嗯
这个放进去了哦
那么凶
不管怎么说
竹子还是给它吃
我还有一支
吃饱了好上路
我带你参观一下我们家
好啊
那么漂亮的房子
现在就是这个样子砖房
可以呀
很凉快的哦 这样的房子  
以前是土屋嘛
冬暖夏凉的
费了很大的功夫
这个是水井
这个水井几十年了
来我给你压
你洗下手吧
我来我来
哇 这个水好凉快哦
别的东西没有水倒是很多
来 你来压我来洗
好啦好啦
够啦
好凉快
这井水好凉快
谁家的鸭子
这个是我家养的
你看都长大了
现在还小还不能吃
现在才三四斤等喂到四五斤再吃
太小了它的毛不好拔
对
其实你早点来就好了
早点来我们下面那块田里的稻谷都还没打
嘿嘿嘿
割稻谷我也会哦
不过你来得也正是时候
我这里有一块地
准备给它翻一下
听说你干农活儿很厉害
对呀
别的不多说锄头我都给你准备好了
你看那边是我种的小葱
哇那么漂亮
那小葱怎么
你看吧我边上都挖了中间给你留了一块
这个没问题啊
小问题
漆二娃把锄头拿过来
反正来都来了就干点会儿嘛
可以
种点青菜
种点那个水果
西红柿之类的
好啊 看谁先挖好
怎么不养几只鸡在这里
这个鸡怎么说呢
养点小动物出来嘛
鸡养着有啊
有啊
但是还小啊
那我来早了哦
对啊
快过年的时候再来一次
可以啊
要多养点那些小动物出来哦
鸡呀 鸭呀 鹅呀
休息会儿呗
可以啊
再坚持几分钟
通通帮你全部翻掉
我就喜欢听你这句话来继续干
多种点菜
休息会儿
累不累
有一点累
这个比爬山轻松多了
爬山更累
对
这个不那么累
但是也会累啊
哇 搞定
终于翻过来了
我那边还有几亩地
下次我牵条牛来帮你把它犁一下
辛苦了兄弟
没事啊
这个土才到哪啊 还多得很

**Comment by archerdominique** [comment]
[translation processing]
