### ISSUE TITLE
[雪鱼探店] 羊肉手抓饭 - https://youtu.be/-AT1m__EnJo

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#225]
https://youtu.be/-AT1m__EnJo

发布日期 2019 年 9 月 27 日

**Comment by okiamnewhere** [comment]
**中文字幕稿如下：**

1 
00:00:01,880 --> 00:00:04,920
新疆·乌鲁木齐

2 
00:00:18,800 --> 00:00:19,280
哇

3 
00:00:19,280 --> 00:00:20,320
哇

4 
00:00:20,320 --> 00:00:22,640
在这儿都能闻到洋葱的味道

5 
00:00:32,400 --> 00:00:34,720
大哥 这是多少斤羊肉

6 
00:00:34,720 --> 00:00:37,840
这是

7 
00:00:37,840 --> 00:00:40,760
30斤羊肉放在这一锅里炒

8 
00:00:41,400 --> 00:00:42,600
厉害

9 
00:00:44,760 --> 00:00:45,760
山东人

10 
00:00:46,440 --> 00:00:47,200
对

11 
00:00:49,400 --> 00:00:52,080
靠近海边的喜欢吃海鲜

12 
00:00:52,080 --> 00:00:56,080
朝里面一点也不是很喜欢吃海鲜

13 
00:00:57,760 --> 00:00:59,040
都喜欢吃海鲜

14 
00:00:59,040 --> 00:01:01,880
一般青岛的会比较多 青岛 烟台 威海

15 
00:01:01,880 --> 00:01:03,160
会比较多

16 
00:01:03,160 --> 00:01:04,120
是这样的

17 
00:01:04,120 --> 00:01:05,040
对

18 
00:01:05,040 --> 00:01:07,840
大哥用铁锹在这儿翻羊肉

19 
00:01:08,960 --> 00:01:11,560
这边用的羊肉 都是肥瘦相间的

20 
00:01:11,560 --> 00:01:12,800
是的

21 
00:01:32,720 --> 00:01:34,400
我告诉你 路过抓饭店

22 
00:01:34,400 --> 00:01:35,280
不得不吃

23 
00:01:35,280 --> 00:01:38,080
因为它这个香味 不仅有羊肉的香味

24 
00:01:38,080 --> 00:01:40,880
还有米香味 还有洋葱的香味

25 
00:01:41,080 --> 00:01:43,480
真是三者融合为一体

26 
00:01:43,480 --> 00:01:45,880
吸引你赶快来吃呀

27 
00:01:46,560 --> 00:01:48,960
现在我们就等着吃手抓饭了

28 
00:02:14,760 --> 00:02:16,160
今天开饭晚了

29 
00:02:16,160 --> 00:02:17,160
没事

30 
00:02:17,880 --> 00:02:20,880
周末 开饭还要晚半个小时

31 
00:02:21,680 --> 00:02:23,600
没事 我们坐一会儿

32 
00:02:23,600 --> 00:02:25,560
在家也没事

33 
00:02:25,560 --> 00:02:29,320
我们从开业第二年 就开始（过来）吃

34 
00:02:29,320 --> 00:02:30,880
一直吃到现在

35 
00:02:30,880 --> 00:02:32,640
十多年老顾客

36 
00:02:32,640 --> 00:02:34,080
都是开车来吃

37 
00:02:34,080 --> 00:02:35,480
开车来吃

38 
00:02:35,480 --> 00:02:39,280
我们也不在这儿周边 在乌鲁木齐市住

39 
00:02:39,280 --> 00:02:41,800
开了多久来的

40 
00:02:41,800 --> 00:02:44,320
他开店第二年就来吃了

41 
00:02:48,840 --> 00:02:50,280
亲戚嘛

42 
00:02:50,280 --> 00:02:53,080
就一块拉来吃

43 
00:02:53,080 --> 00:02:55,600
我们主要是每个星期都来

44 
00:02:55,600 --> 00:02:58,480
他要是没有车 我们都坐公交

45 
00:02:58,480 --> 00:03:00,720
现在有车了 我们就开车来

46 
00:03:00,720 --> 00:03:02,960
公交也近 坐到那个地方

47 
00:03:02,960 --> 00:03:05,200
再走过来得二百米

48 
00:03:08,560 --> 00:03:09,600
刚才这个阿姨说

49 
00:03:09,600 --> 00:03:11,600
这个肉新鲜到什么程度

50 
00:03:11,600 --> 00:03:13,360
就是刚宰来的嘛

51 
00:03:13,360 --> 00:03:16,360
拿来的时候 肉还是热的

52 
00:03:43,240 --> 00:03:44,280
走吧

53 
00:03:44,280 --> 00:03:46,960
就是在新疆吃抓饭 吃羊肉

54 
00:03:46,960 --> 00:03:48,560
记得吃点皮芽子

55 
00:03:48,560 --> 00:03:49,520
哦 洋葱

56 
00:03:49,600 --> 00:03:50,680
也叫皮芽子

57 
00:04:19,120 --> 00:04:20,200
要多少钱的手抓饭 说

58 
00:04:20,200 --> 00:04:22,680
要一盘 大盘加肉 再要四个烤串

59 
00:04:22,680 --> 00:04:24,480
65元
大盘加肉40元
烤串5元/根

60 
00:04:24,480 --> 00:04:26,480
对 对 对

61 
00:04:27,080 --> 00:04:28,480
过去了

62 
00:04:28,880 --> 00:04:32,600
我们今天的目标

63 
00:04:52,600 --> 00:04:53,520
还没到

64 
00:05:34,920 --> 00:05:36,560
来了 来了

65 
00:05:39,400 --> 00:05:40,480
谢谢

66 
00:05:40,680 --> 00:05:42,280
不够再加米

67 
00:05:42,280 --> 00:05:43,280
可以再加米

68 
00:05:43,280 --> 00:05:44,360
可以加

69 
00:05:44,360 --> 00:05:45,440
谢谢

70 
00:05:46,800 --> 00:05:48,800
这个闻到味就饿了吧

71 
00:05:49,880 --> 00:05:51,800
米是先浸泡了

72 
00:05:51,800 --> 00:05:55,560
然后和处理好的羊肉放在一起炖煮

73 
00:05:55,560 --> 00:05:57,560
你看 粒粒分明

74 
00:05:57,800 --> 00:06:00,480
因为米饭是和羊肉一起蒸出来的

75 
00:06:00,480 --> 00:06:02,800
所以说 这个米饭

76 
00:06:02,800 --> 00:06:04,520
一点都不会干

77 
00:06:04,520 --> 00:06:07,080
有油的滑润感

78 
00:06:07,080 --> 00:06:08,640
真的是特别香

79 
00:06:08,640 --> 00:06:10,480
里面放了两种萝卜

80 
00:06:10,480 --> 00:06:14,640
一个是稍微橘色一点 一个是稍微黄色一点

81 
00:06:14,640 --> 00:06:18,800
炖的特别烂 而且还有油水

82 
00:06:29,480 --> 00:06:32,560
大口吃肉
大口吃饭

83 
00:06:33,600 --> 00:06:36,480
羊肉特别软烂 而且不腥也不膻

84 
00:06:36,480 --> 00:06:39,280
吃起来就是这种原汁原味

85 
00:06:39,280 --> 00:06:42,720
可能在很久之前吃抓饭是用手抓着吃的

86 
00:06:42,720 --> 00:06:45,440
现在可以用小勺了

87 
00:06:51,800 --> 00:06:54,880
为什么吃的画面很少

88 
00:06:54,880 --> 00:06:57,960
只怪抓饭太香

89 
00:07:01,920 --> 00:07:05,000
工作日五六锅
周末四五锅

90 
00:07:10,600 --> 00:07:12,920
你以为我们今天是来吃抓饭的吗

91 
00:07:12,920 --> 00:07:15,240
我们今天是来吃肉的

92 
00:07:23,000 --> 00:07:26,000
关 注
雪 鱼 探 店
