### ISSUE TITLE
[华农兄弟] 摘摄影小哥家的板栗和南瓜 - https://youtu.be/fm03VRhc6kE

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#231]
https://youtu.be/fm03VRhc6kE
<p>&#35270;&#39057;&#21457;&#24067;&#20110; September 29, 2019 at 01:23PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
發佈了
