### ISSUE TITLE
【美食作家王刚】土匪猪肝 - https://youtu.be/NxQr_uEBl1o

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#236]
【美食作家王刚】土匪猪肝 - https://youtu.be/NxQr_uEBl1o
本视频时长 3:03，预计发布时间为北京时间10月3日晚6点

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

首先我们准备鲜猪肝一块（约400克）
然后将猪肝切成厚片备用
同学们最好切厚一些大概4毫米左右
这道菜所追求的是外焦里嫩所以不能切太薄
猪肝切好之后放入碗中加入适量的清水清洗干净
大家也可以多清洗几遍这样才能有效去除血腥味
清洗干净之后捞出挤干水分备用
下一步准备腌制
准备生姜1小块切成片放入碗中备用
将料头和猪肝一起腌制下过爆炒
这样的目的是节省成菜的时间
准备几颗打蒜拍散放入碗中
碗中加入生抽酱油3克
加入老抽2克调底色
加入胡椒粉1小勺
加入玉米淀粉1小勺之后搅拌均匀腌制10分钟备用
因为需要下过爆炒淀粉不能加太多
下一步开始准备辅料
准备小米辣几颗切成小片备用
准备野山椒几颗切片备用
准备大红椒1个去籽之后切成小片备用
如果不能吃太辣只需加入大红椒即可
最后准备1小把蒜苗斜刀切成小段备用、
同学们注意因为下锅时间不一样
所以必须将蒜头和蒜苗分开投放
下一步开始制作
首先我们把锅烧热
锅烧热之后加入适量的熟菜籽油
将油温烧至7成热之后加入干辣椒爆锅
随后下入猪肝爆至发卷
猪肝发卷后将准备好的辅料下过爆炒1分钟
中途加入切好的蒜苗头
蒜苗炒至断生后开始调味
加入鸡精1小勺（约2克）
加入少许白糖提鲜
最后就让生抽酱油3克从锅边淋入爆炒几下
当猪肝略微发硬之后再加入准备好的蒜苗叶爆炒几下
我们最后将蒜苗叶炒至断生即可出锅
一道创新做法的“土匪猪肝”就制作完成
下面开始技术总结
第一，猪肝最好切大片且厚一些，这样才能达到干香里嫩
第二，此菜选料不受地方限制，可以搭配辣椒或者蒜薹
第三，土匪猪肝目前没有固定的配料和做法，其特点是香辣里嫩即可
土匪猪肝的技术总结完毕

**Comment by archerdominique** [comment]
[干活]
