### ISSUE TITLE
[雪鱼探店] 新疆烤全羊 - https://youtu.be/BtTL1H7I61Y

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#245]
https://youtu.be/BtTL1H7I61Y
<p>视频时长 9:40，发布于 October 2, 2019 at 09:30PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837906d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by okiamnewhere** [comment]
**中文稿如下：**
1 
00:00:01,920 --> 00:00:04,920
新疆·和田

2 
00:00:12,800 --> 00:00:15,120
我们今天是来吃烤肉的

3 
00:00:15,120 --> 00:00:17,440
后面的师傅还在忙

4 
00:00:18,880 --> 00:00:22,240
天呐

5 
00:00:32,920 --> 00:00:36,600
完成交接

6 
00:00:39,640 --> 00:00:41,520
这一个炉子 地炉

7 
00:00:41,520 --> 00:00:43,240
差不多

8 
00:00:43,240 --> 00:00:46,440
直径长就是一步的距离

9 
00:00:46,680 --> 00:00:50,160
来 跟着我的镜头 看一看里面的羊

10 
00:01:27,520 --> 00:01:31,760
看着这个坑不大

11 
00:01:31,800 --> 00:01:35,280
而每一炉烤熟 就需要

12 
00:02:00,440 --> 00:02:02,520
站在这个地方 你都能感受到

13 
00:02:02,520 --> 00:02:03,800
它的温度

14 
00:02:04,720 --> 00:02:06,160
你看这个地方

15 
00:02:06,160 --> 00:02:08,200
它会留出来一些缝隙

16 
00:02:08,200 --> 00:02:09,800
像这个地方和那个地方

17 
00:02:09,800 --> 00:02:12,160
朝外冒烟

18 
00:02:14,680 --> 00:02:15,880
咱们等一等吧

19 
00:02:15,880 --> 00:02:18,240
等着烤肉做好了 再点

20 
00:02:18,360 --> 00:02:21,800
和我一起等待的还有这么多蜜蜂

21 
00:02:28,640 --> 00:02:33,040
烤全羊要一公斤155块钱

22 
00:02:33,600 --> 00:02:34,400
我的意思是

23 
00:02:34,400 --> 00:02:36,360
最低点多少钱的 有（这样要求）吗

24 
00:02:39,280 --> 00:02:40,480
都可以

25 
00:02:42,200 --> 00:02:43,840
自己在那边点

26 
00:02:48,960 --> 00:02:51,680
我再要一个酸奶 还有一个那个

27 
00:02:51,960 --> 00:02:54,240
还有雏鸽拉面是吧

28 
00:02:54,240 --> 00:02:55,000
对

29 
00:02:55,000 --> 00:02:56,400
再要两个这个 然后

30 
00:02:56,400 --> 00:02:59,080
待会我去那边点全羊

31 
00:03:33,440 --> 00:03:38,440
新疆的烤全羊

32 
00:04:28,320 --> 00:04:30,080
坐在这个地方 你能够看到

33 
00:04:30,080 --> 00:04:32,400
一只只全羊 从身边路过

34 
00:04:32,400 --> 00:04:33,800
刚才那一只已经卖完了

35 
00:04:33,800 --> 00:04:36,040
咱们等着新的来 去拿

36 
00:04:36,040 --> 00:04:38,280
这个就是5块钱的酸奶

37 
00:04:38,680 --> 00:04:40,920
还是有点凉的

38 
00:04:50,440 --> 00:04:52,680
看很多人都说 新疆的酸奶不错

39 
00:04:52,680 --> 00:04:54,360
咱们尝一尝手工做出来的酸奶

40 
00:04:54,360 --> 00:04:55,800
是什么样的味道

41 
00:04:55,800 --> 00:04:59,160
上面是有一层类似奶皮的

42 
00:05:09,720 --> 00:05:12,560
无糖酸奶 真的是无糖酸奶

43 
00:05:20,160 --> 00:05:22,320
来啦 来啦

44 
00:05:22,320 --> 00:05:24,480
这是抱着一只羊过来的

45 
00:05:53,040 --> 00:05:54,200
哇

46 
00:05:54,640 --> 00:05:57,920
这边切好羊排之后 称好羊排之后

47 
00:05:57,920 --> 00:06:00,240
要放在馕上面

48 
00:06:00,240 --> 00:06:02,040
然后再剁 剁 剁

49 
00:06:03,200 --> 00:06:05,480
又来了 又来了 又来了

50 
00:06:05,480 --> 00:06:08,720
多的很 一天卖多少只羊

51 
00:06:27,800 --> 00:06:31,280
一公斤的羊排 14号

52 
00:06:50,960 --> 00:06:53,760
哇 谢谢

53 
00:06:53,760 --> 00:06:57,080
咱们要的是烤全羊当中的羊排

54 
00:06:57,080 --> 00:06:58,880
它是下面放了两个馕

55 
00:06:58,880 --> 00:07:01,920
把全羊放在上面

56 
00:07:03,640 --> 00:07:05,000
但是站在那个地方

57 
00:07:05,000 --> 00:07:07,000
你能够闻到羊肉的香味

58 
00:07:07,000 --> 00:07:07,920
就像

59 
00:07:07,920 --> 00:07:09,800
你好像打开了一个锅一样

60 
00:07:09,800 --> 00:07:12,320
瞬间 羊肉的香味扑鼻而来

61 
00:07:17,320 --> 00:07:20,120
蜜蜂来和我们抢羊肉吃了

62 
00:07:22,160 --> 00:07:25,480
这次咱们先不吃肉 先吃这个皮

63 
00:07:25,480 --> 00:07:28,800
感觉这个皮 特别诱人

64 
00:07:35,920 --> 00:07:39,000
脆脆的外皮

65 
00:07:52,400 --> 00:07:54,800
它这个烤全羊 外面的皮就是咸香的

66 
00:07:54,800 --> 00:07:56,400
但是里面还是比较嫩的

67 
00:07:56,400 --> 00:07:58,960
没有很重的咸味

68 
00:07:59,600 --> 00:08:01,720
这个皮烤的像纸一样薄

69 
00:08:01,720 --> 00:08:04,440
但是薄脆的外皮下

70 
00:08:05,280 --> 00:08:08,000
裹着肥瘦相间的羊肉

71 
00:08:10,160 --> 00:08:11,760
你如果说

72 
00:08:11,760 --> 00:08:13,160
撕一点皮来吃

73 
00:08:13,160 --> 00:08:15,680
真的会满嘴流油

74 
00:08:15,680 --> 00:08:17,240
如果说觉得 （直接吃肉）吃腻了呢

75 
00:08:17,240 --> 00:08:20,560
就是撕点馕 配着羊肉来吃

76 
00:08:21,320 --> 00:08:24,080
咱们要的是肋排 所以说 骨头很多

77 
00:08:24,280 --> 00:08:26,680
吃骨头上的肉 比较带劲一些

78 
00:08:28,080 --> 00:08:30,480
是不是可以下手抓

79 
00:08:31,160 --> 00:08:35,160
感觉下手抓 好像更直接一些

80 
00:08:42,760 --> 00:08:46,240
吃肉最大的乐趣 就是直接上手抓

81 
00:08:51,920 --> 00:08:53,440
烤全羊上来的时候

82 
00:08:53,440 --> 00:08:55,160
你可以自己选择它的部位

83 
00:08:55,160 --> 00:08:58,880
如果想吃肥一点的 像我们要的肋排

84 
00:08:58,880 --> 00:09:00,480
如果说 想吃瘦一点的

85 
00:09:00,480 --> 00:09:03,000
可以要腿上的肉 也是很好的

86 
00:09:04,800 --> 00:09:06,480
像咱就是要了两斤

87 
00:09:06,480 --> 00:09:08,680
但有的人真的会要一只

88 
00:09:08,680 --> 00:09:10,880
很多人围在一起吃烤全羊

89 
00:09:21,520 --> 00:09:24,400
这个就是 真的没有一点的甜味

90 
00:09:24,400 --> 00:09:27,280
但是有这种奶香味
