### ISSUE TITLE
[华农兄弟] 狗子半岁抓来称重 - https://youtu.be/kcgq6MiBhV8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#251]
https://youtu.be/kcgq6MiBhV8
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 5, 2019 at 12:40AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
