### ISSUE TITLE
[雪鱼探店] 新疆烤肉烤包子 - https://youtu.be/dRXnF42z1oM

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#253]
https://youtu.be/dRXnF42z1oM
<p>&#35270;&#39057;时长 11:28，&#21457;&#24067;&#20110; October 5, 2019 at 09:49PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837906d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by okiamnewhere** [comment]
**中文字幕稿**很抱歉这次字幕文件损坏了，丢失了时间标签

这次我们没有点很多


就是两个大肉串


还有两个烤包子


烤包子呢 是


这个肉串是

啊 看着就想吃


因为这个包子是烤的嘛


它的外面好像会有点脏


或者说 有烤的不好的地方


可以用锉刀 把它 就是刮一下


烤的不好的地方 刮一下


这个就是我们的锉刀


把它刮一下


太烫了


这个包子特别硬


我说把它能够当砖头


真的是一点都不过分


真的是一点都不过分 太硬了


我掰一下试试吧

哇


它这里面的羊肉


而且你能看到明显的肥肉


它这个皮特别厚


即使里面有很多的汤汁


都不会漏出来


这个10块钱的烤串


差不多吧 8块肉


真是 羊肉大块吃起来才爽


它这个羊肉吃起来特别嫩


外面可能是因为有面糊


烤出来带这种脆脆的口感


真的是


吃起来特别爽


如果是普通人来吃饭


一般一个烤包子就差不多了


饭量大一点（的人）


可以再要一个肉串 就差不多了


再多 真的就吃不了了


刚才 我弄包子砸自己脑袋的时候


旁边吃包子的大爷都笑了


他可能心想


这怕是个傻子


在这边你很少看到 像（苍蝇 蚊子）


那种飞的很讨厌的东西


但是能够经常看到蜜蜂


这烤肉的签子 和我的胳膊都差不多长


吃完饭


咱们进去看一看 这些东西是怎么做出来的


走吧


在我身后（的屋里）


他们里面是在包这些


馕啊 或者说 其它的一些东西吧


我也不知道具体叫什么东西


前面（的房间）就是


大家在炉子上烤东西


师傅 这个叫什么


能听懂吗


它叫什么名字


这个是什么


肉馕


竟然能够听懂我说什么


这边写的是10块钱的烤肉大串


这个是5块钱的阔埋奇


5块钱的烤包子


大烤包子就是10块钱一个


每一个师傅好像负责的品类是唯一的


比如说 你要做烤肉馕


就一直在这个地方做烤肉馕


做烤包子 就一直在这个地方捞包子


这现在开始做 烤肉大串


现在能够看到的 这个房间里有


后面这一车的包子


你看


他们把烤包子 都是放在这种圆柱形炉子里


中间有个炉子是不一样的


它里面烤的东西也是不一样的


我们过去看一看


中间烤的是阔埋奇吗


这又是来了一车的包子


它这边的包子做的特别大


一个有手掌这么大


（能遮住）半边脸


他们把包子放进炉子里的时候


都得探下头 看一看


因为坑太大了


它这边的烤包子是一炉接着一炉嘛


等一炉的包子好了之后


要让炉子降降温


会打一些盐水进去


这样才能更好地下 下一炉的包子


目前能够看到的就是烤包子


一炉一炉地朝外边捞出来


看这个师傅 拿出来了刚做好的烤包子


他好像是要把烤包子放在这个地方晾一下


这边是擀面 揉剂


擀皮 放馅


然后把它包起来


每一道工序都有好几个人在忙


好了 今天的包子就吃到这儿


咱们明天吃什么呢


猜一猜吧


关 注
雪 鱼 探 店

**Comment by archerdominique** [comment]
我吃

**Comment by immoonancient** [comment]
> 我吃

@archerdominique 你有权限可以直接 self-assign 的

**Comment by archerdominique** [comment]
> > 我吃
> 
> @archerdominique 你有权限可以直接 self-assign 的

好的，我发现了（
