### ISSUE TITLE
【美食作家王刚】茄子的8种切法 - https://youtu.be/tsSstEYDwwU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#262]
【美食作家王刚】茄子的8种切法 - https://youtu.be/tsSstEYDwwU
视频时长 7:17，预计发布时间为北京时间10月11日晚6点

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

其实茄子的切法远远不止8种
本次跟大家分享普通家庭中能用得上的8种
首先我们用滚刀的方式去掉茄子蒂
茄子蒂也可以食用喜欢的同学可以保留
当然了嫌麻烦的同学可以直接切来扔掉
首先跟大家分享第一种切法
将茄子从中间切开然后切成均匀的小条
最后再切成段即可、
这一种形状的茄子比较适合红烧
切的时候尽量切小条均匀一些
这样才更容易炸透
下面是第二种
此法是将茄子放在菜板上面滚着切成块
所以此法俗称“滚刀块”
它原理就像削铅笔一样简单
切熟练之后即可这样快速的滚起来切
这个切法适合做“茄子烧肉”“地三鲜”或者“红烧茄子”
下面是第三种
首先将茄子从中间切开一分为四
然后将茄子翻面切刀切成菱形块
菱形块的形状比滚刀块更美观
这个切法同样比较适合第二种适合做的菜
下面是第四种
将茄子先切成后片再摆好之后切成丝
切丝的茄子适合爆炒或者清炒
所以我们不能切太细否则容易炒烂
大家可以看一下基本上切成薯条大小即可
下面是第五种
第五种切法是最常见之一
种中间切开之后直接切成片即可
同样也是众多切法种最家常的一种
适合清炒爆炒类的做法
这里大家需要注意的是尽量切成大小一致的厚度
下面开始第六种
首先我们把茄子头横切下来
然后切第一刀不切断
在切第二刀的时候切断
此法切的茄子适合在中间加入肉泥炸茄盒
大家可以按照自己的喜好来控制厚度
切的时候尽量保持四分之一的连接
这样才能放入更多的肉
下面开始第七种切法
首先把茄子从中间切开
然后斜刀切进茄子的四分之三
每刀之间的间隔大概4毫米
然后再反过来同样斜刀切另一面
这个切法的茄子适合做成鱼香茄子
此法的优势是更容易炸透和入味
剩下的一半以正常速度展示
最后一种切法是最盘龙茄子
首先在茄子的正面切进去
然后翻过来斜刀切另一面
此法在之前的盘龙茄子种有更详细的切法和做法
好了本期视频到此结束
后续会跟大家带来更多切法小技巧

**Comment by archerdominique** [comment]
我切了吧
