### ISSUE TITLE
[华农兄弟] 华农兄弟挖点摄影小哥家的番薯刚好他女儿也来了叫她帮忙捡番薯 - https://youtu.be/ggPDz4njz8g

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#264]
https://youtu.be/ggPDz4njz8g
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 7, 2019 at 09:01PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
原來老闆會自動開的，等我剛才還開了另一個...

**Comment by immoonancient** [comment]
> 原來老闆會自動開的，等我剛才還開了另一個...

科技改变命运
