### ISSUE TITLE
【美食作家王刚】美蛙鱼头 - https://youtu.be/ciHpcjXqw0I

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#280]
【美食作家王刚】美蛙鱼头 - https://youtu.be/ciHpcjXqw0I
视频时长 5:08，预计发布时间为北京时间10月14日晚6点

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

首先我们准备牛蛙4只
去掉外皮和内脏清洗干净备用
考虑宰杀这一步比较血腥
所以嫌麻烦的同学可以交给摊主处理
中途用剪刀去掉牛蛙的脚趾
然后再从中间剪开备用
下一步开始处理鱼头
准备鲜活的花鲢一条
将鱼敲晕之后去除鱼鳞和内脏
然后将鱼头取下清洗干净备用
处理的时候可以从鱼头背部下刀切开
这样更容易取鳃和清洗
主料备齐之后下一步开始准备辅料
准备酸菜一小把清洗干净之后切成小块备用
加酸菜的目的是增鲜提味
准备生姜1块拍散之后剁碎备用
准备大蒜40克切成小粒备用
准备适量的红泡椒切成小粒备用
准备麻辣火锅底料50克切散备用
底料不限任何品牌
准备干辣椒一小把剪成小节备用
碗中再加入适量的青花椒备用
下一步开始准备打底菜
准备豆芽1小把备用
准备芹菜几根切成小段放入盆中垫底
同学们也可以根据个人喜好添加底菜
下一步开始制作
首先我们把锅烧热
锅烧热之后加入少许的底油
油热之后加入适量的干辣椒爆锅
辣椒变色之后加入准备好的豆芽爆炒几下炒至断生
中途加入少许的食用盐调底味
炒至断生之后倒入盆中垫底备用
然后我们再次把锅烧热
锅烧热之后加入熟菜籽油50克烧至6成热
油温6成热之后加入准备好的料头下锅爆香
中途再加入切好的火锅底料和酸菜
然后转小火翻炒3分钟将底料炒香炒化
底料炒香之后加入适量的清水开大火烧烤
大火烧烤之后开始调味
锅中加入食用盐1大勺（约5克）
加入胡椒粉1勺（约1克）
加入五香粉1勺（约0.5克）
加入鸡精2勺（约4克）
加入白糖少许中和辣味
最后再加入生抽酱油8克
调好味之后将准备好的鱼头和牛蛙下锅
因为牛蛙和鱼头是现杀所以不需要提前腌制
主料下锅之后转中小火烧8分钟
这一步的目的是将其煮熟煮至入味
8分钟之后将主料捞出放入盆中
然后再加入适量的原汤
下一步开始准备泼油
首先我们把锅烧热
锅烧热之后加入熟菜籽油500克
将油温烧至4成热之后加入准备好的辣椒和花椒
然后转大火不停的搅动辣椒
将辣椒烧至棕色之后再一次性泼在牛蛙和鱼头上面
最后再撒上适量的香菜即可
一道重口美味的牛蛙鱼头就制作完成
下面开始技术总结
第一，牛蛙和鱼头必须选择现场宰杀，否则不鲜有腥味
第二，牛蛙和鱼头都不用提前腌制
第三，此菜在后期煮制的时候必须小火慢煮这样才能入味
第四，嫌麻烦的同学可以交给摊主宰杀
牛蛙鱼头的技术总结完毕

**Comment by immoonancient** [comment]
还没发布呢，发布了再 close
