### ISSUE TITLE
【美食作家王刚】葱烧鲫鱼 - https://youtu.be/ZurD6odu08Q

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#285]
【美食作家王刚】葱烧鲫鱼 - https://youtu.be/ZurD6odu08Q
视频时长 5:45，预计发布时间为北京时间10月16日晚6点

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

首先我们准备小鲫鱼10条
在鱼嘴中插入两根筷子
然后用刀去除鱼鳞和内脏清洗干净备用
插上筷子可以更好的操作
嫌麻烦的同学也可以交给热心的摊主处理
鲫鱼宰杀好之后需要用清水多清洗几遍
因为做菜就像做人一样一定要干干净净明明白白
鲫鱼清洗干净之后下一步开始准备辅料
准备大蒜和生姜各1小把剁碎备用
其中生姜可以略多一些这样能压住鱼的腥味
准备仔姜1小块切成姜丝备用
准备几个二荆条切碎备用
加二荆条的目的是增加鲜辣味
准备适量的小米辣切碎备用
不能吃辣的同学可以适当的减少用量
准备小葱1把切成小段备用
最后准备酸菜2片切碎备用
辅料准备好之后开始腌制鲫鱼
将鲫鱼表面切出一字花刀备用
切记刀口不能太深否则鲫鱼下锅容易煮烂
盆中加入食用盐4克
加入适量的料酒拌匀腌制5分钟备用
下一步开始制作
锅烧热之后加入适量的熟菜籽油（约60克）
油温6成热之后加入一半的姜蒜末和酸菜下锅
然后将酸菜和料头翻炒几下炒出香味
料头炒香之后加入适量的清水
清水的量不能太多否则容易抢味
烧开之后开始调味
锅中加入食用盐1大勺（约5克）
加入味精1小勺
加入少许白糖
加入适量的生抽酱油（约6克）
同学们鱼肉适量的多加点生抽咸一些更入味
最后再加入少许老抽调色
调好色之后将处理好的鲫鱼依次下入锅中
鲫鱼下锅之后转小火烧6分钟
将鲫鱼烧熟烧至入味为止
6分钟之后将鲫鱼捞出放入盘中备用
然后将准备好的姜蒜辣椒依次下锅
再加入适量的水淀粉把汤汁收浓
汤汁收浓之后将切好的小葱下锅烧至断生即可
最后将汤汁淋在鲫鱼上面即可食用
一道非常美味的葱香鲫鱼就制作完成
下面开始技术总结
第一，鲫鱼最好现杀现做，这样的味道才足够鲜美
第二，最后成菜之后可以再泼上花椒油增加麻味
第三，此菜为鲜辣味最好不加豆瓣酱
第四，烧鱼最好能略微咸一些这样才够味
葱烧鲫鱼的技术总结完毕

**Comment by GUThe** [comment]
starting now
