### ISSUE TITLE
[华农兄弟] 华农兄弟突然想吃去烫皮河边搞点沙子来炒很香哦 - https://youtu.be/p_qNwOuo_H8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#287]
https://youtu.be/p_qNwOuo_H8
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 13, 2019 at 06:20PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
