### ISSUE TITLE
[华农兄弟] 华农兄弟带老弟上山砍竹子顺便看一下山上的野果熟了没有 - https://youtu.be/CY3i9OFc8PY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#290]
https://youtu.be/CY3i9OFc8PY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 13, 2019 at 10:42PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
