### ISSUE TITLE
[华农兄弟] 华农兄弟河里面好多鱼我们去钓一下顺便网一点来吃 - https://youtu.be/tTzOhz1kzDA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#300]
https://youtu.be/tTzOhz1kzDA
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 16, 2019 at 08:51PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
