### ISSUE TITLE
[华农兄弟] 华农兄弟摘两个西红柿来吃顺便摘点给小猪吃再抓它称一下 - https://youtu.be/EmxlMsPbfzY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#303]
https://youtu.be/EmxlMsPbfzY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 17, 2019 at 06:44PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
