### ISSUE TITLE
[华农兄弟] 华农兄弟看一下写名字的拿藤果熟了没有顺便摘点南瓜跟玉米 - https://youtu.be/estbwzp5fvQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#305]
https://youtu.be/estbwzp5fvQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 18, 2019 at 06:36PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
發佈了
