### ISSUE TITLE
【美食作家王刚】砌烤架，四伯吐槽竹鼠 - https://youtu.be/hB3RsrCfDEQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#309]
【美食作家王刚】砌烤架，四伯吐槽竹鼠 - https://youtu.be/hB3RsrCfDEQ
视频时长 5:00，预计发布时间为北京时间10月20日晚6点

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

哈喽大家好
我跟我伯爷现在准备把这个砖搭一下
就是搭一个灶
明天的时候就可以直接烤羊
然后我也请了一些朋友过来帮忙一起弄
这哈要这样子放（砖）了 放二次墙才牢固
二次墙
哦 你看那些修百多层楼的那些都是这样放的二次
这样子只要这中间这一截
哦 要得嘛要得要得
这又要这样放噻
对 对头的
这哈就这样子放噻
它（灶）不是到时候不稳当 垮了来咋子办呢
砌长点 这么长够不够
嗯 可能都还要长点
还要长点就还要长点噻
加那么长够了吧 这么长够不够
再长一点要得
四伯爷这里头稀稀哈哈地摆都可以
可以啊
这里面不摆实的 摆实的话要搬好多砖哦
这边要这样子摆一哈
好得有那么多木炭哦有那么多
买了两箱 肯定是够的
我看这边都还差 还差得多
差不到好多了
全部都要放到这里（这么高）吗
你上面这个空间呢
这里还要这样子放一匹
就是这样子的噶
这个要摆出来点
可以 可以啊
OK了噶
可以 四伯这个想法很不错
这样子就要得了 
随便你咋子整 这个很扎实
你就是（把）肥猪放在上面都撑得起
你的意思（是）二回烤猪哦
啊 是嘛
今天他们卖了些25（块钱）的
我倒是卖的23、24 
整归一（完）了就等明天羊子杀归一直接烤就是
烤的料那些我都配归一了
要得啊
我们现在杀这个羊子是请的专业的师傅来
我们自己可能下不了手
这个伯爷也会
但是还是请师傅来做吧专业的事情
好吧今天我们这个灶也搭得差不多了
我们搭了一下午就等着明天正式烤羊
今天的视频就到这里
拜拜

四伯爷你还是说拜拜噻
拜拜
这样明天还是把竹鼠杀来烤了嘛免得它到处窜
窜来你那（屋）里头那天你老爸回来打开门没有关
里面的亮瓦都遭打烂了几匹 跑出来
那天我压了五匹砖 25斤是不是
嗯
我后头一对给它加来压起
这哈就 它就窜不出来了
不关事 再留它几天
凶得很
好
这个门呢咬了那么厚一层了
就是那个主门
拿给竹鼠咬烂了啊
那不是咋子呢
我起来我说哪儿哗哗哗的
我六点钟就起来了
我看是昨早上 是昨早上噶
我说咋子哗哗哗的哦
我连忙给它两脚 它搞忙了就跑起进去
跑进去跑到它那个瓦缝缝那儿去藏起
我走起进去就把它揪起来
我说你还凶
这样下去可是不行的
总有一天 嘿嘿
总有一天它要遭烤了
好了 就这样子嘛
太霸道了它的牙齿太霸道了

**Comment by immoonancient** [comment]
安排出了点问题... 我现在开始

**Comment by immoonancient** [comment]
已经在 YouTube 发布了
