### ISSUE TITLE
【美食作家王刚】炖羊烫烤羊肉 - https://youtu.be/drnOZmhSNmI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#310]
【美食作家王刚】炖羊烫烤羊肉 - https://youtu.be/drnOZmhSNmI
视频时长 6:19，预计发布时间为北京时间10月21日晚6点

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

泡一下
泡过一会儿再来腌
不要干醉了哈
哦哟 这个酒
这个酒不得了
这白酒
把这个羊肉腌几个小时
腌入了味
待会儿腌入味了之后就直接把它夹在架子里面直接烤
腌它2-3个小时差不多
天下武功唯快不破
刀是什么刀
这是我专业的杀猪刀
我来
这个我压个把小时没得问题得
你这小事一桩
我们先烤一波来试一下
说一下腌肉过程呗
这个还不简单
就是这个肉砍出来了之后泡一下
泡2-3个小时把血水泡出来
泡出来之后放盐、酱油、姜、葱
就这样就OK
不用搞得太复杂
其实烤羊肉有的地方腌都不用腌也不用洗
直接把肉弄上去烤
来 打开我们这个架子
哇塞
肯定很好吃
这个皮子都烤缩了
怎么样
嗯 好吃
羊肉最好现杀现做
没有羊的同学可以用兔子代替
用猪代替
用猪那成本更高哦
哎呀
这个汤不摆了
现在我们这个烤羊肉也做完啦
羊肉汤也做好啦
现在就烤一些蔬菜
然后我们从早上8点多一直做到现在天黑
从羊肉开始烤就一直吃吃到现在
我们今天就拍到这里
我现在要继续吃

**Comment by kdliu86** [comment]
initial me beh
