### ISSUE TITLE
[华农兄弟] 华农兄弟给猪打扫一下猪窝再给一些稻草跟南瓜给它们 - https://youtu.be/Q5J5vgYMt0c

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#311]
https://youtu.be/Q5J5vgYMt0c
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 19, 2019 at 01:04PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
發佈了
