### ISSUE TITLE
[华农兄弟] 华农兄弟铁门烂掉了我们用铁丝绑一下避免狗子到处乱跑 - https://youtu.be/CET3GzrKipU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#316]
https://youtu.be/CET3GzrKipU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 20, 2019 at 11:34AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
發佈了
