### ISSUE TITLE
[华农兄弟] 华农兄弟竹鼠日常喂养喂点米糠拌饭看它们吃得多开心 - https://youtu.be/NiVVNa1O3aY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#317]
https://youtu.be/NiVVNa1O3aY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 20, 2019 at 02:33PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
發佈了
