### ISSUE TITLE
【美食作家王刚】修房子算账 - https://youtu.be/S0OOmF5maiU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#32]
大家好，这是刚哥最新私享视频，便于大家提前添加字幕，修房子算账 https://youtu.be/S0OOmF5maiU 暂定发布时间为8月11日北京时间晚6点

**Comment by tiffychou** [comment]
剛剛嘗試翻譯完畢了
但是GitHub我真心不會用啊
我是在Youtube Add translation 那裡用的
請教如何上傳？

**Comment by immoonancient** [comment]
@tiffychou 

请先制作中英文对照的翻译稿，然后我们一起审核讨论，最后汇总了再传上 YouTube

翻译稿的范例看这里: [subtitles/wang-gang/](https://github.com/immoonancient/YTSubtitles/tree/master/subtitles/wang-gang)
GitHub 如何上传文件看[这个教程](https://github.com/immoonancient/YTSubtitles/blob/master/tutorial/upload.md)

如果实在搞不定就把翻译稿发直接发在这里吧，我们帮你 GitHub 的相关操作
（不过这样的代价就是你不能出现在 [Contributors 名单](https://github.com/immoonancient/YTSubtitles/graphs/contributors)里了）

**Comment by tiffychou** [comment]
我嘗試上傳文件了 希望是對的
辛苦了！謝謝

**Comment by immoonancient** [comment]
@tiffychou 请问你传到哪了…？我没看到

**Comment by immoonancient** [comment]
@tiffychou 或者加我微信 immoonancient ，看看是什么问题

**Comment by GUThe** [comment]
已上传，close
