### ISSUE TITLE
[华农兄弟] 华农兄弟帮房东把山上的小竹子砍掉拿去喂我们家的竹鼠 - https://youtu.be/0Az2NrrB074

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#321]
https://youtu.be/0Az2NrrB074
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 22, 2019 at 05:21PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
