### ISSUE TITLE
【美食作家王刚】土豆炸香蕉 - https://youtu.be/jQ4Ht6z341I

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#326]
【美食作家王刚】土豆炸香蕉 - https://youtu.be/jQ4Ht6z341I
视频时长 5:06，预计发布时间为北京时间10月26日晚6点

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

首先我们准备土豆一个（约300克）
将土豆去皮之后再切成细丝备用
同学们土豆最好切细一些
刀工不好的同学可以用刮刀擦土豆丝
土豆丝切好之后放入清水中多洗几次
这一步的目的是去掉土豆中的淀粉
然后准备香蕉2根剥离出来
再把香蕉切成小块备用
大概切成2厘米左右即可
下一步开始准备调糊
盆中打入鸡蛋1个
加入适量的玉米淀粉边搅边加水
将玉米糊调成粘稠拉丝即可
然后加入少许的植物油搅拌均匀
加植物油的目的是让玉米糊更加蓬松有粘性
这样的糊才能更容易挂在原料上面
然后加入香蕉拌匀上糊即可
最后准备适量的番茄酱备用
不喜欢酸甜味的同学可以将其换成沙拉酱
下一步开始制作
首先我们把锅烧热
锅烧热之后加入宽油
然后将油温烧至7成热
油温7成热之后将切好的土豆丝下锅
开大火将土豆丝炸至熟透
土豆丝熟透之后捞出重新将油温升高至7成
然后将土豆丝下锅复炸至金黄酥脆
此菜必须宽油炸至，舍不得宽油的同学谨慎观看
土豆丝炸至金黄之后捞出备用
去除油中的残渣之后下一步开始炸香蕉
油温烧至6成的时候再把香蕉依次下入锅中
利用油的余温将香蕉炸至金黄即可捞出
这一步油温不能太高否则会将其炸焦
最后把香蕉均匀的沾上番茄酱再裹上土豆丝即可上菜
一道口感丰富香甜的小甜品就制作完成
下面开始技术总结
第一，土豆丝切得均匀且越细越好，否则成熟的不一样
第二，不喜欢番茄酱的同学可以选择沙拉酱
第三，此菜必须宽油炸至，油太少无法操作
小甜品的技术总结完毕

**Comment by immoonancient** [comment]
沟通后决定推迟一天发布
