### ISSUE TITLE
[华农兄弟] 华农兄弟发现在路边好多青菜摘点来吃顺便再摘点黄豆和萝卜 - https://youtu.be/e9irQlQKjpU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#327]
https://youtu.be/e9irQlQKjpU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 23, 2019 at 10:40PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
