### ISSUE TITLE
[华农兄弟] 华农兄弟竹鼠和老鼠放一起会怎么样上山抓只老鼠回来试一下 - https://youtu.be/1q-KaJEG7CA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#329]
https://youtu.be/1q-KaJEG7CA
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 25, 2019 at 11:40AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
