### ISSUE TITLE
【美食作家王刚】买野猪 - https://youtu.be/PaL5RibdwUk

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#351]
【美食作家王刚】买野猪 - https://youtu.be/PaL5RibdwUk
视频时长 5:05，预计发布时间为北京时间11月1日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

看嘛 这个就是野猪
是啊
杀过这个野猪没有
没有
没有杀过嘛
第一回杀吗
第一回杀
就要那个小点的
大的肉烤来不好吃
你说那条野猪有好重
那个啊
嗯 那个小的
可能有40多斤
这个猪还是有点攻击性
它不是纯家猪也不是纯野猪
它是野猪种性
嗯 是野猪跟家猪配出来的
杀这个猪一个人按得住不
我一个人轻轻儿的就把它杀了

轻轻儿就把它捅了
金钩儿 钩住它提它起来割它一刀就解决了
这个跟华农的野猪不一样
他那个是香猪
这个是野猪那个是香猪
哦
我的杀猪刀起码有它一半长
你一说它都吓到了
慢点 我穿过来点不是你抬不起
这有好重哦
提一会儿就重了
慢一点四伯爷
69斤
69除开笼子46斤
好
我说有40斤嘛
40多
哦哟
好的 要得
好
它不重还凶得很
你后面没有提起来
来
诶呀
我还没有喂过野猪第一次喂
这样它还多荣幸哦
那还用说 它是绝对享受
我修起还没喂过猪 第一次就喂这个野猪
 哦 出来了
羊肉烤起好吃
这个野性的野猪烤起可能更好吃哦
隔几天你那天有空整来试一下嘛
我杀了30、40年的野猪还没杀过野猪我拿来试一下看嘛
它都害怕了听你这么说
那个脑壳打整才不费力哟 平平顺顺的
你朝它念什么哦
那个苕藤是你的啊
在外面拿的
不应该朝它念吧
哦噢
这又喂不了多久
我接着2、3天就弄来杀了烤来吃了
我要是吃到这个野猪肉好吃你就要经常烤给我吃哦
经常 现在好贵哦
再贵只要买得到就可以
只要它吃起舒服管它钱不钱哦
40多斤还没有上次的羊子重
猪脚杆拿来炖
有好多个人就炖好多坨
你听到没嘛好多个人就干你好多坨
那这样我就去弄烧烤架
那个架子小了烤它不下
烤不到啊
嗯 烤不到重新焊个架子
可以

**Comment by Koi111** [comment]
Yep
