### ISSUE TITLE
【美食作家王刚】创新无水姜葱焗鲤鱼 - https://youtu.be/gvh5RZsQnhw

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#352]
【美食作家王刚】创新无水姜葱焗鲤鱼 - https://youtu.be/gvh5RZsQnhw
视频时长 6:31，预计发布时间为北京时间11月3日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

四伯爷 今天弄条鱼给你吃
要得
就拿姜葱来给你煎
你好生点整点好的来把我的身体补起来
拖垮了还要不得
就是这条鱼
要得啊
好生点哈 板下去了你在那儿（池塘里）去摸不到哈
开玩笑 从我的手头板（逃）不脱
这鱼好瘦哦
你准备咋子吃嘛这条鱼
拿姜葱来煎哈 弄来过焖
整锅巴鱼吗还是
跟锅巴鱼有点像
又不是得水煮鱼噶
不是得 这个不加水
就整一整条吗
整条的花不花刀
对 就是这样
在这个里面放点盐
防止这个鱼粘锅
小点火哦 四伯爷
这个鱼应该是第一次吃
这个菜在川菜中没有这个做法
是啊
川菜中哪个拿猪油来做鱼嘛
都是用的菜油
这个是创新菜
好嘛 你就创新菜嘛看你又创什么新嘛
创出一个新世纪来
新世纪倒不是是一个创新菜
等这个鱼煎到另一面黄了再放点盐
然后再翻面这样就不会两面都粘得很厉害
煎到这个时候把姜葱放进去慢慢炸
可以啊
才上得到味哒
然后这个时候火要小
都烧得小
再小都烧熄了
然后把这个锅盖盖上
让它慢慢的焖
把鱼鳔一起丢进去
慢慢煨
趁这个时候来打一些汁
先放一点酱油
再放一大半的料酒
料酒放了再放一点耗油
耗油不能太多一点点就可以了
然后再放一大勺这个白糖
待会儿提味道就是这个东西
这个菜名的话应该叫做姜葱焗鲤鱼
我看一下这个怎么样了
四伯爷这个火可以稍微大点了
好
现在我们这个鱼两面已经煎香了
下面那个姜葱味也煎出来了
然后再翻它一下
你看 这一面也是金黄金黄的
四伯爷
啊
你看哈嘛这个鱼煎到这个时候
就把这个搅拌均匀从边上淋下去
那中间不淋啊
中间要翻面的
好 然后把锅盖盖起
这哈可以烧大点撒
不要太大就是要小火
烧它过几分钟就可以了
这个鱼不辣
吃起来这个肉还是比较嫩
姜葱味比较重鱼的鲜味都在里面得
就跟白味差不多
哦 好香哦
这个汁水把它淋上去
现在这个时候鱼就不能翻了
我们这个筷子插这个鱼身上
轻轻的插进去就说明这个鱼已经熟了
准备起锅了
四伯爷
来 动手
欣赏哈看
尝哈看嘛这个鱼不辣
而且是姜葱把它慢慢焖出来的
姜葱加猪油
为什么放猪油不放菜油呢
这个就是猪油的吸附力更大
味道巴得更紧
有味吧
可以
嗯 好吃
嗯 这个味道是不一样
真的吗
嗯
这个鱼我是实验了大概10多次吧
就是把它煎
放油下去两面煎
把这个腥味去一下
煎好了之后再放姜葱下去
放到油里面满满炸
然后把锅盖盖起来
把这个姜葱的香味进到鱼里面
最后调料汁
放点这个酱油料酒耗油
耗油白糖给他搅匀一下
白糖稍微重一点点
搅匀了以后等姜葱熬香了再倒进去
再把锅盖盖上焖一会儿就可以了
真的好吃 这样整起
吃撒 拈来吃撒

**Comment by WuStevenShengyang** [comment]
我来吧
