### ISSUE TITLE
[华农兄弟] 华农兄弟平时在家随便搞点菜吃今天兄弟来了多煎两个蛋 - https://youtu.be/PqhvD6SYCV8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#355]
https://youtu.be/PqhvD6SYCV8
<p>&#35270;&#39057;&#21457;&#24067;&#20110; October 30, 2019 at 11:20PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
