### ISSUE TITLE
【美食作家王刚】烤野猪 - https://youtu.be/Oe3uftVslek

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#361]
【美食作家王刚】烤野猪 - https://youtu.be/Oe3uftVslek
视频时长 10:18，预计发布时间为北京时间11月6日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

  四伯爷这是什么刀
这是杀猪儿做烫皮的刨子
你磨那么快咋子安
不磨快就刨不动
要磨一下不是那个刨子刨不动
这个也是吗
这个也是
好我去烧水
要得好
好得
挂得稳吗
三百斤的嘛也挂得起啊
这个野猪的毛
跟家猪的不一样
嗯跟家猪不一样
没有我想象中那么难刮
但是也不是那么好刮
毛比较硬还会扎手
那个毛去开咋子是白色的呢
怎么不是呢
这把刀儿好快
肯定很快啊
咦这个猪肝才安逸
嗯
炒得到一盘子不好大哟
我把它弄过来
好好好要得要得取下来
好可以了
经过上次我们烤那个羊
现在我研究了一点新花样出来
就是改进一下这个技术
就是腌的时候我切点柠檬
切点柠檬水然后加一点那个料酒
一起放到这里面待会用来直接喷
防止那个猪肉温度过高
防止它糊
既可以去腥又可以降温
切开
这个柠檬去腥效果比较好
哇这个不好弄
这个也不要丢待会跟那个姜葱
一起剁碎了拿去腌
这个是柠檬汁
我自己配的料酒
刚刚好
嗯可以
然后这个给它切碎
拿来跟那个姜葱一起切碎了
放盐来抹在那个猪上面
腌味腌底味
再放点盐
嗯可以有点咸
加点水
差不多
腌猪肉了先
我们先用这个刚刚调的酱料涂一下
腌一下给它入一下味
好腌在这里
一会就可以烤啦
这个位置吧
拿稳拿稳
好
没挂到好多肉哦
钩到了肉你看嘛
我马上把它拉起来就晓得了
四点钟了可以生碳烤起了
可以升堂了
嗯升堂
生碳
这个猪小了下次杀个大点的猪儿来吃
那个部位咋个炒起好吃那个部位的肉咋个炒起好吃
对我伯爷三十多年的那个经验
可以告诉你们这个猪怎么样去分解
哪一个部位该怎么吃
这个是我伯爷的专业
这一块的脖子肉比较厚所以要多一些碳
然后后面的话要矮一些
假如我们把这个火离得太近了
表面烤焦了中间还没熟
因为这个肉最厚的地方 有这么厚
待会烤熟了再用把刀把它划开
划开了再喷上我们那个姜姜葱还有那个料酒
现在我们这个碳已经起上来了但是火焰还没起来
现在这个天快五点钟了
可能我们吃到这个烤猪的时候都是晚上天黑去了
正好嘛天黑的时候
那个时候肯定肚子饿了
等这个碳起来了就很快了
但是我又不想两下把它烤熟
因为快速烤熟的猪肉表面是焦的里面里面还有水份
一点都不好吃 这个一点要把它烤干烤脆
把水份烤干一点然后时间烤长一点才对得起这个野猪肉嘛
看到了吗 这个葱皮已经烤干了
烤干了说明这个火力已经起来了
现在这个肉已经收紧了
把它割一下稍微
让它这个中间能够熟得更均匀一点
用刀尖慢慢的轻轻的给它划一下
这个是猪的脖子的位置
这个位置的话要划深一点
因为它的肉也比较厚
给它插一下
更均匀一点
下面的油滴得噼里啪啦的响
听到了吗 这个下面的皮已经脆了
你看这个皮已经脆了
我们这个猪从三点多不到四点多烤到现在已经烤了两个小时了
刚开始是碳不够
现在我的这个碳已经加上去了
然后我现在把这个碳烧了再平一下
你看这个都已经快黄了 
转过来平起来
现在这个已经很黄了 
现在我要搞点这个上去因为它温度有点高
得给它降一下
降一下温的话它就没有那么容易焦
啊这个肉好吃
这块插下来给小孩子吃
他们不吃辣椒
然后剩下的继续再弄上去接着烤
你要什么沺沺割一块给你
我也要吃
我要
沺沺等一下啊
来
香不香
嗯
你们吃得辣不辣
吃得辣的话多撒一点
终于好啦三个小时啊这个等了
放上来吧
四伯爷快来这里
我还有点
你听哈看
哎哟那个响声还有点好唉
烤焦啊的哦嗯是
安逸安
我剁一坨给你吃
这坨
这个的皮子最安逸
我尝一坨
咦 安逸安
比上次那个烤全羊都鲜
嗯
很脆这个特别的脆
这个比竹鼠还要脆
安逸
嗯
好吃
我弄一坨肉给你吃
安逸
好吃真的好吃
嗯 真的安逸
四伯爷有啤酒没得哦
有
有我们喝点啤酒嘛
好嘛好嘛我去拿一瓶来
好啦本期视频就到这里啦
我们要开始吃肉喝点小啤酒
拜拜

**Comment by immoonancient** [comment]
抓不到人，我做吧😂
