### ISSUE TITLE
【美食作家王刚】开家庭小灶铸铁锅 - https://youtu.be/WyUIcyHy00U

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#362]
【美食作家王刚】开家庭小灶铸铁锅 - https://youtu.be/WyUIcyHy00U
视频时长 5:45，预计发布时间为北京时间11月8日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

哈喽大家好
前几天我跟我伯爷
我抱了很多那个酱油回来
跟大家分享一些关于酱油的一些小知识
今天我来跟大家分享一下关于铁锅的小知识
 噢哟 这个锅好重哦
这个锅适不适合家里面用
这个锅不适合我们家里用
我们家里用的三水锅
就是这么大
那种大锅
像你这种锅我们农村煮猪食哪里要得嘛
一锅猪草一大摞
抄来吃这个也不得行
你这个重了 要很大的劳动力

没得劳动力还不得行还簸不转
簸不转
是嘛
我伯爷说了这个不适合农村里面炒菜
这种锅呢 只适合城市里面可以移动可以拿起来翻
其实这个锅大家不知道的是
这种锅其实也有2种
一种是平底
这个就是平底
这个是平底锅
一种是圆底
为什么有2种呢
这个平底的话放在灶上面就比较稳
但是这个圆底的
更适合拿起来翻
更适合拿起来抛
其实这两个各有所长
之前有很多粉丝也在问
就是这个锅怎么样去开
问我涂层锅需不需要开锅
其实我想说涂层锅不需要开锅
直接把它洗干净就可以了
如果是生铁锅的话就必须要开
熟铁也需要去开一下
如果熟铁上面有涂层的也不能开
应为你一烧那个涂层就坏掉了
然后今天跟大家分享一下这个锅
该怎么样去开
开这个锅
还有一些保养还有维护
其实我们这个锅只要把它烧得冒烟就可以了
烧到冒烟之后 我们不能马上弄冷水上去
因为它有炸锅的风险
就是容易裂开
要让它温度凉下去
用手试一下
把它凉下去了之后再用猪油来擦
擦一遍就OK
好香哦
安逸
这哈锅打饱牙祭了
嘿嘿打饱牙祭了
嘿嘿
按下去滋它
反过来也给它滋一哈
我们第一次开锅的话把锅的反面也给它涂一下油
生铁锅唯一不好的就是它要生锈
生了锈之后就是把它烧热
烧热了用油来擦
那个锈自己就会掉了
你看这个锈我们用油直接把它擦掉了
这个油摸了是要安逸点看起来亮光光的
嗯
生铁锅就是这样的这个要拿油来给它涂满
其实我们的粉丝从这两年关注我以来
几乎每一天都有粉丝再问
就是让我给他们推荐一款好一点的锅
这个锅其实它好在什么地方呢
我想跟大家说的是这个锅用的材料就是我们农村土锅的那种材料
生铁直接把它压出来的
现在就是找到一个好一点厂家
按照我的要求生产出了这么一款锅
这款锅就像相当于是把农村里面的土灶
把它缩小比列然后加上了这个把柄
手柄 不是把柄
然后把这边耳朵加上这个得话就可以在自己自家里面就可以炒菜
再一个就是还有它的价格
不贵
一百多块钱
还有就是这个锅 它的纹路
这个里面的纹路就跟我们农村烧的大锅的纹路是一样的
这3口锅都是我亲手开的
然后还有一些锅待会儿也会把它开出来
然后看完我们这个视频的话可以在我们评论区互动一下
到时候随便送了吧
就这3个锅
互动最高的粉丝就给它送掉
把这些也弄来上起
把它开了
这个还多稳当哦
使劲车
哦 其实刚刚还有一点没有说
没给你们说这个锅
生铁锅要是长时间不用
一定要用油把它涂满了再放起来
绝对不可以用洗洁精洗干净了再放
因为用洗洁精洗完之后的话它那个水会腐蚀这个锅
然后这个锅肯定会生锈
可以了

**Comment by immoonancient** [comment]
已发布，收工～
