### ISSUE TITLE
[华农兄弟] 华农兄弟摘点老王家的柿子尝一下顺便再去摘点野果 - https://youtu.be/x09aYfC7l6M

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#364]
https://youtu.be/x09aYfC7l6M
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 5, 2019 at 07:36AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
