### ISSUE TITLE
【美食作家王刚】小灶冷吃牛肉 - https://youtu.be/AUlV2UnIRxs

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#370]
【美食作家王刚】小灶冷吃牛肉 - https://youtu.be/AUlV2UnIRxs
视频时长 10:21，预计发布时间为北京时间11月11日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

哈喽大家好
今天剪一点干辣椒 
好有这个牛肉
买了差不多10斤
10斤牛肉配2斤这个干辣椒
炒来做冷吃牛肉
这个冷吃牛肉要凉了之后才好吃
就让它浸泡
把这个油啊味道这些全部进去了之后
再拿来吃
而且这个干辣椒要剪成丝的可能味道更好一点
味道可能差不多就是更好看一点
我还准备了这个辣椒面
辣椒面都是用两种
就是用3种辣椒来炒
现在我们要用这个姜拍一下
还有这个大葱
等一下煮这个牛肉
因为这个牛肉比较大坨
都这么大一坨
总共有3大坨
我估计一锅炒不完要炒两锅
煮牛肉要加一点料酒可以去下腥
煮这个牛肉的时候我加了点八角桂皮香叶一起
刚才我们这个打出的浮沫都是黑的
黑的就是血水
那个真的是血
现在为什么是白的
因为血水已经煮出来了
所以打浮沫的时候也不一定全部要打干净
主要打到这个浮沫变成白色的就没有什么大问题
好了 现在我要把这个牛肉捞出来准备切一下
这个牛肉已经煮了1个小时了
当时说煮40分钟因为这个牛肉实在太大块
10斤牛肉煮出来缩水
5斤都不到了
可能只有4斤多
老出来要让它凉一会儿
凉一会儿我们再来切 现在切的话是烫手的这个
这个牛肉看都看得到非常紧实
现在这个牛肉已经冷得差不多但是还在冒热气
就把它切成粗丝
有多粗呢大概就是筷子这么粗就对了
因为这个牛肉的纹路有的是横的有的是竖的
所以我们在切的时候
直接你怎么样子切更好久可以了
可以不用去考虑它是顺的还是逆的
待会儿姜和葱第一切大块一点
我们炒好了之后把这2个东西挑出来
如果放在里面的话
一是这个放久了会发酸
如果这两个不挑出来这个牛肉的保质期没那么长
这个得话直接切成段就可以了
方便更一下夹出来
放进去
可以啦 下一步开始炒一下它
我们这个菜油烧到它冒大烟的时候就说明已经是熟了
然后再放姜葱下去炸一下
把姜葱的香味炸出来了之后再放牛肉进去爆
牛肉爆到干香了之后再放干辣椒
再放其他它的一些调料
我们把这个姜葱炸到金黄了之后就要把它捞出来
少加一点花椒
 一小把
大家听到响没有
响的话就说明这个牛肉里面水分还是挺重的
这一大盆分2次炒吧1一次也炒不完
把这个牛肉里面的水份给它煸干煸香
现在加点这个陈皮
我们一般炒这个牛肉的时候千万不要只看颜色
不能只看这个肉的颜色好要经常试一下
要看它这个里面的水份
够不够干
够干的话我们就进行下一步
有的时候我们看这个牛肉其实已经
颜色够了但是里面还是水份不够干
这样也是不行的
这个牛肉已经爆得干香了
 现在放这个辣椒
花了一下午剪的这个辣椒
真的是很不容易
辣椒和籽一样一半
也不能只放辣椒
辣椒只管辣
这个籽的话就管香
这个有点满
我想拿起来翻一下
翻过来了
这个干辣椒下去把它爆香
爆香了之后待会儿再加一点刚才煮牛肉的原汤下去
把这个肉的味道收进去
把原汤收干了之后再放点辣椒面
然后再开始调味
我都闻到香了
加点原汤进去
刚才煮肉的原汤

然后加这个原汤的话慢慢给它收
可以把辣椒的这个香味收到肉里面去
而且还没那么燥
我们最后再加一些糖
这个口感就很不错了
现在这里面已经收干了
调下味就行了
调味的话
我们只用生抽酱油 
然后白糖
加一点点醋
再放一点其他香料就可以了
放一勺
放点香料粉 花椒面
然后再放点芝麻
再抓一点点白糖
再放一点醋
好啦 这个冷吃牛肉就做好啦
现在就是关火
让它冷
现在吃的话味道是有一点
但是不是很足
如果我们炒冷吃
冷吃系列的东西
炒的时候味道已经够了
然后放一段时间你会发现
太咸了或者是太辣了
或者是说过头了
这个时候炒
炒到这个时候热的时候吃
感觉味道差那么一点点
它凉了之后
这个味道就非常的到位
好啦 我们现在等它凉一下
把它倒出来凉一下
其实加一点辣椒进去炒出来还是蛮多的

**Comment by max-sun-hongyi** [comment]
ha lou da jia hao, zhe ge shi ping wo fan le. :1st_place_medal:

**Comment by immoonancient** [comment]
咦，bot 挂了？
