### ISSUE TITLE
【美食作家王刚】木须肉 - https://youtu.be/JAtFWFeEbEw

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#371]
【美食作家王刚】木须肉 - https://youtu.be/JAtFWFeEbEw
视频时长 5:05，预计发布时间为北京时间11月9日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

首先我们准备里脊肉1小块（约200克）
将里脊肉切成3.5毫米左右的片然后切成肉丝备用
通常来说鲜肉在切的时候容易不规则
时间充裕的同学可以将其放入冰箱冻2小时再切
切的时候将肉片整齐的码放起来
码放得约平坦约好切
肉丝切好之后加入清水清洗干净
因为鲜肉中会有血水和杂质
清洗干净之后挤干水份下一步准备腌制
碗中加入少许是食用盐和料酒
然后将肉丝搅拌均匀收紧水份
拌匀之后加入适量的植物油拌匀
这一步的目的是让其下锅不粘连
此菜不勾芡不加水
所以在腌制肉丝的时候不必加淀粉和鸡蛋
下一步开始准备配菜
准备适量的黄花菜和黑木耳
将泡发好的黄花菜和木耳撕开备用
这样才能更好的将其炒透
准备适量的青瓜和胡萝卜切成菱形片备用
同学们也可以将其换成玉兰片
准备鸡蛋3个打入碗中
加入少许食用盐搅散备用
蛋液最好能充分的朝着一个方向搅拌
这样的目的是让空气进入
让鸡蛋能承受高温煎至
下一步开始制作
首先我们在锅中加入适量的清水开大火烧开
大火烧开之后加入准备好的黄花菜和木耳焯水40秒
木耳属于菌类食物必须加热熟透
否则快炒不熟容易发生危险
中途再加入少许的食用盐
焯水熟透之后倒出备用
然后把锅烧热
锅烧热之后加入适量的植物油
油温6成热之后将蛋液下锅煎至金黄干香
同学们油多煎蛋必须开大火
否则鸡蛋不发泡容易吸油
中途再翻过来煎另一面
鸡蛋煎香之后倒出备用
锅中再次加入适量的油烧至4成热
油热之后将其腌制好的肉丝下锅滑散
肉丝滑散之后倒出备用
锅中留下少许的底油
然后加入蒜末爆香
蒜末爆香之后加入青瓜和胡萝卜炒至断生
中途再加入木耳和黄花菜炒香炒出锅汽
辅料炒香之后加入处理好的肉丝和鸡蛋下锅
然后加入生抽酱油5克从锅边淋入翻炒均匀
翻炒均匀之后加入适量的食用盐和白糖调味
再加入适量的明油翻炒几下
最后加入几根小葱炒至断生即可出锅装盘
一道口味丰富的木须肉就制作完成
下面开始技术总结
第一，黄花菜和木耳需要提前用温水泡发，然后再撕开备用
第二，此菜鸡蛋和肉丝和木耳是标配不可缺一
第三，制作过程中不能加水炒否则不香
木须肉的技术总结完毕

**Comment by immoonancient** [comment]
我来吧
