### ISSUE TITLE
[华农兄弟] 华农兄弟把兄弟家的竹鼠通通搬到我们新场房去还有花竹鼠哦 - https://youtu.be/Hq2jso2Yhdw

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#372]
https://youtu.be/Hq2jso2Yhdw
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 7, 2019 at 10:41PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
