### ISSUE TITLE
[华农兄弟] 华农兄弟捡点拐枣泡酒路过兄弟的玉米地搞点来喂猪 - https://youtu.be/e66aOy8f8PA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#373]
https://youtu.be/e66aOy8f8PA
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 8, 2019 at 05:06PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
