### ISSUE TITLE
[华农兄弟] 华农兄弟看一下我们家的脐橙熟了没有顺便摘一点回去吃 - https://youtu.be/pDWKWbIb9TQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#380]
https://youtu.be/pDWKWbIb9TQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 10, 2019 at 05:03PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
