### ISSUE TITLE
【雪鱼探店】烤鸡把子肉-https://www.youtube.com/watch?v=RuPgOSxzECE

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#385]
我来咯，带着美味金黄的烤鸡来咯，还有馋人的辣味把子肉
**中文字幕如下：**
1 
00:00:01,920 --> 00:00:04,920
山东·青岛

2 
00:00:06,400 --> 00:00:07,880
真的是特别冷

3 
00:00:07,880 --> 00:00:09,280
我都穿上羽绒服了

4 
00:00:09,280 --> 00:00:11,800
今天呢 咱们到菜市场这一边

5 
00:00:11,800 --> 00:00:14,320
买一只烤鸡来吃

6 
00:00:14,320 --> 00:00:16,880
这家烤鸡店 听说特别火爆

7 
00:00:16,880 --> 00:00:18,760
一天只营业4小时

8 
00:00:18,760 --> 00:00:21,240
如果说 来晚了 可能就没有了

9 
00:00:21,240 --> 00:00:23,720
我们要赶快走了

10 
00:00:32,680 --> 00:00:35,360
刚到市场门口 你就能闻到香味

11 
00:00:35,360 --> 00:00:38,040
我感觉不用地图 也能够找到它

12 
00:00:42,680 --> 00:00:45,040
哇 天呐 这么多人排队

13 
00:00:45,040 --> 00:00:46,760
得什么时候才能够吃得上

14 
00:01:08,200 --> 00:01:09,760
今天有这么多人排队

15 
00:01:09,760 --> 00:01:12,440
一方面可能是因为 周一不开门

16 
00:01:12,440 --> 00:01:13,800
还有一个就是

17 
00:01:13,800 --> 00:01:16,120
看到有这么多人排队 很多路过的人

18 
00:01:16,120 --> 00:01:18,800
可能也加入了排队的大军

19 
00:01:18,800 --> 00:01:22,520
在这儿买烤鸡 可能半天不会动一步

20 
00:01:22,520 --> 00:01:25,080
因为它这边是出一锅 卖一锅

21 
00:01:25,080 --> 00:01:26,520
如果说 烤不出来的话

22 
00:01:26,520 --> 00:01:29,000
我们仍然要站在原来的位置

23 
00:01:35,440 --> 00:01:38,760
15分钟了 我们迈出了历史性的一步

24 
00:01:38,760 --> 00:01:41,400
总算向前走了一点

25 
00:01:41,400 --> 00:01:44,040
还有没有鸡了

26 
00:01:44,960 --> 00:01:47,360
全鸡腿了

27 
00:01:48,000 --> 00:01:51,160
没有鸡了
           全鸡腿了

28 
00:01:51,160 --> 00:01:53,680
刚才老板从这个窗口告诉了我们

29 
00:01:53,680 --> 00:01:55,120
一个不幸的消息

30 
00:01:57,600 --> 00:01:59,480
全都是鸡腿了

31 
00:02:00,600 --> 00:02:04,720
排了老半天 竟然等待我的就是鸡腿

32 
00:02:06,200 --> 00:02:09,600
大姐 这个鸡腿怎么卖

33 
00:02:09,600 --> 00:02:11,280
29一斤

34 
00:02:11,720 --> 00:02:13,360
一个大约多少重

35 
00:02:17,760 --> 00:02:20,520
烤鸡是一只都没了

36 
00:02:20,520 --> 00:02:23,280
那给我拿3个鸡腿吧

37 
00:02:24,920 --> 00:02:27,480
3个

38 
00:02:30,320 --> 00:02:32,880
看 支付宝过去了

39 
00:02:40,080 --> 00:02:42,480
咱们排了差不多半个多小时吧

40 
00:02:42,480 --> 00:02:44,880
一只鸡都没有剩下 就只剩鸡腿了

41 
00:02:44,880 --> 00:02:49,040
我们是买了3个鸡腿 花了46块钱

42 
00:02:49,040 --> 00:02:52,240
走吧 我们要去吃鸡腿了

43 
00:03:02,000 --> 00:03:03,440
天气这么冷

44 
00:03:03,440 --> 00:03:07,320
拿着一个热热的鸡腿 还是感觉很幸福的

45 
00:03:07,600 --> 00:03:10,640
咱们买的鸡腿是花了46块钱

46 
00:03:10,640 --> 00:03:13,400
也就是说 一个鸡腿是15块钱

47 
00:03:13,400 --> 00:03:16,320
第一次买这么贵的鸡腿了

48 
00:03:16,320 --> 00:03:19,680
最近猪肉涨价 什么肉都跟着涨价

49 
00:03:19,680 --> 00:03:22,080
15块钱一个鸡腿 应该个头不小吧

50 
00:03:22,080 --> 00:03:24,040
咱们打开来看一看

51 
00:03:25,920 --> 00:03:27,600
开饭了

52 
00:03:32,720 --> 00:03:34,400
青岛的妖风太厉害了

53 
00:03:34,400 --> 00:03:37,480
我们决定临时转移阵地

54 
00:03:42,120 --> 00:03:44,400
从刚才的地方到现在的地方

55 
00:03:44,400 --> 00:03:46,120
因为实在是太饿了

56 
00:03:46,120 --> 00:03:48,840
现在只剩下一个鸡腿了

57 
00:03:48,840 --> 00:03:51,720
那两个鸡腿已经被我们消灭干净了

58 
00:03:51,720 --> 00:03:54,040
它这个鸡腿就是

59 
00:03:54,040 --> 00:03:56,720
就是你打开袋子的那一刻 就感觉到

60 
00:03:56,720 --> 00:03:59,880
它的烤鸡的味道很浓郁

61 
00:03:59,880 --> 00:04:02,800
它在袋子里 独自芬芳

62 
00:04:02,800 --> 00:04:05,400
你也能看到 鸡腿是很大个的

63 
00:04:05,400 --> 00:04:08,160
外面是烤的皮 有点褶皱了

64 
00:04:08,160 --> 00:04:11,560
而且是微黄色的 就像抹了蜂蜜一样

65 
00:04:11,560 --> 00:04:14,520
咱们是透过它褶皱的外皮

66 
00:04:14,520 --> 00:04:16,520
看它鸡腿的本身

67 
00:04:16,520 --> 00:04:20,960
你会发现它里面的鸡腿肉 好嫩

68 
00:04:26,360 --> 00:04:29,960
鸡腿有个特点 拿出来的时候也能发现

69 
00:04:29,960 --> 00:04:33,560
它的汤汁 顺着皮 一直朝下流

70 
00:04:35,800 --> 00:04:39,880
凭感官 也是觉得它是柔嫩多汁的

71 
00:04:39,880 --> 00:04:40,960
你看

72 
00:04:40,960 --> 00:04:44,640
它里面的鸡腿肉 就是一丝丝的

73 
00:04:44,640 --> 00:04:46,880
柔嫩的鸡腿肉

74 
00:04:49,880 --> 00:04:52,240
其实 你要说鸡腿

75 
00:04:54,960 --> 00:04:57,320
可能这个是意义上的鸡腿吧

76 
00:04:57,320 --> 00:05:00,040
但是它又加了这么多的肉

77 
00:05:00,040 --> 00:05:02,920
这份鸡腿吃起来 鸡肉是更好吃的

78 
00:05:02,920 --> 00:05:06,520
为什么呢 因为它的鸡肉的咸度是正好的

79 
00:05:06,520 --> 00:05:10,080
那你说 鸡皮在外面 它会更咸

80 
00:05:10,080 --> 00:05:12,440
所以说 鸡皮不如鸡肉好吃

81 
00:05:12,440 --> 00:05:13,440
还有一点就是

82 
00:05:13,440 --> 00:05:15,440
它里面的鸡腿肉没有变的很柴

83 
00:05:15,440 --> 00:05:18,880
因为里面 汤水 汤汁足够多

84 
00:05:18,880 --> 00:05:22,320
吃起来会让你觉得鸡肉 肉嫩多汁

85 
00:05:22,600 --> 00:05:23,960
如果说买回家的话

86 
00:05:23,960 --> 00:05:25,160
最爽的应该还是

87 
00:05:25,160 --> 00:05:27,400
直接上嘴啃吧

88 
00:05:39,480 --> 00:05:42,160

1 
00:00:01,920 --> 00:00:04,920
山东·济南

2 
00:00:07,640 --> 00:00:08,640
行了

3 
00:00:09,840 --> 00:00:11,880
你好 要那个菠菜

4 
00:00:11,880 --> 00:00:12,720
豆角

5 
00:00:12,720 --> 00:00:13,640
在这儿吃

6 
00:00:13,640 --> 00:00:14,400
米饭

7 
00:00:14,400 --> 00:00:15,360
两个

8 
00:00:15,360 --> 00:00:16,800
要辣还是不辣

9 
00:00:16,800 --> 00:00:18,920
要微辣

10 
00:00:19,440 --> 00:00:22,480
要一个肉 然后 菠菜 豆角 再要个菜花

11 
00:00:22,480 --> 00:00:24,760
可以了

12 
00:00:24,760 --> 00:00:26,400
多少钱

13 
00:00:26,400 --> 00:00:27,680
一共

14 
00:00:31,320 --> 00:00:32,680
30元

15 
00:00:32,680 --> 00:00:35,440
把子肉多少钱了

16 
00:00:35,440 --> 00:00:38,600
肉都30多块钱一斤了

17 
00:00:39,360 --> 00:00:41,040
过去了 30块钱

18 
00:00:41,040 --> 00:00:43,920
肉 你买 你买得35元一斤

19 
00:00:45,880 --> 00:00:49,120
咱们这是点了菠菜 豆角 菜花

20 
00:00:49,120 --> 00:00:50,800
还有一个把子肉

21 
00:00:50,800 --> 00:00:53,720
现在肉太贵了 刚才大哥说

22 
00:00:53,720 --> 00:00:56,720
咱们要的这一个把子肉 现在是8元一个

23 
00:00:56,720 --> 00:00:58,080
他刚才还加了一句

24 
00:00:58,080 --> 00:00:59,440
如果说 你们去买猪肉

25 
00:00:59,440 --> 00:01:01,480
可能已经到了35块钱一斤了

26 
00:01:01,480 --> 00:01:04,680
现在来吃猪肉 可能是赚了吧

27 
00:01:04,680 --> 00:01:06,280
你看 后面都坐满了

28 
00:01:06,280 --> 00:01:08,280
都是来吃肉的

29 
00:01:10,560 --> 00:01:13,440
把子肉是可以分辣的和不辣的

30 
00:01:13,440 --> 00:01:15,120
咱们是要的一个微辣的

31 
00:01:15,120 --> 00:01:17,200
还有一点我发现 这边的

32 
00:01:17,200 --> 00:01:20,480
豆角真的辣到让你觉得想吃饭

33 
00:01:20,480 --> 00:01:23,480
豆角上面有辣椒 这种干炝的辣椒

34 
00:01:23,480 --> 00:01:24,360
还有白芝麻

35 
00:01:24,360 --> 00:01:27,200
真的是吃起来特别的香

36 
00:01:29,120 --> 00:01:30,200
我本来是来吃肉的

37 
00:01:30,200 --> 00:01:33,600
没想到被干煸豆角圈粉了

38 
00:01:43,520 --> 00:01:47,160
肉其实不算大吧 看起来

39 
00:01:47,160 --> 00:01:50,080
把子肉外皮是这种糖色

40 
00:01:50,080 --> 00:01:53,080
轻轻地把它碾一下

41 
00:01:53,080 --> 00:01:54,760
拌米饭来吃

42 
00:01:54,760 --> 00:01:57,600
这个猪皮感觉很弹口

43 
00:01:57,600 --> 00:01:59,160
Q弹Q弹的

44 
00:01:59,160 --> 00:02:01,560
而且看起来晶莹剔透的

45 
00:02:02,920 --> 00:02:04,760
肥瘦相间

46 
00:02:09,680 --> 00:02:11,520
嚼一口 好香啊

47 
00:02:14,720 --> 00:02:17,080
它这个把子肉最大的特点就是入味

48 
00:02:17,080 --> 00:02:21,000
而且是辣的 咱们是第一次吃辣的把子肉

49 
00:02:21,000 --> 00:02:23,040
这个肉吃起来一点都不柴

50 
00:02:23,040 --> 00:02:25,480
它的肥肉不会让你觉得腻

51 
00:02:25,480 --> 00:02:27,440
瘦肉呢 炖的比较软烂

52 
00:02:27,440 --> 00:02:30,520
进到嘴中 嚼起来不会有什么样的负担

53 
00:02:32,600 --> 00:02:36,280
不爱吃肉呢

54 
00:02:36,280 --> 00:02:39,120
来吃把子肉 不一定要来吃肉

55 
00:02:39,120 --> 00:02:41,000
也可以来吃这个肉汤

56 
00:02:41,000 --> 00:02:42,720
就是不管你要不要肉

57 
00:02:42,720 --> 00:02:44,440
都可以给你来点肉汤（浇米饭上）

58 
00:02:44,440 --> 00:02:47,600
汤汁可能比肉 更下饭

59 
00:02:47,600 --> 00:02:50,200
咱们来的时候 正好赶上别人下班

60 
00:02:50,200 --> 00:02:54,480
所以这个小房子 显得略微有些拥挤

61 
00:02:54,480 --> 00:02:57,520
还是能够随便找几个座位 坐下来

62 
00:02:57,520 --> 00:02:59,960
好好吃一顿饭

63 
00:02:59,960 --> 00:03:01,280
有没有发现 人越多

64 
00:03:01,280 --> 00:03:03,760
你可能会吃得越香呢

65 
00:03:07,920 --> 00:03:10,600
大哥 这个把子肉开多久了

66 
00:03:10,600 --> 00:03:12,480
10来年了

67 
00:03:12,480 --> 00:03:13,920
一直是您在做吗

68 
00:03:13,920 --> 00:03:15,360
一直就我在做的

69 
00:03:15,360 --> 00:03:16,240
在这边做

70 
00:03:16,240 --> 00:03:18,840
我看咱这边是没有厨房 直接肉

71 
00:03:18,840 --> 00:03:21,800
拿锅 拿桶端过来的

72 
00:03:21,800 --> 00:03:24,560
俺有厨房

73 
00:03:24,560 --> 00:03:25,600
有厨房

74 
00:03:25,600 --> 00:03:26,640
厨房不在这里

75 
00:03:26,600 --> 00:03:27,760
不在这边

76 
00:03:28,640 --> 00:03:32,200
有的把子肉在店里做 有的也不在店里做

77 
00:03:32,200 --> 00:03:36,280
猪肉涨价对把子肉的生意有没有影响

78 
00:03:36,280 --> 00:03:37,000
俺没有

79 
00:03:37,000 --> 00:03:37,960
也没有

80 
00:03:37,960 --> 00:03:40,240
俺卖的不贵 俺卖8块钱它贵吗

81 
00:03:40,240 --> 00:03:41,280
8块钱 9块钱

82 
00:03:41,280 --> 00:03:42,840
以前也差不多吧

83 
00:03:42,840 --> 00:03:43,800
差不多

84 
00:03:43,800 --> 00:03:44,880
涨价没 最近

85 
00:03:44,880 --> 00:03:46,880
涨了 涨了两块钱

86 
00:03:46,880 --> 00:03:48,480
光要肉成9块了

87 
00:03:48,480 --> 00:03:51,240
无所谓了 肉不挣钱 菜挣点钱也行

88 
00:03:51,240 --> 00:03:52,160
是

89 
00:03:52,160 --> 00:03:55,400
你得护着让老客户吃上 对吧

90 
00:03:55,400 --> 00:03:56,160
对 对

91 
00:03:56,160 --> 00:03:58,480
一天 能卖多少斤猪肉

92 
00:03:58,480 --> 00:04:00,800
100多斤

93 
00:04:00,800 --> 00:04:02,280
也可以了

94 
00:04:02,280 --> 00:04:04,560
每天买肉就3千多

95 
00:04:04,560 --> 00:04:07,400
4千

96 
00:04:09,680 --> 00:04:11,960
一天4桶肉

97 
00:04:12,800 --> 00:04:16,080
一桶也有汤多汤少的时候

98 
00:04:17,640 --> 00:04:20,920
原来有人说6桶肉呢

99 
00:04:20,920 --> 00:04:24,200
6桶的话 连汤带肉的

100 
00:04:26,920 --> 00:04:29,320
没有汤 可能6桶就剩两桶

101 
00:04:34,960 --> 00:04:37,080
吃完还是有点撑的

102 
00:04:37,600 --> 00:04:40,200
关 注
雪 鱼 探 店

**Comment by immoonancient** [comment]
发布了再 close 吧

**Comment by immoonancient** [comment]
已发布
