### ISSUE TITLE
[华农兄弟] 华农兄弟兄弟家的油柿子熟了一树都是带老弟去摘点 - https://youtu.be/lCQj1ynbyRg

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#394]
https://youtu.be/lCQj1ynbyRg
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 15, 2019 at 06:25PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
