### ISSUE TITLE
[华农兄弟] 华农兄弟小狗又胖了狗妈妈又怀孕了这下真的一地都是狗了 - https://youtu.be/KtUF2vAakhQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#395]
https://youtu.be/KtUF2vAakhQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 15, 2019 at 06:25PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
