### ISSUE TITLE
【美食作家王刚】粑粑肉蒸肉糕 - https://youtu.be/sXQBY9na-jk

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#398]
【美食作家王刚】粑粑肉蒸肉糕 - https://youtu.be/sXQBY9na-jk
视频时长 6:19，预计发布时间为北京时间11月18日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

首先我们准备半肥瘦的二刀肉1大块
将猪肉切开之后再去掉猪皮
同学们蒸肉糕不能放猪皮否则影响口感
不喜欢猪肉的同学也可以用鱼肉或者鸡肉代替
去皮之后将肉放入温水中清洗干净
这里分享一个小技巧
猪肉最好温水清洗，冷水会让猪肉凝固
清洗干净之后捞出下一步开始制作
首先将猪肉切成厚片
然后将其剁成肉蓉备用
同学们这一步比较消耗耐力
纯手工剁肉大约需要30分钟
嫌麻烦的话也可以交给摊主用绞肉机处理
这一步必须将肉剁得越细口感越好
肉蓉多好之后下一步开始调制
首先准备适量的温水
加入几根小葱
再加入2小块生姜拍散
然后用力抓2分钟
这一步的目的是得到姜葱汁
抓好之后把姜葱捞出丢弃
准备鸡蛋5个打入碗中将蛋黄分离
然后将蛋黄搅散备用
准备适量的红薯淀粉
碗中加入1:1的清水将其捏散备用
下一步开始调肉泥
盆中加入分好的蛋清
加入调好的姜葱汁
再加入一半的红薯 淀粉
然后将肉抓散拌匀
同学们切记水淀粉不能一次加入
必须少量多次加入才能完全吸收
水淀粉吸收完成之后再加入2勺食用盐
然后顺着一个方向搅拌上劲备用
搅拌上劲之后加入适量的青花椒面
不能吃麻味的同学可以不加
再加入少许的胡椒粉
拌匀之后准备一个方形磨具
盆中加入适量的食用油润一遍
这样的目的是防止肉糕粘连在盆中
同学们切记边上也要涂抹均匀
涂抹均匀之后将多余的油倒出
然后将肉泥均匀的放入盆中压紧
肉泥压紧之后下一步开始蒸制
将制作好的肉泥放入蒸锅中蒸35分钟即可
中途肉糕成形之后取出
将盆中多余的水份倒出
然后加入适量的的蛋黄均匀涂抹在肉糕上面
嫌麻烦的同学也可以将蛋黄摊成饼盖在上面
然后再放入蒸锅蒸制蛋黄熟透
蛋黄熟透之后再次取出涂抹蛋黄蒸制
如此反复几次之后肉糕上面即可形成一层黄皮
35分钟之后即可将肉糕取出凉透
待肉糕凉透之后再切成厚片即可
一道非常美味营养的蒸肉糕就制作完成
下面开始技术总结
第一，原材料可以选择鸡鱼肉(猪肉)三种，且方法大致相同
第二，蒸肉糕的模具最好大且浅，否则不容易蒸熟透
第三，肉蓉剁得越细口感越嫩
第四，蒸制的时候火候不能太大，也不能超时蒸制否则肉糕变老
蒸肉糕的技术总结完毕

**Comment by shuaisoserious** [comment]
1

**Comment by shuaisoserious** [comment]
1
