### ISSUE TITLE
[华农兄弟] 华农兄弟砍点场里的红象草喂竹鼠看它们抢来抢去的很喜欢吃 - https://youtu.be/V4elakVwR5s

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#401]
https://youtu.be/V4elakVwR5s
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 19, 2019 at 12:06PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
