### ISSUE TITLE
[华农兄弟] 华农兄弟受邀参加第十七届中国国际农产品交易会带大家看一下 - https://youtu.be/4XIsCa6D24I

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#404]
https://youtu.be/4XIsCa6D24I
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 19, 2019 at 05:58PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
