### ISSUE TITLE
完善文档

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#412]
现在的文档过于偏重操作步骤，不利于新成员理解一般的字幕相关技术以及YouTube 的原生工具。计划进行以下扩充：
- 介绍 YouTube 原生字幕制作工具
- 介绍一般字幕技术，包括常见的文件格式等
  - 顺带介绍为何我们要绕道 GitHub 进行字幕校对
- 介绍本字幕组的相关流程步骤
- 介绍本字幕组的自制工具

**Comment by GUThe** [comment]
这个还做吗？

**Comment by immoonancient** [comment]
想做。但是要先确定想法
