### ISSUE TITLE
[华农兄弟] 华农兄弟天气越来越冷了老弟给小狗买了几件衣服给它们穿上 - https://youtu.be/zOfa4oXVHco

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#419]
https://youtu.be/zOfa4oXVHco
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 24, 2019 at 06:32PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
