### ISSUE TITLE
[华农兄弟] 华农兄弟一年又快过去了兄弟家野池塘的鱼也长大了网点来煎 - https://youtu.be/G5ig69mzlmE

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#424]
https://youtu.be/G5ig69mzlmE
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 26, 2019 at 05:30PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
