### ISSUE TITLE
[华农兄弟] 华农兄弟狗子又下崽了带大家看一下顺便给香猪喂点酒糟 - https://youtu.be/l2L-SkIlrEY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#427]
https://youtu.be/l2L-SkIlrEY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 27, 2019 at 07:30PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
