### ISSUE TITLE
[华农兄弟] 华农兄弟喂点粉丝送的狗粮给狗子吃看它们抢来抢去好像很好吃 - https://youtu.be/LvCqcuUxRB4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#430]
https://youtu.be/LvCqcuUxRB4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 28, 2019 at 01:28PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
