### ISSUE TITLE
[华农兄弟] 华农兄弟把小猪放出来了它又可以跟狗子们一起吃喝玩乐了 - https://youtu.be/0r13IZh9fuk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#433]
https://youtu.be/0r13IZh9fuk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 28, 2019 at 08:51PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
