### ISSUE TITLE
[华农兄弟] 华农兄弟猪吃酒糟醉了叫兄弟帮忙一起宰猪烤起来很香哦 - https://youtu.be/xkSxAypC0Wk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#435]
https://youtu.be/xkSxAypC0Wk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 29, 2019 at 02:52PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
