### ISSUE TITLE
[华农兄弟] 华农兄弟天气越来越冷了给小狗子做一个温暖的窝 - https://youtu.be/JVlyc7UBDrQ

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#439]
https://youtu.be/JVlyc7UBDrQ
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 30, 2019 at 03:29PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
