### ISSUE TITLE
[华农兄弟] 华农兄弟场里的橘子快熟了摘一个尝一下顺便看一下小猪崽 - https://youtu.be/witP5dfYDDA

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#441]
https://youtu.be/witP5dfYDDA
<p>&#35270;&#39057;&#21457;&#24067;&#20110; November 30, 2019 at 09:20PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
