### ISSUE TITLE
[华农兄弟] 华农兄弟搞了一点葛根虫子用油一炸嘎嘣脆很好吃哦 - https://youtu.be/x2XKYmCXNNY

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#443]
https://youtu.be/x2XKYmCXNNY
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 1, 2019 at 10:44AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
