### ISSUE TITLE
【美食作家王刚】猪肉涨价问答 - https://youtu.be/PXj3WlVNEys

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#448]
【美食作家王刚】猪肉涨价问答 - https://youtu.be/PXj3WlVNEys
视频时长 5:16，预计发布时间为北京时间12月5日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:01.280,0:00:03.020
哈喽大家好 我是王刚

0:00:03.640,0:00:06.000
昨天有个粉丝发了一个私信

0:00:06.400,0:00:08.920
问了一个高深的问题

0:00:09.220,0:00:12.080
我觉得这个问题提得很有深度

0:00:12.140,0:00:16.240
所以我今天拍了一个视频跟大家互动一下关于这个问题

0:00:16.240,0:00:18.120
他提得这个问题就是

0:00:18.120,0:00:19.520
最近猪肉涨价嘛

0:00:19.640,0:00:25.020
想看一下这个屠夫对于这个猪肉涨价有什么看法

0:00:25.360,0:00:29.620
还有就是想知道对普通人有什么影响

0:00:29.740,0:00:32.400
还有就是对这个餐厅

0:00:32.400,0:00:33.640
或者是餐馆

0:00:33.920,0:00:38.380
对这个猪肉涨价有没有什么更好的一些见解

0:00:39.100,0:00:43.140
所以本期拍这个视频跟大家互动一下

0:00:44.200,0:00:45.560
现在我去找我四伯

0:00:45.900,0:00:49.040
我四伯因为最近生意不好做

0:00:49.380,0:00:54.040
现在他也减少了每次去赶集的次数

0:00:55.580,0:00:57.120
他今天在土里面干活

0:00:57.460,0:00:58.660
我现在去找他

0:00:59.460,0:01:00.900
现在我在农村

0:01:01.780,0:01:03.700
去我们的土里面

0:01:04.260,0:01:06.260
这就是我们的农村

0:01:06.980,0:01:08.900
这边好几块土都是我们的

0:01:09.960,0:01:13.060
四伯在跟菜籽打药

0:01:14.200,0:01:15.720
打那个去虫的药

0:01:17.540,0:01:21.080
我好像听到我四伯说话的声音了

0:01:22.960,0:01:24.240
耶 老子

0:01:24.420,0:01:25.980
害怕还要倒退哦

0:01:32.800,0:01:34.980
要打 早都该打（农药）的了

0:01:43.900,0:01:46.260
这个皮衣还多有个性哦

0:01:46.520,0:01:48.360
烂了没得意思得了

0:01:48.900,0:01:51.220
我们有一个粉丝在后台发了一个私信

0:01:51.280,0:01:55.020
他有些问题想请你讲解哈

0:01:55.020,0:01:56.600
解答哈 是不哦

0:01:57.660,0:02:01.440
他还要想些啥子名堂嘛

0:02:02.240,0:02:07.640
他问你猪肉的价格涨起来了对你有没有什么影响

0:02:08.680,0:02:10.480
对我肯定有影响撒

0:02:10.980,0:02:11.940
啥子影响嘛

0:02:11.940,0:02:12.720
啥子影响

0:02:13.200,0:02:15.040
市民吃不起贵了

0:02:16.020,0:02:17.160
就买得少

0:02:17.560,0:02:19.060
生意就不好做

0:02:20.260,0:02:22.260
该买3斤的只买2斤

0:02:22.260,0:02:23.920
买2斤的就只买1斤

0:02:24.120,0:02:25.940
买1斤的就只买半斤

0:02:26.000,0:02:29.080
这个猪肉价格涨高了就是这样的

0:02:29.520,0:02:32.900
对我们做生意的来说就是大大的不利

0:02:32.900,0:02:34.100
很不利噶

0:02:34.700,0:02:38.460
平时每天吃一次猪肉的现在改成三天吃一次了

0:02:39.660,0:02:41.420
他都要节省点

0:02:42.200,0:02:44.660
农村你晓得的找钱不容易

0:02:44.860,0:02:46.660
往年这个时候我卖1个半（猪）

0:02:46.660,0:02:48.620
今年这个时候卖半个

0:02:50.160,0:02:51.460
看悬殊好大

0:02:52.920,0:02:58.360
那你想嘛以前8~12块钱1斤

0:02:58.380,0:03:00.380
现在上了15~26块钱1斤

0:03:01.020,0:03:02.780
相差一半多了

0:03:03.440,0:03:04.300
你看嘛

0:03:04.760,0:03:05.860
是不是嘛

0:03:06.520,0:03:08.560
不是你都要穿香肠了

0:03:08.580,0:03:10.580
肯定撒

0:03:12.900,0:03:15.260
去年子我整了好多哦

0:03:15.620,0:03:17.860
整了50~60斤肉来穿香肠

0:03:19.220,0:03:21.400
划腌肉（腊肉）都划了2个腿子（猪后腿肉）

0:03:21.520,0:03:23.920
今年子怕是免谈了

0:03:24.000,0:03:27.660
害怕划1~2斤肉腌来尝哈心算了

0:03:27.680,0:03:33.000
划2~3斤肉来尝哈味道就算了

0:03:33.420,0:03:35.620
不要去跟经济使劲蹦

0:03:35.640,0:03:37.980
经济的来源又短缺啊

0:03:38.280,0:03:40.280
又找不到钱 今年子

0:03:40.960,0:03:42.960
好啦 现在我来跟大家聊一聊

0:03:42.960,0:03:48.200
这个猪肉价格上涨对于我们做餐饮有什么影响

0:03:48.640,0:03:50.100
其实最大的一个影响就是

0:03:50.100,0:03:53.300
猪肉的价格它一涨它是马上就涨

0:03:53.700,0:03:56.960
然后我们餐厅里面有放猪肉的菜吧

0:03:56.960,0:03:58.380
菜单不能一下子涨

0:03:58.420,0:04:01.200
因为别人说今天在你这里吃的这个菜

0:04:01.280,0:04:03.720
第二天一来的话马上就涨价

0:04:03.980,0:04:06.960
这个对老顾客来说不怎么好

0:04:07.400,0:04:10.880
所以我们餐厅的话一般原材料上涨

0:04:11.200,0:04:12.620
涨了一段时间之后

0:04:12.980,0:04:15.960
然后我们菜单上面才会去有一点点涨动

0:04:15.980,0:04:17.980
其实做餐饮压力挺大

0:04:18.240,0:04:20.380
现在这个行情基本上你点到

0:04:20.440,0:04:24.300
回锅肉啊 水煮肉片啊 炒肉丝啊之类的菜

0:04:24.400,0:04:26.800
利润高的地方基本都不赚钱

0:04:26.880,0:04:29.900
利润低的地方的话基本上是在赔钱

0:04:30.180,0:04:34.300
好啦 我现在要去看一下四伯弄得怎么样了

0:04:35.600,0:04:37.920
四伯爷你还多专业哦 做这个

0:04:37.920,0:04:40.720
咋啦 这个东西不专业也还有干头啊

0:04:42.080,0:04:45.640
开玩笑哦 干了这么多年的庄稼

0:04:45.880,0:04:47.820
这点都清不到啊

0:04:49.580,0:04:51.980
你看这个（菜籽）拿给你栽得溜称（笔直）的

0:04:52.320,0:04:54.320
那个技术到有哦

0:04:57.360,0:04:58.540
我来帮你打会儿嘛

0:04:58.540,0:05:00.480
你来 pang药臭

0:05:00.820,0:05:01.520
不关事

0:05:01.780,0:05:04.700
那不得行这个药弄得身上（有毒）

0:05:05.180,0:05:08.460
所以我都把皮衣皮裤穿起安

0:05:11.360,0:05:13.360
好吧 本期视频就先到这里

0:05:13.360,0:05:14.520
我要干活啦

0:05:14.540,0:05:15.220
拜拜

**Comment by immoonancient** [comment]
现在只上传了未审核的字幕，修正后的还没上传

**Comment by immoonancient** [comment]
修正版已上传
