### ISSUE TITLE
【美食作家王刚】珠海海滨泳场圆明新园 - https://youtu.be/UTqgjlYb36Y

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#449]
【美食作家王刚】珠海海滨泳场圆明新园 - https://youtu.be/UTqgjlYb36Y
视频时长 3:55，预计发布时间为北京时间12月6日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:01.700,0:00:02.920
哈喽 大家好

0:00:03.480,0:00:04.500
打个招呼宝贝

0:00:05.480,0:00:06.840
你说哈喽大家好你是谁

0:00:07.120,0:00:09.760
哈喽大家好我是沺沺

0:00:09.960,0:00:11.040
嗯 沺沺

0:00:11.720,0:00:14.420
嗯 最近这段时间

0:00:15.140,0:00:16.420
忙了很长一段时间

0:00:16.520,0:00:20.600
所以就跟自己放了一个星期的长假

0:00:20.760,0:00:22.380
带家人出来玩一下

0:00:22.560,0:00:23.960
现在我们在珠海

0:00:24.440,0:00:26.280
又回到了熟悉的地方

0:00:27.720,0:00:28.980
是吧 嗯

0:00:29.160,0:00:30.940
这里小时候你来过 对不对

0:00:30.940,0:00:31.600
对

0:00:33.020,0:00:34.740
现在爸爸带你来这里玩好不好

0:00:34.740,0:00:35.380
嗯

0:00:35.920,0:00:37.360
待会我们去

0:00:37.920,0:00:38.440
抓鱼

0:00:38.440,0:00:39.180
抓鱼啊

0:00:39.840,0:00:40.900
去看金鱼好不好

0:00:40.900,0:00:41.400
好

0:00:41.560,0:00:42.340
好吧

**Comment by riana33** [comment]
认领。

**Comment by riana33** [comment]
bot, please upload
0:00:01.700,0:00:02.920   哈喽 大家好   Hello, everyone.   0:00:03.480,0:00:04.500   打个招呼宝贝   Say hi, baby.   0:00:05.480,0:00:06.840   你说哈喽大家好你是谁   You say “hello I   am...”   0:00:07.120,0:00:09.760   哈喽大家好我是沺沺   Hello everyone I   am Tiantian.   0:00:09.960,0:00:11.040   嗯 沺沺   Um Tiantian.   0:00:11.720,0:00:14.420   嗯 最近这段时间   Um Recently    0:00:15.140,0:00:16.420   忙了很长一段时间   I’ve been busy   for a while.   0:00:16.520,0:00:20.600   所以就跟自己放了一个星期的长假   So I give myself   a one week break,   0:00:20.760,0:00:22.380   带家人出来玩一下   take my family   out to have some fun.   0:00:22.560,0:00:23.960   现在我们在珠海   Now we are in   Zhuhai,   0:00:24.440,0:00:26.280   又回到了熟悉的地方,   Back to the familiar   place. 0:00:27.720,0:00:28.980   是吧 嗯   Right? Yeah   0:00:29.160,0:00:30.940   这里小时候你来过 对不对   You have been   here when you are little, right?     0:00:30.940,0:00:31.600   对   Yes    0:00:33.020,0:00:34.740   现在爸爸带你来这里玩好不好   Now daddy takes   you here to have some fun, okay?    0:00:34.740,0:00:35.380   嗯   Yeah   0:00:35.920,0:00:37.360   待会我们去   We will go to...?   0:00:37.920,0:00:38.440   抓鱼   Catch fish    0:00:38.440,0:00:39.180   抓鱼啊   Oh catch fish ?   0:00:39.840,0:00:40.900   去看金鱼好不好   How about we go   to see goldfish ?   0:00:40.900,0:00:41.400   好   Great   0:00:41.560,0:00:42.340   好吧   Cool
--

**Comment by riana33** [comment]
bot, please upload
0:00:01.700,0:00:02.920
哈喽 大家好
Hello, everyone.
0:00:03.480,0:00:04.500
打个招呼宝贝
Say hi, baby.
0:00:05.480,0:00:06.840
你说哈喽大家好你是谁
You say “hello I am...”
0:00:07.120,0:00:09.760
哈喽大家好我是沺沺
Hello everyone I am Tiantian.
0:00:09.960,0:00:11.040
嗯 沺沺
Um Tiantian.
0:00:11.720,0:00:14.420
嗯 最近这段时间
Um Recently 
0:00:15.140,0:00:16.420
忙了很长一段时间
I’ve been busy for a while.
0:00:16.520,0:00:20.600
所以就跟自己放了一个星期的长假
So I give myself a one week break,
0:00:20.760,0:00:22.380
带家人出来玩一下
take my family out to have some fun.
0:00:22.560,0:00:23.960
现在我们在珠海
Now we are in Zhuhai,
0:00:24.440,0:00:26.280
又回到了熟悉的地方,
Back to the familiar place. 0:00:27.720,0:00:28.980
是吧 嗯
Right? Yeah
0:00:29.160,0:00:30.940
这里小时候你来过 对不对
You have been here when you are little, right?
  0:00:30.940,0:00:31.600
对
Yes 
0:00:33.020,0:00:34.740
现在爸爸带你来这里玩好不好
Now daddy takes you here to have some fun, okay? 
0:00:34.740,0:00:35.380
嗯
Yeah
0:00:35.920,0:00:37.360
待会我们去
We will go to...?
0:00:37.920,0:00:38.440
抓鱼
Catch fish 
0:00:38.440,0:00:39.180
抓鱼啊
Oh catch fish ?
0:00:39.840,0:00:40.900
去看金鱼好不好
How about we go to see goldfish ?
0:00:40.900,0:00:41.400
好
Great
0:00:41.560,0:00:42.340
好吧
Cool

**Comment by immoonancient** [comment]
已发布
