### ISSUE TITLE
[华农兄弟] 华农兄弟抓了只鸡刚好兄弟来了一起烤鸡顺便再烤点排骨 - https://youtu.be/jPIvW8B18-s

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#454]
https://youtu.be/jPIvW8B18-s
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 6, 2019 at 11:53AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
