### ISSUE TITLE
【美食作家王刚】参观兄弟家的猪和竹鼠 - https://youtu.be/z0M01HwpnM4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#455]
【美食作家王刚】参观兄弟家的猪和竹鼠 - https://youtu.be/z0M01HwpnM4
视频时长 10:06，预计发布时间为北京时间12月8日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:03.345,0:00:06.755
你看到没这是我兄弟家的欢迎团

0:00:06.780,0:00:08.400
啦啦队出来（迎接）

0:00:08.760,0:00:10.280
我数一下这个多少

0:00:10.460,0:00:14.560
四个 七个 十个 这里就十个了

0:00:15.060,0:00:16.060
楼上还有

0:00:16.215,0:00:17.215
楼上还有

0:00:17.940,0:00:20.100
这个就是我兄弟说的五十斤的大狗

0:00:20.220,0:00:22.220
它认识我 上次来过

0:00:29.635,0:00:30.805
好乖啊这些狗

0:00:35.965,0:00:36.965
好乖

0:00:41.800,0:00:44.540
你这么欢迎我 都搞得我有点不好意思了

0:00:44.640,0:00:46.560
你看一排一排的站在这里

0:00:47.740,0:00:49.960
你提着东西它以为是好吃的

0:00:49.960,0:00:51.400
你喂它点狗粮

0:00:55.680,0:00:57.280
你喂了它的话会很喜欢你的哦

0:00:57.320,0:00:59.340
这是什么 狗粮啊

0:01:02.700,0:01:03.660
抓一把给它啊

0:01:03.660,0:01:04.560
嗯 多一点

0:01:05.780,0:01:07.360
是大狗吃还是小狗吃

0:01:07.360,0:01:08.200
都行

0:01:09.820,0:01:11.120
这个叫什么名字 这个

0:01:11.120,0:01:12.020
这个 小黑

0:01:12.020,0:01:12.720
小黑来

0:01:14.220,0:01:15.820
这里 这里

0:01:16.680,0:01:18.940
它好斯文 它怕咬到我的手

0:01:27.100,0:01:30.280
来 五十斤的你 诶呀 吓我一跳

0:01:32.940,0:01:34.580
它最喜欢爬楼

0:01:41.140,0:01:43.320
它们会抢 来都给你们吧

0:01:48.340,0:01:51.020
狗崽子在这（楼）上面又下（生）了四条

0:01:51.140,0:01:52.020
又下了四条

0:01:52.020,0:01:52.740
是啊小狗

0:01:52.740,0:01:54.280
那你现在不是十多条狗了

0:01:54.280,0:01:56.140
十多条 十七条

0:01:56.160,0:01:57.300
十七条

0:01:57.300,0:01:58.600
那猪又下崽了

0:01:58.960,0:02:00.740
走我们去看一下

0:02:06.940,0:02:08.020
我要带一棍子进去

0:02:09.140,0:02:12.740
那边那个公猪会拱我的

0:02:13.460,0:02:14.460
你看全部在这里

0:02:16.040,0:02:17.740
那天喝醉的都有哪些

0:02:17.740,0:02:18.980
全部喝醉了

0:02:19.200,0:02:21.680
就一条母猪没醉 其他都醉了

0:02:22.640,0:02:24.200
母猪没喝醉

0:02:24.200,0:02:25.520
这个是公猪吧

0:02:25.520,0:02:26.780
这个是公猪

0:02:26.780,0:02:30.180
这个是母猪 母猪下崽了 崽在那里

0:02:35.520,0:02:38.500
这两条小母猪也怀孕了 那么小都怀孕了

0:02:38.820,0:02:43.880
这要是说宰一只来烤 你觉得哪一只比较好一点

0:02:45.900,0:02:46.720
这个

0:02:46.720,0:02:47.960
那只是吗

0:02:47.980,0:02:49.980
对 那只不合群的

0:02:51.360,0:02:53.680
那我就去抓它嘛

0:02:53.680,0:02:54.840
你抓不到的

0:02:54.840,0:02:56.240
抓到了我就烤嘛

0:02:56.240,0:02:57.260
可以啊 是不是哦

0:02:57.300,0:02:59.020
可以 没问题 好的

0:03:05.400,0:03:07.220
抓不到的 你看它胖嘟嘟的

0:03:08.385,0:03:09.385
它跑的特别快

0:03:10.460,0:03:11.840
抓得到

0:03:12.680,0:03:14.220
哪个是公猪

0:03:14.660,0:03:16.300
最大的那条

0:03:16.640,0:03:18.260
公猪啊这个 对

0:03:18.260,0:03:19.660
别碰到它 会咬人

0:03:20.360,0:03:23.100
你华农哥上次差点都被它咬了

0:03:27.280,0:03:29.580
跟我走 走

0:03:31.820,0:03:33.300
它(公猪)是会保护它的

0:03:33.300,0:03:34.160
对

0:03:36.260,0:03:38.960
喊你走 走过去我们去那边说话

0:03:39.280,0:03:41.300
嘿嘿 那边说话

0:03:52.220,0:03:54.840
嘿嘿 不好抓的 我们都抓不住

0:03:54.900,0:03:56.900
现在都快五十多斤了

0:04:02.560,0:04:03.960
呀 它跑出去了

0:04:03.960,0:04:05.260
没事啊 跑出去最好

0:04:05.260,0:04:07.680
我们赶它出去还赶不出去

0:04:11.480,0:04:12.540
看一下它的小崽

0:04:13.080,0:04:15.240
哇 那小猪也太可爱了吧

0:04:17.625,0:04:19.085
可以摸它不这个小猪

0:04:19.085,0:04:22.365
怕摸不了 我们都摸不了 一摸它就拱我

0:04:22.365,0:04:24.080
有人在 它一直护着小崽

0:04:24.660,0:04:27.700
我们出去的时候它就可以自由活动

0:04:27.780,0:04:29.980
过来 过来一只

0:04:29.980,0:04:31.620
抱一下我就还给你

0:04:32.860,0:04:33.680
它吃奶

0:04:34.620,0:04:36.920
有两只小猪跑出去了

0:04:38.360,0:04:40.580
你不是前几天杀了猪吗

0:04:40.580,0:04:42.040
有 全部在我冰箱里面

0:04:43.500,0:04:45.040
还没吃 就等你过来

0:04:45.420,0:04:46.800
是不是哦 嗯

0:04:47.140,0:04:52.500
你那猪应该是被你故意喂它酒糟喝醉了才那个了的吧

0:04:52.660,0:04:55.480
对啊 要不然找不到机会下手

0:04:56.140,0:04:57.740
太凶了 抓都抓不住

0:05:04.120,0:05:05.920
看看我们这边山泉水

0:05:05.920,0:05:07.440
从山上流下来

0:05:08.880,0:05:10.220
这个桥有名字吗

0:05:10.240,0:05:12.800
这个可以这么叫嘛

0:05:12.800,0:05:14.640
就是叫竹鼠的奈何桥

0:05:14.640,0:05:15.400
奈何桥

0:05:15.440,0:05:18.900
出了这个桥的竹鼠啊几乎都活不到两三天

0:05:18.900,0:05:19.740
哈哈

0:05:19.940,0:05:21.780
就已经被上了餐桌

0:05:22.980,0:05:24.420
你说的是黑竹鼠吗

0:05:24.540,0:05:25.540
嗯 黑的

0:05:25.540,0:05:26.180
白的

0:05:26.180,0:05:27.080
白的不会

0:05:27.080,0:05:28.960
白的我拿来做宠物

0:05:29.780,0:05:30.960
这里面很多花竹鼠

0:05:31.460,0:05:32.040
差不多

0:05:32.160,0:05:37.140
我就是白的跟那个黑的杂交出来就变成花的

0:05:37.520,0:05:39.020
你们这个场地也太大了吧

0:05:39.420,0:05:41.300
这边是准备再修吗

0:05:41.300,0:05:42.055
对

0:05:42.060,0:05:43.620
在搭棚是吧

0:05:44.740,0:05:46.400
修成一个围墙 把它围起来

0:05:46.400,0:05:48.880
围起来要养一点猪

0:05:48.980,0:05:50.980
对 养点鸡啊养点狗呀

0:05:51.000,0:05:55.600
我们家那狗生出来啦生出来啦四只

0:05:55.600,0:05:57.320
我就准备放在这里

0:06:00.800,0:06:02.140
哇 这么大啊

0:06:02.780,0:06:05.220
抓一个你们的花的出来看下

0:06:11.020,0:06:12.500
诶 有一个

0:06:15.440,0:06:16.620
哇 好靓

0:06:16.840,0:06:18.140
黑白相间是吧

0:06:19.640,0:06:20.680
最靓了这个

0:06:20.680,0:06:21.820
它咬不咬人

0:06:22.460,0:06:24.060
有点 要小心一点

0:06:26.100,0:06:27.420
这样子它咬不到了

0:06:27.520,0:06:28.380
对 咬不到

0:06:28.580,0:06:29.440
那就好

0:06:29.660,0:06:31.080
这个像猫一样

0:06:31.080,0:06:32.160
很靓的这个

0:06:32.600,0:06:33.520
很靓

0:06:33.520,0:06:34.740
它心跳的很快

0:06:35.140,0:06:36.280
怕了

0:06:36.700,0:06:37.380
怕

0:06:37.380,0:06:38.060
对呀

0:06:38.080,0:06:38.960
不怕

0:06:38.960,0:06:40.240
你不吃花的

0:06:40.420,0:06:42.820
它肯定认识你 经常拿刀来切东西

0:06:42.820,0:06:44.020
很温顺这个

0:06:44.180,0:06:45.160
像熊猫一样

0:06:45.280,0:06:47.380
是 它这里有点黑黑的

0:06:47.900,0:06:50.620
趁它没有生气就先放它下去

0:06:52.520,0:06:54.520
全部都是密密麻麻的

0:06:54.560,0:06:57.740
天气冷的话多放几只互相取暖

0:06:57.840,0:06:58.540
这个是最靓的

0:06:58.640,0:06:59.640
这个比较黑

0:07:00.520,0:07:01.740
这个不错

0:07:02.820,0:07:05.580
哇 这个更那个

0:07:05.700,0:07:06.860
更黑

0:07:09.280,0:07:11.640
这个真漂亮 真的是很漂亮

0:07:12.700,0:07:13.900
你能送我这个吗

0:07:14.720,0:07:15.720
带不带得回去

0:07:16.160,0:07:17.080
不能上飞机

0:07:17.580,0:07:19.060
它会抓你是不是

0:07:19.060,0:07:19.900
它会抓人

0:07:19.900,0:07:21.100
它的爪子可以抓人

0:07:21.440,0:07:22.560
但是不痛

0:07:23.680,0:07:24.880
这样子弄它最好

0:07:26.860,0:07:27.860
很可爱的哦

0:07:29.200,0:07:30.720
这只竹鼠真的很可爱

0:07:30.720,0:07:32.340
这个是比较黑的

0:07:33.400,0:07:34.460
像熊猫一样

0:07:35.040,0:07:37.940
小心一点 小心小心小心

0:07:40.220,0:07:42.260
这个它应该不会咬人吧

0:07:42.640,0:07:43.700
会咬人

0:07:43.900,0:07:45.420
这么小你都会咬人呀

0:07:46.000,0:07:48.000
这个太漂亮了

0:07:49.620,0:07:50.575
很可爱吧

0:07:50.575,0:07:51.575
好可爱

0:07:52.280,0:07:53.280
小心一点

0:08:01.320,0:08:02.900
凉快吧这个地方

0:08:04.520,0:08:06.880
所以竹鼠养这儿也不容易中暑呀

0:08:07.520,0:08:08.920
但是容易感冒

0:08:08.920,0:08:09.840
容易感冒

0:08:09.900,0:08:11.260
天太冷了

0:08:20.100,0:08:21.100
去二楼看一下

0:08:28.020,0:08:31.520
好像我们以前没有看到过花的竹鼠

0:08:32.660,0:08:35.920
你这花的竹鼠和白的竹鼠是一样的吗

0:08:36.120,0:08:39.340
都差不多吧等于是白色和黑色的（交配生的）

0:08:39.340,0:08:41.040
暖不暖胃就完事儿

0:08:41.040,0:08:46.080
哈哈哈看一下就好（吃了）太浪费了

0:08:46.080,0:08:49.920
肉吃起来（味道）应该都是一样的

0:08:53.520,0:08:58.040
这个花的竹鼠用来养成宠物感觉还不错

0:08:58.300,0:09:01.620
我觉得比白色的还要可爱一点

0:09:06.880,0:09:08.900
你们的这个房子好老

0:09:09.440,0:09:12.480
应该差不多将近20年了

0:09:16.760,0:09:18.660
以前是商店

0:09:18.980,0:09:20.940
很早以前的商店

0:09:20.940,0:09:22.360
这间不错

0:09:22.620,0:09:25.200
这间再养1000只没问题

0:09:25.460,0:09:28.700
养在这上面夏天容易中暑

0:09:29.440,0:09:31.160
你可以在（楼）上面洒水呀

0:09:31.580,0:09:34.300
洒水也行但是要不停洒水啊

0:09:34.760,0:09:38.140
到时候那桂花一开的话 那全部是桂花（香）来着

0:09:38.340,0:09:39.800
一开的话很香的

0:09:39.960,0:09:44.460
这一大片区域都是很香的

0:09:44.820,0:09:46.800
你给我拿了那么多竹鼠

0:09:46.880,0:09:49.380
后面我又试了烤竹鼠

0:09:50.300,0:09:51.800
真的很好吃这个

0:09:52.160,0:09:55.040
烤的那个焦焦的味道特别好

0:09:55.155,0:09:57.295
我在想如果以后开店的话

0:09:57.740,0:10:00.160
想用你的这个竹鼠做一个菜

0:10:00.300,0:10:02.300
可以啊 没问题

0:10:02.780,0:10:04.160
包在我身上

**Comment by immoonancient** [comment]
已发布
