### ISSUE TITLE
[华农兄弟] 华农兄弟最近天气干燥摄影小哥又上火了挖点葛根来炖竹鼠 - https://youtu.be/ST6Ne5xZ7F4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#459]
https://youtu.be/ST6Ne5xZ7F4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 7, 2019 at 12:38PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
