### ISSUE TITLE
雪鱼-厦门小吃合集-https://www.youtube.com/watch?v=ZEHmYYVTOwg

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#462]
https://www.youtube.com/watch?v=ZEHmYYVTOwg

最近以来，一直有字幕文字缺失问题，这次【修正了多字幕轨道带来的字幕缺失问题】，感谢组里同学，请收回你们的8米长🔪。我以后都注意⚠️。
**标题**：逛吃厦门：7元汉堡一层肉一层蛋，5元大饼一面全是虾！酥脆可口馋人
**描述**：
探寻世界最具烟火气息的美味，我是雪鱼。
🐟
这一次算是厦门小吃的集合了，吃完这些就离开厦门了。首先吃的就是鸡蛋汉堡了，一个10几年的小摊，打理的是一对老夫妻，价格是7元一个，料还是很足的。走的时候在巷子口又看见虾饼，和台湾大叔一起一人买了一个。虾饼酥脆馋人，一个根本不够吃。最后在路口碰见一个春卷小摊，别看摊子小，也有几十年了。
🐟
地址：林记老思西鸡蛋汉堡（思明西路山仔顶巷）+虾饼（50米远的距离）+阿卿春卷（局口街中山路路口）
营业时间：14：30-22：30+虾饼春卷随意开摊，一般在下午
Instagram：https://www.instagram.com/xueyu_foodt...
Bilibili：雪鱼探店
新浪微博：雪鱼探店
**字幕**
1
00:00:01,680 --> 00:00:04,920
福建·厦门

2
00:00:11,400 --> 00:00:13,360
你知道吗 在这条马路上

3
00:00:13,360 --> 00:00:16,200
前面有一家小吃店 就是卖鸡蛋汉堡的

4
00:00:16,200 --> 00:00:17,200
特别火爆

5
00:00:17,200 --> 00:00:18,600
别的家没看到排队

6
00:00:18,600 --> 00:00:21,200
就他家 排起了长队

7
00:00:36,600 --> 00:00:39,080
来 就是这个鸡蛋汉堡 人特别多

8
00:00:39,080 --> 00:00:40,760
过来看一下

9
00:00:41,960 --> 00:00:44,880
不知道得排多长时间 才能够吃得到呢

10
00:00:45,160 --> 00:00:46,840
计个时

11
00:00:52,720 --> 00:00:55,880
最近的鸡蛋汉堡 好像都很火爆

12
00:00:55,960 --> 00:00:57,680
这个也是

13
00:00:58,840 --> 00:01:00,840
2个炉子

14
00:01:12,600 --> 00:01:15,480
虽然说 咱们吃过很多次的鸡蛋汉堡

15
00:01:15,480 --> 00:01:17,200
但是这一次的有点不同

16
00:01:17,200 --> 00:01:19,200
她的两个炉子

17
00:01:19,200 --> 00:01:23,160
一个是做面饼 另一个只是做馅儿

18
00:01:23,160 --> 00:01:27,000
这个馅儿是用鸡蛋和猪肉（泥）做的

19
00:01:27,000 --> 00:01:29,960
然后呢 就是把面饼还有馅饼

20
00:01:29,960 --> 00:01:33,600
两个夹在一起 中间可以夹上黄瓜、香菜

21
00:01:33,600 --> 00:01:36,160
还有涂抹上一些酱料

22
00:01:36,160 --> 00:01:39,200
这里面可以是甜的酱 也可以是辣的酱

23
00:01:39,200 --> 00:01:41,160
辣的酱是什么 老干妈

24
00:02:08,880 --> 00:02:10,560
马上吃好吃

25
00:02:44,360 --> 00:02:46,680
这些菜自己看着选择

26
00:02:48,600 --> 00:02:49,480
都加哦

27
00:02:49,480 --> 00:02:50,800
可以

28
00:02:54,600 --> 00:02:56,160
要甜的 要辣

29
00:02:56,200 --> 00:02:58,680
要甜的吧

30
00:02:59,160 --> 00:03:00,680
花生酱要哦

31
00:03:00,680 --> 00:03:01,680
要

32
00:03:03,200 --> 00:03:06,040
花了40多分钟 我们买了3个鸡蛋汉堡

33
00:03:06,040 --> 00:03:07,880
这里面有甜的 有辣的

34
00:03:07,880 --> 00:03:09,720
里面都加了花生酱

35
00:03:09,720 --> 00:03:11,720
第一次尝试这种鸡蛋汉堡

36
00:03:11,880 --> 00:03:18,240
走吧 我们要朝前看一看还有什么好吃的

37
00:03:18,240 --> 00:03:20,240
虾饼

38
00:03:31,920 --> 00:03:33,320
阿姨 我想买一个

39
00:03:33,320 --> 00:03:35,600
这个是虾饼吗

40
00:03:36,440 --> 00:03:37,560
要不要甜辣酱

41
00:03:37,560 --> 00:03:39,320
要甜辣酱

42
00:03:40,360 --> 00:03:43,440
这个是直接用鲜的小虾来炸

43
00:03:44,720 --> 00:03:47,040
我还没给钱呢

44
00:04:07,600 --> 00:04:09,520
5块钱吗

45
00:04:09,520 --> 00:04:11,480
是5块钱

46
00:04:15,120 --> 00:04:17,720
钱过去了

47
00:04:18,900 --> 00:04:20,900
自己想吃 也想让朋友来一份

48
00:04:43,840 --> 00:04:46,160
我刚才就在问她说 有没有这样子

49
00:04:46,160 --> 00:04:46,880
可以两个（都加）

50
00:04:46,880 --> 00:04:49,120
对 我就叫她混合着

51
00:04:49,680 --> 00:04:50,760
你哪里来的

52
00:04:50,760 --> 00:04:53,040
山东

53
00:04:54,640 --> 00:04:55,880
我台湾来的

54
00:04:55,880 --> 00:04:57,320
你是第一次吃这个吗

55
00:04:57,320 --> 00:04:59,040
第一次

56
00:05:03,960 --> 00:05:05,680
甜辣酱要吗

57
00:05:06,280 --> 00:05:07,680
要一点点

58
00:05:18,280 --> 00:05:20,600
这可能是我见过最小的摊位了

59
00:05:23,120 --> 00:05:25,520
阿姨 多少钱一个  5元钱？

60
00:05:26,080 --> 00:05:27,760
里面卷的是什么

61
00:05:27,760 --> 00:05:29,360
菜

62
00:05:29,360 --> 00:05:30,200
里面有什么

63
00:05:30,200 --> 00:05:31,680
好多种菜

64
00:05:33,200 --> 00:05:34,760
有瘦肉丝  有海蛎

65
00:05:36,000 --> 00:05:39,040
很多种菜 有10几种菜

66
00:05:39,040 --> 00:05:43,940
高丽菜 红萝卜 荷兰豆 芹菜 蒜

67
00:05:44,120 --> 00:05:45,400
好多种呢

68
00:05:45,960 --> 00:05:48,480
过去了

69
00:05:48,480 --> 00:05:51,400
阿姨 一直是您两个人在这边吗

70
00:05:51,400 --> 00:05:52,400
一直是两个人吗

71
00:05:52,400 --> 00:05:54,160
有的时候会换人

72
00:05:54,160 --> 00:05:56,400
我们是一家人在做的

73
00:05:56,600 --> 00:05:58,480
有时候 换一下

74
00:05:58,480 --> 00:06:01,800
这个巷子 也就够一个人来回走

75
00:06:01,800 --> 00:06:03,640
多一个人都不行

76
00:06:10,360 --> 00:06:12,840
从局口街里走出来 感觉人好热闹

77
00:06:12,840 --> 00:06:15,320
视野也宽敞了很多

78
00:06:30,880 --> 00:06:31,920
好了 我们尝一尝

79
00:06:31,920 --> 00:06:34,600
鸡蛋汉堡是什么样的（味道）

80
00:06:34,600 --> 00:06:36,080
不过做的时候 我会发现

81
00:06:36,080 --> 00:06:37,960
它（鸡蛋汉堡）里面的料 感觉好足

82
00:06:37,960 --> 00:06:41,640
就是 她（阿姨）把馅做成了一个馅饼

83
00:06:41,640 --> 00:06:43,040
真的是一个馅饼

84
00:06:43,040 --> 00:06:45,880
和这个面饼是一样大的

85
00:06:46,840 --> 00:06:48,440
感觉很厚实

86
00:06:52,160 --> 00:06:53,760
它这个是咸的

87
00:06:53,760 --> 00:06:55,600
但是你能够吃出来的就是

88
00:06:55,600 --> 00:06:57,400
猪肉和鸡蛋的这种香味

89
00:06:57,400 --> 00:07:00,160
这个汉堡最大的特点就是料很足

90
00:07:00,160 --> 00:07:02,720
毕竟她已经把料做成了一个饼

91
00:07:02,720 --> 00:07:05,200
完全不输于另外一个饼皮

92
00:07:06,560 --> 00:07:09,040
黄瓜还挺鲜的

93
00:07:12,040 --> 00:07:14,360
不行了 现在我要去赶车了

94
00:07:14,360 --> 00:07:16,000
等到火车上 再给大家录吧

95
00:07:16,000 --> 00:07:17,040
走吧

96
00:07:34,760 --> 00:07:37,360
到了 坐下了

97
00:07:53,200 --> 00:07:55,200
这车上的人特别多

98
00:07:55,200 --> 00:07:59,120
不太好意思让饭菜的味道出来

99
00:07:59,720 --> 00:08:02,760
我们下车再吃吧

100
00:08:03,760 --> 00:08:05,040
饿死了

101
00:08:09,080 --> 00:08:11,360
实在是太饿了

102
00:08:11,360 --> 00:08:13,360
现在是晚上6点多了

103
00:08:15,000 --> 00:08:17,000
默默吃光了

104
00:08:24,120 --> 00:08:26,120
不行了  太困了

105
00:08:27,680 --> 00:08:30,680
关 注
雪 鱼 探 店

**Comment by Losskywalker** [comment]
认领

**Comment by Losskywalker** [comment]
bot, please upload

标题：逛吃厦门：7元汉堡一层肉一层蛋，5元大饼一面全是虾！酥脆可口馋人
Title: Street food in Xiamen: 7 yuan for a burger with meat and egg, 5 yuan for a pancake with shrimps! Crispy and tasty! 
描述：
探寻世界最具烟火气息的美味，我是雪鱼。
🐟
这一次算是厦门小吃的集合了，吃完这些就离开厦门了。首先吃的就是鸡蛋汉堡了，一个10几年的小摊，打理的是一对老夫妻，价格是7元一个，料还是很足的。走的时候在巷子口又看见虾饼，和台湾大叔一起一人买了一个。虾饼酥脆馋人，一个根本不够吃。最后在路口碰见一个春卷小摊，别看摊子小，也有几十年了。
🐟
地址：林记老思西鸡蛋汉堡（思明西路山仔顶巷）+虾饼（50米远的距离）+阿卿春卷（局口街中山路路口）
营业时间：14：30-22：30+虾饼春卷随意开摊，一般在下午
Instagram：https://www.instagram.com/xueyu_foodt...
Bilibili：雪鱼探店
新浪微博：雪鱼探店
字幕
1
00:00:01,680 --> 00:00:04,920
福建·厦门
Xiamen, Fujian Province
2
00:00:11,400 --> 00:00:13,360
你知道吗 在这条马路上
You know, on this road
3
00:00:13,360 --> 00:00:16,200
前面有一家小吃店 就是卖鸡蛋汉堡的
There is a little restaurant selling egg burgers
4
00:00:16,200 --> 00:00:17,200
特别火爆
Super popular
5
00:00:17,200 --> 00:00:18,600
别的家没看到排队
Other restaurants are quiet
6
00:00:18,600 --> 00:00:21,200
就他家 排起了长队
Just this one, there is a queue already
7
00:00:36,600 --> 00:00:39,080
来 就是这个鸡蛋汉堡 人特别多
Here, this is the restaurant selling egg burgers. Super busy.
8
00:00:39,080 --> 00:00:40,760
过来看一下
Let’s have a look
9
00:00:41,960 --> 00:00:44,880
不知道得排多长时间 才能够吃得到呢
I don’t know how long we have to wait for that
10
00:00:45,160 --> 00:00:46,840
计个时
Let me start the timer
11
00:00:52,720 --> 00:00:55,880
最近的鸡蛋汉堡 好像都很火爆
Egg burgers are popular recently
12
00:00:55,960 --> 00:00:57,680
这个也是
So is this one
13
00:00:58,840 --> 00:01:00,840
2个炉子
(two stoves)
14
00:01:12,600 --> 00:01:15,480
虽然说 咱们吃过很多次的鸡蛋汉堡
Honesty, we’ve experiences many egg burgers
15
00:01:15,480 --> 00:01:17,200
但是这一次的有点不同
But this one is a bit different
16
00:01:17,200 --> 00:01:19,200
她的两个炉子
She has two stoves here
17
00:01:19,200 --> 00:01:23,160
一个是做面饼 另一个只是做馅儿
One for the bum and one for the stuffing
18
00:01:23,160 --> 00:01:27,000
这个馅儿是用鸡蛋和猪肉（泥）做的
The stuffing is made of eggs and (minced) pork
19
00:01:27,000 --> 00:01:29,960
然后呢 就是把面饼还有馅饼
Then she puts the bum and the stuffing together
20
00:01:29,960 --> 00:01:33,600
两个夹在一起 中间可以夹上黄瓜、香菜
With some cucumber and coriander
21
00:01:33,600 --> 00:01:36,160
还有涂抹上一些酱料
Then some sauce
22
00:01:36,160 --> 00:01:39,200
这里面可以是甜的酱 也可以是辣的酱
The sauce could be sweet or spicy
23
00:01:39,200 --> 00:01:41,160
辣的酱是什么 老干妈
The spicy sauce was actually the LAOGANMA chili sauce
24
00:02:08,880 --> 00:02:10,560
马上吃好吃
It tastes better if you eat immediately
25
00:02:44,360 --> 00:02:46,680
(这些菜自己看着选择)
Pic the vegetable you like
26
00:02:48,600 --> 00:02:49,480
都加哦
(Everything?)
27
00:02:49,480 --> 00:02:50,800
可以
Yes
28
00:02:54,600 --> 00:02:56,160
要甜的 要辣
(Sweet or spicy?)
29
00:02:56,200 --> 00:02:58,680
要甜的吧
Sweet please
30
00:02:59,160 --> 00:03:00,680
花生酱要哦
(Peanut butter?)
31
00:03:00,680 --> 00:03:01,680
要
Yes
32
00:03:03,200 --> 00:03:06,040
花了40多分钟 我们买了3个鸡蛋汉堡
We waited for 40 minutes to get three egg burgers
33
00:03:06,040 --> 00:03:07,880
这里面有甜的 有辣的
We have sweet ones and spicy ones
34
00:03:07,880 --> 00:03:09,720
里面都加了花生酱
Peanut butter is a must
35
00:03:09,720 --> 00:03:11,720
第一次尝试这种鸡蛋汉堡
I’ve never had this egg burger befure
36
00:03:11,880 --> 00:03:18,240
走吧 我们要朝前看一看还有什么好吃的
Let’s keep waking and see if there is anything else to eat
37
00:03:18,240 --> 00:03:20,240
虾饼
Shrimp cake
38
00:03:31,920 --> 00:03:33,320
阿姨 我想买一个
Aunty, I would like to have one
39
00:03:33,320 --> 00:03:35,600
这个是虾饼吗
Is this the shrimp cake?
40
00:03:36,440 --> 00:03:37,560
要不要甜辣酱
(Yes, do you want sweet chili sauce with it?)
41
00:03:37,560 --> 00:03:39,320
要甜辣酱
Yes please
42
00:03:40,360 --> 00:03:43,440
这个是直接用鲜的小虾来炸
So it is made with fresh shrimps!
43
00:03:44,720 --> 00:03:47,040
我还没给钱呢
Wait I need to pay first
44
00:04:07,600 --> 00:04:09,520
5块钱吗
5 Yuan?
45
00:04:09,520 --> 00:04:11,480
是5块钱
(Yes 5 Yuan)
46
00:04:15,120 --> 00:04:17,720
钱过去了
Here is the money
47
00:04:18,900 --> 00:04:20,900
自己想吃 也想让朋友来一份
I want it for myself and my friend
48
00:04:43,840 --> 00:04:46,160
我刚才就在问她说 有没有这样子
(I was asking if it’s possible)
49
00:04:46,160 --> 00:04:46,880
可以两个（都加）
To have both the oyster and the shrimp?
50
00:04:46,880 --> 00:04:49,120
对 我就叫她混合着
(Yes so I ordered one with both)
51
00:04:49,680 --> 00:04:50,760
你哪里来的
(Where are you from)
52
00:04:50,760 --> 00:04:53,040
山东
Shandong
53
00:04:54,640 --> 00:04:55,880
我台湾来的
(Oh I’m from Taiwan)
54
00:04:55,880 --> 00:04:57,320
你是第一次吃这个吗
Is it the first time for you?
55
00:04:57,320 --> 00:04:59,040
第一次
(Yes)
56
00:05:03,960 --> 00:05:05,680
甜辣酱要吗
(Sweet chili sauce?)
57
00:05:06,280 --> 00:05:07,680
要一点点
(Yes a little bit)
58
00:05:18,280 --> 00:05:20,600
这可能是我见过最小的摊位了
That’s the smallest stand I’ve ever seen
59
00:05:23,120 --> 00:05:25,520
阿姨 多少钱一个 5元钱？
Aunty, how much is it? (5 Yuan)
60
00:05:26,080 --> 00:05:27,760
里面卷的是什么
What’s in it?
61
00:05:27,760 --> 00:05:29,360
菜
(Vegetables)
62
00:05:29,360 --> 00:05:30,200
里面有什么
What?
63
00:05:30,200 --> 00:05:31,680
好多种菜
(Different types of ingredients)
64
00:05:33,200 --> 00:05:34,760
有瘦肉丝 有海蛎
(There’s pork, oyster)
65
00:05:36,000 --> 00:05:39,040
很多种菜 有10几种菜
(Like 10 ingredients in it)
66
00:05:39,040 --> 00:05:43,940
高丽菜 红萝卜 荷兰豆 芹菜 蒜
(Cabbage, carrot, snow pea, celery, garlic) 
67
00:05:44,120 --> 00:05:45,400
好多种呢
(All kinds of them)
68
00:05:45,960 --> 00:05:48,480
过去了
I’ve made the payment
69
00:05:48,480 --> 00:05:51,400
阿姨 一直是您两个人在这边吗
Aunty, is it always the two of you here?
70
00:05:51,400 --> 00:05:52,400
一直是两个人吗
Always you two?
71
00:05:52,400 --> 00:05:54,160
有的时候会换人
(Sometimes someone else)
72
00:05:54,160 --> 00:05:56,400
我们是一家人在做的
(We have a big family working on this)
73
00:05:56,600 --> 00:05:58,480
有时候 换一下
(So sometimes we switch)
74
00:05:58,480 --> 00:06:01,800
这个巷子 也就够一个人来回走
This is a small alley to fit only one person.
75
00:06:01,800 --> 00:06:03,640
多一个人都不行
Only room for one
76
00:06:10,360 --> 00:06:12,840
从局口街里走出来 感觉人好热闹
I just got out of the block, it’s so crowded here
77
00:06:12,840 --> 00:06:15,320
视野也宽敞了很多
And a better view too
78
00:06:30,880 --> 00:06:31,920
好了 我们尝一尝
OK time to try them
79
00:06:31,920 --> 00:06:34,600
鸡蛋汉堡是什么样的（味道）
I wonder what the egg burgers take like
80
00:06:34,600 --> 00:06:36,080
不过做的时候 我会发现
I noticed that when these were being made,
81
00:06:36,080 --> 00:06:37,960
它（鸡蛋汉堡）里面的料 感觉好足
There’s quite some filling in it.
82
00:06:37,960 --> 00:06:41,640
就是 她（阿姨）把馅做成了一个馅饼
She almost turned the stuffing into a pancake already
83
00:06:41,640 --> 00:06:43,040
真的是一个馅饼
It really is
84
00:06:43,040 --> 00:06:45,880
和这个面饼是一样大的
It’s as big as the bum
85
00:06:46,840 --> 00:06:48,440
感觉很厚实
Quite solid
86
00:06:52,160 --> 00:06:53,760
它这个是咸的
It’s a bit salty
87
00:06:53,760 --> 00:06:55,600
但是你能够吃出来的就是
You can taste the flavor of 
88
00:06:55,600 --> 00:06:57,400
猪肉和鸡蛋的这种香味
Pork and eggs.
89
00:06:57,400 --> 00:07:00,160
这个汉堡最大的特点就是料很足
The best part about this burger is that the stuffing
90
00:07:00,160 --> 00:07:02,720
毕竟她已经把料做成了一个饼
Afterall, the stuffing is as big as a burger
91
00:07:02,720 --> 00:07:05,200
完全不输于另外一个饼皮
It’s as thick as the bum
92
00:07:06,560 --> 00:07:09,040
黄瓜还挺鲜的
Cucumber is quite fresh too
93
00:07:12,040 --> 00:07:14,360
不行了 现在我要去赶车了
Alright I need to go to catch my train
94
00:07:14,360 --> 00:07:16,000
等到火车上 再给大家录吧
I will record more when I’m on the train
95
00:07:16,000 --> 00:07:17,040
走吧
Let’s go
96
00:07:34,760 --> 00:07:37,360
到了 坐下了
OK I’m on my seat
97
00:07:53,200 --> 00:07:55,200
这车上的人特别多
It’s quite crowded on the train
98
00:07:55,200 --> 00:07:59,120
不太好意思让饭菜的味道出来
I’m a bit shy to eat here
99
00:07:59,720 --> 00:08:02,760
我们下车再吃吧
So let’s eat them after we arrive.
100
00:08:03,760 --> 00:08:05,040
饿死了
I’m starving
101
00:08:09,080 --> 00:08:11,360
实在是太饿了
Really starving
102
00:08:11,360 --> 00:08:13,360
现在是晚上6点多了
It’s 6 pm now
103
00:08:15,000 --> 00:08:17,000
默默吃光了
I ate everything already.
104
00:08:24,120 --> 00:08:26,120
不行了 太困了
Sorry but I’m too sleepy
105
00:08:27,680 --> 00:08:30,680
关 注
雪 鱼 探 店
Follow me

**Comment by immoonancient** [comment]
已发布
