### ISSUE TITLE
[华农兄弟] 华农兄弟抬了个兄弟家的烤炉回来顺便再去抓只兄弟家的鸡来烤 - https://youtu.be/wde3Qm5K6Zo

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#472]
https://youtu.be/wde3Qm5K6Zo
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 10, 2019 at 12:07PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
