### ISSUE TITLE
【美食作家王刚】青椒炒荷包蛋 - https://youtu.be/Y8kaaHdGDWU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#480]
【美食作家王刚】青椒炒荷包蛋 - https://youtu.be/Y8kaaHdGDWU
视频时长 5:04，预计发布时间为北京时间12月17日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.045,0:00:01.440
哈喽大家好 我是王刚

0:00:01.440,0:00:03.315
本期视频我和大家分享一道家常菜

0:00:03.315,0:00:04.920
青椒炒荷包蛋

0:00:04.920,0:00:06.545
首先我们准备鸡蛋6个

0:00:06.545,0:00:09.615
鸡蛋不用打开清点数量备用即可

0:00:09.920,0:00:11.920
下一步开始准备辅料

0:00:12.200,0:00:15.180
准备二荆条6个去掉辣椒蒂之后切成小粒备用

0:00:15.180,0:00:17.700
不能吃辣的同学可以用大青椒替换

0:00:34.245,0:00:36.375
准备小半个大红椒切成小粒备用

0:00:36.375,0:00:38.305
加红椒的目的是配色

0:00:46.785,0:00:49.785
准备大葱1根从中间切开之后切成小粒备用

0:00:49.785,0:00:51.360
此菜属于急火爆炒

0:00:51.360,0:00:53.860
所以必须将大葱中间改刀切

0:01:01.440,0:01:04.100
最后准备大蒜3颗拍散之后剁碎备用

0:01:05.800,0:01:07.320
下一步开始制作

0:01:07.320,0:01:08.800
首先我们把锅烧热

0:01:08.800,0:01:11.260
锅烧热之后加入适量的底油滑锅

0:01:14.820,0:01:16.600
滑好锅之后将热油到出

0:01:17.495,0:01:19.855
然后直接打入鸡蛋煎至两面金黄

0:01:20.200,0:01:22.880
同学们切记煎蛋必须小火慢煎

0:01:22.880,0:01:25.140
锅中且不能有生水否则必粘

0:02:16.095,0:02:19.195
待鸡蛋完全定型之后开始轻轻晃动铁锅

0:02:38.340,0:02:40.720
然后将其翻过来继续兼职金黄

0:02:52.820,0:02:55.520
将剩余的5个鸡蛋按照此法煎制

0:03:45.600,0:03:46.960
下一步开始炒制

0:03:47.180,0:03:49.460
鸡蛋到出之后加入少许底油烧热

0:03:52.440,0:03:55.660
油温烧热之后将准备好的青椒以及辅料全部下锅

0:03:58.980,0:04:02.220
然后转大火将青椒翻炒出大量锅气且炒至断生

0:04:07.880,0:04:09.780
青椒断生之后开始调味

0:04:10.180,0:04:11.580
锅中加入食用盐1勺（约2克）

0:04:12.400,0:04:13.960
加入少许白糖提鲜

0:04:14.400,0:04:15.800
加入少许鸡精

0:04:17.440,0:04:19.460
加入生抽酱油5克从锅边淋入

0:04:20.420,0:04:22.580
然后加入少许明油从锅边淋入

0:04:23.720,0:04:25.420
最后加入煎好的鸡蛋下锅

0:04:28.620,0:04:31.000
然后关火翻炒均匀即可出锅装盘

0:04:44.680,0:04:47.500
一道非常美味的青椒炒荷包蛋就制作完成

0:04:50.160,0:04:51.740
下面开始技术总结

0:04:51.740,0:04:54.840
第一，此菜非常简单，特别适合新手操作

0:04:54.840,0:04:57.900
第二，不能吃辣的同学可以选择其它种类的辣椒

0:04:57.980,0:05:01.640
第三，最后关火翻炒的目的是防止辣椒的香味丢失

0:05:01.640,0:05:03.760
青椒炒荷包蛋的技术总结完毕

**Comment by sugarfreec** [comment]
I’ll take it

**Comment by sugarfreec** [comment]
Alan

> 【美食作家王刚】青椒炒荷包蛋 - https://youtu.be/Y8kaaHdGDWU
> 视频时长 5:04，预计发布时间为北京时间12月17日晚
> 
> 这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
> 文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
> 
> 0:00:00.045,0:00:01.440
> 哈喽大家好 我是王刚
> Hello,everyone,I’m WangGang.
> 0:00:01.440,0:00:03.315
> 本期视频我和大家分享一道家常菜
> In today’s video I’m gonna share with everybody a homely dish
> 0:00:03.315,0:00:04.920
> 青椒炒荷包蛋
> “poached egg fry green pepper“
> 0:00:04.920,0:00:06.545
> 首先我们准备鸡蛋6个
> First,prepared six eggs ,
> 0:00:06.545,0:00:09.615
> 鸡蛋不用打开清点数量备用即可
> we needn’t crack eggs,just count the number of eggs for later use.
> 0:00:09.920,0:00:11.920
> 下一步开始准备辅料
> Next,prepare the minor ingredients.
> 0:00:12.200,0:00:15.180
> 准备二荆条6个去掉辣椒蒂之后切成小粒备用
> Dice six "Erjingtiao" chili pepper for later use,
> 0:00:15.180,0:00:17.700
> 不能吃辣的同学可以用大青椒替换
> if you can’t eat spicily ,you can replace it with green bell pepper.
> 0:00:34.245,0:00:36.375
> 准备小半个大红椒切成小粒备用
> Dice a half red bell pepper for later use,
> 0:00:36.375,0:00:38.305
> 加红椒的目的是配色
> the purpose of adding red bell pepper is to match colors.
> 0:00:46.785,0:00:49.785
> 准备大葱1根从中间切开之后切成小粒备用
> spring onions are split in half and dice it for later use.
> 0:00:49.785,0:00:51.360
> 此菜属于急火爆炒
> This dish need to fry on high heat,
> 0:00:51.360,0:00:53.860
> 所以必须将大葱中间改刀切
> so we must cut spring onions in the middle,
> 0:01:01.440,0:01:04.100
> 最后准备大蒜3颗拍散之后剁碎备用
> finally cut garlic into small pieces for later use.
> 0:01:05.800,0:01:07.320
> 下一步开始制作
> Next we start cooking.
> 0:01:07.320,0:01:08.800
> 首先我们把锅烧热
>First heat the wok,
> 0:01:08.800,0:01:11.260
> 锅烧热之后加入适量的底油滑锅
> after the wok was heated,add some base oil to grease the wok,
> 0:01:14.820,0:01:16.600
> 滑好锅之后将热油到出
> Pour out hot oil after greasing wok,
> 0:01:17.495,0:01:19.855
> 然后直接打入鸡蛋煎至两面金黄
> directly whip eggs into wok and fry eggs until golden,
> 0:01:20.200,0:01:22.880
> 同学们切记煎蛋必须小火慢煎
> Remember fry eggs must use soft fire to fry,
> 0:01:22.880,0:01:25.140
> 锅中且不能有生水否则必粘
> there must be no unboiled water in the wok,
> 0:02:16.095,0:02:19.195
> 待鸡蛋完全定型之后开始轻轻晃动铁锅
> when eggs fried to fixed shape,
> 0:02:38.340,0:02:40.720
> 然后将其翻过来继续兼职金黄
> then fry another side until golden,
> 0:02:52.820,0:02:55.520
> 将剩余的5个鸡蛋按照此法煎制
> The remaining  five eggs are made the same way.
> 0:03:45.600,0:03:46.960
> 下一步开始炒制
> Next we start frying. 
> 0:03:47.180,0:03:49.460
> 鸡蛋到出之后加入少许底油烧热
> Add some base oil when pour out eggs.
> 0:03:52.440,0:03:55.660
> 油温烧热之后将准备好的青椒以及辅料全部下锅
> add in all other ingredients.
> 0:03:58.980,0:04:02.220
> 然后转大火将青椒翻炒出大量锅气且炒至断生
> Turn into big fire,continue stir-fry green bell pepper until a bring out the Wok-hei and softened.
> 0:04:07.880,0:04:09.780
> 青椒断生之后开始调味
> Then we start to seasoning.
> 0:04:10.180,0:04:11.580
> 锅中加入食用盐1勺（约2克）
> Add in 2 grams of salt,
> 0:04:12.400,0:04:13.960
> 加入少许白糖提鲜
> a pinch of sugar,
> 0:04:14.400,0:04:15.800
> 加入少许鸡精
> a pinch of chicken flavoring,
> 0:04:17.440,0:04:19.460
> 加入生抽酱油5克从锅边淋入
> then add 5 grams of light soy sauce along the side of the wok,toss evenly.
> 0:04:20.420,0:04:22.580
> 然后加入少许明油从锅边淋入
> Then add in some Ming You (literally "brightening oil") along the side of the wok,
> 0:04:23.720,0:04:25.420
> 最后加入煎好的鸡蛋下锅
>lastly add in fried eggs,
> 0:04:28.620,0:04:31.000
> 然后关火翻炒均匀即可出锅装盘
> then turn off fire toss and stir-fry.now it’s ready to be set on plate.
> 0:04:44.680,0:04:47.500
> 一道非常美味的青椒炒荷包蛋就制作完成
> A very delicious poached egg fry green pepper was completed.
> 0:04:50.160,0:04:51.740
> 下面开始技术总结
> The technical summaries are as follow 
> 0:04:51.740,0:04:54.840
> 第一，此菜非常简单，特别适合新手操作
> First,the method which cook this dish is very easy,so it’s perfect for novices.
> 0:04:54.840,0:04:57.900
> 第二，不能吃辣的同学可以选择其它种类的辣椒
> Second,if you cannot eat spicy,you can pick other kind chili.
> 0:04:57.980,0:05:01.640
> 第三，最后关火翻炒的目的是防止辣椒的香味丢失
> Third,lastly turn off the fire and stir-fry is aimed to prevent the loss of the scent of chili peppers.
> 0:05:01.640,0:05:03.760
> 青椒炒荷包蛋的技术总结完毕

-

**Comment by sugarfreec** [comment]
bot, please upload

**Comment by sugarfreec** [comment]
bot, please upload

> Alan
> 
> > 【美食作家王刚】青椒炒荷包蛋 - https://youtu.be/Y8kaaHdGDWU
> > 视频时长 5:04，预计发布时间为北京时间12月17日晚
> > 这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
> > 文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
> > 0:00:00.045,0:00:01.440
> > 哈喽大家好 我是王刚
> > Hello,everyone,I’m WangGang.
> > 0:00:01.440,0:00:03.315
> > 本期视频我和大家分享一道家常菜
> > In today’s video I’m gonna share with everybody a homely dish
> > 0:00:03.315,0:00:04.920
> > 青椒炒荷包蛋
> > “poached egg fry green pepper“
> > 0:00:04.920,0:00:06.545
> > 首先我们准备鸡蛋6个
> > First,prepared six eggs ,
> > 0:00:06.545,0:00:09.615
> > 鸡蛋不用打开清点数量备用即可
> > we needn’t crack eggs,just count the number of eggs for later use.
> > 0:00:09.920,0:00:11.920
> > 下一步开始准备辅料
> > Next,prepare the minor ingredients.
> > 0:00:12.200,0:00:15.180
> > 准备二荆条6个去掉辣椒蒂之后切成小粒备用
> > Dice six "Erjingtiao" chili pepper for later use,
> > 0:00:15.180,0:00:17.700
> > 不能吃辣的同学可以用大青椒替换
> > if you can’t eat spicily ,you can replace it with green bell pepper.
> > 0:00:34.245,0:00:36.375
> > 准备小半个大红椒切成小粒备用
> > Dice a half red bell pepper for later use,
> > 0:00:36.375,0:00:38.305
> > 加红椒的目的是配色
> > the purpose of adding red bell pepper is to match colors.
> > 0:00:46.785,0:00:49.785
> > 准备大葱1根从中间切开之后切成小粒备用
> > spring onions are split in half and dice it for later use.
> > 0:00:49.785,0:00:51.360
> > 此菜属于急火爆炒
> > This dish need to fry on high heat,
> > 0:00:51.360,0:00:53.860
> > 所以必须将大葱中间改刀切
> > so we must cut spring onions in the middle,
> > 0:01:01.440,0:01:04.100
> > 最后准备大蒜3颗拍散之后剁碎备用
> > finally cut garlic into small pieces for later use.
> > 0:01:05.800,0:01:07.320
> > 下一步开始制作
> > Next we start cooking.
> > 0:01:07.320,0:01:08.800
> > 首先我们把锅烧热
> > First heat the wok,
> > 0:01:08.800,0:01:11.260
> > 锅烧热之后加入适量的底油滑锅
> > after the wok was heated,add some base oil to grease the wok,
> > 0:01:14.820,0:01:16.600
> > 滑好锅之后将热油到出
> > Pour out hot oil after greasing wok,
> > 0:01:17.495,0:01:19.855
> > 然后直接打入鸡蛋煎至两面金黄
> > directly whip eggs into wok and fry eggs until golden,
> > 0:01:20.200,0:01:22.880
> > 同学们切记煎蛋必须小火慢煎
> > Remember fry eggs must use soft fire to fry,
> > 0:01:22.880,0:01:25.140
> > 锅中且不能有生水否则必粘
> > there must be no unboiled water in the wok,
> > 0:02:16.095,0:02:19.195
> > 待鸡蛋完全定型之后开始轻轻晃动铁锅
> > when eggs fried to fixed shape,
> > 0:02:38.340,0:02:40.720
> > 然后将其翻过来继续兼职金黄
> > then fry another side until golden,
> > 0:02:52.820,0:02:55.520
> > 将剩余的5个鸡蛋按照此法煎制
> > The remaining  five eggs are made the same way.
> > 0:03:45.600,0:03:46.960
> > 下一步开始炒制
> > Next we start frying.
> > 0:03:47.180,0:03:49.460
> > 鸡蛋到出之后加入少许底油烧热
> > Add some base oil when pour out eggs.
> > 0:03:52.440,0:03:55.660
> > 油温烧热之后将准备好的青椒以及辅料全部下锅
> > add in all other ingredients.
> > 0:03:58.980,0:04:02.220
> > 然后转大火将青椒翻炒出大量锅气且炒至断生
> > Turn into big fire,continue stir-fry green bell pepper until a bring out the Wok-hei and softened.
> > 0:04:07.880,0:04:09.780
> > 青椒断生之后开始调味
> > Then we start to seasoning.
> > 0:04:10.180,0:04:11.580
> > 锅中加入食用盐1勺（约2克）
> > Add in 2 grams of salt,
> > 0:04:12.400,0:04:13.960
> > 加入少许白糖提鲜
> > a pinch of sugar,
> > 0:04:14.400,0:04:15.800
> > 加入少许鸡精
> > a pinch of chicken flavoring,
> > 0:04:17.440,0:04:19.460
> > 加入生抽酱油5克从锅边淋入
> > then add 5 grams of light soy sauce along the side of the wok,toss evenly.
> > 0:04:20.420,0:04:22.580
> > 然后加入少许明油从锅边淋入
> > Then add in some Ming You (literally "brightening oil") along the side of the wok,
> > 0:04:23.720,0:04:25.420
> > 最后加入煎好的鸡蛋下锅
> > lastly add in fried eggs,
> > 0:04:28.620,0:04:31.000
> > 然后关火翻炒均匀即可出锅装盘
> > then turn off fire toss and stir-fry.now it’s ready to be set on plate.
> > 0:04:44.680,0:04:47.500
> > 一道非常美味的青椒炒荷包蛋就制作完成
> > A very delicious poached egg fry green pepper was completed.
> > 0:04:50.160,0:04:51.740
> > 下面开始技术总结
> > The technical summaries are as follow
> > 0:04:51.740,0:04:54.840
> > 第一，此菜非常简单，特别适合新手操作
> > First,the method which cook this dish is very easy,so it’s perfect for novices.
> > 0:04:54.840,0:04:57.900
> > 第二，不能吃辣的同学可以选择其它种类的辣椒
> > Second,if you cannot eat spicy,you can pick other kind chili.
> > 0:04:57.980,0:05:01.640
> > 第三，最后关火翻炒的目的是防止辣椒的香味丢失
> > Third,lastly turn off the fire and stir-fry is aimed to prevent the loss of the scent of chili peppers.
> > 0:05:01.640,0:05:03.760
> > 青椒炒荷包蛋的技术总结完毕

**Comment by sugarfreec** [comment]
bot, please upload

> > 【美食作家王刚】青椒炒荷包蛋 - https://youtu.be/Y8kaaHdGDWU
> > 视频时长 5:04，预计发布时间为北京时间12月17日晚
> > 这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
> > 文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
> > 0:00:00.045,0:00:01.440
> > 哈喽大家好 我是王刚
> > Hello,everyone,I’m WangGang.
> > 0:00:01.440,0:00:03.315
> > 本期视频我和大家分享一道家常菜
> > In today’s video I’m gonna share with everybody a homely dish
> > 0:00:03.315,0:00:04.920
> > 青椒炒荷包蛋
> > “poached egg fry green pepper“
> > 0:00:04.920,0:00:06.545
> > 首先我们准备鸡蛋6个
> > First,prepared six eggs ,
> > 0:00:06.545,0:00:09.615
> > 鸡蛋不用打开清点数量备用即可
> > we needn’t crack eggs,just count the number of eggs for later use.
> > 0:00:09.920,0:00:11.920
> > 下一步开始准备辅料
> > Next,prepare the minor ingredients.
> > 0:00:12.200,0:00:15.180
> > 准备二荆条6个去掉辣椒蒂之后切成小粒备用
> > Dice six "Erjingtiao" chili pepper for later use,
> > 0:00:15.180,0:00:17.700
> > 不能吃辣的同学可以用大青椒替换
> > if you can’t eat spicily ,you can replace it with green bell pepper.
> > 0:00:34.245,0:00:36.375
> > 准备小半个大红椒切成小粒备用
> > Dice a half red bell pepper for later use,
> > 0:00:36.375,0:00:38.305
> > 加红椒的目的是配色
> > the purpose of adding red bell pepper is to match colors.
> > 0:00:46.785,0:00:49.785
> > 准备大葱1根从中间切开之后切成小粒备用
> > spring onions are split in half and dice it for later use.
> > 0:00:49.785,0:00:51.360
> > 此菜属于急火爆炒
> > This dish need to fry on high heat,
> > 0:00:51.360,0:00:53.860
> > 所以必须将大葱中间改刀切
> > so we must cut spring onions in the middle,
> > 0:01:01.440,0:01:04.100
> > 最后准备大蒜3颗拍散之后剁碎备用
> > finally cut garlic into small pieces for later use.
> > 0:01:05.800,0:01:07.320
> > 下一步开始制作
> > Next we start cooking.
> > 0:01:07.320,0:01:08.800
> > 首先我们把锅烧热
> > First heat the wok,
> > 0:01:08.800,0:01:11.260
> > 锅烧热之后加入适量的底油滑锅
> > after the wok was heated,add some base oil to grease the wok,
> > 0:01:14.820,0:01:16.600
> > 滑好锅之后将热油到出
> > Pour out hot oil after greasing wok,
> > 0:01:17.495,0:01:19.855
> > 然后直接打入鸡蛋煎至两面金黄
> > directly whip eggs into wok and fry eggs until golden,
> > 0:01:20.200,0:01:22.880
> > 同学们切记煎蛋必须小火慢煎
> > Remember fry eggs must use soft fire to fry,
> > 0:01:22.880,0:01:25.140
> > 锅中且不能有生水否则必粘
> > there must be no unboiled water in the wok,
> > 0:02:16.095,0:02:19.195
> > 待鸡蛋完全定型之后开始轻轻晃动铁锅
> > when eggs fried to fixed shape,
> > 0:02:38.340,0:02:40.720
> > 然后将其翻过来继续兼职金黄
> > then fry another side until golden,
> > 0:02:52.820,0:02:55.520
> > 将剩余的5个鸡蛋按照此法煎制
> > The remaining  five eggs are made the same way.
> > 0:03:45.600,0:03:46.960
> > 下一步开始炒制
> > Next we start frying.
> > 0:03:47.180,0:03:49.460
> > 鸡蛋到出之后加入少许底油烧热
> > Add some base oil when pour out eggs.
> > 0:03:52.440,0:03:55.660
> > 油温烧热之后将准备好的青椒以及辅料全部下锅
> > add in all other ingredients.
> > 0:03:58.980,0:04:02.220
> > 然后转大火将青椒翻炒出大量锅气且炒至断生
> > Turn into big fire,continue stir-fry green bell pepper until a bring out the Wok-hei and softened.
> > 0:04:07.880,0:04:09.780
> > 青椒断生之后开始调味
> > Then we start to seasoning.
> > 0:04:10.180,0:04:11.580
> > 锅中加入食用盐1勺（约2克）
> > Add in 2 grams of salt,
> > 0:04:12.400,0:04:13.960
> > 加入少许白糖提鲜
> > a pinch of sugar,
> > 0:04:14.400,0:04:15.800
> > 加入少许鸡精
> > a pinch of chicken flavoring,
> > 0:04:17.440,0:04:19.460
> > 加入生抽酱油5克从锅边淋入
> > then add 5 grams of light soy sauce along the side of the wok,toss evenly.
> > 0:04:20.420,0:04:22.580
> > 然后加入少许明油从锅边淋入
> > Then add in some Ming You (literally "brightening oil") along the side of the wok,
> > 0:04:23.720,0:04:25.420
> > 最后加入煎好的鸡蛋下锅
> > lastly add in fried eggs,
> > 0:04:28.620,0:04:31.000
> > 然后关火翻炒均匀即可出锅装盘
> > then turn off fire toss and stir-fry.now it’s ready to be set on plate.
> > 0:04:44.680,0:04:47.500
> > 一道非常美味的青椒炒荷包蛋就制作完成
> > A very delicious poached egg fry green pepper was completed.
> > 0:04:50.160,0:04:51.740
> > 下面开始技术总结
> > The technical summaries are as follow
> > 0:04:51.740,0:04:54.840
> > 第一，此菜非常简单，特别适合新手操作
> > First,the method which cook this dish is very easy,so it’s perfect for novices.
> > 0:04:54.840,0:04:57.900
> > 第二，不能吃辣的同学可以选择其它种类的辣椒
> > Second,if you cannot eat spicy,you can pick other kind chili.
> > 0:04:57.980,0:05:01.640
> > 第三，最后关火翻炒的目的是防止辣椒的香味丢失
> > Third,lastly turn off the fire and stir-fry is aimed to prevent the loss of the scent of chili peppers.
> > 0:05:01.640,0:05:03.760
> > 青椒炒荷包蛋的技术总结完毕

**Comment by immoonancient** [comment]
已发布
