### ISSUE TITLE
[华农兄弟] 华农兄弟又到了吃虫子的季节放点孜然烤一烤又香又脆很美味哦 - https://youtu.be/LPitnZrvZ7U

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#483]
https://youtu.be/LPitnZrvZ7U
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 14, 2019 at 11:54AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
