### ISSUE TITLE
【美食作家王刚】柴火鸡和贴饼子 - https://youtu.be/dPKSrOm5hwQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#49]
【美食作家王刚】柴火鸡和贴饼子 - https://youtu.be/dPKSrOm5hwQ 视频预计发布时间为北京时间8月14日晚6点

**Comment by SilvesterDong** [comment]
1.同学们我们在杀鸡之前先准备一个小碗
碗中加入适量的清水和食用盐
加盐水放鸡血的目的是让鸡血凝固之后更嫩口感更好

2.然后我们准备本地黑鸡1只
宰杀的时候将鸡血放入准备好的盐水碗中
因为公鸡体型较大且凶猛
所以建议在此过程中2人操作才能更加从容面对

3.放完血之后将鸡放入桶里面加入90度开水烫50秒
同学们切记开水不能到100度否则鸡皮容易烫烂
浸泡的时候尽量让公鸡不漏掉任何一个小细节

4.浸泡50秒钟之后再捞出仔细的拔掉所有鸡毛
这里跟大家分享一个小窍门
公鸡最好选择10个月以上的鸡
否则肉不香且鸡毛也很难拔

5.鸡毛拔干净之后再用明火略烧一下
这样可以去除公鸡表皮无法手工操作的细毛

6.下一步开始处理鸡身
首先用刀在鸡肚切开再掏出内脏清洗干净

7.然后将鸡腰，鸡胗，鸡肠，鸡心清洗干净备用

8.其中将鸡肠和鸡胗改刀切成小段和5毫米的厚片

9.然后加入适量的食用盐抓洗3分钟后用清水清洗干净
这一步的目的是去除鸡肠和鸡胗的黏液跟腥味
建议同学们最好能够保留这些内脏一起烹饪


10.内脏处理好之后将鸡肉剁成稍微大些的块备用
快炒的肉切细丝慢烹的鸡剁大块这是烹饪界中永恒的定律

11.鸡块砍好之后下一步开始准备辅料
准备魔芋一大块切成粗条备用

12.准备土豆1个切成块备用
准备鲜竹笋1根切成块备用
没有鲜竹笋的同学可以用笋干发涨之后代替

13.准备大红椒1个切成三角形片备用

14.下一步开始准备料头
准备适量的老姜切成小粒备用
准备1小把大蒜切成小粒备用
同学们姜蒜可以适量的多一些能增加家常的香味

15.准备适量的小米辣切成小粒备用
准备适量的红泡椒切碎备用

16.下一步开始准备香辛料
碗中加入适量的干辣椒节备用
再加入适量的桂皮，八角，和三奈
同学们图文中所有辅料的“适量”都跟鸡的体重挂钩
所以无法统一给出一个量的标准

17.下一步开始上锅操作
首先我们在锅中加入适量的清水

18.加入1勺食用盐

19.然后将处理好的魔芋土豆竹笋下锅焯水
这一步的目的是去除食材的生味和苦涩味

20.焯好水之后再捞出沥干水份备用

21.下一步开始制作
首先我们把锅烧热
锅烧热之后加入小小的“宽油”（菜籽油）

22.将菜油烧至6成热之后加入适量的青花椒和姜蒜小米辣
然后加入配好的干辣椒和香料爆香

23.料头爆香之后将剁好的公鸡下锅砖小火煸炒3分钟
这一步的目的是把公鸡水份爆干炒香

24.3分钟之后加入切好的红泡椒
再加入适量的红油豆瓣酱翻炒均匀

25.豆瓣酱炒香之后再加入适量的清水

26.再将准备好的辅料下锅（魔芋，土豆，竹笋）

27.辅料下锅之后盖上锅盖减少柴火焖煮20分钟

28.趁这个时候我们来制作包谷粑粑
首先我们在碗中加入适量的包谷粉（玉米粉）
加入适量的面粉
加入少许的小苏打

29.再加入适量的清水将其和成不干不湿的小面团

30.烧至15分钟的时候揭开锅盖加入适量的生抽酱油
然后加入适量的食用盐调咸味

31.调好味之后将切好的红椒下锅翻炒均匀

32.最后再将调好的包谷粑顺手粘在锅边
同学们也可以像我这样随心所欲的将其“哒”在锅边上（注：“哒”甩）

33.然后盖上锅盖总共烧够20分钟即可出锅
同学们需要注意后半部全程都必须小火

34.最后撒上香菜即可出锅

35.一道非常美味的柴火鸡就制作完成！


柴火鸡的技术总结
第一，公鸡最好选择土鸡且生长周期10个月以上
第二，所有的辅料都可以实行一个原则“想吃什么就放什么”
第三，竹笋必须下锅事先焯水否则味道苦涩
第四，此菜不能加鸡精味精否则会强压笋的鲜味

柴火鸡技术总结完毕！

**Comment by GUThe** [comment]
> 【美食作家王刚】柴火鸡和贴饼子 - https://youtu.be/dPKSrOm5hwQ 视频预计发布时间为北京时间8月14日晚6点

发布时间已改为15号
