### ISSUE TITLE
[华农兄弟] 华农兄弟小狗子已经睁眼会爬了把它们捉出来晒晒太阳 - https://youtu.be/gb7KHILMdCs

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#492]
https://youtu.be/gb7KHILMdCs
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 15, 2019 at 07:17PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
