### ISSUE TITLE
【美食作家王刚】处理猪肚的小技巧 - https://youtu.be/RPGgQmgUuHs

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#496]
【美食作家王刚】处理猪肚的小技巧 - https://youtu.be/RPGgQmgUuHs
视频时长 5:07，预计发布时间为北京时间12月19日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.240,0:00:01.400
哈喽大家好 我是王刚

0:00:01.400,0:00:02.980
本期视频我和大家分享

0:00:03.180,0:00:04.660
处理猪肚的小技巧

0:00:05.120,0:00:07.220
首先我们准备新鲜的猪肚一个（约750克）

0:00:07.360,0:00:10.360
市场上售卖的猪肚一般都是被摊主翻过来的

0:00:10.640,0:00:14.100
这样看起来更有卖相，同样肥肠也是如此

0:00:14.300,0:00:15.520
下一步开始处理

0:00:15.680,0:00:17.760
首先我们用剪刀将猪肚剪开

0:00:17.980,0:00:20.080
这样更方便内外清洗和处理

0:00:34.020,0:00:36.900
猪肚剪开之后再去除猪肚里面多余的油脂

0:00:37.100,0:00:40.460
这层油脂跟肥肠的不同它有一定的腥味

0:00:40.460,0:00:42.400
去除得约干净越好

0:00:42.520,0:00:44.920
手撕不动的同学也可以用剪刀剪掉

0:00:50.640,0:00:52.900
肥油去除之后加入热水挼（搓）洗几遍

0:00:53.020,0:00:55.500
这一步的目的是去除猪肚表层的胃液

0:00:55.700,0:00:57.940
同学们注意这一步必须用热水挼 （抓）

0:00:58.000,0:01:00.000
否则剩余的肥油容易腻手

0:01:00.160,0:01:02.800
同时对胃酸过敏的同学可以戴手套操作

0:01:02.980,0:01:04.580
以免对手造成腐蚀

0:01:04.580,0:01:06.260
下一步开始深度清理

0:01:12.160,0:01:14.880
首先在盆中加入一把食用盐挼（抓）洗3分钟

0:01:14.920,0:01:16.920
这一步是对猪肚的初步处理

0:01:43.780,0:01:46.040
3分钟之后加入滚水清洗干净

0:02:02.520,0:02:05.100
清洗干净之后再次加入一大把食用盐

0:02:08.060,0:02:10.400
加入适量的高度白酒用力抓5分钟

0:02:10.400,0:02:12.260
这一步的目的是去除腥臭味

0:02:23.980,0:02:26.140
中途再加入一小把干淀粉挼

0:02:26.260,0:02:28.600
加干淀粉的目的是带走抓出来的黏液

0:02:28.720,0:02:31.920
温馨提示：同学们切记此过程比较棘手和辣手

0:02:32.000,0:02:35.520
对胃酸过敏的同学和手上有伤口的同学请谨慎操作

0:02:35.920,0:02:38.300
5分钟之后加入滚水清洗干净备用

0:02:54.040,0:02:56.120
下一步开始准备煮猪肚是辅料

0:02:56.340,0:02:58.400
准备生姜1小块切成姜片备用

0:03:01.900,0:03:03.560
准备大葱1根切成片备用

0:03:07.860,0:03:09.760
碗中加入适量 的高度白酒

0:03:09.760,0:03:11.160
下一步开始煮猪肚

0:03:11.580,0:03:13.760
首先我们在锅中加入大半锅清水

0:03:15.080,0:03:17.880
然后将处理好的猪肚冷水下锅开大火煮开

0:03:38.860,0:03:40.860
大火烧开之后再撇去浮末

0:03:51.300,0:03:53.300
将猪肚焯水定型之后捞出

0:03:58.220,0:04:00.480
然后将剩余的水倒入高压锅中备用

0:04:00.560,0:04:03.120
没有高压锅的同学可以直接煮40分钟

0:04:03.120,0:04:04.380
下一步开始压猪肚

0:04:04.640,0:04:06.640
将捞出的猪肚对半切开

0:04:21.780,0:04:24.180
然后将肚头上面的白色物质刮干净

0:04:24.180,0:04:26.500
这个部位非常腥臭必须去除干净

0:04:37.500,0:04:40.320
处理干净之后放入高压锅里面上汽之后压8分钟

0:04:40.360,0:04:44.300
同学们压制8分钟这个时长可以让猪肚口感爽脆不嫩不老

0:04:44.480,0:04:47.180
喜欢有嚼劲的同学可以减少压制时间

0:04:47.180,0:04:48.740
8分钟之后即可捞出

0:04:55.400,0:04:58.940
最后根据各自的实际需求将其切成块或者条装烹饪

0:04:59.140,0:05:01.140
好了我的小技巧分享到此结束（完）

**Comment by GUThe** [comment]
Mark, come back in one hour~
