### ISSUE TITLE
【美食作家王刚】腌腊肉 - https://youtu.be/gAIL6eSjGMo

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#503]
【美食作家王刚】腌腊肉 - https://youtu.be/gAIL6eSjGMo
视频时长 10:20，预计发布时间为北京时间12月22日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.460,0:00:01.740
哈喽大家好

0:00:01.740,0:00:07.040
这个猪肉我们本来是想等让他价格下去一点再做这个腊肉

0:00:07.220,0:00:08.640
看来等不了了

0:00:08.860,0:00:10.020
我四伯爷说

0:00:10.020,0:00:12.960
可能会越等越高所以就买看半头猪

0:00:12.960,0:00:16.400
跟去年一样也是做半头100多斤一点

0:00:17.200,0:00:18.320
开始吧

0:00:20.760,0:00:23.720
我来试一下这个跟腿有好重哦

0:00:23.720,0:00:24.780
几十斤嘛

0:00:27.320,0:00:29.580
拿得起不哦 起码有40多斤嘛

0:00:29.580,0:00:31.160
50斤都有害怕

0:00:33.000,0:00:34.100
50斤都有

0:00:36.620,0:00:41.120
等会儿那个前腿留下来我改天做个肘子

0:00:42.740,0:00:45.420
哪里做肘子用前腿做哦

0:00:45.960,0:00:47.340
前肘都嘛

0:00:47.540,0:00:48.900
前肘肉多点

0:00:54.540,0:00:55.940
你帮斗他整

0:00:56.240,0:00:58.500
你帮斗四伯爷整 我整不归一

0:01:04.580,0:01:06.720
哪里有弄不归一的哦

0:01:08.380,0:01:10.680
眼见之功的活路

0:01:11.580,0:01:13.380
我没得你弄得好都嘛

0:01:13.380,0:01:14.760
那还用说

0:01:14.760,0:01:17.640
看你搞得拿行我摸到手都是爪的

0:01:17.660,0:01:18.460
是啊

0:01:19.420,0:01:23.360
看哪天二娃回来我喊他叫我耍微信了

0:01:23.360,0:01:26.600
人家全都耍微信老子耍不归一

0:01:27.160,0:01:29.380
我都可以教你撒

0:01:29.380,0:01:31.380
你要把你的老人机换了

0:01:31.600,0:01:32.780
哦噢

0:01:39.260,0:01:41.260
这个时候做腊肉还没迟撒

0:01:41.420,0:01:42.700
不得迟

0:01:42.700,0:01:44.160
排骨咋子砍法哦

0:01:44.240,0:01:45.340
诶 剔了来

0:01:45.920,0:01:48.820
把排骨抬了来（剔排骨）

0:01:49.940,0:01:51.920
四伯爷来 四伯爷专业点

0:01:51.920,0:01:54.420
你得后面打哈下手就是

0:01:54.620,0:01:57.120
我等会儿剔下来你划肉可以

0:01:57.740,0:01:59.440
我都只有在旁边望斗

0:01:59.580,0:02:01.220
挨都挨不拢（插不上手）

0:02:19.960,0:02:20.460
可以

0:02:20.580,0:02:22.720
好要得了 你去划那个 我来剔排骨

0:02:22.720,0:02:24.040
还要得

0:02:25.680,0:02:27.640
哪里要得了这么厚哦

0:02:28.040,0:02:29.920
这些瘦肉要取下来

0:02:30.180,0:02:31.220
太厚了

0:02:35.800,0:02:37.460
看你划窄点还是划宽点

0:02:39.020,0:02:41.620
划窄点就要连着划两刀

0:02:43.880,0:02:45.120
这样子再划一刀嘛

0:02:46.100,0:02:47.180
看起来安逸点

0:02:54.040,0:02:55.520
厚了还腌不透

0:02:57.080,0:02:58.100
切小坨点

0:03:10.400,0:03:12.780
去年是100几呢 130多斤噶

0:03:13.000,0:03:15.500
去年还要重点

0:03:15.500,0:03:18.540
去年子钱还相因 相因好多

0:03:19.560,0:03:21.140
便宜了差不多一半

0:03:21.140,0:03:22.860
这是你们的鸡吗 四伯爷

0:03:22.860,0:03:23.540
嗯

0:03:25.340,0:03:26.380
老母鸡

0:03:28.980,0:03:31.940
我四伯以前卖猪的时候他这个

0:03:32.620,0:03:35.240
卖一头猪挣点钱

0:03:35.300,0:03:38.360
然后剩下的猪就当时赚的

0:03:38.780,0:03:40.900
现在这个猪肉涨得厉害

0:03:41.020,0:03:44.780
一头猪平时卖不了有时候半头都卖不了

0:03:44.780,0:03:46.260
卖不了怎么办呢

0:03:46.300,0:03:49.980
工钱搭进去了不说剩的肉还要自己倒贴钱

0:03:49.980,0:03:50.620
是不哦

0:03:50.620,0:03:51.120
嗯

0:03:56.060,0:03:57.620
这块排骨可以

0:04:05.020,0:04:07.440
这个鸡真的要吃肉诶

0:04:07.640,0:04:09.260
捡点肉渣渣给它吃

0:04:11.740,0:04:13.900
这个肉直接丢得盆子里哦

0:04:14.100,0:04:15.080
可以啊

0:04:17.680,0:04:20.320
你来丢嘛漆二娃 我去炒盐巴去了

0:04:27.600,0:04:33.460
100多斤肉放2-3斤（盐）

0:04:34.360,0:04:36.300
这一包是2斤

0:04:36.300,0:04:39.540
放一包半 3斤盐

0:04:42.100,0:04:44.180
大概一包半的样子

0:04:56.620,0:04:58.340
放点香料

0:05:00.620,0:05:03.180
做腊肉嘛少不了花椒

0:05:03.180,0:05:06.160
四川人吃花椒都是一把一把的

0:05:11.820,0:05:15.320
去年我们也做了100多斤的腊肉

0:05:15.960,0:05:18.200
其实这个腊肉跟香肠吧就是说

0:05:18.460,0:05:21.540
在家里面把这个肉做好了

0:05:21.540,0:05:24.360
给外面的亲戚呀朋友呀带一点

0:05:29.600,0:05:30.300
行

0:05:31.480,0:05:32.560
炒香了已经

0:06:24.700,0:06:25.840
狗儿咯

0:06:50.220,0:06:51.360
不用刀了嘎

0:06:51.720,0:06:53.560
刀应该不用了

0:06:54.660,0:06:55.960
这里有好多点哦

0:06:57.140,0:06:58.500
差不多3两酒

0:06:59.300,0:07:00.620
3两酒差不多

0:07:01.040,0:07:02.320
够不够哦

0:07:02.780,0:07:06.140
这点到够等会儿整排骨又重新搞

0:07:06.140,0:07:08.920
酒不关事酒可以做整点儿

0:07:10.220,0:07:13.280
这个酒多放点越多越香

0:07:15.780,0:07:17.400
要把它打湿

0:07:17.400,0:07:19.700
你还有么有冰糖嘛

0:07:21.440,0:07:26.660
我们做这个腊肉香不香就看这个酒度数高不高

0:07:26.660,0:07:27.680
酒香不香

0:07:29.860,0:07:31.900
敲烂把冰糖敲烂

0:07:46.660,0:07:48.240
这个酒是不是少了嘛

0:07:48.240,0:07:49.080
不得少

0:07:49.080,0:07:50.320
没打湿均匀都嘛

0:07:52.780,0:07:53.500
不得少

0:07:55.960,0:07:57.000
放不完

0:07:57.000,0:07:58.480
肯定放不完撒

0:07:58.480,0:07:59.560
放一半

0:08:01.660,0:08:02.540
烫不烫哦

0:08:02.860,0:08:03.900
就是有点烫

0:08:04.260,0:08:05.880
烫就这样撒

0:08:06.100,0:08:06.820
你还拿手抓

0:08:06.820,0:08:08.340
清不到

0:08:08.880,0:08:11.720
我清得到都嘛拿在手里那个重量

0:08:13.620,0:08:15.080
好好好好了

0:08:15.820,0:08:16.580
好了

0:08:17.880,0:08:19.780
你说好就好

0:08:19.780,0:08:20.940
整咸了

0:08:23.060,0:08:24.640
越放越咸

0:08:24.740,0:08:26.800
吃咸点看淡点就是

0:08:27.680,0:08:28.980
噶 四伯爷

0:08:35.120,0:08:38.640
这个要放一点老姜放下去那个味道更好

0:08:40.020,0:08:44.200
你的普通话还是椒盐味的哦

0:08:44.480,0:08:46.420
我的普通话好差啊

0:08:46.800,0:08:49.460
白话（粤语）都不在话下

0:08:52.160,0:08:54.740
叫粤语

0:09:09.700,0:09:11.860
这下子把排骨直接丢进去

0:09:16.360,0:09:17.700
抓2把盐巴都够了

0:09:18.380,0:09:20.300
少抓点二娃这个少抓点

0:09:20.300,0:09:24.000
这里面有盐水都嘛 化了就要下流下去

0:09:24.340,0:09:27.180
上面的盐水化下去就可以了

0:09:29.120,0:09:31.180
好 拿去盖起来

0:09:31.400,0:09:34.320
你的意思是排骨放下面肉放上面哦

0:09:34.320,0:09:35.040
哦 对

0:09:44.600,0:09:45.540
好搞定

0:09:46.400,0:09:48.760
排归一撒 你那乱七八糟的丢

0:09:49.440,0:09:51.340
排骨没加冰糖的

0:09:51.620,0:09:53.540
肉上面有冰糖都嘛

0:09:54.020,0:09:56.380
这都有冰糖的 还要翻的都嘛

0:09:56.380,0:10:01.340
排归一你那乱七八糟的丢起看到都不顺眼

0:10:10.360,0:10:11.880
好重哦

0:10:11.880,0:10:13.780
100哒100斤肉

0:10:14.020,0:10:15.720
2000多块钱

**Comment by immoonancient** [comment]
我来吧...
