### ISSUE TITLE
[华农兄弟] 华农兄弟称一下养了几个小月的小狗子看起来小称起来还挺重的 - https://youtu.be/kp5JRMzL1-o

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#509]
https://youtu.be/kp5JRMzL1-o
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 20, 2019 at 07:02PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
