### ISSUE TITLE
[华农兄弟] 华农兄弟天冷看一下竹鼠有没有感冒顺便丢点稻草给猪做窝 - https://youtu.be/OJDHNivX19s

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#511]
https://youtu.be/OJDHNivX19s
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 21, 2019 at 01:10PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
