### ISSUE TITLE
[华农兄弟] 华农兄弟上山砍竹子顺便挖点竹笋回去炒腊肉很好吃哦 - https://youtu.be/2f687b0M2Ws

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#517]
https://youtu.be/2f687b0M2Ws
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 24, 2019 at 12:04PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
