### ISSUE TITLE
【美食作家王刚】磨豆花 - https://youtu.be/wNZ5n4sW_8Y

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#521]
【美食作家王刚】磨豆花 - https://youtu.be/wNZ5n4sW_8Y
视频时长 10:27，预计发布时间为北京时间12月28日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:05.920,0:00:07.480
这个豆子很怪啊

0:00:07.945,0:00:09.895
今年子的豆子

0:00:10.320,0:00:15.380
明年不打完到了后年打起没得豆花得

0:00:16.520,0:00:17.700
就有那么怪

0:00:17.800,0:00:20.780
交给商贩都是这个样子

0:00:22.055,0:00:24.815
不是我们把它泡点来推豆花嘛

0:00:24.925,0:00:25.925
可以啊

0:00:30.955,0:00:32.405
这个豆子是好久的啊

0:00:32.460,0:00:33.760
去年的

0:00:33.760,0:00:34.880
去年好久的

0:00:35.300,0:00:37.200
去年子收豆子的时候撒

0:00:37.820,0:00:40.180
一般收豆子是6-7月都嘛

0:00:40.180,0:00:43.380
这个黄豆已经1年多了很多都生了虫

0:00:43.780,0:00:48.040
为了不浪费呢今天把它做成豆花儿

0:00:48.040,0:00:50.720
我们富顺的千年古菜豆花儿

0:00:50.980,0:00:52.560
走嘛先拿去泡起嘛

0:00:52.560,0:00:53.480
要得

0:00:53.820,0:00:55.060
泡2个小时哦

0:00:55.060,0:00:55.700
嗯

0:00:57.340,0:00:59.340
我要练功了我的蛤蟆功

0:01:00.255,0:01:01.745
蛤蟆功

0:01:02.820,0:01:06.460
我们这个豆子泡了几个小时终于泡好了用冷水发的这个

0:01:07.680,0:01:10.060
但是还是有些硬的

0:01:10.060,0:01:11.380
有

0:01:12.740,0:01:16.560
等我伯爷把这个袖套戴起了之后我要

0:01:17.320,0:01:18.660
磨豆花儿

0:01:18.660,0:01:19.820
练功了

0:01:20.160,0:01:21.380
嘿嘿 练功来了

0:01:21.600,0:01:23.260
这个是练功哦

0:01:24.780,0:01:26.980
好了现在我们要推豆花了

0:01:27.660,0:01:28.660
先放

0:01:31.000,0:01:32.280
是朝这边撒

0:01:32.280,0:01:33.360
是朝这边

0:01:45.485,0:01:47.625
现在这个白色的浆已经出来了

0:01:56.715,0:01:58.745
这个你别说还挺累人的

0:02:01.235,0:02:03.035
磨这个要马步要扎好

0:02:03.545,0:02:04.780
腰要挺直

0:02:04.780,0:02:06.440
这个手要用力

0:02:06.960,0:02:08.220
我这样磨了一会儿

0:02:08.220,0:02:09.200
都有一点

0:02:10.865,0:02:11.980
累不累呀

0:02:11.980,0:02:12.700
累

0:02:14.760,0:02:15.760
当然累

0:02:23.680,0:02:26.380
别人都说打的（机器）没有磨的（手工磨）好吃

0:02:26.420,0:02:27.940
我也觉得磨的（手工磨）好吃

0:02:27.940,0:02:29.200
磨的肯定好吃啊

0:02:29.200,0:02:38.600
机器磨的速度快 手工磨的是慢慢磨的

0:02:39.240,0:02:42.500
这个石磨磨出来的有一股清香味

0:02:43.725,0:02:45.280
现在都可以闻得到

0:02:45.280,0:02:47.005
如果是机器打的话它就是

0:02:47.800,0:02:50.380
机器打的就没有这个清香味

0:02:51.980,0:02:58.260
就像你说的机器打的管的你得不得行都给你打过去

0:02:58.260,0:03:00.255
这个是慢慢磨的

0:03:00.260,0:03:04.560
然后这个石磨磨的话它不行的东西它出来了之后

0:03:04.560,0:03:06.060
它不会磨碎

0:03:06.340,0:03:08.860
就会更那个渣一起出来

0:03:08.860,0:03:12.840
你在外面吃的豆花用的什么来点的（制作）

0:03:12.840,0:03:14.300
石膏都嘛

0:03:14.340,0:03:19.920
石膏点的好吃过屁还是要我们这个胆水的

0:03:19.920,0:03:22.220
外面没得办法得只能这样子

0:03:22.220,0:03:24.720
胆水点的吃起口感都不一样

0:03:24.720,0:03:25.900
香味味道都不一样

0:03:25.900,0:03:27.100
是嘛

0:03:29.340,0:03:30.280
不是

0:03:30.280,0:03:32.115
这样磨起吃起多安逸安

0:03:32.120,0:03:33.620
不是工具人来 工具人

0:03:33.960,0:03:35.880
工具人来磨

0:03:37.420,0:03:38.800
这个我都搞累了

0:03:38.920,0:03:40.680
这样子朝这边不要磨反了

0:03:41.580,0:03:42.640
试一下看

0:03:44.100,0:03:45.880
我手都磨红了

0:03:48.800,0:03:50.260
戴手套

0:03:51.120,0:03:52.360
叫兄弟来帮忙

0:03:53.040,0:03:54.580
兄弟在养竹鼠

0:04:06.760,0:04:08.400
泼来当蘸水噶 嗯

0:04:13.140,0:04:13.860
轻点哈

0:04:13.860,0:04:14.500
好

0:04:26.520,0:04:28.780
多放点柴一会儿就烧开了

0:04:32.480,0:04:34.480
这个豆浆老香了

0:04:34.875,0:04:35.875
这个

0:04:36.360,0:04:37.760
手磨的豆浆

0:04:37.760,0:04:39.640
泡子不管它是不是

0:04:39.640,0:04:40.860
等会儿要散

0:04:40.860,0:04:42.540
一会儿它要散开了就要散

0:04:42.780,0:04:45.160
要这个才得行娃儿嘞

0:04:45.675,0:04:47.585
才好才方便点

0:04:47.820,0:04:51.560
我们这个把它卷好了待会儿把豆浆直接倒进去

0:04:51.560,0:04:53.775
剩下的渣就滤在这个里面来了

0:04:53.780,0:04:57.420
然后里面的那个浆再烧开了就可以当豆浆喝了

0:04:57.580,0:04:59.520
这个非常浓的

0:05:05.860,0:05:06.880
好香哦这个

0:05:06.880,0:05:08.840
我还是觉得 哎呀太幸福了

0:05:10.100,0:05:11.380
幸福的味道

0:05:14.740,0:05:16.860
这是我们剩下的渣滓把它

0:05:17.425,0:05:18.735
把剩下的这个

0:05:19.535,0:05:21.000
豆浆挤出来

0:05:21.000,0:05:22.680
嘿 （用）这个挤还可以

0:05:22.680,0:05:23.240
是不哦

0:05:23.240,0:05:25.300
嗯 比你瓜瓢还得行

0:05:26.020,0:05:28.660
现在把里面的豆浆全部给它榨出来

0:05:28.835,0:05:31.045
这个剩的豆渣可以拿来喂猪

0:05:31.345,0:05:32.985
还可以拿来做一个菜

0:05:36.560,0:05:38.740
慢点哈不要一下倒出去了

0:05:39.620,0:05:41.240
别看这里一锅没多少

0:05:41.320,0:05:43.360
可能有40多斤

0:05:43.360,0:05:44.720
40-50斤的样子

0:05:46.360,0:05:49.360
这个豆浆是我们刚刚弄出来的我先尝一口

0:05:54.800,0:05:57.660
豆浆味特别重

0:05:57.660,0:05:59.420
伯爷尝不尝一下

0:06:00.955,0:06:02.125
我就尝哈嘛

0:06:06.160,0:06:10.100
反正这都是我们喝得拿着喝就是

0:06:12.600,0:06:15.500
嗯 这个就比你那个机子打那个豆浆喝起香啊

0:06:15.500,0:06:16.340
嗯

0:06:16.820,0:06:19.580
这个就有点特别 我跟你说

0:06:19.860,0:06:21.600
等会儿你点（豆花）吗伯娘点哦

0:06:21.640,0:06:24.360
你伯娘点 你伯娘点豆花得行还是可以

0:06:25.115,0:06:26.700
这个要一点点的加

0:06:26.700,0:06:28.085
放胆水要慢慢的点

0:06:28.085,0:06:30.660
慢慢的点要好点

0:06:41.320,0:06:44.160
以前老年人点豆花儿怎么点的呢

0:06:44.160,0:06:47.340
用筷子慢慢点 差不多要一个小时

0:06:47.975,0:06:49.300
四伯爷快过来看

0:06:49.300,0:06:50.700
噢哟 得起豆花了

0:06:50.700,0:06:51.420
起豆花了

0:06:51.420,0:06:52.080
嗯

0:06:53.380,0:06:55.440
我们这个胆水慢慢一点一点的加

0:06:55.440,0:06:59.980
加到现在加了两三次之后开始有这个豆花出来了

0:07:01.060,0:07:04.540
它这个边上的水啊它就脱离了跟这个蛋白质

0:07:10.020,0:07:12.280
等下再用筲箕我伯爷用筲箕给它压压压

0:07:12.280,0:07:15.835
压成一个小坨就变成了豆花

0:07:15.835,0:07:19.245
想吃豆腐的话就把它再煮老一点 再压紧一点

0:07:19.955,0:07:21.905
把这个（gao）水舀一点来丢

0:07:22.520,0:07:23.700
水太多了

0:07:44.600,0:07:47.380
伯爷压好了我用这个刀来划一下

0:07:47.920,0:07:49.300
一

0:07:50.260,0:07:51.720
咦 大坨很了哟

0:07:51.720,0:07:53.060
还要横起划

0:07:53.940,0:07:54.760
四

0:07:54.760,0:07:56.340
横起划 划五下就是

0:07:57.040,0:07:58.880
大坨很了不好铲 娃儿埃

0:08:00.500,0:08:02.780
边上的有点碎

0:08:02.780,0:08:04.760
有些没压到 好嫩哦

0:08:10.520,0:08:11.960
来 你来端我来铲

0:08:12.940,0:08:14.900
你铲来稀巴烂的

0:08:23.625,0:08:25.360
好 够了

0:08:25.360,0:08:26.640
我们这个豆花就做好了

0:08:26.720,0:08:30.355
现在我来跟大家演示一下怎么吃这个豆花

0:08:30.360,0:08:32.860
这个就是我们刚刚煮的那个豆花儿

0:08:32.860,0:08:35.260
然后这个蘸水是我伯娘做的

0:08:35.280,0:08:38.200
她做的是个家常 家常手法做的

0:08:38.360,0:08:39.660
就放了辣椒面

0:08:39.660,0:08:40.740
放了大蒜

0:08:40.900,0:08:45.200
放了其他一些调料用那个菜籽油给它泼出来的

0:08:45.200,0:08:48.600
放了 还放了生辣椒就是小米辣

0:08:49.040,0:08:52.980
现在就是夹点豆花儿放一点点这个

0:08:53.880,0:08:55.520
辣椒酱在上面

0:08:55.520,0:08:58.860
然后再放点小葱放点这个鱼香

0:08:58.860,0:09:01.020
下面是饭 就是和着一起吃

0:09:07.280,0:09:11.680
我伯娘调的这个味道重了一些

0:09:11.840,0:09:17.120
但是很符合我们农村的吃法

0:09:19.740,0:09:21.900
吃一口豆花喝一碗这个汤

0:09:25.940,0:09:28.180
这个汤（颜色）有点黄黄的

0:09:28.180,0:09:32.000
它是压这个豆花分解出来的这个水分

0:09:32.720,0:09:34.180
还带有一定的下火（功效）

0:09:38.080,0:09:41.680
下一次再跟大家分享做这个蘸水 专业做法

0:09:41.680,0:09:43.460
因为这个是家常版本的

0:09:43.980,0:09:49.140
可能跟那个专业的有一些区别

0:09:49.720,0:09:51.760
好了 今天本期视频就到这里

0:09:51.760,0:09:52.760
我们要吃饭了

0:09:53.840,0:09:55.000
伯爷吃饭了来

0:09:55.920,0:09:57.360
我给你整一碗

0:10:15.460,0:10:17.340
倒一碗汤喝

0:10:22.160,0:10:23.180
伯娘呢

0:10:24.260,0:10:25.060
安逸

0:10:25.060,0:10:25.980
喊她过来吃饭了

**Comment by immoonancient** [comment]
之前找的人鸽了，我现在补上吧...
