### ISSUE TITLE
【美食作家王刚】肥肠里外之分 - https://youtu.be/pvHcQFix0NA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#522]
【美食作家王刚】肥肠里外之分 - https://youtu.be/pvHcQFix0NA
视频时长 3:10，预计发布时间为北京时间12月30日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.560,0:00:01.800
哈喽大家好

0:00:01.800,0:00:03.575
今天我们又不用做菜了

0:00:03.580,0:00:06.780
今天让我伯爷留了一笼肥肠

0:00:07.000,0:00:09.120
跟大家分享一个小技巧

0:00:09.120,0:00:11.340
就是说我们前段时间

0:00:11.500,0:00:13.500
做了一个菜叫做“干煸肥肠”

0:00:13.560,0:00:17.520
当时（视频）里面我是说光滑这一面是

0:00:17.520,0:00:18.860
装大便的

0:00:19.020,0:00:20.880
装粪便的

0:00:20.880,0:00:22.920
有的粉丝他有点质疑

0:00:22.920,0:00:26.440
他说带油这边是接触粪便的一面

0:00:26.620,0:00:30.920
现在我就请伯爷做了三四十年的杀猪匠

0:00:30.920,0:00:33.260
来跟你们分享一下这个小技巧

0:00:33.500,0:00:36.740
四伯爷为什么它要翻过来安

0:00:36.740,0:00:41.520
它不翻过来里面这个粪便怎么洗得干净安

0:00:41.700,0:00:43.500
你咋个整来吃安

0:00:43.720,0:00:45.720
现在有个问题是这样的

0:00:45.760,0:00:48.300
这个肥肠出来的时候

0:00:48.300,0:00:52.480
到底是光滑这面接触粪便的

0:00:52.480,0:00:55.000
还是说带油的一面是解除粪便的

0:00:55.000,0:00:57.080
光滑一面（接触）带粪便的

0:00:57.280,0:01:03.420
里面那个角油如果带粪便你洗都洗不干净哒

0:01:03.940,0:01:07.040
现在我们看到这个肥肠就是光光滑滑的

0:01:07.040,0:01:09.360
其实这一面已经被翻过来了

0:01:09.360,0:01:11.780
翻过来了其实里面有一些油

0:01:11.940,0:01:19.240
它里面那一层油的话是那个肠连接在一起的时候粘连住的油

0:01:19.240,0:01:20.800
那个咋子说安 角油

0:01:20.800,0:01:21.680
叫角油

0:01:21.680,0:01:22.760
里面那个角油

0:01:22.760,0:01:24.980
你看嘛翻过来你看嘛

0:01:24.980,0:01:26.420
这边就（全）是角油

0:01:26.420,0:01:29.800
（如果）粪便装在里面看你怎么洗得干净

0:01:31.100,0:01:32.440
必须翻过来

0:01:33.440,0:01:37.255
开始在猪肚皮里面的时候它是这样的

0:01:37.520,0:01:40.420
这里面就是装的粪便

0:01:40.640,0:01:43.920
我们这样把它翻过来过后

0:01:43.920,0:01:49.300
那个粪便粘在上面用水一洗就洗干净了

0:01:49.620,0:01:52.660
还有一个就是这个肥肠现在是经过处理的

0:01:53.120,0:01:55.255
其实这样子看起来是一条一条的

0:01:55.260,0:01:59.260
但是它在猪的肚子里面的时候它不是一条的

0:01:59.260,0:02:00.580
它是盘起来的

0:02:00.580,0:02:03.180
它盘起来粘连的那个油（角油）

0:02:03.180,0:02:07.640
里面的那个油就是粘连肥肠的那个油

0:02:07.780,0:02:09.380
现在的话它是一条一条的

0:02:09.380,0:02:10.780
处理好了就是这样子卖

0:02:11.240,0:02:13.020
是不是  是啊

0:02:13.260,0:02:14.520
它就是弄个子的撒

0:02:14.580,0:02:19.020
你看 到市场上你去看那些屠夫些卖肉

0:02:19.340,0:02:22.220
这个大肠就是弄个子翻起的 翻来卖起的

0:02:22.300,0:02:24.900
你那样翻转来 全是角油 乱翻翻的

0:02:24.900,0:02:27.560
人家看着（不好看） 哪个买你的安

0:02:27.900,0:02:29.500
所以我们现在得出一个结论

0:02:29.500,0:02:33.740
就是肥肠光滑这一面是接触粪便这一面

0:02:33.740,0:02:36.720
有油的那一面它是外面的那一面

0:02:36.720,0:02:39.380
有油它用那个油粘连住这个肠子

0:02:39.620,0:02:41.120
就是说不是一条一条的

0:02:41.120,0:02:43.720
它是盘起来的肠子

0:02:44.820,0:02:46.380
好了 本期视频就到这里吧

0:02:46.380,0:02:48.140
这个问题终于搞清楚了

0:02:49.040,0:02:50.880
光滑一面是接触粪便的

0:02:50.880,0:02:54.360
不光滑带油的那一面是在外面的 对吧

0:02:54.360,0:02:55.280
嗯

0:02:56.120,0:02:57.820
在肚子头就是外面的

0:02:59.040,0:03:01.620
拿出来我们翻过来

0:03:01.620,0:03:05.720
把那个粪便那方翻过来是光滑那方是装粪便的

0:03:05.720,0:03:07.040
里头就是角油

0:03:07.580,0:03:08.380
嗯

0:03:08.380,0:03:09.700
就是弄个做起的

**Comment by heyitstracccy** [comment]
🤭

**Comment by heyitstracccy** [comment]
bot, please upload

0:00:00.560,0:00:01.800 哈喽大家好
Hello everybody
0:00:01.800,0:00:03.575 今天我们又不用做菜了
Today we are not goona cook 
0:00:03.580,0:00:06.780 今天让我伯爷留了一笼肥肠
My uncle leaves me some pork intestine
0:00:07.000,0:00:09.120 跟大家分享一个小技巧
I am gonna share a technique with you guys
0:00:09.120,0:00:11.340 就是说我们前段时间
Last time we 
0:00:11.500,0:00:13.500 做了一个菜叫做“干煸肥肠”
cooked a dish called “Fried pork intestine”
0:00:13.560,0:00:17.520 当时（视频）里面我是说光滑这一面是
In that video, I said the smooth side is to 
0:00:17.520,0:00:18.860 装大便的
hold the shit
0:00:19.020,0:00:20.880 装粪便的
hold the feces
0:00:20.880,0:00:22.920 有的粉丝他有点质疑
Some fans doubt it

0:00:22.920,0:00:26.440 他说带油这边是接触粪便的一面
He believes the side with oil is the side that contacts with the feces
0:00:26.620,0:00:30.920 现在我就请伯爷做了三四十年的杀猪匠
Now I invite my uncle who has been pig butcher for almost forty years
0:00:30.920,0:00:33.260 来跟你们分享一下这个小技巧
to share this tip
0:00:33.500,0:00:36.740 四伯爷为什么它要翻过来安
Why you turn outside in uncle?
0:00:36.740,0:00:41.520 它不翻过来里面这个粪便怎么洗得干净安
You cannot clean the feces inside thoroughly unless turn outside in
0:00:41.700,0:00:43.500 你咋个整来吃安
If you cannot clean it, you cannot eat it
0:00:43.720,0:00:45.720 现在有个问题是这样的
Now we have a question
0:00:45.760,0:00:48.300 这个肥肠出来的时候
When the pork intestine comes out
0:00:48.300,0:00:52.480 到底是光滑这面接触粪便的
whether the smooth side or the 
0:00:52.480,0:00:55.000 还是说带油的一面是解除粪便的
oily side that contacts with the feces
0:00:55.000,0:00:57.080 光滑一面（接触）带粪便的
The smooth side contacts with feces
0:00:57.280,0:01:03.420 里面那个角油如果带粪便你洗都洗不干净哒
If the oily side contacts with feces, you are not able to clean it up
0:01:03.940,0:01:07.040 现在我们看到这个肥肠就是光光滑滑的
Now we see the pork intestine is very smooth 
0:01:07.040,0:01:09.360 其实这一面已经被翻过来了
Actually, the inside is already flipped over
0:01:09.360,0:01:11.780 翻过来了其实里面有一些油
There is still some oil inside
0:01:11.940,0:01:19.240 它里面那一层油的话是那个肠连接在一起的时候粘连住的油
The oil inside is to connect the intestine together 
0:01:19.240,0:01:20.800 那个咋子说安 角油
What’s that called?
0:01:20.800,0:01:21.680 叫角油
Called “Jiao you”
0:01:21.680,0:01:22.760 里面那个角油
The “Jiao you” inside
0:01:22.760,0:01:24.980 你看嘛翻过来你看嘛
You can see
0:01:24.980,0:01:26.420 这边就（全）是角油
The “Jiao you” are all over inside
0:01:26.420,0:01:29.800 （如果）粪便装在里面看你怎么洗得干净
If the feces are inside, how can you wash them clean?
0:01:31.100,0:01:32.440 必须翻过来
So, you must turn outside in
0:01:33.440,0:01:37.255 开始在猪肚皮里面的时候它是这样的
When it still inside the pig it’s like this 
0:01:37.520,0:01:40.420 这里面就是装的粪便
The feces are hold inside
0:01:40.640,0:01:43.920 我们这样把它翻过来过后
After we turn outside in 
0:01:43.920,0:01:49.300 那个粪便粘在上面用水一洗就洗干净了
The feces stick to the above can be easily cleaned by water
0:01:49.620,0:01:52.660 还有一个就是这个肥肠现在是经过处理的
One more thing is that, this intestine is already welly dealt
0:01:53.120,0:01:55.255 其实这样子看起来是一条一条的
They look like in strip now
0:01:55.260,0:01:59.260 但是它在猪的肚子里面的时候它不是一条的
But when they are in the pork belly they 
0:01:59.260,0:02:00.580 它是盘起来的
are stacked together
0:02:00.580,0:02:03.180 它盘起来粘连的那个油（角油）
The oil (“Jiao you”) that help stack
0:02:03.180,0:02:07.640 里面的那个油就是粘连肥肠的那个油
is the oil that stick intestine together
0:02:07.780,0:02:09.380 现在的话它是一条一条的
Now they are in strips
0:02:09.380,0:02:10.780 处理好了就是这样子卖
That’s how it’s sold
0:02:11.240,0:02:13.020 是不是 是啊
Is it?
0:02:13.260,0:02:14.520 它就是弄个子的撒
That’s how it works
0:02:14.580,0:02:19.020 你看 到市场上你去看那些屠夫些卖肉
The butchers also deal like this in market 
0:02:19.340,0:02:22.220 这个大肠就是弄个子翻起的 翻来卖起的
Pork intestine needs to be turned over to sell
0:02:22.300,0:02:24.900 你那样翻转来 全是角油 乱翻翻的
If you flip in that way, the “Jiao you” will be all over and in a mess
0:02:24.900,0:02:27.560 人家看着（不好看） 哪个买你的安
Consumers won’t buy it 
0:02:27.900,0:02:29.500 所以我们现在得出一个结论
Now we come to a conclusion 
0:02:29.500,0:02:33.740 就是肥肠光滑这一面是接触粪便这一面
The smooth side of the pork intestine is the one contacts with feces
0:02:33.740,0:02:36.720 有油的那一面它是外面的那一面
The side with oil is the outside
0:02:36.720,0:02:39.380 有油它用那个油粘连住这个肠子
The oil is to stick intestine together
0:02:39.620,0:02:41.120 就是说不是一条一条的
That means not one by one 
0:02:41.120,0:02:43.720 它是盘起来的肠子
They are stacked together
0:02:44.820,0:02:46.380 好了 本期视频就到这里吧
Okay, it’s the end of this video
0:02:46.380,0:02:48.140 这个问题终于搞清楚了
Now we figure it out
0:02:49.040,0:02:50.880 光滑一面是接触粪便的
The smooth side is in contact with feces
0:02:50.880,0:02:54.360 不光滑带油的那一面是在外面的 对吧
The greasy side is on the outside, right?
0:02:54.360,0:02:55.280 嗯
Right
0:02:56.120,0:02:57.820 在肚子头就是外面的
When inside belly, the greasy side of intestine is outside
0:02:59.040,0:03:01.620 拿出来我们翻过来
Take out, and turn outside in
0:03:01.620,0:03:05.720 把那个粪便那方翻过来是光滑那方是装粪便的
The smooth side is the side that hold feces
0:03:05.720,0:03:07.040 里头就是角油
Inside is “Jiao you”
0:03:07.580,0:03:08.380 嗯
yeap
0:03:08.380,0:03:09.700 就是弄个做起的
That’s it
