### ISSUE TITLE
[华农兄弟] 华农兄弟看一下被霜打死的象草再去拔几个老弟种得萝卜来吃 - https://youtu.be/eAM6tmkN-z4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#523]
https://youtu.be/eAM6tmkN-z4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 25, 2019 at 11:31PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
這個視頻沒有開放字幕功能，不知為何，我向清哥了解一下

**Comment by vincenthychow** [comment]
現在可以了

**Comment by vincenthychow** [comment]
已發佈
