### ISSUE TITLE
【美食作家王刚】夹沙肉 - https://youtu.be/40XhlobS4L8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#525]
【美食作家王刚】夹沙肉 - https://youtu.be/40XhlobS4L8
视频时长 4:11，预计发布时间为北京时间12月31日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.000,0:00:02.220
首先我们准备铁锅一个

0:00:02.220,0:00:04.160
把锅干烧至冒烟为止

0:00:04.160,0:00:07.160
然后准备五花肉一块放入锅中烙成金黄色

0:00:07.320,0:00:10.600
这一步的目的是破坏猪皮表面的汗腺去除腥骚味

0:00:10.605,0:00:13.885
同学们制作夹沙肉最好选择肥膘多一些的五花肉

0:00:13.885,0:00:17.520
这样才能包住更多的糖沙口感实在

0:00:17.520,0:00:20.220
大约3分钟之后猪皮烙黄即可

0:00:20.220,0:00:21.500
下一步开始处理

0:00:21.600,0:00:24.060
将烙好的五花肉放入温水中擦洗干净

0:00:24.160,0:00:26.220
同学们冬天切勿用冷水清洗

0:00:26.220,0:00:29.060
否则黑色的杂质会吸附在肉上面

0:00:29.880,0:00:32.500
清洗干净之后开始准备煮肉的辅料

0:00:32.565,0:00:34.655
准备生姜几块拍散备用

0:00:38.465,0:00:40.485
准备小葱几根挽成结备用

0:00:44.320,0:00:46.040
碗中加入八角2颗

0:00:46.760,0:00:48.360
加入桂皮1小块

0:00:49.120,0:00:50.520
下一步开始煮肉

0:00:50.620,0:00:52.880
首先在锅中加入大半锅清水

0:00:55.800,0:00:57.680
然后将五花肉冷水下锅

0:01:01.380,0:01:03.120
加入准备好的辅料（生姜，小葱，八角，桂皮）

0:01:05.040,0:01:06.540
再加入适量的料酒

0:01:11.680,0:01:14.440
然后大火烧开之后转小火煮40分钟

0:01:15.700,0:01:18.000
这一步的目的是将五花肉煮熟透

0:01:18.060,0:01:20.960
40分钟后用筷子能插透猪肉即可

0:01:25.360,0:01:27.420
然后将猪肉捞出透凉备用

0:01:32.340,0:01:34.200
下一步开始准备糖沙

0:01:34.640,0:01:36.640
准备适量的核桃仁放入碗中

0:01:36.820,0:01:38.620
准备适量的花生仁备用

0:01:38.960,0:01:40.720
准备适量的黑芝麻备用

0:01:42.120,0:01:44.560
最后准备辅料1:1的白糖备用

0:01:44.560,0:01:48.455
辅料的比列为核桃2份花生仁1份黑芝麻1份（2:1:1）

0:01:48.600,0:01:51.040
比例可按照个人口味调制

0:01:51.040,0:01:52.280
下一步开始制作

0:01:52.640,0:01:55.500
锅烧热之后将辅料下过小火翻炒10分钟

0:01:55.500,0:01:57.380
这一步的目的是将其炒香

0:02:08.180,0:02:10.300
然后将所有辅料捣碎备用

0:02:14.840,0:02:17.560
辅料捣碎之后加入适量的白糖拌匀

0:02:27.460,0:02:29.560
然后我们再次把锅烧热

0:02:29.560,0:02:32.060
锅烧热之后将准备好的糖沙下锅

0:02:38.260,0:02:40.800
翻炒至略微融合后捞出

0:02:40.800,0:02:43.820
这一步的目的是让白糖更好的融入进辅料中

0:02:43.820,0:02:46.920
嫌麻烦的同学可以直接购买豆沙加糖代替

0:02:46.920,0:02:48.540
下一步开始“填沙”

0:02:48.540,0:02:50.940
首先我们将煮好的煮肉切成薄片备用

0:02:50.960,0:02:53.880
第一刀的时候不切断第二刀切断

0:02:53.880,0:02:57.340
这样的目的是让其形成夹片方便填充糖沙

0:03:09.900,0:03:13.000
然后将炒好的糖沙均匀的填充进五花肉里面

0:03:23.040,0:03:25.280
将其皮朝下工整的摆放在碗中

0:03:28.640,0:03:30.760
最后再将缺口填充上糖沙

0:03:35.600,0:03:38.200
摆放完毕之后下一步放入蒸锅

0:03:38.200,0:03:41.060
上汽之后转中小火蒸2个小时

0:03:41.060,0:03:43.640
这一步的目的是将夹沙肉蒸至入口即化

0:03:43.640,0:03:46.520
2个小时候取出倒扣在碗中即可出菜

0:03:46.740,0:03:49.780
一道农家宴席美味“夹沙肉”就制作完成

0:03:53.460,0:03:54.980
下面开始技术总结

0:03:54.980,0:03:59.040
第一，猪肉最好选择肥膘多的五花肉，这样口感更佳

0:03:59.040,0:04:02.700
第二，嫌麻烦炒糖沙的同学可以用豆沙加白糖代替

0:04:02.700,0:04:08.420
第三，此菜蒸至的时间最好2个小时以上，这样才能做到“入口即化，肥而不腻”

0:04:08.420,0:04:10.160
夹沙肉的技术总结完毕

**Comment by GUThe** [comment]
mark

**Comment by immoonancient** [comment]
修正版字幕已上传，等发布

**Comment by immoonancient** [comment]
已发布
