### ISSUE TITLE
[华农兄弟] 华农兄弟摘几朵茶花尝一下再去摘点竹节果尝一下 - https://youtu.be/RkljEo0cZQ8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#526]
https://youtu.be/RkljEo0cZQ8
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 26, 2019 at 10:10PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
更新版本亦已上載，待下一個視頻做好時會一併通知清哥審核
