### ISSUE TITLE
[华农兄弟] 华农兄弟有只竹鼠托梦给我想吃竹笋去挖个来炖它 - https://youtu.be/FzDpGodmCnc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#529]
https://youtu.be/FzDpGodmCnc
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 28, 2019 at 09:06PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
