### ISSUE TITLE
[华农兄弟] 华农兄弟天气不错把小狗抱到楼下来玩肥肥的很可爱 - https://youtu.be/utIjUZXw8nw

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#538]
https://youtu.be/utIjUZXw8nw
<p>&#35270;&#39057;&#21457;&#24067;&#20110; December 31, 2019 at 10:15PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
