### ISSUE TITLE
【美食作家王刚】炸甜酥肉 - https://youtu.be/tjCasc1BjeM

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#540]
【美食作家王刚】炸甜酥肉 - https://youtu.be/tjCasc1BjeM
视频时长 4:23，预计发布时间为北京时间1月3日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.295,0:00:03.145
首先我们来介绍主料之一“边油”

0:00:03.145,0:00:06.075
这是吸附在五花肉上面的一层肥油

0:00:06.080,0:00:09.660
每一块边口上都有一块所以俗称“边油”

0:00:10.620,0:00:12.980
这一块是猪外脊外层的肥油

0:00:12.980,0:00:14.660
也就是猪的背部肥肉

0:00:14.660,0:00:17.000
通常来说猪的背部都会有印章

0:00:17.000,0:00:20.560
印章的内容是猪肉的省份和宰杀验收的时间

0:00:20.560,0:00:23.940
如果猪肉的背部没有印章则说明猪肉的来源不明

0:00:23.940,0:00:25.460
下一步开始处理猪肉

0:00:25.460,0:00:28.300
首先我们在盆中加入40度左右的热水

0:00:28.640,0:00:30.180
然后将肥油清洗干净

0:00:30.180,0:00:32.400
同学们注意猪肥油低温容易腻手

0:00:32.400,0:00:34.620
所以最好采用热水清洗

0:00:46.620,0:00:48.760
清洗干净之后下一步开始处理

0:00:54.920,0:00:57.040
首先我们将肥油的猪皮取下

0:00:57.040,0:00:59.200
然后切成大小均匀的小块备用

0:01:08.080,0:01:10.040
边油也是同样的处理

0:01:14.880,0:01:17.020
下一步开始准备淀粉糊

0:01:17.200,0:01:19.000
碗中加入适量的玉米淀粉

0:01:20.340,0:01:21.820
加入五分之一的面粉

0:01:23.560,0:01:25.580
然后加入适量的清水调匀

0:01:40.040,0:01:42.620
淀粉糊调好之后倒入盆中搅拌均匀

0:02:02.340,0:02:04.140
中途加入适量的植物油

0:02:04.140,0:02:06.820
加植物油的目的是稀释淀粉之间的粘性

0:02:06.820,0:02:08.660
以防止原料下锅抱团

0:02:23.400,0:02:25.580
最后我们准备适量的冰糖敲散备用

0:02:25.580,0:02:28.000
冰糖的甜度和颜色比白糖更佳

0:02:28.000,0:02:30.140
不喜欢太甜的同学可以少加一些

0:02:30.140,0:02:31.300
下一步开始制作

0:02:31.360,0:02:32.920
首先我们把锅烧热

0:02:32.920,0:02:34.660
锅烧热之后加入宽油

0:02:38.320,0:02:42.340
开大火将油温烧至160度（约5.3成油温）

0:02:44.420,0:02:47.480
油温烧热之后将准备好的肥油依次下入锅中

0:03:12.120,0:03:14.700
然后转中火将肥油炸至熟透飘起来

0:03:14.720,0:03:18.240
同学们切记不可炸太老否则食用之后容易上火

0:03:18.240,0:03:20.020
只需要炸至飘起来即可

0:03:20.020,0:03:22.240
肥油完全飘起之后捞出备用

0:03:24.980,0:03:27.380
然后将热油倒出下一步开始炒制

0:03:27.920,0:03:30.220
首先我在锅中加入适量的清水

0:03:31.460,0:03:34.740
然后将准备好的冰糖下锅开中小火炒散炒化

0:03:42.180,0:03:44.740
糖炒至冒泡后加入炸好的猪油

0:03:44.740,0:03:47.560
然后马上关火炒至糖浆凉透即可出锅

0:03:47.560,0:03:51.040
喜欢吃嫩一些的同学可以多加些水炒糖浆

0:03:53.700,0:03:55.800
一道农村宴席甜品就制作完成

0:03:58.560,0:04:00.020
下面开始技术总结

0:04:00.020,0:04:03.840
第一，边油相对来说比普通肥膘要香口感更好

0:04:03.840,0:04:12.000
第二，此菜的原料是肥油，淀粉，冰糖或者白糖三者之间没有固定的比例，可以根据实际情况搭配

0:04:12.000,0:04:15.600
第三，肥油下锅之后关火炒至冷却即可出锅

0:04:15.600,0:04:17.740
农村宴席甜品的技术总结完毕

**Comment by immoonancient** [comment]
已发布
