### ISSUE TITLE
[华农兄弟] 华农兄弟祝大家2020年鼠年大吉万事如意 事业有成学业有成 - https://youtu.be/IaDZ5yR8cLg

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#543]
https://youtu.be/IaDZ5yR8cLg
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 1, 2020 at 08:10PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
祝賀類短視頻不放Github了，省點時間，及時發放才有意義
