### ISSUE TITLE
[华农兄弟] 华农兄弟搞点米糠拌饭把小猪骗回去再把猪栏修一下 - https://youtu.be/B-TE9-bSI9k

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#550]
https://youtu.be/B-TE9-bSI9k
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 3, 2020 at 06:34PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
