### ISSUE TITLE
[华农兄弟] 华农兄弟带大家看一下花竹鼠顺便看一下它的崽很漂亮哦 - https://youtu.be/uadvt8DNsE8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#556]
https://youtu.be/uadvt8DNsE8
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 4, 2020 at 09:35PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
已發佈
