### ISSUE TITLE
【美食作家王刚】辣烧甲鱼 - https://youtu.be/Cy7QTnQvchE

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#560]
【美食作家王刚】辣烧甲鱼 - https://youtu.be/Cy7QTnQvchE
视频时长 11:25，发布日期待定

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.000,0:00:01.840
今天赶横溪卖肉（赶集）

0:00:01.840,0:00:03.660
我的肉也没卖完

0:00:03.660,0:00:05.940
就出去转乡看斗别人有两个甲鱼

0:00:05.940,0:00:07.600
我说你的甲鱼怎么卖哦

0:00:07.600,0:00:10.760
那个卖甲鱼的就说我跟你换

0:00:10.760,0:00:14.220
我拿两个甲鱼给你换2两根猪脚杆

0:00:14.220,0:00:18.080
我说要得要得要得 我换回去整来试一下

0:00:20.155,0:00:21.320
安逸噶

0:00:21.320,0:00:22.060
可以

0:00:23.580,0:00:25.040
现在猪肉好多钱一斤哦

0:00:25.380,0:00:27.920
现在猪肉27-28块钱1斤

0:00:27.920,0:00:29.080
27-28块钱1斤

0:00:29.080,0:00:31.480
两根猪脚换两个甲鱼

0:00:31.795,0:00:32.680
划得来噶

0:00:32.680,0:00:37.720
是啊 两根猪脚我卖了两根卖了168块钱

0:00:37.780,0:00:39.780
这两个甲鱼就要值168

0:00:40.500,0:00:42.820
在市场上168块钱买得到不哦

0:00:43.160,0:00:44.580
差不多这个价

0:00:44.580,0:00:45.555
差不多啊

0:00:45.555,0:00:47.080
这样子我还是没吃亏撒

0:00:47.080,0:00:48.545
嘿嘿 可能你要亏一点

0:00:48.545,0:00:49.520
我要亏点啊

0:00:49.520,0:00:50.480
要亏点啊

0:00:50.480,0:00:52.580
亏点不多 不关事

0:00:52.580,0:00:54.700
我先烧水嘛 把它烫出来

0:00:54.820,0:00:56.520
烧来今晚上整来干（吃）了

0:00:56.520,0:00:57.940
要得 马上整嘛

0:00:58.000,0:00:59.540
要得要得 接都干

0:01:00.540,0:01:03.320
这个可能有两斤 你这个换的

0:01:03.760,0:01:05.640
我暗（猜）你是亏了丁点儿的

0:01:05.640,0:01:07.440
亏了不关事 管他的哦

0:01:07.440,0:01:11.000
反正整来尝哈味道嘛

0:01:11.000,0:01:12.440
这个甲鱼要摸它的尾巴

0:01:12.440,0:01:16.215
然后一刀把它的脑壳宰了来把血放了

0:01:16.220,0:01:17.760
要放血噶  嗯

0:01:19.960,0:01:22.260
这样宰了来放在这 等它慢慢放血

0:01:22.620,0:01:23.960
我看你咋个整

0:01:23.960,0:01:28.520
二天我还是又拿肉换了的话 我就照都这样整来干（吃）

0:01:29.160,0:01:31.020
那哈儿拿肉换你不得亏本

0:01:31.020,0:01:32.080
这哈儿换有点小亏

0:01:32.080,0:01:32.860
哎呀 不关事

0:01:32.860,0:01:34.780
我是不晓得这个单价都嘛

0:01:34.780,0:01:36.880
晓得这个单价噻我就不可能浪个子哦

0:01:36.880,0:01:38.480
我还喊他补点钱咯

0:01:40.220,0:01:41.500
干脆把它翻过来算了

0:01:41.500,0:01:42.800
翻过来它脑壳就要伸长

0:01:44.320,0:01:45.800
这个是个母的啊

0:01:45.800,0:01:48.380
翻过来之后它脑壳伸出来它想蹭（翻）过来

0:01:48.400,0:01:51.440
趁它蹭过来的时候 耶 你还缩

0:01:53.100,0:01:54.520
嘿嘿 它还缩

0:01:56.420,0:01:58.600
你翻它过来 翻它过来它又要伸出来

0:01:59.000,0:02:00.340
你倒了霉了

0:02:02.200,0:02:04.500
好 放着慢慢放血

0:02:04.620,0:02:06.600
我去挖瓢开水来

0:02:06.760,0:02:08.940
放了血之后拿这个开水跟它淋起下去

0:02:09.760,0:02:11.580
这个水也不要开得太凶

0:02:12.040,0:02:15.640
开了就行了嘛 嗯就是微微开那种

0:02:16.460,0:02:17.640
把它翻哈

0:02:18.620,0:02:21.340
那个皮子很容易就把它烫那种（脱）了

0:02:24.180,0:02:26.220
你就是烫的时候拿手跟它搓

0:02:28.180,0:02:30.940
跟猪儿皮面上那个薄膜一样

0:02:31.300,0:02:34.140
搓脱一层皮皮过后马上把它弄出来

0:02:34.620,0:02:36.020
这个不能泡太久

0:02:36.020,0:02:37.340
泡太久就不好整的

0:02:38.040,0:02:39.220
这哈子我来教你

0:02:40.340,0:02:41.260
给它搓

0:02:42.840,0:02:45.820
就跟烫猪脚杆那个皮子样

0:02:45.825,0:02:46.940
啊

0:02:46.940,0:02:48.940
但是没烫都你还不是搓不脱啊

0:02:50.160,0:02:52.720
这哈儿就烫都了撒 这皮子一哈就搓下来了

0:02:54.120,0:02:57.000
哎呀 这农村办席 哪个拿皮子给你整了

0:02:57.000,0:02:59.500
他还不是就浪个给你整来蒸起蒸起的

0:03:00.515,0:03:02.200
不好吃都嘛浪个子

0:03:02.200,0:03:06.140
是安 但是老百姓就懂不起撒

0:03:06.140,0:03:08.320
很多老百姓都懂不起撒 嗯

0:03:08.940,0:03:11.060
这个炒的甲鱼你吃过没有

0:03:11.420,0:03:12.280
没有

0:03:12.280,0:03:13.380
就是烧的

0:03:13.660,0:03:17.080
没有 只有蒸的我才吃过 我们办事

0:03:17.600,0:03:22.880
就是农村办宴席 生朝满日

0:03:22.900,0:03:25.880
打发（嫁）女啊  结婚啊这些整来吃过

0:03:25.880,0:03:28.835
这个甲鱼这个边边很好吃

0:03:28.835,0:03:29.915
那个裙边是不是哦

0:03:29.915,0:03:31.040
嗯 裙边

0:03:31.565,0:03:33.155
这个团鱼我跟你说嘛四伯爷

0:03:33.745,0:03:35.625
从中间弄个子开它

0:03:36.305,0:03:37.305
弄个子给它割开

0:03:37.865,0:03:39.280
就跟它包都车（转着切）

0:03:39.280,0:03:40.440
对 包都车（转着切）

0:03:47.000,0:03:49.620
我们做这个团鱼慢慢地从中间打开

0:03:51.180,0:03:52.680
一定不能着急

0:03:53.320,0:03:56.160
慢慢地给它打开了把内脏去除干净

0:03:58.740,0:04:00.660
白色的东西就是它的油

0:04:01.140,0:04:03.900
这个肝跟肺还有胆

0:04:03.900,0:04:05.700
肝子吃不得嘛吃得哦

0:04:06.500,0:04:09.500
肝子 内脏肠肠之类的就不要噻

0:04:13.160,0:04:14.380
这个里头都有蛋了

0:04:17.060,0:04:18.340
看 就是弄个子的

0:04:19.720,0:04:22.800
你这除了壳壳都没得啥子弄的了

0:04:23.365,0:04:24.365
是安

0:04:26.340,0:04:29.240
还是猪脚杆安逸点噶 猪脚杆肉多

0:04:29.240,0:04:31.720
老子二回不弄个子跟它换了 干不得

0:04:34.020,0:04:38.040
我们一般吃甲鱼要先把这个爪子给它去掉

0:04:39.960,0:04:47.460
在酒店里面做的话这个一般不会说用那个胆来给它腌一下

0:04:47.460,0:04:48.920
但是自己吃可以搞一下

0:04:50.360,0:04:56.340
这个甲鱼的苦胆可以放进去腌这个肉 去腥的

0:05:07.960,0:05:10.320
我拿火锅底料来烧哦 四伯爷

0:05:10.320,0:05:14.160
要得 反正你说啥子整起好干点就拿啥子整

0:05:15.400,0:05:19.520
好 我放了点火锅底料加点这个大蒜辣椒姜

0:05:19.740,0:05:21.480
然后弄点蒜苗一起来烧

0:05:21.480,0:05:22.460
要得啊

0:05:23.540,0:05:24.820
一块小点的姜就够了

0:05:41.280,0:05:42.800
要整点泡海椒来呀

0:05:43.400,0:05:44.560
你泡的都嘛

0:05:45.820,0:05:46.940
在你的罐罐头抓的

0:05:46.940,0:05:48.220
那里面生花没有

0:05:48.220,0:05:50.540
没有 生花了你放点酒进去就是

0:05:52.160,0:05:53.820
坛沿水还有没得安那里头

0:05:54.780,0:05:56.540
坛沿水啊 有

0:05:57.060,0:05:59.500
就是要注意坛沿水不要它干

0:05:59.500,0:06:02.080
一干了就着 干了里头就要坏 嗯

0:06:10.580,0:06:12.000
烧的拍不拍都可以

0:06:13.060,0:06:16.320
这个杆杆儿跟叶叶儿分开放

0:06:17.480,0:06:20.420
杆杆儿就先下（锅）叶叶儿就后下

0:06:24.040,0:06:26.880
差不多了 四伯爷你烧火嘛我来炒

0:06:27.420,0:06:28.300
要得啊

0:06:28.985,0:06:29.985
来嘛

0:06:30.745,0:06:32.280
多放点你的菜油哦四伯爷

0:06:32.280,0:06:33.240
要得

0:06:34.980,0:06:37.460
老子亏本钱哦放多很了

0:06:38.600,0:06:40.320
你说来我撤了一哈

0:06:40.380,0:06:42.980
本来想放半斤的都只放了四两

0:06:48.080,0:06:51.640
这个不多撒 这里只有可能一两多点油

0:06:51.640,0:06:53.740
一两多点 二两嘛

0:06:54.720,0:06:56.760
可能三两油都有

0:06:57.340,0:06:59.840
你以为二三两好多点

0:07:01.100,0:07:02.100
要得了

0:07:17.820,0:07:19.460
好 甲鱼爆香了

0:07:22.560,0:07:24.080
诶 你不放点盐在里面啊

0:07:24.240,0:07:29.120
放盐 这里面放火锅底料跟这个姜蒜辣椒啊那些

0:07:29.120,0:07:30.540
慢慢给它煸香了多

0:07:30.560,0:07:33.360
煸香了再加啤酒下去煮

0:07:40.460,0:07:42.960
伯娘你看 你看嘛

0:07:43.040,0:07:44.240
肯定好吃撒

0:07:45.740,0:07:47.160
这是啥子嘛 乌龟是不是哦

0:07:47.660,0:07:49.580
团鱼  哦是团鱼

0:08:00.680,0:08:02.000
炒香了哦四伯爷

0:08:02.000,0:08:02.880
嘿 安逸

0:08:03.380,0:08:04.600
放一瓶哦

0:08:12.960,0:08:15.400
这东西拿来烧魔芋害怕安逸哦噶

0:08:15.400,0:08:17.600
可以按 魔芋烧起好吃安

0:08:17.600,0:08:19.620
魔芋烧鸭子也好吃该是哈  嗯

0:08:20.440,0:08:22.020
就弄个子烧起都很好吃了

0:08:24.080,0:08:27.460
只是说你们平时整不来嘛

0:08:27.460,0:08:29.540
没得哪个整这些来干的

0:08:29.860,0:08:32.180
这哈子我在屋头没事就整给你们吃

0:08:32.460,0:08:33.040
要得啊

0:08:33.040,0:08:36.060
总整些你们这辈子没吃过的东西给你们吃

0:08:36.060,0:08:40.180
没享受过的嘛你都整点让我享受哈嘛嘿嘿  好

0:08:45.220,0:08:49.280
其实我们在家里面烧这个团鱼 不用去勾芡

0:08:49.280,0:08:52.960
它这个慢慢收 慢慢收汤汁会收浓的

0:08:56.580,0:08:59.060
差不多我放盐巴了四伯爷 要得

0:08:59.280,0:09:01.340
不要整咸了哈

0:09:01.340,0:09:02.180
开玩笑

0:09:02.180,0:09:03.460
省都省都得放

0:09:04.640,0:09:06.760
放点盐 然后再放点白糖

0:09:07.580,0:09:08.960
再放点胡椒粉

0:09:11.080,0:09:12.820
还有最重要的是放点酱油

0:09:22.760,0:09:24.880
非常不错这个 特别香

0:09:25.935,0:09:27.695
现在这个汁水有点浓了

0:09:28.415,0:09:31.745
四伯爷这哈你看 这汤汁都黏了

0:09:32.620,0:09:33.700
慢慢在黏了

0:09:35.160,0:09:37.740
这汤汤儿整来跟它放了豆粉的样噶

0:09:39.340,0:09:42.120
它这个不是的豆粉 是这个鱼的胶质

0:09:43.055,0:09:44.105
鱼胶

0:09:45.775,0:09:48.645
一般到了这个时候我们就放辣椒跟这个蒜头

0:09:49.305,0:09:50.495
然后给它炒匀

0:09:59.140,0:10:01.400
这个蒜苗一断生我们就把它铲起来

0:10:01.400,0:10:02.560
好 端过来点

0:10:13.920,0:10:15.160
这个菜我们就炒完了

0:10:15.160,0:10:18.480
这个菜其实最麻烦的就是宰杀这一步

0:10:18.880,0:10:21.120
宰杀这一步交给摊主来处理很快的

0:10:21.120,0:10:24.260
然后我们就剁好 剁好放点调料去烧

0:10:24.260,0:10:30.960
烧一下 放点辣椒啊放点火锅底料啊姜蒜啊这些特别香

0:10:31.400,0:10:34.100
不用烧太久 味道都好得很

0:10:34.580,0:10:36.760
走 我们端过去吃哈看

0:10:37.560,0:10:41.660
我们这个团鱼它边上那层胶质的东西特别软

0:10:41.660,0:10:45.400
吃起来还会有一点粘牙 特别好吃

0:10:46.600,0:10:48.000
嗯 糍妥糍妥的

0:10:48.000,0:10:50.880
比较适合那种牙口不好的

0:10:50.880,0:10:53.680
嗯 看都就跟它很绵一样

0:10:54.280,0:10:56.520
吃起糍妥糍妥的还安逸

0:10:57.960,0:10:58.980
吃这个伯娘

0:10:59.560,0:11:00.700
你吃嘛你吃

0:11:04.280,0:11:06.440
嗯可以这东西

0:11:09.520,0:11:11.220
好了本期视频就到这里吧

0:11:11.500,0:11:13.460
我们要继续吃饭

0:11:13.740,0:11:15.520
这个甲鱼说真的特别好吃

0:11:16.680,0:11:19.960
我伯爷都给出了很高度的评价

0:11:20.335,0:11:22.205
大家可以去试一下

**Comment by immoonancient** [comment]
已上传，发布日期待定

**Comment by immoonancient** [comment]
已发布
