### ISSUE TITLE
【美食作家王刚】四伯帮人杀年猪 - https://youtu.be/qclrONlUInA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#569]
【美食作家王刚】四伯帮人杀年猪 - https://youtu.be/qclrONlUInA
视频时长 5:06，预计发布时间为北京时间1月11日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.000,0:00:00.880
四伯爷

0:00:00.880,0:00:01.600
嗯

0:00:01.600,0:00:03.580
去帮别人杀过年猪啊

0:00:03.580,0:00:05.340
嗯今年子生意不好

0:00:06.800,0:00:09.020
人们觉得猪肉贵舍不得杀来吃

0:00:09.140,0:00:11.380
杀一头猪来吃就是大几千

0:00:11.380,0:00:12.960
现在你杀一头（过年）猪收好多钱安？

0:00:13.160,0:00:15.160
一般是一百六七（一百六七十元）

0:00:15.420,0:00:19.300
今年才杀了10来个猪儿

0:00:19.360,0:00:21.660
往年到现在起码都杀了几十个了

0:00:21.660,0:00:23.200
我跟你一路去杀

0:00:23.200,0:00:24.520
要的要的 好嘛好嘛

0:04:14.760,0:04:16.760
翻完肚子和肠子就可以走了

0:04:36.840,0:04:38.620
四伯爷收拾东西准备撤了吧？

0:04:38.620,0:04:39.240
嗯

0:04:40.060,0:04:42.200
叫你午饭吃了再走你又（着急走）

0:04:42.200,0:04:43.020
不用管我

0:04:43.700,0:04:45.440
叫你午饭吃了再走你又（着急走）

0:04:45.640,0:04:47.840
没得事二回来干嘛（下次来吃）

0:04:47.840,0:04:48.900
二回

0:04:49.260,0:04:51.260
总有一天能吃到你的（饭）

0:04:51.260,0:04:52.440
以后结（儿）媳妇记得给我说一声

0:04:52.440,0:04:53.180
要得

0:04:53.180,0:04:54.800
你要拿给我干啥（记得请我）

0:04:54.800,0:04:56.660
我要拿给你干（会请你的）

0:04:56.720,0:05:00.600
喊你在这里吃午饭你着急回去 你家吃的更好点

0:05:02.440,0:05:04.580
洗下手 洗下手

**Comment by Losskywalker** [comment]
认领

**Comment by Losskywalker** [comment]
bot, please upload

【美食作家王刚】四伯帮人杀年猪 - https://youtu.be/qclrONlUInA
Title: Uncle help friends slaughter a pig for the new year 
视频时长 5:06，预计发布时间为北京时间1月11日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.000,0:00:00.880
四伯爷
Uncle

0:00:00.880,0:00:01.600
嗯
Yeah?

0:00:01.600,0:00:03.580
去帮别人杀过年猪啊
Are you going to help others slaughter a pig?

0:00:03.580,0:00:05.340
嗯今年子生意不好
Yeah, business was not good last year

0:00:06.800,0:00:09.020
人们觉得猪肉贵舍不得杀来吃
Pork price was so high that owners don't want to slaughter pigs for themselves.

0:00:09.140,0:00:11.380
杀一头猪来吃就是大几千
A pig is worth thousands of RMB.

0:00:11.380,0:00:12.960
现在你杀一头（过年）猪收好多钱安？
How much do you charge for slaughting (during the new year)?

0:00:13.160,0:00:15.160
一般是一百六七（一百六七十元）
Around 160 RMB.

0:00:15.420,0:00:19.300
今年才杀了10来个猪儿
I only slaughtered around 10 pigs so far.

0:00:19.360,0:00:21.660
往年到现在起码都杀了几十个了
In previous years it would have been already dozens

0:00:21.660,0:00:23.200
我跟你一路去杀
I wil join you

0:00:23.200,0:00:24.520
要的要的 好嘛好嘛
Sure that would be nice

0:04:14.760,0:04:16.760
翻完肚子和肠子就可以走了
We just need to clean the stomach and intestines inside-out and we are done

0:04:36.840,0:04:38.620
四伯爷收拾东西准备撤了吧？
Uncle, are you packing up to leave?
0:04:38.620,0:04:39.240
嗯
Yes
0:04:40.060,0:04:42.200
叫你午饭吃了再走你又（着急走）
I told you to stay for lunch, there's no rush.

0:04:42.200,0:04:43.020
不用管我
Don't worry
0:04:43.700,0:04:45.440
叫你午饭吃了再走你又（着急走）
I told you to stay for lunch, there's no rush.(这一句是重复么？)
0:04:45.640,0:04:47.840
没得事二回来干嘛（下次来吃）
Don't worry I will come back for that (next time)
0:04:47.840,0:04:48.900
二回
Next time
0:04:49.260,0:04:51.260
总有一天能吃到你的（饭）
Someday, I will eat at your place
0:04:51.260,0:04:52.440
以后结（儿）媳妇记得给我说一声
Let me know when your son is getting married!
0:04:52.440,0:04:53.180
要得
Sure!
0:04:53.180,0:04:54.800
你要拿给我干啥（记得请我）
You remember to invite me!
0:04:54.800,0:04:56.660
我要拿给你干（会请你的）
I will, I will invite you
0:04:56.720,0:05:00.600
喊你在这里吃午饭你着急回去 你家吃的更好点
Told you to stay for lunch, you still want to go home to eat. You have better food at home.
0:05:02.440,0:05:04.580
洗下手 洗下手
I need to clean my hands.
