### ISSUE TITLE
【美食作家王刚】盐焗海鲜 - https://youtu.be/cW5bl2yVJ4U

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#57]
【美食作家王刚】盐焗海鲜 - https://youtu.be/cW5bl2yVJ4U 
这是刚哥最新的视频私享链接，方便大家提前添加字幕，做菜过程文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。然后就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间8月17日晚6点
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
@lolololol0122 @sbsbpk 

首先我们准备鲜活的鲍鱼6个
First of all, let's prepare 6 fresh and alive abalones

准备适量的海螺
some sea snails 

准备适量的蛏子
and some clams 

其实现在很多县城都有海鲜卖
Nowadays seafood is sold in many towns

得到优质的海鲜原材料并不难
So it's not that hard to acquire quality seafood

最后再加入适量的鲜虾
Finally, add some fresh shrimps in

没有海鲜的同学也可以用河鲜
Seafood from both ocean and freshwater can be used to cook this dish

比如河虾螃蟹之类
Such as freshwater shrimps and crabs.

下一步我开始处理
Next up, prepare the seafood

首先在鲍鱼下方用利器划开去除内脏清洗干净
cut open the bottom of abalones and take out the guts, rinse out any residual on it

嫌麻烦处理的同学可以将鲍鱼交给摊主处理
If you guys feel bothered, just ask the fishmonger to do that for you

同时蛏子也是用剪刀将其剪开
likewish, use scissors to cut the clams open 

然后将内脏肠子挤掉备用
squeeze out the guts and set the clams aside

再将大虾的虾线去掉即可
then take the guts out of the shrimps

海螺不用特殊处理只需要将其表面清洗干净
as for sea snails, just rinse out the surface

在鲍鱼表面切上十字花刀
nicking diamond shapes on the abalone with a knife 

其实新鲜的鲍鱼并不贵
In fact, fresh abalones are not that pricy

视频中的鲍鱼在四川售价只需要8块钱一个
abalones shown in this video only cost 8 yuan for each

价格也比较亲民基本上可以接受
the price is fairly reasonable

最后将所有材料清洗几遍
Lastly, rinse all ingredients a few more time

下一步我们来开始处理
Next up, prepare the seasoning

首先我们准备柠檬1个对半切开
take a lemon and cut it in half

柠檬切开之后将汁水挤出
squeeze out the juice 

同学们其实柠檬不仅可以让去除海鲜的腥味
Not only can the juice remove the fishy smell on seafood

而且还能增加海鲜的保质期
but also help to preserve seafood as well

再准备生姜1小块切成薄片
thinly slice a small block of ginger 

然后搅拌均匀腌制10分钟备用
mix it up and marinate for 10 mins 

下一步开始制作
Next up, start cooking 

首先我们在锅中加入“宽盐”
pour "Kuan Yan" (Lots of salt) into the wok

大概需要6斤左右即可
Roughly 3kg is enough

可同学们可以也根据锅的大小而定
Feel free to adjust the amount base on the size of your wok

这个“宽盐”可以反复使用所以并不会造成浪费
These salt can be used many times so it won't be wasted 

食用盐下锅之后加热翻炒几下
heat up the wok and stir up the salt

中途的时候再加入适量的红花椒下锅一起翻炒
add some sichuan peppercorns halfway through 

刚哥你加这么多盐巴不鹹吗
Bro, won't it be salty that you add that much salt.

不得鹹
Nope, it won't.

为啥子啊
Why?

等下你吃了你就知道咸不咸了
You'll see after you try the dish.

嘿嘿好嘛
Haha, fine.

正如这位同学提问：
As this mate asked

一般来说只要是海鲜带壳的食材都可以下锅盐焗
Normally, any seafood with shell can be Yanju (salt baked) like this

而且成菜之后不咸不淡味道刚刚好
and the saltiness is just about right

再将食用盐翻炒加热至略带黄色
heat up and stir the salt until it's lightly yellow

食用盐炒香之后将所有的海鲜肉朝上依次放入锅中
After bringing out the fragrance, lay down all the seafood with meat side up

再将切好的柠檬片放在上面盖上锅盖小火焗15分钟
cover the seafood with lemon slices, then put on the lid and let it bake for 15 min on low heat

盐焗的时间需要根据食材的大小来灵活运用
Adjust the baking time based on the amount and size of ingrediants.

但是同学们切记焗的过程中需要全程开微小火
Bare in mind that the baking process has to be on low heat the whole time

这样才能达到干香入味的境界
only by this can you achieve the perfect dryness and fragrance level

15分钟之后即可捞出食用
15 minutes later, it can be served 

下面开始技术总结
Technical summaries are as follows

第一，此菜处理食用盐和柠檬姜片之外不需要其它调料
Firstly,  no other seasoning is needed besides salt, lemons and gingers.

第二，原料下锅之前必须先把花椒和盐炒烫炒香
Secondly, the fragrance of Sichuan peppercorns and salt must be brought out before placing down the ingrediants. 

第三，“焗”的时候必须全程小火否则容易有焦味
Thirdly, heat must be maintained on low throughout the baking process otherwise it may result in a burnt taste 

好了下面开始试吃总结
Alright, let's start the tasting summary

我們這個蝦殼呢一般焗好之後都是脆的
The shells of the shrimps should be crunchy after being 'Yanju'.

但是這個有個缺點
But there's a con tho -

就是涼了之後味道就沒那麼好了
that it may not taste that good when it's cooled down.

這個蝦肉裡面有一點點水分但是不是特別多
There's still a tiny bit of juice left in the shrimps

吃起來特別香 很入味
which makes it tasty.

不會像大家想像的沒有鹽
It's not that insipid

或者說非常鹹
or salty as people think.

它恰好不會這樣
The flavour is well-balanced. 

吃起來這個肉就有一點點嚼勁
The shrimps are quite chewy,

主要是非常鮮
and taste fresh.

再吃一個蛏子
Let's try the clam.

說實在話這個蛏子裡面 可能會有一點沙
Honestly, there might be sand left in the clams.

然後這個肉也沒有蝦的那麼好吃
And it's not as tatsty as the shrimps.

我嚐一個鮑魚
Let's give the abalone a taste.

像這麼大的鮑魚
 Abalones in this size

一般在市場裡面的話10塊錢左右
cost around 10 yuan on the market normally.

現在的鮑魚非常便宜
Abalones are pretty low-prized.
 
嗯
Um...

鮑魚的話在口感上面要比這個蛏子要好一點
The abalone is more tasty than the clam 

因為它這個肉比較厚
since abalones are somehow thicker,

因為那個蛏子比較薄
and clams are flimsy.

一起焗十分鐘之後呢這個蛏子有點發乾
So the clams may turn out a bit dry after 10minutes of Yanju,

但這個不會 這個吃起來很有韌勁
but not for the abalone, it's still chewy,

水分也非常夠
and juicy enough.

而且它裡面會有油
Plus, there's oil in it,

這個菜是沒有放油的 但它裡面會有油
even if we haven't add any oil in the dish.

吃起來很香
It tastes really good.

這裡面有個小竅門
There's a trick-

就是一定要把食材裡面的水分焗乾
Make sure that the moisture in the seafood is dried thoroughly. 

如果焗不乾的話
Otherwise, 

出完鍋之後那個鹽 一但遇到這個湯汁之後它就變鹹了
once the salt is mixed with the juice of the seafood,

就非常鹹
it will taste extremely salty

如果你焗乾了之後
Once you 'Yanju' till the seafood is dry enough,

就像這樣
It will be like this.

非常有味道而且不鹹
The flavor is rich but it's not greasy.

很香
It smells really good.

然後檸檬汁的話可以盡量多放一點
Actually you can add as much lemon juice as you can.

非常好吃
Delicious!

大家可以聽一下這個聲音
Listen!

已經是焦脆焦脆的
It's very crispy already 

聽到了嗎
Can you hear this?

好了 本期視頻就到這裡了
Okay, that's all for this video.

剩下的我們就慢慢吃
We'll finish the rest.

掰掰
See you.

**Comment by lolololol0122** [comment]
我做這個👆🏻🙊

**Comment by immoonancient** [comment]
Published already.
