### ISSUE TITLE
【美食作家王刚】扣肘子 - https://youtu.be/5WgprEIZFzU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#570]
【美食作家王刚】扣肘子 - https://youtu.be/5WgprEIZFzU
视频时长 6:35，预计发布时间为北京时间1月12日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.065,0:00:01.300
哈喽大家好 我是王刚

0:00:01.300,0:00:03.240
本期视频我给大家分享一道年菜

0:00:03.360,0:00:04.420
扣肘子

0:00:04.840,0:00:06.640
首先我们准备猪前肘2个（每个约1000克）

0:00:06.800,0:00:09.520
将肘子的皮烧至焦黑后再用温水清洗干净

0:00:10.000,0:00:13.280
同学们这一步的目的是破坏猪皮的汗腺去除腥味

0:00:13.280,0:00:16.420
也可以清洗干净之后再次烧黑再次清洗

0:00:16.420,0:00:19.020
二次处理可以更大限度的减少皮腥味

0:00:34.740,0:00:36.900
清洗干净之后开始准备辅料

0:00:37.320,0:00:39.220
准备生姜和大葱各50克

0:00:39.420,0:00:41.340
分别切成片和长段备用

0:00:49.260,0:00:51.380
碗中加入去籽草果2颗

0:00:51.620,0:00:53.080
加入橘子皮1小块

0:00:53.080,0:00:54.300
加入八角2颗

0:00:54.520,0:00:55.960
加入桂皮1小块

0:00:56.440,0:00:57.880
加入香叶2片

0:00:58.260,0:00:59.700
加入小茴香1小把（约10克）

0:01:00.600,0:01:01.960
加入几颗三奈

0:01:01.960,0:01:03.215
下一步开始初加工

0:01:03.220,0:01:05.600
首先我们在锅中加入大半锅清水

0:01:07.740,0:01:09.780
然后将肘子冷水下锅焯水

0:01:17.745,0:01:19.365
中途再加入少许料酒

0:01:22.540,0:01:24.700
水开10分钟之后将肘子捞出

0:01:26.040,0:01:27.720
下一步开始准备卤制

0:01:27.900,0:01:29.740
锅中加入植物油1大勺

0:01:32.625,0:01:35.595
油温4成热之后将准备好的料头和香辣下锅

0:01:38.585,0:01:40.585
然后开小火翻炒5分钟

0:01:47.925,0:01:50.105
中途加入1小把青花椒和干辣椒

0:01:57.525,0:01:59.985
所有辅料炒香之后加入一大锅清水

0:02:03.460,0:02:05.500
然后将焯水的肘子下锅

0:02:05.500,0:02:07.800
清水的量能没过肘子2厘米即可

0:02:08.900,0:02:10.780
下一步开始调色和调味

0:02:11.135,0:02:12.575
锅中加入糖色30克

0:02:12.975,0:02:15.155
没有糖色的同学可以用老抽代替

0:02:21.020,0:02:22.640
加入生抽酱油50克

0:02:29.960,0:02:31.300
加入冰糖1小块（约20克）

0:02:33.120,0:02:34.660
加入食用盐5大勺（约22克）

0:02:41.180,0:02:42.660
加入胡椒粉2大勺（约3克）

0:02:44.960,0:02:46.960
然后转小火卤制90分钟

0:02:46.960,0:02:49.780
这一步的目的是将肘子初步卤香入底味

0:02:53.760,0:02:55.920
90分钟之后将肘子捞出备用

0:03:07.180,0:03:08.720
然后再次把锅烧热

0:03:08.720,0:03:10.240
锅烧热之后加入宽油

0:03:17.700,0:03:20.200
油温5成热之后将肘子下锅炸6分钟

0:03:20.200,0:03:23.020
这一步的目的是减少肘子皮下的油脂和增香

0:03:23.040,0:03:25.320
喜欢肥一些的同学可以忽略这一步

0:03:33.080,0:03:34.600
6分钟之后将肘子捞出

0:03:38.640,0:03:39.880
下一步开始拆肘子

0:03:40.740,0:03:43.440
首先将肘子切开之后取下中间的骨头

0:03:43.440,0:03:47.100
同学们也可以待其凉透之后再操作以防烫手

0:03:50.340,0:03:52.480
然后将肘子的皮和肉分离下来

0:04:02.980,0:04:05.340
皮肉分离之后在内侧切上花刀

0:04:05.340,0:04:07.720
切花刀的目的是方便用筷子夹开

0:04:10.000,0:04:12.440
然后将肘子皮朝下垫在碗底

0:04:23.980,0:04:26.100
垫好之后将肘子的肉切成片

0:04:29.740,0:04:31.980
切好之后整齐的码放在碗中

0:04:34.660,0:04:36.280
下一步开始调汁

0:04:36.600,0:04:38.760
碗中加入卤肘子的原汁大半碗

0:04:41.340,0:04:42.720
加入适量的食用盐

0:04:43.080,0:04:44.600
加入胡椒粉少许

0:04:47.620,0:04:49.960
将调好的汁倒入碗中

0:04:56.040,0:04:57.940
碗中加入适量的生姜片

0:04:58.565,0:05:00.245
加入几颗花椒

0:05:00.920,0:05:02.360
加入八角1颗

0:05:02.900,0:05:04.420
加入干辣椒3个

0:05:07.260,0:05:08.800
然后放入蒸锅中

0:05:10.900,0:05:12.640
加入小葱1根增香

0:05:20.120,0:05:22.560
大火烧开之后转中小火蒸2个小时

0:05:24.680,0:05:27.360
2个小时之后将肘子取出倒出汁水

0:05:32.080,0:05:34.140
然后把肘子倒扣在碗里面

0:05:39.980,0:05:41.780
下一步开始准备淋汁

0:05:42.240,0:05:44.900
将倒出的汁水放入锅中烧开

0:05:52.180,0:05:55.120
烧开之后加入适量的水淀粉把汤汁收浓

0:05:55.840,0:05:58.160
同学们注意收汁的时候必须锅离火

0:05:58.160,0:05:59.660
否则汤汁收不紧

0:06:03.985,0:06:06.405
汤汁收浓之后加入少许明油

0:06:08.300,0:06:10.640
最后均匀的淋在肘子上面即可上菜

0:06:15.540,0:06:17.780
一道非常美味的扣肘子就制作完成

0:06:20.520,0:06:22.000
下面开始技术总结

0:06:22.000,0:06:25.900
第一，肘子最好选择大一些的，这样成菜更加饱满

0:06:25.900,0:06:29.240
第二，不方便宽油炸的同学可以忽略这一步

0:06:29.240,0:06:32.340
第三，蒸制的时间越长口感约软嫩

0:06:32.340,0:06:33.920
扣肘子的技术总结完毕

**Comment by Yibing-Du** [comment]
Hi! Would love to be assigned to translate this one. Thanks!
