### ISSUE TITLE
【雪鱼】顺德生滚粥https://www.youtube.com/watch?v=hu5onHi9iAY&t=30s

### ISSUE THREAD

**Issue by shuaisoserious** [immoonancient/YTSubtitles#573]

**Comment by okiamnewhere** [comment]
标题：顺德豪华早餐粥，2碗43元有牛肉、鱼片、猪杂+午餐39元的蝎子炖汤
简介：我是雪鱼，带你一起踏上寻味之旅。这几天我来到广东省佛山市顺德区，虽然它地方小，但是却藏着很多美味小吃，并吸引了全球顾客来此地开启寻味之旅。今天早餐选择了生滚粥，10几盆的肉随便加，在热粥里滚数，鲜美无比！鱼片、牛肉片最招顾客喜欢。中午吃了蝎子炖汤，看着一个个的蝎子长的那么吓人，我也勇敢的吃了下去，非常不一样的心智体验。
字幕：
1
00:00:01,920 --> 00:00:06,400
佛山·顺德

2
00:00:08,800 --> 00:00:11,120
现在天刚是有点蒙蒙亮

3
00:00:11,120 --> 00:00:12,680
天气还是有点小冷

4
00:00:12,680 --> 00:00:15,120
起这么早就是为了喝一碗粥

5
00:00:15,120 --> 00:00:17,040
这个粥到底有什么特别的呢

6
00:00:17,040 --> 00:00:19,720
它就是人称 粥中爱马仕的

7
00:00:19,720 --> 00:00:21,880
顺德生滚粥

8
00:00:21,880 --> 00:00:24,560
听名字 是不是觉得有点奇特呢

9
00:00:24,560 --> 00:00:26,360
去看看吧

10
00:00:46,240 --> 00:00:48,320
你好
坐吧

11
00:00:48,320 --> 00:00:50,160
不用点单吗

12
00:00:50,160 --> 00:00:52,360
不用写 你看吃什么粥就行

13
00:00:52,360 --> 00:00:55,000
哦哦，这里看吃什么粥就可以

14
00:00:56,880 --> 00:00:59,640
内心话：老板 你确定是问我 要吃什么粥吗

15
00:00:59,640 --> 00:01:02,560
不应该问：来 看你想吃什么肉

16
00:01:02,800 --> 00:01:06,160
这一盆盆摆的鸡肉 牛肉 鱼肉 猪肉

17
00:01:06,160 --> 00:01:07,400
应有尽有

18
00:01:10,200 --> 00:01:13,120
到底应该吃哪一种呢

19
00:01:23,560 --> 00:01:25,440
点这个
知道吃什么了

20
00:01:27,360 --> 00:01:31,920
大哥 我要一个猪杂肉丸的

21
00:01:31,920 --> 00:01:34,600
对 再要一个牛肉鱼片的

22
00:01:34,600 --> 00:01:35,920
对

23
00:01:37,720 --> 00:01:39,360
多少钱

24
00:01:41,840 --> 00:01:44,840
2碗一共43块钱

25
00:01:46,680 --> 00:01:49,840
哇 这么多的肉

26
00:02:46,440 --> 00:02:50,000
哇
碗好大啊

27
00:03:09,080 --> 00:03:10,080
谢谢

28
00:03:10,080 --> 00:03:11,400
别动 别动 烫

29
00:03:11,400 --> 00:03:13,920
那里有小碗 自己去拿一下 消毒柜那里

30
00:03:13,920 --> 00:03:15,320
可以 可以

31
00:03:26,840 --> 00:03:29,800
这就是咱们要的两碗生滚粥

32
00:03:29,800 --> 00:03:36,480
这个呢 就是加了鱼片和牛肉  这个是猪杂和肉丸

33
00:03:36,480 --> 00:03:38,960
一共是43块钱

34
00:03:41,800 --> 00:03:44,680
我喝粥从来没有用过这么大的碗

35
00:03:44,680 --> 00:03:47,120
大到什么程度呢 就是这个勺

36
00:03:47,120 --> 00:03:51,600
我放进碗里 它时不时地会自己滑落到里面

37
00:03:51,600 --> 00:03:53,120
被粥淹没

38
00:03:53,120 --> 00:03:56,760
这好像不是碗是用盆装的生滚粥

39
00:03:56,760 --> 00:03:59,480
我告诉大家 我本来还想再加点油条

40
00:03:59,480 --> 00:04:00,680
再加点别的

41
00:04:00,680 --> 00:04:03,240
后来上来这一碗 直接什么都不要了

42
00:04:03,240 --> 00:04:06,520
今天早上就干了这一碗粥就足够了

43
00:04:06,520 --> 00:04:09,800
不过这一碗也不一定能够喝得了

44
00:04:13,560 --> 00:04:17,160
生滚粥 你看 米快被熬化了

45
00:04:17,160 --> 00:04:20,800
米 几乎没有一粒是完整的

46
00:04:20,800 --> 00:04:25,800
粥喝起来就是香糯 咸中带些甘甜

47
00:04:25,800 --> 00:04:28,360
肉是提前腌制过的 所以吃起来

48
00:04:28,360 --> 00:04:30,920
不是索然无味的

49
00:04:36,000 --> 00:04:38,360
（店）它这边的招牌是猪杂生滚粥

50
00:04:38,360 --> 00:04:41,080
但是一些人吃不惯怎么办

51
00:04:41,080 --> 00:04:44,480
这一碟的姜丝酱油 可供解腥

52
00:04:44,480 --> 00:04:47,880
本来以为20多块钱一碗粥 会很贵

53
00:04:47,880 --> 00:04:49,840
但是这个料真的很多

54
00:04:49,840 --> 00:04:55,040
多到你每舀一勺 都会感觉这个肉 这个料沉甸甸的

55
00:04:55,040 --> 00:04:57,240
多到吃不完

56
00:04:57,720 --> 00:05:01,040
这几天吃饭都是用的这种大圆桌

57
00:05:01,040 --> 00:05:02,920
就是谁到谁先坐

58
00:05:02,920 --> 00:05:03,800
来晚的呢

59
00:05:03,800 --> 00:05:07,320
可以随眼缘拼桌

60
00:05:07,320 --> 00:05:08,680
咱们是来的比较早

61
00:05:08,680 --> 00:05:10,760
一些老人家早早来吃早饭

62
00:05:10,760 --> 00:05:12,840
他们在吃生滚粥的时候

63
00:05:12,840 --> 00:05:14,920
还会用白酒来配

64
00:05:14,920 --> 00:05:17,280
这个店是一对兄妹开的

65
00:05:17,280 --> 00:05:20,080
做的是街坊邻居的生意

66
00:05:20,240 --> 00:05:23,440
很多老人就直接把自己的酒瓶放在这边

67
00:05:23,440 --> 00:05:25,840
早上起来呢 就是喝粥配白酒

68
00:05:50,560 --> 00:05:54,000
今天是这几天在顺德最冷的一天了

69
00:05:54,000 --> 00:05:56,440
喝碗粥暖和暖和

70
00:05:56,440 --> 00:05:58,360
你看 大早上起来我是这样

71
00:05:58,360 --> 00:06:01,120
等到中午我就是另外一个面貌了

72
00:06:01,200 --> 00:06:03,560
知道为什么这么冷吗 因为有风

73
00:06:03,560 --> 00:06:07,200
如果说 没有风的话 应该会暖和很多

74
00:06:35,920 --> 00:06:37,720
关 注
雪 鱼 探 店

75
00:06:38,120 --> 00:06:42,120
一直以来 我们吃的东西都是平淡无奇的

76
00:06:42,520 --> 00:06:44,520
像猪肉牛肉羊肉这样的荤菜

77
00:06:45,220 --> 00:06:47,220
还有面 粉这样的主食

78
00:06:47,480 --> 00:06:49,480
继去年来广州吃到蛇

79
00:06:49,680 --> 00:06:50,900
这次我们来顺德

80
00:06:51,020 --> 00:06:54,480
来挑战一个不一样的美食品种 吃蝎子

81
00:06:54,480 --> 00:06:56,400
听起来感觉有点恶毒的蝎子

82
00:06:56,400 --> 00:06:58,080
把它炖着吃

83
00:06:58,240 --> 00:07:00,240
是不是还比较有意思呢

84
00:07:01,440 --> 00:07:03,440
来 走吧

85
00:07:07,420 --> 00:07:09,420
你好 开始营业了吗

86
00:07:09,420 --> 00:07:11,240
可以了 哦

87
00:07:11,420 --> 00:07:13,420
进来坐吧 开门了 今天提前了5分钟开门

88
00:07:14,860 --> 00:07:16,860
因为是周六周日的原因吗

89
00:07:17,360 --> 00:07:19,360
很少提前开门  一直都是标准时间开门

90
00:07:19,740 --> 00:07:21,740
今天心情特别好 知道你们来了

91
00:07:21,920 --> 00:07:23,920
所以 提前开门了

92
00:07:23,920 --> 00:07:24,720
哈哈

93
00:07:25,060 --> 00:07:27,060
坐吧 随便做吧

94
00:07:30,440 --> 00:07:32,440
平常排队都需要排队到12点

95
00:07:37,620 --> 00:07:39,620
老板这边卖的最多的是什么呀

96
00:07:39,620 --> 00:07:43,640
党参乌鸡蝎子汤 30多年来最受欢迎的

97
00:07:52,820 --> 00:07:54,820
每天70%的客人都喝这个汤

98
00:07:55,960 --> 00:07:57,960
小心 这个碗很烫的 刚刚消完毒

99
00:07:57,960 --> 00:07:59,280
谢谢

100
00:08:09,460 --> 00:08:11,460
你稍等 坐在那里点就可以了

101
00:08:11,460 --> 00:08:13,300
我可以听到你说话

102
00:08:13,780 --> 00:08:15,780
好的 我要一个党参乌鸡炖蝎子

103
00:08:16,380 --> 00:08:18,380
然后 还有一个松茸炖乌鸡

104
00:08:21,220 --> 00:08:23,220
再加一个煎蛋 一份米饭

105
00:08:23,600 --> 00:08:25,600
煎蛋要几分熟 八分熟还是全熟

106
00:08:25,600 --> 00:08:27,080
全熟！

107
00:08:38,660 --> 00:08:40,660
你吃白米饭 要不要试试我们的榨菜

108
00:08:41,200 --> 00:08:43,200
5块钱一份  可以

109
00:08:43,220 --> 00:08:45,220
是我们自己做的 跟外面的不一样

110
00:08:49,120 --> 00:08:51,120
因为我估计你没试过 当配菜可以试一下

111
00:09:05,440 --> 00:09:07,440
这边最贵的是1150元一份

112
00:09:07,440 --> 00:09:09,300
但是需要预定

113
00:09:10,020 --> 00:09:12,020
感觉吃不到 也吃不起

114
00:09:12,260 --> 00:09:14,260
上菜了  好 谢谢

115
00:09:15,780 --> 00:09:17,780
这个料汁是什么呀

116
00:09:17,780 --> 00:09:19,160
酱油

117
00:09:26,200 --> 00:09:28,200
你觉得肉淡的话就蘸一下吃

118
00:09:37,240 --> 00:09:39,240
闻着还是有中药材的味道的

119
00:09:50,720 --> 00:09:52,720
炖蝎子 听起来感觉很恶毒

120
00:09:52,860 --> 00:09:54,860
让人感觉很害怕

121
00:09:55,360 --> 00:09:57,360
但是这个汤还是很清澈的

122
00:09:57,880 --> 00:09:59,880
没有任何的浑浊物（让人难受）

123
00:10:02,480 --> 00:10:04,480
这一碗汤大概有五六只蝎子

124
00:10:05,540 --> 00:10:07,540
还有大块的乌鸡肉

125
00:10:12,460 --> 00:10:14,460
先尝一口这个蝎子汤吧

126
00:10:22,640 --> 00:10:24,640
这个汤很清甜 还融入了乌鸡的香味

127
00:10:32,380 --> 00:10:34,380
老板 这个蝎子应该可以吃吧

128
00:10:35,780 --> 00:10:37,780
蘸一下酱油吃 咀嚼一下

129
00:10:38,300 --> 00:10:42,580
能吞的就吞 不能吞的当作骨头一样吐掉

130
00:10:45,820 --> 00:10:47,820
这个蝎子能吃到的部分

131
00:10:47,820 --> 00:10:49,560
其实只有腹部这一部分

132
00:10:49,560 --> 00:10:51,160
其他的部位都吃不到肉

133
00:10:51,800 --> 00:10:53,800
这个肉感觉像鱼脑一样

134
00:10:53,800 --> 00:10:55,440
一下子就吸溜进去了

135
00:10:56,300 --> 00:10:58,300
剩下的都是硬壳 要当骨头一样吐掉

136
00:11:13,240 --> 00:11:15,240
其实 你看在广东 不仅有靓仔

137
00:11:15,240 --> 00:11:16,740
还有靓汤

138
00:11:17,640 --> 00:11:20,160
蝎子是作为一种食材 直接炖汤吃

139
00:11:20,680 --> 00:11:22,680
在我小时候还见过

140
00:11:22,680 --> 00:11:24,360
用蝎子来泡酒的

141
00:11:24,620 --> 00:11:26,620
但是炖汤还是第一尝试吃

**Comment by immoonancient** [comment]
已发布
