### ISSUE TITLE
[华农兄弟] 华农兄弟挖到2个大竹笋庆祝一下抓只兄弟家的鸭来炖 - https://youtu.be/bhegVpXekYk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#577]
https://youtu.be/bhegVpXekYk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 11, 2020 at 11:34AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/bhegVpXekYk

#华农兄弟：挖到2个大竹笋，庆祝一下，抓只兄弟家的鸭来炖
#Huanong Brothers: We got two huge bamboo shoots. To celebrate, we cook it with a duck caught from our buddy's place.

7:56 / 16:08
华农兄弟：挖到2个大竹笋，庆祝一下，抓只兄弟家的鸭来炖

0:00:00.000,0:00:01.540
# 大家好  今天沒菜吃啦
Hi everyone! We run out of food today.

0:00:01.880,0:00:05.220
# 叫兄弟借了他的  借了他的那鋤頭啊  他的鋤頭很利的哦
I've asked my buddy to lend me, lend me his hoe. His hoe is really sharp.

0:00:05.940,0:00:06.800
# 挖個竹笋來
Let's get a bamboo shoot.

0:00:18.000,0:00:18.600
# 你看這裡
Look!

0:00:19.460,0:00:20.900
# 都被兄弟拱過了一樣  (註︰「拱」似乎是一個頗負面的字)
Here seems to have been looted by my buddy.

0:00:23.240,0:00:25.200
# 這裡有個小的  他挖出個小的他不要
Here's a small one. He dug out a small one and he didn't want it.

0:00:26.180,0:00:27.720
# 前兩天兄弟來了這裡挖
My buddy came here for the bamboo shoots a couple of days ago.

0:00:32.920,0:00:33.780
# 這裡太乾啦
It's too dry here,

0:00:34.680,0:00:35.500
# 乾巴巴的
as dry as bone.

0:00:36.400,0:00:37.060
# 肯定沒有
There can't be any.

0:00:38.560,0:00:39.760
# 我去另外一個地方挖
Let me dig at another place.

0:00:40.760,0:00:42.220
# 全部都被人挖過啊
All have been dug out.

0:00:50.680,0:00:51.460
# 這裡沒有
Nothing here.

0:01:06.300,0:01:08.240
# 沿著這個竹林找就會找到的
We can certainly find them along this way.

0:01:12.420,0:01:13.760
# 哎呀  有一個
Aya! Here's one!

0:01:14.880,0:01:15.560
# 看到啦
I can see it.

0:01:20.620,0:01:22.120
# 挖[SIC] (註︰應該是「哇」) 這個土那麼鬆
Wa! The soil is so loose.

0:01:22.880,0:01:23.440
# 怪不得
No wonder,

0:01:24.260,0:01:26.300
# 怪不得那竹笋那麼大  看一下還有沒有
no wonder that the bamboo shoot is that large. Let's see if it's even larger.

0:01:35.120,0:01:36.180
# 哇塞
Wa, gosh!

0:01:42.800,0:01:43.740
# 那麼大
It's huge!

0:01:52.300,0:01:54.060
# 要把這根砍斷
I need to chop off the root.

0:02:14.160,0:02:15.460
# 長了棵那麼深
It goes really deep.

0:02:18.180,0:02:20.080
# 藏的[SIC]那麼好  被我挖掉啦
It's so well hidden. But I've dug it out.

0:02:28.080,0:02:28.900
# 夠大吧
It's big enough, isn't it?

0:02:29.820,0:02:30.900
# 這個一斤左右
It's around 500 grams.

0:02:33.380,0:02:35.160
# 挖的我上氣不接下氣
It makes me pant like a dog.

0:02:38.320,0:02:39.280
# 我都出太陽啦
The sun is now coming out.

0:02:43.680,0:02:44.280
# 沒有
Nothing here.

0:02:52.760,0:02:54.020
# 哎呀  有一個哦
Aya! Here's one!

0:02:55.340,0:02:55.840
# 你看
Look!

0:02:56.700,0:02:57.340
# 這裡有一個
Here's one.

0:03:18.080,0:03:20.080
# 這個  搞這個竹笋太難搞啦
Getting, getting the bamboo shoots is simply too hard.

0:03:33.020,0:03:34.380
# 這個要  下狠心
I can't be too gentle.

0:03:35.140,0:03:36.280
# 這樣把你搞斷
I'll just break you.

0:04:03.180,0:04:04.320
# 終於把它搞開啦
I got it, finally.

0:04:05.540,0:04:06.340
# 這個笋
This bamboo shoot...

0:04:12.620,0:04:13.280
# 又一個
One more

0:04:15.720,0:04:17.160
# 挖這個竹笋挖的[SIC]太累啦
Digging out the bamboo shoots is too exhausting.

0:04:18.600,0:04:20.400
# 這個竹笋不好挖  今年的竹笋不好挖
It's hard, it's hard to get the bamboo shoots this year.

0:04:22.280,0:04:23.680
# 哎呀  挖了兩個啦
Aya! So now I have two.

0:04:24.280,0:04:26.040
# 你看  今天的運氣太好啦
Look! I'm simply too lucky today,

0:04:26.420,0:04:28.040
# 我挖了兩個那麼大的竹笋
having these two enormous bamboo shoots.

0:04:28.700,0:04:29.940
# 等下叫兄弟過來一起吃
Let me ask my buddy to enjoy it with us.

0:04:33.460,0:04:34.180
# 竹子味
The scent of bamboo

0:04:35.340,0:04:35.980
# 好  回去啦
Alright! Let's go back.

0:04:43.820,0:04:44.840
# 剛才我去找了兄弟
We've just tried to reach our buddy.

0:04:45.320,0:04:45.860
# 沒找到
But he was not there.

0:04:46.300,0:04:47.820
# 看到他家的野鴨子放在這裡哦
His wild ducks are now here in front of me.

0:04:49.000,0:04:51.920
# 我去抓過來  野鴨子燉竹笋  也很好吃的哦
Let me catch them. Wild duck bamboo shoots stew, is also a very good dish.

0:04:55.780,0:04:56.840
# 你看  抓了一隻
Look! I've caught one.

0:04:57.580,0:04:58.600
# 這隻大肥鴨
It's a big fat duck.

0:04:59.980,0:05:00.860
# 抓了這隻
Having this one caught,

0:05:01.460,0:05:03.440
# 抓了這一隻的話  那一隻就太孤單啦
having this one caught, that one would be too lonely.

0:05:04.100,0:05:06.680
# 等一下不知道會跑哪野去  我把那隻也抓過來
Who knows where it might go. Let me catch that one as well.

0:05:07.600,0:05:08.520
# 這隻你拿著先
You hold this one first.

0:05:21.980,0:05:23.540
# 野鴨子  別跑
Wild ducky! Don't run away!

0:05:24.880,0:05:26.040
# 帶你去玩哦
I'll take you to an interesting place.

0:05:40.160,0:05:40.660
# 你看
Look!

0:05:40.880,0:05:42.180
# 這兩隻鴨子都捉回來啦
Both ducks are caught.

0:05:42.800,0:05:44.100
# 等一下叫兄弟一起來吃
Let's ask our buddy to enjoy with us.

0:05:44.920,0:05:45.980
# 兄弟應該沒意見
He should have no objections.

0:05:59.020,0:05:59.640
# 別叫啊
Don't yelp!

0:06:07.680,0:06:08.180
# 你看
Look!

0:06:08.560,0:06:09.620
# 那麼肥的鴨子
What a fat duck!

0:06:10.300,0:06:12.200
# 這個我也拔不乾淨啦  我扒皮
I can't dehair it thoroughly. So I'll skin it.

0:06:12.800,0:06:13.560
# 把它皮拔掉
Let me strip it's skin.

0:06:17.140,0:06:18.760
# 這個皮不好吃  這個皮
The skin doesn't taste good, the skin.

0:06:19.840,0:06:20.420
# 反正
I can't,

0:06:22.240,0:06:23.420
# 洗不了這個皮
I can't wash the skin anyway.

0:06:26.660,0:06:27.520
# 來  不狗
Doggy come!

0:06:28.160,0:06:28.660
# 吃皮
Take the skin!

0:06:32.960,0:06:33.900
# 拔皮啊
Skin it!

0:06:35.100,0:06:37.300
# 把皮扒了就剩下這樣子  翅也沒要
That's what remains after skinning. The wings are also taken away,

0:06:39.100,0:06:41.060
# 腳要[SIC]沒要  剩下這個   我把它砍碎
and the feet too. Leaving only this. Let me chop it into pieces.

0:06:43.100,0:06:43.960
# 全是瘦肉
There's only lean meat.

0:06:55.900,0:06:57.840
# 裝點水  去一下血沫
Put some water, to remove the blood.

0:07:18.000,0:07:19.300
# 把這個竹笋  剝啦
I'm gonna peel the bamboo shoots now.

0:07:21.220,0:07:23.040
# 這個頭  這個頭不能吃的
The head, the head is not edible.

0:07:34.620,0:07:35.420
# 你要嗎
You want it?

0:07:36.420,0:07:37.180
# 給小豬吃
Leave it for the piggies.

0:07:39.960,0:07:41.580
# 那麼大的笋  就那麼一點點肉
In spite of its size, the edible part is just a tiny little bit.

0:07:43.080,0:07:43.840
# 沒多少肉啦
There's not much to eat.

0:07:47.860,0:07:48.680
# 就那麼一點點
It's just a tiny little bit.

0:07:49.460,0:07:51.460
# 把它切成一塊一塊的
Let me cut it into pieces.

0:07:52.700,0:07:54.360
# 然後跟 竹 鴨子
And then together with bam... the duck,

0:07:55.860,0:07:57.480
# 就  直接燜鴨子
make a stew with the duck right, right away.

0:07:58.200,0:07:59.240
# 竹笋燜鴨子
Bamboo shoots and duck stew

0:08:05.300,0:08:05.900
# 搞定
Alright!

0:08:07.140,0:08:08.100
# 放到這裡先
Put it here first.

0:08:15.540,0:08:16.760
# 你看  就那麼一點點
Look! It's just a tiny little bit here.

0:08:17.780,0:08:21.160
# 這個竹笋  放多了也不好吃  就放那麼一點點就夠了
It won't taste any better with even with more bamboo shoots. Just a tiny little bit here is enough.

0:08:21.660,0:08:22.820
# 主要是鴨子好吃
It's the duck which tastes good.

0:08:24.460,0:08:25.420
# 先把它放在這裡
Put it here first.

0:08:30.020,0:08:31.540
# 我還剛買了雙新鞋
I've just bought a new pair of slippers.

0:08:33.000,0:08:37.420
# 你看  這些血沬  我把它換一下水就可以直接煲了
Look! That's the blood. It can be cooked right away after replenishing it with fresh water.

0:08:47.020,0:08:51.300
# 啊  可以  我把那個  我把竹笋拿過來
Ah! Good! Let me, let me fetch the bamboo shoots.

0:08:56.020,0:08:56.680
# 這個竹笋
These are the bamboo shoots.

0:09:01.100,0:09:02.060
# 加點生薑
Put some ginger.

0:09:04.520,0:09:06.000
# 就直接這樣  先煲一下
Then just cook it for a while.

0:09:10.320,0:09:11.360
# 蓋子  蓋住
Cover it, with the lid.

0:09:14.360,0:09:16.380
# 接下來就是  大火 猛燒
Next, it's high heat, burn fiercely.

0:09:22.300,0:09:25.120
# 這個豬  關都關不住了  全部都跑到這裡來啦
The pigs, I can't fence them off anymore. They've all come here.

0:09:26.320,0:09:27.260
# 給個西紅杮給它吃
I give them a tomato.

0:09:30.400,0:09:30.900
# 小豬
Piggies!

0:09:32.660,0:09:33.160
# 小豬
Piggies!

0:09:34.740,0:09:35.760
# 要不要西紅杮吃哦
You want tomato?

0:09:37.500,0:09:38.360
# 要不要吃哦
Do you?

0:09:42.900,0:09:43.940
# 十幾隻啦
A dozen of them now.

0:09:45.500,0:09:47.000
# 那條大公豬最不聽話
The big boar is the naughtiest.

0:10:01.860,0:10:03.660
# 嗯  很喜歡吃哦
Um! It likes the tomato very much.

0:10:05.380,0:10:06.900
# 全部人都看著我  沒有啦
Everybody is looking at me. No more!

0:10:07.280,0:10:08.220
# 我吃都吃完了
I've finished it.

0:10:08.760,0:10:09.480
# 又不早點來
You should have come earlier.

0:10:12.460,0:10:13.820
# 小豬崽現在都七八斤了
The little piglets are almost four kilograms now.

0:10:15.960,0:10:18.000
# 下次我們搞一條來  做烤乳豬
Let's get one next time, to make a roast suckling pig.

0:10:22.380,0:10:24.320
# 你看這隻  這隻想偷奶喝
Look at this puppy! It wants to steal the milk.

0:10:24.440,0:10:26.700
# 不行哦  那麼大了  不能偷奶喝
No! You're that big now. You can't steal milk.

0:10:27.820,0:10:30.160
# 吃了奶  吃弓了奶會中毒的  走開
You'll get poisoned, you'll get poisoned if you have the milk. Go 'way!

0:10:31.000,0:10:32.120
# 快點吃  吃
Suck it, suck!

0:10:32.320,0:10:34.420
# 這條小胖墩  這條好肥呀  這條  (註︰小胖墩是苏洋取的名字)
This is Chubbie. It's so fat, this puppy!

0:10:36.860,0:10:38.460
# 小狗   小狗
Puppy! Puppy!

0:10:39.220,0:10:40.540
# 小狗
Puppy~!

0:10:41.780,0:10:42.280
# 這個狗
This puppy...

0:10:47.560,0:10:49.000
# 這個是  小母狗
It's a, little girl.

0:10:50.580,0:10:51.080
# 你看
Look!

0:10:54.520,0:10:55.740
# 它的毛好好摸啊
It's coat feels so good.

0:10:58.940,0:10:59.440
# 叫啊
Yelp!

0:10:59.800,0:11:00.500
# 怎麼不叫的
Why don't you yelp?

0:11:01.500,0:11:02.000
# 叫
Yelp!

0:11:04.040,0:11:04.600
# 不叫
She doesn't yelp.

0:11:07.560,0:11:09.140
# 你看  它這個皮  嘿嘿
Have a look at her coat! He he

0:11:10.160,0:11:10.960
# 舒不舒服
Does it feel good?

0:11:11.360,0:11:12.200
# 給你按摩哦
I'm giving you a massage, you know.

0:11:13.060,0:11:13.660
# 哦
Oh!

0:11:14.900,0:11:16.180
# 你看  它多享受
Look! She enjoys it so much,

0:11:16.800,0:11:17.880
# 享受我的按摩
enjoys my massage.

0:11:20.220,0:11:21.120
# 跟你握握手
Shake hand with you.

0:11:23.360,0:11:24.440
# 看這邊
Put your eyes here.

0:11:24.600,0:11:25.580
# 看這邊
Put your eyes here.

0:11:26.040,0:11:27.840
# 看這邊啊  看我有甚麼好看的
I say put your eyes here. What's the purpose of looking at me?

0:11:30.620,0:11:32.280
# 你看  好爽啊  哈哈
Look! Isn't it cool? Ha ha!

0:11:36.020,0:11:38.880
# 這它沒反應  它正在享受當中  它在
No response. She's enjoying her time. She's...

0:11:40.520,0:11:41.520
# 給你坐個搖搖車
Let me be your kiddie ride.

0:11:42.540,0:11:43.740
# 像個搖搖車一樣
It's like a kiddie ride.

0:11:44.200,0:11:44.860
# 多爽啊
Cool!

0:11:47.460,0:11:49.140
# 來  坐個搖搖車  是不是搖
C'mon! I'm your kiddie ride. Do you like it?

0:11:52.020,0:11:54.440
# 搖搖搖搖搖  你看 搖的不肯了
Rock rock rock rock rock. Look! She doesn't want it.

0:11:56.340,0:11:58.360
# 來啦  你吃飽了哦  是不是
C'mon! You've eaten enough, haven't you?

0:11:58.840,0:12:00.820
# 吃飽了就過來 看一下你那麼胖啊
Then come here. Let me see how fat you are.

0:12:01.180,0:12:02.140
# 多胖啊  你知不知道
Do you know how fat you are?

0:12:02.660,0:12:03.700
# 超標了  身材
You're already overweight.

0:12:04.280,0:12:05.000
# 這樣怎麼行
How can it be ?

0:12:05.940,0:12:06.440
# 來
Come!

0:12:06.860,0:12:07.420
# 看一下你
Let me have a look!

0:12:07.960,0:12:08.540
# 搖搖車
Kiddie ride

0:12:14.240,0:12:15.140
# 它在拖地
He's wiping the floor.

0:12:16.140,0:12:16.780
# 搞的[SIC]好髒
It's so dirty.

0:12:17.100,0:12:18.320
# 啊  過來
Ah! Come here!

0:12:19.680,0:12:20.220
# 小狗
Puppu!

0:12:20.940,0:12:24.100
# 小狗  你鑽到哪裡去啦  搞到一身都是髒不拉稀的
Puppy! Where have you been? Why are you dirty?

0:12:24.960,0:12:27.400
# 你看著我幹嘛  我又沒奶給你吃
Why are you looking at me? I don't have any milk for you.

0:12:30.120,0:12:31.180
# 好肥呀  這隻
He's really fat, this puppy.

0:12:32.600,0:12:34.400
# 哎呀 一身肥膘  跟那個
Aya! The whole body is covered with fat. And the,

0:12:34.840,0:12:36.340
# 這個  這個肉
the, the flesh here,

0:12:37.740,0:12:40.660
# 一抓  皺巴巴的  一揪  一揪把它揪得起來
I can, it's folded, I can take it up simply, simply by grabbing it here.

0:12:41.300,0:12:43.240
# 說明你胖  知不知道
It means that you are fat. Got it?

0:12:45.940,0:12:47.100
# 來  坐一下搖搖車
C'mon! Get onto the kiddie ride.

0:12:48.120,0:12:49.680
# 免費的搖搖車給你坐一下
I let you enjoy this free kiddie ride.

0:12:53.980,0:12:54.600
# 不肯
He doesn't like it.

0:12:55.720,0:12:58.520
# 享  趴在那裡不動啦  耍賴皮
Hm! He's lying there, like a statue, shamelessly.

0:12:59.600,0:13:00.800
# 看它牙齒  好利啊
Look! His teeth are really sharp.

0:13:01.560,0:13:02.820
# 長大了肯定很強壯
He must be very strong when he grows up.

0:13:05.660,0:13:06.640
# 把它綁起來
Let me tie you up!

0:13:08.340,0:13:09.900
# 不能咬我啊  你咬了我
Don't bite me! If you bite me,

0:13:10.720,0:13:11.780
# 我把你牙齒拔掉
I'll knock off your teeth.

0:13:17.720,0:13:19.900
# 看 快點  看  看鏡頭
Look! C'mon! Look! Look at the camera!

0:13:20.820,0:13:24.740
# 給你看著  不看  不看不行的哦  看著
I say look at the camera. You are not looking. You have to look at the camera. Look at it!

0:13:25.880,0:13:26.760
# 看啦
Just look!

0:13:28.320,0:13:29.040
# 它不看
It's not looking.

0:13:29.780,0:13:30.480
# 不聽話
Naughty!

0:13:31.660,0:13:33.960
# 聽話才行  不聽話不喜歡你哦
Be a good boy! You can't gain my love if you're naughty.

0:14:05.180,0:14:07.000
# 哎呀  好香啊
Aya! It smells so good!

0:14:08.800,0:14:09.720
# 來  加點鹽
Alright! Put some salt.

0:14:11.500,0:14:12.020
# 誒呦
Eyo?

0:14:13.120,0:14:13.900
# 應該可以  夠了
I think it's alright. It should be enough.

0:14:26.140,0:14:27.480
# OK  可以
Okay! Good!

0:14:43.920,0:14:45.540
# 開始吃啦  這個好吃
Let's get started. It tastes good!

0:14:46.780,0:14:47.480
# 鴨肉哦
It's duck!

0:14:53.680,0:14:56.260
# 你看  這個竹笋  很好吃的啊
Look! The bamboo shoot, is really tasty.

0:15:01.880,0:15:03.300
# 很脆  很清甜
It's crunchy and sweet.

0:15:08.140,0:15:08.880
# 這個鴨肉
The duck...

0:15:12.980,0:15:15.020
# 哇  好吃哦  這個鴨肉
Wa! Tasty! The duck

0:15:16.140,0:15:16.880
# 都煲爛啦
It's so soft and tender.

0:15:20.320,0:15:23.960
# 喝一下這個湯  這個湯很好喝  你看  這湯變白啦
Let me have some soup. The soup must be very tasty. Look! It's already milky white.

0:15:25.880,0:15:26.900
# 很甜的  這個湯
The soup is savory sweet.

0:15:31.480,0:15:32.900
# 嗯  這個鴨肉蠻好吃的  (註︰似乎不幫金洋做字幕也要Standardize這句的翻譯了)
Um! The duck is rather tasty.

0:15:35.320,0:15:37.700
# 哇 這湯好甜  可以哦
Wa! The soup tastes really good. Not bad!

0:15:38.280,0:15:41.220
# 還有一隻  下次來把它  吃了
The other duck is over there. Next time we'll, eat it.

0:15:48.760,0:15:50.640
# 現在豬看到我們吃  它也過來啦
The pigs are also coming now when they see us eating.

0:15:56.020,0:15:56.780
# 小豬
Piggies!

0:15:57.700,0:15:58.840
# 你們又搶不到來吃
But you can''t get our good.

0:15:59.900,0:16:01.940
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:16:02.500,0:16:03.340
# 先吃飽再算
Let's feed ourselves first.

**Comment by immoonancient** [comment]
终于使用 bot 上传成功，可喜可贺

**Comment by vincenthychow** [comment]
已發佈
