### ISSUE TITLE
【美食作家王刚】烤牛腿 - https://youtu.be/banzyGAkxA8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#580]
【美食作家王刚】烤牛腿 - https://youtu.be/banzyGAkxA8
视频时长 6:35，预计发布时间为北京时间1月14日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.375,0:00:01.375
哈喽大家好

0:00:01.375,0:00:03.968
过年了嘛 我伯爷都说过年要吃点好的

0:00:04.200,0:00:05.671
所以我买了这个牛腿

0:00:05.900,0:00:09.728
这一根牛腿肉不多 买来今天下午烤来吃

0:00:10.250,0:00:12.975
这是新鲜的 价格现在还算比较公道

0:00:13.150,0:00:15.775
因为是剩的一些东西 全部都给他买了

0:00:16.000,0:00:19.625
我还是跟上次烤猪那样把它烤了

0:00:19.940,0:00:22.880
要的嘛 你这个厚很了你不片哈啊

0:00:22.980,0:00:24.900
等会拿你的杀猪刀来片撒

0:00:25.100,0:00:27.375
这个片薄一点 不然烤不好

0:00:28.420,0:00:31.340
这个牛肉刚刚洗好 我随便改下刀

0:00:32.100,0:00:33.740
先暂时改一下

0:00:34.740,0:00:36.700
改好刀准备腌一下

0:00:41.600,0:00:44.020
这两块是它屁股上面那一截

0:00:45.080,0:00:46.800
因为没什么肉 老板白送

0:00:51.520,0:00:53.580
老婆 给我赶一下这个鸡

0:00:54.980,0:00:56.480
这公鸡也想吃肉

0:00:56.650,0:00:58.700
这一块的话肉就比较厚

0:00:59.140,0:01:03.140
这一块我估计有十多斤吧

0:01:03.920,0:01:08.020
这一块肉的话有十公分厚 所以要先改一下（刀）

0:01:08.020,0:01:10.600
这一次改主要是入味

0:01:10.600,0:01:12.000
先竖着改

0:01:18.440,0:01:21.120
好 准备一下料头 腌一下

0:01:25.325,0:01:27.150
腌这个搞简单一点

0:01:27.200,0:01:28.450
就搞点姜片吧

0:01:37.480,0:01:40.900
现在过年了嘛 过年了在家里做一点好吃的

0:01:40.900,0:01:43.280
平时没有这么奢侈

0:01:50.080,0:01:51.340
再加点小葱

0:02:04.040,0:02:08.060
我伯爷说这个搞简单一点所以就简简单单的

0:02:08.120,0:02:12.280
正好我上次烤猪还剩了一些烧烤料

0:02:13.340,0:02:14.340
正好可以用上

0:02:15.000,0:02:17.200
姜葱加下去了之后再加一点白酒

0:02:17.450,0:02:18.900
这个白酒是低度的

0:02:20.925,0:02:24.425
再多少放一点盐 盐就不要放太多

0:02:29.925,0:02:30.550
好

0:02:33.540,0:02:34.940
给它抹一下

0:02:46.800,0:02:48.760
好 先腌它两个小时

0:02:49.520,0:02:50.940
现在去生碳

0:03:00.340,0:03:02.700
上次用的碳还没用完

0:03:04.140,0:03:07.020
这次烤这个牛腿把它全部用掉

0:03:24.820,0:03:25.640
要得咯

0:03:27.240,0:03:29.220
四伯爷 来嘛 帮都捆哈

0:03:30.620,0:03:34.940
还有点重噶 十多斤

0:03:41.525,0:03:43.050
我给你剪哈不嘛

0:03:43.240,0:03:44.960
剪成几节

0:03:46.680,0:03:48.040
我这里给你剪哈

0:03:48.040,0:03:49.160
诶 长了

0:03:50.480,0:03:51.320
从这里（剪）安

0:03:57.100,0:04:00.820
现在我们用这个铁丝把这个牛肉固定在这个架子上面

0:04:02.600,0:04:06.500
多固定一下 落下去得话就等于是“喂”碳去了

0:04:17.650,0:04:18.450
穿进去没

0:04:18.475,0:04:20.400
穿进去了

0:04:21.475,0:04:23.700
就先这样等它慢慢烤都

0:04:24.675,0:04:25.850
高不高了点哦

0:04:26.000,0:04:29.400
不得高 这个你矮了的话一下就要糊

0:04:29.600,0:04:32.350
这个不开玩笑 高点好点

0:04:32.450,0:04:34.450
让它慢慢受热烤

0:04:34.575,0:04:35.950
烤出水了

0:04:36.025,0:04:37.075
是不是哦

0:04:38.175,0:04:39.550
好快哦

0:04:41.040,0:04:43.360
你看嘛这里都在滴水了

0:04:44.400,0:04:45.720
还真是

0:04:47.060,0:04:49.680
来 漆二娃 你来守都它

0:04:50.620,0:04:51.440
经常翻

0:05:02.340,0:05:03.420
轻点拷（转）哦

0:05:03.960,0:05:05.400
等会儿烤落了哈

0:05:05.425,0:05:07.025
拷落了今天就不吃

0:05:07.475,0:05:11.425
四伯爷 你看这牛腿烤得这个水蒸气直冒

0:05:12.175,0:05:14.525
你看那个鸡想吃的不得了咯

0:05:15.200,0:05:16.225
一个脑壳在那里蹭一蹭得

0:05:17.250,0:05:21.050
你看嘛 这皮子都收紧了四伯爷

0:05:21.450,0:05:24.675
我感觉我每一次翻都提心吊胆的

0:05:25.850,0:05:27.050
落了就怪你撒

0:05:27.175,0:05:29.400
这里这一坨厚的很哦

0:05:29.740,0:05:32.140
等会拿你的杀猪刀来划

0:05:32.920,0:05:35.920
沺沺 过来看爸爸烤牛腿

0:05:35.925,0:05:36.793
看狗狗

0:05:36.793,0:05:37.820
看狗狗啊

0:05:37.820,0:05:38.440
嗯

0:05:38.820,0:05:39.900
狗狗出去玩了

0:05:41.850,0:05:43.375
你看这个牛腿香不香

0:05:46.350,0:05:47.025
不香啊

0:05:48.440,0:05:50.040
你看那个油接是滴

0:06:01.380,0:06:03.400
烤熟的就片来干（吃）了

0:06:04.125,0:06:06.750
没烤熟的就等它在上面又烤

0:06:08.225,0:06:12.875
所以现在的话每隔一个小时我带你们看一下它有什么变化

0:06:13.100,0:06:15.200
这个确实要很多时间

0:06:25.150,0:06:27.075
诶 等会整不整点海椒（辣椒）在上面安

0:06:27.175,0:06:29.100
要 我配了的 配了香料的

0:06:35.075,0:06:36.500
这边要不要加点火呀

0:06:36.575,0:06:37.250
不用

0:06:40.525,0:06:41.100
沺沺

0:06:41.100,0:06:41.580
嗯

0:06:41.580,0:06:42.760
要不要尝一块啊

0:06:42.760,0:06:43.260
要

0:06:43.800,0:06:44.920
爸爸给你弄一块好不好

0:06:44.975,0:06:45.475
好

0:06:45.480,0:06:46.820
闻着挺香是吧

0:06:46.820,0:06:47.320
嗯

0:06:49.120,0:06:49.840
烫吗

0:06:50.850,0:06:52.450
不烫 这块熟了

0:06:53.875,0:06:54.775
好不好吃

0:06:55.600,0:06:56.500
好吃吗

0:06:56.550,0:06:57.275
嗯

0:06:59.325,0:07:01.675
差不多了 那块肉要好了的了

0:07:02.925,0:07:04.300
我把碳整一下

0:07:04.325,0:07:07.425
嗯 这坨好了 吃起还很香

0:07:09.275,0:07:10.850
真的熟了

0:07:13.880,0:07:15.180
这一坨都熟了

0:07:16.400,0:07:17.380
是不是

0:07:17.400,0:07:18.060
熟了

0:07:22.980,0:07:24.660
可能只有中间这儿还没熟

0:07:29.150,0:07:30.675
割一块给沺沺吃

0:07:32.540,0:07:33.340
有点烫啊

0:07:35.160,0:07:35.840
烫不烫

0:07:40.450,0:07:41.650
四伯爷 自己割哦

0:07:41.975,0:07:43.675
想吃哪里割哪里

0:07:43.950,0:07:48.075
现在抹这个油 这个是我调的料油

0:07:48.625,0:07:52.150
抹好了之后就撒点孜然辣椒面什么的

0:07:52.425,0:07:53.675
可以了

0:07:54.475,0:07:55.525
先撒孜然

0:08:02.120,0:08:03.780
咿呀 有点好吃哦

0:08:04.680,0:08:05.800
好香哦

0:08:05.820,0:08:07.220
我也想吃

0:08:07.220,0:08:08.180
你也想吃啊

0:08:08.480,0:08:11.200
等一下啊 爸爸给你留了一块没加辣的

0:08:27.120,0:08:28.120
好啦沺沺

0:08:29.320,0:08:30.340
好香哦

0:08:34.920,0:08:35.740
好 可以

0:08:37.280,0:08:37.820
烫哦

0:08:39.000,0:08:40.600
你先试一下烫不烫

0:08:40.725,0:08:42.375
这个筋是不是可以吃的

0:08:42.525,0:08:43.225
可以啊

0:08:43.700,0:08:46.320
我都想用手弄来吃了

0:08:47.140,0:08:48.320
我都想用手弄来吃了

0:08:50.120,0:08:53.860
你掐不动啊老婆 来 这是筋

0:08:56.040,0:08:57.360
嗯 好吃

0:09:01.550,0:09:02.925
漆二娃 来

0:09:06.525,0:09:08.300
看都你一直在旁边吞口水

0:09:08.525,0:09:10.625
漆二娃 这

0:09:12.450,0:09:14.825
可不可以让我一个位置

0:09:15.125,0:09:17.575
让你一个位置啊 来吧来吧

0:09:17.680,0:09:19.180
小心别戳到上面了

0:09:20.360,0:09:21.600
好香哦 好吃

0:09:21.600,0:09:22.860
香是蛮香的

0:09:26.325,0:09:27.775
这里这里

0:09:27.920,0:09:32.220
那里撕不动撕这里 这一块也是（肉）你看

0:09:35.540,0:09:40.120
好吃吧 这里你看这一坨都是好吃的

0:09:45.980,0:09:48.440
把这坨肉剁下来嘛四伯爷

0:09:50.350,0:09:52.200
割下来哦 割它下来就是

0:10:01.800,0:10:03.475
好脆啊这个筋

0:10:09.925,0:10:11.800
放下面就是

0:10:12.700,0:10:16.100
好啦 我们取下来慢慢割着吃

0:10:16.350,0:10:17.700
本期视频就到这里啦

0:10:18.050,0:10:19.875
有空的话你们在家也可以试一下

0:10:20.475,0:10:22.200
这个牛肉是要贵那么一点点

0:10:23.275,0:10:24.100
好吃

0:10:24.100,0:10:25.375
好吃吗

0:10:25.425,0:10:25.925
嗯

0:10:26.325,0:10:28.750
好好吃呀 妈妈爸爸

0:10:28.850,0:10:30.100
那你多吃一点啊

0:10:30.175,0:10:32.025
那一块都是你的 不辣的

**Comment by immoonancient** [comment]
我来吧

**Comment by immoonancient** [comment]
bot, please upload

0:00:00.375,0:00:01.375
哈喽大家好
Hello everyone

0:00:01.375,0:00:03.968
过年了嘛 我伯爷都说过年要吃点好的
The (Chinese) New Year is approach. Uncle said we need to treat ourselves with something good for the New Year

0:00:04.200,0:00:05.671
所以我买了这个牛腿
So I bought this beef leg

0:00:05.900,0:00:09.728
这一根牛腿肉不多 买来今天下午烤来吃
Not a big one. We'll grill it this afternoon

0:00:10.250,0:00:12.975
这是新鲜的 价格现在还算比较公道
It's a fresh one. The price was fair

0:00:13.150,0:00:15.775
因为是剩的一些东西 全部都给他买了
As it's a leftover. I bought them all

0:00:16.000,0:00:19.625
我还是跟上次烤猪那样把它烤了
We'll grill it, like how we grilled the pig last time

0:00:19.940,0:00:22.880
要的嘛 你这个厚很了你不片哈啊
Yeah. It's very thick. You need to slice it, don't you?

0:00:22.980,0:00:24.900
等会拿你的杀猪刀来片撒
I'll slice it with your butchering knife

0:00:25.100,0:00:27.375
这个片薄一点 不然烤不好
Need to slice it well. Or it's hard to grill

0:00:28.420,0:00:31.340
这个牛肉刚刚洗好 我随便改下刀
The beef has been cleaned up. Let me slice it for a bit

0:00:32.100,0:00:33.740
先暂时改一下
For now

0:00:34.740,0:00:36.700
改好刀准备腌一下
And marinate it after that

0:00:41.600,0:00:44.020
这两块是它屁股上面那一截
These two pieces are above the butt

0:00:45.080,0:00:46.800
因为没什么肉 老板白送
The seller gave me for free, as there's not much meat

0:00:51.520,0:00:53.580
老婆 给我赶一下这个鸡
Honey, could you drive the chicken away?

0:00:54.980,0:00:56.480
这公鸡也想吃肉
The rooster also wants some meat

0:00:56.650,0:00:58.700
这一块的话肉就比较厚
The meat is very thick here

0:00:59.140,0:01:03.140
这一块我估计有十多斤吧
I guess it weighs over 10 jin (jin = 500g)

0:01:03.920,0:01:08.020
这一块肉的话有十公分厚 所以要先改一下（刀）
This chunk of meat must be over 10cm thick. So I need to slice it first

0:01:08.020,0:01:10.600
这一次改主要是入味
Slicing to help flavor penentration

0:01:10.600,0:01:12.000
先竖着改
Slice with the grain first

0:01:18.440,0:01:21.120
好 准备一下料头 腌一下
Alright. Prepare the seasoning to marinate it

0:01:25.325,0:01:27.150
腌这个搞简单一点
Let's do it simple

0:01:27.200,0:01:28.450
就搞点姜片吧
Just some ginger slices

0:01:37.480,0:01:40.900
现在过年了嘛 过年了在家里做一点好吃的
You know, it's the New Year. We'll have something good at home for the New Year

0:01:40.900,0:01:43.280
平时没有这么奢侈
We don't always have such luxuries

0:01:50.080,0:01:51.340
再加点小葱
Also some scallions

0:02:04.040,0:02:08.060
我伯爷说这个搞简单一点所以就简简单单的
Uncle said, it can be simpler. So we'll keep it simple

0:02:08.120,0:02:12.280
正好我上次烤猪还剩了一些烧烤料
We didn't use up the BBQ seasonings last time when grilling the pig

0:02:13.340,0:02:14.340
正好可以用上
So we can use them this time

0:02:15.000,0:02:17.200
姜葱加下去了之后再加一点白酒
After ginger and scallion, add some baijiu (liquor)

0:02:17.450,0:02:18.900
这个白酒是低度的
This is low alcohol baijiu

0:02:20.925,0:02:24.425
再多少放一点盐 盐就不要放太多
And also some salt. Not too much

0:02:29.925,0:02:30.550
好
Good

0:02:33.540,0:02:34.940
给它抹一下
Rub it

0:02:46.800,0:02:48.760
好 先腌它两个小时
Good. Marinate it for two hours

0:02:49.520,0:02:50.940
现在去生碳
Now we'll light the charchol

0:03:00.340,0:03:02.700
上次用的碳还没用完
We didn't use up the charcoal last time

0:03:04.140,0:03:07.020
这次烤这个牛腿把它全部用掉
So this time, let's use it up for the beef leg

0:03:24.820,0:03:25.640
要得咯
Alright

0:03:27.240,0:03:29.220
四伯爷 来嘛 帮都捆哈
Come on, uncle! Help me tie it

0:03:30.620,0:03:34.940
还有点重噶 十多斤
Kinda heavy, hub? At least 10 jin

0:03:41.525,0:03:43.050
我给你剪哈不嘛
Let me cut it for you

0:03:43.240,0:03:44.960
剪成几节
Cut it

0:03:46.680,0:03:48.040
我这里给你剪哈
I'll cut it here?

0:03:48.040,0:03:49.160
诶 长了
Eh, that's too long

0:03:50.480,0:03:51.320
从这里（剪）安
Cut it here?

0:03:57.100,0:04:00.820
现在我们用这个铁丝把这个牛肉固定在这个架子上面
Now we are fixing the beef on the rack with some iron wire

0:04:02.600,0:04:06.500
多固定一下 落下去得话就等于是“喂”碳去了
Fix it well. If it falls, we are feeding the charcoal instead

0:04:17.650,0:04:18.450
穿进去没
Has it gone through?

0:04:18.475,0:04:20.400
穿进去了
Yeah

0:04:21.475,0:04:23.700
就先这样等它慢慢烤都
Let's slow grill it like this for now

0:04:24.675,0:04:25.850
高不高了点哦
Isn't it too high?

0:04:26.000,0:04:29.400
不得高 这个你矮了的话一下就要糊
Not high. It will burn if you lower it

0:04:29.600,0:04:32.350
这个不开玩笑 高点好点
Not kidding. Better be higher

0:04:32.450,0:04:34.450
让它慢慢受热烤
Let it heat slowly

0:04:34.575,0:04:35.950
烤出水了
The water is coming out

0:04:36.025,0:04:37.075
是不是哦
Is it?

0:04:38.175,0:04:39.550
好快哦
So fast

0:04:41.040,0:04:43.360
你看嘛这里都在滴水了
Look, water drops here

0:04:44.400,0:04:45.720
还真是
Oh yeah

0:04:47.060,0:04:49.680
来 漆二娃 你来守都它
Come here, Qi Erwa. Handle it

0:04:50.620,0:04:51.440
经常翻
Flip it often

0:05:02.340,0:05:03.420
轻点拷（转）哦
Be careful when you flip it

0:05:03.960,0:05:05.400
等会儿烤落了哈
What if it falls?

0:05:05.425,0:05:07.025
拷落了今天就不吃
Then we are not going to eat today

0:05:07.475,0:05:11.425
四伯爷 你看这牛腿烤得这个水蒸气直冒
Uncle, look! The steam is grilled out

0:05:12.175,0:05:14.525
你看那个鸡想吃的不得了咯
Look at that chicken! It wants to eat so much

0:05:15.200,0:05:16.225
一个脑壳在那里蹭一蹭得
The head keeps popping out

0:05:17.250,0:05:21.050
你看嘛 这皮子都收紧了四伯爷
The skin has been tightened, uncle

0:05:21.450,0:05:24.675
我感觉我每一次翻都提心吊胆的
I'm so anxious to flip it

0:05:25.850,0:05:27.050
落了就怪你撒
If it falls, you'll be blamed

0:05:27.175,0:05:29.400
这里这一坨厚的很哦
This part is too thick

0:05:29.740,0:05:32.140
等会拿你的杀猪刀来划
Let's slice it later with your butchering knife

0:05:32.920,0:05:35.920
沺沺 过来看爸爸烤牛腿
Tian Tian, come here! Watch daddy grill a beef leg

0:05:35.925,0:05:36.793
看狗狗
Watch the little dog

0:05:36.793,0:05:37.820
看狗狗啊
You want to watch the little dog?

0:05:37.820,0:05:38.440
嗯
Yes

0:05:38.820,0:05:39.900
狗狗出去玩了
The little dog has gone outside

0:05:41.850,0:05:43.375
你看这个牛腿香不香
Is this beef leg tasty?

0:05:46.350,0:05:47.025
不香啊
Not tasty

0:05:48.440,0:05:50.040
你看那个油接是滴
Look, the oil drops

0:06:01.380,0:06:03.400
烤熟的就片来干（吃）了
We can slice the cooked parts and eat

0:06:04.125,0:06:06.750
没烤熟的就等它在上面又烤
And wait for the raw parts to grill

0:06:08.225,0:06:12.875
所以现在的话每隔一个小时我带你们看一下它有什么变化
So after every hour, I'll check the progress with you

0:06:13.100,0:06:15.200
这个确实要很多时间
It's going to take a long time, indeed

0:06:25.150,0:06:27.075
诶 等会整不整点海椒（辣椒）在上面安
Eh, do we add chili later?

0:06:27.175,0:06:29.100
要 我配了的 配了香料的
Yeah, I've prepared it. I've prepared spices

0:06:35.075,0:06:36.500
这边要不要加点火呀
Do we need to add some fire here?

0:06:36.575,0:06:37.250
不用
No

0:06:40.525,0:06:41.100
沺沺
Tian Tian

0:06:41.100,0:06:41.580
嗯
Yes

0:06:41.580,0:06:42.760
要不要尝一块啊
Do you want to try?

0:06:42.760,0:06:43.260
要
Yes

0:06:43.800,0:06:44.920
爸爸给你弄一块好不好
Let daddy find a piece for you, OK?

0:06:44.975,0:06:45.475
好
OK

0:06:45.480,0:06:46.820
闻着挺香是吧
Smells good, right?

0:06:46.820,0:06:47.320
嗯
Yes

0:06:49.120,0:06:49.840
烫吗
Is it hot?

0:06:50.850,0:06:52.450
不烫 这块熟了
Not hot. This piece is cooked

0:06:53.875,0:06:54.775
好不好吃
Is it tasty?

0:06:55.600,0:06:56.500
好吃吗
Tasty?

0:06:56.550,0:06:57.275
嗯
Huh

0:06:59.325,0:07:01.675
差不多了 那块肉要好了的了
Looks good. That piece looks already done

0:07:02.925,0:07:04.300
我把碳整一下
Let me deal with the charcoal

0:07:04.325,0:07:07.425
嗯 这坨好了 吃起还很香
Hmm, this part is done. Very tasty

0:07:09.275,0:07:10.850
真的熟了
Yeah, it's done

0:07:13.880,0:07:15.180
这一坨都熟了
This part is all done

0:07:16.400,0:07:17.380
是不是
Is it?

0:07:17.400,0:07:18.060
熟了
Done

0:07:22.980,0:07:24.660
可能只有中间这儿还没熟
Maybe only the middle part isn't done yet

0:07:29.150,0:07:30.675
割一块给沺沺吃
Cut a slice for Tian Tian

0:07:32.540,0:07:33.340
有点烫啊
It's a bit hot

0:07:35.160,0:07:35.840
烫不烫
Is it hot?

0:07:40.450,0:07:41.650
四伯爷 自己割哦
Do it yourself, uncle?

0:07:41.975,0:07:43.675
想吃哪里割哪里
Cut whatever you want to eat

0:07:43.950,0:07:48.075
现在抹这个油 这个是我调的料油
Now brush the oil, the seasoning oil made by myself

0:07:48.625,0:07:52.150
抹好了之后就撒点孜然辣椒面什么的
Then we add some cumin and chili powder

0:07:52.425,0:07:53.675
可以了
Alright

0:07:54.475,0:07:55.525
先撒孜然
Cumin first

0:08:02.120,0:08:03.780
咿呀 有点好吃哦
Ya, quite tasty

0:08:04.680,0:08:05.800
好香哦
Smells so good

0:08:05.820,0:08:07.220
我也想吃
I also want to eat it

0:08:07.220,0:08:08.180
你也想吃啊
You also want to eat it?

0:08:08.480,0:08:11.200
等一下啊 爸爸给你留了一块没加辣的
Wait a minute. Daddy will leave you some without chili

0:08:27.120,0:08:28.120
好啦沺沺
Alright, Tian Tian

0:08:29.320,0:08:30.340
好香哦
It smells so good

0:08:34.920,0:08:35.740
好 可以
Alright, good

0:08:37.280,0:08:37.820
烫哦
It's hot

0:08:39.000,0:08:40.600
你先试一下烫不烫
Have a try if it's still hot

0:08:40.725,0:08:42.375
这个筋是不是可以吃的
Can we eat this tendon?

0:08:42.525,0:08:43.225
可以啊
Yeah

0:08:43.700,0:08:46.320
我都想用手弄来吃了
I even want to use my hands

0:08:47.140,0:08:48.320
我都想用手弄来吃了
I even want to use my hands

0:08:50.120,0:08:53.860
你掐不动啊老婆 来 这是筋
You can't tear it off, honey. Here, tendon

0:08:56.040,0:08:57.360
嗯 好吃
Hmm, good

0:09:01.550,0:09:02.925
漆二娃 来
Qi Erwa, come here

0:09:06.525,0:09:08.300
看都你一直在旁边吞口水
You've been drooling over there

0:09:08.525,0:09:10.625
漆二娃 这
Here, Qi Erwa

0:09:12.450,0:09:14.825
可不可以让我一个位置
Could you give me a position?

0:09:15.125,0:09:17.575
让你一个位置啊 来吧来吧
Give you a position? Come here, come

0:09:17.680,0:09:19.180
小心别戳到上面了
Careful, don't be poked

0:09:20.360,0:09:21.600
好香哦 好吃
It smells so good. So tasty

0:09:21.600,0:09:22.860
香是蛮香的
It's really tasty

0:09:26.325,0:09:27.775
这里这里
Here, here

0:09:27.920,0:09:32.220
那里撕不动撕这里 这一块也是（肉）你看
You can't tear it off. This part is also meat. Look!

0:09:35.540,0:09:40.120
好吃吧 这里你看这一坨都是好吃的
Tasty, isn't it? This part is all tasty

0:09:45.980,0:09:48.440
把这坨肉剁下来嘛四伯爷
Can we chop it off, uncle?

0:09:50.350,0:09:52.200
割下来哦 割它下来就是
- Slice it off?
- Just slice it

0:10:01.800,0:10:03.475
好脆啊这个筋
The tendon is crunchy

0:10:09.925,0:10:11.800
放下面就是
Just leave it there

0:10:12.700,0:10:16.100
好啦 我们取下来慢慢割着吃
Alright, let's slice it off and enjoy

0:10:16.350,0:10:17.700
本期视频就到这里啦
That's all for this video

0:10:18.050,0:10:19.875
有空的话你们在家也可以试一下
If you have time, you can try it at home

0:10:20.475,0:10:22.200
这个牛肉是要贵那么一点点
Beef is more expensive, though

0:10:23.275,0:10:24.100
好吃
It's tasty

0:10:24.100,0:10:25.375
好吃吗
Is it tasty?

0:10:25.425,0:10:25.925
嗯
Yeah

0:10:26.325,0:10:28.750
好好吃呀 妈妈爸爸
It is so tasty, mommy and daddy

0:10:28.850,0:10:30.100
那你多吃一点啊
Then you can enjoy more

0:10:30.175,0:10:32.025
那一块都是你的 不辣的
That piece is yours. It's not spicy
