### ISSUE TITLE
【美食作家王刚】豆腐煮泥鳅 - https://youtu.be/phD1ZfMaFJ8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#581]
【美食作家王刚】豆腐煮泥鳅 - https://youtu.be/phD1ZfMaFJ8
视频时长 2:56，预计发布时间为北京时间1月15日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.045,0:00:01.500
哈喽大家好我是王刚

0:00:01.500,0:00:02.915
本期视频我跟大家分享

0:00:03.260,0:00:04.420
豆腐煮泥鳅

0:00:04.780,0:00:07.080
首先我们准备鲜活的泥鳅半斤（250克）

0:00:07.080,0:00:09.520
泥鳅不能选择太小否则不好宰杀

0:00:11.020,0:00:12.420
下一步开始处理

0:00:14.960,0:00:16.900
首先将泥鳅放在菜板上

0:00:25.880,0:00:27.720
然后将泥鳅的头切下来

0:00:27.720,0:00:30.440
由于泥鳅表面黏液较多且比较滑

0:00:30.700,0:00:33.000
同学们切记这一步必须小心操作

0:00:33.360,0:00:36.000
切断泥鳅的头之后用菜刀将尾巴压住

0:00:36.140,0:00:39.100
然后用手反方向将腹部的内脏挤出来

0:00:44.175,0:00:46.240
最后将泥鳅头丢弃不用

0:00:46.240,0:00:47.820
下一步开始准备辅料

0:00:47.820,0:00:49.260
准备老豆腐一小块

0:00:49.265,0:00:52.205
将豆腐从中间切开之后切成厚片备用

0:00:56.600,0:00:59.000
准备生姜一小块切成姜片备用

0:01:00.960,0:01:03.140
准备小葱几根切成葱花备用

0:01:08.280,0:01:11.160
将切好的葱花放入盆中下一步开始制作

0:01:11.160,0:01:12.900
首先我们把锅烧热

0:01:12.900,0:01:14.880
锅烧热之后加入适量的底油

0:01:17.360,0:01:19.980
油温6成热之后在锅中加入一勺食用盐

0:01:23.600,0:01:26.420
然后将处理好的泥鳅下锅煎3分钟

0:01:26.420,0:01:29.180
同学们煎泥鳅的时候最好用锅盖挡住锅面

0:01:29.180,0:01:31.160
这样可以防止热油溅出伤人

0:01:32.320,0:01:34.540
中途将泥鳅翻面煎香煎黄

0:01:37.820,0:01:39.440
锅中再加入姜片爆香

0:01:48.160,0:01:50.340
三分钟之后再加入适量的热水

0:01:58.200,0:02:00.240
再加入切好的豆腐下锅

0:02:03.840,0:02:05.660
然后开大火烧开

0:02:05.660,0:02:08.100
大火烧开之后转中火煮5分钟

0:02:08.100,0:02:10.200
这一步的目的是把汤煮至浓白

0:02:14.740,0:02:16.460
五分钟之后开始调味

0:02:16.980,0:02:18.700
锅中加入食用盐一勺

0:02:19.820,0:02:21.120
加入胡椒粉半勺

0:02:24.960,0:02:27.040
调好味之后即可出锅上菜

0:02:31.080,0:02:33.740
一道营养丰富的豆腐煮泥鳅就制作完成

0:02:36.960,0:02:38.540
下面开始技术总结

0:02:38.540,0:02:42.100
第一，泥鳅最好现杀现做以保证汤鲜味美

0:02:42.160,0:02:48.960
第二，泥鳅的表面黏液比较多，宰杀的时候需要注意安全，嫌麻烦的同学可以交给摊主来处理

0:02:48.980,0:02:53.540
第三，此菜适合工作压力大的人群食用，具有一定的养生功能

0:02:53.540,0:02:55.640
豆腐煮泥鳅的技术总结完毕

**Comment by Hackerry** [comment]
认领
