### ISSUE TITLE
【美食作家王刚】水煮鸡片 - https://youtu.be/WKaGAprUGZ4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#588]
【美食作家王刚】水煮鸡片 - https://youtu.be/WKaGAprUGZ4
视频时长 6:26，预计发布时间为北京时间1月18日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.200,0:00:01.375
哈喽大家好 我是王刚

0:00:01.425,0:00:02.825
本期视频我和大家分享

0:00:03.025,0:00:04.175
水煮鸡片

0:00:04.550,0:00:07.075
首先我们准备新鲜的鸡胸肉二两（100克）

0:00:07.250,0:00:09.650
将鸡胸肉的筋膜去除干净备用

0:00:09.750,0:00:11.900
这一步的目的是提升菜品的口感

0:00:12.000,0:00:13.800
然后切碎备用

0:00:13.925,0:00:15.400
下一步开始处理

0:00:15.400,0:00:17.575
首先将鸡胸肉放入料理机

0:00:18.750,0:00:20.325
然后加入冰水100克

0:00:20.575,0:00:22.950
清水的量和鸡胸肉为1:1

0:00:23.075,0:00:24.625
加入食用盐3克

0:00:25.575,0:00:27.650
然后将鸡胸肉搅成肉泥

0:00:27.675,0:00:31.025
这一步必须加冰水降温否则肌纤维容易失去弹性

0:00:36.550,0:00:38.775
搅成肉泥之后下一步开始调试

0:00:41.575,0:00:43.525
盆中加入蛋清240克

0:00:46.075,0:00:48.700
拌匀之后顺着一个方向搅拌5分钟

0:00:48.700,0:00:51.375
同学们蛋清的量不能太多也不能太少

0:00:56.250,0:00:59.350
蛋清和鸡肉蓉拌均之后下一步开始调淀粉糊

0:01:00.175,0:01:02.575
盆中加入土豆淀粉240克

0:01:02.600,0:01:05.200
加入清水200克之后将淀粉拌匀备用

0:01:12.475,0:01:15.150
淀粉拌匀之后倒入鸡肉泥种拌匀备用

0:01:15.150,0:01:17.950
同学们配料的详细比列会在视频尾部

0:01:22.975,0:01:24.575
下一步开始准备辅料

0:01:25.200,0:01:26.975
准备绿豆芽150克

0:01:27.925,0:01:30.225
准备青蒜2根斜刀切成小段备用

0:01:34.875,0:01:36.800
准备适量的鲜菇撕开备用

0:01:42.375,0:01:44.600
准备适量的干辣椒剪成小节备用

0:01:48.975,0:01:50.850
碗中加入几颗青花椒备用

0:01:51.450,0:01:53.600
最后拍几颗大蒜剁成蒜末备用

0:01:57.050,0:01:58.375
下一步开始制作

0:01:58.825,0:02:00.350
首先我们把锅烧热

0:02:00.425,0:02:02.300
锅烧热之后加入小宽油

0:02:10.750,0:02:12.950
油温烧至大约70度之后即可（2成油温）

0:02:20.075,0:02:23.275
然后用炒勺少量多次的将鸡肉泥从锅边淋入

0:02:33.375,0:02:36.550
转小火将鸡片炸至飘起来之后捞出备用

0:02:36.875,0:02:38.950
同学们这一步必须保持低油温

0:02:39.025,0:02:40.700
否则容易将鸡片炸老  

0:03:17.700,0:03:20.400
再加入清水烧开之后将鸡片下锅焯水几秒钟

0:03:20.575,0:03:22.925
这一步的目的是减少鸡片中的油脂

0:03:39.300,0:03:40.825
焯好水之后倒出备用

0:03:43.600,0:03:45.700
锅中加入少许的底油烧热

0:03:46.150,0:03:49.350
油温烧热之后加入花椒辣椒和蒜末爆香

0:03:50.725,0:03:53.600
料头爆香之后加入豆芽等辅料炒至断生

0:03:59.850,0:04:02.175
中途加入食用盐和鸡精调味

0:04:10.000,0:04:12.125
调好味之后倒入碗中垫底备用

0:04:14.525,0:04:17.100
然后锅中再次加入适量的底油烧热

0:04:18.125,0:04:20.550
油温5成热之后加入料头爆香（干辣椒，花椒，蒜末）

0:04:25.275,0:04:29.025
料头爆香之后加入红油豆瓣酱15克炒香炒出红油

0:04:34.425,0:04:37.550
豆瓣酱炒香之后加入适量的清水开大火烧开、

0:04:47.175,0:04:48.975
大火烧开之后开始调味

0:04:49.600,0:04:51.300
锅中加入食用盐4克

0:04:52.425,0:04:53.725
加入鸡精2克

0:04:54.775,0:04:56.975
加入少许白糖和胡椒粉调味

0:05:00.575,0:05:03.375
最后将鸡片下锅小火煮1分钟煮至入味

0:05:13.475,0:05:15.900
1分钟之后将鸡片捞出放入盆中

0:05:26.625,0:05:28.275
下一步开始准备泼油

0:05:28.525,0:05:31.250
锅烧热之后加入适量的植物油烧至7成热

0:05:39.075,0:05:41.100
油温7成热之后盛出半勺

0:05:44.125,0:05:46.975
炒勺中加入剩余的花椒辣椒和蒜末炸香

0:05:47.025,0:05:49.550
料头炸香之后再泼在鸡片上面即可

0:05:53.275,0:05:56.600
一道口感爽嫩的水煮鸡片就制作完成

0:05:58.500,0:06:00.050
下面开始技术总结

0:06:00.100,0:06:04.700
第一，鸡胸肉中的筋膜必须去除干净，这样才能有效提升口感

0:06:04.825,0:06:08.775
第二，此菜最好用料理机搅拌这样更加细腻

0:06:08.825,0:06:23.450
第三，详细比列为：鸡肉100克加水100克加盐3克搅拌成肉泥，然后加蛋清240克和肉泥搅拌均匀，另外土豆淀粉240克加清水200克拌匀，最后用鸡肉泥和湿淀粉搅拌均匀即可

0:06:23.475,0:06:25.250
水煮鸡片的技术总结完毕

**Comment by Yibing-Du** [comment]
认领

**Comment by immoonancient** [comment]
已发布
