### ISSUE TITLE
[雪鱼探店] 保定牛肉罩饼 - https://youtu.be/gPVUXTlettc

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#59]
https://youtu.be/gPVUXTlettc

视频已于 8 月 14 日发布

**Comment by GUThe** [comment]
8/19 update，尚未上传

**Comment by immoonancient** [comment]
先 unassign 吧，开工再 assign

**Comment by shuaisoserious** [comment]
self assign babe

**Comment by shuaisoserious** [comment]
河北·保定
牛肉罩饼
罩饼在哪里拿
坐下点
这个罩饼前面是肉，后面是饼
就是一两肉，一两饼
你看它菜单上写的是 罩饼
前面是肉，后面是饼
 一罩一的牛肉罩饼是11块钱
一罩二的牛肉罩饼也是11块钱
只要肉一样，饼多加一两不要钱
菜单后面是热菜
我感觉很多的种类
很多的菜品都是我没有见过的
我要一个青豆炒牛柳
再要这个罩饼，要一个二罩二的把
二罩二的
一份？
对
先付钱还是待会再付钱
待会付钱还是现在付
待会
可以
等吃完了再付钱
谢谢
一个青豆炒牛柳，一个二罩二
对 对 对二罩二罩饼
我给你放下，你可以试一下
不是谁想端就端的 这个
因为太烫了
小心你的手
上来这个罩饼，我明白了
其实这家店，已经从一个小吃店
升级为一个饭店
连罩饼都是用盘子装的
上面就是二两的牛肉，下面罩了二两的饼
咱们要的是20块钱的二两（牛肉罩饼）
下面的饼是手撕的
现在有点泡囊了
上面是能看到纹理的牛肉
其实如果这么吃牛肉会有点干
所以把牛肉泡在汤里，口感更好一些
很多人来点餐的时候都会说
来个几罩几
我突然明白，他们好像说的是
用几两的牛肉 罩住几两的饼
就像这样
你把牛肉掀开就仿佛是牛肉罩住了饼
牛肉对饼说，兄弟我罩着你
吃起来有一种牛肉清香的味道
吃到半截 我发现了这个
辣椒
其实这个牛肉罩饼 很像牛肉汤的味道
没有很咸
如果说 觉得咸度不够的话
可以要一碗这样的辣椒
这个辣椒是鲜的 你看
鲜的青辣椒 蒜瓣这些东西泡出来的
它这个就是 鲜中带点辣
然后带点咸味
配牛肉罩饼 挺好的
不要觉得我今天来的地方很荒凉
但是这边真的有很多人来排队吃饭

**Comment by kdliu86** [comment]
#89
