### ISSUE TITLE
【美食作家王刚】烤鱼 - https://youtu.be/KtCwukbqPHQ

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#593]
【美食作家王刚】烤鱼 - https://youtu.be/KtCwukbqPHQ
视频时长 10:10，预计发布时间为北京时间1月21日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.750,0:00:01.550
哈喽大家好

0:00:01.675,0:00:05.050
这个我们昨天剩的两条鱼今天我们把它烤了

0:00:05.225,0:00:08.225
做烤鱼 炭火烤鱼

0:00:08.800,0:00:09.300
可以啊

0:00:10.625,0:00:12.425
我今天炭已经生好了

0:00:12.625,0:00:16.550
正好以前用的那个炉子放了很久也要用一下

0:00:26.650,0:00:29.050
我们一般做烤鱼都是从背上开

0:00:30.225,0:00:32.775
今下午你又干饱餐

0:00:37.425,0:00:38.300
倒了这个水

0:00:38.550,0:00:41.694
烤鱼改刀就随便有几刀就可以了

0:00:45.475,0:00:47.175
2条鱼都放得下

0:00:47.525,0:00:48.900
还可以哦  刚好

0:00:50.175,0:00:51.967
嘿 安逸得很

0:00:53.353,0:00:55.273
我们用这个架子把它夹起来烤

0:00:56.297,0:00:58.537
先放旁边 先弄配料

0:01:07.675,0:01:09.975
这个烤鱼你们想吃什么都可以放进去

0:01:11.084,0:01:13.300
洋葱基本上是用来垫底

0:01:13.901,0:01:15.384
垫底的话也可以用豆芽

0:01:18.609,0:01:20.685
大蒜切一刀都可以了

0:01:24.077,0:01:25.727
好 少放点嘛

0:01:25.838,0:01:26.654
少放点

0:01:28.266,0:01:29.323
你还是有喊辣的时候啊

0:01:29.879,0:01:31.862
那肯定的哦

0:01:34.272,0:01:35.180
加点花椒

0:01:36.589,0:01:37.701
花椒你到是吃得哦

0:01:37.775,0:01:39.749
那个嚼来吃都可以

0:01:39.944,0:01:40.926
那样子多放点

0:01:41.064,0:01:41.524
可以啊

0:01:43.818,0:01:46.534
这是你上次没吃完的火锅底料

0:01:46.874,0:01:47.892
可以弄点在里面噶

0:01:48.062,0:01:49.618
这是我们自己做的火锅底料

0:01:50.297,0:01:50.947
我的配方做的

0:01:51.541,0:01:53.097
一半都怕多了哦

0:01:53.154,0:01:56.322
2条（鱼）都嘛还有那么多配菜 是不是

0:02:02.772,0:02:04.299
闻到真的多香

0:02:10.664,0:02:13.125
你想吃香菜等会儿可以加点香菜进去

0:02:13.974,0:02:15.021
好 差不多了

0:02:15.388,0:02:16.973
现在先考鱼嘛

0:02:17.058,0:02:20.169
烤嘛烤嘛 把火点起

0:02:30.834,0:02:34.568
可以了 现在我们这个炭已经夹上来了

0:02:35.360,0:02:36.973
现在火力还比较大

0:02:38.925,0:02:40.141
我给你们分享一下

0:02:41.131,0:02:43.875
你一般在外面馆子里面吃烤鱼

0:02:44.130,0:02:46.449
凡是是20分钟以内上的鱼

0:02:46.732,0:02:48.854
都不是炭烤的 全是油炸的

0:02:49.985,0:02:52.616
我们这个烤鱼必须烤够40分钟

0:02:52.729,0:02:55.190
才能够把这个鱼烤干烤焦烤香

0:02:55.841,0:02:56.633
咦 你看

0:02:56.690,0:02:58.217
还在动

0:03:00.933,0:03:02.630
嘿嘿嘿 还安逸

0:03:05.205,0:03:06.110
还在闪（抖）

0:03:06.845,0:03:10.410
我们这个烤鱼一开始要大火烤猛火烤

0:03:10.834,0:03:13.012
把它的水份短时间内烤干

0:03:13.578,0:03:15.954
然后两面烤干了之后

0:03:16.124,0:03:20.437
再把炭火剥掉一些再小火慢慢的烤

0:03:23.140,0:03:24.243
咿呀 好烫噢

0:03:26.110,0:03:28.429
刚刚火力太大了我去了一些炭

0:03:28.854,0:03:30.777
现在只留了几块炭在这里

0:03:31.173,0:03:33.012
现在都有点金黄金黄的了

0:03:34.908,0:03:36.944
现在我们这个烤鱼已经烤了半个小时了

0:03:37.171,0:03:38.868
大家可以看一下现在这个

0:03:39.377,0:03:41.301
已经金黄金黄的了但是还是不够

0:03:41.810,0:03:45.884
烤来好吃下次我把我那只大公鸡杀来烤

0:03:46.958,0:03:49.674
大公鸡杀来烤了好吃我又杀鸭子来烤

0:03:53.125,0:03:54.710
好了 你看我们的这个鱼

0:03:54.992,0:03:56.379
已经烤得可以了

0:03:56.577,0:03:59.292
它的皮已经脆了你看这里它的尾巴

0:04:01.216,0:04:04.243
尾巴就是捏一下就可以全部糟了碎了

0:04:04.724,0:04:06.591
这个烤鱼的话才是烤到了位

0:04:06.958,0:04:08.628
现在这个时候来刷点油

0:04:10.919,0:04:16.039
刷油的话就是方便它粘上辣椒面孜然粉之类的

0:04:18.670,0:04:20.198
现在给它刷一下油

0:04:21.810,0:04:23.026
翻过来再刷一下

0:04:25.233,0:04:26.704
哦 中间燃了

0:04:27.722,0:04:30.579
这个油刷好了再放点这个孜然粉

0:04:31.485,0:04:32.701
撒孜然

0:04:33.437,0:04:36.265
油已经OK了

0:04:36.831,0:04:38.274
在撒点辣椒面

0:04:47.807,0:04:48.826
加不加花椒  四伯爷

0:04:48.882,0:04:50.891
要 咋子不加花椒呢

0:04:52.362,0:04:55.304
花椒加起那个味道才安逸

0:04:57.963,0:04:59.151
好 差不多了

0:05:00.056,0:05:01.527
一 二 三

0:05:03.705,0:05:05.431
嘿嘿 差一点翻在地上去了

0:05:05.572,0:05:06.845
不可能

0:05:09.306,0:05:12.192
听这个声音就能感觉到这个已经脆了

0:05:13.069,0:05:15.134
它要贴在上面是很正常的

0:05:15.360,0:05:17.425
因为这个鱼皮（已经烤焦了）

0:05:21.301,0:05:22.687
好 现在来炒这个

0:05:23.705,0:05:27.100
这个油我随便放点哈

0:05:27.496,0:05:29.193
好了好了差不多了

0:05:29.759,0:05:31.485
现在我们来炒这个料

0:05:31.994,0:05:37.001
当然烤鱼的话鱼越大这个油越多

0:05:37.538,0:05:39.773
其实这点油我觉得少了一点

0:05:39.971,0:05:41.951
2个鱼好多点嘛

0:05:43.422,0:05:44.158
够了

0:05:44.724,0:05:46.676
烤鱼就是油要多一点

0:05:53.719,0:05:54.794
这个就要慢慢爆

0:05:54.964,0:05:57.482
让它把这个料头爆香

0:05:57.652,0:05:59.236
到时候再放这个火锅底料

0:05:59.321,0:06:03.402
它这个大蒜起泡了就说明这个蒜油已经出来了

0:06:05.657,0:06:06.534
可以了

0:06:08.543,0:06:09.787
这个等它慢慢炒

0:06:17.510,0:06:20.565
 我们把这个炒化了加一点点水

0:06:21.103,0:06:23.309
如果有啤酒的就可以加一点啤酒

0:06:23.451,0:06:28.373
给它煮化调盐白糖啊这些味给它一调

0:06:28.514,0:06:30.947
调好之后再倒在哪个烤鱼盘里面

0:06:31.258,0:06:34.257
最后放在这个炭火上面慢慢烤

0:06:34.512,0:06:36.011
慢慢加热慢慢吃

0:06:36.435,0:06:38.953
吃完鱼之后可以加一点自己喜欢的菜

0:06:39.123,0:06:41.923
现在我们这个火锅底料已经炒香炒化了

0:06:42.178,0:06:43.932
加点这个水

0:06:47.213,0:06:50.381
这水不能加太多 加太多了就不香了

0:06:52.588,0:06:55.304
好 这个加了水之后开始调味

0:06:56.011,0:06:59.717
盐的话就一定要控制它的量不能太多

0:07:00.056,0:07:03.507
好 盐就是这么多大概的话3克左右

0:07:06.902,0:07:08.147
然后再加这个白糖

0:07:09.080,0:07:11.428
白糖大概是盐的两倍

0:07:14.229,0:07:15.813
然后少加点鸡精

0:07:16.633,0:07:18.331
大概1勺也是3克吧

0:07:20.650,0:07:23.649
然后把这个土豆跟香菇丢下去煮一下

0:07:30.523,0:07:32.277
现在我们这个汤汁已经熬好了

0:07:32.277,0:07:32.984
咸不咸

0:07:33.550,0:07:35.700
不咸吧 刚好合适

0:07:36.407,0:07:37.058
合适

0:07:37.284,0:07:40.480
等一下我们把这个烤鱼盘放在上面把这个汤汁倒进去就可以了

0:07:40.707,0:07:41.442
哎呀 好辣哦

0:07:41.782,0:07:42.432
辣吗

0:07:43.140,0:07:44.045
很辣很辣

0:07:44.752,0:07:46.308
我们这个下面是放的炭

0:07:46.732,0:07:50.127
所以这个就刚刚好这样子放进去

0:07:51.428,0:07:53.776
放进去了之后放洋葱

0:07:54.314,0:07:55.785
洋葱撒再这个上面

0:07:57.482,0:07:59.094
现在这个汤已经差不多了

0:07:59.858,0:08:01.555
我把这个汤淋上去

0:08:11.739,0:08:16.152
这个时候呢我们就撒这个葱段

0:08:17.114,0:08:20.113
然后把我们这个魔芋 魔芋是焯过水的

0:08:21.188,0:08:22.574
边吃边加

0:08:24.865,0:08:26.110
边吃边加进去

0:08:26.364,0:08:28.147
再把这个蒜苗撒在上面去

0:08:30.240,0:08:31.768
还有这个鱼腥草

0:08:31.852,0:08:33.635
我们四川人喜欢吃鱼腥草嘛

0:08:34.002,0:08:35.502
撒点鱼香草在这个上面

0:08:40.129,0:08:43.026
好 剩下的就交给时间把它慢慢煮开

0:08:55.983,0:08:57.086
味道很好吃

0:08:57.680,0:09:00.028
特别是这个鱼啊特别的香

0:09:00.537,0:09:02.065
这个土豆可能很好吃

0:09:02.517,0:09:03.705
土豆你尝一下嘛

0:09:06.393,0:09:08.712
这魔芋呀这些东西要煮一下

0:09:09.533,0:09:10.721
这土豆是脆的

0:09:10.947,0:09:11.903
 好吃噶 嗯

0:09:16.051,0:09:17.451
这个跟烤牛腿那个好吃哦

0:09:17.963,0:09:19.010
这个好吃点

0:09:19.314,0:09:20.240
这个好吃 嗯

0:09:20.315,0:09:21.371
这个还便宜点

0:09:22.261,0:09:23.632
这个吃起来味道都要安逸点

0:09:27.043,0:09:28.081
味道有一点点重

0:09:28.155,0:09:28.581
太辣了

0:09:29.193,0:09:29.860
不重啊

0:09:30.936,0:09:31.807
   辣味有一点点重

0:09:31.918,0:09:32.641
嗯 好吃

0:09:32.789,0:09:33.994
辣味要少一点

0:09:34.772,0:09:35.699
咿呀 好辣哦

0:09:40.352,0:09:41.853
吃还是好吃 吃魔芋

0:09:45.301,0:09:47.099
你们可以在家里面试一下

0:09:47.784,0:09:51.362
这个鱼非常的入味非常好吃

0:09:54.087,0:09:55.421
很简单就用火锅底料

0:09:56.607,0:09:59.845
加点调料料头把它爆香了加水煮

0:10:00.796,0:10:01.983
这个鱼皮才好吃

0:10:02.316,0:10:02.687
嗯

0:10:03.058,0:10:04.559
鱼皮煮起很好吃

0:10:04.708,0:10:05.783
这个皮子好吃的很

0:10:05.875,0:10:07.747
好啦 本期视频就到这里了

0:10:08.100,0:10:09.045
我们要慢慢吃了

**Comment by Hackerry** [comment]
不好意思，忘了 xD

**Comment by immoonancient** [comment]
已发布
