### ISSUE TITLE
[华农兄弟] 华农兄弟今天天气不错山上搞点野果来吃一树都是 - https://youtu.be/QO8u-0TLODU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#599]
https://youtu.be/QO8u-0TLODU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 21, 2020 at 06:57PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload

#https://youtu.be/QO8u-0TLODU

#华农兄弟：今天天气不错，山上搞点野果来吃，一树都是
#Huanong Brothers: The weather is nice today. We get some wild fruits on the hill. They're all over the tree.

0:00:00.000,0:00:03.460
# 大家好  今天天氣很好哦  我上山上看一下有甚麼
Hi everyone! The weather is very nice today. I'm going onto the hill and see if there's anything,

0:00:03.480,0:00:05.640
# 東西可以摘  摘回來的
that I can take, take home.

0:00:05.980,0:00:07.000
# 就從這裡上去
We're heading up this way.

0:00:09.960,0:00:13.660
# 你看  兄弟的板車都放在這裡  不知道他想拉甚麼東西
Look! My buddy has put his cart here. Who knows what he wants to take.

0:00:14.380,0:00:15.260
# 哎喲
Ayo!

0:00:20.720,0:00:25.420
# 你看  這裡  荒無人煙哦 一年都沒人來過啦  只有我們來
Look! Here is completely deserted. No one has been here for the whole year, except us.

0:00:26.260,0:00:27.200
# 別人都不敢來
Nobody dares to come.

0:00:28.120,0:00:29.080
# 全是草
I see only grass,

0:00:29.480,0:00:30.340
# 路都看不到了
but no path.

0:00:47.960,0:00:51.140
# 你看  終於到啦  這棵樹  年年都很多的
Look! We're here finally. This tree, has a lot of fruits every year.

0:00:53.020,0:00:54.700
# 這樹上 直接可以上去哦
This tree, I can just climb it right away.

0:00:56.960,0:00:58.700
# 哇呀  哎呀
Waha! Aya!

0:00:59.580,0:01:00.080
# 哎呀
Oiya!

0:01:01.060,0:01:01.800
# 那麼多
There are so many.

0:01:04.160,0:01:06.860
# 你看這樹上  好多啊  下面看不到
Look! There are so many on the tree. I can't see them down there.

0:01:07.320,0:01:09.180
# 一上來的話  你看  一樹都是
Once I'm here, look, they're all over the tree.

0:01:10.480,0:01:11.700
# 這  竹節果
This, wild mangosteen,

0:01:12.300,0:01:13.200
# 身材好好哦
looks really attractive.

0:01:14.740,0:01:15.300
# 又大
And it's big.

0:01:16.700,0:01:18.740
# 不像  去年的都是那麼小的
It's not like, last year, when they were so tiny.

0:01:19.500,0:01:21.960
# 今年大部份都有那麼大  還有更大的嘞
They are mostly that big this year. There are some even bigger.

0:01:23.660,0:01:24.280
# 就是
It's like...

0:01:25.840,0:01:27.220
# 涼風颼颼的
cooling breeze.

0:01:28.580,0:01:29.100
# 你看
Look!

0:01:29.760,0:01:30.760
# 這邊好多啊
Here are a lot!

0:01:34.260,0:01:35.280
# 看這個果肉
Have a look at the pulp!

0:01:36.840,0:01:38.160
# 口水都流出來了
I'm already drooling.

0:01:46.480,0:01:47.460
# 這裡有個壞的
It's rotten here.

0:01:51.820,0:01:52.560
# 好酸
Really sour!

0:01:53.500,0:01:54.620
# 酸中帶甜  (註︰救命，這堆廢話有更好的譯法嗎？)
Sour but sweet

0:01:55.060,0:01:56.060
# 甜中帶酸
Sweet but sour

0:01:59.060,0:02:00.140
# 就是酸酸甜甜
And it means sweet and sour.

0:02:04.060,0:02:05.560
# 你看  那籽很大的哦
Look! The seed is huge.

0:02:06.280,0:02:07.000
# 這肉很少
There's not so much to eat.

0:02:07.760,0:02:08.540
# 但吃起來
But it tastes really not bad,

0:02:09.300,0:02:10.140
# 味道很不錯
when it's in your mouth.

0:02:12.440,0:02:12.940
# 你看
Look!

0:02:13.140,0:02:14.180
# 碩果纍纍
I't's so fruitful.

0:02:15.880,0:02:16.800
# 這裡有個壞的
Here's a rotten one.

0:02:20.340,0:02:22.300
# 一串一串的哦  很漂亮吧
They're in bunches. Pretty, aren't they?

0:02:23.500,0:02:25.060
# 嘗一下這個最大個的來吃一下
Let me pick this biggest one and have a try.

0:02:29.800,0:02:30.340
# 嗯
Um!

0:02:31.900,0:02:33.020
# 大一點就好吃一點
Bigger means tastier.

0:02:45.320,0:02:46.060
# 這個不錯
This one is not bad.

0:02:56.560,0:03:00.440
# 這棵樹摘的差不多啦  不要摘乾淨啦  留給鳥過冬
I think we have enough from this tree. We can't take everything. We need to leave some to the birds for the winter.

0:03:01.120,0:03:02.420
# 我們上面那棵樹再摘
Let's move on to the tree up there.

0:03:06.640,0:03:09.660
# 哇  這棵樹  這個  有幾個好黃的哦 (註︰用yellow感覺有點怪，我通常盡量避免)
Wa! This tree, this one, there are several golden yellow ones.

0:03:10.620,0:03:11.520
# 你看  這個
Look! This one is,

0:03:12.340,0:03:13.280
# 婀娜多姿
flirtatious!

0:03:13.600,0:03:14.480
# 很漂亮的哦
It's really pretty!

0:03:20.260,0:03:20.820
# 誒呦
Eyo!

0:03:21.780,0:03:22.580
# 大好勾哦
I can't hook it.

0:03:24.260,0:03:24.800
# 唉
Ay!

0:03:25.420,0:03:26.740
# 恨自己長得太矮了
It's a shame that I'm too short.

0:03:47.300,0:03:48.140
# 就那麼幾個
Just a couple of them,

0:03:49.220,0:03:49.960
# 還有個壞的
and one is rotten.

0:03:51.640,0:03:52.140
# 你看
Look!

0:03:52.800,0:03:53.900
# 就摘了那麼一點點
So we have just a tiny little bit here.

0:03:54.940,0:03:55.440
# 大少啦
It's too few.

0:03:56.600,0:03:57.460
# 天氣快黑啦
It's getting dark very soon.

0:03:57.940,0:04:01.020
# 我要回去啦  下次我叫兄弟過來  幫忙摘
I need to go back now. Next time, I'll ask my buddy to come, and pick with us.

0:04:04.500,0:04:05.940
# 誒呦  那麼重啦
Eyo! It's so heavy!

0:04:15.380,0:04:18.080
# 你看  這路邊上還有一棵哦
Look! Here's one more tree on the road side.

0:04:18.780,0:04:20.580
# 剛  剛好在回家的路上
It's right, right on our way back home.

0:04:21.560,0:04:22.460
# 順便就把它給
Why don't we simply,

0:04:22.840,0:04:23.420
# 摘掉
pick them?

0:04:26.200,0:04:27.460
# 這棵樹太小啦
This tree is too small.

0:04:30.300,0:04:31.720
# 上都上去怎麼摘
How can I pick when I can't even climb the tree?

0:04:41.820,0:04:44.440
# 你看  這個很黃哦  很大的哦
Look! This one looks really nice, and it's very big!

0:04:47.260,0:04:49.380
# 你看  這些都是  誒呦 掉了一顆
Look! These are all...Eyo! I dropped one.

0:04:50.380,0:04:51.080
# 浪費了
What a waste!

0:05:09.980,0:05:10.900
# 好啦 沒啦
Alright! That's it!

0:05:19.240,0:05:20.300
# 樹都被我壓爛
I broke some branches.

0:05:53.860,0:05:55.640
# 你看  這個都摘回來啦  去去去 (註︰這個「去」只是趕狗聲)
Look! I've brought them all back. Chu chu chu!

0:05:56.520,0:06:00.260
# 去去去  走開  你們走開  這些不是你們吃的
Chu chu chu! Go 'way! You guys go 'way! These are not for you!

0:06:01.420,0:06:02.920
# 你看  摘了一籮筐
Look! We've picked one basket here,

0:06:03.860,0:06:04.680
# 就那麼一點點
just a tiny little bit.

0:06:05.620,0:06:07.260
# 你看  又大又黃的  這個
Look! This is big and golden yellow.

0:06:07.600,0:06:08.320
# 很靚的哦
It's so beautiful!

0:06:09.420,0:06:11.160
# 這樣的竹節果是最好吃的  這個
A wild mangosteen like this one tastes the best, this one.

0:06:11.960,0:06:12.940
# 到成熟期啦
It's now the season.

0:06:15.980,0:06:17.740
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:06:18.280,0:06:19.440
# 明天叫兄弟過來一起吃
I'll ask my buddy to come and enjoy with us tomorrow.

**Comment by vincenthychow** [comment]
已發佈
