### ISSUE TITLE
【雪鱼】澳门叉烧饭-https://youtu.be/HUivD-npjEQ

### ISSUE THREAD

**Issue by okiamnewhere** [immoonancient/YTSubtitles#600]
【雪鱼】澳门叉烧饭-https://youtu.be/HUivD-npjEQ
发布日期：北京时间2020年1月21日 21:00
标题：在澳门吃70元的叉烧饭，肉给得直冒尖，路人看着都想来一份！实惠
简介：我是雪鱼，带你一起踏上寻味之旅。对澳门的美食觊觎已久，这次终于来到心心念念的澳门，刚下车就来到一家烧腊店，听阿姨说已经有50年历史了，门牌特别小，但是顾客特别多。很多人都是没开门就在这排队！店里的品种很少，只卖3种肉，分别是蜜汁叉烧、猪蹄、油鸡，切好的肉直接盖在米饭上，热气腾腾的很诱人。份量很大，一份的价格是70mop，在澳门来讲，还是很实惠的。
地址：澳门缆厂巷6号芬记烧腊
营业时间：周一至周五11:00-13:00
字幕：
1
00:00:01,980 --> 00:00:03,300
雪鱼现在在澳门
I'm in Macau right now

2
00:00:03,440 --> 00:00:06,020
今天中午我们将要去一家叉烧店
We are going to a char siu shop later today

3
00:00:06,060 --> 00:00:08,580
你看 我们还没有放下书包
See, we haven't even dropped our bags yet

4
00:00:08,580 --> 00:00:11,260
就来吃这个叉烧
We came to this shop straight away

5
00:00:11,260 --> 00:00:12,540
他们这边是11点营业
This shop opens at 11 am

6
00:00:12,540 --> 00:00:14,460
但是现在是10点半
But it's only 10:30 am now 

7
00:00:14,460 --> 00:00:17,700
已经有很多人在排队等待
Yet you can see many people queuing up for it

8
00:00:18,620 --> 00:00:20,620
路人心理：这边在排队买什么
Passer-by: what are they queuing up for?

9
00:00:23,940 --> 00:00:27,020
开门啦
It's opening!

10
00:00:32,700 --> 00:00:35,140
转眼间 好多人
So many people in a blink of an eye 

11
00:00:35,900 --> 00:00:37,340
这么有吸引力的一家店
Such a popular shop 

12
00:00:37,340 --> 00:00:38,620
并没有很大的来头
doesn't have a big story behind it

13
00:00:38,620 --> 00:00:41,780
它由一对老夫妻 默默经营着
It's managed and ran by an old couple 

14
00:00:42,300 --> 00:00:44,620
一位只负责和食材进行交流
One of them deal with all the ingredients 

15
00:00:44,620 --> 00:00:45,860
手起刀落间
With his knife in hand,

16
00:00:45,860 --> 00:00:50,180
要保证每一份米饭上的肉份量足够
he has to make sure there's enough meat on each serving of rice 

17
00:00:53,180 --> 00:00:54,660
拿不准分量的时候
When he can't tell the amount,

18
00:00:54,660 --> 00:00:57,900
还是习惯于借助 抬头就能得到的小秤
He uses the small scale right in front of him

19
00:01:11,820 --> 00:01:14,020
另一位呢 当然就是我们眼前这位
And of course, the other one is  

20
00:01:14,020 --> 00:01:15,100
爱笑的阿姨
this auntie who smiles all the time

21
00:01:15,100 --> 00:01:18,460
和顾客间交流的重任 就落在了她的身上
The responsibility of communicating with customers falls on her shoulder

22
00:01:19,940 --> 00:01:22,700
那什么是 比三色饭 中的比
What is the "Bi" in "Bi San Se Fan" (Chicken drumstick three-color rice) 

23
00:01:22,700 --> 00:01:23,640
比就是鸡腿
Bi is chicken drumstick

24
00:01:23,700 --> 00:01:27,100
叉烧 油鸡腿 熏蹄
Char-siu, soy-sauce braised chicken drumstick and smoked pork trotter

25
00:01:27,100 --> 00:01:29,980
广东人叫 比就是鸡腿
In Cantonese, Bi means chicken drumstick

26
00:01:33,740 --> 00:01:35,660
看到这儿 大家也能够发现
Now you all can see that

27
00:01:35,660 --> 00:01:37,580
叔叔呢 就是比较内向
Uncle is more of an introvert 

28
00:01:37,580 --> 00:01:40,740
阿姨在这边就是比较活泼开朗
whereas untie is more active and outgoing 

29
00:01:40,740 --> 00:01:42,220
两个人相互配合
Two of them helping each other

30
00:01:42,220 --> 00:01:44,460
感觉生活也很有乐趣
makes life a lot happier 

31
00:02:19,780 --> 00:02:21,640
这个有吗 三色的
Do we still have this? The three-color one?

32
00:02:21,640 --> 00:02:23,540
三色饭 要一个吗
Would you like a three-color rice?

33
00:02:23,900 --> 00:02:25,460
3 个
Three of those

34
00:02:26,180 --> 00:02:29,460
70元一个 你要3个吗
It's 70 yuan each, you want 3 of those?

35
00:02:40,140 --> 00:02:41,980
你刚才还说要一个鸡吗
Did you say you want a chicken?

36
00:02:41,980 --> 00:02:44,540
不要鸡我还可以退钱给你 吃不了
I can give you a refund on the chicken, you can't finish them all

37
00:02:50,540 --> 00:02:52,860
昨天来都卖完了
It was all sold out yesterday afternoon

38
00:02:52,860 --> 00:02:56,820
是啊 昨天我们下午就没有开了
Yeah, we closed in the afternoon on yesterday 

39
00:02:56,820 --> 00:02:59,140
香葱 酱油能吃吗
Any scallions and soy sauce?

40
00:02:59,320 --> 00:03:01,320
要
Yes please

41
00:03:05,500 --> 00:03:07,820
一个三色饭
Can I have a three-color rice

42
00:03:09,020 --> 00:03:11,860
外带你知道的
Take-away you know that

43
00:03:14,020 --> 00:03:15,220
蘸料是什么
What's the dipping sauce?

44
00:03:15,220 --> 00:03:17,180
不 我告诉她作料
Nah I'll tell her (PLZ HELP HERE)

45
00:03:36,700 --> 00:03:39,260
我们接下来要找地方吃饭
Next we'll find a place to eat this

46
00:03:39,260 --> 00:03:41,820
因为这边是不提供堂食的
As you can't dine-in here

47
00:03:57,620 --> 00:03:59,340
哇
Wow

48
00:04:05,980 --> 00:04:08,020
这三种肉 放在上面
With these three types of meat on top 

49
00:04:08,020 --> 00:04:09,620
已经充满了整个盒子
It has already filled up the entire box

50
00:04:09,620 --> 00:04:12,460
米饭 你不扒拉一下 都看不到米饭
You can't even see the rice if you don't move the meats to the side

51
00:04:12,460 --> 00:04:15,300
排队排了这么久 拿到这么沉甸甸的饭
We've lined up for such a long time to get this rice 

52
00:04:15,300 --> 00:04:17,180
也是觉得值得了
But I think it's still worth the wait

53
00:04:17,180 --> 00:04:20,220
我觉得这里面最诱人的就是叉烧
Personally I think Char-siu is the most attractive one

54
00:04:20,220 --> 00:04:22,460
我们找一个稍微瘦一点的吧
Let's find one that's a bit leaner

55
00:04:22,460 --> 00:04:24,860
它这个叉烧不仅颜色好看
Not only does this Char-siu look good

56
00:04:24,860 --> 00:04:30,100
而且 你能看到流下来的蜜汁尤其诱人
but you can see the honey glazing that's dripping down extremely attractive 

57
00:04:31,580 --> 00:04:36,420
叉烧 肉质紧实
Char-siu with a firm texture

58
00:04:37,100 --> 00:04:41,020
而且吃一口 是肉香中带有一些甜的味道
And you can taste a hint of sweetness within the aroma of meat

59
00:04:41,020 --> 00:04:43,580
还有就是这个叉烧汁 流到米饭上
Also with the Char-siu sauce that's on the rice 

60
00:04:43,580 --> 00:04:44,780
拌饭特别好
Taste really good once stirred with rice

61
00:04:47,020 --> 00:04:49,060
这份鸡肉 虽然叫油鸡（酱油鸡）
Although the chicken is called oil chicken (Soy-sauce chicken)

62
00:04:49,060 --> 00:04:51,020
但是吃起来并没有很油腻
It doesn't taste greasy at all

63
00:04:51,020 --> 00:04:53,460
反而是这种水分比较多一些
In stead, it's fairly juicy 

64
00:04:53,460 --> 00:04:54,460
看颜色也知道
You can tell by the color of it

65
00:04:54,460 --> 00:04:57,780
它是有点嚼劲 有点脆的
It's a little chewy and crunchy (PLZ HELP HERE)

66
00:04:57,780 --> 00:05:00,500
这里面最咸的就是熏蹄
And the most salty one of all three

67
00:05:00,500 --> 00:05:03,820
五香味还有肉味特别浓重
has a strong smell of five-spice and meat

68
00:05:06,500 --> 00:05:08,300
吃这个饭就是 你随便
With this rice, you can just randomly 

69
00:05:08,300 --> 00:05:10,020
一找 一夹都是肉
All you can see or find is meat

70
00:05:10,940 --> 00:05:15,180
在这大马路上 我拿着这么一个沉甸甸的盒饭
Standing on the street with such heavy box of rice

71
00:05:15,180 --> 00:05:19,940
瞬间感觉 我就是这条街最富有的人
Right now I feel like I'm the richest person on the street

72
00:05:19,940 --> 00:05:23,060
很多路过的人 看着我的饭都说 哎这饭不错哦
Many people that walked passed me looked at my rice and said wow that looks good

73
00:05:23,420 --> 00:05:25,460
当然不错啦 哈哈
Of course it's good haha

**Comment by max-sun-hongyi** [comment]
Ready to be reviewed @xiaochengh

**Comment by immoonancient** [comment]
bot, please upload

1
00:00:01,980 --> 00:00:03,300
雪鱼现在在澳门
I'm in Macau right now

2
00:00:03,440 --> 00:00:06,020
今天中午我们将要去一家叉烧店
We are going to a char siu shop later today

3
00:00:06,060 --> 00:00:08,580
你看 我们还没有放下书包
See, we haven't even dropped our bags yet

4
00:00:08,580 --> 00:00:11,260
就来吃这个叉烧
We came to this shop straight away

5
00:00:11,260 --> 00:00:12,540
他们这边是11点营业
This shop opens at 11 am

6
00:00:12,540 --> 00:00:14,460
但是现在是10点半
But it's only 10:30 am now

7
00:00:14,460 --> 00:00:17,700
已经有很多人在排队等待
Yet you can see many people queuing up for it

8
00:00:18,620 --> 00:00:20,620
路人心理：这边在排队买什么
Passer-by: what are they queuing up for?

9
00:00:23,940 --> 00:00:27,020
开门啦
It's opening!

10
00:00:32,700 --> 00:00:35,140
转眼间 好多人
So many people in a blink of an eye

11
00:00:35,900 --> 00:00:37,340
这么有吸引力的一家店
Such a popular shop

12
00:00:37,340 --> 00:00:38,620
并没有很大的来头
doesn't have a big story behind it

13
00:00:38,620 --> 00:00:41,780
它由一对老夫妻 默默经营着
It's managed and ran by an old couple

14
00:00:42,300 --> 00:00:44,620
一位只负责和食材进行交流
One of them deal with all the ingredients

15
00:00:44,620 --> 00:00:45,860
手起刀落间
With his knife in hand,

16
00:00:45,860 --> 00:00:50,180
要保证每一份米饭上的肉份量足够
he has to make sure there's enough meat on each serving of rice

17
00:00:53,180 --> 00:00:54,660
拿不准分量的时候
When he can't tell the amount,

18
00:00:54,660 --> 00:00:57,900
还是习惯于借助 抬头就能得到的小秤
He uses the small scale right in front of him

19
00:01:11,820 --> 00:01:14,020
另一位呢 当然就是我们眼前这位
And of course, the other one is

20
00:01:14,020 --> 00:01:15,100
爱笑的阿姨
this auntie who smiles all the time

21
00:01:15,100 --> 00:01:18,460
和顾客间交流的重任 就落在了她的身上
The responsibility of communicating with customers falls on her shoulder

22
00:01:19,940 --> 00:01:22,700
那什么是 比三色饭 中的比
What is the "Bi" in "Bi San Se Fan" (Chicken drumstick three-color rice)

23
00:01:22,700 --> 00:01:23,640
比就是鸡腿
Bi is chicken drumstick

24
00:01:23,700 --> 00:01:27,100
叉烧 油鸡腿 熏蹄
Char-siu, soy-sauce braised chicken drumstick and smoked pork trotter

25
00:01:27,100 --> 00:01:29,980
广东人叫 比就是鸡腿
In Cantonese, Bi means chicken drumstick

26
00:01:33,740 --> 00:01:35,660
看到这儿 大家也能够发现
Now you all can see that

27
00:01:35,660 --> 00:01:37,580
叔叔呢 就是比较内向
Uncle is more of an introvert

28
00:01:37,580 --> 00:01:40,740
阿姨在这边就是比较活泼开朗
whereas untie is more active and outgoing

29
00:01:40,740 --> 00:01:42,220
两个人相互配合
Two of them helping each other

30
00:01:42,220 --> 00:01:44,460
感觉生活也很有乐趣
makes life a lot happier

31
00:02:19,780 --> 00:02:21,640
这个有吗 三色的
Do we still have this? The three-color one?

32
00:02:21,640 --> 00:02:23,540
三色饭 要一个吗
Would you like a three-color rice?

33
00:02:23,900 --> 00:02:25,460
3 个
Three of those

34
00:02:26,180 --> 00:02:29,460
70元一个 你要3个吗
It's 70 yuan each, you want 3 of those?

35
00:02:40,140 --> 00:02:41,980
你刚才还说要一个鸡吗
Did you say you want a chicken?

36
00:02:41,980 --> 00:02:44,540
不要鸡我还可以退钱给你 吃不了
I can give you a refund on the chicken, you can't finish them all

37
00:02:50,540 --> 00:02:52,860
昨天来都卖完了
It was all sold out yesterday afternoon

38
00:02:52,860 --> 00:02:56,820
是啊 昨天我们下午就没有开了
Yeah, we closed in the afternoon on yesterday

39
00:02:56,820 --> 00:02:59,140
香葱 酱油能吃吗
Any scallions and soy sauce?

40
00:02:59,320 --> 00:03:01,320
要
Yes please

41
00:03:05,500 --> 00:03:07,820
一个三色饭
Can I have a three-color rice

42
00:03:09,020 --> 00:03:11,860
外带你知道的
Take-away you know that

43
00:03:14,020 --> 00:03:15,220
蘸料是什么
What's the dipping sauce?

44
00:03:15,220 --> 00:03:17,180
不 我告诉她作料
Nah I'll tell her (PLZ HELP HERE)

45
00:03:36,700 --> 00:03:39,260
我们接下来要找地方吃饭
Next we'll find a place to eat this

46
00:03:39,260 --> 00:03:41,820
因为这边是不提供堂食的
As you can't dine-in here

47
00:03:57,620 --> 00:03:59,340
哇
Wow

48
00:04:05,980 --> 00:04:08,020
这三种肉 放在上面
With these three types of meat on top

49
00:04:08,020 --> 00:04:09,620
已经充满了整个盒子
It has already filled up the entire box

50
00:04:09,620 --> 00:04:12,460
米饭 你不扒拉一下 都看不到米饭
You can't even see the rice if you don't move the meats to the side

51
00:04:12,460 --> 00:04:15,300
排队排了这么久 拿到这么沉甸甸的饭
We've lined up for such a long time to get this rice

52
00:04:15,300 --> 00:04:17,180
也是觉得值得了
But I think it's still worth the wait

53
00:04:17,180 --> 00:04:20,220
我觉得这里面最诱人的就是叉烧
Personally I think Char-siu is the most attractive one

54
00:04:20,220 --> 00:04:22,460
我们找一个稍微瘦一点的吧
Let's find one that's a bit leaner

55
00:04:22,460 --> 00:04:24,860
它这个叉烧不仅颜色好看
Not only does this Char-siu look good

56
00:04:24,860 --> 00:04:30,100
而且 你能看到流下来的蜜汁尤其诱人
but you can see the honey glazing that's dripping down extremely attractive

57
00:04:31,580 --> 00:04:36,420
叉烧 肉质紧实
Char-siu with a firm texture

58
00:04:37,100 --> 00:04:41,020
而且吃一口 是肉香中带有一些甜的味道
And you can taste a hint of sweetness within the aroma of meat

59
00:04:41,020 --> 00:04:43,580
还有就是这个叉烧汁 流到米饭上
Also with the Char-siu sauce that's on the rice

60
00:04:43,580 --> 00:04:44,780
拌饭特别好
Taste really good once stirred with rice

61
00:04:47,020 --> 00:04:49,060
这份鸡肉 虽然叫油鸡（酱油鸡）
Although the chicken is called oil chicken (Soy-sauce chicken)

62
00:04:49,060 --> 00:04:51,020
但是吃起来并没有很油腻
It doesn't taste greasy at all

63
00:04:51,020 --> 00:04:53,460
反而是这种水分比较多一些
In stead, it's fairly juicy

64
00:04:53,460 --> 00:04:54,460
看颜色也知道
You can tell by the color of it

65
00:04:54,460 --> 00:04:57,780
它是有点嚼劲 有点脆的
It's a little chewy and crunchy (PLZ HELP HERE)

66
00:04:57,780 --> 00:05:00,500
这里面最咸的就是熏蹄
And the most salty one of all three

67
00:05:00,500 --> 00:05:03,820
五香味还有肉味特别浓重
has a strong smell of five-spice and meat

68
00:05:06,500 --> 00:05:08,300
吃这个饭就是 你随便
With this rice, you can just randomly

69
00:05:08,300 --> 00:05:10,020
一找 一夹都是肉
All you can see or find is meat

70
00:05:10,940 --> 00:05:15,180
在这大马路上 我拿着这么一个沉甸甸的盒饭
Standing on the street with such heavy box of rice

71
00:05:15,180 --> 00:05:19,940
瞬间感觉 我就是这条街最富有的人
Right now I feel like I'm the richest person on the street

72
00:05:19,940 --> 00:05:23,060
很多路过的人 看着我的饭都说 哎这饭不错哦
Many people that walked passed me looked at my rice and said wow that looks good

73
00:05:23,420 --> 00:05:25,460
当然不错啦 哈哈
Of course it's good haha
