### ISSUE TITLE
【美食作家王刚】年终总结报菜名 - https://youtu.be/1x8wUJsA0oI

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#602]
【美食作家王刚】年终总结报菜名 - https://youtu.be/1x8wUJsA0oI
视频时长 2:30，预计发布时间为北京时间1月24日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.175,0:00:01.280
哈喽大家好我是王刚

0:00:01.280,0:00:02.950
本期视频我给大家分享

0:00:02.950,0:00:04.500
年终总结报菜名

0:00:05.000,0:00:06.100
松鼠鱼

0:00:06.250,0:00:07.700
麻辣牛油火锅

0:00:08.000,0:00:09.150
汆水丸子

0:00:09.725,0:00:10.775
椒香鲤鱼

0:00:11.225,0:00:12.325
鱼丸火锅

0:00:12.725,0:00:14.000
腊味合蒸

0:00:14.150,0:00:16.050
麻辣火锅底料的极速版本

0:00:16.550,0:00:17.675
麻辣香肠

0:00:18.325,0:00:19.450
青椒牛肉丝

0:00:19.875,0:00:20.975
碎炒羊肉

0:00:21.400,0:00:22.675
玉米排骨汤

0:00:23.350,0:00:24.475
炝炒包菜

0:00:24.875,0:00:26.100
风味茄子

0:00:26.300,0:00:27.550
椒香腰片

0:00:28.000,0:00:29.125
冷吃兔

0:00:29.850,0:00:31.175
酸菜黄骨鱼

0:00:31.650,0:00:32.975
脆青瓜炒肉

0:00:33.400,0:00:34.600
口味猪肝

0:00:35.050,0:00:36.375
砂锅豆腐

0:00:36.675,0:00:38.225
蒜蓉粉丝蒸花甲

0:00:38.475,0:00:39.750
鲜虾蒸蛋

0:00:40.075,0:00:41.475
盐烧鲈鱼

0:00:41.700,0:00:43.125
冷吃杏鲍菇

0:00:43.500,0:00:45.100
蒜蓉粉丝蒸娃娃菜

0:00:45.175,0:00:46.425
生焖鱼头

0:00:46.675,0:00:47.925
辣炒鸡爪

0:00:48.150,0:00:49.275
爱心山药

0:00:49.550,0:00:50.825
辣炒田螺

0:00:51.000,0:00:52.175
冷吃串串

0:00:52.400,0:00:53.525
藿香鳝鱼

0:00:53.850,0:00:55.075
小葱煎鸡蛋

0:00:55.350,0:00:56.650
清蒸小龙虾

0:00:57.050,0:00:58.300
大蒜烧鲶鱼

0:00:58.525,0:00:59.675
拔丝红薯

0:00:59.900,0:01:01.100
干煎带鱼

0:01:01.525,0:01:02.950
青椒炒鸡丁

0:01:03.125,0:01:04.375
红烧鲟鱼

0:01:04.650,0:01:05.950
虎皮青椒

0:01:06.150,0:01:07.275
烤鸡架

0:01:07.400,0:01:08.400
卤牛肉

0:01:08.700,0:01:09.825
小炒白豆角

0:01:10.100,0:01:11.225
青椒豆豉酱

0:01:11.550,0:01:12.625
麻婆豆腐

0:01:12.975,0:01:14.000
青椒爆甲鱼

0:01:14.250,0:01:15.375
肉末烧茄子

0:01:15.525,0:01:16.625
鲜椒茄猫儿

0:01:17.125,0:01:18.050
小炒木耳

0:01:18.400,0:01:19.450
拔丝土豆

0:01:19.850,0:01:20.800
甲鱼汤

0:01:21.250,0:01:22.200
炒猪肝

0:01:22.550,0:01:23.825
鲍鱼汁蒸排骨

0:01:24.150,0:01:25.150
柴火鸡

0:01:25.675,0:01:26.775
鸡丝凉面

0:01:27.125,0:01:28.250
酱油炒饭

0:01:28.650,0:01:29.675
盘龙茄子

0:01:30.100,0:01:31.300
盐焗海鲜

0:01:31.500,0:01:32.400
炸蜂蛹

0:01:32.900,0:01:34.050
竹笋烧竹鼠

0:01:34.275,0:01:35.275
葱烧鲫鱼

0:01:35.700,0:01:36.800
川味牛肉面

0:01:37.050,0:01:38.050
烤竹鼠

0:01:38.375,0:01:39.475
凉拌茄子

0:01:39.675,0:01:40.650
烧牛腩

0:01:41.175,0:01:42.300
红烧牛鞭

0:01:42.550,0:01:43.775
土豆裹香蕉

0:01:44.025,0:01:45.100
可乐鸡翅

0:01:45.450,0:01:46.400
烤羊肉

0:01:46.825,0:01:47.875
美蛙鱼头

0:01:48.025,0:01:49.075
蜂窝玉米

0:01:49.250,0:01:50.350
木须肉

0:01:50.500,0:01:51.775
烤野猪

0:01:51.975,0:01:53.250
干炸肉丸

0:01:53.600,0:01:54.800
黄焖土鸡

0:01:54.925,0:01:56.050
琥珀核桃

0:01:56.200,0:01:57.000
粑粑肉

0:01:57.325,0:01:58.350
干锅鸭掌

0:01:58.675,0:01:59.500
红烧肉

0:02:00.125,0:02:00.975
酥排骨

0:02:01.450,0:02:02.575
酸辣大白菜

0:02:02.925,0:02:04.000
小煎花鲢

0:02:04.150,0:02:05.250
炸甜肉

0:02:05.600,0:02:06.675
石磨豆花

0:02:07.025,0:02:08.125
红烧鲤鱼

0:02:08.250,0:02:09.175
夹沙肉

0:02:09.675,0:02:10.625
扣肘子

0:02:11.125,0:02:12.350
青椒炒荷包蛋

0:02:12.725,0:02:13.900
大蒜烧肚条

0:02:14.275,0:02:15.225
鲜锅兔

0:02:15.575,0:02:16.575
蒸腊鱼

0:02:16.975,0:02:17.900
咸烧白

0:02:18.500,0:02:19.650
水族蒸鱼

0:02:20.250,0:02:21.175
烤牛腿

0:02:21.625,0:02:22.725
麻辣烤鱼

0:02:23.025,0:02:24.025
水煮鸡片

**Comment by immoonancient** [comment]
我来吧

**Comment by immoonancient** [comment]
bot, please upload

0:00:00.175,0:00:01.280
哈喽大家好我是王刚
Hello everyone, this is Wang Gang

0:00:01.280,0:00:02.950
本期视频我给大家分享
In this video, I will share with you

0:00:02.950,0:00:04.500
年终总结报菜名
Annual Summary: All the Dishes

0:00:05.000,0:00:06.100
松鼠鱼
Songshu Yu
("Squirrel Fish")

0:00:06.250,0:00:07.700
麻辣牛油火锅
Mala Niuyou Huoguo
("Spicy Beef Tallow Hot Pot Soup Base")

0:00:08.000,0:00:09.150
汆水丸子
Cuanshui Wanzi
("Blanched Meatballs")

0:00:09.725,0:00:10.775
椒香鲤鱼
Jiaoxiang Liyu
("Spice Flavored Carp")

0:00:11.225,0:00:12.325
鱼丸火锅
Yuwan Huoguo
("Fish Ball Hot Pot")

0:00:12.725,0:00:14.000
腊味合蒸
Lawei Hezheng
("Steamed Cured Pork and Sausage Combo")

0:00:14.150,0:00:16.050
麻辣火锅底料的极速版本
Quick recipe of Spicy Hot Pot Soup Base

0:00:16.550,0:00:17.675
麻辣香肠
Mala Xiangchang
("Spicy Sausage")

0:00:18.325,0:00:19.450
青椒牛肉丝
Qingjiao Niurousi
("Stir-Fried Beef with Green Peppers")

0:00:19.875,0:00:20.975
碎炒羊肉
Suichao Yangrou
("Stir-Fried Diced Lamb")

0:00:21.400,0:00:22.675
玉米排骨汤
Yumi Paigu Tang
("Corn and Pork Rib Stew")

0:00:23.350,0:00:24.475
炝炒包菜
Qiangchao Baocai
("Stir-Fried Cabbage")

0:00:24.875,0:00:26.100
风味茄子
Fengwei Qiezi
("Flavorful Eggplant")

0:00:26.300,0:00:27.550
椒香腰片
Jiaoxiang Yaopian
("Spice Flavored Pork Kidney Slices")

0:00:28.000,0:00:29.125
冷吃兔
Lengchi Tu
("Cold Served Rabbit")

0:00:29.850,0:00:31.175
酸菜黄骨鱼
Suancai Huanguyu
("Yellowhead Catfish Soup with Pickles")

0:00:31.650,0:00:32.975
脆青瓜炒肉
Cui Qinggua Chao Rou
("Stir-Fried Pork with Crunchy Cucumber")

0:00:33.400,0:00:34.600
口味猪肝
Kouwei Zhugan
("Tasty Pork Liver Stir Fry")

0:00:35.050,0:00:36.375
砂锅豆腐
Shaguo Doufu
("Clay Pot Tofu")

0:00:36.675,0:00:38.225
蒜蓉粉丝蒸花甲
Suanrong Fensi Zheng Huajia
("Steamed Clams with Minced Garlic and Fensi Noodles")

0:00:38.475,0:00:39.750
鲜虾蒸蛋
Xianxia Zhengdan
("Steamed Eggs with Prawns")

0:00:40.075,0:00:41.475
盐烧鲈鱼
Yanshao Luyu
("Salt Clay Pot Bass")

0:00:41.700,0:00:43.125
冷吃杏鲍菇
Lengchi Xingbaogu
("Cold Served King Oyster Mushroom")

0:00:43.500,0:00:45.100
蒜蓉粉丝蒸娃娃菜
Suanrong Fensi Zheng Wawacai
("Steamed Baby Cabbage with Minced Garlic and Fensi Noodles")

0:00:45.175,0:00:46.425
生焖鱼头
Shengmen Yutou
("Fresh Braised Fish Head")

0:00:46.675,0:00:47.925
辣炒鸡爪
Lachao Jizhua
("Spicy Stir-Fried Chicken Feet")

0:00:48.150,0:00:49.275
爱心山药
Aixin Shanyao
("Loving Heart Chinese Yam")

0:00:49.550,0:00:50.825
辣炒田螺
Lachao Tianluo
("Spicy Stir-Fried River Snails")

0:00:51.000,0:00:52.175
冷吃串串
Lengchi Chuanchuan
("Cold Served Skewers")

0:00:52.400,0:00:53.525
藿香鳝鱼
Huoxiang Shanyu
("Asian Swamp Eels with Huoxiang")

0:00:53.850,0:00:55.075
小葱煎鸡蛋
Xiaoconng Jian Jidan
("Scallion Fried Egg")

0:00:55.350,0:00:56.650
清蒸小龙虾
Qingzheng Xiaolongxia
("Streamed Crayfish")

0:00:57.050,0:00:58.300
大蒜烧鲶鱼
Dasuan Shao Nianyu
("Catfish Braised with Garlic")

0:00:58.525,0:00:59.675
拔丝红薯
Basi Hongshu
("Silk-Pulling Sweet Potato")

0:00:59.900,0:01:01.100
干煎带鱼
Ganjian Daiyu
("Fried Beltfish")

0:01:01.525,0:01:02.950
青椒炒鸡丁
Qingjiao Chao Jiding
("Stir-Fried Diced Chicken with Green Peppers")

0:01:03.125,0:01:04.375
红烧鲟鱼
Hongshao Xunyu
("Braised Sturgeon")

0:01:04.650,0:01:05.950
虎皮青椒
Hupi Qingjiao
("Tiger Skin Green Peppers")

0:01:06.150,0:01:07.275
烤鸡架
Kao Jijia
("Roasted Chicken Wings and Ribs")

0:01:07.400,0:01:08.400
卤牛肉
Lu Niurou
("Braised Beef")

0:01:08.700,0:01:09.825
小炒白豆角
Xiaochao Baidoujiao
("Stir Fried Long Beans")

0:01:10.100,0:01:11.225
青椒豆豉酱
Qingjiao Douchi Jiang
("Sauce of Green Peppers and Douchi Bean Paste")

0:01:11.550,0:01:12.625
麻婆豆腐
Mapo Tofu

0:01:12.975,0:01:14.000
青椒爆甲鱼
Qingjiao Bao Jiayu
("Stir-Fried Softshell Turtle with Green Peppers")

0:01:14.250,0:01:15.375
肉末烧茄子
Roumo Shao Qiezi
("Braised Eggplants with Ground Pork")

0:01:15.525,0:01:16.625
鲜椒茄猫儿
Xianjiao Qiemaor
("Stir-Fried Frogs with Fresh Peppers")

0:01:17.125,0:01:18.050
小炒木耳
Xiaochao Muer
("Stir-Fried Woodears")

0:01:18.400,0:01:19.450
拔丝土豆
Basi Tudou
("Silk-Pulling Potato")

0:01:19.850,0:01:20.800
甲鱼汤
Jiayu Tang
("Softshell Turtle Soup")

0:01:21.250,0:01:22.200
炒猪肝
Chao Zhugan
("Stir-Fried Pork Liver")

0:01:22.550,0:01:23.825
鲍鱼汁蒸排骨
Baoyuzhi Zheng Paigu
("Steamed Pork Ribs with Abalone Sauce")

0:01:24.150,0:01:25.150
柴火鸡
Chaihuo Ji
("Firewood Chicken")

0:01:25.675,0:01:26.775
鸡丝凉面
Jisi Liangmian
("Chicken Noodle Salad")

0:01:27.125,0:01:28.250
酱油炒饭
Jiangyou Chaofan
("Fried Rice with Soy Sauce")

0:01:28.650,0:01:29.675
盘龙茄子
Panlong Qiezi
("Coiled Dragon Eggplants")

0:01:30.100,0:01:31.300
盐焗海鲜
Yanju Haixian
("Salt Baked Seafood")

0:01:31.500,0:01:32.400
炸蜂蛹
Zha Fengyong
("Fried Wasp Pupae")

0:01:32.900,0:01:34.050
竹笋烧竹鼠
Zhusun Shao Zhushu
("Braised Bamboo Rat with Bamboo Shoots")

0:01:34.275,0:01:35.275
葱烧鲫鱼
Congshao Jiyu
("Braised Jiyu Carp with Green Onions")

0:01:35.700,0:01:36.800
川味牛肉面
Chuanwei Niuroumian
("Beef Noodle Soup in Sichuan Style")

0:01:37.050,0:01:38.050
烤竹鼠
Kao Zhushu
("Grilled Bamboo Rat")

0:01:38.375,0:01:39.475
凉拌茄子
Liangban Qiezi
("Eggplant Salad")

0:01:39.675,0:01:40.650
烧牛腩
Shao Niunan
("Braised Beef Brisket")

0:01:41.175,0:01:42.300
红烧牛鞭
Hongshao Niubian
("Braised Bull Pizzle")

0:01:42.550,0:01:43.775
土豆裹香蕉
Tudou Guo Xiangjiao
("Fried Banana with Potato Shreds")

0:01:44.025,0:01:45.100
可乐鸡翅
Kele Jichi
("Cola Chicken Wings")

0:01:45.450,0:01:46.400
烤羊肉
Kao Yangrou
("Grilled Lamb")

0:01:46.825,0:01:47.875
美蛙鱼头
Meiwa Yutou
("Bullfrog with Fish Head")

0:01:48.025,0:01:49.075
蜂窝玉米
Fengwo Yumi
("Honeycomb Corn")

0:01:49.250,0:01:50.350
木须肉
Mu Xu Rou
("Moo Shu Pork")

0:01:50.500,0:01:51.775
烤野猪
Kao Yezhu
("Grilled Wild Pig")

0:01:51.975,0:01:53.250
干炸肉丸
Ganzha Rouwan
("Fried Meatballs")

0:01:53.600,0:01:54.800
黄焖土鸡
Huangmen Tuji
("Yellow Braised Chicken")

0:01:54.925,0:01:56.050
琥珀核桃
Hupo Hetao
("Amber Sugar Coated Walnuts")

0:01:56.200,0:01:57.000
粑粑肉
Baba Rou
("Sichuan Meatloaf")

0:01:57.325,0:01:58.350
干锅鸭掌
Ganguo Yazhang
("Dry Pot Duck Feet")

0:01:58.675,0:01:59.500
红烧肉
Hongshao Rou
("Red Braised Pork")

0:02:00.125,0:02:00.975
酥排骨
Su Paigu
("Deep Fried Pork Ribs")

0:02:01.450,0:02:02.575
酸辣大白菜
Suan La Dabaicai
("Sour and Spicy Chinese Cabbage")

0:02:02.925,0:02:04.000
小煎花鲢
Xiaojian Hualian
("Stir-Fried Bighead Carp")

0:02:04.150,0:02:05.250
炸甜肉
Zha Tianrou
("Crispy Sweet Pork")

0:02:05.600,0:02:06.675
石磨豆花
Shimo Douhua
("Tofu Pudding Made with a Stone Mill")

0:02:07.025,0:02:08.125
红烧鲤鱼
Hongshao Liyu
("Red Braised Carp")

0:02:08.250,0:02:09.175
夹沙肉
Jia Sha Rou
("Steamed Pork Belly with Sugar Paste")

0:02:09.675,0:02:10.625
扣肘子
Kou Zhouzi
("Steamed Braised Pork Knuckle")

0:02:11.125,0:02:12.350
青椒炒荷包蛋
Qingjiao Chao Hebaodan
("Fried Eggs with Green Peppers")

0:02:12.725,0:02:13.900
大蒜烧肚条
Dasuan Shao Dutiao
("Braised Pork Tripe Strips with Garlic")

0:02:14.275,0:02:15.225
鲜锅兔
Xian Guo Tu
("Stir-Fried Rabbit with Young Ginger")

0:02:15.575,0:02:16.575
蒸腊鱼
Zheng Layu
("Steamed Cured Fish")

0:02:16.975,0:02:17.900
咸烧白
Xian Shao Bai
("Steamed Pork with Preserved Vegetables")

0:02:18.500,0:02:19.650
水族蒸鱼
Shuizu Zhengyu
("Steamed Fish in Shui Ethnic Style")

0:02:20.250,0:02:21.175
烤牛腿
Kao Niutui
("Roasted Beef Leg")

0:02:21.625,0:02:22.725
麻辣烤鱼
Mala Kao Yu
("Spicy Grilled Fish")

0:02:23.025,0:02:24.025
水煮鸡片
Shuizhu Jipian
("Water Boiled Chicken Slices")
