### ISSUE TITLE
[华农兄弟] 华农兄弟快过年了烧点水叫兄弟帮忙一起宰猪过年 - https://youtu.be/AnLBMKbyU9A

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#606]
https://youtu.be/AnLBMKbyU9A
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 23, 2020 at 03:52PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/AnLBMKbyU9A

#华农兄弟：快过年了，烧点水，叫兄弟帮忙一起宰猪过年
#Huanong Brothers: The Chinese New Year is coming. I boil some water, and ask my buddy to help me kill a pig.

0:00:00.320,0:00:04.160
# 快過年了  天氣好冷啊  烤烤火  很舒服哦
It will soon be the Chinese New Year and it's really cold. It's so nice to be in front of a fire.

0:00:04.280,0:00:05.200
# 燒了壼水
I'm also boiling a pot of water.

0:01:54.720,0:01:56.440
# 這個毛拔都拔不乾淨的
There's no way to dehair it thoroughly.

0:01:56.700,0:01:57.820
# 用火來燒一下
except burning it in the fire.

0:02:27.900,0:02:31.540
# 這樣燒一下  這樣燒一下整個豬都很香哦
Burning it, burning it makes the whole pig smell really nice.

0:03:21.760,0:03:22.960
# 哎呀  金黃色了
Aya! It's now golden yellow.

0:03:28.620,0:03:31.680
# 你看這個豬  變成金黃色的啦
Have a look at this pig! It has turned golden yellow.

0:03:37.340,0:03:38.680
# 看你還敢不敢啦
Do you still dare to be naughty?

0:03:47.860,0:03:49.480
# 很漂亮啦  哈哈~
It's so pretty, ha ha~!

0:03:54.580,0:03:55.880
# 來幫忙枱一下
Come and help me move it!

0:03:58.300,0:04:00.640
# 哎呀  燒一下太香啦  很好吃
Aya! It smells so good. It must be very tasty.

0:04:11.340,0:04:11.980
# 沖乾淨
Cleanse it.

**Comment by vincenthychow** [comment]
已發佈
