### ISSUE TITLE
[华农兄弟] 华农兄弟今天是大年初一给大家拜个年 - https://youtu.be/c1GaZBsFT4U

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#614]
https://youtu.be/c1GaZBsFT4U
<p>&#35270;&#39057;&#21457;&#24067;&#20110; January 25, 2020 at 06:21PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
只有八秒，我自己做算了
