### ISSUE TITLE
[老饭骨] 发财鸭 - https://www.youtube.com/watch?v=kBKnBO5DUU8

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#621]
https://www.youtube.com/watch?v=kBKnBO5DUU8

视频发布于 2020 年 1 月 29 日，时长 10:15

**Comment by immoonancient** [comment]
@Yibing-Du 请前来认领

**Comment by Yibing-Du** [comment]
认领

**Comment by shuaisoserious** [comment]
发财鸭
发财呀
三叔 二伯 大爷
大爷好
二伯好
二伯好
小焦又进来了
徒弟们好
今 二伯做个什么菜啊
发财鸭
发财呀
发财鸭
也叫发财呀
好 开始
来 第一步
小焦 我先处理这个鸭子
对 你现在处理了
我先开火
这是咱们北方的白条鸭
你看这鸭子选的特别好
也没有什么肥肉 关键肥肉我都去了
这个鸭子啊回来以后
从脊背开刀
把内脏去干净了
然后嘴这里切了一半
师父刚教我的
这嘴切一半啊 脑子里都入味
那另一半干什么去了
另一半洗洗睡了
洗洗睡了
然后我们把这鸭子先压一下
压一下选了几个调料去腥的
另外几个香叶 桂皮
白芷 豆蔻
草果 花椒 大料小茴香
全是增香的 对
但是都不多
都不多很全
中国菜本身就是百味集中
是永远其他菜比不了的
复合味特别强
大爷 你发现了没
小焦说话跟他师父一样 没句号
比师傅能说
比师父能侃
这是师父教他的·
这比师父能侃
我们是只有45分钟
好 开始了第一步
把这个调料先放进去
把根留住 姜
刚才我师父给了我一个最好的原材料
陈皮 特别棒 然后
安然睡去
好了不脱下水吗
不用 这鸭子洗干净了
鸭子要压45分钟
看压力
现在给你加味
糖
盐
因为我们这鸭子还有其他加工所以少放
对 有个底味就行
胡椒粉
调料已经很多了
我们给它设置了45分钟时间
下面你看到了没有
粗加工完了
徒弟做粗加工 师父做细加工
这掉包了 掉包了
这鸭子啊

**Comment by immoonancient** [comment]
刚才小焦也讲了
压完了以后
压完了以后刚才是整张的
然后脱骨
把这骨头一蹬是吧
然后这有一个模具 看到没有
展示展示这个模具
如果是家里喜欢做的话
露露这个罐头 是吧
剪一下 剪圆了
啪啪啪往上一刻
是个就出来了
发财是金钱的意思嘛 圆嘛
又代表团团圆圆
对
圆 地球也是圆的嘛
是不是 家庭和睦也是圆的嘛
关键过去的钱也是圆的
钱是圆的取发财之意
对啊 今天用的东西就有这个
这个虾胶 小焦介绍一下
小焦是玩粤菜的 玩得非常好
介绍介绍 师父也是玩粤菜的
这个虾胶啊
先把它碾碎
把它整个碾碎 然后呢
剁
剁的不要太随 里面要有点颗粒状
这样更有口感
所以我们这个已经处理好了
对 加点盐 加点味就好了
稍微加点盐 加点味就好了
这就加好了
虾胶里面放不放猪油啊？
这个虾饺里面部放猪油
因为猪油跟这个虾啊
本身就是鲜的
就缺少香
我们给它加什么呀 加点肥膘肉
可以切成丁
还可以加什么呢 加冬笋丁
这样把虾的鲜味和香味提取出来
把鸭子上边稍微放一点淀粉
干嘛用啊 放淀粉？
要不然他们俩就分离了
离婚了
离婚了
咱们不能让它离婚 大过节的
本来是圆满的事儿 你非让他离
你看这东西啊 不好
你先做一件好事 让它们黏合在一起
对啊 这不就黏嘛
发财鸭 发财呀
二伯也是左撇子啊
我怎么不知道我是左撇子啊
你是左撇子啊
我一看你挤虾胶的时候是左撇子
师父咱们做九个就得了 就也是大吉祥数字
小焦在这里我就放心了
我可以偷个懒
大家注意一下啊
生活需要仪式感
菜品也需要仪式感 必须的
精加工一下 给他抹平
抹平
抹平的时候搁点油
这个不沾油就抹手上去了
抹完了你搁在这 弄好了
你看这个菜
你看到没有 这就发财了
然后你看看 这个菜
开始下一步
我们可以切一半
这叫什么蛋啊
鹌鹑蛋
哦 鹌鹑蛋
鹌鹑下的蛋
这个菜什么来历？
这个菜是本人创造
国宴 当年这个宴会上
也受到特别的好评
就好像大牛眼是的
你没有眼睛能往前看准方向吗
能发财吗
是不是 老三？
今天老三表现不错啊
你看老三是善意的督促
老大给我刨坑啊
你看 多漂亮啊
好看吧？好看
是不是啊
跟那个牛眼似的
再不传就失传了
发菜发菜
发财发财
发菜的产地在宁夏内蒙交界处
因为它生长的时候会破坏很多植被
这个产量很小
我们在做菜的时候用量也不多
基本上就像二伯做粤菜吧
粤菜里面的发菜猪手啊
发菜鸭啊
像淮扬菜做的文思豆腐啊
都会用到发菜
它是以点缀为主
但是它也有一定的营养价值
这有点像眼珠子的眉毛
现在二伯给眼珠子化妆呢
这个菜你查所有的菜谱 没有
查不到
对 这是独创
当年八几年的时候
我在华都做宴会的时候
经常在宴会上有一道菜
他的弟子是樟茶鸭子 因为樟茶鸭好吃啊
那时候干川菜啊
所以说这个非常受客人欢迎
你看那时候做川菜
现在改了 改粤菜了
二伯就是川鲁粤
样样精通
我走到北京饭店上学的时候
我就仰视着北京饭店
那时候我见到郑秀生的时候
我都得这么看着
现在个高了 那时候他还小啊
那个时候他还没蹿个呢
现在长了一个大高个
现在往下看
那时候我见二伯也这么看 颈椎完蛋了
这决策点一定要让二伯来确定
这个蒸出来特漂亮
你看你看 先搓
你看看 你看看多漂亮
另外炸的时候 油温不宜太高
（漂亮啊）
三四成就好
下油锅了
网友朋友们
在家能不能直接
在家还得是笊篱
在这里我师父有这么多年的
有经验 就不往笊篱里面放了
师哥 准备装盘 你看我们的盘啊
这大菜就需要仪式感啊
盘也需要仪式感
盘在这里呢
装这里面倒下盘
就这温度就行啊
这颜色越浅越好
得 咱们一个个捞吧
跟鸟巢似的
跟鸟巢一样
鸟巢
行 那几个再炸上她 正合适
好了
过年的大菜 你看到没有
你看这香气 虾的香气都出来了
我在这里都闻见了 是吧
师父我觉得咱们做菜啊
就是任何菜啊
一个是细心加工
第二 菜一定要需要仪式感
而且还有什么呢
还有传承
还有网友说你们做菜为什么工序这么多
我说我们也想做简单的
但是实力不允许啊
那今天咱来做个仪式感的菜吧
而且还有传承
还有中国过年的气氛
是吧 大红灯笼
你看这大灯笼
宫灯
圆圆满满
发财鸭 发财呀
大爷 二伯
三叔
二伯的菜出来了 出来了
您先尝尝 还是我们先尝尝啊
让小饭骨先尝
你每次都审人家
这回咱们被人审
今天我们小饭骨审二伯
发财鸭 发菜呀
吃完发财
吃完了发大财
发财鸭发财呀
一口肉 一口酒 美哉
一口肉 一口酒 什么都有
2020 年什么都有
