### ISSUE TITLE
【美食作家王刚】虎皮青椒 - https://youtu.be/dvl2yq25nlU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#63]
【美食作家王刚】虎皮青椒 - https://youtu.be/dvl2yq25nlU 
这是刚哥最新的视频私享链接，方便大家提前添加字幕，做菜过程文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。然后就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间8月19日晚6点

首先我们准备适量的小青椒和小米辣去蒂备用
此辣椒碧绿短小辣度适中
是由湖南本土优质辣椒种子而结果
怕辣的同学可以选择辣度较低的大青椒
然后将辣椒清洗干净捞出备用
下一步开始准备辅料
准备五花肉1小块切成厚片之后剁碎备用
加半肥瘦的五花肉爆香之后成菜会更有层次感
准备大蒜几颗拍散之后剁碎备用
同学们大蒜是虎皮青椒的灵魂所以一定不能少
下一步开始制作
首先我们把锅烧热
锅烧热之后将辣椒下锅
然后烧小火将辣椒挤压翻炒6分钟左右
这一步的目的是将辣椒的表皮通过高温炒糊炒香
同学们切记这一步不能放油
之后经过慢火挤压翻炒的辣椒才够香辣
当辣椒炒至表皮焦香之后取出备用
下一步开始炒肉末
锅烧热之后加入适量的菜籽油下锅
油温6成热之后将剁好的肉末下锅翻炒至干香
当肉末炒至干香后加入蒜蓉翻炒均匀
然后再加入干香的辣椒下锅
下一步开始调味
锅中加入适量的酱油从锅边淋入翻炒几下
当炒出锅汽之后再加入适量的食用盐
同学们食用盐可以略微多一点点这样才够味
再加入小半勺白糖翻炒均匀即可出锅装盘
一道香辣下饭的家常虎皮青椒就制作完成
下面开始技术总结
第一，不同辣椒的种类辣度也不一样，大家可以选择适合自己的辣椒
第二，辣椒下锅必须小火慢炒，炒至辣椒表皮脱层干香即可
第三，此菜可以不加肉末，但蒜蓉是必不可少
下面开始试吃

**Comment by GUThe** [comment]
我做吧？大概北京时间17号早上做

**Comment by GUThe** [comment]
北京时间9:00-10:00制作并上传，review后我再去改YT

**Comment by GUThe** [comment]
starting now
