### ISSUE TITLE
[华农兄弟] 华农兄弟去镇上买点菜路过兄弟家的竹林顺便挖点竹笋 - https://youtu.be/kF9jZXRBz5k

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#633]
https://youtu.be/kF9jZXRBz5k
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 6, 2020 at 12:41AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
0:00:00.420,0:00:03.760
# 大家好  今天家里沒菜啦  我出鎮上來買點菜
Hi everyone. I run out of food at home. So I'm coming to the town today to buy some.

0:00:06.340,0:00:08.080
# 現在鎮上都沒甚麼人啦
There are hardly any people in the town now.

0:00:08.520,0:00:09.760
# 大家都呆在家裡
Everybody stays at home.

0:00:09.920,0:00:12.920
# 大家沒事就呆在家  盡量少出門
Everybody stays at home and avoids coming if not really necessary.

0:00:30.480,0:00:34.400
# 今天在鎮上買了  面包哇 蘿蔔  淮山  (註︰淮山即山藥)
Today I've bought in the town some bread, and well, radish, yam,

0:00:35.200,0:00:39.080
# 淮山 豬肉  豬腳  豬肉  面
yam, pork, pork legs, pork, noodle,

0:00:39.340,0:00:44.000
# 洗髮水  沐浴露  還有奶茶 好多  一大堆
shampoo, shower gel, and milk tea. A lot of stuffs, a whole lot!

0:00:44.640,0:00:49.200
# 剛好路過兄弟的竹林  看一下有沒有竹笋挖 挖兩個竹笋來
We just pass by my buddy's bamboo forest. Let's see if there are any bamboo shoots, and get a couple of them.

0:00:58.160,0:01:00.700
# 到了竹林這裡  就在這上面一點
We've arrived at the bamboo forest. It's right up there.

0:01:37.060,0:01:39.360
# 你看  這邊好像沒有
Look! Here doesn't seem to be any.

0:01:39.940,0:01:41.460
# 這是兄弟家的竹林哦
This is my buddy's bamboo forest, you know.

0:01:44.240,0:01:45.940
# 他家的竹子太扣啦
His bamboos are too stingy.

0:01:46.780,0:01:48.180
# 一個笋都長不出來
There isn't even a single shoot.

0:01:49.760,0:01:50.420
# 我去
Let me,

0:01:51.080,0:01:53.360
# 隔壁家大嬸家看一下  她家有沒有 (註︰原字幕出錯，應該是︰「她家的竹林」
go to my neighbouring auntie and have a look at her bamboo forest.

0:01:54.220,0:01:55.100
# 看一下有沒有(竹笋)
and see if there are any (bamboo shoots).

0:01:59.280,0:02:00.100
# 軟啦~
I'm fatigue~

0:02:01.240,0:02:02.480
# 我要去前面看一下
I wanna have a look over there.

0:02:02.940,0:02:04.200
# 這邊竹林太硬啦
The soil is too hard here,

0:02:04.660,0:02:06.300
# 全是石頭  小石頭來的
all are rocks, tiny rocks.

0:02:06.620,0:02:07.380
# 不好挖
No good

0:02:10.320,0:02:11.540
# 前面  前面還有
There, over there

0:02:27.680,0:02:29.280
# 唉  有一個
Ay! Here's one!

0:02:29.600,0:02:30.420
# 爛掉啦
But it's broken.

0:02:31.000,0:02:32.020
# 那麼小的
It's so small.

0:02:39.340,0:02:40.640
# 很大哦
Ayo! It's big!

0:02:41.240,0:02:42.060
# 不小哦
It's not small.

0:02:42.100,0:02:43.000
# 爛掉啦
But it's broken.

0:02:44.060,0:02:45.200
# 誒 爛掉啦
Ey! It's broken.

0:02:46.020,0:02:47.640
# 不小心  一搞就搞爛啦
I broke it, before I noticed it.

0:02:48.200,0:02:50.080
# 好不容易挖一個都爛掉啦
It's a precious single bamboo shoot. But I've broken it.

0:02:50.900,0:02:52.120
# 嗯  還有一塊肉
Um! This part is still edible.

0:02:53.100,0:02:54.060
# 先放到這裡
Put it here first.

0:03:02.300,0:03:03.820
# 哎呀 有
Aya! Yeah!

0:03:04.440,0:03:06.520
# 你看  雙胞胎喲
Look! They're twins!

0:03:14.120,0:03:15.120
# 好小
They're so small.

0:03:21.820,0:03:22.860
# 那(麼)小一個
What a tiny little one.

0:03:23.800,0:03:25.060
# 這還一個小的
And here's another small one.

0:03:33.760,0:03:35.120
# 一下就挖到3個
So I got three at a time.

0:03:35.600,0:03:36.960
# 拿來炒咸菜
I'll have them fried with pickled mustard.

0:03:37.260,0:03:39.200
# 很好吃的哦  這個 竹笋炒咸菜
It tastes really good, bamboo shoots fried with pickled mustard.

0:03:42.680,0:03:44.340
# 好香呀 夠啦  夠啦
It smells really good! Enough, enough.

0:03:44.500,0:03:46.020
# 3個就夠啦  不要多
Three is enough. Don't take too many.

0:03:46.080,0:03:47.400
# 剩下的留給他們挖
The rest is left for them.

0:03:49.040,0:03:49.760
# 回去啦
Let's go back.

**Comment by vincenthychow** [comment]
已發佈
