### ISSUE TITLE
[华农兄弟] 华农兄弟祝大家元宵节快乐 - https://youtu.be/kbe4INBrodU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#640]
https://youtu.be/kbe4INBrodU
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 8, 2020 at 09:35PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
只有12秒，我自己做算了
