### ISSUE TITLE
[华农兄弟] 华农兄弟看一下小黑最肥的崽还有其它小狗子再去田里砍点包菜 - https://youtu.be/j8fdqyhoM3M

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#648]
https://youtu.be/j8fdqyhoM3M
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 11, 2020 at 11:12AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/j8fdqyhoM3M

#华农兄弟：看一下小黑最肥的崽，还有其它小狗子，再去田里砍点包菜
#Huanong Bothers: Let's take a look at Blacky's fattest puppy and also other puppies. And then we go to pick some cabbages.

0:00:03.780,0:00:06.840
# 你看這條狗  胖成這樣子啦  不知道是不是
Look at this puppy! Ridiculously fat! I wonder if he's...

0:00:14.840,0:00:16.180
# 別跑 別跑  別跑
Stay here, stay here, stay here!

0:00:17.200,0:00:20.140
# 這狗  它的毛怎麼全部是拱起來的
This puppy, why is his hair all curling up?

0:00:20.420,0:00:22.320
# 它也不是很胖啊  哈
He's not really that fat, ha!

0:00:22.880,0:00:25.060
# 就是毛全部豎起來的  這個毛
It's just that the hair is all standing up, the hair.

0:00:25.640,0:00:28.040
# 爆炸頭一樣 爆炸型的哦
It's like afro style, afro style you know.

0:00:30.080,0:00:30.940
# 不可以打架
No fighting!

0:00:35.640,0:00:37.320
# 它的我好多哇  它的毛
He has a lot of hair, a lot.

0:00:45.960,0:00:47.420
# 這條那麼標亮  這條
He's so pretty, this puppy.

0:00:49.340,0:00:50.520
# 一臉懵逼
He looks perplexed.

0:00:54.660,0:00:55.760
# 看一下那個花的
Let's have a look at the tinted ones.

0:00:56.440,0:00:57.560
# 還有花的(狗子)
There are tinted (puppies) too.

0:00:58.280,0:00:59.160
# 它自己會走
They can walk by themselves.

0:00:59.320,0:01:00.360
# 不用我們管
We don't need to take care of them.

0:01:01.260,0:01:02.880
# 眼睛睜開了  看到沒
The eyes have already opened, see?

0:01:19.340,0:01:23.400
# 這條  這條  這條金紅色的
This one, this one, this one is golden red.

0:01:28.480,0:01:31.560
# 它這種顏色  這黑狗生出這個顏色出來
This colour, how can this black dog have a puppy of this colour?

0:01:35.720,0:01:37.240
# 好啦  叫那麼大聲
Enough! You're yelping so loudly.

0:01:45.500,0:01:46.220
# 坐下來
Sit!

0:01:49.880,0:01:50.920
# 它們都在吃奶
They're all sucking milk.

0:01:54.940,0:01:56.600
# 這條花的  你看  這條花的
This is tinted. Look! This is a tinted puppy.

0:01:58.040,0:02:00.780
# 有點瘦  可能是下崽 下得太多啦
It's a bit skinny. Perhaps there are too many puppies in this litter.

0:02:01.280,0:02:02.580
# 下了6只
There are six.

0:02:08.400,0:02:09.400
# 小狗~
Puppie~

0:02:11.620,0:02:12.640
# 小狗~
Puppie~

0:02:15.880,0:02:17.140
# 它不理我
No response.

0:02:17.780,0:02:18.620
# 給你按摩
Give you a massage.

0:02:31.100,0:02:32.160
# 不打擾它們吃奶啦
I'd better not disturb their meal time.

0:02:35.060,0:02:38.420
# 大家好  現在這十幾畝 大幾畝的包菜呀
Hi everyone! These dozens, dozens of mu of cabbages here (1 mu = 667 meter square),

0:02:38.780,0:02:40.660
# 額  兄弟都把它送給我哦
eh, my buddy gives them all to me.

0:02:41.120,0:02:42.380
# 它這個好小哇  好看
This one is really tiny, look!

0:02:42.680,0:02:44.940
# 有些很小的 有些都還沒長大
Some are really small, some have not even grown up.

0:02:45.680,0:02:47.180
# 今年的行情不好  他說
The sale this year is not that good, he said.

0:02:47.520,0:02:49.200
# 所以他就全部送給我們啦
So he gives all these to us.

0:02:49.460,0:02:52.200
# 有些  裂開的我們就可以拿去餵豬
Some are, cracked, and can be given to the pigs.

0:02:53.120,0:02:53.880
# 像農戶
Like the farmers,

0:02:54.240,0:02:56.540
# 農戶他們也經常來這裡砍  也砍了些
the farmers are also coming here quite often. And they have taken some too.

0:02:59.360,0:03:00.760
# 你看  這個就很靚啊  這種
Look! This is really beautiful, this one.

0:03:02.080,0:03:03.340
# 剛剛包起來的
It has just grown up.

0:03:05.840,0:03:07.620
# 上次我割了批走
I've already taken a batch last time,

0:03:08.140,0:03:09.340
# 割了五六千斤
with almost a ton and a half.

0:03:11.740,0:03:12.860
# 你看  現在都爆掉啦
Look! They're already cracked.

0:03:13.840,0:03:15.220
# 這個就可以吃的  這個
This one is edible, this one.

0:03:18.040,0:03:19.760
# 你看  這樣的包菜  很靚的哦
Look! Such a cabbage, is really beautiful!

0:03:20.900,0:03:22.280
# 我們把這個裝一下
Let's put it here.

0:03:23.060,0:03:24.160
# 把到靚的來割
We take the beautiful ones.

0:03:26.560,0:03:28.000
# 下次把麵包車開過來
I'll come with my van next time,

0:03:28.580,0:03:30.220
# 開過來把這些菜全部裝回去
then I can take all these cabbages with me,

0:03:30.320,0:03:31.280
# 拿來餵小豬
to feed the piggies.

0:03:32.340,0:03:33.300
# 直接割完的(註︰他想說甚麼？)
I'll take every single one.

0:03:35.360,0:03:36.600
# 你看 這樣的小包菜
Look! This is a small cabbage,

0:03:38.060,0:03:39.900
# 小包菜很靚的哦  這些小包菜
these small cabbages are really beautiful.

0:03:40.960,0:03:42.600
# 你看  剛剛好煮一餐
Look! It's a perfect size for a meal.

0:03:46.360,0:03:47.200
# 這邊也有
This side too.

0:03:48.420,0:03:49.420
# 你看  這邊也有
Look! There are some more on this side.

0:03:59.040,0:04:00.080
# 不要那麼大的
We don't want the big ones.

0:04:00.120,0:04:01.320
# 就這樣小的就可以
This kind of small ones are good enough.

0:04:01.900,0:04:03.180
# 這麼小的更好吃
These small ones taste even better,

0:04:04.060,0:04:04.760
# 這樣小嫩
cuz they're more tender.

0:04:06.040,0:04:06.880
# 越小越嫩
The smaller, the more tender

0:04:12.960,0:04:13.640
# 這個就
And this one,

0:04:14.060,0:04:14.800
# 還會大的
can still grow.

0:04:15.340,0:04:17.140
# 但是這樣子更嫩  更好吃
But now it's more tender, and tastes better.

0:04:18.300,0:04:19.880
# 吃小一點的  不要那麼大的
We take the smaller ones, not the big ones.

0:04:26.780,0:04:27.600
# 這個可以啦
It's alright now.

0:04:35.240,0:04:36.580
# 這3個小包菜
These three small cabbages

0:04:37.920,0:04:38.900
# 一個煮一餐
One for one meal

0:04:57.200,0:04:58.940
# 你看 這個包菜很靚的哦  你看
Look! This cabbage is really beautiful. look!

0:04:59.200,0:05:01.620
# 可以做成手撕包菜  這就樣一片片把它撕下來
It can be made into hand shredded cabbage. Just peel it piece by piece,

0:05:01.780,0:05:04.140
# 然後再來炒  就是手撕包菜
and then fry it. And it is hand shredded cabbage.

0:05:05.400,0:05:06.900
# 砍多一點  反正都還很多
Why don't we get more? There are still a lot.

0:05:07.880,0:05:08.720
# 那麼靚的
Beautiful!

0:05:10.080,0:05:12.060
# 這個有點爛的就要把它撕掉
This one is a bit rotten. Let me peel it.

0:05:12.840,0:05:14.940
# 這葉子有點爛 撕掉就好啦
The leaves are a bit rotten. Take them away and it'll be fine.

0:05:20.040,0:05:21.400
# 你看  這葉子撕掉就
Look! After taking away the leaves,

0:05:21.720,0:05:22.420
# 很靚啊
it's so beautiful.

0:05:25.860,0:05:27.580
# 哇  就跟超市賣的一樣的
Wa! It's just like those in the supermarket.

0:05:45.300,0:05:46.880
# 啊  你看  這樣就可以啦
Ah! Look! It's alright now!

0:06:07.000,0:06:09.040
# 摘了那麼一點(點)  好  夠啦  夠啦  夠啦
We have just a tiny little bit here. Alright! It's enough, enough, enough.

**Comment by vincenthychow** [comment]
已發佈
