### ISSUE TITLE
[华农兄弟] 华农兄弟没什么菜吃了去竹林挖点笋来吃运气还错挖到几个 - https://youtu.be/nZ0demULkIs

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#652]
https://youtu.be/nZ0demULkIs
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 11, 2020 at 06:19PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/nZ0demULkIs

#华农兄弟：没什么菜吃了，去竹林挖点笋来吃，运气还错，挖到几个
#Huanong Brothers: We don't have much food left. So I go to get some bamboo shoots and come back with a couple of them. Lucky, lucky!

0:00:00.000,0:00:01.740
# 大家好  今天又沒菜吃啦
Hi everyone! I run out of food again today.

0:00:02.040,0:00:04.220
# 我去山上挖點那個竹笋 你看  這山上
I go onto the hill to get some, you know, some bamboo shoots. Look! That hill.

0:00:04.760,0:00:06.220
# 這個竹林很茂盛哦
The bamboo forest is really bushy.

0:00:31.920,0:00:32.780
# 哎呀  有一個
Aya! Here's one!

0:00:36.120,0:00:38.080
# 你看  這個竹笋很大哦  這個
Look! This bamboo shoot is really big, this one.

0:00:40.480,0:00:41.380
# 大竹笋
Big bamboo shoot

0:00:45.600,0:00:47.300
# 哎喲  這個  這個可以
Ayo! This one, this one is not bad.

0:00:59.740,0:01:00.300
# 你看
Look!

0:01:01.200,0:01:02.940
# 這個竹笋很漂亮的哦 你看
It's a really pretty bamboo shoot, look!

0:01:03.380,0:01:04.080
# 不大不小
Not too big, not too small

0:01:14.320,0:01:15.120
# 哎喲  有一個
Ayo! Here's one!

0:01:16.320,0:01:16.820
# 你看
Look!

0:01:30.240,0:01:31.160
# 這麼小的
It's so small.

0:01:41.100,0:01:42.240
# 好小這個
It's really small.

0:01:55.180,0:01:55.820
# 你看
Look!

0:01:56.480,0:01:57.340
# 也不小哦
It's not that small in fact.

0:01:58.340,0:01:58.840
# 你看
Look!

0:01:59.960,0:02:01.220
# 夠嫩  剛剛好
It's young, just right.

0:02:02.080,0:02:03.320
# 先把它放在這裡先
Let me put it here first.

0:02:07.360,0:02:08.360
# 哎喲  有一個
Ayo! Here's one,

0:02:09.600,0:02:10.380
# 好小哇
a tiny one!

0:02:28.160,0:02:29.120
# 這個那麼小
This one is so tiny.

0:02:32.040,0:02:33.640
# 又扁又小  你看  這個
It's flat and small. Look! This one

0:02:34.880,0:02:35.640
# 要  (註︰沒下文了)
I wanna...

0:02:38.800,0:02:39.980
# 我檢到一堆去
I have several over there.

0:02:42.020,0:02:43.000
# 放在那裡先
Put it there first.

0:02:48.840,0:02:49.720
# 哎呀  有一個
Aya! Here's one!

0:02:50.880,0:02:52.720
# 哎呀  這個挺大的哦  這個
Aya! It's rather large, this one.

0:02:53.780,0:02:55.900
# 哎呀  不大  剛剛那個不大  (註︰我想他是想說︰「不比剛剛那個大」)
Aya! No, it's not that large.

0:02:57.080,0:02:58.480
# 這個小哇  小短腿
It's small, with short legs.

0:02:59.760,0:03:00.780
# 你看  是不是
Look! Isn't it?

0:03:02.400,0:03:03.600
# 一看就看得出來
I can tell immediately.

0:03:21.840,0:03:22.380
# 你看
Look!

0:03:23.480,0:03:24.480
# 還可以哦  這個
It's not bad, this one.

0:03:26.520,0:03:28.080
# 你看  就挖了這三四個
Look! I've got a couple of them here.

0:03:28.600,0:03:29.480
# 現在下雨了啊
It's raining now.

0:03:29.760,0:03:30.400
# 回去啦
Let's head back.

0:03:31.580,0:03:32.620
# 夠吃一餐啦
It's enough for a meal.

**Comment by vincenthychow** [comment]
已發佈
