### ISSUE TITLE
[华农兄弟] 华农兄弟去田里摘点包菜叶拿回去喂兔子 - https://youtu.be/enEQy283H7A

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#656]
https://youtu.be/enEQy283H7A
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 12, 2020 at 12:06PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by immoonancient** [comment]
兔子居然还活着

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/enEQy283H7A

#华农兄弟：去田里摘点包菜叶，拿回去喂兔子
#Huanong Brothers: We go to the farm to pick some cabbage leaves for the bunnies.

0:00:00.000,0:00:03.920
# 大家好  今天摘點菜葉子去餵小  餵那個小兔子
Hi everyone! Today I'm gonna get some veggie leaves for the lit, for the little bunnies.

0:00:05.760,0:00:07.300
# 這個菜葉子很嫩的哦
These veggie leaves are really young and tender you know.

0:00:16.540,0:00:17.960
# 這些菜葉子很靚我哦
These veggie leaves are really beautiful.

0:00:20.100,0:00:21.020
# 一片片來
Pick them out,

0:00:21.300,0:00:22.000
# 摘下來
piece by piece,

0:00:31.540,0:00:32.040
# 你看  這個
Look! This one,

0:00:32.400,0:00:33.880
# 這個  這個爆掉啦
this one, this one has already cracked open.

0:00:34.140,0:00:35.560
# 你看 這個爆掉了也可以
Look! This cracked one is still good.

0:00:36.160,0:00:37.060
# 很好吃的
It's really tasty.

0:00:38.560,0:00:39.620
# 今天沒帶刀
I don't have a knife with me today.

0:00:45.160,0:00:46.360
# 你看 這些菜葉子
Look! These veggie leaves...

0:00:54.540,0:00:58.080
# 這一大片都是兄弟家的哦 通通送給我們啦
This whole area belongs to my buddy. And he gives them all to us.

0:00:58.240,0:01:02.140
# 他說不要啦  他自己  他自己到外面去上班啦
He said he doesn't want it anymore. He, he's already got a job outside.

0:01:02.980,0:01:05.620
# 種了那麼多菜 那麼多包菜
Here are so many veggies, so many cabbages.

0:01:05.860,0:01:08.140
# 摘到摘不完  吃都吃不完
There's no way to pick them all, no way to finish them.

0:01:08.380,0:01:12.820
# 前兩天我們都扛了三四袋  三四袋那個牛皮袋呀
We've already taken three or four, three or four bags of cabbages a couple of days ago.

0:01:13.120,0:01:15.980
# 拿到村里面  讓他們想要的人就去拿
We took the cabbages back to the village. Anyone who needs them can take some.

0:01:16.400,0:01:18.820
# 每個人拿了幾個  幾個  一下就沒有啦
Everybody took a few, a few, and all were gone in a second.

0:01:19.100,0:01:22.280
# 過兩天吃完啦  我又來割一點  全部發給他們
When they have finished, I'll come again in a couple of days. All will be distributed to the villagers.

0:01:26.000,0:01:28.020
# 你看  這  半個牛皮袋
Look! Here, half a bag.

0:01:28.520,0:01:31.020
# 夠啦  夠兔子吃個  一個禮拜左右
It's enough, enough for the bunnies for, for about a week.

0:01:32.840,0:01:34.540
# 不要摘那麼多  下次來摘
Don't take too much. We'll come again next time,

0:01:34.960,0:01:35.620
# 才新鮮
to ensure the freshness.

**Comment by vincenthychow** [comment]
已發佈
