### ISSUE TITLE
[华农兄弟] 烤兄弟家的小龙虾 - https://youtu.be/aFsIbji2Wxg

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#66]
https://youtu.be/aFsIbji2Wxg

331k 点击热门老视频，考虑补字幕

建议老同学不用太着急接，让新同学能够更多参与～

**Comment by vincenthychow** [comment]
華農兄弟YouTube上的舊視頻沒有開放添加字幕的
待攝影小哥沒那麼忙時我會跟他商量一下
因為他本身想移除舊視頻上的「西瓜視頻」水印重新上載
但要比較多時間

**Comment by immoonancient** [comment]
那这个我们目前做不了，先 close 好了
确定能添加字幕的再开 issue
