### ISSUE TITLE
【美食作家王刚】家常蒜蓉辣椒酱 - https://youtu.be/RsjYYAJ_Gcc

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#660]
【美食作家王刚】家常蒜蓉辣椒酱 - https://youtu.be/RsjYYAJ_Gcc
视频时长 5:04，预计发布时间为北京时间2月14日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.375,0:00:02.850
首先我们准备小米辣200克

0:00:02.850,0:00:05.375
将小米辣清洗干净之后切碎备用

0:00:05.375,0:00:07.975
辣椒切得越碎则越辣和入味

0:00:21.625,0:00:24.775
准备二荆条500克去掉辣椒蒂之后切碎备用

0:00:24.775,0:00:28.400
不能吃太辣的同学可以用大青椒或者大红椒代替

0:00:41.325,0:00:43.600
准备杏鲍菇1根切成小粒备用

0:00:43.600,0:00:45.775
杏鲍菇的重量是350克

0:00:45.800,0:00:48.550
加杏鲍菇的目的是代替味精增加鲜味

0:00:48.550,0:00:51.625
同学们也可以改变比例多加一些杏鲍菇

0:00:51.625,0:00:53.650
这样还能丰富辣椒酱的口感

0:00:58.225,0:01:00.900
杏鲍菇切好之后下一步开始准备辅料

0:01:01.464,0:01:03.975
准备生姜和大蒜各100克剁碎备用

0:01:03.975,0:01:06.525
生姜和大蒜可以适量的多加一些

0:01:06.525,0:01:08.950
这样能够让香味更加浓郁

0:01:14.000,0:01:15.425
准备空碗一个

0:01:15.425,0:01:17.475
加入炒香的白芝麻20克

0:01:17.475,0:01:19.900
没有芝麻的同学也可以不加

0:01:21.800,0:01:23.700
加入刀口辣椒面30克

0:01:24.000,0:01:26.775
加辣椒面的目的是增加成品的层次感

0:01:31.750,0:01:33.625
下一步开始准备香料

0:01:34.250,0:01:36.175
碗中加入八角2颗

0:01:36.175,0:01:38.025
加入桂皮2小块

0:01:38.025,0:01:39.500
加入香叶2片

0:01:39.500,0:01:41.300
加入几根小葱挽成结

0:01:47.175,0:01:48.775
再加入几根香菜

0:01:50.125,0:01:53.600
然后在剁好的辣椒中加入食用盐15克搅拌均匀

0:01:53.600,0:01:56.500
这一步的目的是让辣椒提前出水和入味

0:02:00.450,0:02:02.075
下一步开始制作

0:02:03.125,0:02:04.950
首先我们把锅烧热

0:02:06.950,0:02:10.575
锅烧热之后加入菜籽油700克 烧至6成热（约180度）

0:02:17.175,0:02:20.775
油温6成热之后将准备好的香料和小葱香菜下锅

0:02:21.000,0:02:23.600
然后转中小火浸炸3分钟左右

0:02:23.600,0:02:26.750
这一步的目的是将香料和辅料炸出香味

0:02:26.750,0:02:29.250
家庭小灶则需要5分钟左右

0:02:33.525,0:02:36.200
3分钟之后将辅料捞出丢弃不用

0:02:48.100,0:02:50.650
然后再次将油温升至7成热

0:02:53.225,0:02:56.775
油温7成热之后将切好的杏鲍菇下锅炸3分钟

0:02:56.775,0:02:59.600
这一步的目的是减少杏鲍菇的水份

0:03:05.478,0:03:08.450
中途加入剁好的姜蒜末炸香

0:03:19.975,0:03:23.250
杏鲍菇炸至金黄色之后（3分钟）再加入切好的辣椒

0:03:23.250,0:03:26.350
辣椒碎下锅之后先开大火烧开搅拌均匀

0:03:26.350,0:03:28.775
拌匀之后开中火熬4分钟

0:03:28.775,0:03:31.275
这一步的目的是将其熬至断生

0:03:31.275,0:03:34.475
同学们只有熬至断生之后可以防止变质

0:03:45.125,0:03:48.400
4分钟之后加入准备好的刀口辣椒和熟芝麻

0:03:48.400,0:03:50.525
然后继续翻炒2分钟

0:04:05.725,0:04:09.250
刀口辣椒炒香炒出颜色之后再加入黄豆酱50克

0:04:09.250,0:04:12.375
黄豆酱翻炒1分钟之后即可出锅冷却食用

0:04:21.100,0:04:24.600
同学们辣椒酱冷却之后最好放入玻璃瓶中密封保存

0:04:25.620,0:04:28.880
一道鲜辣回味无穷的辣椒酱就制作完成

0:04:36.600,0:04:38.260
下面开始技术总结

0:04:38.420,0:04:42.300
第一，不同地区的同学可以选择适合自己辣度的辣椒

0:04:42.320,0:04:48.700
第二，最好选择菜籽油作为油料，且油量可以稍微多一些，这样可以增加保存的时间

0:04:48.740,0:04:52.800
第三，此酱除了下饭之外还可以用作蒸鱼头的原料

0:04:52.880,0:04:56.700
第四，冷却之后最好用密封容器放入冰箱保存

0:04:56.800,0:05:00.620
第五，成品切忌阳光暴晒或者阴暗潮湿

0:05:00.680,0:05:02.800
家常辣椒酱的技术总结完毕

**Comment by Yibing-Du** [comment]
认领

**Comment by Yibing-Du** [comment]
Add files via upload #667

**Comment by immoonancient** [comment]
已发布
