### ISSUE TITLE
[华农兄弟] 华农兄弟一年之计在于春田园生活四季合集 - https://youtu.be/hX7rpQrFOL0

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#664]
https://youtu.be/hX7rpQrFOL0
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 13, 2020 at 04:34PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/hX7rpQrFOL0

#华农兄弟：一年之计在于春，田园生活，四季合集
#Huanong Brothers: A year starts in spring. Four season collection of country life.

0:00:17.820,0:00:19.420
# 大家好  河邊的
Hi everyone! The peaches,

0:00:19.800,0:00:20.300
# 桃子
on the riverside,

0:00:21.000,0:00:22.060
# 桃子快熟了哦 (註︰因為中英語序不同，把口吃部份換了一下，使口吃更自然)
on the riverside, are almost ripe.

0:00:54.880,0:00:56.440
# 哈哈  不要暈掉了
Ha ha! Hope I won't pass out!

0:00:58.280,0:00:58.940
# 哎喲
Ayo!

0:00:59.700,0:01:00.740
# 哇塞~
Oh gosh~

0:01:00.760,0:01:01.380
# 爆啦
It's cracked.

0:01:04.060,0:01:05.300
# 好紅啊  這個肉
It's really red inside!

0:01:42.660,0:01:43.400
# 專
Exclusive

0:01:44.440,0:01:46.400
# 專享  享受的享字怎麼寫  (註︰當然字幕是這樣改了一下，增加觀眾共鳴感)
Exclusive enjoyment. How do you spell "enjoyment"?

0:01:53.480,0:01:55.400
# 哎呀  一扭就斷掉啦
Aya! A single twist is enough to break it.

0:01:59.080,0:02:00.860
# 你看  那裡有一串芭蕉哦
Look! There's a bunch of plantains.

0:02:01.300,0:02:02.900
# 那麼大啦  還沒有人來摘
It's so big now but no one takes it.

0:02:04.000,0:02:05.800
# 熟了之後我們就可以過來
When it becomes ripe, we can come here again,

0:02:06.640,0:02:07.800
# 在樹上吃
and enjoy on the tree.

0:02:08.060,0:02:10.820
# 你看  這顆[SIC]樹  好大呀
Look! This tree, is huge!

0:02:11.800,0:02:12.680
# 我上去
Let me climb it.

0:02:35.620,0:02:36.260
# 誒呦
Eyo!

0:02:39.380,0:02:40.160
# 哇  這個是
Wa! This one,

0:02:40.680,0:02:42.660
# 最少有三四十斤  四五十斤
it's a least twenty, or twenty five kilograms.

0:02:43.600,0:02:46.560
# 沒味道  現在還沒聞不出味
No smell. There isn't any smell yet.

0:02:47.260,0:02:49.960
# 你看  就摘了那麼一點點
Look! We've got just a tiny little bit here.

0:02:50.580,0:02:51.520
# 大少啦
It's too few.

**Comment by vincenthychow** [comment]
已發佈
