### ISSUE TITLE
[华农兄弟] 带白竹鼠玩沙子 - https://youtu.be/9Tghy7PEA6k

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#67]
https://youtu.be/9Tghy7PEA6k

老视频补字幕

**Comment by immoonancient** [comment]
@vincenthychow 字幕已上传，请通知一下摄影小哥谢谢！

**Comment by vincenthychow** [comment]
天亮了會告訴他了...
我另外都在YouTube上的字幕作了些調整...調較了字幕的出入時間
我通常會盡量配合原字幕的出入時間....差距盡量少於0.05秒...
畢竟華農兄弟不是資訊或教學視頻為主(竹鼠養殖教學除外)......觀賞的雅興較重要

**Comment by immoonancient** [comment]
> 我另外都在YouTube上的字幕作了些調整...調較了字幕的出入時間
> 我通常會盡量配合原字幕的出入時間....差距盡量少於0.05秒...

那这样做一期挺费工的喔...
不过有人愿意负责的话就是再好不过的了

**Comment by GUThe** [comment]
> 天亮了會告訴他了...
> 我另外都在YouTube上的字幕作了些調整...調較了字幕的出入時間
> 我通常會盡量配合原字幕的出入時間....差距盡量少於0.05秒...
> 畢竟華農兄弟不是資訊或教學視頻為主(竹鼠養殖教學除外)......觀賞的雅興較重要

8/19检查摄影小哥还没通过诶。。。

**Comment by vincenthychow** [comment]
沒法子，他會做的，但不是即時，尤其有時可能家中有事，或到外地出席活動，有人到訪，採訪，外出拍攝，他便會過幾天才理YouTube了
這兩天他在微信的反應都較慢，應該有其他工作
真的沒法子，他沒團隊，但他很上心的，有時間便會馬上處理

**Comment by immoonancient** [comment]
如果跟他打个招呼，然后我们自行审核通过呢？这样怎么样？

**Comment by vincenthychow** [comment]
先多待兩天吧，村霸微博提過他這兩天不在，應該有其他事做，不想太多微信打擾他了
以往他也經常過很多天才發佈字幕的...不出奇
