### ISSUE TITLE
【美食作家王刚】介绍儿菜棒菜 - https://youtu.be/BU7MgbsJMQM

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#671]
【美食作家王刚】介绍儿菜棒菜 - https://youtu.be/BU7MgbsJMQM
视频时长 4:07，预计发布时间为北京时间2月17日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.500,0:00:01.550
嗨喽大家好

0:00:01.550,0:00:02.275
我是王刚

0:00:02.275,0:00:06.325
今天跟大家介绍一下我们四川的这三种菜

0:00:07.375,0:00:09.750
这个太重了我拿下来一样一样的介绍

0:00:11.250,0:00:14.025
这个叫棒菜看起来像莴笋

0:00:14.025,0:00:16.450
一根（小的）的话大概有一斤多 

0:00:16.450,0:00:18.525
大的有两三斤三四斤的也有

0:00:18.700,0:00:20.425
长得有点像莴笋

0:00:20.700,0:00:23.550
我们这个棒菜在四川来说产量非常地高

0:00:24.600,0:00:26.550
就是春节前后（登市）

0:00:26.725,0:00:29.075
因为春节前后大家大鱼大肉吃多了

0:00:29.075,0:00:30.900
然后这个把皮撕掉

0:00:30.900,0:00:35.775
用它来清煮或者说加一些腊味下去煮

0:00:35.775,0:00:38.350
煮出来这个菜的口感很软

0:00:38.350,0:00:41.300
就是特别的鲜 汤比较鲜

0:00:41.875,0:00:43.750
然后这个

0:00:44.450,0:00:47.625
这个看起来有点棱棱角角的

0:00:47.625,0:00:49.625
在我们四川这个叫菱角菜

0:00:49.625,0:00:52.225
我们本地话叫菱盖儿菜

0:00:52.400,0:00:55.846
菱角菜

0:00:55.975,0:01:01.250
同样的它这个也是一样把这个老的皮给它撕掉

0:01:01.400,0:01:05.850
吃法的话就比这个棒菜多一种吃法

0:01:05.900,0:01:09.450
它可以用来凉拌也可以用来煮汤

0:01:09.450,0:01:11.125
然后可以用来炖肉

0:01:11.125,0:01:14.400
同样的是春节前后（登市）这个产量非常高

0:01:14.400,0:01:17.150
我们这个菱角菜呢它其实还有一个做法

0:01:17.150,0:01:19.875
就是跟（竹）笋干萝卜干一样

0:01:19.875,0:01:21.900
直接切开切开了之后晒

0:01:21.900,0:01:23.400
晒成干的东西

0:01:23.400,0:01:26.000
然后我们吃的时候再拿出来泡

0:01:26.000,0:01:29.925
把它（泡）发好了不管是用来炒也好 用来炖也好

0:01:30.275,0:01:31.800
或者是凉拌也好

0:01:31.825,0:01:35.825
然后我们这个菜的话跟另外两样它比起来的话

0:01:35.875,0:01:37.925
它的保存的周期就更加长

0:01:37.925,0:01:41.100
可以放到几个月甚至一年都可以

0:01:41.350,0:01:42.750
下面这个菜

0:01:43.400,0:01:44.825
跟大家介绍一下这个菜

0:01:45.125,0:01:47.925
这个菜在我们这里叫法比较多

0:01:48.350,0:01:51.300
有一个比较好听的名字叫超生菜

0:01:51.300,0:01:52.700
为什么叫超生呢

0:01:52.700,0:01:56.425
因为它这里一坨一坨一坨的

0:01:57.000,0:01:58.800
也叫做儿菜

0:01:58.800,0:02:03.100
就是说除了一根茎上来之外它像花瓣一样

0:02:03.100,0:02:06.300
会朝四边发展出很多“儿子”出来

0:02:06.300,0:02:07.575
所以叫做儿菜

0:02:07.575,0:02:10.250
我们本地叫这个菜叫南充菜

0:02:10.725,0:02:14.900
这个同样的也是春节的时候（登市）产量非常地高

0:02:14.900,0:02:18.725
这个的话比较小 这个都有三斤多

0:02:18.800,0:02:21.800
然后大的话可以到七八斤 十多斤的也有

0:02:21.975,0:02:24.050
因为比较实在嘛 长得比较实在

0:02:25.025,0:02:26.675
基本上都是实心的

0:02:27.150,0:02:28.450
种得也比较多

0:02:28.575,0:02:31.475
同样吃法也是可以用来炖菜

0:02:31.475,0:02:36.425
然后把这个老的地方撕掉 切成片

0:02:36.425,0:02:39.850
就像那个萝卜丝一样放点盐给它出一下水

0:02:39.850,0:02:45.050
然后再加辣椒啊红油啊盐啊白糖这些拌一下来吃

0:02:45.050,0:02:47.350
我们这个儿菜呢还有一个吃法就是

0:02:47.350,0:02:52.775
把这个上面的儿把它弄下来 弄下来做泡菜

0:02:52.775,0:02:55.975
就是像泡萝卜这些跳水菜

0:02:55.975,0:03:00.075
就是直接泡一下短时间就可以吃

0:03:00.075,0:03:01.975
吃起来味道也很鲜

0:03:02.250,0:03:04.050
比较好吃 而且比较脆

0:03:04.700,0:03:07.925
所以在我们四川这些东西都是非常常见的

0:03:07.925,0:03:12.350
可能说这个的话在外地还有人经常见到过

0:03:12.350,0:03:16.600
但这种东西的话只有在我们四川吃得比较多

0:03:16.600,0:03:19.375
因为它这个第一个是便宜

0:03:19.375,0:03:21.075
第二个是产量高

0:03:21.075,0:03:25.750
然后我们这里特别喜欢把它弄来煮汤来吃

0:03:25.750,0:03:26.800
它的汤也比较鲜

0:03:27.100,0:03:29.744
如果想吃得清淡一点的话就直接用来煮水

0:03:30.300,0:03:31.800
用白开水煮

0:03:31.800,0:03:36.425
煮熟了之后弄点酱油蒜直接就可以蘸着吃

0:03:36.600,0:03:40.725
这个也算是我们这边产量比较高的一个青菜

0:03:40.850,0:03:42.775
也算作是青菜

0:03:42.775,0:03:46.400
但是这三种同样是属于芥菜科里面的

0:03:46.400,0:03:49.150
但是长得完全不一样

0:03:49.275,0:03:53.750
好啦 如果你们喜欢这个的话想了解更多的话

0:03:53.750,0:03:57.000
你们在评论里面可以跟我留言

0:03:57.000,0:04:00.325
后面的话会考虑把它做成一个菜谱出来

0:04:00.800,0:04:02.650
好啦本期视频就到这里了

0:04:02.650,0:04:03.300
拜拜

**Comment by immoonancient** [comment]
@Hackerry 请前来认领

**Comment by Hackerry** [comment]
认领

**Comment by immoonancient** [comment]
已发布
