### ISSUE TITLE
【美食作家王刚】鲜花椒的存储 - https://youtu.be/2-AKD2kNiE4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#677]
【美食作家王刚】鲜花椒的存储 - https://youtu.be/2-AKD2kNiE4
视频时长 1:02，预计发布时间为北京时间2月19日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.500,0:00:02.075
嗨喽大家好 我是王刚

0:00:02.075,0:00:06.125
最近有很多粉丝在问这个青花椒怎么样去保存

0:00:06.125,0:00:09.200
现在我拿的这一袋是我刚刚拆的

0:00:09.200,0:00:12.625
这个是已经放了大概有几个月的时间

0:00:12.625,0:00:14.300
已经冻上了冰块

0:00:14.300,0:00:20.150
这个青花椒的话它因为熟的时间比较特殊

0:00:20.150,0:00:25.425
然后把它摘下来了之后如果没有方法去保存很快它就干了

0:00:25.425,0:00:27.075
很快这个味道就挥发了

0:00:27.075,0:00:29.450
这个花椒属于油性挥发的东西

0:00:29.450,0:00:30.975
就没有（鲜花椒的）味道了

0:00:30.975,0:00:34.050
然后今天跟大家分享一下这个保存的一些方法

0:00:34.225,0:00:37.325
我们这个花椒现在像这样子抽完真空

0:00:37.325,0:00:41.150
抽了真空之后就放在那个冰柜里面把它冻硬

0:00:41.150,0:00:46.025
冻硬了之后的话这个可以保存 最长可以保存一年半以上

0:00:46.025,0:00:49.350
这个是我目前知道的保存的时间最长的

0:00:49.425,0:00:51.075
如果不是长期保存

0:00:51.075,0:00:53.000
可以把它放到一个容器里面

0:00:53.000,0:00:54.500
倒上一些植物油

0:00:54.500,0:00:56.775
然后再放到冰柜里面密封保存

0:00:56.775,0:01:00.200
这样子的话可以保存一个月到三个月之间

**Comment by immoonancient** [comment]
bot, please upload



0:00:00.500,0:00:02.075
嗨喽大家好 我是王刚
Hello everyone, this is Wang Gang

0:00:02.075,0:00:06.125
最近有很多粉丝在问这个青花椒怎么样去保存
Many fans have been asking how to preserve Sichuan green peppercorns

0:00:06.125,0:00:09.200
现在我拿的这一袋是我刚刚拆的
I just took these out from a bag

0:00:09.200,0:00:12.625
这个是已经放了大概有几个月的时间
which has been stored for a few months

0:00:12.625,0:00:14.300
已经冻上了冰块
Already frozen

0:00:14.300,0:00:20.150
这个青花椒的话它因为熟的时间比较特殊
Sichuan green peppercorns ripen in a special season

0:00:20.150,0:00:25.425
然后把它摘下来了之后如果没有方法去保存很快它就干了
After harvesting, they will dry soon if not preserved properly

0:00:25.425,0:00:27.075
很快这个味道就挥发了
All the flavor will evaporate soon

0:00:27.075,0:00:29.450
这个花椒属于油性挥发的东西
as peppercorns are oil-soluble and volatile

0:00:29.450,0:00:30.975
就没有（鲜花椒的）味道了
So there's no flavor (of fresh peppercorns) any more

0:00:30.975,0:00:34.050
然后今天跟大家分享一下这个保存的一些方法
Today, I'd like to share some methods to preserve it

0:00:34.225,0:00:37.325
我们这个花椒现在像这样子抽完真空
As you see, these peppercorns are vacuum sealed

0:00:37.325,0:00:41.150
抽了真空之后就放在那个冰柜里面把它冻硬
Vacuum seal, and then store it in a freezer

0:00:41.150,0:00:46.025
冻硬了之后的话这个可以保存 最长可以保存一年半以上
It can be stored frozen for 1.5 years or longer

0:00:46.025,0:00:49.350
这个是我目前知道的保存的时间最长的
As far as I know, that's the longest preservation

0:00:49.425,0:00:51.075
如果不是长期保存
If it's not for a long term preservation

0:00:51.075,0:00:53.000
可以把它放到一个容器里面
we can put them in a container

0:00:53.000,0:00:54.500
倒上一些植物油
and pour some vegetable oil

0:00:54.500,0:00:56.775
然后再放到冰柜里面密封保存
Then seal it, and leave it in a freezer

0:00:56.775,0:01:00.200
这样子的话可以保存一个月到三个月之间
In this way, it can be stored for 1 to 3 months
