### ISSUE TITLE
【美食作家王刚】鲜椒千层肚 - https://youtu.be/uF_Cl5uumQA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#678]
【美食作家王刚】鲜椒千层肚 - https://youtu.be/uF_Cl5uumQA
视频时长 5:16，预计发布时间为北京时间2月20日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.260,0:00:01.620
大家好 我是王刚

0:00:01.620,0:00:03.480
本期视频我给大家分享一道家常菜

0:00:03.800,0:00:05.500
鲜椒千层肚

0:00:05.920,0:00:08.180
首先我们准备千层肚400克

0:00:08.675,0:00:12.350
将千层肚从中间切开之后再翻面横切成细丝备用

0:00:12.450,0:00:15.600
不喜欢细丝的同学也可以将其改刀切成片

0:00:24.675,0:00:27.450
然后将切好的千层肚放入盆中

0:00:28.575,0:00:31.325
盆中再加入适量的清水没过千层肚

0:00:31.325,0:00:34.525
加入白醋40克搅拌均匀浸泡10分钟备用

0:00:34.525,0:00:37.125
这一步的目的是中和千层肚的碱性

0:00:37.125,0:00:39.350
同时也减少千层肚的异味

0:00:40.900,0:00:43.275
下一步开始准备垫底的辅料

0:00:43.450,0:00:46.200
准备大白菜几片用手撕成小片备用

0:00:49.125,0:00:51.350
准备凤尾1颗切成小条备用

0:01:01.425,0:01:03.900
准备适量的黄豆芽放入碗中备用

0:01:06.000,0:01:08.600
最后准备几根香芹切成小段备用

0:01:17.600,0:01:19.625
下一步开始准备料头

0:01:19.750,0:01:22.850
准备大蒜和仔姜各30克切成片备用

0:01:32.325,0:01:34.725
准备小米辣30克切成片备用

0:01:40.975,0:01:43.225
准备二荆条几根切成小片备用（约40克）

0:01:48.625,0:01:51.000
准备油泡（鲜）青花椒30克备用

0:01:53.025,0:01:55.750
最后准备火锅底料35克切散备用

0:01:55.750,0:01:58.450
不喜欢红汤的同学可以不加火锅底料

0:01:58.450,0:02:00.425
也可以改用鸡汁代替

0:02:02.025,0:02:05.100
10分钟之后将千层肚捞出沥干水份备用

0:02:08.850,0:02:10.325
下一步开始制作

0:02:10.675,0:02:14.075
首先我们在锅中加入适量的清水开大火烧开

0:02:18.350,0:02:20.300
中途加入一大勺食用盐（约5克）

0:02:26.550,0:02:30.425
大火烧开之后将所有准备好的垫底辅料下锅焯水2分钟

0:02:30.425,0:02:32.750
这一步的目的是将辅料煮至断生

0:02:32.750,0:02:35.350
辅料下锅之后再加入适量的植物油

0:02:41.850,0:02:44.725
焯水2分钟之后捞出放入盆中垫底备用

0:02:52.600,0:02:55.050
锅中再次加入适量的清水烧开

0:02:56.800,0:02:58.475
中途加入少许的白醋

0:02:58.500,0:03:00.950
然后将千层肚下锅烫10秒钟

0:03:00.950,0:03:04.300
同学们切记这一步的目的不是将千层肚煮熟

0:03:04.300,0:03:06.100
而是去除一些异味

0:03:13.350,0:03:15.475
10秒钟之后倒出控水备用

0:03:23.750,0:03:25.450
下一步开始制作红汤

0:03:25.450,0:03:27.050
首先我们把锅烧热

0:03:27.050,0:03:29.250
锅烧热之后加入适量的植物油（约35克）

0:03:38.300,0:03:41.875
油温4成热之后将准备好的所有料头下锅（姜蒜片、火锅底料、青花椒）

0:03:45.900,0:03:48.950
料头下锅之后转中小火将其炒香炒化

0:03:52.375,0:03:55.600
底料炒化之后加入适量的清水开大火烧开

0:04:02.100,0:04:04.225
大火烧开之后开始调味

0:04:05.050,0:04:07.125
锅中加入食用盐1勺（约4克）

0:04:07.625,0:04:09.075
加入少许白糖

0:04:09.575,0:04:11.125
加入胡椒粉1勺（约1克）

0:04:11.675,0:04:13.125
加入味精1勺（约2克）

0:04:17.825,0:04:21.625
调好味之后将准备好的鲜辣椒和千层肚下锅烫30秒钟

0:04:21.625,0:04:25.175
同学们千层肚不适合煮太久否则容易变老

0:04:29.275,0:04:32.175
然后在起锅之前再加入适量的藤椒油（约4克）

0:04:38.550,0:04:41.050
30秒钟之后将其捞出放入盆中

0:04:41.050,0:04:43.075
最后再加入适量的原汤

0:04:48.520,0:04:51.280
一道非常美味的鲜椒千层肚就制作完成

0:04:58.940,0:05:14.960
下面开始技术总结
第一，千层肚可以切丝也可以切片，同学们可以按照自己喜好操作
第二，此菜可以用鸡汁代替火锅底料
第三，千层肚不能煮太久，否则容易缩水变得难嚼
鲜椒千层肚的技术总结完毕

**Comment by WuStevenShengyang** [comment]
我來吧

**Comment by immoonancient** [comment]
已发布
