### ISSUE TITLE
[华农兄弟] 华农兄弟看下新场的小黄狗还有兄弟的肥猫再去山上挖竹笋 - https://youtu.be/DwsLYD3n9Jk

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#686]
https://youtu.be/DwsLYD3n9Jk
<p>&#35270;&#39057;&#21457;&#24067;&#20110; February 18, 2020 at 07:42PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/DwsLYD3n9Jk

#华农兄弟：看下新场的小黄狗，还有兄弟的肥猫，再去山上挖竹笋
#Huanong Brothers: We have a look at the doggies at our new site, and also our buddy's big fat cat. Then we go onto the hill to get some bamboo shoots.

0:00:00.280,0:00:00.800
# 狗
Doggy!

0:00:02.500,0:00:03.000
# 狗
Doggy!

0:00:05.580,0:00:06.080
# 狗
Doggy!

0:00:07.560,0:00:08.060
# 狗
Doggy!

0:00:13.740,0:00:15.320
# 你看  上次帶下來的小狗
Look! This is one of the doggies that we brought here last time.

0:00:16.120,0:00:17.240
# 現在那麼大啦
He's already that big now,

0:00:18.460,0:00:19.440
# 現在變黃啦
and has turned brown.

0:00:20.620,0:00:23.240
# 以前都是灰色的  嗯  現在都變黃色啦
He used to be grey. Um, but now he has turned brown.

0:00:24.640,0:00:27.080
# 戴著口罩  我戴著口罩它不認識我
With the mask, he can't recognize me as I'm wearing the mask.

0:00:27.620,0:00:28.640
# 叫它它不過來
He doesn't come even when I call him.

0:00:29.300,0:00:29.800
# 是不是
Am I right?

0:00:30.200,0:00:31.280
# 叫你你不過來啊
You were ignoring my call.

0:00:32.960,0:00:34.160
# 是啊  過來
Yes, you are. Come here!

0:00:34.880,0:00:36.320
# 不(用)[SIC]可以這樣子的
C'mon! It's not nice!

0:00:41.200,0:00:42.720
# 你看  給點草給你吃要不要
Look! Shall I give you some grass?

0:00:44.260,0:00:45.380
# 這草很好吃的哦
The grass is really tasty!

0:00:47.360,0:00:48.040
# 打滾啊
He's rolling.

0:00:48.080,0:00:48.580
# 啊
Ah!

0:00:48.760,0:00:50.400
# 賴皮  耍賴了哈
He's begging my attention, shamelessly, ha!

0:01:02.980,0:01:03.740
# 你妹妹呢
Where is your sister?

0:01:04.080,0:01:04.580
# 狗
Doggy!

0:01:05.660,0:01:07.040
# 狗  來啦  來啦
Doggy! She's coming, she's coming!

0:01:08.060,0:01:08.680
# 它妹妹
His sister

0:01:12.740,0:01:14.420
# 我戴著口罩它不認識我啊
She can't recognize me as I'm wearing the mask.

0:01:16.220,0:01:17.480
# 你看  它們兩個又要打架
Look! They're starting a fight again.

0:01:18.440,0:01:18.940
# 過來
Come here!

0:01:20.220,0:01:20.720
# 過來
Come here!

0:01:23.560,0:01:24.180
# 小狗
Doggies!

0:01:25.480,0:01:26.220
# 過來
Come here!

0:01:27.640,0:01:28.140
# 過來
Come here!

0:01:31.560,0:01:32.220
# 干架啦
So they start fighting.

0:01:36.000,0:01:37.240
# 太調皮啦  它們兩個
These two kids are simply too naughty!

0:01:42.840,0:01:44.820
# 你看  兄弟的貓 現在都好胖啦
Look! My buddy's cat, is already that fat now.

0:01:45.780,0:01:46.320
# 喵
Meow!

0:01:47.440,0:01:48.080
# 喵
Meow!

0:01:50.080,0:01:51.740
# 我不去  一去到它就跑啦
I'll leave it alone. It will run away if I get any closer.

0:01:52.840,0:01:55.400
# 這個貓差不多五六斤哦  那麼大
This cat is almost three kilograms, so big.

0:01:57.240,0:01:57.940
# 喵
Meow!

0:01:59.320,0:02:00.080
# 喵
Meow!

0:02:01.840,0:02:03.420
# 老是在叫 不知道叫甚麼
It's always yelping, but who knows why.

0:02:08.680,0:02:09.180
# 喵
Meow!

0:02:10.840,0:02:11.520
# 喵
Meow!

0:02:13.140,0:02:13.880
# 摸一摸你
Let me touch you.

0:02:14.440,0:02:15.140
# 喵
Meow!

0:02:16.540,0:02:17.040
# 喵
Meow!

0:02:17.720,0:02:19.360
# 摸都不要我摸  跑啦
No, it doesn't allow. It runs away.

0:02:23.880,0:02:24.480
# 喵
Meow!

0:02:27.640,0:02:28.200
# 過來
Come here!

0:02:29.280,0:02:29.880
# 握個手
Shake hand with me!

0:02:34.800,0:02:35.440
# 跑啦
It runs away,

0:02:36.300,0:02:37.020
# 不要我摸
from my touch.

0:03:00.580,0:03:02.640
# 大家好  今天天氣很不錯哦
Hi everyone! The weather today is really not bad.

0:03:02.800,0:03:05.160
# 我們上山挖點那個竹笋下來吃
Let's go onto the hill and get some, you know, some bamboo shoots.

0:03:06.240,0:03:07.300
# 就在這上面一點
It's just a bit up there.

0:03:13.720,0:03:14.780
# 從這裡上去
Let's go up from here.

0:03:28.680,0:03:31.080
# 挖了一天  一個竹笋都沒挖到
I've been digging for a whole day. But not even a single bamboo shoot is found.

0:03:32.000,0:03:34.440
# 你看 這個大葉蘭  這個蘭花(註︰找不到一個合理的「大葉蘭」翻譯，大葉蘭是人民幣上的水印，有人知道英文是甚麼嗎？)
Look! This is "Da Yelan" (Lit: big leave orchid, a local plant), it's orchid.

0:03:35.540,0:03:37.140
# 挖回去  自己種
Let me dig it out, and plant it at my place.

0:03:39.280,0:03:40.460
# 這個很靚的哦  這個
It's really beautiful, this orchid.

0:03:43.740,0:03:44.740
# 竹笋沒挖到
No bamboo shoots.

0:03:45.280,0:03:46.800
# 總不能空著手回去吧
But getting back home empty-handed is not an option.

0:03:49.400,0:03:50.880
# 你看  是不是很靚的
Look! Isn't it beautiful?

0:03:51.360,0:03:52.220
# 這個蘭花
This orchid

0:04:05.200,0:04:06.520
# 我拿回去自己種
I'll plant it at my place.

0:04:14.160,0:04:15.220
# 收工收工收工
Go, go, go!

0:04:17.820,0:04:18.940
# 好啦 回去啦
Alright! Let's go back.

0:04:20.160,0:04:22.280
# 路又好遠啊 我們走了好遠
It's a long way. We've gone far far away.

0:04:23.840,0:04:25.840
# 有一個這個過山車坐一下就好啦  (註︰他這個「過山車」應該是指走在山去的四驅車之類的吧)
I wish I had a mountain truck.

0:04:26.920,0:04:27.720
# 沒有
But I don't have.

0:04:28.000,0:04:29.460
# 啊 慢慢走回去吧
Ah! Let's go on foot, slowly.

0:04:30.840,0:04:31.680
# 挖個坑來
Let me dig a pit,

0:04:33.780,0:04:35.140
# 把這個蘭花種下來
and plant the orchid here,

0:04:35.820,0:04:37.140
# 種在這院子裡面
plant it in this yard.

0:04:56.820,0:04:57.440
# 好啦
Alright!

0:04:58.680,0:05:00.120
# 今天的視頻就到這裡啦
The video ends here.

0:05:02.700,0:05:03.800
# 你看  很靚的哦
Look! It's really beautiful!

**Comment by immoonancient** [comment]
看你没上传，帮你上传了

**Comment by vincenthychow** [comment]
已發佈
