### ISSUE TITLE
【美食作家王刚】折耳根炒腊肉 - https://youtu.be/Ufpzx6onAK8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#687]
【美食作家王刚】折耳根炒腊肉 - https://youtu.be/Ufpzx6onAK8
视频时长 3:13，预计发布时间为北京时间2月22日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.480,0:00:01.720
哈喽大家好 我是王刚

0:00:01.760,0:00:03.680
本期视频我跟大家分享一道家常菜

0:00:04.520,0:00:05.860
折耳根炒腊肉

0:00:06.580,0:00:08.680
首先我们准备折耳根（四川叫法）300克

0:00:08.950,0:00:11.175
同学们折耳根也叫做鱼腥草

0:00:11.175,0:00:14.075
鱼腥草可以作为中药也可以作为食材

0:00:14.075,0:00:16.000
将鱼腥草掐成小段备用

0:00:26.450,0:00:29.175
然后准备1块煮好的腊肉切成片备用

0:00:29.200,0:00:31.900
不喜欢腊肉的同学也可以用五花肉代替

0:00:37.275,0:00:39.025
下一步开始准备料头

0:00:39.475,0:00:42.125
准备大蒜几颗拍散之后剁碎备用

0:00:50.750,0:00:52.850
准备生姜1小块剁碎备用

0:00:58.725,0:01:01.050
准备几颗干辣椒剪成小节备用

0:01:01.050,0:01:03.750
不能吃辣的同学也可以用大红椒代替

0:01:05.300,0:01:07.350
再加入适量的青花椒备用

0:01:08.475,0:01:11.800
最后准备蒜苗几根轻轻拍散之后切成小段备用

0:01:18.800,0:01:20.175
下一步开始制作

0:01:20.550,0:01:22.275
首先我们把锅烧热

0:01:22.275,0:01:24.725
锅烧热之后加入适量的底油

0:01:24.725,0:01:28.025
油温5成热之后加入切好的腊肉和料头下锅爆香（姜蒜粒、干辣椒、花椒）

0:01:46.300,0:01:49.300
将腊肉炒香爆出油之后再将鱼腥草下锅

0:01:49.300,0:01:51.100
然后开中火翻炒几下

0:01:59.675,0:02:02.125
鱼腥草炒至6成熟之后开始调味

0:02:02.825,0:02:05.625
锅中加入生抽酱油4克从锅边淋入

0:02:06.850,0:02:08.850
加入陈醋1克从锅边淋入

0:02:10.575,0:02:12.150
加入少许食用盐（约1克）

0:02:14.125,0:02:15.675
加入白糖1克

0:02:17.075,0:02:19.725
调好味之后再加入切好的蒜苗下锅

0:02:19.725,0:02:23.100
然后再加入少许的明油翻炒均匀即可出锅装盘

0:02:43.600,0:02:46.760
一道风味独特的折耳根炒腊肉就制作完成

0:02:54.720,0:03:12.720
下面开始技术总结
第一，翻炒的鱼腥草只能选根部不能要叶子，因此必须将其分开
第二，鱼腥草不能炒得太熟，否则成菜变得发面
第三，除了炒腊肉之外还可以炒猪肉、牛肉，也可以切碎之后炒肉沫
腊肉炒折耳根的技术总结完毕

**Comment by immoonancient** [comment]
已发布
