### ISSUE TITLE
【美食作家王刚】儿菜炒五花肉 - https://youtu.be/A076A87CbL4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#688]
【美食作家王刚】儿菜炒五花肉 - https://youtu.be/A076A87CbL4
视频时长 2:35，预计发布时间为北京时间2月23日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.300,0:00:01.560
哈喽大家好 我是王刚

0:00:01.560,0:00:03.560
本期视频我跟大家分享一道家常菜

0:00:03.880,0:00:05.060
儿菜爆五花肉

0:00:05.680,0:00:07.750
首先我们准备儿菜一颗

0:00:07.750,0:00:10.650
将其超生的小儿菜用手掰下来备用

0:00:13.075,0:00:16.200
然后用小刀去掉儿菜根部比较老的皮

0:00:18.475,0:00:21.825
去掉皮之后将儿菜清洗干净切成薄片备用

0:00:21.825,0:00:24.900
不喜欢生炒的同学也可以直接用清水煮

0:00:28.750,0:00:31.425
准备五花肉去皮之后切成薄片备用

0:00:31.475,0:00:34.550
同学们也可以用腊肉或者腊肠代替猪肉

0:00:34.550,0:00:36.725
还可以将儿菜直接清炒

0:00:42.050,0:00:43.825
下一步开始准备料头

0:00:44.275,0:00:46.225
准备大蒜几颗拍散备用

0:00:50.375,0:00:52.525
准备适量的小米辣切成片备用

0:00:54.250,0:00:55.500
下一步开始制作

0:00:55.675,0:00:57.175
首先我们把锅烧热

0:00:57.300,0:01:00.025
锅烧热之后加入少许的食用油滑锅

0:01:07.200,0:01:10.300
油温烧热之后加入切好的五花肉翻炒1分钟

0:01:10.575,0:01:13.025
这一步的目的是爆出五花肉的猪油

0:01:21.875,0:01:24.425
五花肉爆香之后加入小半勺食用盐

0:01:24.425,0:01:27.075
再加入切好的料头和儿菜下锅

0:01:27.075,0:01:29.825
然后转中火翻炒3分钟炒至断生

0:01:40.325,0:01:42.125
3分钟之后开始调味

0:01:42.125,0:01:43.850
锅中加入食用盐1勺（约2.5克）

0:01:44.775,0:01:46.225
加入少许白糖

0:01:47.850,0:01:50.950
最后加入适量的生抽酱油（约3克）从锅边淋入翻炒几下

0:01:50.950,0:01:53.125
翻炒均匀之后即可出锅装盘

0:02:06.580,0:02:09.740
一道非常美味的时蔬炒猪肉就制作完成

0:02:17.600,0:02:34.760
下面开始技术总结
第一，儿菜可以切片也可以切成细丝炒制
第二，喜欢（软）嫩的同学可以直接加入少许清水焖煮
第三，此菜为生炒家常做法，喜欢清淡的同学可以焯水之后再急火短炒
儿菜炒五花肉的技术总结完毕

**Comment by immoonancient** [comment]
已发布
