### ISSUE TITLE
[华农兄弟] 西西瓜瓜的崽 - https://youtu.be/UneqS84USYU

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#70]
https://youtu.be/UneqS84USYU

时间关系我在 YT 直接做了，希望能把那位字幕君拉进我们字幕组

**Comment by GUThe** [comment]
我在YT点了通过了。但是好像没看到你发的广告？找过intro/sub/comment了
@immoonancient

**Comment by GUThe** [comment]
我重新发一个吧
