### ISSUE TITLE
【美食作家王刚】凉拌菱角菜 - https://youtu.be/Wtj8-kc72_U

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#708]
【美食作家王刚】凉拌菱角菜 - https://youtu.be/Wtj8-kc72_U
视频时长 2:07，预计发布时间为北京时间2月25日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.240,0:00:01.420
哈喽大家好我是王刚

0:00:01.420,0:00:03.380
本期视频我给大家分享一道家常菜

0:00:03.860,0:00:04.960
凉拌菱角菜

0:00:05.500,0:00:07.675
首先我们准备菱角菜2颗

0:00:07.675,0:00:10.525
同学们菱角菜其实就是制作榨菜的原材料

0:00:10.525,0:00:12.775
然后将其老的经络撕掉备用

0:00:12.775,0:00:15.700
同学们凉拌的菱角菜必须先晾晒几天

0:00:15.700,0:00:17.675
这样才能够轻易地撕下筋膜

0:00:22.975,0:00:26.375
然后将菱角菜平刀切成厚片再切成粗丝备用

0:00:26.375,0:00:28.900
嫌麻烦的同学也可以直接切成薄片

0:00:36.550,0:00:38.325
下一步开始初加工

0:00:38.725,0:00:40.925
首先在盆中加入食用盐6克

0:00:44.950,0:00:46.475
加入白糖4克

0:00:50.925,0:00:52.525
加入白醋6克

0:00:54.375,0:00:56.850
然后将其抓拌均匀出水30分钟

0:01:05.400,0:01:08.150
30分钟之后捞出挤干水分备用

0:01:11.375,0:01:12.850
下一步开始调味

0:01:13.275,0:01:15.425
碗中加入适量的刀口辣椒面（约5克）

0:01:15.425,0:01:18.850
没有刀口辣椒的同学也可以用普通辣椒面代替

0:01:20.100,0:01:21.975
碗中加入花椒面1勺（约2克）

0:01:22.825,0:01:24.325
加入白糖1勺（约2克）

0:01:25.250,0:01:27.575
然后搅拌均匀即可装盘上菜

0:01:36.400,0:01:39.700
一道香辣爽脆的凉拌菱角菜就制作完成

0:01:47.000,0:02:06.680
下面开始技术总结
第一，切好的菱角菜必须加入盐糖白醋
刹水，这一步的目的是保证菜品的爽脆
第二，刹好水之后可以不用清洗直接加料凉拌
第三，不喜欢吃辣的同学可以不加辣椒和花椒
只需加入盐和白糖即可
凉拌菱角菜的技术总结完毕

**Comment by immoonancient** [comment]
@Yibing-Du 请前来认领

**Comment by Yibing-Du** [comment]
认领

**Comment by Yibing-Du** [comment]
bot, please upload
0:00:00.240,0:00:01.420
哈喽大家好我是王刚
Hello everyone, I'm Wang Gang

0:00:01.420,0:00:03.380
本期视频我给大家分享一道家常菜
In this video, I'll teach you a common dish

0:00:03.860,0:00:04.960
凉拌菱角菜
Spicy mustard plant stem salad

0:00:05.500,0:00:07.675
首先我们准备菱角菜2颗
First, prepare two mustard plant stems

0:00:07.675,0:00:10.525
同学们菱角菜其实就是制作榨菜的原材料
Mustard plant stem is actually what Chinese pickle, "Zha Cai", is made of

0:00:10.525,0:00:12.775
然后将其老的经络撕掉备用
Remove the hard part on the surface 

0:00:12.775,0:00:15.700
同学们凉拌的菱角菜必须先晾晒几天
The stems must be aired for several days before being cooked

0:00:15.700,0:00:17.675
这样才能够轻易地撕下筋膜
This makes removing the surface part much easier

0:00:22.975,0:00:26.375
然后将菱角菜平刀切成厚片再切成粗丝备用
Then cut the veggies into thick slices and then thick threads

0:00:26.375,0:00:28.900
嫌麻烦的同学也可以直接切成薄片
If that's too much, you can cut them into thin slices

0:00:36.550,0:00:38.325
下一步开始初加工
The next step is the pre-processing

0:00:38.725,0:00:40.925
首先在盆中加入食用盐6克
First, add 6g of salt to the bowl

0:00:44.950,0:00:46.475
加入白糖4克
Add 4g of sugar

0:00:50.925,0:00:52.525
加入白醋6克
Add 6g of rice vinegar

0:00:54.375,0:00:56.850
然后将其抓拌均匀出水30分钟
Then mix them for 30 minutes to remove the water from the veggies

0:01:05.400,0:01:08.150
30分钟之后捞出挤干水分备用
After 30 minutes, take the veggies out and squeeze out the water

0:01:11.375,0:01:12.850
下一步开始调味
The next step is to season the veggies

0:01:13.275,0:01:15.425
碗中加入适量的刀口辣椒面（约5克）
Add some Daokou chili powder to the bowl (around 5g)

0:01:15.425,0:01:18.850
没有刀口辣椒的同学也可以用普通辣椒面代替
If you don't have Daokou chili powder, you can use any other kind of chili powder

0:01:20.100,0:01:21.975
碗中加入花椒面1勺（约2克）
Add a teaspoon of ground Sichuan peppercorn to the bowl (around 2g)

0:01:22.825,0:01:24.325
加入白糖1勺（约2克）
Add a teaspoon of sugar (around 2g)

0:01:25.250,0:01:27.575
然后搅拌均匀即可装盘上菜
Then mix everything and lay it out in the plate

0:01:36.400,0:01:39.700
一道香辣爽脆的凉拌菱角菜就制作完成
Now, we've finished making this spicy and refreshing spicy mustard plant stem salad

0:01:47.000,0:02:06.680
下面开始技术总结
第一，切好的菱角菜必须加入盐糖白醋
刹水，这一步的目的是保证菜品的爽脆
第二，刹好水之后可以不用清洗直接加料凉拌
第三，不喜欢吃辣的同学可以不加辣椒和花椒
只需加入盐和白糖即可
凉拌菱角菜的技术总结完毕

Now, let's summarize the key techniques:
First, we need to add the salt. sugar, and rice vinegar mixture to the cutted veggies to remove the water, making sure the final product is refreshing and crispy
Secondly, we don't need to rinse the veggies after the water removal step
Thirdly, If you don't like spicy food, you don't need to add chili and peppercorn; salt and sugar will be enough.
Above are all the techniques for the spicy mustard plant stem salad

**Comment by immoonancient** [comment]
已发布
