### ISSUE TITLE
厨师秀频道翻译？ https://www.youtube.com/channel/UC7D2fGKMUWge3yac4YRELPA

### ISSUE THREAD

**Issue by NoraZheng** [immoonancient/YTSubtitles#718]
关注蛮久了 Up主是专业厨师 做菜有功底 而且蛮幽默的 菜谱都很适合家庭制作 
经常有两个很有趣的孩子试吃
关注不多 Youtube不到50k 国内平台数据不知道
有没有兴趣？
近期作品：
[炸鸡腿](https://www.youtube.com/watch?v=nRduAq2YVhk)
[红烧鸡翅](https://www.youtube.com/watch?v=MJDOdjLI9dA)

**Comment by immoonancient** [comment]
下次再发个问卷看看群里对这个频道以及别的频道的意向如何吧

**Comment by vincenthychow** [comment]
西瓜頭條綜合有185萬  (單一最高70多萬)
B站有13.4萬
算不俗喔

**Comment by immoonancient** [comment]
提名贴: https://github.com/immoonancient/YTSubtitles/issues/1063#issuecomment-629846071
