### ISSUE TITLE
[华农兄弟] 华农兄弟换个新铁门再去河边种点象草顺便摘点蕨菜 - https://youtu.be/BnMU-j0Rexg

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#755]
https://youtu.be/BnMU-j0Rexg
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 6, 2020 at 11:32AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/BnMU-j0Rexg

#华农兄弟：换个新铁门，再去河边种点象草，顺便摘点蕨菜
#Huanong Brothers: Let's install a new gate and then some plant some elephant grass at the riverside. Then, let's come back with some eagle ferns.

0:00:00.000,0:00:00.780
# 大家好
Hi everyone!

0:00:01.360,0:00:03.260
# 大個門都已經被那個小狗哇
The gate was already damaged by the, you know, the puppies,

0:00:03.660,0:00:04.560
# 被爬壞啦
always climbed the gate.

0:00:04.860,0:00:05.780
# 所以現在
So now,

0:00:06.200,0:00:08.640
# 現在我們叫兄弟過來  裝一下這個門
now we've asked our buddies to come over, and have the new gate installed.

0:00:11.780,0:00:13.020
# 這裝上去就很好看啦
It will look really nice when it's done.

0:00:18.240,0:00:19.400
# 現在快裝好一扇啦
Now one is nearly done.

0:00:19.560,0:00:20.400
# 還要對好位甲置
They still need to match the positions.

0:00:20.640,0:00:22.480
# 對好位就裝好啦  裝好就很好看啦
Then it will be done and it will look really nice.

0:00:23.180,0:00:26.220
# 到時就裡面  裡面就看不到的  看王到裡面的
Then the inside, the inside can' be seen, can't be seen from outside.

0:01:42.720,0:01:44.560
# 今天天氣比較冷啦  你看
Today is rather cold. Look!

0:01:45.140,0:01:46.120
# 小狗都靠著它
The puppies are leaning on her,

0:01:46.480,0:01:48.300
# 它奶奶  它老媽在睡覺 
sleeping next to their grandma, their mother.

0:01:54.200,0:01:55.940
# 你看  這個鐵門已經裝好啦
Look! The gate is now installed.

0:01:57.480,0:01:58.440
# 這很漂亮哦
It's really pretty.

0:02:01.040,0:02:01.980
# 看不到裡面啦
The inside can't be seen.

0:02:02.180,0:02:03.760
# 把門關起來就看不到裡面啦
The inside can't be seen when the gate is closed.

0:02:04.560,0:02:05.920
# 小狗也跑不出來啦
And the doggies can't run away.

0:02:11.000,0:02:12.420
# 小狗它們也跑不出來啦
The doggies can no longer run away.

0:02:13.720,0:02:14.480
# 這個
This is,

0:02:15.300,0:02:16.280
# 紅象草哦
red elephant grass, you know.

0:02:16.700,0:02:19.120
# 我們拿到田裡面去種一些這紅象草來
Let's take it to the field and plant some red elephant grass.

0:02:19.700,0:02:21.900
# 我們這有幾棵  其它地方我都沒種
I have just a few here, and nowhere else.

0:02:22.620,0:02:24.720
# 我把它種多一點  現在都長嫩芽啦
Let's plant a bit more. They have already started sprouting.

0:02:25.400,0:02:26.420
# 這有好多嫩芽
Here are a lot of sprouts.

0:02:31.860,0:02:32.940
# 全長嫩芽啦
All have already started sprouting.

0:02:36.040,0:02:38.520
# 你看 都長嫩芽啦  一節一節的
Look! It's already sprouting. Look at the joints.

0:02:38.880,0:02:40.440
# 我們插上去它就會生啦
It will start growing once we stick it in.

0:02:40.880,0:02:41.960
# 插到田裡面去
I mean, stick it into the field.

0:02:45.480,0:02:48.160
# 原來就是一棵的  現在長那麼多
There was only one at the beginning. But now there are so many.

0:02:48.320,0:02:49.900
# 今年又把這些種下去的話
After planting all these this year,

0:02:50.360,0:02:52.340
# 幾百棵  幾千棵都出來啦
it might become hundreds, or thousands of them.

0:03:00.200,0:03:01.880
# 跑小朋友
No running, kid!

0:03:01.920,0:03:03.100
# 還那麼小你就亂跑
You're still a kid but you're already running  here and there.

0:03:15.140,0:03:16.440
# 把這些丟到車上去
Let me throw all these onto the car.

0:03:24.420,0:03:27.180
# 你看  把它扛那麼個  荒地裡面去種
Look! I'm taking them to the abandoned field and have them planted there.

0:03:27.840,0:03:28.440
# 在前面
It's just in front of us.

0:03:40.600,0:03:42.940
# 這一片都是荒的  都是雜草
This whole area is abandoned. There are only weeds.

0:03:43.480,0:03:46.040
# 但是這個草長起來的話  這個雜草就會死掉的
But the weeds would die out once the grass starts growing.

0:03:47.680,0:03:49.160
# 種這個很簡單的  就這樣
Planting it is a no-brainer. That's it.

0:03:53.520,0:03:54.400
# 這幾節
These chunks,

0:03:55.720,0:03:57.360
# 隨便插  插在這附近
simply stick them in, anywhere nearby.

0:03:59.500,0:04:00.860
# 插下去  插下穩這裡
Stick it in. It's shaky here.

0:04:02.080,0:04:02.800
# 你看  這個
Look! This one,

0:04:03.300,0:04:04.260
# 這種就是插在這
this one needs to be stuck into,

0:04:04.320,0:04:06.120
# 有泥土的地方就插在泥土上去
into the soil, if there's soil.

0:04:06.760,0:04:07.980
# 如果沒泥土的話
If there's no soil,

0:04:09.200,0:04:10.480
# 就是用鋤頭
then I need a hoe.

0:04:35.460,0:04:36.780
# 把這個插下去就好啦
Stick it in, and it's done.

0:04:48.580,0:04:50.820
# 這個象草也可以鞏固那個水土流失哦 (註︰應該是「鞏固泥土防止水土流失」吧)
The elephant grass can also stabilize the soil and prevent it from being washed away.

0:04:51.000,0:04:53.400
# 這個大水一沖的話 有這個根話
The roots of the grass can catch the, well, the soil,

0:04:53.500,0:04:55.500
# 就把那個  沙土哇  留住
when the river overflows.

0:04:55.940,0:04:58.520
# 如果沒有這個的話  它就很容易把這個土掀掉
Without the roots, the soil would be easily peeled off,

0:04:58.680,0:04:59.560
# 沖到下面去
and washed away.

0:05:00.500,0:05:01.960
# 我在附近插一下
Let me stick a few more nearby.

0:05:10.700,0:05:12.100
# 你看  這河邊還有薄荷哦
Look! There are also mints on the riverside.

0:05:13.040,0:05:14.000
# 這個薄荷是
The mint is...

0:05:15.220,0:05:16.620
# 哇  好濃的薄荷味
Wa! A rich scent of mint!

0:05:17.680,0:05:20.360
# 是上 上遊  應該上遊沖下來這個根  就在這裡
is up, upstream, it should be washed down from the upstream, and then the roots,

0:05:20.720,0:05:22.500
# 生根發芽  那麼大一片
the roots sprouted here. There are so many of them.

0:05:22.900,0:05:24.380
# 下次我們摘點田螺來炒
Next time let's get some river snails and fry with the mint.

0:05:24.860,0:05:25.820
# 薄荷炒田螺
River snails fried with mint

0:05:26.440,0:05:27.120
# 很好吃的哦
Tasty!

0:05:27.520,0:05:28.380
# 你看  這個
Look! Here!

0:05:30.120,0:05:31.640
# 很漂亮的哦  這個薄荷
The mints are really pretty, you know.

0:05:36.660,0:05:38.480
# 這裡還好多艾草哦  這裡
Here's also a lot of mugwort, here.

0:05:39.080,0:05:40.480
# 旁邊插一棵下去
Let me stick one next to it,

0:05:43.100,0:05:44.080
# 這附近也可以
and also somewhere nearby.

0:05:53.260,0:05:54.760
# 這個是黑麥草哦
This is ryegrass.

0:05:55.180,0:05:57.780
# 這個餵魚  那魚很喜歡吃的  很嫩的這個
It can be used to feed the fish. The fish like it very much. It's really young.

0:05:58.080,0:05:59.140
# 你看  一搞就斷掉
Look! It can be easily torn.

0:05:59.820,0:06:01.500
# 而且特別有那種香味
And it also has a particularly strong scent,

0:06:02.020,0:06:03.300
# 那種植物的香味
scent of plant.

0:06:03.360,0:06:03.860
# 這裡
Here!

0:06:06.420,0:06:08.100
# 旁邊  插一棵下去
Let me stick one next to it.

0:06:18.260,0:06:19.340
# 這好多這個
There are a lot of, you know,

0:06:19.880,0:06:20.560
# 但是現在
eagle ferns.

0:06:22.060,0:06:22.840
# 現在等下  等下我來摘
But now...

0:06:24.080,0:06:25.640
# 把這個種好了再說
Not now, I'll pick them in a moment.

0:06:26.580,0:06:27.820
# 快下雨啦 你看  天都下雨啦
I'll have them all planted first.

0:06:53.240,0:06:55.300
# 我摘點那個牛尾節回去
It's gonna rain soon. Look! It starts raining.

0:06:56.620,0:06:58.160
# 回去炒
Let me get some eagle ferns back,

0:06:58.880,0:06:59.520
# 家裡沒  沒得青菜吃啦
and have them fried.

0:07:00.260,0:07:01.960
# 看看這  好多哇
I've run, run out of veggies at home.

0:07:03.340,0:07:04.980
# 摘到嫩的來
Look at here! There are a lot!

0:07:07.560,0:07:08.500
# 好嫩啊
Let me pick the young ones.

0:07:08.740,0:07:09.480
# 好多好嫩的  剛長出來的
They're really young.

0:07:12.640,0:07:14.820
# 你看
Many have just grown out from the soil, and are really young.

0:07:15.620,0:07:16.180
# 這樣就很好吃的哦
Look!

0:07:17.600,0:07:18.880
# 這是野菜
It will then be really tasty.

0:07:22.160,0:07:23.300
# 這個也叫野菜
This is wild veggie.

0:07:24.560,0:07:25.740
# 你看  這兩個就很嫩的
It's also called wild veggie.

0:07:32.000,0:07:34.060
# 你看  摘了那麼一點點
Look! These two are really young.

0:07:58.020,0:07:59.260
# 回去啦  夠一餐
Look! I've picked just a tiny little bit here.

0:07:59.720,0:08:00.800
# 
Let's go back. It's enough for a meal.
