### ISSUE TITLE
【美食作家王刚】猛火灶遮阳网 - https://youtu.be/BUKF0BI5KdU

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#757]
【美食作家王刚】给猛火灶装个遮阳网，农家硬核后厨正式上线！给四伯做个“炸鲜奶”犒劳他老人家，特别适合牙口不好的老人 - https://youtu.be/BUKF0BI5KdU
视频时长 10:02，预计发布时间为北京时间3月9日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:01.725,0:00:02.675
宽是好宽

0:00:03.075,0:00:03.800
宽是4米

0:00:04.175,0:00:04.650
差不多

0:00:08.700,0:00:13.144
那就走你那边来撒 这里

0:00:13.400,0:00:15.975
来撒 你拉着头子撒

0:00:23.700,0:00:26.925
我这样 我把它甩到这上面 等会来拉

0:00:26.925,0:00:28.800
拉来套（拴）在这底下

0:00:33.300,0:00:37.450
咿呀 我要是滚到这田头去要打得浇湿的哦

0:00:38.700,0:00:41.752
慢点 你鞋子是滑的 干脆把它脱了

0:00:42.050,0:00:44.500
下来 老子来

0:00:46.500,0:00:48.575
这绳子就合适噶 长短合适

0:00:49.175,0:00:50.575
使劲拉

0:00:50.625,0:00:51.575
那里款（卡）起的

0:00:51.750,0:00:53.575
伯爷那儿款起的

0:01:16.200,0:01:17.225
够了够了

0:01:21.125,0:01:23.075
嘿 这个整起还要得四伯爷

0:01:23.075,0:01:23.262
咋子要不得安

0:01:23.262,0:01:24.300
咋子要不得安

0:01:25.825,0:01:29.275
那没得事我给你炒两个菜在这阴凉坝（吃）

0:01:29.450,0:01:31.175
老子啤酒都没得

0:01:31.350,0:01:33.550
你要喝啥子啤酒我给你买就是

0:01:33.675,0:01:34.750
有的是酒屋头

0:01:34.850,0:01:36.575
有的是酒 伯娘说得对

0:01:41.650,0:01:43.375
就套在那里

0:01:43.375,0:01:44.294
这棵树上是不哦

0:01:44.294,0:01:45.374
在这里

0:01:48.125,0:01:49.575
要不要我给你掌（扶）一下哦

0:01:49.675,0:01:52.175
掌啥子掌哦 老子是飞天蜈蚣

0:01:55.325,0:01:56.525
你还多凶哦

0:01:56.675,0:01:57.900
那不是咋子

0:02:02.350,0:02:03.875
我给你甩上来哦

0:02:04.175,0:02:05.100
甩嘛

0:02:15.375,0:02:17.925
再站一梯上去嘛

0:02:18.125,0:02:19.775
你再站一梯上去 矮很了

0:02:19.775,0:02:20.525
我害怕

0:02:20.550,0:02:21.293
没得事的

0:02:21.293,0:02:23.085
哪里害怕哦老子恩是

0:02:23.085,0:02:24.600
我双手给你掌都的

0:02:25.150,0:02:27.575
233米跳下来都不害怕

0:02:27.575,0:02:29.493
这丁点儿（高度）老子

0:02:29.825,0:02:32.600
在这沟沟河头打烂船呐

0:02:34.650,0:02:35.327
安逸撒

0:02:35.327,0:02:35.650
安逸 可以

0:02:35.650,0:02:36.977
安逸 可以

0:02:37.850,0:02:39.325
一哈子凉快了很多

0:02:39.800,0:02:41.350
搭了遮阳棚当然了

0:02:41.650,0:02:42.600
狗东西麻雀儿

0:02:42.900,0:02:44.075
雀儿窝得屎噶

0:02:44.075,0:02:44.625
嗯

0:02:45.025,0:02:48.100
二天炒菜炒啊炒得它要窝点屎来给你加点料

0:02:48.125,0:02:48.900
哈哈 加点佐料

0:02:48.925,0:02:50.600
这哈遮阳棚挡住了没得事的

0:02:51.750,0:02:53.500
四伯爷还是可以哦

0:02:59.950,0:03:01.200
可以可以

0:03:02.300,0:03:03.610
还上得到台（面）了哈

0:03:03.610,0:03:04.550
嗯 可以

0:03:06.475,0:03:08.075
我给你炸个鲜奶嘛

0:03:08.475,0:03:10.275
随便

0:03:12.500,0:03:15.450
你是试这个灶的

0:03:15.575,0:03:17.100
是不是嘛

0:03:17.150,0:03:17.950
买了两瓶 两瓶来做

0:03:18.025,0:03:18.725
拔鲜奶

0:03:19.050,0:03:21.575
嘿嘿 拔鲜奶 炸鲜奶

0:03:22.925,0:03:23.475
哦

0:03:23.475,0:03:24.375
炸鲜奶

0:03:24.450,0:03:25.950
炸鲜奶哇

0:03:25.975,0:03:26.500
哦

0:03:27.100,0:03:29.225
就是你说炸来金黄金黄的那个呢

0:03:29.600,0:03:30.275
啊

0:03:31.950,0:03:32.800
倒两瓶

0:03:34.000,0:03:37.000
你下次想吃（炸）酸奶也可以 纯牛奶也可以

0:03:37.725,0:03:41.925
酸奶 酸的拿啥子来配呢

0:03:42.725,0:03:46.500
糖撒 甜的你吃得不嘛

0:03:47.300,0:03:49.125
甜的吃得

0:03:49.975,0:03:52.950
你看这里一斤鲜奶

0:03:54.125,0:03:55.775
放这个淀粉

0:03:56.025,0:03:58.375
这个包谷粉 玉米淀粉60克

0:04:00.175,0:04:02.900
两勺 两勺多一点点

0:04:02.950,0:04:04.662
吃甜点吗不吃嫩甜

0:04:04.725,0:04:07.125
不吃嫩甜 吃甜很了不安逸

0:04:07.925,0:04:08.850
差不多咯

0:04:08.875,0:04:10.650
不得 这个炸出来没得那么甜的

0:04:10.750,0:04:11.825
放五勺糖

0:04:11.875,0:04:14.375
把这个搅 搅匀了弄来煮

0:04:15.700,0:04:18.750
你这冷的（牛奶）白糖都化不了的嘛

0:04:18.750,0:04:20.300
煮来它就要化的嘛

0:04:22.475,0:04:24.025
走 我去开火

0:04:24.075,0:04:26.025
第一次（在家）弄哦 四伯爷

0:04:26.100,0:04:29.950
第一次弄技术要拿出来哦

0:04:30.125,0:04:37.175
你不要跟他们说的希尔糊涂的整来不规则撒我要涛人哦

0:04:37.650,0:04:39.900
你放心 害怕会让你涛人

0:04:40.100,0:04:42.825
是撒 你整来不规则我就要涛你

0:04:48.150,0:04:50.050
这哈就干起咯

0:04:50.050,0:04:52.975
干起嘛 我看你咋子干的嘛

0:05:08.025,0:05:09.575
看到没 粘（稠）了

0:05:10.700,0:05:14.552
煮粘了哒 煮粘了就可以了

0:05:19.707,0:05:21.307
可以吃了哇

0:05:22.500,0:05:24.025
这白白的

0:05:25.300,0:05:26.845
我摸哈看冷没有

0:05:26.845,0:05:29.025
好想 就冷咯

0:05:30.175,0:05:33.325
再冰它哈儿就冷了 就跟它冰凉粉样

0:05:34.175,0:05:35.775
四伯爷你看 这都冷了

0:05:35.775,0:05:37.000
还可以撒 结了皮了噶

0:05:37.050,0:05:37.850
啊 冷了

0:05:38.050,0:05:40.200
一般结了皮了基本上就可以要得了

0:05:40.401,0:05:42.350
看嘛 直接就可以把它拿起来

0:05:42.600,0:05:43.491
来了火的

0:05:44.125,0:05:45.325
可以可以可以

0:05:45.375,0:05:46.350
直接弄来切

0:05:47.475,0:05:49.098
哦哟 这个粘刀的

0:05:49.098,0:05:50.350
粘刀的 拿纸擦哈

0:05:50.475,0:05:51.025
用点水

0:05:51.675,0:05:53.875
我们切这个要是粘刀的话就弄点水

0:05:54.400,0:05:55.500
它有一点粘刀这个

0:05:57.125,0:05:58.575
那哈子就不粘了

0:05:58.600,0:05:59.900
好 又搞起水

0:06:05.925,0:06:07.325
好嘛 好好好

0:06:07.325,0:06:08.550
然后就是把它弄起

0:06:10.050,0:06:12.150
跟豆腐一样

0:06:14.000,0:06:16.600
把它分开 分开来裹

0:06:18.450,0:06:18.975
好

0:06:19.025,0:06:20.525
嘿 安逸安逸

0:06:20.550,0:06:21.500
尝一坨看

0:06:21.550,0:06:22.500
这哈都可以吃

0:06:22.525,0:06:24.950
你那菜刀沾了生水的

0:06:24.975,0:06:25.650
不关事

0:06:28.150,0:06:30.500
不吃不吃不吃 炸好了来吃

0:06:31.025,0:06:32.050
打两个蛋

0:06:35.550,0:06:38.575
嘿打蛋这个技术还拿给你学到了的哒

0:06:38.975,0:06:40.875
可以 你这个级别

0:06:41.125,0:06:41.950
单手打蛋

0:06:42.125,0:06:46.625
是啊 你打蛋的级别还是上等级别 我看一哈

0:06:48.350,0:06:50.025
我在视频头都看得到

0:06:50.025,0:06:52.600
一敲手一捏就起来了

0:06:53.325,0:06:54.000
可以

0:06:54.125,0:06:54.925
可以噶

0:06:55.850,0:06:58.475
好 现在手套戴好了开始裹

0:07:03.750,0:07:05.350
然后再裹这个

0:07:07.075,0:07:07.700
可以撒

0:07:07.750,0:07:10.684
可以可以 嘿嘿安逸

0:07:11.950,0:07:13.300
这个是啥子做的安

0:07:13.550,0:07:14.775
这个是面包糠

0:08:23.675,0:08:24.900
尝一哈看嘛

0:08:29.925,0:08:33.875
是不是外面是脆的 里头还是嫩的

0:08:35.000,0:08:35.725
安逸

0:08:35.975,0:08:38.575
这个就是我跟你说的那个炸酸奶

0:08:38.900,0:08:40.525
鲜奶 不是酸奶

0:08:40.550,0:08:44.175
好吃好吃 外面有点硬 里头嫩咚咚的

0:08:47.550,0:08:48.300
安逸

0:08:49.375,0:08:51.925
适合我们这些牙口不好的吃

0:08:52.975,0:08:54.050
真的有点好吃

0:08:54.100,0:08:56.200
伯娘 过来吃

0:08:57.675,0:08:58.950
哪个是好的嘛 这个

0:08:58.975,0:09:00.750
随便哪个都好的

0:09:03.625,0:09:04.675
嗯 好吃

0:09:07.650,0:09:09.175
这个吃了扛饿不呢

0:09:09.200,0:09:09.875
扛饿

0:09:13.325,0:09:15.050
我直接用手拿了

0:09:23.375,0:09:25.325
我再吃一坨

0:09:40.700,0:09:41.600
可以

0:09:43.075,0:09:45.875
老子二天干活路带点拿出去干可以撒

0:09:45.925,0:09:46.375
可以

0:09:46.400,0:09:47.500
拿个胶纸纸装起

0:09:52.375,0:09:53.050
安逸

0:09:53.375,0:09:58.500
所以说我们在家里面有这种老人的话可以做点这个给他吃

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
0:00:01.725,0:00:02.675
宽是好宽
How wide is this (sunshade)?

0:00:03.075,0:00:03.800
宽是4米
4 meters.

0:00:04.175,0:00:04.650
差不多
Good.

0:00:08.700,0:00:13.144
那就走你那边来撒 这里
How about I come over there.

0:00:13.400,0:00:15.975
来撒 你拉着头子撒
Do come. Take this corner.

0:00:23.700,0:00:26.925
我这样 我把它甩到这上面 等会来拉
Now I'll throw this up (this tree) so we can pull the shade up later.

0:00:26.925,0:00:28.800
拉来套（拴）在这底下
And we tie the end down there.

0:00:33.300,0:00:37.450
咿呀 我要是滚到这田头去要打得浇湿的哦
Eeya! I'd be soaking wet if I fell into this paddy field.

0:00:38.700,0:00:41.752
慢点 你鞋子是滑的 干脆把它脱了
Careful! You shoes are slippery. Better take them off.

0:00:42.050,0:00:44.500
下来 老子来
Get down. Leave it to me.

0:00:46.500,0:00:48.575
这绳子就合适噶 长短合适
This string is just right. Not too long and not too short.

0:00:49.175,0:00:50.575
使劲拉
Pull!

0:00:50.625,0:00:51.575
那里款（卡）起的
It gets stuck there.

0:00:51.750,0:00:53.575
伯爷那儿款起的
Uncle, it's stuck there.

0:01:16.200,0:01:17.225
够了够了
Good. Stop.

0:01:21.125,0:01:23.075
嘿 这个整起还要得四伯爷
Hei! This is already looking nice, isn't it uncle.

0:01:23.075,0:01:23.262
咋子要不得安
Of course.

0:01:23.262,0:01:24.300
咋子要不得安
Of course.

0:01:25.825,0:01:29.275
那没得事我给你炒两个菜在这阴凉坝（吃）
How about sometime I cook some dish and you can enjoy under this shade.

0:01:29.450,0:01:31.175
老子啤酒都没得
I don't have any beer.

0:01:31.350,0:01:33.550
你要喝啥子啤酒我给你买就是
Any beer you want I can buy some for you.

0:01:33.675,0:01:34.750
有的是酒屋头
There are so many liquor stores.

0:01:34.850,0:01:36.575
有的是酒 伯娘说得对
We are never short of beer. Aunt is right.

0:01:41.650,0:01:43.375
就套在那里
Just tie it there.

0:01:43.375,0:01:44.294
这棵树上是不哦
On this tree?

0:01:44.294,0:01:45.374
在这里
Here.

0:01:48.125,0:01:49.575
要不要我给你掌（扶）一下哦
Do you need me holding the ladder?

0:01:49.675,0:01:52.175
掌啥子掌哦 老子是飞天蜈蚣
No need. I'm "Fei Tian Wu Gong" (literally "Flying Centipede").

0:01:55.325,0:01:56.525
你还多凶哦
You must be very ferocious.

0:01:56.675,0:01:57.900
那不是咋子
Definitely. What do you expect?

0:02:02.350,0:02:03.875
我给你甩上来哦
I'll throw it up.

0:02:04.175,0:02:05.100
甩嘛
Do it.

0:02:15.375,0:02:17.925
再站一梯上去嘛
Stand one step higher.

0:02:18.125,0:02:19.775
你再站一梯上去 矮很了
Take one step higher. You are too short.

0:02:19.775,0:02:20.525
我害怕
I'm afraid.

0:02:20.550,0:02:21.293
没得事的
Rest assured.

0:02:21.293,0:02:23.085
哪里害怕哦老子恩是
What are you afraid of?

0:02:23.085,0:02:24.600
我双手给你掌都的
I'm holding the ladder with both hands.

0:02:25.150,0:02:27.575
233米跳下来都不害怕
Jumping from 233 meters high doesn't scare me.

0:02:27.575,0:02:29.493
这丁点儿（高度）老子
This height isn't going to be any problem.

0:02:29.825,0:02:32.600
在这沟沟河头打烂船呐
I'm telling you there's nothing to be afraid of.

0:02:34.650,0:02:35.327
安逸撒
Isn't it nice?

0:02:35.327,0:02:35.650
安逸 可以
Nice. Good.

0:02:35.650,0:02:36.977
安逸 可以
Nice. Good.

0:02:37.850,0:02:39.325
一哈子凉快了很多
Suddenly it feels cool.

0:02:39.800,0:02:41.350
搭了遮阳棚当然了
Of course. We have this sunshade.

0:02:41.650,0:02:42.600
狗东西麻雀儿
Bad sparrow.

0:02:42.900,0:02:44.075
雀儿窝得屎噶
Sparrow poop?

0:02:44.075,0:02:44.625
嗯
Yep.

0:02:45.025,0:02:48.100
二天炒菜炒啊炒得它要窝点屎来给你加点料
Maybe some day sparrows come and add some "flavoring" when you cook.

0:02:48.125,0:02:48.900
哈哈 加点佐料
Haha! Add some "seasoning".

0:02:48.925,0:02:50.600
这哈遮阳棚挡住了没得事的
Now this sunshade will protect us.

0:02:51.750,0:02:53.500
四伯爷还是可以哦
Uncle you are good.

0:02:59.950,0:03:01.200
可以可以
Good. Good.

0:03:02.300,0:03:03.610
还上得到台（面）了哈
Does it look proper?

0:03:03.610,0:03:04.550
嗯 可以
En. Good.

0:03:06.475,0:03:08.075
我给你炸个鲜奶嘛
Let me cook some Deep-fried Milk for you.

0:03:08.475,0:03:10.275
随便
Go ahead.

0:03:12.500,0:03:15.450
你是试这个灶的
You are testing this stove,

0:03:15.575,0:03:17.100
是不是嘛
aren't you?

0:03:17.150,0:03:17.950
买了两瓶 两瓶来做
We bought two bottles of milk for this.

0:03:18.025,0:03:18.725
拔鲜奶
Thread Milk

0:03:19.050,0:03:21.575
嘿嘿 拔鲜奶 炸鲜奶
Hehe. Thread Milk? Fried Milk.

0:03:22.925,0:03:23.475
哦
Oh.

0:03:23.475,0:03:24.375
炸鲜奶
Fried Milk

0:03:24.450,0:03:25.950
炸鲜奶哇
So it's Fried Milk.

0:03:25.975,0:03:26.500
哦
Oh.

0:03:27.100,0:03:29.225
就是你说炸来金黄金黄的那个呢
It's the thing you said was yellow and golden after frying.

0:03:29.600,0:03:30.275
啊
Ah.

0:03:31.950,0:03:32.800
倒两瓶
Let's pour both in.

0:03:34.000,0:03:37.000
你下次想吃（炸）酸奶也可以 纯牛奶也可以
Next time we can fry yogurt. Or whole-milk.

0:03:37.725,0:03:41.925
酸奶 酸的拿啥子来配呢
Yogurt? What goes with yogurt?

0:03:42.725,0:03:46.500
糖撒 甜的你吃得不嘛
Sugar. Can you eat sweet things?

0:03:47.300,0:03:49.125
甜的吃得
Yes, I can.

0:03:49.975,0:03:52.950
你看这里一斤鲜奶
Here we have 1 Jin (500g) fresh milk.

0:03:54.125,0:03:55.775
放这个淀粉
Add some corn starch.

0:03:56.025,0:03:58.375
这个包谷粉 玉米淀粉60克
60 grams of corn starch.

0:04:00.175,0:04:02.900
两勺 两勺多一点点
Two spoonful. And a little bit more.

0:04:02.950,0:04:04.662
吃甜点吗不吃嫩甜
Make it sweeter? Not too sweet.

0:04:04.725,0:04:07.125
不吃嫩甜 吃甜很了不安逸
Not too sweet. It's not good to have too much sugar.

0:04:07.925,0:04:08.850
差不多咯
That's enough.

0:04:08.875,0:04:10.650
不得 这个炸出来没得那么甜的
No, it's not that sweet after frying.

0:04:10.750,0:04:11.825
放五勺糖
Add five spoons of sugar.

0:04:11.875,0:04:14.375
把这个搅 搅匀了弄来煮
First stir and then boil after well mixed.

0:04:15.700,0:04:18.750
你这冷的（牛奶）白糖都化不了的嘛
Sugar isn't dissolving in cold (milk).

0:04:18.750,0:04:20.300
煮来它就要化的嘛
It will dissolve once I boil the milk.

0:04:22.475,0:04:24.025
走 我去开火
Let's go. I'll light the stove.

0:04:24.075,0:04:26.025
第一次（在家）弄哦 四伯爷
Uncle, this is the first time I cook (with this stove at home).

0:04:26.100,0:04:29.950
第一次弄技术要拿出来哦
Don't disappoint me this first time.

0:04:30.125,0:04:37.175
你不要跟他们说的希尔糊涂的整来不规则撒我要涛人哦
I'll chide you if you are not good at this after you've bragged so much.

0:04:37.650,0:04:39.900
你放心 害怕会让你涛人
Rest assured. I'm afraid of you scolding.

0:04:40.100,0:04:42.825
是撒 你整来不规则我就要涛你
Yes. I'll chide you if you are not good.

0:04:48.150,0:04:50.050
这哈就干起咯
We are starting now.

0:04:50.050,0:04:52.975
干起嘛 我看你咋子干的嘛
Go ahead. I'll watch you cook.

0:05:08.025,0:05:09.575
看到没 粘（稠）了
See? It turns thick.

0:05:10.700,0:05:14.552
煮粘了哒 煮粘了就可以了
Just cook until it's thick.

0:05:19.707,0:05:21.307
可以吃了哇
We can eat now?

0:05:22.500,0:05:24.025
这白白的
Look how white it is.

0:05:25.300,0:05:26.845
我摸哈看冷没有
Let me feel the temperature.

0:05:26.845,0:05:29.025
好想 就冷咯
It's turning cold.

0:05:30.175,0:05:33.325
再冰它哈儿就冷了 就跟它冰凉粉样
Let it cool a little bit longer. Just like cooling bean jelly.

0:05:34.175,0:05:35.775
四伯爷你看 这都冷了
Uncle look. It's cold now.

0:05:35.775,0:05:37.000
还可以撒 结了皮了噶
Is it good? Has it gelled?

0:05:37.050,0:05:37.850
啊 冷了
Ah. Yes.

0:05:38.050,0:05:40.200
一般结了皮了基本上就可以要得了
Usually it's good enough when it gels.

0:05:40.401,0:05:42.350
看嘛 直接就可以把它拿起来
See. I can take it out as a whole.

0:05:42.600,0:05:43.491
来了火的
It's well formed.

0:05:44.125,0:05:45.325
可以可以可以
Good. Good. Good.

0:05:45.375,0:05:46.350
直接弄来切
Let's cut.

0:05:47.475,0:05:49.098
哦哟 这个粘刀的
Oyo. It sticks to the knife.

0:05:49.098,0:05:50.350
粘刀的 拿纸擦哈
Sticks? Wipe it with some paper towel.

0:05:50.475,0:05:51.025
用点水
Get some water.

0:05:51.675,0:05:53.875
我们切这个要是粘刀的话就弄点水
Rinse the knife with some water if it sticks.

0:05:54.400,0:05:55.500
它有一点粘刀这个
It sticks a little bit.

0:05:57.125,0:05:58.575
那哈子就不粘了
Now it doesn't stick to the knife anymore.

0:05:58.600,0:05:59.900
好 又搞起水
Good. Rinse more.

0:06:05.925,0:06:07.325
好嘛 好好好
Good.

0:06:07.325,0:06:08.550
然后就是把它弄起
Now let's put it in a plate.

0:06:10.050,0:06:12.150
跟豆腐一样
It looks like Tofu.

0:06:14.000,0:06:16.600
把它分开 分开来裹
Seperate it apart to be coated later.

0:06:18.450,0:06:18.975
好
Good.

0:06:19.025,0:06:20.525
嘿 安逸安逸
Hei. Nice!

0:06:20.550,0:06:21.500
尝一坨看
Let me try a piece.

0:06:21.550,0:06:22.500
这哈都可以吃
It's eatable.

0:06:22.525,0:06:24.950
你那菜刀沾了生水的
You knife was rinsed with tap water.

0:06:24.975,0:06:25.650
不关事
No worries.

0:06:28.150,0:06:30.500
不吃不吃不吃 炸好了来吃
Nope. Nope. I want to eat it fried.

0:06:31.025,0:06:32.050
打两个蛋
Crack two eggs.

0:06:35.550,0:06:38.575
嘿打蛋这个技术还拿给你学到了的哒
Hei! You learned this cracking trick pretty well.

0:06:38.975,0:06:40.875
可以 你这个级别
Good. You are professional.

0:06:41.125,0:06:41.950
单手打蛋
Cracking eggs with one hand.

0:06:42.125,0:06:46.625
是啊 你打蛋的级别还是上等级别 我看一哈
Indeed! I can see you are "top-rated" at cracking the eggs.

0:06:48.350,0:06:50.025
我在视频头都看得到
I saw in videos where people

0:06:50.025,0:06:52.600
一敲手一捏就起来了
simply crack the egg and lift the shells up with one hand.

0:06:53.325,0:06:54.000
可以
Good.

0:06:54.125,0:06:54.925
可以噶
Looks good?

0:06:55.850,0:06:58.475
好 现在手套戴好了开始裹
Ok. Now we have disposable glove on. We can coat the milk.

0:07:03.750,0:07:05.350
然后再裹这个
Then coat with this.

0:07:07.075,0:07:07.700
可以撒
Good?

0:07:07.750,0:07:10.684
可以可以 嘿嘿安逸
Good. Hehe. Nice.

0:07:11.950,0:07:13.300
这个是啥子做的安
What is this?

0:07:13.550,0:07:14.775
这个是面包糠
This is breadcrumbs.

0:08:23.675,0:08:24.900
尝一哈看嘛
Let me take a bite.

0:08:29.925,0:08:33.875
是不是外面是脆的 里头还是嫩的
Isn't it crispy outside and tender inside?

0:08:35.000,0:08:35.725
安逸
Nice!

0:08:35.975,0:08:38.575
这个就是我跟你说的那个炸酸奶
This is the Deep-fried Yogurt I told you about.

0:08:38.900,0:08:40.525
鲜奶 不是酸奶
Fresh milk, not yogurt.

0:08:40.550,0:08:44.175
好吃好吃 外面有点硬 里头嫩咚咚的
It tastes good. Hard outside, but really tender inside.

0:08:47.550,0:08:48.300
安逸
Nice!

0:08:49.375,0:08:51.925
适合我们这些牙口不好的吃
It suits us who don't have strong teeth.

0:08:52.975,0:08:54.050
真的有点好吃
It really tastes good.

0:08:54.100,0:08:56.200
伯娘 过来吃
Aunt, come and try some.

0:08:57.675,0:08:58.950
哪个是好的嘛 这个
Which one tastes good? This one?

0:08:58.975,0:09:00.750
随便哪个都好的
Any of them tastes good.

0:09:03.625,0:09:04.675
嗯 好吃
Umm. Delicious.

0:09:07.650,0:09:09.175
这个吃了扛饿不呢
Does eating this ward off hunger?

0:09:09.200,0:09:09.875
扛饿
It does.

0:09:13.325,0:09:15.050
我直接用手拿了
I'm eating with my hands.

0:09:23.375,0:09:25.325
我再吃一坨
I want one more.

0:09:40.700,0:09:41.600
可以
Good.

0:09:43.075,0:09:45.875
老子二天干活路带点拿出去干可以撒
Can I take some when I go to work?

0:09:45.925,0:09:46.375
可以
Sure.

0:09:46.400,0:09:47.500
拿个胶纸纸装起
Take some in a plastic wrap.

0:09:52.375,0:09:53.050
安逸
Nice!

0:09:53.375,0:09:58.500
所以说我们在家里面有这种老人的话可以做点这个给他吃
So we can cook this dish for senior people at home.
