### ISSUE TITLE
【美食作家王刚】切鱼片水煮鱼 - https://youtu.be/BxcTf8qAByo

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#758]
【美食作家王刚】厨师长教你：“大鲤鱼的改刀”和“如何切鱼片”，再做个家常水煮鱼，简单实用易懂，学习起来！- https://youtu.be/BxcTf8qAByo
视频时长 5:35，预计发布时间为北京时间3月10日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

0:00:00.125,0:00:03.625
这个大鲤鱼首先我们先拍下它的头

0:00:09.575,0:00:10.900
好 我们现在开它的肚

0:00:11.650,0:00:13.175
可以慢慢走几下

0:00:13.800,0:00:14.475
不要着急

0:00:15.725,0:00:18.350
然后再反过来往外面这样子刷一下

0:00:20.950,0:00:22.450
轻轻地把它给扣下来

0:00:24.600,0:00:25.800
这是它的肠子

0:00:26.600,0:00:27.825
肠子加鱼胆

0:00:28.550,0:00:30.650
然后我们把它的油给取下来

0:00:33.625,0:00:36.600
油取下来了之后再清洗干净就可以了

0:00:37.375,0:00:39.475
然后我们在去除这个鱼鳃的时候

0:00:39.550,0:00:41.225
用两根手指这样插进去

0:00:41.225,0:00:43.875
大拇指掐断它的鱼鳃

0:00:44.400,0:00:45.300
掐断上面的

0:00:46.625,0:00:48.800
好 下来之后然后直接掐断

0:00:48.975,0:00:51.325
翻过来的时候我们再换一只手

0:00:53.200,0:00:55.875
右手扣右边的鳃左手扣左边的鳃

0:00:56.975,0:00:58.075
然后这样子扣下来

0:00:58.875,0:01:00.250
然后清洗一下就可以了

0:01:00.775,0:01:02.250
开始来（分）解这个鱼

0:01:02.550,0:01:03.725
从尾部下刀

0:01:04.025,0:01:06.150
一刀一刀的往上面走

0:01:06.250,0:01:07.600
贴着骨头往上面走

0:01:11.950,0:01:14.050
好 我们这个已经走上来了

0:01:14.150,0:01:16.875
有很多粉丝朋友他在起这个鱼的时候

0:01:17.275,0:01:19.225
刀他是往上面这样子走的

0:01:19.300,0:01:20.875
其实我们不能那样子

0:01:20.875,0:01:23.550
刀一定要平起来 往下面倾斜一点点

0:01:23.700,0:01:24.500
往上面剔骨

0:01:24.700,0:01:27.000
因为你如果不往下面的话这个肉

0:01:27.475,0:01:29.225
基本上就留在鱼上面去了

0:01:30.025,0:01:31.475
就留到了骨头上面

0:01:31.700,0:01:32.950
我们可以看一下

0:01:34.050,0:01:34.850
这个骨头

0:01:35.050,0:01:37.625
片过来的时候一定要贴着这个骨头走

0:01:37.675,0:01:39.100
要不然就看不到肉了

0:01:39.175,0:01:40.575
鱼片就起不下来

0:01:40.800,0:01:42.375
一刀一刀的往下面剁

0:01:44.825,0:01:46.350
然后就把它剁开了

0:01:52.650,0:01:56.725
起鱼片的话我们首先把刀比到这个鱼刺这里

0:01:57.025,0:01:59.400
推一刀慢慢地推

0:01:59.450,0:02:00.125
慢慢推

0:02:00.200,0:02:03.300
然后到下面的时候再换一个角度再往下面走

0:02:04.100,0:02:05.200
这样子往下面走

0:02:05.775,0:02:07.575
然后这边再回转来

0:02:08.075,0:02:08.775
再上来

0:02:09.400,0:02:10.575
再下去上来

0:02:11.900,0:02:12.975
再下去上来

0:02:16.875,0:02:17.700
再下去

0:02:17.950,0:02:19.450
慢慢的慢慢的

0:02:19.550,0:02:21.025
靠这个刀慢慢的走位

0:02:23.950,0:02:26.950
片鱼的时候我们也要把这个下面擦干净

0:02:27.375,0:02:28.700
就是防止它有水

0:02:29.575,0:02:31.400
有水的话鱼会滑

0:03:00.225,0:03:02.450
我们这个鱼片好了之后加点盐进来

0:03:03.125,0:03:03.850
抓一下

0:03:04.570,0:03:05.425
少加点盐

0:03:05.500,0:03:07.375
这个鱼骨跟鱼片也抓点盐

0:03:10.750,0:03:13.025
抓完了之后再用清水洗

0:04:14.700,0:04:17.800
放上香菜就可以准备吃水煮鱼了

0:04:19.300,0:04:21.000
这是鱼片

0:04:21.400,0:04:23.700
有凳子你们不坐着吃啊

0:04:24.000,0:04:26.400
站着多吃点撒

0:04:26.600,0:04:28.200
坐都干啥子哦 坐都矮得很

0:04:30.800,0:04:32.300
嗯 好吃

0:04:33.898,0:04:35.423
大家在家里面可以试一下

0:04:35.423,0:04:36.377
有几斤嘛这个鱼

0:04:38.961,0:04:40.826
漆二娃买回来她给我说8斤

0:04:40.953,0:04:42.648
我当真以为有8斤

0:04:42.987,0:04:43.665
真的8斤啊

0:04:44.512,0:04:45.847
她吃了3斤的回扣

0:04:49.258,0:04:52.266
她跑了路嘛脚步钱要撒

0:04:55.211,0:04:56.927
还吃了3斤的回扣可以

0:04:57.372,0:04:58.644
你看嘛一哈才8斤

0:04:58.644,0:05:00.677
那是跑路费那叫回扣吗

0:05:00.699,0:05:02.690
一哈8斤就吃了3哒3斤的回扣

0:05:02.987,0:05:03.834
跑路费

0:05:04.745,0:05:05.868
那是跑路费

0:05:05.868,0:05:06.800
嗯 对头

0:05:07.121,0:05:10.799
你少吃点  跑路费你都吃了那么多的哈

0:05:12.076,0:05:13.898
哦 你跑路费都吃了

0:05:14.618,0:05:16.610
那是跑路费又不是回扣好不好

0:05:16.864,0:05:18.834
跑路费还不是要打折扣啊

0:05:23.538,0:05:24.682
这是芹菜是不是哦

0:05:25.423,0:05:28.241
嗨呀 今晚上晚饭都不用吃了

0:05:28.326,0:05:29.491
今晚上还吃啥子饭哦

0:05:30.296,0:05:31.949
这就是晚饭撒

**Comment by immoonancient** [comment]
我来一期吧

**Comment by immoonancient** [comment]
【美食作家王刚】厨师长教你：“大鲤鱼的改刀”和“如何切鱼片”，再做个家常水煮鱼，简单实用易懂，学习起来！
Chef Wang teaches you: how to fillet and slice a fish, and make a “Shuizhuyu” spicy boiled fish

0:00:00.125,0:00:03.625
这个大鲤鱼首先我们先拍下它的头
Let’s first knock on the head of this big carp

0:00:09.575,0:00:10.900
好 我们现在开它的肚
Alright, now we open the belly

0:00:11.650,0:00:13.175
可以慢慢走几下
We can make some slices carefully

0:00:13.800,0:00:14.475
不要着急
Don’t rush

0:00:15.725,0:00:18.350
然后再反过来往外面这样子刷一下
Then turn it round, and slice it

0:00:20.950,0:00:22.450
轻轻地把它给扣下来
Remove it gently

0:00:24.600,0:00:25.800
这是它的肠子
This is the intestine

0:00:26.600,0:00:27.825
肠子加鱼胆
Intestine and gallbladder

0:00:28.550,0:00:30.650
然后我们把它的油给取下来
Then we take the fat out

0:00:33.625,0:00:36.600
油取下来了之后再清洗干净就可以了
The fat just needs some rinses after taken out

0:00:37.375,0:00:39.475
然后我们在去除这个鱼鳃的时候
When we remove the gills

0:00:39.550,0:00:41.225
用两根手指这样插进去
Stick two fingers in like this

0:00:41.225,0:00:43.875
大拇指掐断它的鱼鳃
Nip off the gill with your thumb

0:00:44.400,0:00:45.300
掐断上面的
Nip it off # 不确定“上面的”指什么

0:00:46.625,0:00:48.800
好 下来之后然后直接掐断
Alright, just nip it off like this

0:00:48.975,0:00:51.325
翻过来的时候我们再换一只手
Flip it, and then use the other hand

0:00:53.200,0:00:55.875
右手扣右边的鳃左手扣左边的鳃
Right hand for the right gill, and left hand for the left gill

0:00:56.975,0:00:58.075
然后这样子扣下来
And then dig it out like this

0:00:58.875,0:01:00.250
然后清洗一下就可以了
And then we just rinse it

0:01:00.775,0:01:02.250
开始来（分）解这个鱼
Now we start dividing the fish

0:01:02.550,0:01:03.725
从尾部下刀
Start cutting from the tail

0:01:04.025,0:01:06.150
一刀一刀的往上面走
Knife it all the way up

0:01:06.250,0:01:07.600
贴着骨头往上面走
All the way up, right next to the bone

0:01:11.950,0:01:14.050
好 我们这个已经走上来了
Good. Now we have gone to the top

0:01:14.150,0:01:16.875
有很多粉丝朋友他在起这个鱼的时候
Many followers and friends are filleting fish like this

0:01:17.275,0:01:19.225
刀他是往上面这样子走的
The knife is pointing upwards

0:01:19.300,0:01:20.875
其实我们不能那样子
Actually, we shouldn’t do that

0:01:20.875,0:01:23.550
刀一定要平起来 往下面倾斜一点点
The knife must lie flat, and slant downwards

0:01:23.700,0:01:24.500
往上面剔骨
when filleting the fish

0:01:24.700,0:01:27.000
因为你如果不往下面的话这个肉
If you don’t point the knife downwards

0:01:27.475,0:01:29.225
基本上就留在鱼上面去了
A lot of meat will be left on the fish

0:01:30.025,0:01:31.475
就留到了骨头上面
Will be left on the bone

0:01:31.700,0:01:32.950
我们可以看一下
Now let’s take a look

0:01:34.050,0:01:34.850
这个骨头
Look at the bone

0:01:35.050,0:01:37.625
片过来的时候一定要贴着这个骨头走
When filleting, the knife must be right next to the bone

0:01:37.675,0:01:39.100
要不然就看不到肉了
Or you don’t get any meat

0:01:39.175,0:01:40.575
鱼片就起不下来
The fillet can’t be taken off

0:01:40.800,0:01:42.375
一刀一刀的往下面剁
Chop it up like this # 不知道这句怎么翻译好

0:01:44.825,0:01:46.350
然后就把它剁开了
So we have chopped it up

0:01:52.650,0:01:56.725
起鱼片的话我们首先把刀比到这个鱼刺这里
To make fish slices, put the knife at the fishbones

0:01:57.025,0:01:59.400
推一刀慢慢地推
Push the knife slowly

0:01:59.450,0:02:00.125
慢慢推
Push it slowly

0:02:00.200,0:02:03.300
然后到下面的时候再换一个角度再往下面走
When reaching the lower part, change the direction and keep going

0:02:04.100,0:02:05.200
这样子往下面走
Go all the way down like this

0:02:05.775,0:02:07.575
然后这边再回转来
Then here, cut it backwards

0:02:08.075,0:02:08.775
再上来
Moving up

0:02:09.400,0:02:10.575
再下去上来
And down, and then up

0:02:11.900,0:02:12.975
再下去上来
And down, and then up

0:02:16.875,0:02:17.700
再下去
And down

0:02:17.950,0:02:19.450
慢慢的慢慢的
Keep it slow

0:02:19.550,0:02:21.025
靠这个刀慢慢的走位
Move the knife slowly and accurately # “走位”一词似乎包含了精度方便的要求

0:02:23.950,0:02:26.950
片鱼的时候我们也要把这个下面擦干净
While slicing the fish, we need to clean up the cutting board

0:02:27.375,0:02:28.700
就是防止它有水
Don’t leave any water there

0:02:29.575,0:02:31.400
有水的话鱼会滑
With water, the fish may slip away

0:03:00.225,0:03:02.450
我们这个鱼片好了之后加点盐进来
Now we’ve done the slicing, add some salt

0:03:03.125,0:03:03.850
抓一下
Mix it

0:03:04.570,0:03:05.425
少加点盐
Not too much salt

0:03:05.500,0:03:07.375
这个鱼骨跟鱼片也抓点盐
Add some salt to the fish bones and tail, too

0:03:10.750,0:03:13.025
抓完了之后再用清水洗
And then rinse it in water

0:04:14.700,0:04:17.800
放上香菜就可以准备吃水煮鱼了
Add some cilantro, then we can enjoy our “Shuizhuyu” dish

0:04:19.300,0:04:21.000
这是鱼片
These are fish slices

0:04:21.400,0:04:23.700
有凳子你们不坐着吃啊
We have seats. You guys don’t take a seat?

0:04:24.000,0:04:26.400
站着多吃点撒
I can eat more when standing

0:04:26.600,0:04:28.200
坐都干啥子哦 坐都矮得很
Why would I sit down? It will be too low

0:04:30.800,0:04:32.300
嗯 好吃
Hmm, delicious

0:04:33.898,0:04:35.423
大家在家里面可以试一下
Guys, you can try it at home

0:04:35.423,0:04:36.377
有几斤嘛这个鱼
How heavy was the fish?

0:04:38.961,0:04:40.826
漆二娃买回来她给我说8斤
Qi Erwa bought it. She told me it’s 8 jin (=4kg)

0:04:40.953,0:04:42.648
我当真以为有8斤
I thought it was really 8 jin

0:04:42.987,0:04:43.665
真的8斤啊
8 jin? For real?

0:04:44.512,0:04:45.847
她吃了3斤的回扣
She took 3 jin as a kickback

0:04:49.258,0:04:52.266
她跑了路嘛脚步钱要撒
She ran the errand. That’s the errand fee

0:04:55.211,0:04:56.927
还吃了3斤的回扣可以
A kickback of 3 jin. Good

0:04:57.372,0:04:58.644
你看嘛一哈才8斤
Check it out. Only 8 jin

0:04:58.644,0:05:00.677
那是跑路费那叫回扣吗
That’s my errand fee! You call it a kickback?

0:05:00.699,0:05:02.690
一哈8斤就吃了3哒3斤的回扣
8 jin in total, and she took a kickback of 3 jin

0:05:02.987,0:05:03.834
跑路费
Errand fee

0:05:04.745,0:05:05.868
那是跑路费
That’s my errand fee

0:05:05.868,0:05:06.800
嗯 对头
Hmm, correct

0:05:07.121,0:05:10.799
你少吃点 跑路费你都吃了那么多的哈
Don’t eat too much. You’ve already eaten a lot with you errand fee

0:05:12.076,0:05:13.898
哦 你跑路费都吃了
Oh, you ate your errand fee

0:05:14.618,0:05:16.610
那是跑路费又不是回扣好不好
Come on! It’s just an errand fee, not a kickback

0:05:16.864,0:05:18.834
跑路费还不是要打折扣啊
Isn’t errand fee also a rebate?

0:05:23.538,0:05:24.682
这是芹菜是不是哦
Is this celery?

0:05:25.423,0:05:28.241
嗨呀 今晚上晚饭都不用吃了
Heya, we don’t need to have dinner tonight

0:05:28.326,0:05:29.491
今晚上还吃啥子饭哦
We don’t need dinner tonight, do we?

0:05:30.296,0:05:31.949
这就是晚饭撒
This is the dinner
