### ISSUE TITLE
[华农兄弟] 华农兄弟这只小花狗很像以前的公狗看起来很靓也很乖 - https://youtu.be/aUPmbJAnA9o

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#761]
https://youtu.be/aUPmbJAnA9o
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 7, 2020 at 06:13PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/aUPmbJAnA9o

#华农兄弟：这只小花狗很像以前的公狗，看起来很靓，也很乖
#Huanong Brothers: This tinted puppy looks like our lost boy. She is so beautiful and such a good girl.

0:00:00.420,0:00:01.540
# 你看  小花狗
Look! A tinted puppy

0:00:06.660,0:00:08.480
# 它吃得好飽啊  你看  肚子上
She has eaten a lot! Look! Her belly,

0:00:08.780,0:00:09.780
# 吃得好[SIC]飽飽的
is stuffed with food.

0:00:13.240,0:00:15.420
# 它正在睡覺  我把它拉起來的
She was sleeping. But I pulled her out.

0:00:17.780,0:00:19.900
# 這條狗很像以前的那條公狗哦
This puppy looks really like our lost boy.

0:00:22.840,0:00:25.300
# 都沒有這樣的狗  生出來就這樣子的  哈哈
We don't have such a dog here. But she was born with this colour. Ha ha

0:00:26.460,0:00:27.020
# 是不是
Am I right?

0:00:28.060,0:00:29.560
# 這個是母的  這個
It's a girl, yea.

0:00:39.180,0:00:41.160
# 遺傳它爺爺的  遺傳
She has inherited the genes,

0:00:41.560,0:00:43.160
# 遺傳它爺爺的基因
she has inherited the genes from her grandpa.

0:00:47.300,0:00:47.800
# 過來
Come here!

0:00:48.340,0:00:49.340
# 通通給我過來
Everybody come here!

0:00:51.200,0:00:52.600
# 都不肯過來 小狗
They're not coming, the puppies.

0:00:57.880,0:00:58.660
# 握握手
Shake hand with me!

0:01:02.360,0:01:03.260
# 大胖子
Big fat girl

0:01:05.700,0:01:06.320
# 看看
Have a look!

0:01:08.440,0:01:09.540
# 容易掉毛
She sheds a lot.

0:01:12.640,0:01:13.620
# 不敢動是不是
You don't dare to move, do you?

0:01:14.020,0:01:15.500
# 沒事的  動一動啊
No worries! Just move

0:01:15.840,0:01:17.020
# 要有點表情  (註︰「表情」這個概念很難找到相對的翻譯。"Facial expressions"是指一般的面部表情，與這裡的不一樣)
Happy or not, show me!

0:01:17.340,0:01:19.340
# 笑一笑哇  你怎麼不笑呢
Have a smile. Why don't you smile?

0:01:20.620,0:01:22.940
# 笑一笑十年少  你知道嗎
A single smile makes you ten years younger, got it?

0:01:24.720,0:01:27.180
# 我天左餵了你 吃好喝好
I feed you everyday. You have good food and food drinks.

0:01:28.320,0:01:29.280
# 你還怕我幹嘛
So why are you still scared of me?

0:01:32.660,0:01:35.240
# 你看  它很喜 它這樣很喜黏著我的哦
Look! She likes, she really likes clinging onto me.

0:01:36.400,0:01:39.060
# 天天跟我 想 想  想跟我回家
Everyday she was, she was hope, hope, hoping to go home with me.

0:01:39.140,0:01:40.220
# 我不讓它回
But I don't let her come with me.

0:01:45.140,0:01:47.200
# 給它按一下摩  按一下脖子
Let me give her a massage, a massage on her neck.

0:01:47.940,0:01:49.680
# 看它很享愛的樣子
See how much she enjoys it?

0:01:52.860,0:01:53.700
# 看一下我
Look at me!

0:01:54.040,0:01:55.060
# 怎麼不看
Why don't you look at me?

0:01:58.860,0:01:59.720
# 看著我幹嘛
Why are you looking at me?

0:02:00.540,0:02:02.420
# 看著我就一直一動不動
She stares at me, like statue.
