### ISSUE TITLE
[华农兄弟] 华农兄弟野果没摘到那就砍一把芭蕉挖一个竹笋回去 - https://youtu.be/INKYq5amPfs

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#770]
https://youtu.be/INKYq5amPfs
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 9, 2020 at 11:40AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/INKYq5amPfs

#华农兄弟：野果没摘到，那就砍一把芭蕉，挖一个竹笋回去
#Huanong Brothers: As we can't pick any wild fruits, we chopa bunch of plantains and dig a bamboo shoot back home.

0:00:00.260,0:00:01.660
# 大家好  現在天晴啦
Hi everyone! It's sunny now.

0:00:01.660,0:00:03.800
# 我上山上看一下有沒有那個野果
So I'm heading onto the hill and see if there are any, any wild fruits.

0:00:04.100,0:00:05.100
# 摘來吃一下啊
You could pick some.

0:00:05.360,0:00:06.880
# 你看  這是我們村
Look! This is an orchard,

0:00:07.320,0:00:10.060
# 有一位老爺爺  他自己種的那個果園哦
of an old man in our village. He planted everything, all by himself.

0:00:10.180,0:00:11.380
# 這個  茶樹
This is, tea tree.

0:00:12.020,0:00:13.040
# 這個  還有這個是
This is, and this is,

0:00:13.760,0:00:15.900
# 這個是牛頭柑  就是那個柚子啊
this is "bull head mandarin", which is actually pomelo.

0:00:15.920,0:00:17.160
# 我們叫柚子樹 這樣
We call it pomelo tree, yea.

0:00:17.440,0:00:18.380
# 還有茘枝樹
There are also lychee trees,

0:00:18.900,0:00:19.580
# 桃樹
peach trees,

0:00:19.800,0:00:20.620
# 李樹
plum trees,

0:00:21.220,0:00:21.960
# 還有板栗
and chestnuts too.

0:00:22.500,0:00:23.220
# 好多哇
A lot!

0:00:23.420,0:00:24.960
# 我記得還小的時候  他就在這裡種
I remember that when I was a kid, he was planting,

0:00:25.120,0:00:26.220
# 種了好多這個果樹
planting a lot of these fruit trees.

0:00:26.640,0:00:28.460
# 以前我還小的時候都來這裡摘過
I've also come and picked some fruits here when I was a kid,

0:00:28.600,0:00:29.680
# 趁他不在的時候
of course, when he was not around.

0:00:30.720,0:00:32.160
# 現在他又從新種了一下
And how he has planted some new ones,

0:00:32.780,0:00:33.800
# 種得更靚啦
which are much more beautiful.

0:00:34.780,0:00:35.840
# 你看 他這個
Look! This is ah,

0:00:36.340,0:00:38.240
# 這個柚子  柚子樹都開花啦
this is pomelo. The pomelo tree has already blossomed.

0:00:38.640,0:00:40.140
# 好多那些花  小花啊
There are a lot of flowers, small flowers.

0:00:41.140,0:00:42.480
# 到時候就有柚子摘啦
We can come again for the pomelos later.

0:00:45.600,0:00:46.960
# 你看 那裡還有桃花
Look! There are peach flowers too.

0:00:47.580,0:00:48.720
# 這個桃花就靚哦  (註︰很靚表達「就」這個概念，所以用了高一層次的字)
These peach flowers are gorgeous.

0:00:55.180,0:00:55.680
# 你看
Look!

0:00:56.100,0:00:56.720
# 這桃花
The peach flowers,

0:00:57.180,0:00:58.340
# 它顏色都不一樣的
they have different colours,

0:00:58.780,0:01:00.640
# 有的鮮艷一點  有的白一點
some are brighter, while some are paler.

0:01:02.320,0:01:03.360
# 可能品種不一樣
Perhaps they're of different specie.

0:01:11.720,0:01:13.720
# 你看  這房子還是用泥磚做的哦
Look! This house is still made of mudbrick.

0:01:14.080,0:01:15.540
# 很結實的哦  這樣
It's really firm, you know.

0:01:22.560,0:01:24.160
# 還最吉老的辦法做的
This is the oldest way of building a house.

0:01:25.540,0:01:26.320
# 全是那個
These are all,

0:01:27.180,0:01:27.840
# 黃泥
mud,

0:01:28.000,0:01:28.920
# 用黃泥來做
made with mud.

0:01:29.280,0:01:30.260
# 用黃泥做的
It's made with mud.

0:01:30.380,0:01:31.220
# 搞到搞不掉  (註︰不明白，我想應該是用手擦後不會沾到手的意思吧)
It doesn't shed.

0:01:34.860,0:01:36.100
# 做這個房子也不容易呀
Building this house is certainly not a simple task.

0:01:36.380,0:01:36.980
# 這從那裡
You need to, from there,

0:01:37.520,0:01:40.380
# 把家裡  要從  要從家裡把它這個泥 挑過來
from home, I mean, you need to bring, bring the mudbricks all the way from home,

0:01:41.680,0:01:43.020
# 一塊一塊挑過來
one after the other.

0:01:58.440,0:02:00.200
# 這裡可以打造成一個世外桃源
This place can be made a heaven on earth.

0:02:00.780,0:02:01.500
# 又有房子
There is a house.

0:02:02.320,0:02:05.040
# 有柵欄  再養小狗小雞
There are sheds. You can keep some doggies and chicks here,

0:02:05.740,0:02:06.860
# 摘點小鴨子在下面
and also some duckies down there,

0:02:07.740,0:02:08.740
# 再摘條小牛
and a calf too.

0:02:09.580,0:02:11.240
# 哇  這個地方很  很漂亮的哦
Wa! This place is rea, really pretty.

0:02:13.160,0:02:15.440
# 可能是那個  我們村的那個老爺爺
Perhaps the, I mean the old man in our village,

0:02:16.180,0:02:16.820
# 他也喜歡
he also likes,

0:02:17.360,0:02:18.860
# 他也喜歡這種清靜的生活
he also likes this kind of peaceful life.

0:02:21.220,0:02:23.000
# 你看  他只種  種上果樹
Look! He has only planted, planted fruit trees.

0:02:24.680,0:02:26.220
# 甚麼樹的果樹都可以種一點
It doesn't really matter what kind of fruits.

0:02:29.220,0:02:30.880
# 你看  又可以放點香菇
Look! He can also plant some mushrooms.

0:02:32.420,0:02:33.620
# 在這裡很清靜的哦
It's really peaceful here.

0:02:33.820,0:02:34.760
# 空氣又好
The air is fresh,

0:02:35.140,0:02:36.280
# 全部都是植物
as it's surrounded by plants.

0:02:36.600,0:02:37.840
# 沒有水泥板的哦 這裡
Nothing is made of concrete here.

0:02:39.300,0:02:41.700
# 哇  多好哇  每天睡到自然醒
Wa! What a wonderful life! You can switch off our alarm every night.

0:02:43.520,0:02:44.360
# 想想就
It's really...

0:02:44.780,0:02:47.560
# 等我老啦  等我老了的時候  我也找個這樣地方
When I become an old man, when I become an old man, I'm also gonna find such a place,

0:02:49.040,0:02:50.380
# 清靜一下生活
to spend my days peacefully.

0:02:50.740,0:02:53.260
# 每天就是種點青  種種青菜呀
Everyday, I plant some veg, plant some veggies,

0:02:53.900,0:02:54.940
# 逗逗小狗哇
play with the doggies,

0:02:55.760,0:02:57.380
# 再找條小豬  溜溜小豬
and get a piggy, walk the piggy.

0:02:57.660,0:02:58.200
# 也好
Why not?

0:03:04.280,0:03:06.040
# 你看  樹上一個都沒有啦
Look! There's not even one in the tree.

0:03:06.500,0:03:07.740
# 地上我看到了一個
And I see one on the ground.

0:03:08.040,0:03:08.760
# 一個
One

0:03:09.480,0:03:10.400
# 有一點青的
It's a bit green.

0:03:11.540,0:03:12.740
# 哎 吃了再說
Ay! Let me finish it first.

0:03:13.960,0:03:14.740
# 就一個
Just one

0:03:17.420,0:03:18.660
# 等下我們去挖竹笋
Let's go to dig some bamboo shoots in a while.

0:03:22.620,0:03:23.700
# 嗯  可以喲
Um! Not bad!

0:03:25.740,0:03:27.020
# 挖一點竹笋回去
Let's dig some bamboo shoots.

0:03:27.800,0:03:30.100
# 來都來啦  不能空著手回去嘛  是不是
We're already here. We just can't get back home empty-handed, can we?

0:03:32.860,0:03:33.360
# 嗯
Um!

0:03:33.940,0:03:34.460
# 可以
Not bad

0:03:34.800,0:03:35.480
# 有點酸
It's a bit sour.

0:03:38.180,0:03:38.720
# 沒啦
No more?

0:03:40.820,0:03:41.560
# 就一個
Just one

0:03:50.300,0:03:51.160
# 啊  回去
Ah! Let's go back,

0:03:51.720,0:03:52.500
# 回去下面
go back down there,

0:03:53.260,0:03:54.360
# 再  往那邊走
and, go that way.

0:03:54.560,0:03:55.520
# 現在去挖竹笋
We're now gonna dig some bamboo shoots.

0:03:57.080,0:03:57.900
# 鋤頭沒帶
I don't have a hoe today.

0:03:58.700,0:04:00.300
# 用刀來挖  用刀來挖
I'll dig with the knife, dig with the knife.

0:04:01.340,0:04:02.600
# 應該也能挖一點
I think I can still get some.

0:04:05.760,0:04:06.600
# 啊  這裡有
Ah! Here's one,

0:04:07.040,0:04:07.980
# 又檢了一個
one more.

0:04:09.340,0:04:10.740
# 這個就好吃的  這個
This one is undoubtedly tasty.

0:04:14.080,0:04:15.300
# 哎呀  可以  沒壞
Aya! Good! It's not rotten.

0:04:21.540,0:04:22.060
# 嗯
Um!

0:04:22.260,0:04:23.040
# 真好吃
It's really tasty!

0:04:25.480,0:04:26.520
# 這個很甜哦  這個
It's really sweet, you know.

0:04:28.600,0:04:29.500
# 剛剛青的
That one was green.

0:04:40.840,0:04:41.460
# 沒啦
No more

0:04:46.240,0:04:47.500
# 你看  從這裡進去
Look! We go this way.

0:04:47.840,0:04:48.660
# 這是竹林
This is a bamboo forest.

0:04:49.380,0:04:50.620
# 我們去這裡面去  可以
We get in from this way, then we can,

0:04:50.940,0:04:51.920
# 挖得到竹笋
find the bamboo shoots.

0:05:02.340,0:05:03.760
# 你看  這野芭蕉哦
Look! These are wild plantains.

0:05:04.380,0:05:05.320
# 這個野芭蕉
These wild plantains,

0:05:05.580,0:05:06.720
# 現在那麼大啦
look, they're already that big now.

0:05:09.520,0:05:12.220
# 它這個不  不 不  不把它砍掉的話也會那個的
Even if I don't, don't, don't chop it down, it would still, you know,

0:05:12.640,0:05:13.880
# 也會自然會死掉的
it would still die naturally.

0:05:15.960,0:05:17.160
# 我把它  砍下來
Let me, chop it down.

0:05:19.560,0:05:20.960
# 你看  這個很大了哦
Look! This is already that big.

0:05:21.320,0:05:22.040
# 可以砍啦
So I can chop it.

0:05:23.080,0:05:25.560
# 這個香蕉長出來之後哇  要把這個樹要砍掉  (註︰他又香蕉又芭蕉，我不管了，照字面譯)
The tree needs to be chopped down when there are bananas.

0:05:25.720,0:05:26.800
# 不然這個樹沒用的
It's useless keeping the tree here.

0:05:27.920,0:05:28.740
# 那麼大的樹
It's such a big tree.

0:05:29.700,0:05:32.300
# 你看  這個不是很靚哦  那個有個很靚的
Look! This is not really that beautiful. There's a really beautiful one.

0:05:32.800,0:05:33.300
# 又大
And big too

0:05:34.160,0:05:35.040
# 我砍那棵
I'll get that one.

0:05:52.100,0:05:54.040
# 我聽說這個芭蕉芘可以吃的哦
I've heard that the cores of the plantain trees are edible.

0:05:54.940,0:05:56.060
# 我怎麼敢吃
How would I dare to eat?

0:05:56.160,0:05:56.720
# 看一下
Let me take a look,

0:05:57.220,0:05:58.040
# 劈開來看一下
take a look inside.

0:06:04.080,0:06:05.560
# 好多那個水分啊 這裡
It's really juicy, here.

0:06:18.380,0:06:19.400
# 是不是可以吃的
Is it really edible?

0:06:48.980,0:06:50.060
# 哇  這個好像是誒
Wa! I think it's this part.

0:06:51.100,0:06:51.800
# 很嫩哦
It's really tender.

0:06:56.800,0:06:58.100
# 哇  就剩下這一坨
Wa! Only this little bit remains.

0:07:01.180,0:07:02.280
# 是不是能不能吃  (註︰這個有點混亂，也翻譯得混亂一點以配合吧)
Isn't it not edible or not?

0:07:03.260,0:07:03.760
# 誒呀
Yeeya!

0:07:10.500,0:07:11.340
# 不知道甚麼味
I can't describe the taste.

0:07:11.800,0:07:12.920
# 感覺甚麼味都沒有
It's like simply tasteless.

0:07:13.700,0:07:15.160
# 嗯  還是不要吃啦  算啦
Um! Forget it. I'm not eating it.

0:07:30.760,0:07:31.900
# 你看  這個香蕉
Look! The bananas,

0:07:32.400,0:07:34.220
# 這個香蕉就很靚的哦  香蕉
the bananas are really beautiful, the bananas.

0:07:38.840,0:07:39.580
# 把它帶回去
Lets' bring them back.

0:07:44.660,0:07:46.500
# 這邊全是那個野芭蕉哦
These are all the wild plantains here.

0:07:46.580,0:07:47.340
# 這沒人要的
They don't belong to anyone.

0:07:48.620,0:07:50.840
# 不知道是誰種的  種下去可能就是
I wonder who planted them. They were planted and then,

0:07:51.300,0:07:52.800
# 沒有  沒有  沒有去管啦
no, no, nobody takes care of them.

0:07:53.100,0:07:54.200
# 長得到處都是
So they're growing everywhere.

0:07:56.980,0:07:58.960
# 你看  下面有竹子哦  我下去看一下
Look! I see bamboos down there. Let me go down and have a look.

0:07:59.880,0:08:00.660
# 看一下有沒有
Let me see if there are any,

0:08:01.200,0:08:02.180
# 有沒有竹笋
any bamboo shoots,

0:08:02.520,0:08:03.020
# 竹笋
bamboo shoots.

0:08:14.060,0:08:15.040
# 你看  這裡有一個
Look! Here's one!

0:08:15.880,0:08:16.540
# 裂開的
It's cracked here.

0:08:20.140,0:08:21.480
# 啊 沒帶鋤頭
Ah! No hoe.

0:08:22.100,0:08:24.200
# 要有鋤頭我兩下就把它 挖到啦
If I had a hoe, I could be able to dig it out in a couple of seconds.

0:08:27.940,0:08:29.400
# 哎喲  好大哦
Ayo! It's really big!

0:08:29.600,0:08:30.280
# 好大哦
It's so big!

0:08:33.980,0:08:34.580
# 看到沒有
Can you see it?

0:08:35.440,0:08:36.620
# 這個應該大  這個
It should be a big one, definitely.

0:08:38.720,0:08:40.400
# 這一個就夠一晚上吃啦
This one alone is enough for a dinner.

0:08:49.320,0:08:50.680
# 這個不好挖
I don't think I can make it.

0:08:51.240,0:08:52.060
# 拔根棍來
Let me get a stick,

0:08:52.900,0:08:53.980
# 拔根棍來挖
and dig with a stick.

0:09:00.600,0:09:01.300
# 哎喲
Ayo!

0:09:03.480,0:09:04.440
# 那麼硬的  這個
It's so hard!

0:09:25.100,0:09:26.060
# 哎喲
Ayo!

0:09:30.820,0:09:31.720
# 很大  這個
This one is really large.

0:09:34.240,0:09:36.240
# 摘小一點的我也不介意呀
I won't mind having a smaller one.

0:09:37.380,0:09:38.640
# 搞那麼大的給我幹嘛
So why do you give me such a big one?

0:09:54.300,0:09:55.000
# 沒帶鋤頭
Without a hoe,

0:09:55.860,0:09:57.060
# 就是不好挖
things become so much more difficult.

0:10:01.840,0:10:03.940
# 剛好兄弟來啦  借他的鋤用一下
I just saw my buddy. Let me borrow a hoe from him.

0:10:04.740,0:10:05.560
# 這個很大的
This one is really big.

0:10:07.900,0:10:08.720
# 拿頭鋤頭來
Give me your hoe!

0:10:13.300,0:10:14.100
# 夠大  這個
It's big enough.

0:10:14.680,0:10:15.180
# 哪個
Which one?

0:10:15.580,0:10:16.080
# 很深
It's so deep.

0:10:16.100,0:10:17.280
# 還沒我挖的那個大
It's not even as big as the one that I dug.

0:10:17.500,0:10:18.160
# 你挖的有多大
How big is yours then?

0:10:19.800,0:10:20.560
# 好有很多
There are still a lot.

0:10:20.980,0:10:22.320
# 很深的  有的挖都挖不到
Some are really deep that you can't even dig them up.

0:10:22.380,0:10:22.880
# 是
Indeed

0:10:23.320,0:10:25.560
# 不要挖爛了就很靚  挖爛了就沒意思了
It's really beautiful, if I don't break it. It would be too bad if I do.

0:10:26.020,0:10:26.700
# 要挖寬一點
Dig wider!

0:10:27.240,0:10:27.920
# 還刀一到  (註︰不明白)
Not yet.

0:10:28.540,0:10:29.420
# 莖都還沒有挖到  (註︰笋的莖又是甚麼意思？我照字面譯算了)
You haven't even reached the stem.

0:10:31.000,0:10:31.940
# 很難挖
It's really hard.

0:10:32.840,0:10:34.360
# 去哪裡挖來  是不是去裡面
Where is it? Is it inside?

0:10:34.440,0:10:34.960
# 去裡面
Yes, inside.

0:10:36.320,0:10:37.820
# 太多雜草  找都不好找
These's too much weed, making it very difficult to find one.

0:10:39.260,0:10:40.520
# 年底就10塊錢一斤
It was 10 RMB/500 g by the end of last year.

0:10:41.720,0:10:42.940
# 現在有2塊錢都值
It still costs 2 RMB now.

0:10:43.800,0:10:45.280
# 2塊錢沒人會去挖
No one would be digging it for 2 RMB.

0:10:47.760,0:10:48.800
# 好深呀  這個
It's really deep, here.

0:10:58.620,0:10:59.940
# 這個竹笋最少3斤
This bamboo shoot is at least a kilogram and a half.

0:11:04.420,0:11:05.080
# 哇  這個
Wa! This is...

0:11:06.380,0:11:07.260
# 這個  沒找到
this one...I've not yet

0:11:07.280,0:11:08.420
# 它的頭在哪
Where's its head?

0:11:09.600,0:11:10.660
# 全都是根
There are only roots.

0:11:11.700,0:11:13.120
# 你很專用[SIC]挖這個  是不是
You're professional in it, aren't you?

0:11:13.780,0:11:15.020
# 看你挖弓好多在上面
I saw that you had dug a lot up there.

0:11:21.940,0:11:22.780
# 無從下刀
There's nowhere to cut it out.

0:11:32.140,0:11:32.820
# 鋤頭
Hoe...

0:11:37.300,0:11:37.920
# 哇
Wa!

0:11:38.580,0:11:39.320
# 扁的
It's flat.

0:11:40.520,0:11:41.180
# 我還以為
I though it was...

0:11:41.460,0:11:42.460
# 圓的才俊
A round one is more handsome.

0:11:42.480,0:11:43.040
# 對
Exactly!

0:11:48.640,0:11:49.520
# 可以  這個
Alright! This is,

0:11:49.980,0:11:51.120
# 可以搞一餐啦
enough for a meal.

0:11:51.980,0:11:52.700
# 今天晚上就
Tonight I'll,

0:11:53.000,0:11:53.960
# 用它來炒咸菜
fry it with pickled mustard.

0:11:57.280,0:11:59.100
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:11:59.700,0:12:00.280
# 去回去啦
We need to go back.
