### ISSUE TITLE
【美食作家王刚】后厨基本功“翻锅” - https://youtu.be/6zdi77_L9d8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#776]
https://youtu.be/6zdi77_L9d8
视频时长 5:07，预计发布时间为北京时间3月13日晚

这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

标题
```
【美食作家王刚】厨师长从头教你：后厨基本功“翻锅”要如何练习，连抓锅布都有讲究，跟着一起学！
```

字幕
```
0:00:00.426,0:00:01.706
哈喽大家好我是王刚

0:00:02.269,0:00:05.290
今天我想跟大家分享一个翻锅的小技巧

0:00:05.580,0:00:10.345
我的教学视频 做菜教学当中从来没有这个翻锅的小技巧

0:00:12.235,0:00:14.061
以前我以为在家里面吧 

0:00:14.283,0:00:18.617
大家可能不怎么会用得上这个翻锅的一些技巧

0:00:18.873,0:00:20.887
其实我觉得应该是我错了 

0:00:20.972,0:00:25.597
其实大家最渴望最基本的应该就是第一步 从翻锅开始

0:00:26.023,0:00:27.713
今天我就来跟大家分享 

0:00:28.174,0:00:33.788
包括从怎么样去用这个抓锅布到怎么样子去翻做第一节课

0:00:34.453,0:00:36.228
好 现在我们来开始来切这个布

0:00:36.877,0:00:40.273
我们一般厨房里面用的是这种毛巾

0:00:40.802,0:00:44.057
这个专门（用）做厨房里面的纯白色毛巾 

0:00:44.078,0:00:47.423
用来擦东西 也可以用来做抓锅布

0:00:48.225,0:00:51.706
然后今天就用这个来切一块下来

0:00:52.354,0:00:54.402
我们叠这个毛巾的方法有很多

0:00:54.470,0:00:56.365
我今天就跟大家分享一个最简单的

0:00:56.962,0:00:59.249
首先把这个布叠得这么宽

0:00:59.522,0:01:01.928
根据你自己的手掌这样子试一下

0:01:02.252,0:01:04.897
差不多的话再往外面叠 再叠一层

0:01:06.075,0:01:08.208
OK 然后这里给它切掉

0:01:16.723,0:01:18.959
好 然后我们直接对折过来

0:01:20.665,0:01:25.887
对折过来了之后待会儿我们上锅的时候把这个卡到耳朵里面就可以了

0:01:26.331,0:01:28.651
这是最简单最普通的一个做法

0:01:28.907,0:01:33.276
然后我们还有一种拿抓锅布的办法是这样子的

0:01:33.890,0:01:35.341
两只手（指）夹住这里

0:01:36.092,0:01:39.522
然后这边拿过来这样子 

0:01:39.914,0:01:41.535
这个是随拿随走

0:01:41.604,0:01:46.877
我们手离开锅的时候 是拿着毛巾一起离开的

0:01:47.150,0:01:50.972
还有一种就是直接挂在上面 挂在锅上面直接这样子拿的

0:01:52.354,0:01:53.959
好了 我们现在来试一下第一种

0:01:54.368,0:01:57.935
第一种就是经常在我视频当中可以看到的直接挂上去

0:01:58.344,0:02:01.621
这样子这个布直接挂上去 这样就可以

0:02:01.843,0:02:06.040
这个做法的话适合于我们川菜厨师 大部分都是这样子

0:02:06.075,0:02:07.218
因为简单省事儿

0:02:07.559,0:02:09.812
还有另外一种是粤菜厨师非常喜欢的

0:02:10.068,0:02:12.354
就刚刚我说的两根手指夹住它 

0:02:12.713,0:02:17.235
然后手张开翻过来这样子拿

0:02:18.293,0:02:21.774
他是抓着这个抓锅布翻翻翻

0:02:22.116,0:02:26.228
翻好了之后 他如果是打调料的话这个布是跟着手一起过来的

0:02:26.433,0:02:33.088
其实如果你说哪一样更实用的话我觉得这个是更加实用的 简单直接

0:02:34.180,0:02:35.784
我们新手的话这样就OK了

0:02:36.058,0:02:40.354
好了 下面来分享一下翻锅的一些规则小技巧

0:02:41.655,0:02:43.941
首先我们翻锅的话不要着急 急着翻

0:02:44.112,0:02:47.201
我们先来第一步 就是拉锅 直线拉锅

0:02:47.337,0:02:49.692
直线拉锅现在锅放在这个位置 

0:02:49.965,0:02:53.020
把它拉出来 拉出三分之一的位置 

0:02:53.242,0:02:55.170
大概是这个位置 三分之一

0:02:55.546,0:02:57.969
然后我们再把它放下去

0:02:58.310,0:03:01.655
放下去放到什么位置呢 只要说不撞到这里就OK 

0:03:05.221,0:03:06.757
这样子 我们先练习这一步

0:03:08.020,0:03:09.795
这一步一般练习三天

0:03:10.153,0:03:13.198
这一步的目的就是锻炼你左手的力气

0:03:13.225,0:03:16.569
然后是说推出去拉回来的这一步走直线 

0:03:16.877,0:03:20.597
不能够歪 歪了的话就会这样子

0:03:20.750,0:03:22.406
你中间的菜就会翻不过来

0:03:26.126,0:03:27.576
然后到我后面来看一下

0:03:27.935,0:03:30.409
从我肩膀 左肩的这个位置 

0:03:30.648,0:03:33.873
左肩锁骨这个位置 这里出去一条直线

0:03:39.948,0:03:44.129
好 现在我们第一步会了之后来第二步

0:03:44.965,0:03:48.191
第二步的话它就要出去之后有一个弧度上来

0:03:51.706,0:03:55.699
同样也是锅拉出来不要超出三分之一 这个位置左右

0:03:55.802,0:04:00.849
然后下去了之后一点点弧度上来 下去上来

0:04:00.853,0:04:05.563
好 我们再从我的后面来 锁骨的这个位置来看一下

0:04:08.856,0:04:13.293
好 这些我们练会了之后然后才开始拿勺子

0:04:13.498,0:04:17.730
右手拿勺 拿勺子的话 勺子主要的目的是什么

0:04:17.883,0:04:23.208
这样子出去的时候 菜到这个位置它不会翻过来的

0:04:23.208,0:04:27.150
需要用勺子把它推起来 推得时候推推

0:04:27.252,0:04:30.439
但是回来的时候这边就不要刮到这边

0:04:36.552,0:04:39.146
好 今天就跟你们先分享到这里

0:04:39.436,0:04:43.566
就是说这三个动作 拉 

0:04:44.488,0:04:48.720
好 到第二个动作下去的时候有一定的弧度

0:04:50.938,0:04:55.290
第三个动作才开始拿勺子 推 炒

0:04:58.566,0:05:00.955
好了 本期视频就先跟你们聊到这里

0:05:01.177,0:05:05.563
下一期视频我会教大家放东西进去把它翻起来

0:05:06.092,0:05:07.218
好了 拜拜
```

**Comment by immoonancient** [comment]
@greentea007 请前来认领

**Comment by greentea007** [comment]
认领

**Comment by greentea007** [comment]
bot, please upload0:00:00.426,0:00:01.706
哈喽大家好我是王刚
Hello everyone, I am Wang Gang

0:00:02.269,0:00:05.290
今天我想跟大家分享一个翻锅的小技巧
Today, I will be sharing some techniques of wok tossing.

0:00:05.580,0:00:10.345
我的教学视频 做菜教学当中从来没有这个翻锅的小技巧
In my previous videos, I have never taught these techniques to you.

0:00:12.235,0:00:14.061
以前我以为在家里面吧 
I thought home cooking

0:00:14.283,0:00:18.617
大家可能不怎么会用得上这个翻锅的一些技巧
Does not require wok tossing

0:00:18.873,0:00:20.887
其实我觉得应该是我错了 
But I was wrong 

0:00:20.972,0:00:25.597
其实大家最渴望最基本的应该就是第一步 从翻锅开始
In fact, the most basic thing everyone desires are wok tossing

0:00:26.023,0:00:27.713
今天我就来跟大家分享 
I am sharing this with you guys today

0:00:28.174,0:00:33.788
包括从怎么样去用这个抓锅布到怎么样子去翻做第一节课
Including how to use wok towel to toss the wok

0:00:34.453,0:00:36.228
好 现在我们来开始来切这个布
Now, let’s cut this towel

0:00:36.877,0:00:40.273
我们一般厨房里面用的是这种毛巾
Normally, I use this type of kitchen towel

0:00:40.802,0:00:44.057
这个专门（用）做厨房里面的纯白色毛巾 
This cloth was designed to be used in kitchen

0:00:44.078,0:00:47.423
用来擦东西 也可以用来做抓锅布
You can wipe things with it, or use it as a wok towel

0:00:48.225,0:00:51.706
然后今天就用这个来切一块下来
Now, let’s cut this towel in half

0:00:52.354,0:00:54.402
我们叠这个毛巾的方法有很多
There are many ways to fold the towel

0:00:54.470,0:00:56.365
我今天就跟大家分享一个最简单的
I am going to share the easiest one with you

0:00:56.962,0:00:59.249
首先把这个布叠得这么宽
First, fold this towel like this

0:00:59.522,0:01:01.928
根据你自己的手掌这样子试一下
Use your palm to measure the width

0:01:02.252,0:01:04.897
差不多的话再往外面叠 再叠一层
And fold it one more time.

0:01:06.075,0:01:08.208
OK 然后这里给它切掉
OK cut it from here

0:01:16.723,0:01:18.959
好 然后我们直接对折过来
And then, we fold it like this

0:01:20.665,0:01:25.887
对折过来了之后待会儿我们上锅的时候把这个卡到耳朵里面就可以了
Now, let’s put the towel into the handle of the wok

0:01:26.331,0:01:28.651
这是最简单最普通的一个做法
And this is the easiest way to do it

0:01:28.907,0:01:33.276
然后我们还有一种拿抓锅布的办法是这样子的
There is another way to grab the towel as well

0:01:33.890,0:01:35.341
两只手（指）夹住这里
Use these two fingers to hold here

0:01:36.092,0:01:39.522
然后这边拿过来这样子 
And grab here

0:01:39.914,0:01:41.535
这个是随拿随走
The towel goes with your hand

0:01:41.604,0:01:46.877
我们手离开锅的时候 是拿着毛巾一起离开的
When we’re letting our hand off the wok, we grab the towel with us

0:01:47.150,0:01:50.972
还有一种就是直接挂在上面 挂在锅上面直接这样子拿的
You can hang your towel on the handle like this as well

0:01:52.354,0:01:53.959
好了 我们现在来试一下第一种
Alright, let’s try the first way to do it

0:01:54.368,0:01:57.935
第一种就是经常在我视频当中可以看到的直接挂上去
Normally, I just hang my towel on the handle in my videos

0:01:58.344,0:02:01.621
这样子这个布直接挂上去 这样就可以
Hang it on here, just like that

0:02:01.843,0:02:06.040
这个做法的话适合于我们川菜厨师 大部分都是这样子
Most Sichuanese chefs do it like that

0:02:06.075,0:02:07.218
因为简单省事儿
Easy and convince 

0:02:07.559,0:02:09.812
还有另外一种是粤菜厨师非常喜欢的
Another way is widely used by Cantonese chefs

0:02:10.068,0:02:12.354
就刚刚我说的两根手指夹住它 
Hold it by two fingers

0:02:12.713,0:02:17.235
然后手张开翻过来这样子拿
Open the palm and flip it like this

0:02:18.293,0:02:21.774
他是抓着这个抓锅布翻翻翻
Toss the wok like this

0:02:22.116,0:02:26.228
翻好了之后 他如果是打调料的话这个布是跟着手一起过来的
Grab the towel with you when you going to get some spices

0:02:26.433,0:02:33.088
其实如果你说哪一样更实用的话我觉得这个是更加实用的 简单直接
If you ask me which one do I prefer, I think the first one is better

0:02:34.180,0:02:35.784
我们新手的话这样就OK了
It works for beginners

0:02:36.058,0:02:40.354
好了 下面来分享一下翻锅的一些规则小技巧
Ok let me show you some tips to toss the wok

0:02:41.655,0:02:43.941
首先我们翻锅的话不要着急 急着翻
Firstly, do not rush to toss

0:02:44.112,0:02:47.201
我们先来第一步 就是拉锅 直线拉锅
Let’s learn how to pull the wok

0:02:47.337,0:02:49.692
直线拉锅现在锅放在这个位置 
Straightly pull the wok like this, place the wok over here

0:02:49.965,0:02:53.020
把它拉出来 拉出三分之一的位置 
About one third

0:02:53.242,0:02:55.170
大概是这个位置 三分之一
Roughly one third

0:02:55.546,0:02:57.969
然后我们再把它放下去
And then place it down

0:02:58.310,0:03:01.655
放下去放到什么位置呢 只要说不撞到这里就OK 
Make sure the side of the wok doesn’t touch the wok station when you push it back

0:03:05.221,0:03:06.757
这样子 我们先练习这一步
Let’s practice that

0:03:08.020,0:03:09.795
这一步一般练习三天
Usually, it takes three days to practice

0:03:10.153,0:03:13.198
这一步的目的就是锻炼你左手的力气
The purpose of this is the strengthen your left hand

0:03:13.225,0:03:16.569
然后是说推出去拉回来的这一步走直线 
Pull and push the wok on a straight line

0:03:16.877,0:03:20.597
不能够歪 歪了的话就会这样子
Don’t go zig zag

0:03:20.750,0:03:22.406
你中间的菜就会翻不过来
Your ingredient wont flip over if you do that

0:03:26.126,0:03:27.576
然后到我后面来看一下
Go behind me and check this out

0:03:27.935,0:03:30.409
从我肩膀 左肩的这个位置 
From my left shoulder
 
0:03:30.648,0:03:33.873
左肩锁骨这个位置 这里出去一条直线
From my left collarbone, push the wok on the straight line 

0:03:39.948,0:03:44.129
好 现在我们第一步会了之后来第二步
Let’s move on to the next step

0:03:44.965,0:03:48.191
第二步的话它就要出去之后有一个弧度上来
In the second step, it requires a curve to do

0:03:51.706,0:03:55.699
同样也是锅拉出来不要超出三分之一 这个位置左右
Same as the first step, pull up wok out on one third of the wok

0:03:55.802,0:04:00.849
然后下去了之后一点点弧度上来 下去上来
And then push it back, and pull it up again with an curve

0:04:00.853,0:04:05.563
好 我们再从我的后面来 锁骨的这个位置来看一下
Go behind me again to check it from my collarbone

0:04:08.856,0:04:13.293
好 这些我们练会了之后然后才开始拿勺子
After that, lets use the chef spoon

0:04:13.498,0:04:17.730
右手拿勺 拿勺子的话 勺子主要的目的是什么
Hold it on your right hand

0:04:17.883,0:04:23.208
这样子出去的时候 菜到这个位置它不会翻过来的
The purpose of it is to make sure  your ingredients can flip over

0:04:23.208,0:04:27.150
需要用勺子把它推起来 推得时候推推
Use you spoon to push it up

0:04:27.252,0:04:30.439
但是回来的时候这边就不要刮到这边
And don’t touch this side on the way back

0:04:36.552,0:04:39.146
好 今天就跟你们先分享到这里
Alright, that’s it today

0:04:39.436,0:04:43.566
就是说这三个动作 拉 
Three moves, pull

0:04:44.488,0:04:48.720
好 到第二个动作下去的时候有一定的弧度
Push with a curve

0:04:50.938,0:04:55.290
第三个动作才开始拿勺子 推 炒
And push with your spoon and start stir fry

0:04:58.566,0:05:00.955
好了 本期视频就先跟你们聊到这里
Ok, that’s today

0:05:01.177,0:05:05.563
下一期视频我会教大家放东西进去把它翻起来
In the next video, I’ll show you how to stir-fry with ingredients inside the wok

0:05:06.092,0:05:07.218
好了 拜拜
Bye bye
