### ISSUE TITLE
【美食作家王刚】农家小炒肉 - https://youtu.be/RcYq8W6xRZo

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#828]
**视频链接**：https://youtu.be/RcYq8W6xRZo

视频时长 3:56，预计发布时间为北京时间3月25日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“农家小炒肉”的最佳做法，家常味浓郁，下饭神器

简介
同学们好，今天和大家分享一道农家小炒肉，将五花肉和里脊肉分开来炒虽说较为繁琐，但效果特别好，不仅成菜更香并且也相对更加健康营养更加均和，农家味十足！
本期菜品:【青椒小炒肉】 
【主料】
五花肉（约150克）
里脊肉（约100克）
【辅料】
二荆条（300克） 
小米辣（几个）
蒜苗（2根）
大蒜（15克）
生姜（15克）
蛋清（2克）
干淀粉（少许）
植物油（适量）
【调味料】
食用盐（少许）
胡椒粉（少许）
生抽酱油（适量）
蚝油（6克）
白糖（少许）
老抽（2克）

字幕
0:00:00.300,0:00:01.440
哈喽大家好 我是王刚

0:00:01.440,0:00:03.540
本期视频我跟大家分享一道家常菜

0:00:03.940,0:00:05.380
青椒小炒肉

0:00:05.520,0:00:07.700
首先我们准备二荆条300克

0:00:07.875,0:00:10.175
去掉辣椒蒂之后再切成滚刀片备用

0:00:10.300,0:00:12.750
不能吃辣的同学可以用大青椒代替

0:00:21.400,0:00:23.475
准备小米辣几个切成小片备用

0:00:27.150,0:00:30.075
准备蒜苗2根拍散之后斜刀切成小段备用

0:00:34.275,0:00:37.575
准备大蒜和生姜各15克拍散之后剁碎备用

0:00:39.825,0:00:41.275
下一步开始准备主料

0:00:41.475,0:00:44.175
准备五花肉1小块去皮之后切成薄片备用（约150克）

0:00:44.175,0:00:46.400
同学们五花肉必须切得越薄越好

0:00:46.600,0:00:48.475
这样更容易炒香爆出猪油

0:00:51.075,0:00:54.075
准备里脊肉1小块逆着纹路切成薄片备用（约100克）

0:00:54.125,0:00:56.900
同学们加里脊肉的目的是让成菜肥瘦均匀

0:00:57.150,0:00:59.100
使其适合更广泛的人群食用

0:00:59.175,0:01:01.018
下一步开始准备腌里脊肉

0:01:01.250,0:01:03.075
碗中加入少许食用盐

0:01:03.300,0:01:04.525
加入少许胡椒粉

0:01:05.200,0:01:06.775
加入生抽酱油2克

0:01:08.600,0:01:10.825
加入蛋清2克之后抓拌均匀

0:01:16.000,0:01:18.125
中途加入少许的干淀粉拌匀

0:01:18.300,0:01:20.825
加干淀粉可以保持里脊肉嫩而不柴

0:01:21.300,0:01:23.625
最后加入适量的植物油拌匀即可

0:01:23.746,0:01:25.514
目的是防止下锅起团

0:01:29.350,0:01:30.750
下一步开始制作

0:01:31.275,0:01:32.725
首先我们把锅烧热

0:01:33.050,0:01:35.875
锅烧热之后将切好的辣椒下锅干炒2分钟

0:01:36.075,0:01:38.325
这一步的目的是提前将辣椒炒香

0:01:38.400,0:01:41.800
同学们切记这一步必须保持中火防止炒糊

0:01:44.375,0:01:46.900
将辣椒炒出虎皮状即可倒出备用

0:01:50.750,0:01:53.875
辣椒倒出之后将锅洗干净下一步开始炒肉

0:02:06.275,0:02:07.675
首先我们把锅烧热

0:02:08.075,0:02:10.350
锅烧热之后加入适量的油滑锅

0:02:12.800,0:02:14.675
滑好锅之后将热油倒出

0:02:16.850,0:02:19.550
然后将切好的五花肉下锅爆炒1分钟

0:02:19.675,0:02:22.275
这一步的目的是将五花肉爆香炒出猪油

0:02:22.375,0:02:24.750
同学们家庭小灶则需要2分钟左右

0:02:25.150,0:02:29.225
1分钟之后将腌好的里脊肉下锅翻炒几下炒至8成熟

0:02:38.925,0:02:41.075
中途加入剁好的姜蒜末爆香

0:02:50.325,0:02:53.050
里脊肉炒至8成熟之后下一步开始调味

0:02:53.225,0:02:54.700
锅中加入蚝油6克

0:02:56.175,0:02:58.300
加入生抽酱油4克从锅边淋入

0:02:59.450,0:03:01.175
加入少许白糖提鲜

0:03:01.825,0:03:03.475
加入少许胡椒粉

0:03:04.695,0:03:06.500
最后加入老抽2克调色

0:03:12.200,0:03:15.225
翻炒均匀之后将处理好的辣椒下锅翻炒均匀

0:03:20.450,0:03:23.850
最后再加入切好的蒜苗炒至断生即可出锅装盘

0:03:35.100,0:03:38.280
一道非常美味的家常菜小炒肉就制作完成

0:03:42.940,0:03:56.920
下面开始技术总结
第一，采用五花肉和里脊肉搭配可以显得肥瘦皆宜
第二，提前炒香的辣椒味更具农家风味
第三，此菜可以不用放盐，只需要蚝油酱油调咸味即可
小炒肉的技术总结完毕


```

**Comment by lhrotk** [comment]
认领

**Comment by lhrotk** [comment]
# 厨师长教你：“农家小炒肉”的最佳做法，家常味浓郁，下饭神器
# Chef Wang teaches you:The best practice of "stir fried meat", goes well with rice.

# 简介
#同学们好，今天和大家分享一道农家小炒肉，将五花肉和里脊肉分开来炒虽说较为繁琐，但效果特别好，不仅成菜更香并且也相对更加健康营养更加均和，农家味十足！
# 本期菜品:【青椒小炒肉】 
# 【主料】
# 五花肉（约150克）
# 里脊肉（约100克）
# 【辅料】
# 二荆条（300克） 
# 小米辣（几个）
# 蒜苗（2根）
# 大蒜（15克）
# 生姜（15克）
# 蛋清（2克）
# 干淀粉（少许）
# 植物油（适量）
# 【调味料】
# 食用盐（少许）
# 胡椒粉（少许）
# 生抽酱油（适量）
# 蚝油（6克）
# 白糖（少许）
# 老抽（2克）
# Introduction
# Hello friends, today I will share with you how to cook stir fried meat. Although separating the pork belly and tenderloin to fry is more cumbersome, but makes the dish particularly better. Not only the vegetables are more fragrant, but also relatively healthy and more nutritious.
# Dish of the issue:[stir fried meat green pepper]
# [Main material]
# Pork belly (about 150 grams)
# Tenderloin (about 100 g)
# [Accessories]
# "Erjingtiao" chili pepper (300 g)
# "Xiaomila" chili pepper (a few)
# Garlic sprouts (2)
# Garlic (15 g)
# Ginger (15 g)
# Egg white (2 g)
# Dried starch (a little)
# Vegetable oil (appropriate amount)
# 【seasoning】
# Table salt (a little)
# Ground pepper (a little)
# Light soy sauce (appropriate amount)
# Oyster sauce (6g)
# White sugar (a little)
# dark soy sauce (2g)

subtitle
0:00:00.300,0:00:01.440
Hello everyone, I'm Wang Gang

0:00:01.440,0:00:03.540
In this video I will share a home cooking

0:00:03.940,0:00:05.380
Stir-fried pork with green pepper

0:00:05.520,0:00:07.700
First we prepare 300g "Erjingtiao" chili pepper

0:00:07.875,0:00:10.175
After removing the pepper cap, cut into roll blades for later use

0:00:10.300,0:00:12.750
If you don't like spicy food, you can use a big green pepper instead

0:00:21.400,0:00:23.475
Prepare a few "Xiaomila" and cut into small pieces for later use

0:00:27.150,0:00:30.075
Prepare 2 garlic sprouts, and then cut them into small pieces diagonally.

0:00:34.275,0:00:37.575
Prepare garlic and ginger, each 15 grams, and crush them for later use.

0:00:39.825,0:00:41.275
The next step is to prepare the main ingredients

0:00:41.475,0:00:44.175
Prepare 1 small piece of pork belly and cut into thin slices (about 150 g)

0:00:44.175,0:00:46.400
You must cut the pork belly as thin as possible

0:00:46.600,0:00:48.475
This makes it easier to stir-fry the lard

0:00:51.075,0:00:54.075
Prepare a small piece of tenderloin and slice it against the grain for later use (about 100g)

0:00:54.125,0:00:56.900
The purpose of adding tenderloin is to make this dish fat and even.

0:00:57.150,0:00:59.100
Make it suitable for a wider population

0:00:59.175,0:01:01.018
The next step is to prepare the cured tenderloin

0:01:01.250,0:01:03.075
Add a pinch of salt to the bowl

0:01:03.300,0:01:04.525
Add a little pepper

0:01:05.200,0:01:06.775
Add 2 grams of light soy sauce

0:01:08.600,0:01:10.825
Add 2 grams of egg white and stir well

0:01:16.000,0:01:18.125
Add a little dry starch halfway through and mix well

0:01:18.300,0:01:20.825
Adding dried starch can keep tenderloin tender but not firewood

0:01:21.300,0:01:23.625
Finally add an appropriate amount of vegetable oil and mix well

0:01:23.746,0:01:25.514
The purpose is to prevent clump

0:01:29.350,0:01:30.750
Next step is fry

0:01:31.275,0:01:32.725
First let's heat the wok

0:01:33.050,0:01:35.875
After the wok is hot, fry the cutted peppers for 2 minutes

0:01:36.075,0:01:38.325
The purpose of this step is to bring out pepper's aroma 

0:01:38.400,0:01:41.800
please remember that at this step, maintain moderate fire to prevent speculation.

0:01:44.375,0:01:46.900
Stir the chili into a tiger skin and pour it out

0:01:50.750,0:01:53.875
After the peppers are poured out, clean the wok and start frying the meat.

0:02:06.275,0:02:07.675
First we preheat the wok

0:02:08.075,0:02:10.350
After the wok is hot, add the appropritate amount of oil

0:02:12.800,0:02:14.675
Pour out the hot oil afterwards

0:02:16.850,0:02:19.550
Then stir-fry the cut pork belly for 1 minute

0:02:19.675,0:02:22.275
The purpose of this step is to stir-fry pork belly for lard.

0:02:22.375,0:02:24.750
It takes about 2 minutes if using family stove

0:02:25.150,0:02:29.225
After 1 minute, stir-fry the marinated pork tenderloin a few times until it is medium well.

0:02:38.925,0:02:41.075
Add chopped ginger and garlic in between

0:02:50.325,0:02:53.050
The next step is to seasoning

0:02:53.225,0:02:54.700
Add 6 grams of oyster sauce to the wok

0:02:56.175,0:02:58.300
Add 4 grams of soy sauce

0:02:59.450,0:03:01.175
Add a little sugar to refresh

0:03:01.825,0:03:03.475
Add a little pepper

0:03:04.695,0:03:06.500
Finally add dark soy 2g for color

0:03:12.200,0:03:15.225
Add and stir-fry the processed peppers evenly afterwards.

0:03:20.450,0:03:23.850
Finally, add the chopped garlic sprouts and stir-fry until they are softened.

0:03:35.100,0:03:38.280
A very delicious homemade dish with small fried meat is done

0:03:42.940,0:03:56.920
Technical summary below
First, the use of pork belly and tenderloin can make it fat and even.
Second, the savory pepper flavor is more farm-like
Third, this dish does not need salt, just need oyster sauce soy sauce for salty taste
The technical summary of the stir fried meat is completed

**Comment by immoonancient** [comment]
bot, please upload on behalf of the assignee

厨师长教你：“农家小炒肉”的最佳做法，家常味浓郁，下饭神器
Chef Wang teaches you:The best practice of "stir fried meat", goes well with rice.

简介
同学们好，今天和大家分享一道农家小炒肉，将五花肉和里脊肉分开来炒虽说较为繁琐，但效果特别好，不仅成菜更香并且也相对更加健康营养更加均和，农家味十足！

本期菜品:【青椒小炒肉】
【主料】
五花肉（约150克）
里脊肉（约100克）
【辅料】
二荆条（300克）
小米辣（几个）
蒜苗（2根）
大蒜（15克）
生姜（15克）
蛋清（2克）
干淀粉（少许）
植物油（适量）
【调味料】
食用盐（少许）
胡椒粉（少许）
生抽酱油（适量）
蚝油（6克）
白糖（少许）
老抽（2克）
Introduction
Hello friends, today I will share with you how to cook stir fried meat. Although separating the pork belly and tenderloin to fry is more cumbersome, but makes the dish particularly better. Not only the vegetables are more fragrant, but also relatively healthy and more nutritious.
Dish of the issue:[stir fried meat green pepper]
[Main material]
Pork belly (about 150 grams)
Tenderloin (about 100 g)
[Accessories]
"Erjingtiao" chili pepper (300 g)
"Xiaomila" chili pepper (a few)
Garlic sprouts (2)
Garlic (15 g)
Ginger (15 g)
Egg white (2 g)
Dried starch (a little)
Vegetable oil (appropriate amount)
【seasoning】
Table salt (a little)
Ground pepper (a little)
Light soy sauce (appropriate amount)
Oyster sauce (6g)
White sugar (a little)
dark soy sauce (2g)

0:00:00.300,0:00:01.440
哈喽大家好 我是王刚
Hello everyone, I'm Wang Gang

0:00:01.440,0:00:03.540
本期视频我跟大家分享一道家常菜
In this video I will share a home cooking

0:00:03.940,0:00:05.380
青椒小炒肉
Stir-fried pork with green pepper

0:00:05.520,0:00:07.700
首先我们准备二荆条300克
First we prepare 300g "Erjingtiao" chili pepper

0:00:07.875,0:00:10.175
去掉辣椒蒂之后再切成滚刀片备用
After removing the pepper cap, cut into roll blades for later use

0:00:10.300,0:00:12.750
不能吃辣的同学可以用大青椒代替
If you don't like spicy food, you can use a big green pepper instead

0:00:21.400,0:00:23.475
准备小米辣几个切成小片备用
Prepare a few "Xiaomila" and cut into small pieces for later use

0:00:27.150,0:00:30.075
准备蒜苗2根拍散之后斜刀切成小段备用
Prepare 2 garlic sprouts, and then cut them into small pieces diagonally.

0:00:34.275,0:00:37.575
准备大蒜和生姜各15克拍散之后剁碎备用
Prepare garlic and ginger, each 15 grams, and crush them for later use.

0:00:39.825,0:00:41.275
下一步开始准备主料
The next step is to prepare the main ingredients

0:00:41.475,0:00:44.175
准备五花肉1小块去皮之后切成薄片备用（约150克）
Prepare 1 small piece of pork belly and cut into thin slices (about 150 g)

0:00:44.175,0:00:46.400
同学们五花肉必须切得越薄越好
You must cut the pork belly as thin as possible

0:00:46.600,0:00:48.475
这样更容易炒香爆出猪油
This makes it easier to stir-fry the lard

0:00:51.075,0:00:54.075
准备里脊肉1小块逆着纹路切成薄片备用（约100克）
Prepare a small piece of tenderloin and slice it against the grain for later use (about 100g)

0:00:54.125,0:00:56.900
同学们加里脊肉的目的是让成菜肥瘦均匀
The purpose of adding tenderloin is to make this dish fat and even.

0:00:57.150,0:00:59.100
使其适合更广泛的人群食用
Make it suitable for a wider population

0:00:59.175,0:01:01.018
下一步开始准备腌里脊肉
The next step is to prepare the cured tenderloin

0:01:01.250,0:01:03.075
碗中加入少许食用盐
Add a pinch of salt to the bowl

0:01:03.300,0:01:04.525
加入少许胡椒粉
Add a little pepper

0:01:05.200,0:01:06.775
加入生抽酱油2克
Add 2 grams of light soy sauce

0:01:08.600,0:01:10.825
加入蛋清2克之后抓拌均匀
Add 2 grams of egg white and stir well

0:01:16.000,0:01:18.125
中途加入少许的干淀粉拌匀
Add a little dry starch halfway through and mix well

0:01:18.300,0:01:20.825
加干淀粉可以保持里脊肉嫩而不柴
Adding dried starch can keep tenderloin tender but not firewood

0:01:21.300,0:01:23.625
最后加入适量的植物油拌匀即可
Finally add an appropriate amount of vegetable oil and mix well

0:01:23.746,0:01:25.514
目的是防止下锅起团
The purpose is to prevent clump

0:01:29.350,0:01:30.750
下一步开始制作
Next step is fry

0:01:31.275,0:01:32.725
首先我们把锅烧热
First let's heat the wok

0:01:33.050,0:01:35.875
锅烧热之后将切好的辣椒下锅干炒2分钟
After the wok is hot, fry the cutted peppers for 2 minutes

0:01:36.075,0:01:38.325
这一步的目的是提前将辣椒炒香
The purpose of this step is to bring out pepper's aroma

0:01:38.400,0:01:41.800
同学们切记这一步必须保持中火防止炒糊
please remember that at this step, maintain moderate fire to prevent speculation.

0:01:44.375,0:01:46.900
将辣椒炒出虎皮状即可倒出备用
Stir the chili into a tiger skin and pour it out

0:01:50.750,0:01:53.875
辣椒倒出之后将锅洗干净下一步开始炒肉
After the peppers are poured out, clean the wok and start frying the meat.

0:02:06.275,0:02:07.675
首先我们把锅烧热
First we preheat the wok

0:02:08.075,0:02:10.350
锅烧热之后加入适量的油滑锅
After the wok is hot, add the appropritate amount of oil

0:02:12.800,0:02:14.675
滑好锅之后将热油倒出
Pour out the hot oil afterwards

0:02:16.850,0:02:19.550
然后将切好的五花肉下锅爆炒1分钟
Then stir-fry the cut pork belly for 1 minute

0:02:19.675,0:02:22.275
这一步的目的是将五花肉爆香炒出猪油
The purpose of this step is to stir-fry pork belly for lard.

0:02:22.375,0:02:24.750
同学们家庭小灶则需要2分钟左右
It takes about 2 minutes if using family stove

0:02:25.150,0:02:29.225
1分钟之后将腌好的里脊肉下锅翻炒几下炒至8成熟
After 1 minute, stir-fry the marinated pork tenderloin a few times until it is medium well.

0:02:38.925,0:02:41.075
中途加入剁好的姜蒜末爆香
Add chopped ginger and garlic in between

0:02:50.325,0:02:53.050
里脊肉炒至8成熟之后下一步开始调味
The next step is to seasoning

0:02:53.225,0:02:54.700
锅中加入蚝油6克
Add 6 grams of oyster sauce to the wok

0:02:56.175,0:02:58.300
加入生抽酱油4克从锅边淋入
Add 4 grams of soy sauce

0:02:59.450,0:03:01.175
加入少许白糖提鲜
Add a little sugar to refresh

0:03:01.825,0:03:03.475
加入少许胡椒粉
Add a little pepper

0:03:04.695,0:03:06.500
最后加入老抽2克调色
Finally add dark soy 2g for color

0:03:12.200,0:03:15.225
翻炒均匀之后将处理好的辣椒下锅翻炒均匀
Add and stir-fry the processed peppers evenly afterwards.

0:03:20.450,0:03:23.850
最后再加入切好的蒜苗炒至断生即可出锅装盘
Finally, add the chopped garlic sprouts and stir-fry until they are softened.

0:03:35.100,0:03:38.280
一道非常美味的家常菜小炒肉就制作完成
A very delicious homemade dish with small fried meat is done

0:03:42.940,0:03:56.920
下面开始技术总结
第一，采用五花肉和里脊肉搭配可以显得肥瘦皆宜
第二，提前炒香的辣椒味更具农家风味
第三，此菜可以不用放盐，只需要蚝油酱油调咸味即可
小炒肉的技术总结完毕
Technical summary below
First, the use of pork belly and tenderloin can make it fat and even.
Second, the savory pepper flavor is more farm-like
Third, this dish does not need salt, just need oyster sauce soy sauce for salty taste
The technical summary of the stir fried meat is completed
