### ISSUE TITLE
【美食作家王刚】华农兄弟送的竹鼠 - https://youtu.be/hIUDPMbLlf4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#83]
【美食作家王刚】华农兄弟送的竹鼠 - https://youtu.be/hIUDPMbLlf4 
这是刚哥最新的视频私享链接，方便大家提前添加字幕
就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间8月21日晚6点

**Comment by GUThe** [comment]
8/19 22：30 start

**Comment by immoonancient** [comment]
建议开工的时候再 assign，这样谁先有时间谁先做

**Comment by immoonancient** [comment]
Sorry 我看漏了...
