### ISSUE TITLE
【美食作家王刚】 粉条炸丸子 - https://youtu.be/IWPA72YYLQ8

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#846]
**视频链接**：https://youtu.be/IWPA72YYLQ8

视频时长 5:03，预计发布时间为北京时间3月30日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：宽油炸“粉条素丸子”，外酥里嫩味道很赞，比肉丸子还香

简介
同学们好，今天给大家分享一道素菜“粉条丸子”，这样做出来的丸子外酥里嫩，虽说没有肉但味道却一点都不差，吃一个就想吃第二个根本停不下来（亲测），当然想吃肉的朋友可以加入适当的猪肉或者牛肉末，其他做法相同，希望大家喜欢本期内容。

本期菜品：【粉条炸丸子】
【主料】
红薯粉条（适量）
面粉（400克）
【辅料】
莲藕（1小块）
香菇（3个）
胡萝卜（1小块）
青瓜（1小块）
大葱（2根）
大红椒（半个）
酵母粉（约1克）
豆腐（1小块）
植物油（适量）
【调味料】
食用盐（约5克）


字幕
0:00:00.320,0:00:01.280
哈喽大家好 我是王刚

0:00:01.280,0:00:03.400
本期视频我给大家分享一道家常菜

0:00:03.880,0:00:05.020
粉条丸子

0:00:05.600,0:00:08.680
首先我们准备适量的红薯粉条放入盆中

0:00:08.875,0:00:11.825
然后加入80度左右的热水泡发30分钟

0:00:13.475,0:00:16.200
同学们以下辅料众多请做好笔记

0:00:16.225,0:00:19.050
准备莲藕1小块去皮之后切成小颗粒备用

0:00:19.075,0:00:21.600
加莲藕可以增加丸子爽脆的口感

0:00:23.600,0:00:26.450
准备香菇3个从中间片开之后切碎备用

0:00:26.450,0:00:28.825
加香菇可以代替味精增加鲜味

0:00:32.700,0:00:34.775
准备胡萝卜1小块切碎备用

0:00:37.550,0:00:39.375
准备青瓜1小块切碎备用

0:00:39.375,0:00:41.925
加胡萝卜和青瓜可以增加红绿色

0:00:43.400,0:00:46.125
准备大葱2根对半切开之后切碎备用

0:00:49.450,0:00:52.175
准备大红椒半个去掉辣椒籽之后切碎备用

0:00:52.200,0:00:54.500
加大红椒的目的是增加鲜甜味

0:00:57.100,0:00:59.350
最后将泡发好的粉条剁碎备用

0:00:59.350,0:01:01.150
粉条可以增加丸子的韧劲

0:01:01.150,0:01:02.550
下一步开始调糊

0:01:03.000,0:01:04.975
盆中加入普通面粉400克

0:01:04.975,0:01:07.475
面粉和颗粒辅料的比例为1:1

0:01:07.475,0:01:09.250
盆中加入酵母粉1小勺（约1克）

0:01:09.250,0:01:11.425
加入食用盐2勺半调底味（约5克）

0:01:13.350,0:01:15.625
然后我们加水之前先搅拌均匀

0:01:17.950,0:01:20.775
搅拌均匀之后少量多次的加入热水搅拌

0:01:20.900,0:01:23.100
同学们水温最好在60度以上

0:01:33.600,0:01:35.650
然后加入1小块豆腐捏碎

0:01:35.650,0:01:37.950
加豆腐可以增加成菜的香味

0:01:37.950,0:01:41.225
再加入和豆腐等量的面粉搅拌均匀收干水份

0:01:41.225,0:01:43.725
将其搅拌至可以挤出丸子即可

0:01:53.250,0:01:55.650
然后我们再加入适量的植物油拌匀

0:01:55.650,0:01:58.200
加植物油的目的是减少面团的粘度

0:02:04.725,0:02:07.718
搅拌均匀之后再加入所有切好的辅料拌匀

0:02:22.450,0:02:24.600
辅料拌匀之后下一步开始制作

0:02:25.300,0:02:26.850
首先我们把锅烧热

0:02:26.850,0:02:29.250
锅烧热之后举盆之力加入宽油

0:02:29.250,0:02:31.200
将油温烧至5成热

0:02:46.775,0:02:50.500
油温5成热之后将面团挤成大小均匀的丸子下锅

0:03:12.525,0:03:15.225
丸子下锅之后转中火炸至飘起来即可

0:03:20.575,0:03:23.327
中途需要将提前炸黄的丸子捞出

0:03:23.327,0:03:25.300
这一步的目的是防止炸糊

0:03:44.975,0:03:47.775
最后炸至丸子全部飘起来之后捞出备用

0:04:01.325,0:04:04.875
然后将油温升至6成热之后再下入丸子复炸10秒钟

0:04:04.900,0:04:06.900
这一步的目的是将表皮炸脆

0:04:13.525,0:04:15.950
10秒钟之后将丸子捞出即可上菜

0:04:28.640,0:04:31.400
一道外酥里嫩的粉条炸丸子就制作完成

0:04:39.160,0:05:02.880
下面开始技术总结
第一，所有蔬菜瓜果可以根据个人喜爱添加，最好全部切成小颗粒
第二，调面糊必须用60度以上的热水，这样调的糊炸出来更嫩
第三，炸至的时候油温不能太高，且边炸边捞出炸好的丸子
第四，此菜不仅可以加素菜还可以加入猪肉末或者牛肉
粉条丸子的技术总结完毕


```

**Comment by WuStevenShengyang** [comment]
标题
厨师长教你：宽油炸“粉条素丸子”，外酥里嫩味道很赞，比肉丸子还香
Chef Wang teaches you: Broad oil fried vegetarian glass noodle meatballs. Crispy outside and tender inside, more delicious than actual meatballs.

简介
同学们好，今天给大家分享一道素菜“粉条丸子”，这样做出来的丸子外酥里嫩，虽说没有肉但味道却一点都不差，吃一个就想吃第二个根本停不下来（亲测），当然想吃肉的朋友可以加入适当的猪肉或者牛肉末，其他做法相同，希望大家喜欢本期内容。
Hey friends, today I will share with you: Broad oil fried vegetarian glass noodle meatballs. They are crispy outside and tender inside. Althoug this dish doesn't have meat but it tastes delicious (I tried myself). You can't stop eating. However, you can also add minced pork or beef if you prefer.
本期菜品：【粉条炸丸子】
Dish: Vegetarian glass noodle meatballs
【主料】
Main Ingredient:
红薯粉条（适量）
Glass noodle
面粉（400克）
flour (400g)
【辅料】
Complementary Ingredient
莲藕（1小块）
Lotus root (a small chunk)
香菇（3个）
Shiitake muchroom (three)
胡萝卜（1小块）
Carrot (A small chunk)
青瓜（1小块）
Cucumber (A small chunk)
大葱（2根）
Spring onions (two)
大红椒（半个）
Red bell pepper (half)
酵母粉（约1克）
Yeast (About 1g)
豆腐（1小块）
Tofu (A small chunk)
植物油（适量）
Vegetable oil
【调味料】
Seasoning
食用盐（约5克）
Salt (About 5g)


字幕
0:00:00.320,0:00:01.280
哈喽大家好 我是王刚
Hi, this is Chef Wang Gang.

0:00:01.280,0:00:03.400
本期视频我给大家分享一道家常菜
Today, I will share with you a dish.

0:00:03.880,0:00:05.020
粉条丸子
Vegetarian Glass Noodle Meatballs.

0:00:05.600,0:00:08.680
首先我们准备适量的红薯粉条放入盆中
First, we need some glass noodle.

0:00:08.875,0:00:11.825
然后加入80度左右的热水泡发30分钟
Add 80 degrees Celsius hot water and soak the glass noodle for 30 minutes.

0:00:13.475,0:00:16.200
同学们以下辅料众多请做好笔记
Please pay attention. There will be lots of complementary ingredients.

0:00:16.225,0:00:19.050
准备莲藕1小块去皮之后切成小颗粒备用
Dice a small chunk of lotus root after peeling its skin off.

0:00:19.075,0:00:21.600
加莲藕可以增加丸子爽脆的口感
Adding lotus root will make the meatball more crunchy.

0:00:23.600,0:00:26.450
准备香菇3个从中间片开之后切碎备用
Prepare three shiitake mashroom. Slice them in half and mince them.

0:00:26.450,0:00:28.825
加香菇可以代替味精增加鲜味
Shiitake mushroom can be used as a replacement for MSG.

0:00:32.700,0:00:34.775
准备胡萝卜1小块切碎备用
Mince a small chunk of carrot.

0:00:37.550,0:00:39.375
准备青瓜1小块切碎备用
Mince a small chunk of cucumber.

0:00:39.375,0:00:41.925
加胡萝卜和青瓜可以增加红绿色
Adding cucumber and carrot will bring the meatball a sense of green and red color.

0:00:43.400,0:00:46.125
准备大葱2根对半切开之后切碎备用
Cut two spring onions in half and mince them.

0:00:49.450,0:00:52.175
准备大红椒半个去掉辣椒籽之后切碎备用
Prepare a red bell pepper, remove its seeds, and mince it.

0:00:52.200,0:00:54.500
加大红椒的目的是增加鲜甜味
Red bell pepper will provide sweetness and a umami taste to the meatball.

0:00:57.100,0:00:59.350
最后将泡发好的粉条剁碎备用
Lastly, mince the pre-soaked glass noodle.

0:00:59.350,0:01:01.150
粉条可以增加丸子的韧劲
Glass noodle will provide tenacity to the meatball.

0:01:01.150,0:01:02.550
下一步开始调糊
Now, let's make the batter.

0:01:03.000,0:01:04.975
盆中加入普通面粉400克
Add 400g of plain flour.

0:01:04.975,0:01:07.475
面粉和颗粒辅料的比例为1:1
The ratio of flour and complementary ingredients should be 1:1.

0:01:07.475,0:01:09.250
盆中加入酵母粉1小勺（约1克）
Add a small spoon of yeast (About 1g).

0:01:09.250,0:01:11.425
加入食用盐2勺半调底味（约5克）
Add two and a half spoons of salt (About 5g).

0:01:13.350,0:01:15.625
然后我们加水之前先搅拌均匀
Before we add in water, we need to mix them well.

0:01:17.950,0:01:20.775
搅拌均匀之后少量多次的加入热水搅拌
Add a little bit of hot water at a time.

0:01:20.900,0:01:23.100
同学们水温最好在60度以上
The water should be above 60 degrees Celsius.

0:01:33.600,0:01:35.650
然后加入1小块豆腐捏碎
Add a small chunk of crushed Tofu.

0:01:35.650,0:01:37.950
加豆腐可以增加成菜的香味
Tofu will provide aroma to the meatball.

0:01:37.950,0:01:41.225
再加入和豆腐等量的面粉搅拌均匀收干水份
Then, add equivalent amount of flour to soak up excess water. 

0:01:41.225,0:01:43.725
将其搅拌至可以挤出丸子即可
Mix the batter until you can squeeze meatball from it.

0:01:53.250,0:01:55.650
然后我们再加入适量的植物油拌匀
Then, add some vegetable oil.

0:01:55.650,0:01:58.200
加植物油的目的是减少面团的粘度
This will reduce the stickness of the batter.

0:02:04.725,0:02:07.718
搅拌均匀之后再加入所有切好的辅料拌匀
Then, we add in all of the complementary ingredients. 

0:02:22.450,0:02:24.600
辅料拌匀之后下一步开始制作
Mix them well.

0:02:25.300,0:02:26.850
首先我们把锅烧热
We need to heat up the wok first.

0:02:26.850,0:02:29.250
锅烧热之后举盆之力加入宽油
Add Kuan You (literally "broad oil") 	

0:02:29.250,0:02:31.200
将油温烧至5成热
Heat up the oil to 50%.

0:02:46.775,0:02:50.500
油温5成热之后将面团挤成大小均匀的丸子下锅
Squeeze the batter into meatballs and put them in the oil.

0:03:12.525,0:03:15.225
丸子下锅之后转中火炸至飘起来即可
After putting the meatballs in, turn the stove to medium and wait until they start to float.

0:03:20.575,0:03:23.327
中途需要将提前炸黄的丸子捞出
We have to take out the meatballs that are already golden.

0:03:23.327,0:03:25.300
这一步的目的是防止炸糊
To prevent them from burning.

0:03:44.975,0:03:47.775
最后炸至丸子全部飘起来之后捞出备用
Take out all the meatballs until they are floating.

0:04:01.325,0:04:04.875
然后将油温升至6成热之后再下入丸子复炸10秒钟
Then, heat up the oil to 60% and re-fry the meatballs for 10 seconds.

0:04:04.900,0:04:06.900
这一步的目的是将表皮炸脆
This will make the meatballs crispy.

0:04:13.525,0:04:15.950
10秒钟之后将丸子捞出即可上菜
After 10 seconds, take the meatballs out.

0:04:28.640,0:04:31.400
一道外酥里嫩的粉条炸丸子就制作完成
A delicious glass noodle meatball is finished.

0:04:39.160,0:05:02.880
下面开始技术总结
第一，所有蔬菜瓜果可以根据个人喜爱添加，最好全部切成小颗粒
第二，调面糊必须用60度以上的热水，这样调的糊炸出来更嫩
第三，炸至的时候油温不能太高，且边炸边捞出炸好的丸子
第四，此菜不仅可以加素菜还可以加入猪肉末或者牛肉
粉条丸子的技术总结完毕
Technical Summary:
First, you can add any vegetable you want, but remember to finely mince them.
Second, the water has to be above 60 degree Celsius when making the batter. This will make the meatballs more tender.
Third, don't heat up the oil to high. You also have to take out the meatballs that are already fully fried.
Fourth, you can also add minced pork or beef to this dish if you prefer.
That's all for glass noodle meatball's technical summary.
