### ISSUE TITLE
[老饭骨] 火焰醉龙虾 - https://www.youtube.com/watch?v=6H-2KjVMW9k

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#849]
**视频链接**：https://www.youtube.com/watch?v=6H-2KjVMW9k

# 请翻译以下全部内容

**标题（翻译主要意思即可，不要超过 100 个字符）**
【国宴大师•火焰醉龙虾】酒香虾鲜，这么特别的小龙虾做法你见过吗？三叔奇招火焰醉龙虾，带你解锁小龙虾的新吃法！二伯都馋了！

**简介**
小友们好，三叔这次又给我们带来了他的奇招——火焰醉龙虾。
这名字听起来就不简单。小龙虾先过油炸一下，这样肉更紧致，还能去味儿。
依次加入了三种酒，花雕酒、米酒和白酒，这可真的是醉龙虾！
淋入白酒之后迅速点燃，这步可以带走更多的腥气，还能让酒香沁进小龙虾里。小友们要是在家做这道菜可一定要注意安全。
收汁之后看看咱二伯都馋的忍不住了，在那儿可劲儿扒拉三叔。
吃惯了十三香和麻小，这道火焰醉龙虾的做法是不是让人眼前一亮呢？

**字幕**
需自行制作时间轴和对照中文
自动翻译提示功能不可用，请人工参考[对译表](https://immoonancient.github.io/YTSubtitles/static/translation-table.html)

**Comment by Losskywalker** [comment]
bot, please upload
Title: [State Banquet Master Chefs' Crayfish in flame]

Introduction.
Dear followers, Sanshu has brought his special dish: Crayfish in flame.
Sounds amazing already right? First you need to deep fry the crayfish to make the flesh more tight and to get rid of unwanted smells. Then we added three different types of alcohol: the Chinese rice wine, the fermented sticky rice and the Chinese liqueur. It's almost like a "drunken" crayfish dish. Light it up after pouring the Chinese liqueur to remove the unwanted smell while disolving the alcoholic flavour into the crayfish. But please be careful when you cook this at home.
Even Er Bai cannot hold himself after it's done.
After having the traditional crayfish dishes, maybe you should give this new dish a try?


0:00:00.005,0:00:00.780
Crayfish in flames

0:00:00.780,0:00:03.060
Crayfish in flames

0:00:03.720,0:00:05.860
Here we go. Sanshu has been waiting for this for a whole day for this.

0:00:06.840,0:00:08.980
Looks like he is going to deep fry it

0:00:08.980,0:00:10.860
Get the oil hot and fry it quickly

0:00:11.120,0:00:12.680
Let's drain it first.

0:00:12.680,0:00:14.040
Pour it in!

0:00:16.760,0:00:19.400
The steam is coming out this way 

0:00:20.020,0:00:23.000
Deep-frying removes the fishy smell as well as using vinegar

0:00:23.580,0:00:26.200
It also makes it more firm

0:00:26.680,0:00:28.960
Indeed, it removes all the unwanted smells

0:00:29.740,0:00:30.740


0:00:31.660,0:00:33.620
It also gives a nice color

0:00:33.900,0:00:36.920
The frying makes the crayfish more "open" to absorbed flavor.

0:00:36.920,0:00:38.420
I wouldn't fry it though.

0:00:38.560,0:00:39.720
Can you pass the dried shrimps to me?

0:00:39.720,0:00:41.520
We didn't soak it in advance. That's alright.

0:00:41.640,0:00:46.620
We must fry the dried shrimps slowly with the crayfish.

0:00:46.740,0:00:49.400
Get the flavors out (Spring onion and ginger in)

0:00:50.540,0:00:52.080
Where is the Chinese rice wine?

0:00:52.340,0:00:54.720
The "Hua Diao" rice wine.

0:00:55.000,0:00:56.780
That's quite a lot of seasoning.

0:00:57.000,0:00:59.360
What is that? Laozao(fermented sticky rice)

0:00:59.940,0:01:02.760
Crayfish with Laozao, that's a southern dish.

0:01:02.920,0:01:06.100
It's almost like fried rice with lobster.

0:01:06.420,0:01:08.940
See?

0:01:09.045,0:01:10.045


0:01:10.625,0:01:11.575


0:01:11.575,0:01:12.985


0:01:13.600,0:01:14.600


0:01:16.840,0:01:19.900
They call this the "drunken" crayfish in the south.

0:01:19.900,0:01:22.340
As it was cooked with rice wine.

0:01:23.235,0:01:24.265


0:01:24.800,0:01:25.800


0:01:25.980,0:01:29.920
The rice wine is at about 11-12%, sometimes up to 17%   

0:01:30.420,0:01:31.980
Looks good.

0:01:32.000,0:01:36.520
Ok now, sugar and salt. (That's a lot of sugar)

0:01:36.520,0:01:37.020


0:01:37.025,0:01:37.300


0:01:37.300,0:01:39.800


0:01:43.280,0:01:45.200


0:01:45.200,0:01:49.540
(pour some Chinese liqueur around the lid)

0:01:51.300,0:01:52.700
Crayfish in flame

0:01:53.960,0:01:58.520
Sidi, film it quickly before the flame goes out.

0:01:58.680,0:02:02.500
Here we have it, the crayfish in flame. We waited so long for this moment.

0:02:02.600,0:02:06.300
We have to keep reducing the sauce on high heat.

0:02:07.640,0:02:09.640
Almost done

0:02:10.860,0:02:12.960
Daye, grab a spoon and have a taste first.

0:02:13.140,0:02:14.960
The sauce looks sweet.

0:02:15.220,0:02:18.140
Nice flavor from the rice wine and the crayfish

0:02:19.140,0:02:21.540
Is it sweet enough? Yes 

0:02:21.780,0:02:23.420
Let me have a taste. Wait wait it's coming.

0:02:23.680,0:02:24.860
Really nice.

0:02:25.240,0:02:29.440
Let's pick the spring onion and ginger out.

0:02:29.440,0:02:30.840
How was the taste?

0:02:31.040,0:02:33.380
What can I say, a new signature dish on Guijie
(Famous food location in Beijing)

0:02:33.960,0:02:34.460


0:02:36.260,0:02:37.620
It's done!

0:02:37.820,0:02:40.100
That was a quick and smooth move.

0:02:40.520,0:02:43.180
OK, turn off the heat.

0:02:43.460,0:02:45.900
Is that a nice bright color?(nice)

0:02:48.520,0:02:51.060
Fragrant rice wine combined with nice flavor of the crayfish

0:02:51.060,0:02:54.160
Color? Nice bright red.

0:02:54.160,0:02:56.720


0:02:58.795,0:03:00.205


0:03:01.175,0:03:03.155


0:03:03.575,0:03:04.435


0:03:04.435,0:03:05.435


0:03:05.985,0:03:07.425


0:03:08.020,0:03:09.020


0:03:11.960,0:03:13.240
我是大爷
