### ISSUE TITLE
[华农兄弟] 华农兄弟看一下金银花开了没有顺便看一下送出去的小狗子 - https://youtu.be/QALA-4TxA9Y

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#854]
https://youtu.be/QALA-4TxA9Y
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 27, 2020 at 11:35AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/QALA-4TxA9Y

#华农兄弟：看一下金银花开了没有，顺便看一下送出去的小狗子
#Huanong Brothers: We see if the honeysuckles have blossomed. And then we have a look at the puppies that we gave out.

0:00:00.000,0:00:02.560
# 大家好  現在看一下那個金銀花有沒有開
Hi everyone! We're gonna have a look at the honeysuckles, and see if they have blossomed.

0:00:02.900,0:00:04.460
# 就有前面  前面很多的哦
There are a lot, just in front of us.

0:00:04.900,0:00:06.580
# 這個就是  我們這邊叫
This is, here it's called,

0:00:07.500,0:00:09.940
# 酸葉子  就這樣子  它葉子有點酸酸的
sour leaf. So here it is. It's a little bit sour.

0:00:12.240,0:00:14.560
# 有點酸酸的  甘甜甘甜的  這個
It's a bit sour and savory sweet, I mean...

0:00:15.720,0:00:16.380
# 很好吃的哦
It's really tasty.

0:00:20.380,0:00:21.120
# 味道還可以
It tastes not too bad.

0:00:22.120,0:00:24.500
# 因為現在還沒長齊  它剛剛長的嫩芽
Cuz it's still growing, only the shoots have come out.

0:00:24.740,0:00:26.580
# 嫩芽出來有那麼長的話 直接
When the shoots become that long, I can,

0:00:26.940,0:00:28.320
# 把這裡摘  摘下來吃
pick, pick this part right away.

0:00:29.880,0:00:31.280
# 酸酸甜甜  很開胃
It's sweet and sour, really appetizing.

0:00:32.580,0:00:33.600
# 好多這個小花
Here are a lot of this kind of flowers.

0:00:35.260,0:00:37.520
# 這樣一束一束摘起來  很漂亮的哦
I'm picking them in bunches. It's really pretty, you know.

0:00:38.360,0:00:39.900
# 這個我但這邊也不知道叫甚麼
I've no ideas how it's called here.

0:00:39.900,0:00:41.460
# 那個牛很喜喜歡吃的  這個
It's the cattle's favourite food.

0:00:42.420,0:00:43.360
# 我們這邊叫做  
Here it's called,

0:00:43.660,0:00:44.260
# 紅花草  (註︰那他究竟是知還是不知....)
"red flower grass".

0:00:46.460,0:00:47.580
# 哇  好香
Wa! It smells great!

0:00:53.840,0:00:55.120
# 你看這個金銀花
Have a look at the honeysuckles!

0:00:55.600,0:00:56.940
# 剛剛有點花蕾
There are some newly grown buds,

0:00:58.660,0:00:59.460
# 小花蕾
small buds.

0:01:00.740,0:01:02.040
# 還有開花 來早啦
We come too early. They've still not yet blossomed.

0:01:02.540,0:01:03.480
# 晚一點的話
If we come later...

0:01:03.920,0:01:05.380
# 晚一點的話又不知道有沒有啦
But I wonder if there's anything left if we come later.

0:01:06.020,0:01:07.120
# 到時候我經常來看一下
I gotta check more often then,

0:01:07.620,0:01:08.380
# 經常來看一下
check more often.

0:01:10.040,0:01:10.700
# 這些都是
These are all,

0:01:11.720,0:01:12.380
# 金銀花
 honeysuckles.

0:01:13.480,0:01:16.000
# 這邊應該用牛  牛拱的  拱那麼長
I think it's taken down, taken down by cattle. It's such a long path.

0:01:16.320,0:01:17.880
# 那麼  那麼乾淨這邊  (註︰他究竟想說甚麼....)
Everything is cleared here.

0:01:19.220,0:01:19.880
# 肯定有
Yea, I'm sure.

0:01:23.920,0:01:25.700
# 你看  這個好多這個拿藤包啊
Look! Here are a lot of chocolate vines.

0:01:26.200,0:01:28.180
# 長得一卡一卡的  你看 都是
They're in batches. Look! They're everywhere.

0:01:28.540,0:01:31.040
# 這個是花  花謝了之後就長這個果實
This is a flower. When the flower withers, it becomes a, well, a fruit.

0:01:31.320,0:01:32.260
# 這個是小拿藤包
This is a small chocolate vine.

0:01:32.700,0:01:33.240
# 一個
One,

0:01:33.840,0:01:36.100
# 三個  六個  四個 
three, six, four

0:01:36.560,0:01:37.760
# 你看  好多啊
Look! A lot!

0:01:38.940,0:01:39.760
# 這棵也是
And this one too

0:01:40.720,0:01:42.340
# 到時候有些可能就是
Later, I think, it's like,

0:01:42.440,0:01:44.380
# 營養不好的話就算己慢慢凋謝掉
the weaker ones might be falling off by themselves.

0:01:44.700,0:01:47.720
# 如果好的話它就會慢慢地長出那個果來  嘖
And the stronger ones will turn gradually into fruits, nice!

0:01:48.280,0:01:50.140
# 就等你們長大啦  走啦
We'll wait, until you grow up. Let's go!

0:01:50.920,0:01:52.800
# 這是上次我送給大姑家的小狗
They are the puppies that I gave to my aunt last time.

0:01:55.020,0:01:55.560
# 狗
Puppies!

0:01:56.900,0:01:58.880
# 這雞  我又沒檢你的雞蛋
This chicken... C'mon, I'm not picking your eggs.

0:01:59.960,0:02:01.520
# 叫得那麼大聲  小狗
You're yelping so loudly, oh, puppies!

0:02:09.060,0:02:10.900
# 那麼胖  好像大了一點哦
So chubby. It seems that they've grown a bit, right?

0:02:14.300,0:02:14.860
# 過來
Come here!

0:02:18.540,0:02:19.280
# 過來  過來
Come here, come here!

0:02:20.040,0:02:20.960
# 它不肯過來
She doesn't want to come.

0:02:21.160,0:02:21.660
# 小狗
Puppy!

0:02:22.520,0:02:24.740
# 它也不肯過來喲  我碰一下它就呱呱叫
He's not coming. He yelps with all his might whenever I touch him.

0:02:27.620,0:02:28.420
# 現在很激動
You're now really excited

0:02:28.740,0:02:29.340
# 是不是
aren't you?

0:02:29.580,0:02:31.340
# 是不是想不到我還來看你  是不是
You've never expected that I'll still come and see you, have you?

0:02:31.940,0:02:33.920
# 就那我近  我會經常來看你的
We are living so close. I'll come and see you often.

0:02:36.020,0:02:38.020
# 這個是公的哦  那個是母的
This one is a boy, and that one is a girl.

0:02:44.980,0:02:45.640
# 小狗
Puppies!

0:02:46.240,0:02:46.880
# 過來
Come here!

0:02:49.720,0:02:50.640
# 好激動啊  它們
They're really excited!

0:02:51.580,0:02:52.320
# 不要我啦
I'm abandoned.

0:02:53.740,0:02:55.720
# 小狗  很開心啊  在這裡
Puppies! Are you very happy living here?

0:02:56.240,0:02:58.900
# 轉來轉去的  那麼寬  就它們兩個人
Here are just you two, running here and there, in such a large space.

0:03:02.320,0:03:02.940
# 小狗
Puppies!

0:03:03.240,0:03:03.820
# 過來
Come here!

0:03:05.600,0:03:07.140
# 哎喲 捉都捉不到你
Ayo! I can't even catch you!

0:03:08.680,0:03:09.720
# 嗯 小狗  過來
Um! Puppy! Come here!

0:03:12.600,0:03:13.600
# 你看  這個小母狗
Look! This little girl!

0:03:15.460,0:03:16.720
# 不許  不許動
No! Don't move!

0:03:17.140,0:03:18.780
# 不許動 怎機那麼調皮
Don't move! Why are you so naughty?

0:03:20.400,0:03:22.080
# 你要我摸一下是不是  你又不要我
You want my petting, don't you? No, you don't want me.

0:03:23.320,0:03:24.020
# 哎呀
Aya!

0:03:25.260,0:03:26.040
# 不許動
Don't move!

0:03:26.680,0:03:27.360
# 知不知道
Got it?

0:03:32.020,0:03:32.720
# 它不動敢
She dares not move.

0:03:34.120,0:03:34.940
# 你看  這個是
Look! She is,

0:03:35.160,0:03:36.220
# 戴了一個白手套  
wearing a pair of white gloves.

0:03:42.540,0:03:43.200
# 你過來
It's your turn!

0:03:44.120,0:03:45.700
# 那個狗  它不肯過來
That puppy, doesn't want to come.

0:03:48.100,0:03:49.600
# 你看  這個  摸都摸(不)[SIC]到它
Look! I can't, I can't even touch it.

0:03:57.200,0:03:59.660
# 像個裡很乾淨的 毛色都好多啦
It's a very clean place here and their coats look so much better.

0:04:00.180,0:04:01.100
# 而吃得又好
They have very good food too.

0:04:02.820,0:04:04.840
# 是啊  每天的剩飯剩菜都給它們吃
Yup! They have all the leftover every day.

0:04:05.020,0:04:05.820
# 吃得好飽啊
They're very well fed.

0:04:08.160,0:04:10.940
# 比我們那裡好多啦  我們那只吃到米糠拌飯
It's so much better than our place. They had only rice and bran at our place,

0:04:11.540,0:04:12.480
# 啥都沒得吃
and nothing else.

0:04:18.300,0:04:19.000
# 過來
Come here!

0:04:19.520,0:04:22.140
# 你還在呵呵呵呵呵呵呵呵呵 是笑吧
You're always like, ho ho ho ho ho ho ho ho. Are you laughing?

0:04:22.580,0:04:23.080
# 是不是
Are you?

0:04:23.480,0:04:24.820
# 是不是你在笑  是不是
Are you laughing? Are you?

0:04:25.360,0:04:27.800
# 是不是在  在這裡天天都吃好的喝好的  是不是
Do you, do you have good food and food drinks here every day? Do you?

0:04:28.620,0:04:29.160
# 是不是
Do you?

0:04:30.160,0:04:30.960
# 你家主人呢
Where's you master?

0:04:31.520,0:04:32.620
# 你家主人去哪裡啦
Where's your master now?

0:04:33.840,0:04:35.340
# 啊  你家主人去哪裡啦
Ah! Where's your master now?

0:04:38.240,0:04:38.840
# 去哪裡啦
Where is he?

0:04:48.280,0:04:49.100
# 哎喲  這裡
Ayo! Here,

0:04:49.600,0:04:50.720
# 這裡好像受傷啦
Here seems to be a wound.

0:04:52.340,0:04:53.960
# 是不是兩  你們兩打架啦
I bet two, you two must had a fight, right?

0:04:54.800,0:04:55.740
# 不可以打架哦
No fighting! Got it?

0:04:56.660,0:04:57.960
# 你又那麼兇  你看
You know how fierce you are? Look!

0:04:58.000,0:04:59.600
# 笨 碰都碰不到你
You, you don't even let me touch you.

0:04:59.980,0:05:00.960
# 太壞啦  它
What a bad boy!

0:05:02.000,0:05:04.660
# 抓都抓不住的  一抓它都呱呱叫的  這個
Don't even think of catching him. He would yelp with all his might on your hand, this boy.

0:05:05.020,0:05:05.620
# 過來
Come here!

0:05:06.140,0:05:06.680
# 過來
Come here!

0:05:07.540,0:05:08.040
# 你看
Look!

0:05:08.620,0:05:10.080
# 挨都不會挨我一下
He doesn't even lean on me.

0:05:14.000,0:05:14.660
# 老是跑
He just runs away.

0:05:20.520,0:05:21.400
# 很激動哦
They're so excited,

0:05:21.740,0:05:22.760
# 又像小黑哦
just like Blacky.

0:05:30.060,0:05:32.340
# 你看  我抓了它  它不敢掙扎啦
Look! She's now on my hand and she dares not struggle anymore.

0:05:33.080,0:05:34.840
# 掙扎我就打它  打它屁屁
I would spank, spank her if she dares to struggle.

0:05:35.580,0:05:36.160
# 是不是
Am I right?

0:05:37.120,0:05:39.060
# 這個很可愛哦  你看  它的耳朵
She's really cute. I mean, her ears,

0:05:39.560,0:05:41.080
# 輕微的  輕微的
are a bit, a bit,

0:05:42.020,0:05:43.600
# 這樣  彎過來啦
like, floppy.

0:05:48.200,0:05:49.040
# 小狗
Puppy!

0:05:50.280,0:05:52.060
# 小狗  哎呀  是不是有跳蚤
Puppy! Aya! Is it a flea?

0:05:53.000,0:05:53.620
# 沒有
No, it's not.

0:05:54.560,0:05:55.660
# 很乖喲 小狗
She's a good girl, puppy.

0:05:58.580,0:05:59.220
# 要不要
Do you,

0:06:00.400,0:06:00.900
# 一起
wanna,

0:06:01.460,0:06:02.100
# 跳個舞
dance with me?

0:06:04.280,0:06:05.040
# 它不幹
No, she doens't.

0:06:05.860,0:06:06.940
# 來  跳舞
C'mon! Let's dance!

0:06:11.780,0:06:12.340
# 它不肯
She doesn't like it.

0:06:32.160,0:06:34.040
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.

0:06:34.240,0:06:36.360
# 到時候我們來  經常來看下它們
We'll come here, come here to see them more often.

0:06:37.060,0:06:38.360
# 看的它們慢慢長大
We'll see them grow to adults.

0:06:40.120,0:06:40.780
# 回去啦
Let's go back.
