### ISSUE TITLE
【美食作家王刚】盘龙茄子 - https://youtu.be/uLh3QMVr7og

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#86]
【美食作家王刚】盘龙茄子 - https://youtu.be/uLh3QMVr7og
这是刚哥最新的视频私享链接，方便大家提前添加字幕，做菜过程文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。然后就是由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！
本视频预计发布时间为北京时间8月22日晚6点

首先我们准备嫩茄子2根
切掉茄子蒂之后开始改刀
同学们最好选择比较嫩且直的茄子
首先我们用正刀切进茄子五分之三的深度
用刀尖顶着菜板刀刃与菜板的角度为45度
没有手感的同学可以在茄子下面垫上一双筷子
正面切好之后再翻过来
用同样的方式再加上刀身与茄子倾斜成45度角
切进茄子七分之四的深度
同样每一刀都必须保持一致
这样才能保证茄子本身不断且美观
茄子切好之后下一步开始准备辅料
准备去皮的五花肉一块切成小粒备用
分享一个小窍门
肉末切碎的比剁碎的更香
准备红椒一小块切成小粒备用
加红椒的目的是增加菜品的色彩
准备大蒜几颗拍散之后剁碎备用
最后准备生姜1小块剁碎备用
温馨提示：此菜为宽油制作，舍不得的同学请谨慎观看
下一步开始制作
首先我们把锅烧热
锅烧热之后加入宽油
然后将油温烧至5成热
油温5成热之后将切好的茄子下锅炸熟炸透
茄子下锅炸的中途必须保持火力一致
油温高容易炸胡油温底容易吸油
然后在起锅之前将茄子盘成一个圆圈后捞出备用
宽油倒出可以反复使用请不必担心浪费
将热油倒出之后下一步开始制作
然后将切好的肉末下锅中火爆香炒出猪油
猪肉爆香之后加入准备好的料头下锅翻炒均匀
翻炒均匀之后下一步开始调味
锅中加入蚝油8克
加入老抽2克调底色
加入生抽酱油4克从锅边淋入
然后再加入适量的清水
锅中加入少许食用盐调咸味
加入一点点胡椒粉
最后加入少许的白糖提鲜
调好味之后加入适量的水淀粉把汤汁收浓（土豆淀粉）
汤汁收浓后将炸好的茄子下锅烧2分钟烧至入味
中途可以用筷子把茄子再盘得圆一些
2分钟之后撒入适量的葱花即可出锅装盘
一道非常美观下饭的盘龙茄子就制作完成
下面开始技术总结
第一，最好选择紧实且嫩的茄子，这样在切的时候才不容易断开
第二，茄子下锅炸的时候油温不能低于160度和高于180度
，否则茄子会吸油或者炸焦
第三，锅中打好汤汁后应先勾芡，茄子下锅后才能减少搅动
盘龙茄子的技术总结完毕

**Comment by kdliu86** [comment]
#90

**Comment by immoonancient** [comment]
已发布
