### ISSUE TITLE
[华农兄弟] 小肥狗 - https://youtu.be/Q4anfmEyU2Y

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#871]
https://youtu.be/Q4anfmEyU2Y
<p>&#35270;&#39057;&#21457;&#24067;&#20110; March 31, 2020 at 12:09PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
#https://youtu.be/Q4anfmEyU2Y

#华农兄弟：这只小肥狗越来越胖了，称一下看有多少斤
#Huanong Brothes: This chubby puppy is getting bigger and bigger. Let's weigh him.

0:00:00.000,0:00:03.740
# 大家好 今天我秤一下那個大肥狗  看一下有多重啦
Hi everyone! Today I'm gonna weigh the big fat dog, and see how heavy he is now.

0:00:03.900,0:00:05.020
# 應該差不多20斤啦
I think he should be almost 10 kilograms.

0:00:05.400,0:00:06.440
# 就它長得最大
He's always the biggest.

0:00:09.900,0:00:10.420
# 小狗
Puppies!

0:00:11.200,0:00:12.000
# 過來  過來  過來
Come here, come here, come here!

0:00:15.020,0:00:15.620
# 狗
Doggies!

0:00:17.720,0:00:18.280
# 狗
Doggies!

0:00:20.480,0:00:22.560
# 嗯  這條最聽話它  秤一下你
Um! This is always the good boy. Let me weigh you.

0:00:22.820,0:00:23.360
# 坐穩
Sit well!

0:00:23.560,0:00:24.980
# 哎呀  好重
Aiya! He's so heavy!

0:00:25.560,0:00:26.160
# 坐下來
Sit down!

0:00:32.420,0:00:33.060
# 坐著嘛
Just sit down!

0:00:37.440,0:00:38.340
# 坐著就行啦
Sit down and relax!

0:00:39.440,0:00:39.940
# 你看
Look!

0:00:40.660,0:00:41.440
# 公斤秤
It's in kilograms.

0:00:42.040,0:00:42.720
# 9斤
Nine

0:00:42.920,0:00:43.740
# 9斤4兩
9.4 kilograms

0:00:44.980,0:00:45.480
# 你看
Look!

0:00:45.720,0:00:46.320
# 這個狗
This dog,

0:00:48.340,0:00:49.300
# 好乖的哦  這條
he's a very good boy, you know.

0:00:54.700,0:00:55.660
# 它  他的毛
His, his coat,

0:00:56.180,0:00:57.380
# 好多哇  這個毛
is really thick, his coat.

0:00:58.380,0:00:59.740
# 現在都19斤啦
He's now almost 10 kilograms.

0:01:00.960,0:01:03.320
# 它多少個月  2個月  2個月左右
How old is he? Two months, around two months

0:01:03.680,0:01:04.780
# 就長了19斤啦
And he's now almost 10 kilograms.

0:01:07.200,0:01:08.500
# 長得太快了哇  你
Don't you think that you're growing too fast?

0:01:09.800,0:01:10.700
# 很聽話的哦
He's a really good boy.

0:01:10.780,0:01:12.000
# 我一叫它  它就不走啦
He never runs away whenever I call him,

0:01:13.100,0:01:14.960
# 其它的一看到我來啦  全跑啦
while the others all run away whenever they see me.

0:01:19.600,0:01:20.920
# 乖 走
Good boy! Go!

0:01:22.820,0:01:24.600
# 下次天晴的時候給它去洗一下澡
I'll bathe him next time when it's sunny.

0:01:24.720,0:01:25.840
# 好髒呀 它的毛
His coat is so dirty now.

0:01:28.440,0:01:29.040
# 哎呀
Aya!

0:01:29.760,0:01:30.260
# 小狗
Puppy!

0:01:31.820,0:01:32.320
# 你看
Look!

0:01:32.560,0:01:33.760
# 夠高哦  現在
He's quite tall now.

0:01:33.900,0:01:36.720
# 現在  應該差不多  有半個半個我那麼高啦
I think, he's almost half, half as tall as me now.

0:01:43.900,0:01:44.480
# 幹嘛
What's up?

0:01:44.780,0:01:47.680
# 我又不會把你怎麼樣 你看  其它的狗看到我都跑
I won't do any harm on you. Look! Other dogs simply run away whenever I get close.

0:01:48.020,0:01:48.720
# 下次我們
Next time we'll,

0:01:49.260,0:01:51.500
# 把它們全部送人  就不  就不送你啦
we'll give them all out. But you, you'll be staying with us.

0:01:51.580,0:01:52.380
# 你我就不送
I'm not giving you out.

0:01:52.760,0:01:53.620
# 你那麼聽話
You're such a good boy.

0:02:02.700,0:02:03.200
# 小狗
Puppy!

0:02:03.900,0:02:04.660
# 看我一下
Look at me!

0:02:05.840,0:02:06.820
# 瞄我一眼哦
Just throw me a glance!

0:02:08.280,0:02:09.240
# 一直看著那邊
He's staring at that side..

0:02:10.060,0:02:11.060
# 它就是敢看我
But he dares not look at me.

0:02:15.700,0:02:17.640
# 哎呀 它一身  一身這個毛
Aya! His fur, his fur is all over the body.

0:02:23.080,0:02:23.860
# 它不動的
He's not moving at all.

0:02:28.960,0:02:30.000
# 很乖的這個狗
He's a very good boy.

0:02:30.420,0:02:32.320
# 其它狗不乖哦  就你最乖
The other puppies are all naughty. You're the only good boy.

0:02:33.840,0:02:34.340
# 小狗
Puppy!

0:02:35.000,0:02:35.840
# 是不是就你最乖  (註︰"The best boy"之類的說法太奇怪，所以一直避用)
Are you the only good boy?

0:02:37.660,0:02:38.540
# 到這裡好不好玩
Do you like staying here?

0:02:39.100,0:02:39.740
# 看一下牙齒
Let me see your teeth.

0:02:43.300,0:02:44.720
# 不刷牙牙齒都那麼白
How can your teeth be that white? You never brush your teeth.

0:02:46.280,0:02:47.740
# 不刷牙的牙齒這麼白
How can you keep the teeth so white without brushing them?
