### ISSUE TITLE
[华农兄弟] 华农兄弟水池里跳出一条鱼来估计不想活了把它油炸很香哦 - https://youtu.be/5d2vmVqFkM4

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#904]
https://youtu.be/5d2vmVqFkM4
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 9, 2020 at 01:57PM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/5d2vmVqFkM4

#华农兄弟：水池里跳出一条鱼来，估计不想活了，把它油炸，很香哦
#Huanong Brothers: A fish jumped out of the pond. I bet it's tired of living. I fry it. It smells so good!

0:00:00.000,0:00:01.360
# 這個魚好像跳出來啦
It seems that the fish has jumped out.

0:00:02.860,0:00:03.620
# 擋在這裡
It gets stuck here.

0:00:04.440,0:00:05.340
# 它還活的
It's still living.

0:00:06.880,0:00:07.900
# 把它給煮啦
Let me cook it.

0:00:17.220,0:00:17.720
# 你看
Look!

0:00:18.320,0:00:19.640
# 這個魚還活的哦
The fish is still living, isn't it?

0:00:20.040,0:00:21.380
# 一晚上啊 在那裡
It has been staying there for the whole night,

0:00:22.180,0:00:22.840
# 還沒跑
and didn't run away.

0:00:24.260,0:00:25.160
# 它又不跑
It just didn't run away.

0:00:25.960,0:00:26.880
# 它有吃的
It got food there.

0:00:26.940,0:00:28.420
# 這個甚麼  吃的草
What is it?  It has eaten grass.

0:00:40.700,0:00:42.260
# 把這個打一下花
Let me slice it a few times.

0:00:42.960,0:00:44.640
# 這樣就  更入味
Then the flavour, can be better absorbed.

0:00:56.640,0:00:57.280
# 搞定
Done!

0:00:58.880,0:00:59.800
# 搞點生薑
Some ginger,

0:01:00.100,0:01:01.200
# 搞點生薑給它
let me give it some ginger.

0:01:01.940,0:01:02.780
# 這個生薑
This is ginger.

0:01:14.800,0:01:15.760
# 加點料酒
Put some cooking wine.

0:01:18.200,0:01:19.040
# 加點鹽
Put some salt.

0:01:20.700,0:01:21.900
# 鹽要搞多一點
I need a bit more salt.

0:01:23.220,0:01:24.060
# 搞點它這裡
Put the salt here on the fish.

0:01:30.760,0:01:31.840
# 搞點醬油
Put some soy sauce.

0:01:36.480,0:01:37.440
# 它還活的
It's still living.

0:01:39.580,0:01:40.480
# 再加點油
And some oil too.

0:01:44.800,0:01:46.060
# 再給它摸一摸
Then, give it a massage.

0:01:49.660,0:01:52.820
# 好啦  腌個半個小時  我們再來處理它
Alright! Marinate it for half an hour, then we can go to the next step.

0:01:54.380,0:01:56.360
# 鍋燒熱  再把油放下去
Let's heat the wok and then pour the oil.

0:02:27.220,0:02:28.400
# 這個薑也放下去
Let's put in the ginger as well.

0:02:35.760,0:02:36.600
# 還要煎
It needs to be fried for a bit longer.

0:02:45.200,0:02:47.240
# 你看  這個肉全裂開啦
Look! The meat has already cracked open.

0:02:49.100,0:02:50.200
# 丟點辣椒一下
I throw in some chilli.

0:02:51.920,0:02:53.280
# 沒辣椒不好吃
It won't taste good without chilli.

0:03:00.800,0:03:01.860
# 可以啦  起鍋
Alright! It's done!

0:03:04.340,0:03:06.020
# 它這個薑  辣椒不要
The ginger and the chilli are no longer needed,

0:03:07.000,0:03:07.780
# 全部都不要
neither of them.

0:03:08.640,0:03:09.620
# 就要這個魚
I want only the fish.

0:03:16.620,0:03:17.460
# 這個魚
The fish...

0:03:18.700,0:03:19.660
# 好殘忍 你看
So cruel, look!

0:03:19.700,0:03:21.440
# 剛剛還活潑  活潑亂跳的
It was still jumping, jumping around energetically a few moments ago.

0:03:21.940,0:03:23.620
# 現在就變成這樣子的
But now, everything has been changed.

0:03:25.380,0:03:25.940
# 沒事
No worries.

0:03:27.920,0:03:29.160
# 反正煮的很好吃
Cuz it must be very tasty.

0:03:36.740,0:03:37.580
# 很靚吧
Beautiful, isn't it?

0:03:39.680,0:03:40.980
# 哎呀  好香
Aya! It smells so good!

0:03:42.060,0:03:42.560
# 嗯
Um!

0:03:42.900,0:03:43.980
# 很香這個魚
The fish smells really nice!

0:03:47.340,0:03:48.240
# 被火燒啦
It's burnt.

0:03:53.120,0:03:54.040
# 加點青菜
Put some veggies.

0:03:55.840,0:03:57.240
# 給它蓋一下被子
Let me give it a blanket,

0:03:57.300,0:03:58.460
# 蓋一下它的傷口
to cover up its wound.

0:03:59.520,0:04:00.260
# 做好啦
Done!

0:04:02.040,0:04:03.600
# 先嘗一下它的尾巴
I try its tail first.

0:04:05.100,0:04:05.740
# 哎呀
Aya!

0:04:08.380,0:04:09.780
# 嗯  可以喲
Um! It's not bad!

0:04:10.440,0:04:11.180
# 好香啊
It smells so good!

0:04:12.220,0:04:14.140
# 這個魚是小的  很嫩的
This is a small fish. It's so tender.

0:04:16.260,0:04:16.800
# 嗯
Um!

0:04:17.320,0:04:18.320
# 真的很好吃哦
It's really tasty!

0:04:19.940,0:04:21.720
# 好像我比較喜歡吃香的 (註︰這個「香」，應該是指「香口」，英語裡似乎沒有一個很合用的字)
It seems that I prefer deep fried food.

0:04:22.440,0:04:24.200
# 這個  有點上火  (註︰為免外國人不清楚「上火」這概念，這裡情境應該可以避一下)
It's ah, not really that healthy,

0:04:24.680,0:04:25.620
# 有一點辣
and a bit spicy too.

0:04:32.460,0:04:34.060
# 微辣  不是很辣
It's not too spicy, just a bit.

0:04:37.820,0:04:39.540
# 嗯  吃點魚翅
Um! Let me get a fin.

0:04:44.640,0:04:46.140
# 魚翅都可以直接咬碎
The fins are also crispy.

0:04:55.740,0:04:56.960
# 還很不的
It's really not bad.

0:04:57.100,0:04:58.300
# 這個魚我都養了錯
I've been keeping the fish for,

0:04:58.960,0:05:00.880
# 養了差不多半年啦  才養那麼大
for half a year, before it gets to this size.

0:05:02.220,0:05:03.980
# 不好容易把它養大 它又跳出來
I put so much effort in raising it. But it jumped out.

0:05:05.560,0:05:06.480
# 這不能怪我哦
It's not my fault.

0:05:14.660,0:05:16.660
# 好啦 今天的視頻就到這裡啦
Alright! The video ends here.

0:05:18.040,0:05:18.980
# 留著晚上來
It will be a dish,

0:05:19.340,0:05:19.980
# 下飯
of my dinner.
