### ISSUE TITLE
【美食作家王刚】香辣豆豉 - https://youtu.be/FpgawC2FKp4

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#940]
**视频链接**：https://youtu.be/FpgawC2FKp4

视频时长5:04，预计发布时间为北京时间4月23日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“香辣豆豉”的做法，在家复制“老干妈”，味道一级棒，极力推荐！

简介
同学们好，今天和大家分享万能”香辣豆豉酱“的做法，豆豉是传统豆制发酵调味品，本身就味道醇厚香醇，但由于原始豆豉过咸并且会有酱生味，所以如果想发挥出其最棒的香味一定需要经过蒸制过油等步骤，独步天下的“老干妈 风味豆豉 油制辣椒”就是这么制作的。当然老干妈肯定还有其特殊秘密的配方，但根据我教给大家方法已经可以有其精髓，并且还可以根据自己的口味来调整风味，比如加入油酥花生，熟芝麻，牛肉粒等等，大家有机会一定要尝试，无论是拌面下饭拌菜都不会失望的！

本期菜品:【香辣豆豉】
【主料】
豆豉（400克）
【辅料】
生姜（80克）
大蒜（50克）
大葱（1小把）
蒜苗（1小把）
八角（几颗）
香叶（几片）
小茴香（约25克）
青花椒（约15克）
白酒（适量）
灯笼椒（适量）
子弹头辣椒（适量）
干小米辣（适量）
植物油（适量）
菜籽油（1200克）
【调味料】
蚝油（100克）
鸡精（约10克）
白糖（少许）

字幕
0:00:00.320,0:00:01.380
哈喽大家好我是王刚

0:00:01.380,0:00:02.820
本期视频我给大家分享

0:00:03.040,0:00:04.240
香辣豆豉的做法

0:00:04.480,0:00:06.400
首先我们准备豆豉400克

0:00:06.550,0:00:08.525
分出200克将其捏散备用

0:00:08.650,0:00:11.275
这一步的目的是让豆豉碎整各占一半

0:00:14.250,0:00:16.775
捏碎之后将所有豆豉搅拌均匀备用

0:00:21.425,0:00:22.950
下一步开始准备辅料

0:00:23.150,0:00:25.375
准备生姜80克切成姜末备用

0:00:34.300,0:00:36.425
准备大蒜50克切成蒜末备用

0:00:39.925,0:00:42.350
准备大葱1小把斜刀切成小段备用

0:00:44.625,0:00:46.750
准备蒜苗1小把切成小段备用

0:00:49.325,0:00:50.750
下一步开始准备香料

0:00:50.950,0:00:52.400
碗中加入八角几颗

0:00:52.625,0:00:53.800
加入香叶几片

0:00:54.275,0:00:55.775
加入1小把小茴香（约25克）

0:00:56.075,0:00:57.400
加入适量的青花椒（约15克）

0:00:57.575,0:00:59.550
不能吃麻味的同学可以不加

0:00:59.975,0:01:02.500
碗中加入适量的白酒搅拌均匀浸泡备用

0:01:02.500,0:01:04.500
这一步的目的是让香料出味

0:01:11.302,0:01:13.327
准备适量的灯笼椒放入碗中备用（主要作用增香）

0:01:13.875,0:01:15.350
加入适量的子弹头备用（主要作用增色）

0:01:15.775,0:01:17.775
最后加入适量的干小米辣备用（主要作用增辣）

0:01:18.025,0:01:20.925
同学们所有的干辣椒可以按照自己的口味来添加

0:01:21.500,0:01:22.975
下一步开始准备调味料

0:01:23.050,0:01:24.775
碗中加入蚝油100克

0:01:25.675,0:01:27.075
加入适量的鸡精（约10克）

0:01:28.050,0:01:29.575
加入少许白糖提鲜

0:01:29.675,0:01:31.125
下一步开始处理辣椒

0:01:31.250,0:01:32.650
首先我们把锅烧热

0:01:33.250,0:01:35.000
锅烧热之后加入适量的底油

0:01:36.625,0:01:40.200
油温4成热之后将准备好的干辣椒下锅炒香炒至棕色

0:01:45.700,0:01:47.575
辣椒炒香之后倒出备用

0:01:47.875,0:01:49.825
下一步锅中加入适量的清水

0:01:51.150,0:01:53.675
然后放入蒸笼将豆豉下锅蒸20分钟

0:01:54.025,0:01:56.725
这一步的目的是激发豆豉最原始的香味

0:02:02.000,0:02:05.150
最后趁这个时间将炒香的辣椒放入石臼中捣碎备用

0:02:05.775,0:02:08.175
嫌麻烦的同学也可以用料理机打碎

0:02:21.175,0:02:23.325
20分钟之后取出蒸好的豆豉

0:02:25.800,0:02:27.225
下一步开始炒制

0:02:29.325,0:02:31.875
锅烧热之后加入纯菜籽油1200克

0:02:37.200,0:02:40.400
油温烧至5成热之后将切好的大葱和蒜苗下锅

0:02:47.675,0:02:50.425
再加入准备好的香料带着白酒一起下锅

0:02:51.275,0:02:53.750
然后转中小火把辅料和香料炸香（香料：八角，小茴香，香叶）

0:03:01.200,0:03:03.850
辅料香料炒至干香之后捞出丢弃不用

0:03:06.775,0:03:09.000
然后我们再次把油温升至6成热

0:03:12.250,0:03:14.875
油温6成热之后加入剁碎的姜蒜末下锅

0:03:15.125,0:03:17.300
同学们这一步把姜蒜末炸香即可

0:03:22.525,0:03:25.050
料头炸香之后加入蒸好的豆豉下锅

0:03:30.600,0:03:32.875
豆豉下锅之后转小火炒10分钟

0:03:33.150,0:03:35.725
这一步的目的是把豆豉的水份炒至略干

0:03:44.575,0:03:46.975
10分钟之后加入捣碎的干辣椒面

0:03:50.000,0:03:52.225
然后继续开小火炒15分钟

0:03:58.150,0:04:01.400
这一步必须小火慢炒防止辣椒面炒糊

0:04:04.025,0:04:05.500
15分钟之后关火

0:04:05.725,0:04:08.375
再加入配好的蚝油和鸡精搅拌均匀

0:04:13.700,0:04:15.750
拌匀之后倒出冷却即可食用

0:04:30.325,0:04:32.625
一份自制香辣豆豉酱就制作完成

0:04:41.340,0:05:03.640
下面开始技术总结
第一，干辣椒最好选用灯笼椒子弹头和小米辣，比例根据个人口味微调
第二，豆豉下锅之前必须事先蒸20分钟，这样才能发挥出最大潜力
第三，成品之后最好静止12小时再食用才更加入味
第四，此酱可以作为万能佐料（下饭，下面条，拌菜，开胃辣椒酱）
豆豉香辣将的技术总结完成


```

**Comment by Hackerry** [comment]
认领

**Comment by Hackerry** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“香辣豆豉”的做法，在家复制“老干妈”，味道一级棒，极力推荐！
Chef Wang teaches you: "Spicy Douchi Sauce". Home-version "Lao Gan Ma". Highly recommended!

简介
同学们好，今天和大家分享万能”香辣豆豉酱“的做法，豆豉是传统豆制发酵调味品，本身就味道醇厚香醇，但由于原始豆豉过咸并且会有酱生味，所以如果想发挥出其最棒的香味一定需要经过蒸制过油等步骤，独步天下的“老干妈 风味豆豉 油制辣椒”就是这么制作的。当然老干妈肯定还有其特殊秘密的配方，但根据我教给大家方法已经可以有其精髓，并且还可以根据自己的口味来调整风味，比如加入油酥花生，熟芝麻，牛肉粒等等，大家有机会一定要尝试，无论是拌面下饭拌菜都不会失望的！
Hi, everyone! Today I want to share with you the goes with everything "Spicy Douchi Sauce". Douchi is a traditional seasoning made with fermented beans. Although it has the original aromatic flavor, the beans are too salty and have a strong soy sauce smell. So to get the best flavor out of it, we need additional processing like steam and fry. The well-known "Lao Gan Ma" - Special Flavor Douchi and Oil Chilli is also made in this way. Of course, "Lao Gan Ma" has other secret ingredients in it. We can still mimic its flavor through the method I teach you. In addition, we can adjust the flavor by adding fried crispy peanut, fried sesame, minced beef, etc. It goes well with both noodle and rice. You should definitely try it out!

本期菜品:【香辣豆豉】
【主料】
豆豉（400克）
【辅料】
生姜（80克）
大蒜（50克）
大葱（1小把）
蒜苗（1小把）
八角（几颗）
香叶（几片）
小茴香（约25克）
青花椒（约15克）
白酒（适量）
灯笼椒（适量）
子弹头辣椒（适量）
干小米辣（适量）
植物油（适量）
菜籽油（1200克）
【调味料】
蚝油（100克）
鸡精（约10克）
白糖（少许）
Today's Dish: Spicy Douchi Sauce
Main Ingredients
Douchi (400g)

Supplementary Ingredients
Ginger (80g)
Garlic (50g)
Spring onions (a small handful)
Garlic sprouts (a small handful)
Star anise (several)
Bay leaves (several)
Fennel seeds (~25g)
Sichuan green peppercorns (~15g)
Baijiu (some)
Red bell peppers (some)
"Zidantou" chili peppers (some)
Dried "Xiaomila" chili peppers (some)
Vegetable oil (some)
Mustard oil (1200g)

Seasoning Ingredients
Oyster sauce (100g)
Chicken bouillon (~10g)
White sugar (some)


字幕
0:00:00.320,0:00:01.380
哈喽大家好我是王刚
Hello, everyone. This is Wang Gang.

0:00:01.380,0:00:02.820
本期视频我给大家分享
In today's video I want to share with you

0:00:03.040,0:00:04.240
香辣豆豉的做法
how to make Spicy Douchi Sauce

0:00:04.480,0:00:06.400
首先我们准备豆豉400克
First we get Douchi 400g

0:00:06.550,0:00:08.525
分出200克将其捏散备用
Take out 200g and crush them

0:00:08.650,0:00:11.275
这一步的目的是让豆豉碎整各占一半
This step is to make half of the Douchi complete and half mashed

0:00:14.250,0:00:16.775
捏碎之后将所有豆豉搅拌均匀备用
Then mix the two halves well

0:00:21.425,0:00:22.950
下一步开始准备辅料
Next we prepare the supplementary ingredients

0:00:23.150,0:00:25.375
准备生姜80克切成姜末备用
Mince 80g ginger

0:00:34.300,0:00:36.425
准备大蒜50克切成蒜末备用
Mince 50g garlic

0:00:39.925,0:00:42.350
准备大葱1小把斜刀切成小段备用
Slant-cut a small handful of spring onions

0:00:44.625,0:00:46.750
准备蒜苗1小把切成小段备用
Chop a small handful of garlic sprouts

0:00:49.325,0:00:50.750
下一步开始准备香料
Next we prepare the spices

0:00:50.950,0:00:52.400
碗中加入八角几颗
Add several star anise into a bowl

0:00:52.625,0:00:53.800
加入香叶几片
with some bay leaves

0:00:54.275,0:00:55.775
加入1小把小茴香（约25克）
a small handful of fennel seed (about 25g)

0:00:56.075,0:00:57.400
加入适量的青花椒（约15克）
and some Sichuan green peppercorn (about 15g)

0:00:57.575,0:00:59.550
不能吃麻味的同学可以不加
You can leave out the peppercorn if you can't endure the numbing flavor

0:00:59.975,0:01:02.500
碗中加入适量的白酒搅拌均匀浸泡备用
Add some Baijiu and stir well. Let it soak for a while.

0:01:02.500,0:01:04.500
这一步的目的是让香料出味
This step is to bring out the flavor of the spices.

0:01:11.302,0:01:13.327
准备适量的灯笼椒放入碗中备用（主要作用增香）
Have some red bell peppers ready in a bowl (for the flavor)

0:01:13.875,0:01:15.350
加入适量的子弹头备用（主要作用增色）
Add some "Zidantou" chili pepper (for the color)

0:01:15.775,0:01:17.775
最后加入适量的干小米辣备用（主要作用增辣）
Finally add some dried "Xiaomila" chili pepper (for the spiciness)

0:01:18.025,0:01:20.925
同学们所有的干辣椒可以按照自己的口味来添加
You can customize your own dried cili peppers combo

0:01:21.500,0:01:22.975
下一步开始准备调味料
Next we prepare the seasoning ingredients

0:01:23.050,0:01:24.775
碗中加入蚝油100克
Add 100g oyster sauce to a bowl

0:01:25.675,0:01:27.075
加入适量的鸡精（约10克）
Add some chicken bouillon (about 10g)

0:01:28.050,0:01:29.575
加入少许白糖提鲜
Add some white sugar for umami flavor

0:01:29.675,0:01:31.125
下一步开始处理辣椒
Next we process the chili peppers

0:01:31.250,0:01:32.650
首先我们把锅烧热
First we heat up the wok

0:01:33.250,0:01:35.000
锅烧热之后加入适量的底油
After heated, add some base oil

0:01:36.625,0:01:40.200
油温4成热之后将准备好的干辣椒下锅炒香炒至棕色
When oil temperature is about 120°C, add the dried peppers. Fry until you smell the aroma and the peppers turn brown

0:01:45.700,0:01:47.575
辣椒炒香之后倒出备用
Set them aside once done

0:01:47.875,0:01:49.825
下一步锅中加入适量的清水
Next we add some water into the wok

0:01:51.150,0:01:53.675
然后放入蒸笼将豆豉下锅蒸20分钟
Then put Douchi on a steamer and steam for 20 minutes

0:01:54.025,0:01:56.725
这一步的目的是激发豆豉最原始的香味
This step is to enhance the original flavor of Douchi

0:02:02.000,0:02:05.150
最后趁这个时间将炒香的辣椒放入石臼中捣碎备用
Finally we use this time to grind the chili peppers in a mortar

0:02:05.775,0:02:08.175
嫌麻烦的同学也可以用料理机打碎
You can also use a blender to save some effort

0:02:21.175,0:02:23.325
20分钟之后取出蒸好的豆豉
20 minutes later, we take Douchi out

0:02:25.800,0:02:27.225
下一步开始炒制
Next we make the sauce

0:02:29.325,0:02:31.875
锅烧热之后加入纯菜籽油1200克
Add 1200g mustard oil after heating up the wok

0:02:37.200,0:02:40.400
油温烧至5成热之后将切好的大葱和蒜苗下锅
Put in spring onions and garlic sprouts once oil temperature reaches 150°C

0:02:47.675,0:02:50.425
再加入准备好的香料带着白酒一起下锅
Then add the spices and Baijiu mixture

0:02:51.275,0:02:53.750
然后转中小火把辅料和香料炸香（香料：八角，小茴香，香叶）
Turn to middle to low heat and fry the spices until you can smell the aroma (spices: star anise, fennel seed, bay leaves)

0:03:01.200,0:03:03.850
辅料香料炒至干香之后捞出丢弃不用
Pick everything out once dry and used

0:03:06.775,0:03:09.000
然后我们再次把油温升至6成热
Then we bring oil temperature to around 180°C

0:03:12.250,0:03:14.875
油温6成热之后加入剁碎的姜蒜末下锅
Add minced garlic and minced ginger

0:03:15.125,0:03:17.300
同学们这一步把姜蒜末炸香即可
We only need to fry slightly and bring the flavor out in this step

0:03:22.525,0:03:25.050
料头炸香之后加入蒸好的豆豉下锅
Add steamed Douchi once the smell comes out

0:03:30.600,0:03:32.875
豆豉下锅之后转小火炒10分钟
Turn to low heat and cook for 10 minutes

0:03:33.150,0:03:35.725
这一步的目的是把豆豉的水份炒至略干
We want to dry our Douchi in this step

0:03:44.575,0:03:46.975
10分钟之后加入捣碎的干辣椒面
10 minutes later add ground chili pepper powder

0:03:50.000,0:03:52.225
然后继续开小火炒15分钟
Then cook at low heat for 15 minutes

0:03:58.150,0:04:01.400
这一步必须小火慢炒防止辣椒面炒糊
You must be using low heat or you may burn the chili powder

0:04:04.025,0:04:05.500
15分钟之后关火
15 minutes later turn off the heat

0:04:05.725,0:04:08.375
再加入配好的蚝油和鸡精搅拌均匀
Add prepared oyster sauce and chicken bouillon and mix well

0:04:13.700,0:04:15.750
拌匀之后倒出冷却即可食用
Then pour it out, let it cool and that's it

0:04:30.325,0:04:32.625
一份自制香辣豆豉酱就制作完成
A self-made Spicy Douchi Sauce is finished

0:04:41.340,0:05:03.640
下面开始技术总结
第一，干辣椒最好选用灯笼椒子弹头和小米辣，比例根据个人口味微调
第二，豆豉下锅之前必须事先蒸20分钟，这样才能发挥出最大潜力
第三，成品之后最好静止12小时再食用才更加入味
第四，此酱可以作为万能佐料（下饭，下面条，拌菜，开胃辣椒酱）
豆豉香辣将的技术总结完成
Now the technical tips:
First, it's better to use red bell peppers and "Xiaomila" chili peppers. The ratio can be slightly adjusted based on your taste.
Second, Douchi must be steamed for 20 minutes beforehand to get the best result.
Third, let it rest for 12 hours after cooking for better flavored sauce.
Fourth, this sauce is "multi-purposed" (it goes well with rice and noodle, and can be used as dressing for dish or consumed as a regular spicy sauce).
That's all the technical tips for Spicy Douchi Sauce.
