### ISSUE TITLE
我们可不可以也做盗月社的英文字幕？

### ISSUE THREAD

**Issue by sai-919** [immoonancient/YTSubtitles#953]
同问，盗月社的外挂字幕是youtube机翻的，我们可不可以也把这个youtuber纳入到字幕组射程里？

**Comment by immoonancient** [comment]
这个可以考虑
之前做过一期觉得对话量太大了就放弃了... 现在可以重新拿起来试试

**Comment by immoonancient** [comment]
提名在这里了 https://github.com/immoonancient/YTSubtitles/issues/1063#issuecomment-629845887
