### ISSUE TITLE
【美食作家王刚】 冬瓜烧排骨 - https://youtu.be/S-uOqElHXbA

### ISSUE THREAD

**Issue by SilvesterDong** [immoonancient/YTSubtitles#959]
**视频链接**：https://youtu.be/S-uOqElHXbA

视频时长4:20，预计发布时间为北京时间4月28日晚
这是刚哥最新的视频私享链接，方便大家提前添加字幕，文字稿在下面
文字稿可能会和视频有微小出入，请大家以视频为主。由于刚哥的合同问题，请大家务必不要泄露或分享刚哥未在YouTube发布的内容，包括文字，视频链接等，望大家理解！

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
厨师长教你：“冬瓜烧排骨”的家常做法，也可以用土豆芋头来做经典烧排骨，排骨香嫩入味脱骨

简介
同学们好，今天和大家分享一道“冬瓜烧排骨”，如果把冬瓜换成土豆或者芋头就是经典的烧排骨，用此法处理和烧出来的排骨香嫩入味，肉可以做到脱骨，并且家常味十足，非常适合喜欢吃炖菜的朋友。

本期菜品【冬瓜烧排骨】
【主料】
精排骨（500克）
【辅料】
冬瓜（500克）
大蒜（几颗）
生姜（1小块）
小米辣（适量）
小苏打（3克）
鸡蛋黄（1个）
干淀粉（约4克）
植物油（适量）
水淀粉（适量）
明油（少许）
【调味料】
食用盐（适量）
胡椒粉（少许）
蚝油（3克）
红油豆瓣酱（约10克）
料酒（适量）
白糖（少许）
鸡精（1克）

字幕
0:00:00.320,0:00:01.460
哈喽大家好我是王刚

0:00:01.460,0:00:03.400
本期视频我跟大家分享一道家常菜

0:00:03.960,0:00:05.160
冬瓜烧排骨

0:00:05.340,0:00:07.500
首先我们准备精排骨500克

0:00:07.550,0:00:09.850
将每一根分开之后剁成小块备用

0:00:10.075,0:00:11.750
同学们最好剁小块一些

0:00:11.750,0:00:13.450
这样更加容易炒熟

0:00:17.250,0:00:18.750
下一步开始处理排骨

0:00:19.375,0:00:21.350
盆中加入1小把食用盐（约10克）

0:00:21.976,0:00:23.260
加入小苏打3克

0:00:23.260,0:00:26.231
加小苏打的目的是破坏排骨中的肌纤维增加嫩度

0:00:26.647,0:00:29.079
然后先加入少量的清水抓洗3分钟

0:00:29.079,0:00:31.271
这样可以去除排骨中残留的血水

0:00:34.725,0:00:36.705
3分钟之后加入清水清洗干净

0:00:39.630,0:00:41.364
然后再捞出挤干水份备用

0:00:43.450,0:00:45.445
同学们这一步必须多清洗几遍

0:00:50.994,0:00:52.393
下一步开始腌制排骨

0:00:53.950,0:00:55.560
盆中加入少许食用盐（约0.5克）

0:00:55.800,0:00:57.023
加入少许胡椒粉

0:00:57.450,0:00:58.675
加入蚝油3克

0:00:59.925,0:01:01.800
加入蛋黄1个之后搅拌均匀（鸡蛋黄）

0:01:06.650,0:01:08.604
再加入适量的干淀粉收紧水份（约4克）

0:01:12.802,0:01:14.675
最后加入少许的植物油拌匀

0:01:14.675,0:01:16.976
加植物油可以防止排骨下锅粘连

0:01:18.000,0:01:19.492
下一步开始处理冬瓜

0:01:20.150,0:01:22.705
准备冬瓜500克去皮之后切成小块备用

0:01:22.850,0:01:25.833
不喜欢冬瓜的同学可以用土豆或者芋头代替

0:01:30.763,0:01:32.550
下一步开始准备料头

0:01:32.550,0:01:34.342
准备大蒜几颗切成小粒备用（约20克）

0:01:37.325,0:01:39.151
准备生姜1小块切成姜粒备用

0:01:41.200,0:01:43.199
最后准备适量的小米辣切碎备用

0:01:43.199,0:01:44.817
不能吃辣的同学可以不加

0:01:45.100,0:01:46.245
下一步开始制作

0:01:46.850,0:01:48.803
首先我们在锅中加入适量的清水

0:01:50.500,0:01:51.853
加入1小勺食用盐

0:01:52.312,0:01:54.659
然后将切好的冬瓜下锅焯水1分钟

0:01:54.659,0:01:56.682
这一步的目的是去除冬瓜的生味

0:01:56.682,0:01:58.763
中途再加入少许的植物油保色

0:02:01.275,0:02:03.159
焯水1分钟之后倒出备用

0:02:04.000,0:02:05.445
下一步开始爆排骨

0:02:07.400,0:02:09.481
锅烧热之后加入适量的油滑锅

0:02:10.900,0:02:13.132
然后将热油倒出再加入适量的底油

0:02:16.550,0:02:19.105
油温5成热之后将腌制好的排骨下锅

0:02:21.959,0:02:24.075
排骨下锅之后先不翻动煎30秒

0:02:24.075,0:02:25.786
这一步的目的是防止脱浆

0:02:26.825,0:02:28.733
煎30秒钟之后再翻动均匀

0:02:31.150,0:02:33.913
煎至排骨略微金黄之后倒出多余的植物油

0:02:35.925,0:02:38.110
油倒完之后再将排骨重新下锅

0:02:38.625,0:02:40.972
加入切好的姜蒜辣椒粒开中火爆香

0:02:45.467,0:02:47.825
料头爆香之后加入适量的红油豆瓣酱（约10克）

0:02:47.825,0:02:50.114
然后转小火将豆瓣酱炒香炒出红油

0:02:53.975,0:02:55.779
再加入适量的料酒从锅边淋入

0:02:59.475,0:03:01.799
翻炒几下之后将焯好水的冬瓜下锅

0:03:03.650,0:03:05.719
再加入适量的清水开大火烧开

0:03:08.975,0:03:11.322
大火烧开之后转小火烧25分钟

0:03:15.575,0:03:17.621
排骨烧至20分钟之后开始调味

0:03:19.000,0:03:20.353
锅中加入食用盐1克

0:03:21.150,0:03:22.237
加入少许胡椒粉

0:03:22.825,0:03:24.293
加入少许白糖提鲜

0:03:25.050,0:03:26.218
加入鸡精1克

0:03:27.150,0:03:29.034
调好味之后继续烧5分钟

0:03:34.596,0:03:37.971
5分钟之后将锅离火加入适量的水淀粉勾芡

0:03:39.717,0:03:41.821
水淀粉下锅之后再开中火烧开

0:03:45.063,0:03:47.548
最后再加入少许明油即可出锅装盘

0:03:55.620,0:03:58.420
一道口感软嫩入味的冬瓜烧排骨就制作完成

0:04:04.040,0:04:19.560
下面开始技术总结
第一，最好选择嫩排骨，否则老排骨需要增加烧制的时间
第二，冬瓜不能烧太久否则很容易化成水
第三，不能吃辣的同学可以不加豆瓣酱和辣椒用蚝油香菇代替
烧排骨的技术总结完毕

```

**Comment by lh-du** [comment]
认领

**Comment by lh-du** [comment]
标题（翻译主要意思即可，不要超过 100 个字符）
Title
厨师长教你：“冬瓜烧排骨”的家常做法，也可以用土豆芋头来做经典烧排骨，排骨香嫩入味脱骨
Chef Wang teaches you: "Braised Pork Ribs w. White Gourd", homestyle dish also good for Potato/Taro

简介
Introduction
同学们好，今天和大家分享一道“冬瓜烧排骨”，如果把冬瓜换成土豆或者芋头就是经典的烧排骨，用此法处理和烧出来的排骨香嫩入味，肉可以做到脱骨，并且家常味十足，非常适合喜欢吃炖菜的朋友。
Hi everyone, today I will share the recipe of Braised Pork Ribs with White Gourd. White gourd can be swapped with potato or taro. Ribs come out of this recipe are tender and flavorful, meat can be easily deboned, and the dish is full of homestyle. Very suitable for stew lovers.

本期菜品【冬瓜烧排骨】
Today's dish: Braised Pork Ribs with White Gourd
【主料】
Main ingredients
精排骨（500克）
Lean pork ribs (500g)
【辅料】
Supplementary ingredients
冬瓜（500克）  
White Gourd (500g)
大蒜（几颗）
Garlic (a few cloves)
生姜（1小块）
Ginger (1 piece)
小米辣（适量）
"Xiaomila" chili pepper (a reasonable amount)
小苏打（3克）
Baking soda (3g)
鸡蛋黄（1个）
Egg yolk (1 piece)
干淀粉（约4克）
Dry starch (4g)
植物油（适量）
Vegetable oil (a reasonable amount)
水淀粉（适量）
Slurry (a reasonable amount)
明油（少许）
Ming You (literally "oil for a shiny presence") (a little)

【调味料】
Seasoning
食用盐（适量）
Salt (a reasonable amount)
胡椒粉（少许）
Ground pepper (a little)
蚝油（3克）
Oyster sauce (3g)
红油豆瓣酱（约10克）
Chili oil doubanjiang (10g)
料酒（适量）
Chinese cooking wine (a reasonable amount)
白糖（少许）
Sugar (a few)
鸡精（1克）
Chicken bouillon (1g)

字幕
Subtitle
0:00:00.320,0:00:01.460
哈喽大家好我是王刚
Hi everyone, I am Wang Gang

0:00:01.460,0:00:03.400
本期视频我跟大家分享一道家常菜
Today I will share the recipe of a homestyle dish

0:00:03.960,0:00:05.160
冬瓜烧排骨
Braised Pork Ribs with White Gourd

0:00:05.340,0:00:07.500
首先我们准备精排骨500克
First, prepare 500 gram of lean pork ribs

0:00:07.550,0:00:09.850
将每一根分开之后剁成小块备用
Separate and chop into small pieces

0:00:10.075,0:00:11.750
同学们最好剁小块一些
You can chop it into smaller pieces …

0:00:11.750,0:00:13.450
这样更加容易炒熟
… which are easier to cook

0:00:17.250,0:00:18.750
下一步开始处理排骨
Next, prepare the ribs

0:00:19.375,0:00:21.350
盆中加入1小把食用盐（约10克）
In a pot, add 10 gram of salt

0:00:21.976,0:00:23.260
加入小苏打3克
Add 3 gram of baking soda

0:00:23.260,0:00:26.231
加小苏打的目的是破坏排骨中的肌纤维增加嫩度
Baking soda adds tenderness by breaking up muscle fibers

0:00:26.647,0:00:29.079
然后先加入少量的清水抓洗3分钟
Rinse with water for 3 minutes …

0:00:29.079,0:00:31.271
这样可以去除排骨中残留的血水
… to remove blood remaining in the ribs

0:00:34.725,0:00:36.705
3分钟之后加入清水清洗干净
3 minters later, add more water to rinse

0:00:39.630,0:00:41.364
然后再捞出挤干水份备用
Drain and squeeze to remove water

0:00:43.450,0:00:45.445
同学们这一步必须多清洗几遍
The cleaning step must be repeated for several times

0:00:50.994,0:00:52.393
下一步开始腌制排骨
Next is to marinate the ribs

0:00:53.950,0:00:55.560
盆中加入少许食用盐（约0.5克）
In a pot, add 0.5 gram of salt

0:00:55.800,0:00:57.023
加入少许胡椒粉
Add a few ground pepper

0:00:57.450,0:00:58.675
加入蚝油3克
Add 3 gram of oyster sauce

0:00:59.925,0:01:01.800
加入蛋黄1个之后搅拌均匀（鸡蛋黄）
Add 1 yolk and stir (chicken egg yolk)

0:01:06.650,0:01:08.604
再加入适量的干淀粉收紧水份（约4克）
And add a reasonable amount (about 4g) of dry starch to absorb water

0:01:12.802,0:01:14.675
最后加入少许的植物油拌匀
Finally add a little vegetable oil and stir well

0:01:14.675,0:01:16.976
加植物油可以防止排骨下锅粘连
Vegetable oil avoids the ribs from sticking to wok

0:01:18.000,0:01:19.492
下一步开始处理冬瓜
Next, we prepare white gourd

0:01:20.150,0:01:22.705
准备冬瓜500克去皮之后切成小块备用
Peel 500 gram of white gourd and cut into pieces

0:01:22.850,0:01:25.833
不喜欢冬瓜的同学可以用土豆或者芋头代替
If you do not like white gourd, you can replace it with potato or taro

0:01:30.763,0:01:32.550
下一步开始准备料头
Next, prepare aromatics

0:01:32.550,0:01:34.342
准备大蒜几颗切成小粒备用（约20克）
Cut 20 gram of garlic into pieces

0:01:37.325,0:01:39.151
准备生姜1小块切成姜粒备用
Cut up one piece of ginger

0:01:41.200,0:01:43.199
最后准备适量的小米辣切碎备用
Finally, cut up some "Xiaomila" chili pepper

0:01:43.199,0:01:44.817
不能吃辣的同学可以不加
Skip the pepper if you do not like

0:01:45.100,0:01:46.245
下一步开始制作
Next start cooking

0:01:46.850,0:01:48.803
首先我们在锅中加入适量的清水
First, we add a reasonable amount of water into the wok

0:01:50.500,0:01:51.853
加入1小勺食用盐
Add 1 tbsp of salt

0:01:52.312,0:01:54.659
然后将切好的冬瓜下锅焯水1分钟
Add the white gourd and blanch for 1 minute

0:01:54.659,0:01:56.682
这一步的目的是去除冬瓜的生味
This helps remove raw odor from the white gourd

0:01:56.682,0:01:58.763
中途再加入少许的植物油保色
Add a little vegetable oil midway to preserve color

0:02:01.275,0:02:03.159
焯水1分钟之后倒出备用
Blanch for 1 minute

0:02:04.000,0:02:05.445
下一步开始爆排骨
Next, we fry the ribs

0:02:07.400,0:02:09.481
锅烧热之后加入适量的油滑锅
Heat up the wok then add some oil to grease the wok

0:02:10.900,0:02:13.132
然后将热油倒出再加入适量的底油
After pouring out the heated oil, we add some base oil

0:02:16.550,0:02:19.105
油温5成热之后将腌制好的排骨下锅
Add the marinated ribs as oil temperature reach 150°C/302°F

0:02:21.959,0:02:24.075
排骨下锅之后先不翻动煎30秒
After adding the ribs, fry for 30 seconds without stirring …

0:02:24.075,0:02:25.786
这一步的目的是防止脱浆
… to avoid losing slurry on the ribs

0:02:26.825,0:02:28.733
煎30秒钟之后再翻动均匀
After frying 30 seconds, stir well

0:02:31.150,0:02:33.913
煎至排骨略微金黄之后倒出多余的植物油
Stir till ribs are slightly golden brown, then drain excessive vegetable oil

0:02:35.925,0:02:38.110
油倒完之后再将排骨重新下锅
After draining the oil, replace the ribs into the wok

0:02:38.625,0:02:40.972
加入切好的姜蒜辣椒粒开中火爆香
Add aromatics (diced ginger, garlic, and pepper) and fry with medium heat

0:02:45.467,0:02:47.825
料头爆香之后加入适量的红油豆瓣酱（约10克）
After frying the aromatics, add 10 gram of chili oil doubanjiang

0:02:47.825,0:02:50.114
然后转小火将豆瓣酱炒香炒出红油
Switch to low heat and fry till you see red oil

0:02:53.975,0:02:55.779
再加入适量的料酒从锅边淋入
Add Chinese cooking wine from the side of the wok

0:02:59.475,0:03:01.799
翻炒几下之后将焯好水的冬瓜下锅
Stir-fry several times and add blanched white gourd

0:03:03.650,0:03:05.719
再加入适量的清水开大火烧开
Add some water and boil with high heat

0:03:08.975,0:03:11.322
大火烧开之后转小火烧25分钟
Upon boiling, switch to low heat for 25 minutes

0:03:15.575,0:03:17.621
排骨烧至20分钟之后开始调味
Begin seasoning 20 minutes into the low heat

0:03:19.000,0:03:20.353
锅中加入食用盐1克
In the wok, add 1 gram of salt

0:03:21.150,0:03:22.237
加入少许胡椒粉
Add a little ground pepper

0:03:22.825,0:03:24.293
加入少许白糖提鲜
Add a little sugar to enhance umami

0:03:25.050,0:03:26.218
加入鸡精1克
Add 1 gram of chicken bouillon

0:03:27.150,0:03:29.034
调好味之后继续烧5分钟
Continue to cook for 5 minutes after seasoning

0:03:34.596,0:03:37.971
5分钟之后将锅离火加入适量的水淀粉勾芡
After 5 minutes, add some slurry 

0:03:39.717,0:03:41.821
水淀粉下锅之后再开中火烧开
After adding slurry, cook with medium heat till boiling

0:03:45.063,0:03:47.548
最后再加入少许明油即可出锅装盘
Last, add a little Ming You (literally "oil for a shiny presence") and plate

0:03:55.620,0:03:58.420
一道口感软嫩入味的冬瓜烧排骨就制作完成
A dish of tender and flavorful Braised Pork Ribs with White Gourd is ready to serve

0:04:04.040,0:04:19.560
下面开始技术总结
Now, technical summary
第一，最好选择嫩排骨，否则老排骨需要增加烧制的时间
First, tender ribs are preferred over rigid ones. Rigid ribs demand longer cooking time
第二，冬瓜不能烧太久否则很容易化成水
Second, white gourd cannot be cooked for too long or it will turn into water
第三，不能吃辣的同学可以不加豆瓣酱和辣椒用蚝油香菇代替
Third, if you cannot eat spicy food, doubanjiang and pepper can be replaced with oyster sauce and shiitake mushroom
烧排骨的技术总结完毕
That is all for the technical summary
