### ISSUE TITLE
[华农兄弟] 华农兄弟金银花又开了摘点来泡茶很香哦 - https://youtu.be/OSSM5CPiie0

### ISSUE THREAD

**Issue by immoonancient** [immoonancient/YTSubtitles#964]
https://youtu.be/OSSM5CPiie0
<p>&#35270;&#39057;&#21457;&#24067;&#20110; April 25, 2020 at 11:36AM</p>
<p><small><i>&#30001; <a href="https://ifttt.com/applets/104837875d">IFTTT</a> &#33258;&#21160;&#21457;&#24067;</i></small></p>

**Comment by vincenthychow** [comment]
bot, please upload
#https://youtu.be/OSSM5CPiie0

#华农兄弟：金银花又开了，摘点来泡茶，很香哦
#Huanong Brothers: The honeysuckles blossom again. We pick them to make some tea. It smells so good!

0:00:00.000,0:00:02.000
# 大家好  今天天氣比較好哦
Hi everyone! The weather is much better today.

0:00:02.000,0:00:03.520
# 我搞點金銀花回去吃哦
I'm gonna get some honeysuckles back home.

0:00:04.360,0:00:05.140
# 就這  你看
Over there, look!

0:00:05.420,0:00:06.060
# 一大片
They're everywhere.

0:00:06.960,0:00:07.920
# 我把它割下來
I'm gonna cut them off,

0:00:08.600,0:00:09.400
# 通通割下來
cut them all off.

0:00:16.820,0:00:18.280
# 哇  好茂盛啊
Wa! It's so bushy here.

0:00:19.160,0:00:21.020
# 把這個整片把它割下來
I cut off the whole bunch of it.

0:00:21.580,0:00:23.860
# 這個割完之後還會長出來哦  這個藤子
It keeps on growing after cutting them off, I mean the stem.

0:00:24.880,0:00:25.700
# 長得很快的
It grows really fast.

0:00:25.940,0:00:27.420
# 割一下明年長的更多
Cutting it helps it grow even more next year.

0:00:37.880,0:00:39.220
# 哇  好香啊
Wa! It smells so nice!

0:00:40.180,0:00:41.700
# 一種那種淡淡的香味
It's sort of like a subtle fragrance.

0:00:44.120,0:00:45.740
# 問[SIC]一下這個味道  (註︰"Smell"這個字不合這裡的意境，故避用)
It's a fragrance, which,

0:00:47.440,0:00:48.580
# 真的很舒服的
makes you feel really great.

0:01:10.640,0:01:12.060
# 我們去另外一個地方搞
Let's move to another place.

0:01:12.800,0:01:14.200
# 這個太少啦  就一點點
It's too few here, just a tiny little bit.

0:01:22.320,0:01:23.760
# 你看  這裡好多啊  這裡
Look! Here are a lot, here.

0:01:24.780,0:01:25.800
# 一片一片的
They're in bunches.

0:01:29.900,0:01:33.280
# 早知道我拿兩個籮筐來  一個籮筐裝了多少
I should have come with two buckets. I can't take too much with just one.

0:01:42.100,0:01:42.600
# 這個
Here are,

0:01:43.380,0:01:44.000
# 那個多
so many.

0:01:50.240,0:01:52.300
# 快點走  不怕  我牽你去
C'mon, let's go! I'm holding you hand, so don't be afraid.

0:01:52.580,0:01:53.620
# 快點  我牽你去
C'mon! I'm holding your hand.

0:01:54.300,0:01:57.720
# 就在那邊  看到沒有那麼漂亮的牛你都不敢去
They're right over there! Can you see them? Why don't you dare to go? The cattle are so pretty.

0:01:57.860,0:02:00.020
# 大家刘星辰都坐在牛背上騎牛  (註︰「人家」這譯不到，唯有用另一種說法突出他想表達刘星辰膽子大)
You know what? Liu Xingchen even dares to ride on a cow!

0:02:00.540,0:02:01.560
# 真的 不騙你
No kidding. I'm serious.

0:02:03.320,0:02:04.460
# 你要你自己去
No, leave me alone.

0:02:05.060,0:02:06.320
# 不是騎 看
We're not riding! We just watch.

0:02:06.840,0:02:08.080
# 我帶你去喝牛奶  去不去
Let's go to have some milk. Are you going with me?

0:02:08.480,0:02:09.600
# 那裡有牛奶的哦
There's milk, you know.

0:02:11.060,0:02:11.560
# 去不去
Are you going?

0:02:14.880,0:02:15.680
# 韋汝  過來
Come here, Weiru.

0:02:16.400,0:02:18.200
# 沒事的  跳下來
No worries! Just jump down the step!

0:02:18.480,0:02:19.680
# 我不敢跳
But I dare not.

0:02:21.120,0:02:22.940
# 怎麼不敢跳  你多少歲啦 (註︰「啦」有「已經有少了」的意思，不能譯，明示一下)
Why don't you dare? You're not a baby anymore. How old are you?

0:02:23.540,0:02:24.300
# 有五歲了
Already five

0:02:31.880,0:02:33.740
# 你看 這都是兄弟家的牛哦
Look! These are all my buddy's cattle.

0:02:34.880,0:02:36.280
# 這幾條  幾萬塊呀
These several here are worth tens of thousands of RMB.

0:02:37.560,0:02:38.580
# 現在牛肉貴
Beef is expensive these days.

0:02:40.160,0:02:42.300
# 我再去摘點金銀花 就摘了一點點金銀花
I'll go on with the honeysuckles. I've just picked a tiny little bit.

0:02:42.300,0:02:43.120
# 看到這個牛
I come to see the cattle,

0:02:43.320,0:02:44.880
# 那麼可愛就過來看一下
as I found that they're so cute.

0:02:45.240,0:02:45.740
# 走
Let's go!

0:02:46.160,0:02:46.660
# 繼續摘
Back to the honeysuckles

0:02:47.800,0:02:48.800
# 好漂亮嗎
Is it pretty?

0:02:48.800,0:02:50.040
# 你有這種顏色的花嗎
Do you have any flowers in this colour?

0:02:51.380,0:02:52.200
# 這個
This colour?

0:02:52.520,0:02:53.020
# 對啊
Yup!

0:02:55.480,0:02:56.540
# 這種哦
I mean this one.

0:02:56.540,0:02:57.820
# 我也有這種
Yes, I have this one too.

0:02:58.160,0:02:59.720
# 這種  我這個比你大
This one, mine is larger than yours.

0:03:01.800,0:03:02.740
# 這個好靚哦
It's really beautiful!

0:03:16.660,0:03:18.600
# 胡韋汝快點滴  別偷懶哦
Keep picking, Hu Weiru! Don't be a slacker!

0:03:19.500,0:03:21.000
# 等下我摘的我不給你哦
You're not gonna get your share if you don't work.

0:03:21.200,0:03:23.180
# 你看  這個好靚的哦  這種
Look! This is really beautiful, isn't it?

0:03:23.840,0:03:25.260
# 剛好變黃色的
They have just turned yellow.

0:03:27.660,0:03:28.960
# 變黃色才好吃
It tastes much better when it has turned yellow,

0:03:30.560,0:03:32.660
# 就快謝了  但是沒謝的那一種
the ones which are about to whither, but have not yet withered.

0:03:35.600,0:03:37.160
# 你看  摘金銀花的話  這個
Look! When you're picking the honeysuckles,

0:03:37.580,0:03:38.720
# 這種還沒開苞的
look for this kind of buds which have not yet blossomed,

0:03:39.180,0:03:41.360
# 或者這種白色的或變黃色了都可以摘
or this kind of white ones, or the yellow ones. All are fine.

0:03:41.760,0:03:42.420
# 這個就像
It's like,

0:03:43.280,0:03:44.820
# 小  小男孩一樣  這個
like a lit, little boy, this one.

0:03:45.100,0:03:45.980
# 這種就小男孩
This is a little boy.

0:03:46.260,0:03:47.300
# 這種就是青年
And this is a young man.

0:03:47.760,0:03:49.120
# 這種就是像我這種  嘖
And this is, just like me, I mean,

0:03:49.580,0:03:50.940
# 三十多歲的這種  這種
somebody in his thirties, this one.

0:03:52.580,0:03:53.160
# 不好看
It doesn't look good,

0:03:54.740,0:03:56.140
# 變黃色的那一種不好
I mean the yellow flowers.

0:04:03.840,0:04:05.280
# 哇  挺多的哦
Wa! Quite a lot!

0:04:06.240,0:04:07.920
# 今天一下午都摘了好多
We've already picked a lot in just an afternoon today.

0:04:17.880,0:04:19.080
# 好  差不多夠了
Alright! I think we should have enough now.

0:04:19.840,0:04:20.860
# 這裡有大袋啦
Here's a bag already.

0:04:22.360,0:04:24.120
# 裝  裝都裝不  裝都裝不下啦
We can't, we can't take, we can't take anymore.

0:04:26.940,0:04:28.260
# 不知道有沒有人摘的到  (註︰不太明白)
I wonder if anyone has picked them.

0:04:29.280,0:04:30.120
# 半斤啦
It's a quarter of kilogram here.

0:04:31.200,0:04:34.260
# 你看  這個要拿回去慢慢把它摘下來  摘下然後曬乾
Look! We need to bring them home and pick off the flowers one by one. They are then dried under the sun.

0:04:34.660,0:04:35.740
# 然後才可以泡茶
Only after that can we use the flowers to make tea.

0:04:37.280,0:04:38.140
# 嗯  我們先回去
Um! Let's go back first.

0:04:41.020,0:04:43.060
# 走 走走走  沒事  走
C'mon! Let's go, let's go. No worries. Keep going.

0:04:43.840,0:04:46.640
# 好像蟲子  回家啦  (註︰不明白甚麼像蟲子)
They look like bugs. Let's go home.

0:04:46.880,0:04:47.780
# 我都不怕
I don't even feel scared.

0:04:49.460,0:04:51.060
# 剛好攝影小哥的奶奶也在這裡
It just so happens that Mr. Cameraman's grandma is also here.

0:04:52.100,0:04:54.460
# 我們一起  一起摘  摘的快一點
Let's do it together, pick together. It's more efficient.

0:04:55.440,0:04:57.780
# 把它曬乾  就可以直接泡茶喝啦
Dry them under the sun, then we can use them to make tea right away.

0:05:00.040,0:05:00.660
# 摘花
We pick the flowers.

0:05:01.200,0:05:02.280
# 摘花
Pick flowers

0:05:02.420,0:05:02.920
# 對
Yea!

0:05:03.300,0:05:04.480
# 辣手催花  (註︰"deflower"有「破處」的意思，雖然有小孩在，但正是「辣手催花」的意思吧)
We deflower with our cruel hands.

0:05:04.480,0:05:04.980
# 是啊
Exactly!

0:05:05.880,0:05:08.100
# 它這是把這花丟到盆子裡面去
You know you have to throw the flowers into the pot.

0:05:09.940,0:05:10.640
# 小嘟嘟
Little Doo Doo

0:05:10.940,0:05:11.440
# 誒
Ey?

0:05:11.640,0:05:13.660
# 小嘟嘟  為甚麼你叫小嘟嘟  啊
Little Doo Doo. Why are you called Little Doo Doo, ah?

0:05:14.640,0:05:15.140
# 為甚麼
Why?

0:05:16.220,0:05:17.720
# 為甚麼你老爸叫你小嘟嘟
Why is your dad calling you Little Doo Doo?

0:05:18.040,0:05:20.180
# 因為這個就是我的小名字
Cuz this is my nickname.

0:05:20.180,0:05:21.100
# 你的小名字啊
You said it's your nickname?

0:05:22.240,0:05:23.460
# 我媽媽叫小嘟嘟
My mom is called Big Doo Doo.

0:05:23.760,0:05:24.860
# 哦  這樣啊
Oh! I see!

0:05:25.900,0:05:27.100
# 原來是有故事的
I didn't know that. There's a story.

0:05:28.640,0:05:29.140
# 是不是
Isn't it?

0:05:30.680,0:05:31.540
# 有甚麼故事
What is the story?

0:05:32.260,0:05:33.200
# 跟叔叔說一下
C'mon! Let uncle know the story.

0:05:34.560,0:05:35.880
# 哦  這樣啊
Oh! I see!

0:05:42.360,0:05:45.580
# 這個花已經摘好啦  在樓頂上曬幾天
So all the flowers are picked off. We're gonna dry them under the sun on the rooftop for a few days.

0:05:46.060,0:05:47.700
# 曬乾了  就用來泡茶
They can be used to make tea, after being dried.

0:05:48.140,0:05:49.820
# 幾天後
A few days later

0:05:50.120,0:05:52.680
# 你看  這金銀花曬乾了哦
Look! The honeysuckles have been dried.

0:05:53.680,0:05:55.340
# 摘點來泡茶喝一下
Let me take some and make some tea.

0:05:55.520,0:05:56.680
# 搞多點花來
I want a bit more flowers.

0:06:03.440,0:06:04.620
# 過一下水
Let me drain the water.

0:06:20.480,0:06:21.500
# 把蓋子蓋上
Cover it with the lid.

0:06:24.400,0:06:26.440
# 要等一下哦  味道還沒出來
We need to wait for a while. The flavour is still not there.

0:06:30.960,0:06:31.740
# 現在
Now...

0:06:33.920,0:06:34.920
# 等個幾分鐘
It takes a few minutes,

0:06:35.140,0:06:36.140
# 味道就出來啦
for the flavour to be released.

0:06:38.440,0:06:39.580
# 哇  可以了
Wa! It's alright now!

0:06:43.180,0:06:44.940
# 金黃色的液體
The golden yellow liquid,

0:06:46.520,0:06:47.340
# 就出來啦
is coming out.

0:06:48.380,0:06:48.940
# 嘗一下
Let me have a try.

0:06:54.120,0:06:54.620
# 嗯~
Um!

0:06:55.020,0:06:55.580
# 很香
It smells really good.

0:06:55.720,0:06:57.640
# 香[SIC](應該是「像」)那個花瓣  花的味道
It's like the fragrance of petals, I mean the flowers,

0:06:57.720,0:06:58.700
# 金銀花的味道
the honeysuckles.

0:07:02.020,0:07:02.760
# 可以喲
Not bad!

0:07:04.540,0:07:05.480
# 嘗一下
Have a try!

0:07:09.200,0:07:11.240
# 好啦  今天的視頻就到這裡啦
Alright! The video ends here.
