### ISSUE TITLE
[老饭骨] 干锅花菜- https://youtu.be/uomoUkMCGQQ

### ISSUE THREAD

**Issue by Laofangu** [immoonancient/YTSubtitles#988]
**视频链接**：https://youtu.be/uomoUkMCGQQ

抖音链接：https://v.douyin.com/wT1tqM 
YouTube 视频目前处于私享状态，请参照抖音视频

时长：4:08 发布时间：5月4日10:00PM

# 请翻译以下全部内容

```
标题（翻译主要意思即可，不要超过 100 个字符）
【国宴大师•干锅花菜】一个小技巧让干锅花菜成为菜花巅峰， 香脆入味，省事儿又好吃 |老饭骨

简介
小友们好，今天二伯这道干锅花菜估计有许多小友都喜欢吃，还不赶紧看看视频学起来？
二伯在视频里教了大家一个小诀窍，这个技巧可以让花菜更加脆、还更入味儿，而且下油锅的时候还不容易溅油，堪称整道菜的点睛之笔。究竟是什么小技巧呢？赶紧到视频里来寻找答案吧！
同时欢迎各位小友做出来以后到我们的Facebook交作业哦！

字幕
1
00:00:00,000 --> 00:00:02,160

2
00:00:02,160 --> 00:00:04,680
今天咱们教点省事儿又好吃的

3
00:00:04,680 --> 00:00:07,720
加点盐 为什么加点盐啊

4
00:00:07,720 --> 00:00:08,760
网友朋友们好多

5
00:00:08,760 --> 00:00:11,440
都喜欢这个菜  干锅花菜

6
00:00:11,440 --> 00:00:13,560
酒店基本不能焯水

7
00:00:13,560 --> 00:00:15,960
对 一焯水水煮了 成水煮菜了

8
00:00:15,960 --> 00:00:17,720
如果说我在家里边做

9
00:00:17,720 --> 00:00:20,360
你要这么多油太浪费了

10
00:00:20,360 --> 00:00:21,520
就不用这么着

11
00:00:21,520 --> 00:00:23,760
煸点肉片直接把这下去就行

12
00:00:23,760 --> 00:00:25,680
干煸了 在家就可以干煸

13
00:00:25,680 --> 00:00:29,560
这个菜花都洗干净弄完了 就怕水

14
00:00:29,560 --> 00:00:30,600
这个菜很简单

15
00:00:30,600 --> 00:00:33,200
这蒜一拍 你看齐活

16
00:00:33,200 --> 00:00:35,680
注意拍蒜 蒜可以大一点 拍蒜才有味

17
00:00:35,680 --> 00:00:38,960
稍微来点葱 五花肉

18
00:00:38,960 --> 00:00:40,960
来点小米辣 借点辣味

19
00:00:40,960 --> 00:00:43,960
别太碎了 太碎了它就不匹配了

20
00:00:43,960 --> 00:00:45,920
再来点绿的

21
00:00:45,920 --> 00:00:47,840
这小米辣很辣的 不要太多了

22
00:00:47,840 --> 00:00:50,440
在家里边根据自己的喜好

23
00:00:50,440 --> 00:00:52,240
接受辣的程度

24
00:00:52,240 --> 00:00:54,520
这点咱们就够了

25
00:00:54,520 --> 00:00:56,440
来点青蒜 提个味儿 够了

26
00:00:56,440 --> 00:00:59,920
突然发现师父现在会过了

27
00:00:59,920 --> 00:01:02,760
以前您不是教我们要 料要下的足

28
00:01:02,760 --> 00:01:04,560
你看这个刚才讲了

29
00:01:04,560 --> 00:01:07,120
在家里边直接煸就行了

30
00:01:07,120 --> 00:01:08,680
千万别煸烂了

31
00:01:08,680 --> 00:01:11,840
如果说你吃着有面感 这菜就失败了

32
00:01:11,840 --> 00:01:13,200
必须得脆的

33
00:01:13,200 --> 00:01:15,600
这个菜你说为什么加点盐

34
00:01:15,600 --> 00:01:17,640

35
00:01:17,640 --> 00:01:19,120
你看这个又不一样了

36
00:01:19,120 --> 00:01:20,880
你看加点盐 一个是入了味了

37
00:01:20,880 --> 00:01:24,400
再一个什么 更容易脆了 更脆了

38
00:01:24,400 --> 00:01:25,400
网友朋友们记住了

39
00:01:26,320 --> 00:01:28,760
师父就教我们小窍门

40
00:01:28,760 --> 00:01:30,440
而且你看下去盐之后

41
00:01:30,440 --> 00:01:31,720
它（过油的时候）还不容易崩

42
00:01:31,720 --> 00:01:33,400
后边儿的锅烧着呢

43
00:01:33,400 --> 00:01:35,720
咱们提前把工作预做一下

44
00:01:35,720 --> 00:01:38,120
兑点汁 根据菜花多少可以了

45
00:01:38,120 --> 00:01:40,720
蒸鱼豉油 这是一比一

46
00:01:40,720 --> 00:01:42,480
这到时候还用放盐什么的么

47
00:01:42,480 --> 00:01:44,120
不用放 什么都不用放

48
00:01:44,120 --> 00:01:45,640
本身这里边就已经有盐味了

49
00:01:45,640 --> 00:01:46,800
就这点东西就足够了

50
00:01:46,800 --> 00:01:48,320
酱油 蒸鱼豉油

51
00:01:48,320 --> 00:01:50,520
今天咱们教点省事儿的又好吃的

52
00:01:50,520 --> 00:01:52,120
这个油温还是不够

53
00:01:52,120 --> 00:01:55,400
油温高一点 得六成热

54
00:01:55,400 --> 00:01:57,720
下去的时候一炸就得了

55
00:01:57,720 --> 00:02:04,240

56
00:02:04,240 --> 00:02:07,200
我们把油都得控好了 你看这一下就得

57
00:02:07,200 --> 00:02:08,880

58
00:02:08,880 --> 00:02:12,480
咱们来点底油  把这肉片下去 五花肉

59
00:02:12,480 --> 00:02:13,960

60
00:02:13,960 --> 00:02:18,440
火热咱就撤 这叫控制火候

61
00:02:18,440 --> 00:02:20,680
依次下入蒜煸炒一会

62
00:02:20,680 --> 00:02:25,200
这蒜还可以多点 多点儿它香 金黄色

63
00:02:25,200 --> 00:02:28,960
再就小米辣 葱 这两个下去了

64
00:02:28,960 --> 00:02:31,360
这青蒜是不是最后再搁

65
00:02:31,360 --> 00:02:32,640

66
00:02:32,640 --> 00:02:34,640
香气辣气都出来了

67
00:02:34,640 --> 00:02:37,000
别死乞白赖的煸这就行了

68
00:02:37,000 --> 00:02:39,720
你看搁里边儿 汁儿

69
00:02:39,720 --> 00:02:43,520

70
00:02:43,520 --> 00:02:45,880
咱们顺着这锅边烹汁

71
00:02:45,880 --> 00:02:48,280

72
00:02:48,280 --> 00:02:51,680
你看这香气 锅气

73
00:02:51,680 --> 00:02:55,400
然后青蒜倒里边

74
00:02:55,400 --> 00:03:00,120

75
00:03:00,120 --> 00:03:01,760
行了 好嘞

76
00:03:01,760 --> 00:03:03,840
直接倒锅里了 滋啦滋啦的

77
00:03:03,840 --> 00:03:06,920

78
00:03:06,920 --> 00:03:08,840
看看干锅

79
00:03:08,840 --> 00:03:11,320

80
00:03:11,320 --> 00:03:12,880
这菜花多透亮是吧

81
00:03:12,880 --> 00:03:14,280

82
00:03:14,280 --> 00:03:18,840
您瞧这菜花 特别脆 刚刚好

83
00:03:18,840 --> 00:03:20,960
让你说的我这个不吃菜花的

84
00:03:20,960 --> 00:03:24,600
我都得尝尝菜花 特别脆

85
00:03:24,600 --> 00:03:29,800
而且鲜味香味锅气全出来了 真棒

86
00:03:29,800 --> 00:03:31,520
刚才你知道为什么要抖点儿盐吧

87
00:03:31,520 --> 00:03:34,640
不抖盐它就很难入味 特别入味

88
00:03:34,640 --> 00:03:38,640
网友朋友们一定要记住 非常清爽

89
00:03:38,640 --> 00:03:41,160
不要加那么多酱油 黑乎乎油乎乎

90
00:03:41,160 --> 00:03:43,040
很清爽但是很入味

91
00:03:43,040 --> 00:03:44,680
你看在传承当中

92
00:03:44,680 --> 00:03:47,240
有一个点的技巧就够了

93
00:03:47,240 --> 00:03:50,840
你看你搁了盐之后 一个是入味了吧

94
00:03:50,840 --> 00:03:52,760
再一个你往里下油的时候

95
00:03:52,760 --> 00:03:54,680
那么多水它不崩

96
00:03:54,680 --> 00:03:57,080
这窍门在这儿呢

97
00:03:57,080 --> 00:00:02,000

98
00:00:03,000 --> 00:00:05,000

```

**Comment by kyoiroi880** [comment]
认领

**Comment by kyoiroi880** [comment]
【国宴大师?干锅花菜】一个小技巧让干锅花菜成为菜花巅峰， 香脆入味，省事儿又好吃 |老饭骨
State Banquet Master Chef's dry pot cauliflower.Here's a tip to make dry pot cauliflower taste best.Delicious and crunchy,also simple and tasty.
简介
小友们好，今天二伯这道干锅花菜估计有许多小友都喜欢吃，还不赶紧看看视频学起来？
Hello my friends.This dry pot cauliflower cooked by Er Bai today may be welcomed by many friends.Let's  watch the video and learn immediately!  
二伯在视频里教了大家一个小诀窍，这个技巧可以让花菜更加脆、还更入味儿，而且下油锅的时候还不容易溅油，堪称整道菜的点睛之笔。究竟是什么小技巧呢？赶紧到视频里来寻找答案吧！
同时欢迎各位小友做出来以后到我们的Facebook交作业哦！
Er Bai taught us a tip to make cauliflower crunchier and tastier,and oil seldom spatters when the cauliflower is poured into the pot.It's really the soul of the dish.What is it?Let's find it out through the video.And welcome to upload your works to Fcaebook!
字幕
1
00:00:00,000 --> 00:00:02,160

2
00:00:02,160 --> 00:00:04,680
今天咱们教点省事儿又好吃的
Today we will teach you something both easy and delicious
3
00:00:04,680 --> 00:00:07,720
加点盐 为什么加点盐啊
Add some salt.   What for?
4
00:00:07,720 --> 00:00:08,760
网友朋友们好多
A number of netizens
5
00:00:08,760 --> 00:00:11,440
都喜欢这个菜  干锅花菜
Are fond of this dish, this dry pot cauliflower
6
00:00:11,440 --> 00:00:13,560
酒店基本不能焯水
It can't be blanched in a restaurant in most cases
7
00:00:13,560 --> 00:00:15,960
对 一焯水水煮了 成水煮菜了
Yes, once it is blanched, it turns into a stew
8
00:00:15,960 --> 00:00:17,720
如果说我在家里边做
It wastes too much oil
9
00:00:17,720 --> 00:00:20,360
你要这么多油太浪费了
if you cook like this at home
10
00:00:20,360 --> 00:00:21,520
就不用这么着
You needn't do it that way
11
00:00:21,520 --> 00:00:23,760
煸点肉片直接把这下去就行
Fry some sliced meat and then pour them into the pot
12
00:00:23,760 --> 00:00:25,680
干煸了 在家就可以干煸
That's dry-fry. We can do this at home
13
00:00:25,680 --> 00:00:29,560
这个菜花都洗干净弄完了 就怕水
The cauliflower is cleaned, it's afraid of water now
14
00:00:29,560 --> 00:00:30,600
这个菜很简单
This dish is easy to cook
15
00:00:30,600 --> 00:00:33,200
这蒜一拍 你看齐活
Flap the garlic, well done
16
00:00:33,200 --> 00:00:35,680
注意拍蒜 蒜可以大一点 拍蒜才有味
Pay attention to the garlic, the bigger the tastier
17
00:00:35,680 --> 00:00:38,960
稍微来点葱 五花肉
A bit of green onion, and then the pork belly
18
00:00:38,960 --> 00:00:40,960
来点小米辣 借点辣味
Some "Xiaomila" chili pepper to get spicier
19
00:00:40,960 --> 00:00:43,960
别太碎了 太碎了它就不匹配了
Don't slice it too small, or it won't match the size
20
00:00:43,960 --> 00:00:45,920
再来点绿的
Some more green onion 
21
00:00:45,920 --> 00:00:47,840
这小米辣很辣的 不要太多了
The "Xiaomila" chili pepper is so spicy that we just need a little
22
00:00:47,840 --> 00:00:50,440
在家里边根据自己的喜好
Add it according to your preferences at home
23
00:00:50,440 --> 00:00:52,240
接受辣的程度
According to your acceptance of pepper
24
00:00:52,240 --> 00:00:54,520
这点咱们就够了
Such is enough for us
25
00:00:54,520 --> 00:00:56,440
来点青蒜 提个味儿 够了
Add some green onion to improve the taste, ok it's enough
26
00:00:56,440 --> 00:00:59,920
突然发现师父现在会过了
I suddenly found master thriftier 
27
00:00:59,920 --> 00:01:02,760
以前您不是教我们要 料要下的足
You taught us to add plenty ingredients before, didn't you?
28
00:01:02,760 --> 00:01:04,560
你看这个刚才讲了
I've said just now
29
00:01:04,560 --> 00:01:07,120
在家里边直接煸就行了
At home,frying it directly is ok
30
00:01:07,120 --> 00:01:08,680
千万别煸烂了
But never fry it too tender
31
00:01:08,680 --> 00:01:11,840
如果说你吃着有面感 这菜就失败了
Once you feel it tender, it's considered a crappy dish
32
00:01:11,840 --> 00:01:13,200
必须得脆的
It must be crunchy
33
00:01:13,200 --> 00:01:15,600
这个菜你说为什么加点盐
Maybe now you know why we add some salt into the cauliflower before cooking
34
00:01:15,600 --> 00:01:17,640

35
00:01:17,640 --> 00:01:19,120
你看这个又不一样了
You see,there's a distinction between wether we add some salt first or not
36
00:01:19,120 --> 00:01:20,880
你看加点盐 一个是入了味了
That brings two benefits
37
00:01:20,880 --> 00:01:24,400
再一个什么 更容易脆了 更脆了
Tastier and crunchier
38
00:01:24,400 --> 00:01:25,400
网友朋友们记住了
Remember,my friends
39
00:01:26,320 --> 00:01:28,760
师父就教我们小窍门
That's the tip master wannna teaches us
40
00:01:28,760 --> 00:01:30,440
而且你看下去盐之后
Once you add the salt
41
00:01:30,440 --> 00:01:31,720
它（过油的时候）还不容易崩
Oil seldom spatters when the cauliflower is poured into the pot
42
00:01:31,720 --> 00:01:33,400
后边儿的锅烧着呢
The pot is getting hotter now
43
00:01:33,400 --> 00:01:35,720
咱们提前把工作预做一下
Let's do some penetration first
44
00:01:35,720 --> 00:01:38,120
兑点汁 根据菜花多少可以了
Adding some sauce according to the amount of cauliflower
45
00:01:38,120 --> 00:01:40,720
蒸鱼豉油 这是一比一
Seasoned soy sauce for seafood,1:1 to the sauce
46
00:01:40,720 --> 00:01:42,480
这到时候还用放盐什么的么
Shall we add some salt or something else then?
47
00:01:42,480 --> 00:01:44,120
不用放 什么都不用放
No, not any more
48
00:01:44,120 --> 00:01:45,640
本身这里边就已经有盐味了
It's already salty itself
49
00:01:45,640 --> 00:01:46,800
就这点东西就足够了
That's enough
50
00:01:46,800 --> 00:01:48,320
酱油 蒸鱼豉油
Sauce and seasoned soy sauce for seafood
51
00:01:48,320 --> 00:01:50,520
今天咱们教点省事儿的又好吃的
Today we will teach you something both easy and delicious
52
00:01:50,520 --> 00:01:52,120
这个油温还是不够
The oil temperature isn't high enough yet
53
00:01:52,120 --> 00:01:55,400
油温高一点 得六成热
It should be higher, about 180℃(60%heat)
54
00:01:55,400 --> 00:01:57,720
下去的时候一炸就得了
Just pour it into the pot and fry 
55
00:01:57,720 --> 00:02:04,240

56
00:02:04,240 --> 00:02:07,200
我们把油都得控好了 你看这一下就得
Wait until the spare oil is drained. Just one step
57
00:02:07,200 --> 00:02:08,880

58
00:02:08,880 --> 00:02:12,480
咱们来点底油  把这肉片下去 五花肉
Let's add some base oil and then pour the pork belly into the pot  
59
00:02:12,480 --> 00:02:13,960

60
00:02:13,960 --> 00:02:18,440
火热咱就撤 这叫控制火候
Controlling the cooking heat by taking away the pot as soon as it's hot enough
61
00:02:18,440 --> 00:02:20,680
依次下入蒜煸炒一会
Add the garlic sprouts and stir-fry for a while
62
00:02:20,680 --> 00:02:25,200
这蒜还可以多点 多点儿它香 金黄色
A little more garlic sprouts please, it gives the dish better taste and color 
63
00:02:25,200 --> 00:02:28,960
再就小米辣 葱 这两个下去了
Then we add the "Xiaomila" chili pepper and green onion
64
00:02:28,960 --> 00:02:31,360
这青蒜是不是最后再搁
Do we add the green onion in the end?
65
00:02:31,360 --> 00:02:32,640

66
00:02:32,640 --> 00:02:34,640
香气辣气都出来了
It smells good and spicy
67
00:02:34,640 --> 00:02:37,000
别死乞白赖的煸这就行了
Don't stir-fry too much, that's enough
68
00:02:37,000 --> 00:02:39,720
你看搁里边儿 汁儿
Then we add the sauce
69
00:02:39,720 --> 00:02:43,520

70
00:02:43,520 --> 00:02:45,880
咱们顺着这锅边烹汁
Pour it around the pot
71
00:02:45,880 --> 00:02:48,280

72
00:02:48,280 --> 00:02:51,680
你看这香气 锅气
Feel the aroma and steam
73
00:02:51,680 --> 00:02:55,400
然后青蒜倒里边
Then pour the green onion into the pot
74
00:02:55,400 --> 00:03:00,120

75
00:03:00,120 --> 00:03:01,760
行了 好嘞
Ok
76
00:03:01,760 --> 00:03:03,840
直接倒锅里了 滋啦滋啦的
Pour it into the pot directly, sizzling
77
00:03:03,840 --> 00:03:06,920

78
00:03:06,920 --> 00:03:08,840
看看干锅
Look at this dish
79
00:03:08,840 --> 00:03:11,320

80
00:03:11,320 --> 00:03:12,880
这菜花多透亮是吧
So bright, isn't it?
81
00:03:12,880 --> 00:03:14,280

82
00:03:14,280 --> 00:03:18,840
您瞧这菜花 特别脆 刚刚好
You see this cauliflower, it tastes very crunchy,just right
83
00:03:18,840 --> 00:03:20,960
让你说的我这个不吃菜花的
I can't help trying this cauliflower even if I hated it before
84
00:03:20,960 --> 00:03:24,600
我都得尝尝菜花 特别脆
So crunchy
85
00:03:24,600 --> 00:03:29,800
而且鲜味香味锅气全出来了 真棒
The savory taste and aroma are circulated. Excellent.
86
00:03:29,800 --> 00:03:31,520
刚才你知道为什么要抖点儿盐吧
Now you know why I added some salt just now
87
00:03:31,520 --> 00:03:34,640
不抖盐它就很难入味 特别入味
It's hard to be tasty if you don't do that. Now it's particularly tasty.
88
00:03:34,640 --> 00:03:38,640
网友朋友们一定要记住 非常清爽
Remember that my friends, and it can be very refreshing
89
00:03:38,640 --> 00:03:41,160
不要加那么多酱油 黑乎乎油乎乎
Don't add too much soy sauce, or the dish will be dark and greasy
90
00:03:41,160 --> 00:03:43,040
很清爽但是很入味
Now it's refreshing and tasty
91
00:03:43,040 --> 00:03:44,680
你看在传承当中
You see, one tip is enough	
92
00:03:44,680 --> 00:03:47,240
有一个点的技巧就够了
in the process of inheritance
93
00:03:47,240 --> 00:03:50,840
你看你搁了盐之后 一个是入味了吧
Once you add the salt first, it promotes the taste
94
00:03:50,840 --> 00:03:52,760
再一个你往里下油的时候
Meanwhile, oil seldom spatters when the cauliflower is poured into the pot
95
00:03:52,760 --> 00:03:54,680
那么多水它不崩
Even if the cauliflower is covered with water 
96
00:03:54,680 --> 00:03:57,080
这窍门在这儿呢
That is the tip
97
00:03:57,080 --> 00:00:02,000

98
00:00:03,000 --> 00:00:05,000
